### ISSUE TITLE
Some documentation

### ISSUE THREAD

**Issue by devmondo** [AngleSharp/AngleSharp#1]
Hi, 

this project looks awesome, would you kindly add some documentation on usage.

thanks in advanced.

**Comment by FlorianRappl** [comment]
Thanks for your feedback and request. I am currently busy writing a CodeProject article about the project, which should be released within this week. For the article I will provide some sample projects and documentation, which will then be also available here.

**Comment by devmondo** [comment]
awesome, thank you

**Comment by FlorianRappl** [comment]
The CodeProject article is now available:
http://www.codeproject.com/Articles/609053/AngleSharp
Additionally I've put some samples in the repo and I will start a wiki soon.

**Comment by devmondo** [comment]
thank you very much

**Comment by FlorianRappl** [comment]
I've started writing some documentation in the provided GitHub wiki. More examples, code and explanations to come.

**Comment by devmondo** [comment]
awesome, you are the man :)
