### ISSUE TITLE
Escaped quotes in attribute not being parsed correctly

### ISSUE THREAD

**Issue by jsultana-leap** [AngleSharp/AngleSharp#1000]
# Bug Report

## Prerequisites

- [ X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ X] Are you running the latest version of AngleSharp?
- [ X] Did you check the FAQs to see if that helps you?
- [ X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [ X] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

AngleSharp.Core (specifically the HtmlTokenizer) falls over when dealing with escaped double quotes in an attribute. Every space in the attribute ends up parsed as an entirely distinct attribute. Eg: Given the input string `"<img alt=\"My code is awesome\" />"`, this produces 4 attributes: "alt="\"My", "code=", "is=", "awesome".

This probably doesn't come up too often if working with HTML directly. My particular use case is using the `HtmlSanitizer` package (which uses AngleSharp internally) to sanitise a JSON string that contains HTML, so the HTML has its quotes escaped. Eg:

```
{
    "content": "<img alt=\"My code is awesome\" />"
}
```

## Steps to Reproduce

Add the following (failing) test to `Tricky.cs`:

```
        [Test]
        public void EscapedQuotes()
        {
            var doc = ("<img alt=\\\"My code is awesome!\\\" />").ToHtmlDocument();
            var docHtml = doc.ChildNodes[0] as Element;
            var docHtmlHead = docHtml.ChildNodes[0] as Element;
            var docHtmlBody = docHtml.ChildNodes[1] as Element;
            var img = docHtmlBody.ChildNodes[0] as Element;

            // There should only be one attribute on the img

            var attributes = img.Attributes.Select(attr => new
            {
                attr.Name,
                attr.Value
            })
            .ToArray();

            Console.WriteLine("Attributes: ", string.Join(",", img.Attributes.Select(attr => $"{attr.Name}:{attr.Value}")));

            Assert.AreEqual(1, img.Attributes.Length, "There should be one attribute on the img");
            Assert.AreEqual("My code is awesome!", img.Attributes[0].Value);
        }
```

**Expected behavior:** Escaped double quotes (i.e: \") are treated as normal double quotes (i.e: ").

**Actual behavior:** Escaped double quotes seem to be parsed as attribute content, meaning that a following space is treated as a whole new attribute.

**Environment details:** Windows 10, cloned this repo and added a test to `Tricky.cs`.

## Possible Solution

In `HtmlTokenizer::ParseAttributes`, instead of comparing `c` to `Symbols.DoubleQuote`, use a comparison helper function that compares it to either `Symbols.DoubleQuote` OR a backslash and double quote. This will require the ability to inspect the next character in the file though, which doesn't seem like it's supported currently.

**Comment by FlorianRappl** [comment]
Your expected behavior collides with the spec.

Look what Chrome does:

![grafik](https://user-images.githubusercontent.com/1766191/135536172-bee42bf9-0e5e-4f1f-bf62-59b1af2b50e8.png)

AngleSharp does the same. Please first check with the browser of your choice to verify your knowledge of HTML - thanks!
