### ISSUE TITLE
Mutation Observer throws when connecting to a document

### ISSUE THREAD

**Issue by hahn-kev** [AngleSharp/AngleSharp#1001]
# Bug Report

## Prerequisites

- [y] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [y] Are you running the latest version of AngleSharp?
- [y] Did you check the FAQs to see if that helps you?
- [y] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [y] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

I'm trying to use a mutation observer to watch an entire document. Unfortunately when I try to do that I get a null reference exception.

## Steps to Reproduce

```C#
var document = ... //from somewhere
var observer = new MutationObserver((mutations, observer) => {});
observer.Connect(document);
```

**Expected behavior:**
no exception should be thrown

**Actual behavior:** 
a null reference exception was thrown when the connect method tries to access the document owner which is always null

**Environment details:** 
Windows
.NET 5

## Possible Solution

In this file: https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Dom/MutationObserver.cs#L221
the following line in the issue
```C#
node.Owner.Mutations.Register(this);
```
the problem is that a document always returns null for it's owner. I see 2 ways to fix this, the first is to change the document so returns itself as it's owner. The other way would be to refactor this line to check if the node is a document and if it is then just use the Mutations Property directly. Something like this
```C#
if (node is Document d)
    d.Mutations.Register(this);
else
    node.Owner.Mutations.Register(this);
```

**Comment by FlorianRappl** [comment]
Well, maybe we should throw a different exception, but what you do is invalid anyway. If you try that in the browser you get:

> Uncaught TypeError: MutationObserver.observe: One of 'childList', 'attributes', 'characterData' must not be false.

So you cannot observe a document. If you want to observe the full document use `document.DocumentElement`

**Comment by hahn-kev** [comment]
Thanks, it looks like using `document.DocumentElement` solved my problem. Maybe that should be the solution if the document is passed in instead?

**Comment by FlorianRappl** [comment]
> Maybe that should be the solution if the document is passed in instead?

I am not sure if I just miscommunicated my message. What you want to have (passing in `document`) is forbidden by [spec](https://dom.spec.whatwg.org/#interface-mutationobserver). We cannot change the spec.

**Comment by hahn-kev** [comment]
Ok, thanks for clarifying my bad I was confused because the Document type is considered a Node in AnguleSharp, so I assumed it should work considered the method accepts Nodes. 

If not that's fine, an error message telling you to use DocumentElement instead would be great.

**Comment by FlorianRappl** [comment]
Hm maybe you missed my earlier message. This is what you get in the browser:

> Uncaught TypeError: MutationObserver.observe: One of 'childList', 'attributes', 'characterData' must not be false.

So that's also an exception although a slightly different type. The error message cannot tell you that you should use `DocumentElement` instead as it cannot know that this is your intention. It can only tell you that the provided value is not supported.

This is what I wrote:

> Well, maybe we should throw a different exception, but what you do is invalid anyway.

I already proposed to spit out a different exception close to the one from most browsers.

Update: A document is a node, not only in AngleSharp but in every browser. However, just because the argument has to be a node does not mean that every node is accepted. See [step 3 of the algorithm](https://dom.spec.whatwg.org/#dom-mutationobserver-observe).

**Comment by hahn-kev** [comment]
I'm sorry, I think my example was incorrect, instead of this: 
`observer.Connect(document);` it should have been this `observer.Connect(document, true);` so I wouldn't get an error about any of those settings being false.

I did a little testing (in Firefox and Chrome) and it seems perfectly happy to observe the document without any errors. If you want to test it out copy this into your browser console and modify something in the html.
```js
// Options for the observer (which mutations to observe)
const config = { attributes: true, childList: true, subtree: true };

// Callback function to execute when mutations are observed
const callback = function(mutationsList, observer) {
    // Use traditional 'for loops' for IE 11
    for(const mutation of mutationsList) {
        if (mutation.type === 'childList') {
            console.log('A child node has been added or removed.');
        }
        else if (mutation.type === 'attributes') {
            console.log('The ' + mutation.attributeName + ' attribute was modified.');
        }
    }
};

// Create an observer instance linked to the callback function
const observer = new MutationObserver(callback);

// Start observing the target node for configured mutations
observer.observe(document, config);
```

Like you said a document is a node, in AngleSharp and the browser, there's just a minor detail in AngleSharp that seems to prevent it from working currently. As for step 3 of the algorithm I don't see what this has to do with a document not being accepted.

**Comment by FlorianRappl** [comment]
Fix released in preview https://www.nuget.org/packages/AngleSharp/0.16.1-alpha-120.

**Comment by hahn-kev** [comment]
I'm sorry, my example was incorrect and so it was misleading about the error I'm seeing, instead of this: 
`observer.Connect(document);` it should have been this `observer.Connect(document, true);` so I wouldn't get an error about any of those settings being false.

I did a little testing (in Firefox and Chrome) and it seems perfectly happy to observe the document without any errors. If you want to test it out copy this into your browser console and modify something in the html.
```js
// Options for the observer (which mutations to observe)
const config = { attributes: true, childList: true, subtree: true };

// Callback function to execute when mutations are observed
const callback = function(mutationsList, observer) {
    // Use traditional 'for loops' for IE 11
    for(const mutation of mutationsList) {
        if (mutation.type === 'childList') {
            console.log('A child node has been added or removed.');
        }
        else if (mutation.type === 'attributes') {
            console.log('The ' + mutation.attributeName + ' attribute was modified.');
        }
    }
};

// Create an observer instance linked to the callback function
const observer = new MutationObserver(callback);

// Start observing the target node for configured mutations
observer.observe(document, config);
```

Like you said a document is a node, in AngleSharp and the browser, there's just a minor detail in AngleSharp that seems to prevent it from working currently. As for step 3 of the algorithm I don't see what this has to do with a document not being accepted.
