### ISSUE TITLE
Accept Header cannot changed in default loader

### ISSUE THREAD

**Issue by LelandGrunt** [AngleSharp/AngleSharp#1003]
Hello,

Maybe I found a bug within the default loader.
Please confirm.
Thank you!

With version 0.14 the Accept header with value "text/html" was added to the default loader.
See also https://github.com/AngleSharp/AngleSharp/issues/859 and https://github.com/AngleSharp/AngleSharp/commit/c0b922db9a8760c64cdf2b4eb72be5c4260d08e1.
In my case this results in a different HTML response.

I tried to remove and to change the Accept header from the default loader, but based on Fiddler the header is still there or still contains the "text/html" value.

This is what I tried:
```
string url = "https://finance.yahoo.com/quote/MSFT";
string cssSelector = ".Fz\\(36px\\)";

var htmlRequester = new DefaultHttpRequester();
/* // Trial #1
   htmlRequester.Headers["Accept"] = "application/xhtml+xml,application/xml";
   IConfiguration configuration = Configuration.Default.With(htmlRequester).WithDefaultLoader(); */
/* // Trial #2
   htmlRequester.Headers.Remove("Accept");
   IConfiguration configuration = Configuration.Default.With(htmlRequester).WithDefaultLoader(); */
// Trial #3
IConfiguration configuration = Configuration.Default.WithDefaultLoader().Without<DefaultHttpRequester>();
configuration = configuration.With(htmlRequester);
IBrowsingContext browsingContext = BrowsingContext.New(configuration);
Task<IDocument> document = browsingContext.OpenAsync(url);
IElement element = document.Result.DocumentElement.QuerySelector(cssSelector);
```

Regards,
Leland

**Comment by FlorianRappl** [comment]
You are creating new instances and then forget about them, but expect that your instance-based value somehow ends up in a new instance. This is not how it works (generally, not constraint to AngleSharp).

In AngleSharp I'd recommend using a filter to change the request before its actually submitted.

Example: 

```cs
async Task Main()
{
	var config = Configuration.Default.WithDefaultLoader(new LoaderOptions
	{
	 	Filter = (req) => {
			req.Headers["Accept"] = "application/json";
			return true;
		}
	});
	var document = await BrowsingContext.New(config).OpenAsync("https://feed.piral.cloud/api/v1/pilet/sample");
	document.ToHtml().Dump();
}
```

Note: The `Filter` can also be used to reject certain requests at all. In this case we use it to not reject anything and give *all* requests a certain `Accept` header.
