### ISSUE TITLE
IElement.Insert() strips &zwnj;

### ISSUE THREAD

**Issue by utillity** [AngleSharp/AngleSharp#1004]
# Bug Report

## Description

the zero-width-non-joiner is removed by AngleSharp, when using IElement.Insert(). (using AngleSharp 0.16.0)

## Steps to Reproduce

`heading.Insert(AdjacentPosition.AfterBegin, $"<a name=\"{entry.Id}\">&zwnj;</a>");`

**Expected behavior:**
I expect the html to be inserted as set. (ie. `<a name="234">&zwnj;</a>`)

**Actual behavior:**
In the string returned from ie. .InnerHtml the `&zwnj;` is removed (ie. `<a name="234"></a>`). If I replace it with `&nbsp;` that is not removed.

**Environment details:**
Windows 10, .Net5 (core)

**Comment by FlorianRappl** [comment]
Hm can you specify what you mean by "removed"? Because this entity is supposed to "disappear" in normal rendering (hence the "zero-width").

**Comment by utillity** [comment]
I mean in the resulting string the `&zwnj;` is gone - so the result looks like this: `<a name="234"></a>`, but it should look like this: `<a name="234">&zwnj;</a>`

**Comment by FlorianRappl** [comment]
This is not how it works. Entities are always replaced with their character representations. There are only some exclusions, see the formatter (https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Html/HtmlMarkupFormatter.cs#L162).

**Comment by utillity** [comment]
then there should be a unicode symbol between the `>` and the `</a>`, but I don't see that either. `&nbsp;` is untouched, for instance.

**Comment by utillity** [comment]
so maybe this should also be added to the exclusions? Why do you replace these explicitly specified entities?

**Comment by FlorianRappl** [comment]
> Why do you replace these explicitly specified entities?

By spec. There is a serialization spec and those entities are actually required to form valid HTML (you can see that specifically using the angle-brackets itself, which would otherwise form invalid code).

> `&nbsp;` is untouched, for instance.

This is wrong. It is replaced like anything else.

In order to see that the entity is properly treated:

```cs
var config = Configuration.Default;
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(res => res.Content("<div>&zwnj;</div>"));
document.Body.Children[0].InnerHtml.Length.Dump(); // 1 -> the character representation of &zwnj;
```

Also see wikipedia:

> The ZWNJ is encoded in Unicode as U+200C ZERO WIDTH NON-JOINER (HTML `&#8204; · &zwnj;`). 

So if you do:

```cs
((int)document.Body.Children[0].InnerHtml[0]).Dump(); // 8204
```

you confirm that everything is as it should be.

**Comment by utillity** [comment]
awesome! Thanks for the clarification!
