### ISSUE TITLE
Can I customize HtmlEncode?

### ISSUE THREAD

**Issue by tsu1980** [AngleSharp/AngleSharp#1005]
[This is a feature request]

I want to customize [HtmlEncode()](https://github.com/AngleSharp/AngleSharp/blob/0bee862e8aa61fe3ace84068113d2e97a77beb32/src/AngleSharp/Text/StringExtensions.cs#L628).

In my case, the encoding of the HTML document is `shift_jis` and I am trying to send the character `~` (U+301C) which cannot be converted to `shift_jis`.
Currently, the string sent is `?` in the current situation. I would like to replace `~`(U+301C) with `&#12316;` in HtmlEncode().

Original string:
```
〜
```

ShiftJIS encoded string(current):
```
?
```

ShiftJIS encoded string(using HTML character entity reference):
```
&#12316;
```

If we can inject `IHtmlEncoderService`, it would be very helpful.

**Comment by FlorianRappl** [comment]
Sounds reasonable to me.

Do you want to try making a PR?
