### ISSUE TITLE
Couldn't get any scraped content for this URL

### ISSUE THREAD

**Issue by LasanthaKathriarachchi** [AngleSharp/AngleSharp#1007]
Hi Guys,

I wanted to use AngleSharp to scrape the page text content of some pages.
It worked for most of the pages.
But I found these 2 URLs, those not return any text content.

https://crawlq.ai
https://crawlq.ai/pricing

Please have a look..
Let me know if found the reason..

Thanks...

**Comment by FlorianRappl** [comment]
Sorry, we cannot handle such individual responses as the time is limited. Potentially, these pages are SPAs and use JS to render their content.

Hope that helps!
