### ISSUE TITLE
Add .NET 6 as a target framework

### ISSUE THREAD

**Issue by silkfire** [AngleSharp/AngleSharp#1010]
# Add .NET 6 as a target framework

## Description

I believe that as a modern library, AngleSharp should target the current and latest LTS release of .NET, i.e. the recently released **.NET 6**, in addition to the frameworks it already targets.
This would also eliminate the need to reference the NuGet package `System.Buffers`, which became part of the framework since .NET 5.

PR submitted: https://github.com/AngleSharp/AngleSharp/pull/1011

**Comment by FlorianRappl** [comment]
Landed in preview.
