### ISSUE TITLE
Problem with margin CssText output

### ISSUE THREAD

**Issue by D92130** [AngleSharp/AngleSharp#102]
For a centered style definition:

```
        var snippet = ".centered {margin:0;margin-left:auto;margin-right:auto;text-align:left;}";
        var result = CssParser.ParseRule(snippet);
        var cssText = result.CssText;
```

Then output of cssText is actually:  .centered { margin: 0 0 auto auto; text-align: left; }
The output is actually changed to a "right aligned" definition.
The expected result should be something like: .centered { margin: 0 auto 0 auto; text-align: left; }

**Comment by FlorianRappl** [comment]
I will definitely fix this in the upcoming version. Thanks for noticing!

**Comment by D92130** [comment]
Just want to point out that this is a general problem for shorthand css text output. Other properties like "padding", "border" all have the same issue.

**Comment by FlorianRappl** [comment]
They are all using the same converter - hence this fix applies to them all.

**Comment by FlorianRappl** [comment]
(Also I wanted to point out that this code will improve in the next version anyway; it is an evil hack that works in nearly all cases unless the longhand is a border-radius-\* declaration. But I have it on my radar.)
