### ISSUE TITLE
Reflect code conventions in .editorconfig.

### ISSUE THREAD

**Issue by kzrnm** [AngleSharp/AngleSharp#1025]
# New Feature Proposal

## Description

This project has [Code Conventions](https://github.com/AngleSharp/AngleSharp/blob/devel/.github/CONTRIBUTING.md#code-conventions), but the editorconfig doesn't reflect those conventions.

I think it's better to reflect it in .editorconfig.

## Specification

```
[*.cs]
dotnet_style_predefined_type_for_member_access = false:suggestion
dotnet_style_predefined_type_for_locals_parameters_members = false:suggestion

csharp_prefer_braces = true:suggestion

csharp_using_directive_placement = inside_namespace:suggestion

csharp_style_var_for_built_in_types=true:suggestion
csharp_style_var_when_type_is_apparent=true:suggestion
```

### Additional options

- Run `dotnet format`

**Comment by FlorianRappl** [comment]
Landed in `devel` - thanks for the suggestion!
