### ISSUE TITLE
The Parse method is missing

### ISSUE THREAD

**Issue by pazicb** [AngleSharp/AngleSharp#1027]
Hello,
I found the code
```
var fragment = "<script>deane</script><div>deane</div>";
var p = new HtmlParser();
var dom = p.Parse("<html><body></body></html>");
var nodes = p.ParseFragment(fragment, dom.Body);
```
I would need to use this. Unfortunately, the Parse method does not exist in .NET 4.8.
Can you please advise me how to proceed?

**Comment by FlorianRappl** [comment]
Hm where did you find this? Why is it a bug? The method is called `ParseDocument`.
