### ISSUE TITLE
Add option to XhtmlMarkupFormatter for not to make empty elements self-closing

### ISSUE THREAD

**Issue by Aizeren** [AngleSharp/AngleSharp#1029]
# New Feature Proposal

## Description

Add an option `emptyTagsToSelfClosing` to XhtmlMarkupFormatter so that a user can choose whether he wants to format empty elements to self-closing or not.

## Background

It would be helpful for HTML compatibility. In HTML5 self-closing elements are considered as just opening tags which can cause layout issues.

**Comment by Aizeren** [comment]
Looks like I cannot self-assign the issue, but I will take it

**Comment by FlorianRappl** [comment]
> Looks like I cannot self-assign the issue, but I will take it

Sounds good to me! I'll assign it to you.

> In HTML5 self-closing elements are considered as just opening tags which can cause layout issues.

Well, if you care about compatibility, then I'd argue choosing the XHTML markup formatter is not the right choice. But adding the option does not hurt either way.

**Comment by Aizeren** [comment]
> choosing the XHTML markup formatter is not the right choice.

Sometimes there is not much choice :(
