### ISSUE TITLE
tagnames

### ISSUE THREAD

**Issue by xp44mm** [AngleSharp/AngleSharp#1032]
https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Dom/TagNames.cs
Tag names seem incomplete or outdated, send a link for reference.

https://github.com/wooorm/mathml-tag-names
https://github.com/wooorm/html-tag-names
https://github.com/wooorm/svg-tag-names

You don't have to install him as said in readme.md, you just need to look directly at the `index.js`.

**Comment by FlorianRappl** [comment]
I think you missed the purpose of that file. As those tags are specifically handled in the HTML parser. All other tags are either implicit or play no direct role (e.g., MathML or SVG).

Please take a look at the bug report template before posting a bug: https://github.com/AngleSharp/AngleSharp/blob/devel/.github/ISSUE_TEMPLATE/bug_report.md
