### ISSUE TITLE
Downloading Zip from HP will detect the virus. 

### ISSUE THREAD

**Issue by gtk2k** [AngleSharp/AngleSharp#1033]
Trojan: Script / Ulthar.A! ml

**Comment by FlorianRappl** [comment]
Note sure here, the link goes directly to GitHub:

https://github.com/AngleSharp/AngleSharp/archive/master.zip

(and this is just a snapshot of the previous `master` branch, which, indeed, could be changed to `main` - but is valid as is)

If what you say is true its either GitHub or your network that has been compromised. The likelihood that your network has been compromised is higher I'd say.
