### ISSUE TITLE
File within Repo getting flagged by Defender ATP for malware

### ISSUE THREAD

**Issue by MrSecuRED** [AngleSharp/AngleSharp#1034]
The file Heisenberg.Bug.txt is being flagged by Microsoft ATP as a few variations of malware. It looks like it's some sort of malicious email that's saved as a .txt file. 

The file path: \AngleSharp-main\AngleSharp-main\src\AngleSharp.Core.Tests\Html\Heisenberg.bug.txt

Although this doesn't seem inherently malicious, I have to question why it's included in the first place. I'll say I'm not familiar with this project, I just came across is when my security dashboard starting lighting up when a user downloaded the zip

**Comment by FlorianRappl** [comment]
Its a test (well I guess from the path you might have guessed). It's the raw input - and yes, that's apparently something that should not crash the parser. See #893 for details.

**Comment by heinrich-ulbricht** [comment]
Just as a note: ClamAV flags `Heisenberg.Bug.txt` as Win.Worm.Allaple-318

**Comment by FlorianRappl** [comment]
> Just as a note: ClamAV flags Heisenberg.Bug.txt as Win.Worm.Allaple-318

Yeah - please address that with ClamAV as its obviously a false-positive.
