### ISSUE TITLE
 Query is not included in Href propery of IHtmlAnchorElement

### ISSUE THREAD

**Issue by vastar** [AngleSharp/AngleSharp#1037]
Query part of the URL is not included in the result string when getting Href propery of IHtmlAnchorElement if the attribute is empty `href=''` or has a link to an element on the same page `href='#section1'` `href='#'`. Browsers include query when clicking on such links.

Example:
```
var ctx = BrowsingContext.New();
var url = "https://example.com/path?query=value";
var content = "<a href='#section1'></a>";
var document = await ctx.OpenAsync(x => x.Address(url).Content(content));
var a = document.QuerySelector<IHtmlAnchorElement>("a");
Debug.Assert(a.Href == "https://example.com/path?query=value#section1");
```

For now `a.Href` equals `"https://example.com/path#section1"` in this scenario

**Comment by FlorianRappl** [comment]
Landed in `devel`
