### ISSUE TITLE
Request is considered done, when data is downloaded instead when data is processed

### ISSUE THREAD

**Issue by ossaltu** [AngleSharp/AngleSharp#104]
Here is the example

```
var html = @"<html>
  <head>
     <title>test title</title>
     <link href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css' rel='stylesheet'>
    </head>
    <body>
    </body>
</html>";

var config = new Configuration().WithDefaultLoader(l => l.IsResourceLoadingEnabled = true).WithCss();
var loaded = await BrowsingContext.New(config).OpenAsync(m => m.Content(html));
await Task.WhenAll(loaded.Requests);
Console.WriteLine(loaded.StyleSheets.Count()); // outputs 0, sometimes might be 1
await Task.Delay(5000);
Console.WriteLine(loaded.StyleSheets.Count()); // outputs 1
```

The problem is that css is parsed after 

```
await Task.WhenAll(loaded.Requests);
```

and there is no way to figure out when document is actualy ready.

**Comment by FlorianRappl** [comment]
Hm, how to do you want it to be changed? Obviously the name is requests, and not "tasks" or something more generic. It is really about the requests. I could, maybe, abstract the provided tasks more and have like an internal statemachine. But then the code just keeps on growing and I am heavily thinking about splitting up the library already (http://www.florian-rappl.de/News/Page/299/anglesharp-future-plans).

What is your proposal?

**Comment by ossaltu** [comment]
Since downloaded data is useless untill it is interpreted, there is no big point to split request and processing tasks in api level: I can't find a scenario in scope of AngleSharp where you would need get request result without it's parsing - if you want to do this you don't need AngleSharp, HttpClient would work :)
It would seem fine to me to include data downloading and processing under single term of "request", but if you think that this is too ambiguous, "ChildTasks" may work.

**Comment by FlorianRappl** [comment]
I disagree. I had many requests (pun intended) to measure resource loading times and make it as fine grained as possible. Of course in your application domain you do not care about the request, but only about the result of a request. So let's try to figure out a solution that remains fine grained, but allows you to focus on specifics as well.

I therefore propose the following: The current `Requests` will remain unchanged, however, I'll add the missing `load` event to the `HtmlLinkElement` and you can then just await that. That way you will also know the specific `IHtmlLinkElement` instance.

**Comment by ossaltu** [comment]
It is ok to have load event in HtmlLinkElement, but we still need an easy way to continue code execution after document is fully loaded (this should be really common scenario). So, in addition, I propose to have separate "ChildTasks" property in document which would include all tasks executed during loading.

**Comment by FlorianRappl** [comment]
I will provide an extension method that collects for things you are interested (its just a 1-liner and you could easily write it yourself - you already have `AwaitEvent` etc.). It will look similar to

```
await document.AwaitLoadingAll<IHtmlLinkElement>();
```

For a specific element you can already do

```
await element.AwaitEvent("load");
```

which will also work for the `HtmlLinkElement` once the event is implemented / triggered.

**Comment by ossaltu** [comment]
Still there is a bug:

```
var html = @"<html>
                    <head>
                        <title>test title</title>
                        <link href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css' rel='stylesheet'>
                    </head>
                    <body>
                    </body>
                </html>";

            var config = new Configuration().WithDefaultLoader(l => l.IsResourceLoadingEnabled = true).WithCss();
            var loaded = await BrowsingContext.New(config).OpenAsync(m => m.Content(html));
            await Task.Delay(2000);
            await loaded.WhenLoadFired<IHtmlLinkElement>();
```

await loaded.WhenLoadFired<IHtmlLinkElement>(); never returns, because link is already loaded before calling it.

PS: some thoughts to consider: current solution seems to be too counter-intuitive. Maybe it would be possible to expose Task Load() method for loadable elements (links, images, iframes, etc.), so that one could select manualy elements that need to be loaded and await when loading tasks will be done.

**Comment by FlorianRappl** [comment]
Of course - awaiting an event that is not fired will always wait. The same is true with the (underlying) `AwaitEvent` - so there is no bug. Also the documentation states this. It is, as said, only a helper. 

If you want to be sure in your code - then make sure by getting the specific `link` element, checking if the sheet has been loaded yet and if not - await loading.

**Comment by ossaltu** [comment]
No bug because of inner workings and because it is documented? :) You sound like Microsoft, maybe worked there for a while? :)
To be seriuous, by calling WhenLoadFired<IHtmlLinkElement>() right after OpenAsync you cannot be sure if it will exit or not, sometimes it exits, sometimes it doesn't, depending on how fast link contents are loaded. Sounds like a bug to me :) If this is not fixable, the helper itself is useless and there is no point of having it in api.

By the way, checking if link is loaded and then awaiting it's task is just decreasing the problem, not solving it: what would happen, if style is loaded between the check if it is loaded and awaiting the task? The task will not return...

To remind you the whole point of this: I need a way to figure out when document with it's resources is loaded, so that document examination could be continued.

**Comment by FlorianRappl** [comment]
Sounds like somebody who complains about "a bug" in floating point arithmetics when he looks at 0.1 + 0.1 + 0.1.

Nevertheless all you need for your scenario is already available ... The `load` event was the only missing thing prior to that issue.

**Comment by merthsoft** [comment]
> If you want to be sure in your code - then make sure by getting the specific link element, checking if the sheet has been loaded yet and if not - await loading.

I can't seem to find such methods on the IHtmlLinkElement to check if it's loaded and await if it's not. Can you give an example of how I'd do that?

**Comment by FlorianRappl** [comment]
The `IDocument` has a property called `Requests`. However, I will most probably remove this property in one of the next versions. It will be replaced by a more powerful (yet reliable) way, which lets you access all (past + current) requests (not only limited to their tasks, but with full information, i.e., request, response, status, ...).

The await loading mechanism is using `AwaitEvent("load")`. This will give you a task that fires once the `load` event has been triggered. Please note that I do not advise using the mechanism with `load`, since the event may not be fired in some cases (error while loading, problem with Internet connection, has already been fired, ...). If you use it, make sure to check first if a stylesheet has been loaded, and then use it similar to the following code:

``` cs
// ...
var loadTask = link.AwaitEvent("load");
var errorTask = link.AwaitEvent("error");
await Task.WhenAny(loadTask, errorTask);
```
