### ISSUE TITLE
Add an overload to ParseDocument(Stream stream, Encoding encoding) to specify an encoding

### ISSUE THREAD

**Issue by fedesasso** [AngleSharp/AngleSharp#1040]
Is there a way to load a HtmlDocument from a byte array / a stream specifying which character encoding to use?
We currently are loading the HTML document this way:

```
Encoding encoding = ...
using (MemoryStream ms = new MemoryStream(bytes))
{
	this.document = parser.ParseDocument(ms); // I cannot specify the given encoding
}
```

If I understood correctly, AngleSharp tries to detect the proper encoding, but encoding could be specified in various ways (HTTP headers, Byte Order Mark, meta content-type and meta charset), so at least the HTTP header case cannot be known by the parser.

We are trying to move away from HtmlAgilityPack, which in its equivalent class has an overload to specify the encoding to use.
In our program byte array can be read from the web, or be loaded from a local DB. In most cases we already have the encoding, plus we wish to permit users to visualize HTML content with a different encoding.

Does AngleSharp already provide a way to do it?

If not, can I request an implementation?
Can you add an overload:
`HtmlParser.ParseDocument(Stream stream, Encoding encoding)`
 to specify an encoding

If the current method tries to detect the encoding, it would mean also a performance improvement when the encoding is already know.

Thank you

**Comment by FlorianRappl** [comment]
As you mentioned the encoding can be specified via a header, so you could use `OpenAsync` function of a `BrowsingContext`. This allows you to also open something from a given source (e.g., your stream) with "a mock response", i.e., headers that you define.

**Comment by fedesasso** [comment]
I could certainly do it as a workaround (and a back and forth strategy, as other parts of our system already interpret HTTP headers).
So far I preferred avoiding using OpenAsync to avoid yet another thread in a part that is already handling its own thread pool.

Could you please clear out some of my doubts?

Setting an encoding code in a mocked request would prevent the parser checking for BOM, content-type and meta charset?
I guess the library follows a priority order to decide which encoding directive to follow. I'm totally new with AngleSharp code base and I'm trying to find the relevant code files.
My concern here is that finding a contrasting directive the parser might decide to discard and reload the document with another encoding; that would be the correct behaviour if the "best guess" utf-8 encoding didn't match an encoding directive found in the meta tags, but not if I wanted to force a particular encoding no matter what (something we don't do it yet, but wish to permit it). I'd expect the parser to give priority to a (mocked) HTTP header over other directives, but can you please confirm it?

Can you please point me to the codebase part where BOM, meta content-type and meta charset are processed, and in what order?

By the way, thank you for the impressive work you did with this library.

**Comment by FlorianRappl** [comment]
> Setting an encoding code in a mocked request would prevent the parser checking for BOM, content-type and meta charset? I guess the library follows a priority order to decide which encoding directive to follow. I'm totally new with AngleSharp code base and I'm trying to find the relevant code files.

It follows the same priority list as a browser does.  Essentially, that means that BOM always is considered the highest standard for it, but a header has higher precedence than a meta flag. In any case there is also the complication of a "guess" vs a "confident" pick. So the BOM would still be checked as its required / standardized per W3C.

(For the flow check the `CreateDocumentOptions` and its use - you'll see its used in the document factory, which gets used when a document request is being processed)

The BOM itself (as its the lowest level construct) is part of the `TextSource` - this file also keeps track of the encoding confidence. The usage of the `CurrentEncoding` property is then reflected to the meta handler etc.

**Comment by FlorianRappl** [comment]
Some pointers:

- Received HTTP header: https://github.com/AngleSharp/AngleSharp/blob/c5916721841dded3f55c224b7fa5233f15bab3f9/src/AngleSharp/Dom/CreateDocumentOptions.cs#L40
- Document being processed / was received: https://github.com/AngleSharp/AngleSharp/blob/c5916721841dded3f55c224b7fa5233f15bab3f9/src/AngleSharp/Io/Processors/DocumentRequestProcessor.cs#L44
- Setting the encoding for the actual `TextSource`: https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Text/TextSource.cs#L109

Hope that helps!

**Comment by fedesasso** [comment]
Hey, that was a prompt and detailed answer!
A lot to study for me... thank you!

**Comment by FlorianRappl** [comment]
Landed in `devel`.
