### ISSUE TITLE
Re-Request for stable release (=version 1.0) / RTM

### ISSUE THREAD

**Issue by 304NotModified** [AngleSharp/AngleSharp#1041]
Please reconsider creating a 1.0 version. I requested this years ago: #709, but it doesn't seem to happen.

This library is used by many. The 1.0 version **only** requires to not making (source) breaking changes! There is no requirement to fix the docs, performance, fix all the bugs etc etc. 

Also, if you really need a breaking change, you could make soon a 2.0. That's is better than staying on 0.x forever. (Also related #265)

**Comment by FlorianRappl** [comment]
As mentioned the documentation is not ready for a 1.0 and we miss contributors. It would be great if you could step up and contribute here - much appreciated!

**Comment by SimonCropp** [comment]
As a consumer, IMO the quality of docs and code is good enough to mark it as a stable release

**Comment by Mertsch** [comment]
Would it be possible to unlist all 1.0.0-* nuget packages?
Like https://www.nuget.org/packages/AngleSharp/1.0.0-alpha-844

For me it was quite confusing at first to see an 1.0.0 that is older than 0.17.x

**Comment by FlorianRappl** [comment]
> Would it be possible to unlist all 1.0.0-* nuget packages?

Yeah totally - done!

Thanks for the suggestion.

**Comment by 304NotModified** [comment]
I'm gonna close this as this isn't something this seem to happen ever.

**Comment by FlorianRappl** [comment]
> I'm gonna close this as this isn't something this seem to happen ever.

Nice attitude.

**Comment by 304NotModified** [comment]
> Nice attitude.

thx

**Comment by ImrePyhvel** [comment]
@FlorianRappl Semantic versioning is something that would help every consumer, especially library authors depending on AngleSharp. The frustration you saw is there and it flows down the dependency chain to project-owners trying to keep up with updates and constantly fiddling if it is safe to upgrade a tree or not.

I fully understand that it would be cool to have a perfect package with bells and whistles and comprehensive docs, that following semVer takes a little extra effort, but IMHO it would be worthy to at least reopen this request, to have this on the roadmap. By my view, you have done a good job and it is "good enough" as it is for a real release.

**Comment by FlorianRappl** [comment]
I think you may have misunderstood semver/ the original request @ImrePyhvel . 

Also the issue was not closed by me and my comments are still relevant.
