### ISSUE TITLE
Update GitHubActionsTestLogger to the latest version to support test summaries

### ISSUE THREAD

**Issue by Tyrrrz** [AngleSharp/AngleSharp#1044]
# New Feature Proposal

## Description

The latest version of GHATL adds support for GitHub's job summaries and renders detailed overview of the executed test run:

![image](https://user-images.githubusercontent.com/1935960/171029307-489c9a6b-6b80-4fd9-8ddf-a78bdb5a63f0.png)

## Background

This is a devops enhancement

## Specification

N/A

**Comment by FlorianRappl** [comment]
This is great, thanks!
