### ISSUE TITLE
Could not load file or assembly System.Text.Encoding.CodePages v6

### ISSUE THREAD

**Issue by linkdotnet** [AngleSharp/AngleSharp#1046]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

With the recent update from `v0.16.x` to `v0.17` we get issue due to failing dependencies. 
> One or more errors occurred. (Could not load file or assembly 'System.Text.Encoding.CodePages, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

See [here](https://github.com/bUnit-dev/bUnit/runs/6692337330?check_suite_focus=true#step:7:92) as an example.

I quickly checked the repo and it seems that the `AngleSharp.csproj` file really has the dependency to version 6 (see [here](https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/AngleSharp.Core.csproj#L28)) but the nuspec still points to version 5 (see [here](https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp.nuspec#L19)).

Before I do a PR or something else, is this mismatch on purpose?

**Comment by FlorianRappl** [comment]
> Before I do a PR or something else, is this mismatch on purpose?

No its not. PR welcome; thanks!

**Comment by linkdotnet** [comment]
Thanks for the swift response and merge ;)
