### ISSUE TITLE
QuerySelector returns null for selector

### ISSUE THREAD

**Issue by readonlyden** [AngleSharp/AngleSharp#1049]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

We have a site with a list of datasets on it: https://trudvsem.ru/opendata/datasets

I can use a selector `#dataset-10 .table__wrapper .link` to find some download url on the site.

Element exists and can be found through standard `document.querySelector` APIs in JS:

![image](https://user-images.githubusercontent.com/59210489/174747214-a173e105-d2f4-4d9d-8302-ba2a1c33d161.png)

Also checked this with `jsoup` in Java and `bs4` in python, everything works.

Howewer, in AngleSharp it simply doesn't work at all and returns `null`:

![image](https://user-images.githubusercontent.com/59210489/174748230-e63bd932-a892-4a78-abde-7bed3f6fbfce.png)

## Steps to Reproduce

1. Create a console project
2. Install AngleSharp
3. Query element with selector above

Or just simply check the demo code in my repository https://github.com/readonlyden/anglesharp-bug-demo

**Expected behavior:** Element is returned correctly and I can check it `href` attribute

**Actual behavior:** `QuerySelector` returns `null`

**Environment details:** .NET 6, Windows

**Comment by FlorianRappl** [comment]
The part is not there. This is not a bug - AngleSharp reads the DOM as is. Don't compare pages that have been manipulated by JS or require login / have changed by your user context with what AngleSharp sees.

**Comment by readonlyden** [comment]
@FlorianRappl I disagree, I've checked it out in Chrome DevTools Network tab, and I can see a hyperlink in the initial server html response
![image](https://user-images.githubusercontent.com/59210489/174914261-3444e41a-b1a0-40c5-a36e-7affb9aa25c0.png)

Also I rechecked this in Postman. Links ARE in initial html response. So AngleSharp should be able to find this element

**Comment by FlorianRappl** [comment]
You compare two different things. See what Anglesharp received from the server. Instead of looking at postman you should look at Anglesharp.

**Comment by readonlyden** [comment]
@FlorianRappl beautifulsoup4 in python doesn't execute any JS as well. One can use something like this to fetch a page and SEE that link.

![image](https://user-images.githubusercontent.com/59210489/175814520-7199531d-be0d-4cff-8d95-f4261090714d.png)

Also I've tested AngleSharp with `User-Agent` headers, still no results.

So, since AngleSharp is similar to Bs4 and Jsoup libraries, and since they can handle this selector and find a link in the HTML response (without any JS involved), and AngleSharp not, it seems to be a bug in AngleSharp itself

**Comment by FlorianRappl** [comment]
As long as there is no MWE to reproduce there is nothing we investigate. The code right now uses an URL and when I go there I don't see any table / get the same behavior in chrome that you describe as a bug.

So if you really think this is an issue please make a reproducible MWE. Happy to look into it when we have some code showing the issue.
