### ISSUE TITLE
"The output char buffer is too small to contain the decoded characters"

### ISSUE THREAD

**Issue by own2k** [AngleSharp/AngleSharp#105]
Sometimes i get errors building IDocument from byte stream, using BrowsingContext as DocumentBuilder class does. Sometimes i get an exception:

**The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.**

This was from byte output from http://independent.co.uk/ (site encoding is utf-8). 
Could you please explain why this error happens and what should i do.

**Comment by FlorianRappl** [comment]
I've never seen that error - it might be platform specific. What's your platform?

According to StackOverflow that might be an internal problem with the error handling of UTF-8 from .NET (http://stackoverflow.com/questions/18530568/c-sharp-binaryreader-readchar-throws-system-argumentexception-the-output-char).

**Comment by own2k** [comment]
Windows Store app in 8.1, ok, will be testing..

**Comment by FlorianRappl** [comment]
Thanks I'll investigate the issue as well.

**Comment by own2k** [comment]
Okay i've added test project to a repository https://github.com/CrackHD/angleSharp-105bug that reproduces the issues.

I have an idea that 'char buffer' issue related with 'content-type' and 'content-encoding' headers are not accessible to parser code (no appropriate methods in VirtualResponse to set them easy). 
If so, this error should appear on any non-UTF data streams. 

I have no time to explore the AngleSharp source, so my **feature request** is:
Add a simple method in VirtualResponse class to import headers from HttpResponseMessage (System.Net.Http), and classic HttpWebResponse (System.Net). Or better, from IDictionary[string, string].

As my application detects encoding from response, i tried to set it as header in VirtualResponse:

``` csharp
m.Header("Content-Encoding", ContentEncoding.WebName);
m.Header("Content-Type", "text/html charset=" + ContentEncoding.WebName);
```

(it was windows-1251)

But it does not help to solve the exception on parse. Any ideas?

**Comment by FlorianRappl** [comment]
Why do you use `VirtualResponse`? If you have the address then give it to AngleSharp directly. It is not only convenient, but it will also reduce such errors dramatically. That being said - if you pass in a string then this string is UTF-16 already - so the encoding does not matter at all!

If you pass in a stream then the encoding from the server the changes are little as well. The encoding from the server is only a hint, which will be used in the beginning, however, it is overpowered by the readings from the BOM and the specific encoding hint in the HTML source. 

The error does not appear on the non-UTF data streams that are tested with AngleSharp (Windows-1251 is one of them). I will have a look at the repo where you reproduce the issue. Hopefully I'll find the answer to your problems there.

I will add an overload for `Headers` accepting an `IDictionary`.

**Comment by own2k** [comment]
I use it because AngleSharp is only one of possible destinations for downloaded data in my program and i don't want to let AngleSharp access network. It is most common situation for users of your library after the recommended by you.

**Comment by FlorianRappl** [comment]
Alright - but just one note: AngleSharp will read your stream, so if you use it as in your test project, then the stream (which has no random access) is at its end and cannot be used anymore. Hence you need something like a buffer stream or use a memory stream to wrap it. I guess you are already thinking about that, but if not, then this is something to keep in mind.

**Comment by own2k** [comment]
Stream.Seek() helps, yeah :+1: 
in my app i clone the response into MemoryStream, by the way. but i think this is not required..

**Comment by FlorianRappl** [comment]
I think I was able to fix the problem. At least for the cases described it is sufficient to increase the char buffer by a single element compared to the byte buffer. Also the other problem (infinite loop) is solved now.
