### ISSUE TITLE
How to get the width of an element?

### ISSUE THREAD

**Issue by Tony20221** [AngleSharp/AngleSharp#1051]
How to get the width of an element? a div or h2.
This code is returning an empty width. style.Dump() displays some properties but none for element size.

```
var config = Configuration.Default.WithDefaultLoader().WithCss().WithRenderDevice(new DefaultRenderDevice { DeviceHeight = 768, DeviceWidth = 1024, });
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(req => req.Content(html));

var style = document.DefaultView.GetComputedStyle(someElement);
	style.Dump();
	style.GetWidth().Dump();  //is blank
	style.GetMaxWidth().Dump();  //is blank
	elements[i].GetInnerText().Dump();

```

**Comment by FlorianRappl** [comment]
AngleSharp is only the parser - it does not actually render. The `RenderDevice` allows to compute some metrics, but width requires an actual rendering to occur in order to know how large elements will be.

At this time we don't construct a render tree and therefore do not know such metrics.
