### ISSUE TITLE
Add MouseEvent missing properties

### ISSUE THREAD

**Issue by egil** [AngleSharp/AngleSharp#1054]
# New Feature Proposal

The type `MouseEvent` is missing properties according to https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent

## Description

The following properties are missing from the `MouseEvent` type:

- [MouseEvent.layerX](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/layerX) (not standard, but supported by all browsers)
- [MouseEvent.layerY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/layerY) (not standard, but supported by all browsers)
- [MouseEvent.movementX](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX)
- [MouseEvent.movementY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementY)
- [MouseEvent.offsetX](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX)
- [MouseEvent.offsetY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetY)
- [MouseEvent.pageX](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageX)
- [MouseEvent.pageY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageY)
- [MouseEvent.relatedTarget](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget)

## Specification

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent

**Comment by FlorianRappl** [comment]
Yeah all these properties require layout information and would not be concerns of AngleSharp.Core, but rather of a non-existing rendering library.

**Comment by egil** [comment]
Ok, for my purpose in bUnit, where users emulate events being raised, I guess I can just create an BunitMouseEvent type that inherits from Mouse event and include these properties.
