### ISSUE TITLE
How to specify HtmlParserOptions with context.OpenAsync(...) ?

### ISSUE THREAD

**Issue by fedesasso** [AngleSharp/AngleSharp#1055]
I'm mocking the desidered encoding as suggested in the documentation (and issue 1040):

	IBrowsingContext context = BrowsingContext.New();
	IDocument document = await context.OpenAsync(req => req.Content(myStream).Header("content-type", "text/html; charset=UTF-8"));

But this way I cannot find a way to specify the desired HtmlParserOptions.

I know how to do it by creating explicitely the parser:

	var parserOptions = new HtmlParserOptions
	{
		IsKeepingSourceReferences = keepCoordinates,
		IsNotConsumingCharacterReferences = keepCharRef,
		IsStrictMode = false
	};
	var context = BrowsingContext.New(Configuration.Default);

	var parser = new HtmlParser(parserOptions, context);
	var doc = parser.ParseDocument(....);

How can I do both things?

**Comment by FlorianRappl** [comment]
I think if you make a configuration that includes a creator for `IHtmlParser` you'll be good.

https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Configuration.cs#L61

```cs
Creator<IHtmlParser>(ctx => new HtmlParser(new HtmlParserOptions(...), ctx)),
```

Does that go in the direction you want - or am I misunderstand the issue?
