### ISSUE TITLE
Virus infested

### ISSUE THREAD

**Issue by CieloVistaSoftware** [AngleSharp/AngleSharp#1058]
# Bug Report
Better run some virus checkers on all code. I downloaded on 28 July 2022.  The next day I received a report from security team. There were 4 or 5 virus in the code.
## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version of AngleSharp?
- [ ] yes
- [ ] Did you check the FAQs to see if that helps you?
- [ ] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [ ] Did you perform a search in the issues?
- [ ] 

For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the bug]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Environment details:** [OS, .NET Runtime, ...]

## Possible Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
That is just BS. Better check your sources...

**Comment by FlorianRappl** [comment]
(Pro tip: If you have just crappy virus scanners that do actually detect viruses in the HTML edge cases that the parser needs to handle then you should maybe rethink your protection strategy. Also your "security team" should maybe get a training or two.)
