### ISSUE TITLE
im not sure is that a bug,but when im change element innerHtml,the htmldocument looks not apply the change to the source.

### ISSUE THREAD

**Issue by sgf** [AngleSharp/AngleSharp#1059]
# Bug Report
im not sure is that a bug,
but when im change element innerHtml,
the htmldocument looks not apply the change to the source.

**Comment by FlorianRappl** [comment]
The source is the source - it will remain unchanged (same in your webbrowser). Instead of the source get the serialized DOM - only the DOM updates so if you want to see the change get the DOM serialization.

**Comment by sgf** [comment]
> The source is the source - it will remain unchanged (same in your webbrowser). Instead of the source get the serialized DOM - only the DOM updates so if you want to see the change get the DOM serialization.

ok,fine ,thank you much.
