### ISSUE TITLE
CSS parsing issue related to the import rule

### ISSUE THREAD

**Issue by D92130** [AngleSharp/AngleSharp#106]
For the testing code below:

```
        var src = "@import url(import3.css); p { color : #f00; }";
        var sheet = ParseStyleSheet(src);
```

The end sheet.CssText is:  "@import url(\"import3.css\") not all"
and the value of sheet.CssRules.Lenght is 1.  The css definition after the import rule is ignored.

**Comment by FlorianRappl** [comment]
Thanks - I'll look at that!
