### ISSUE TITLE
Uri when using ParseDocument?

### ISSUE THREAD

**Issue by Quaraxkad** [AngleSharp/AngleSharp#1060]
Is there a way to specify the source url when parsing an HTML string using ParseDocument? Or maybe I'm going about it the wrong way... In my scenario, I want to get anchor hrefs, they are relative paths though, so AngleSharp uses about:blank as the base. Getting the source from BrowsingContext.OpenAsync is not an option.

**Comment by FlorianRappl** [comment]
Why is `OpenAsync` not an option?

**Comment by Quaraxkad** [comment]
I have my own function for downloading the urls that's too complicated to convert the whole project to use OpenAsync instead of my function.

**Comment by FlorianRappl** [comment]
Hm not sure how that impacts you. `OpenAsync` accepts a callback where you can just create the response as you like (e.g., with a stream or text content from data you received somewhere else).

(Just in case you did not read / see the docs: https://anglesharp.github.io/docs/core/03-Examples).

**Comment by Quaraxkad** [comment]
I did not see that example, that's perfect thanks! However my C# is not so "sharp"... How would I do context.OpenAsync(req => req.Content(source)) in vb.net?

**Comment by FlorianRappl** [comment]
https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/lambda-expressions
