### ISSUE TITLE
CssSelectorParser.ParseSelector("a[href*=8a1ae5ec7f9301ef0180c0271d422199]")

### ISSUE THREAD

**Issue by garrett12138** [AngleSharp/AngleSharp#1061]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description
CssSelectorParser.ParseSelector("a[href*=8a1ae5ec7f9301ef0180c0271d422199]") got null.Element.QuerySelector("a[href*=8a1ae5ec7f9301ef0180c0271d422199]") got AngleSharp.Dom.DomException

[Description of the bug]

## Steps to Reproduce

```cs
 public void test()
        {
            var context = BrowsingContext.New(Configuration.Default);
            var parser = context.GetService<IHtmlParser>();
            var html = "<!DOCTYPE html>" +
                        "<html lang=\"en\">" +
                        "<head>" +
                        "    <meta charset=\"UTF-8\">" +
                        "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">" +
                        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" +
                        "    <title>Document</title>" +
                        "</head>" +
                        "<body>" +
                        "    <a href=\"?studentId=8a1ae5ec7f9301ef0180c0271d422199&abc\">text</a>" +
                        "</body>" +
                        "</html>";
            var document = parser.ParseDocument(html);
            try
            {
               var  dom = document.QuerySelector("a[href*=8a1ae5ec7f9301ef0180c0271d422199]"); //got AngleSharp.Dom.DomException
                if (dom != null)
                {
                    string text = dom.TextContent;
                }
            }
            catch (Exception)
            {

                throw;
            }
  }
```

**Expected behavior:** [What you expected to happen]
 dom shoud be not null
**Actual behavior:** [What actually happened]
document.QuerySelector("a[href*=8a1ae5ec7f9301ef0180c0271d422199]") got AngleSharp.Dom.DomException
```
  The string did not match the expected pattern.
   at AngleSharp.Dom.QueryExtensions.CreateSelector(INodeList nodes, INode scope, String selectorText)
   at AngleSharp.Dom.QueryExtensions.QuerySelector(INodeList nodes, String selectorText, INode scopeNode)
   at AngleSharp.Dom.Document.QuerySelector(String selectors)
```
![DomException](https://user-images.githubusercontent.com/1832638/189418349-df76632e-ebc8-474c-aba4-d7ff584057ad.png)

**Environment details:** [OS, .NET Runtime, ...]
OS: windows 11 pro
.NET Runtime .NET 6.0 

## Possible Solution
document.QuerySelector("a[href*=a1ae5ec7f9301ef0180c0271d422199]") work exactly

**Comment by FlorianRappl** [comment]
This is not a valid selector. Please try first in the browser of your choice.

![image](https://user-images.githubusercontent.com/1766191/189481082-5bea19ce-bf87-46f5-9308-b34b4b7bedac.png)

**Comment by campersau** [comment]
The issue is that the attribute value starts with a number, try to use quotes e.g.:
`"a[href*='8a1ae5ec7f9301ef0180c0271d422199']"`

See https://stackoverflow.com/questions/6247221/css-selectors-cannot-match-numerical-attribute-values-why
