### ISSUE TITLE
Sudden publish errors with .NET 6 Blazor WASM and AngleSharp

### ISSUE THREAD

**Issue by UweKeim** [AngleSharp/AngleSharp#1065]
Out of nowhere I'm getting errors during the optimization phase when publishing my Blazor WebAssembly application. 

I'm unsure why this happens suddenly, and since "AngleSharp.dll" is the only thing I recognize, I'll try my luck and post it here.

Excerpt from the error log:

> c:\P\zp-next\Main\Source\MainFrontend\Code\Helper\PropertyHelper.cs(159,9): warning CS8601: Mögliche Nullverweiszuweisung. [c:\P\zp-next\Main\Source\MainFrontend\MainFrontend.csproj]
>   MainFrontend -> c:\P\zp-next\Main\Source\MainFrontend\bin\Release;optimize=true;PublishProfile=FolderProfile.pubxml\net6.0\MainFrontend.dll
>   MainFrontend (Blazor output) -> c:\P\zp-next\Main\Source\MainFrontend\bin\Release;optimize=true;PublishProfile=FolderProfile.pubxml\net6.0\wwwroot
>   Das Optimieren der Assembly für die Größe kann das Verhalten der App ändern. Stellen Sie sicher, dass nach der Veröffentlichung Tests durchgeführt werden. Informationen finden Sie unter https://aka.ms/dotnet-illink.
>   Assemblys werden für die Größe optimiert. Dieser Vorgang kann eine Weile dauern.
> C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(412,5): error : System.ArgumentException: **An item with the same key has already been added.** Key: c:\P\zp-next\Main\Source\MainFrontend\bin\Release;optimize=true;PublishProfile=FolderProfile.pubxml\net6.0\wwwroot\_framework\**AngleSharp.dll** [c:\P\zp-ne
> xt\Main\Source\MainFrontend\MainFrontend.csproj]
> C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(412,5): error :    at System.Collections.Generic.Dictionary\`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) [c:\P\zp-next\Main\Source\MainFrontend\MainFrontend.csproj]
> C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(412,5): error :    at System.Collections.Generic.Dictionary\`2.Add(TKey key, TValue value) [c:\P\zp-next\Main\Source\MainFrontend\MainFrontend.csproj]
> C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(412,5): error :    at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.GroupExistingStaticWebAssets(Dictionary\`2 assemblyAssets, Dictionary\`2 nativeAssets, Dictionary\`2 satelliteAssemblyAssets, Dictionary\`2 symbolAssets, Dictionary\`2 compressedRepresentations) [c:\P\zp-next\Main\Source\MainFrontend\MainFrontend.csproj]
> C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(412,5): error :    at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.Execute() [c:\P\zp-next\Main\Source\MainFrontend\MainFrontend.csproj]

### Question

Does someone have a clue what's going on here and how to fix this?

**Comment by FlorianRappl** [comment]
Yeah I'm not sure if its related to AngleSharp, because I vaguely remember that I've seen `An item with the same key has already been added.` in the past. I think there was no great way to resolve it - I cleaned the VS output / cache and restarted VS. Maybe it'll come up again.

If somebody knows this / has a better idea I'd welcome insights. I think its related to the way how Blazor post-builds / optimizes the resources.

**Comment by UweKeim** [comment]
Thanks, Florian. Unfortunately cleaning did not help.

Maybe there is an issue with .NET 7SDK RC 1 (as it reads" C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\" in the output logs.

Easiest would probably be to wait until .NET 7 is officially released.

**Comment by UweKeim** [comment]
Awesome me 😁, I fixed it!

By placing a "global.json" file in the same folder as the SLN file of my solution with this content, I fixed it:

```
{
  "sdk": {
    "version": "6.0.401"
  }
}
```

After that, running the publish again, everything succeeds.

([See here for details](https://entwicklergate.de/t/verwendete-version-von-dotnet-fuer-ein-vs-projekt-umschalten/525))

**Comment by FlorianRappl** [comment]
Nice!
