### ISSUE TITLE
How to get the  downloaded file after click a button?

### ISSUE THREAD

**Issue by f3404923** [AngleSharp/AngleSharp#1067]
I want to get a document( a excel file) after click 'imgExport' button, Can you give me some suggestions how to do?
-------------------------------------------------------------------------------------------------------------------------------------
 <!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
   
    <form method="post" action="./PrdDetails.aspx?s=BSH_Input&amp;qwo=&amp;qpn=&amp;qline=&amp;qt1=2022-10-24+10%3a12%3a31&amp;qt2=2022-10-24+14%3a12%3a31&amp;qproduct=&amp;t=FAIL" id="form1">
        <table class="CommonTable" style="width:100%;margin-bottom:2px" ;="" cellpadding="0px" ;cellspacing="0px" ;background-image:="" url('..="" images="" bar_mid.png');="">
            <tbody>
                <tr>
                    <td class="auto-style2">
                        工单:
                    </td>
                    <td>
                        <input name="txtWO" type="text" id="txtWO">
                    </td>
                    <td>
                        产品别:
                    </td>
                    <td class="auto-style1">
                        <select name="drpProductList" id="drpProductList">
                            <option selected="selected" value="">全部</option>
                            <option value="test">test</option>

                        </select>
                    </td>
                    <td>
                        产品代码：
                    </td>
                    <td>
                        <input name="txtPn" type="text" id="txtPn">
                    </td>
                    <td>
                        产线:
                    </td>
                    <td>
                        <select name="drpLineList" id="drpLineList">
                        </select>
                    </td>
                    <td id="tdLineStation">
                        生产日期:
                    </td>
                    <td>
                        <input name="txtDayStart" type="text" value="2022-10-24" id="txtDayStart">
                        <input name="txtTimeStart" type="text" value="10:12:31" id="txtTimeStart">
                        ~<input name="txtDayEnd" type="text" value="2022-10-24" id="txtDayEnd">
                        <input name="txtTimeEnd" type="text" value="14:12:31" id="txtTimeEnd">
                    </td>
                    <td>
                        <span id="lblInfo">无数据记录.</span>
                    </td>
                    <td>
                    </td>
                    <td>
                        <input type="image" name="btnQuery" id="btnQuery" actioncode="R" src="../Images/query.png" onclick="return checkNullInput();">

                        <input type="image" name="imgExport" id="imgExport" src="../Images/export.gif">
                    </td>
                </tr>
                <tr><td colspan="4">由于数据量较大，系统只显示前50条数据，如果看全部数据请单击“导出”按钮用Excel查看</td></tr>
            </tbody>
        </table>
        </div>
        &nbsp;<div>

        </div>
        </div>

        <input type="hidden" name="hidTime" id="hidTime">
    </form>

</body>
</html>

**Comment by FlorianRappl** [comment]
Can you specify

> I want to get a document after click 'imgExport' button

Also instead of posting a txt file can you have the code in the message?

**Comment by f3404923** [comment]
I closed this ticket.
I instead that with 'selenium' to click button and get downloaded document.
