### ISSUE TITLE
Issue with JSON string in attributes

### ISSUE THREAD

**Issue by xC0dex** [AngleSharp/AngleSharp#1071]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

## Description
Currently, I'm facing an issue while fetching attributes from an element. When I'm putting some JSON string into an attribute, AngleSharp it won't work, when I'm using the double quotation marks. I know that I have to use the single quotation marks in a case where the value contains some double quotation marks, however, I'm not able to change it in the context of Blazor. As far as I can tell, Blazor and the bUnit framework always replace the single quotation marks with double quotation marks. The problem occurred after a recent update of the bUnit framework. They are now having the same render behavior as Blazor (No more encoding). The following example showcases the issue:

```csharp
var context = BrowsingContext.New();  
var data = new  
{  
Foo = "Bar"  
};  
var jsonString = JsonSerializer.Serialize(data);  
var contentToRender = $"<h1 data-attribute='{jsonString}'></h1><h2 data-attribute=\"{jsonString}\"></h2>";  
var document = await context.OpenAsync(request => request.Content(contentToRender));  
var h1Attributes = document.QuerySelector("h1")!.Attributes;  
var h2Attributes = document.QuerySelector("h2")!.Attributes;  
Console.WriteLine(h1Attributes.Length); // Returns 1  
Console.WriteLine(h2Attributes.Length); // Returns 2
```
I already mentioned this issue to bUnit https://github.com/bUnit-dev/bUnit/discussions/916. It would be nice to find a solution for it. 

## Steps to Reproduce

1. Create any tag with an attribute 
2. This attribute should use the double quotation marks
3. The value should be a JSON string with double quotation marks

**Expected behavior:**
To be honest: I'm not sure. If AngleSharp is intended to follow the same behavior as the browser, I think the current implementation is correct. However, it would be nice, if the generated Blazor component markup would also work with AngleSharp seamlessly.

**Actual behavior:**
AngleSharp always expects single quotation marks, if the value of an attribute contains double quotation marks.

**Environment details:**
.NET 7 on windows (local machine) and Linux (docker environment)

## Possible Solution

Maybe a short discussion with the guys from bUnit to find a good solution that fits for everyone.

**Comment by FlorianRappl** [comment]
Hm you marked it as a "bug" but this is rather a question. As you mentioned the current behavior is not only the specified behavior, but also the only thing that makes sense. You need to correctly encode your attribute values - `&quot;` represents a double quote.

**Comment by xC0dex** [comment]
Hey,
thanks for your feedback. I updated the discussion in the bUnit project https://github.com/bUnit-dev/bUnit/discussions/916#discussioncomment-4116591 I also think that this is no issue in AngleSharp. I'll close this issue.

Sorry, this was my first issue. I will pay more attention to the way how to create issues.

**Comment by FlorianRappl** [comment]
> Sorry, this was my first issue. I will pay more attention to the way how to create issues.

Completely fine - no issue here; just remarked that I was confused that it was stated as a bug. Thanks for following up!
