### ISSUE TITLE
I can't set template content using InnerHtml

### ISSUE THREAD

**Issue by santoro-mariano** [AngleSharp/AngleSharp#1072]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

When I set the InnerHtml property in the template element it doesn't seem to reflect those changes in the Content property:

![bug](https://user-images.githubusercontent.com/15754816/201482271-6ce46836-0d3c-4c52-8488-1102ac8d973e.png)

On the other hand, the same steps work just fine in Chrome:

![chrome_example](https://user-images.githubusercontent.com/15754816/201481708-ed7ca5f0-6350-48be-aaf2-ba4e03dc2233.png)

## Steps to Reproduce

1. Create new HTML template element calling CreateElement from document instance
2. Set InnerHtml property in template instance

**Expected behavior:**

Content property should be populated when InnerHtml property is set

**Actual behavior:**

Content property is not populated

**Environment details:**
* Windows 11
* Dotnet 7

## Possible Solution

Call internal method 'PopulateFragment' when the InnerHtml property is set?
I tried calling that method using reflection and it seems to work:

![reflection](https://user-images.githubusercontent.com/15754816/201482306-8e50dc47-608a-4e43-912f-aefb91bdd3fe.png)

**Comment by FlorianRappl** [comment]
I think what we could do is to introduce a method call in `ReplaceAll` (https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Dom/Internal/Node.cs#L220) which is defined like this (names etc. to be defined)

```cs
protected virtual void ReplacedAll() {};
```

and is then overridden in `HtmlTemplateElement` (calling `PopulateFragment`).

**Comment by santoro-mariano** [comment]
@FlorianRappl makes sense. I'm not very familiar with the AngleSharp code yet (I started using it in one of my projects last night) but, If it's ok with you, I could look into it as soon as I have a chance.

**Comment by FlorianRappl** [comment]
That would be much appreciated - if you need any help don't hesitate to ask me. Always here to help.

**Comment by FlorianRappl** [comment]
Landed in `devel`.
