### ISSUE TITLE
TreeWalker throws NullReferenceException while iterating template content

### ISSUE THREAD

**Issue by santoro-mariano** [AngleSharp/AngleSharp#1073]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

## Description

TreeWalker throws NullReferenceException while iterating template content. It works just fine until it reach the end of the content.
Logic in the ToNext method in the TreeWalker does not contemplate that I can set the current element in the tree walker using the Current property and that that element could have the parent node set to null:

![bug](https://user-images.githubusercontent.com/15754816/201483585-8c9fe25a-4d77-4ac1-9e45-f206f0e33b56.png)

![bug2](https://user-images.githubusercontent.com/15754816/201483589-9021e7bd-5404-4b0f-97e5-786465bfe9c8.png)

## Steps to Reproduce

Check screenshots

**Expected behavior:**

TreeWalker should finish successfully

**Actual behavior:**

TreeWalker throws NullReferenceException if tree is not all the way connected to the root

**Environment details:**

* Windows 11
* Dotnet 7

## Possible Solution

* Contemplate possible null parent in node from TreeWalker class logic

**Comment by FlorianRappl** [comment]
Sounds reasonable - mind doing a PR with the proposed solution (and a MWE as a unit test to verify the bug and prevent regression)?

**Comment by FlorianRappl** [comment]
Fix landed in `devel`.
