### ISSUE TITLE
Virus detection

### ISSUE THREAD

**Issue by srcmkr** [AngleSharp/AngleSharp#1076]
Hey there,

visiting your documentation website [anglesharp.github.io](https://anglesharp.github.io/) triggers our virus scanner.
![image](https://user-images.githubusercontent.com/30409640/204749753-72a93f84-6168-46c1-972c-f24f32e9ec70.png)

If you're using wasm there, it might be an known issue: https://github.com/dotnet/aspnetcore/issues/40283
If not, you should have a look - there are already multiple tickets about (false) positives in your closed issues.

Have a nice day.

**Comment by FlorianRappl** [comment]
Please stop posting BS.

This is the response from the service (https://feed.piral.cloud/api/v1/pilet/anglesharp):

```json
{"items":[{"name":"@anglesharp/core","version":"0.17.1-pre.1","description":"The doclet for the AngleSharp.Core documentation.","author":{"name":"","email":""},"requireRef":"pr_ef8ea386e6a99f81eabfdd5b007c551e","link":"https://assets.piral.cloud/pilets/anglesharp/@anglesharp/core/0.17.1-pre.1/index.js","spec":"v1"},{"name":"@anglesharp/css","version":"0.16.0-pre.1","description":"The doclet for the AngleSharp.Css documentation.","author":{"name":"","email":""},"requireRef":"pr_11893c417b5c5ec831f17fd5733a06ba","link":"https://assets.piral.cloud/pilets/anglesharp/@anglesharp/css/0.16.0-pre.1/index.js","spec":"v1"},{"name":"@anglesharp/io","version":"0.16.0-pre.16","description":"The doclet for the AngleSharp.Io documentation.","author":{"name":"","email":""},"requireRef":"pr_8794a328ff040a6d59204231b655f026","link":"https://assets.piral.cloud/pilets/anglesharp/@anglesharp/io/0.16.0-pre.16/index.js","spec":"v1"},{"name":"@anglesharp/js","version":"0.16.0-pre.18","description":"The doclet for the AngleSharp.Js documentation.","author":{"name":"","email":""},"requireRef":"pr_6be4c03890732fa4b6736a7024a68f11","link":"https://assets.piral.cloud/pilets/anglesharp/@anglesharp/js/0.16.0-pre.18/index.js","spec":"v1"},{"name":"@anglesharp/wasm","version":"0.16.0-pre.14","description":"The doclet for the AngleSharp.Wasm documentation.","author":{"name":"","email":""},"requireRef":"pr_718a006f21bd7ec5bae6a5bb57c5f003","link":"https://assets.piral.cloud/pilets/anglesharp/@anglesharp/wasm/0.16.0-pre.14/index.js","spec":"v1"},{"name":"@anglesharp/xml","version":"0.16.0-pre.15","description":"The doclet for the AngleSharp.Xml documentation.","author":{"name":"","email":""},"requireRef":"pr_1df18c457d7ef527a99d0038b1024197","link":"https://assets.piral.cloud/pilets/anglesharp/@anglesharp/xml/0.16.0-pre.15/index.js","spec":"v1"}],"feed":"anglesharp"}
```

Not sure where a virus is seen. I rather think your virus scanner should be exchanged.

**Comment by srcmkr** [comment]
Speaking of ignorance and claiming "BS": There are multiple reports of (I assume) false positives.
Ich bin auch kein Bot oder irgendein Dully, der erst seit gestern Software entwickelt, vielleicht wäre hier ein wenig mehr Kollegialität und ein etwas anderer Ton angesagt. Ich bin nicht dein Feind, sondern denke, dass AngleSharp gut und einsetzbar ist.

My goal is not to blame you in any way - but improving this project by telling you, that there *IS* an actual problem, which I personally experienced. I don't think that I'm wasting your time by creating an existing issue which is about your software.
There are confirmed issues (by the dotnet team) with wasm (.dll files), there might be other reasons. 
This is why I created this ticket, so you know and can have a look. If you don't want, it's ok. But I know from my experiences in over 20+ years in software development, that I cannot know every issue happening on other computers - and I am thankful for every feedback. Never would I insult anyone to post BS or waste my time filing an issue. You should overthink your attitude.

Oh and btw: You can't just tell devs to change their antivirus (G-Data is a german company with 42 million in revenue producting enterprise-grade anti-virus solutions) - because they just might have any influence on those decisions.

**Comment by FlorianRappl** [comment]
Alright then let's follow your judgement. Where and what virus should be on the reported site? Please tell me and show evidence.

**Comment by srcmkr** [comment]
It seems like the whole domain https://*.piral.cloud got blacklisted - maybe some bad players commited code to piral.cloud. I had to look it up, is piral.cloud some kind of CDN? Maybe this triggers the alert.

Edit: yes, this seems to be the root of this issue:

![image](https://user-images.githubusercontent.com/30409640/204768619-69679c8b-a3ae-46f4-9a12-02660bb9b650.png)

**Comment by FlorianRappl** [comment]
No Piral Cloud is in our possession and is a free service to host feeds for micro frontends.

So again, the root cause is G DATA just blocking some page without any cause actually backing my initial point about being a crappy protection service.

**Comment by srcmkr** [comment]
If piral.cloud is yours, I only see two options:
1. You ignore this issue with the "crappy protection service" (maybe there should be a hint in the docs about this to avoid further tickets) or
2. You try to contact G Data (as domain admin) and demand a removal of your domain from the blacklist. If no malware is hosted, they have to comply.
