### ISSUE TITLE
The PowerShell package doesn't match the public API

### ISSUE THREAD

**Issue by ZzZombo** [AngleSharp/AngleSharp#1077]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)?
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

I've installed the latest, 0.8.1 version of the PowerShell package via NuGet. After I imported it into the PS session, however, it lacks certain types in the assembly, for example `BrowsingContext` and in general the API seems to mismatch the one in the `main` branch, so my options are limited in regards to working with the library. I used the tests as reference FWIW.

## Steps to Reproduce

1. `Install-Package AngleSharp`
2. `Add-Type -Path (Get-ChildItem -Filter '*.dll' -Recurse (Split-Path (Get-Package -Name 'AngleSharp').Source)).FullName`
3. Invoke autocompletion (`Ctrl+Space`) after typing out `[AngleSharp.`, note the lack of the `BrowsingContext` type, only the base interface is present.

**Expected behavior:** The public API matches the current described behavior.

**Actual behavior:** It doesn't.

**Environment details:** Windows 10 19045.2251, PowerShell Core v7.3.1.

## Possible Solution

N/A

**Comment by FlorianRappl** [comment]
> I've installed the latest, 0.8.1 version of the PowerShell package via NuGet

There is no PowerShell package (not sure what you refer to) and the latest version is 0.17.1 (https://www.nuget.org/packages/AngleSharp/). If you have 0.8.1 - this version is more than 7 years old and surely diverged from `main`.

**Comment by ZzZombo** [comment]
As I said I installed the package from the NuGet package provider of PowerShell. For some reason it installed that old version that I assumed to be the latest. Today after the hint it was not the latest, I reinstalled it and after working around the "dependency loop" error, got the latest package version but w/o dependencies.
