### ISSUE TITLE
Parsing a document from the given URL and parser options?

### ISSUE THREAD

**Issue by ZzZombo** [AngleSharp/AngleSharp#1078]
I've been combing the docs and tests, but can't figure out how to parse HTML from a URL while also setting parser options. It appears to be unsupported. The HTML parser must be instantiated directly in order to supply your own parser options using the overloaded constructor that takes both context and options as arguments, but I see no way to specify what URL the document was served from. I've tried both using the virtual request/response via the `ctx.OpenAsync()` call and also `ctx.Current.Open()`, then creating the parser instance and parsing the document out of a stream, but the resulting document still defaults to the `about:blank` URI for its properties.

Later, I've found the time to trace through the sources and figured out that it's possible to set the document's `Location.href` to the desired URI value, and it appears to be properly reflected in the DOM. However, I think that it's counter-intuitive that the parser ignores the context's location when creating the document, so I suggest to remedy that by making sure the parser takes it into account.

**Comment by FlorianRappl** [comment]
> virtual request/response

But that one has it directly.

```cs
ctx.OpenAsync(res => res.Address(url).Content(yourContent));
```

> I think that it's counter-intuitive that the parser ignores the context's location when creating the document

Talk to the W3C people. I don't make these rules. The context is the context, not the document. A context can create many documents and a document can create new contexts. According to the spec every document starts with `about:blank`.

> It appears to be unsupported.

The parser is also taken from the registered services, so you can just prepare your services with a parser such that your options are respected (the document factory obtains the parser then, see, e.g., https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Dom/DefaultDocumentFactory.cs#L96).
