### ISSUE TITLE
Element names and namespaces

### ISSUE THREAD

**Issue by michaelhkay** [AngleSharp/AngleSharp#1079]
# New Feature Proposal

## Description

[Description of the proposed feature]

## Background

Provide any additional background for the feature. e.g., user scenarios.

## Specification

In case of updates that adhere to specification changes, please reference the used specification.

**Comment by FlorianRappl** [comment]
Not sure what this is about. Please describe your issue in more detail.

**Comment by michaelhkay** [comment]
Sorry, I thought I abandoned it before posting, as I needed to collect more information.
