### ISSUE TITLE
Help Get computed style

### ISSUE THREAD

**Issue by kamekjay** [AngleSharp/AngleSharp#1082]
Hi! I'm new to AngleSharp,
I'm using it with Unity and I have I think a noob question.
The only thing I'm trying to get is the computed style of an element.

The input HTML is this

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title></title></head><body><p style="margin-top: 0px;margin-bottom: 0px;line-height: 1.15;text-align: center;"><span style="font-family: 'Verdana';font-style: Normal;font-weight: normal;font-size: 48px;color: #000000;">3</span><span style="font-family: 'Verdana';font-style: Normal;font-weight: normal;font-size: 19px;color: #000000;"></span></p></body></html>`

What is the best way to get the computed style of the string "3"

Using this code I'm getting a null ref 
NullReferenceException: Object reference not set to an instance of an object
AngleSharp.Css.Dom.CssStyleDeclaration.ChangeDeclarations (System.Collections.Generic.IEnumerable`1[T] decls, System.Predicate`1[T] defaultSkip, System.Func`3[T1,T2,TResult] removeExisting) (at <e21e4035785343bfa23606c51eaa0ef2>:0)
AngleSharp.Css.Dom.CssStyleDeclaration.SetDeclarations (System.Collections.Generic.IEnumerable`1[T] decls) (at <e21e4035785343bfa23606c51eaa0ef2>:0)
AngleSharp.Css.StyleCollectionExtensions.ComputeCascadedStyle (System.Collections.Generic.IEnumerable`1[T] styleCollection, AngleSharp.Dom.IElement element, AngleSharp.Css.Dom.ICssStyleDeclaration parent) (at <e21e4035785343bfa23606c51eaa0ef2>:0)
AngleSharp.Css.StyleCollectionExtensions.ComputeDeclarations (System.Collections.Generic.IEnumerable`1[T] rules, AngleSharp.Dom.IElement element, System.String pseudoSelector) (at <e21e4035785343bfa23606c51eaa0ef2>:0)
AngleSharp.Dom.WindowExtensions.GetComputedStyle (AngleSharp.Dom.IWindow window, AngleSharp.Dom.IElement element, System.String pseudo) (at <e21e4035785343bfa23606c51eaa0ef2>:0)

CODE (P.S. the code is only for this test):
```
var config = Configuration.Default;
config.WithCss();
using var context = BrowsingContext.New(config);
using var doc = await context.OpenAsync(_req => _req.Content(html));
var span = doc.LastElementChild.LastElementChild.LastElementChild.FirstElementChild;
var style = doc.DefaultView.GetComputedStyle(span);
```

Thank you so much!

**Comment by FlorianRappl** [comment]
1. You need to use AngleSharp.Css - right now you are not using it (`WithCss` returns a new config - you do nothing with the returned config)
2. In order to compute styles you need a render device - but no such device is registered

Please read the README of AngleSharp.Css (https://github.com/AngleSharp/AngleSharp.Css) and place questions / issues regarding AngleSharp.Css there.

Hope that helps!
