### ISSUE TITLE
StyleSheets empty in 1.0.0

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp#1083]
The `StyleSheets` property is empty in 1.0.0. Do I need to change something?

```c#
var config = Configuration.Default.WithCss();
var parser = new HtmlParser(new HtmlParserOptions { IsScripting = true }, BrowsingContext.New(config));
var html = "<html><head><style>body { background-color: rgba(255, 255, 255, 1); }</style></head><body><div>Test</div></body></html>";
var dom = parser.ParseDocument(html);
var stylesheetCount = dom.StyleSheets.Count(); // -> 1 in 0.17.1, 0 in 1.0.0
```

**Comment by FlorianRappl** [comment]
Nothing was changed here - also this is most likely the wrong repo for it as stylesheets is AngleSharp.Css.

**Comment by mganss** [comment]
Oops, sorry. Shall I open in AngleSharp.Css?

**Comment by FlorianRappl** [comment]
As mentioned nothing here changed - I'd recommend first to investigate what exactly the issue is before opening any issue somewhere.

**Comment by mganss** [comment]
The issue is that the `StyleSheets` property should not be empty. The example code hasn't changed either. The version of AngleSharp.Css is 0.16.4 in both cases. Don't know how to investigate further 🤷🏻

**Comment by mganss** [comment]
I think I know what's going on. 
Something ***has*** changed, the signature of the `Event`  constructor in https://github.com/AngleSharp/AngleSharp/commit/d9f3bc7a6e54ca83aa6f5c3ef44f1a130f33012c
AngleSharp.Css 0.16.4 was built against an older version which did not have the additional parameter. This causes `MissingMethodException`s to be thrown when the non-existing constructor overload is called from code in AngleSharp.Css.
These execeptions seem to get swallowed.
In this particular case it's a `CssParseEvent` that gets constructed in `CssParser.ParseStylesheetAsync()`.

**Comment by FlorianRappl** [comment]
Thanks for the investigation.

Yes, AngleSharp.Css 0.16.x is of course only compatible with AngleSharp 0.16.x - that's why we always released all auxiliary libs on the same version. There is no 1.0 of AngleSharp.Css or any other auxiliary lib yet.

**Comment by mganss** [comment]
OK got it. I wasn't aware of this. Luckily, AngleSharp.Css 0.16.4 seems to work fine with AngleSharp 0.17 (for my use case at least). Shouldn't this requirement be reflected in the NuGet dependencies of AngleSharp.Css?

**Comment by FlorianRappl** [comment]
It is reflected there - we just don't pin the version to allow scenarios like the one you had here. As far as I know NuGet does not support semantic versioning via ranges (using things like `^`, `~` etc.), but that might have changed.

For the 1.0 of the auxiliary libraries we could pin it to `[1.0,2.0)` - essentially achieving the desired `^`.
