### ISSUE TITLE
StackOverflowException when accessing the StyleSheets property

### ISSUE THREAD

**Issue by bjornri** [AngleSharp/AngleSharp#1084]
# Description
If you have a sufficiently deep DOM, accessing the `StyleSheets` property on a parsed document causes a StackOverflowException to be thrown by AngleSharp. 

After some investigation I found that this is because the method `StyleExtensions.GetStyleSheets()` uses the program stack to iterate the DOM in a recursive way.

## Background
Our application running in IIS somtimes see StackOverflowExceptions when sanitizing HTML documents. We use [HtmlSanitizer](https://github.com/mganss/HtmlSanitizer) which uses AngleSharp to parse the document. This [issue](https://github.com/mganss/HtmlSanitizer/issues/417) is the same as we are having and there was a similar issue in HtmlSanitizer, which is now fixed. However, we still get StackOverflowException from AngleSharp. 

When we get a StackOverflowException, the entire app crash and needs to be restarted by IIS.

When an application is running in IIS it has a relatively small stack size compared to if you are running a console application (256KB for 32bit app and 512KB for 64bit app). Hence the demo application below tries to replicate the "IIS environment".

## Steps to reproduce:

Using this sample application with a relatively low stack size similar to what an application running in IIS gets by default. Create a new solution with this code, add AngleSharp (v1.0.1) and AngleSharp.Css (v.0.17.0) Nuget packages. Build and run the application and observe it throws StackOverflowException in `StyleExtensions.GetStyleSheets()`.

```c#
using AngleSharp;
using AngleSharp.Html.Parser;

var thread = new Thread(() =>
{
    var beginTags = String.Join("", Enumerable.Repeat("<div>", 10000));
    var endTags = String.Join("", Enumerable.Repeat("</div>", 10000));
    var html = $"<html><head><style></style></head><body>{beginTags}<style></style>{endTags}</body></html>";

    var context = BrowsingContext.New(Configuration.Default.WithCss());
    var document = context.GetService<IHtmlParser>()!.ParseDocument(html);

    var sheets = document.StyleSheets;
    Console.WriteLine(sheets.Length);
}, 512 * 1024);

thread.Start();
thread.Join();
```

## Possible solution
While we could try to mess with stack sizes in our application, create new threads and similar - a better solution would be if AngleSharp did not throw an exception in the first place. 

A way to achieve this is to use a stack on the heap instead of the program stack when iterating the DOM. I am currently working on a pull request with this change.

**Comment by FlorianRappl** [comment]
Merged and will be part of the next release.
