### ISSUE TITLE
Question: Does the css parser implement the css-3 parsing algorithm?

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#110]
Hi, this is a question I've been asked to answer, since I'm recommending the use of AngleSharp as a css parser.

"Does the css parser implement the parsing algorithms exactly as described in http://dev.w3.org/csswg/css-syntax-3/#parser-algorithms? In particular, does the error handling match the specification?"

I'd appreciate a clear answer to this so that I can communicate it.

**Comment by FlorianRappl** [comment]
Yes, this was the specification after which I've built the parser.
