### ISSUE TITLE
The official website not working

### ISSUE THREAD

**Issue by nirzaf** [AngleSharp/AngleSharp#1106]
# Bug Report
The official website not working

https://anglesharp.github.io/

<img width="264" alt="image" src="https://user-images.githubusercontent.com/18024930/221827437-7d95514f-2c8a-4526-bb11-8878c654a351.png">

**Comment by FlorianRappl** [comment]
It's working for me - can you check with your ISP?

We also had the problem that you use some custom middleware on your machine (e.g., some network hijackers), which might block the resources.

(A good objective check is always to visit web.dev/measure and check what this page "sees":https://pagespeed.web.dev/report?url=https%3A%2F%2Fanglesharp.github.io%2F&form_factor=desktop - see below

![image](https://user-images.githubusercontent.com/1766191/221831154-7109b93c-46b9-4ba6-93ad-d33677c3022e.png)

obviously the page is working in general, which means the problem sits on your machine / network)
