### ISSUE TITLE
Missing semicolons in @page rule

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp#1108]
```c#
var html = "<html><body><style>@page { margin: 25mm }</style></body></html>";
var parser = new HtmlParser(new HtmlParserOptions(), BrowsingContext.New(Configuration.Default.WithCss(new CssParserOptions())));
var dom = parser.ParseDocument(html);
var styleSheet = dom.StyleSheets.OfType<ICssStyleSheet>().First();
var css = styleSheet.ToCss(); // -> "@page { margin-top: 25mm margin-right: 25mm margin-bottom: 25mm margin-left: 25mm }"
```

This was originally reported as https://github.com/mganss/HtmlSanitizer/issues/438.

**Comment by FlorianRappl** [comment]
CSS is not part of AngleSharp.Core.

**Comment by FlorianRappl** [comment]
> CssStyleFormatter.cs is part of this repository, isn't it?

Yes, and? The issue seems to be in the serialization of the specific rule, not of a stylesheets in general. That makes a huge difference. The style formatter (as any formatter) does not know or need to know rules and their internals. It does not serialize declarations or rules.

**Comment by mganss** [comment]
@FlorianRappl Will you transfer the issue or shall I open a new one in AngleSharp.Css?
