### ISSUE TITLE
Accessing Document.ReadyState in JavaScript exposes enum value instead of string

### ISSUE THREAD

**Issue by Sebbs128** [AngleSharp/AngleSharp#1109]
# Bug Report

## Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

When JavaScript in a HTML document reads the `document.readyState` property, the value returned is a digit (the underlying value of the `DocumentReadyState` enum) instead of the expected string (such as `"loading"` or `"complete"`).

Although this requires AngleSharp.Js to expose that the value is incorrect, because the `document.readyState` property comes from the core library I believe this is the correct place to report it.

## Steps to Reproduce

Reproduction using Top Level Statements

```csharp
using AngleSharp;
using AngleSharp.Js;

string html = """
            <html>
                <head>
                    <script type="text/javascript">
                        document.onreadystatechange = function() {
                            console.log("Document OnReadyStateChange fired");
                            console.log(document.readyState);
                            
                            if (document.readyState == "complete")
                                console.log("document state is complete");
                                
                            if (document.readyState == 1)
                                console.log("document state is 1");
                        };
                    </script>
                </head>
            </html>
            """;

var browserContext = BrowsingContext.New(Configuration.Default
    .WithJs()
    .WithConsoleLogger(ctx => new ConsoleLogger())
    .WithEventLoop());

var doc = await browserContext.OpenAsync(m => m.Content(html)).WhenStable();

class ConsoleLogger : IConsoleLogger
{
    public void Log(object[] values)
    {
        var elements = values.Select(m => (m ?? String.Empty).ToString());
        var content = String.Join(", ", elements);
        Console.WriteLine(content);
    }
}
```

Output will be
```
Document OnReadyStateChange fired
1
document state is 1
Document OnReadyStateChange fired
2
```

**Expected behavior:** [What you expected to happen]

`document.readyState` call in JavaScript should return a string of either `"loading"`, `"interactive"`, or `"complete"`

**Actual behavior:** [What actually happened]

`document.readyState` call in JavaScript is returning the underlying enum value (ie. `0`, `1`, or `2`)
**Environment details:** [OS, .NET Runtime, ...]
OS: Win11x64
Runtime: .NET 7.0.201

## Possible Solution

Simplest would be to replace the `DocumentReadyState` enum with constant or static readonly strings, even though that's not always the nicest to code against (and would result in a breaking change).

I'm not sure if there's some way within AngleSharp to expose the `document.readyState` differently (as a string) to the JS execution engine, while keeping the .NET side as an enum. Maybe AngleSharp.Js is the correct place to fix it after all with some extra layer in between to translate the enum.

**Comment by FlorianRappl** [comment]
Will be part of 1.0.2.

**Comment by Sebbs128** [comment]
Thanks @FlorianRappl 

I just updated my console test to use v1.0.2 (and tried v1.0.3 as well) and the Javascript is still seeing only the enum int values, not the serialized values introduced in the `DomName` values introduced in commit efa35b1.

Just to be clear, the current (non-working) output of the minimal reproduction is
```
Document OnReadyStateChange fired
1
document state is 1
Document OnReadyStateChange fired
2
```

However, the expected output (as confirmed in a browser) is
```
Document OnReadyStateChange fired
interactive
Document OnReadyStateChange fired
complete
document state is complete
```
(ie. the `"document state is 1"` log output shouldn't be written)

**Comment by FlorianRappl** [comment]
Well, I'd say this is rather an issue with AngleSharp.Js than AngleSharp as .NET can never provide string values and the `DomName` should be taken.

In any case if you think this is an issue with AngleSharp (or if you want to correct the behavior of AngleSharp.Js) then please make a PR with the appropriate changes. This is an open-source project.

**Comment by Sebbs128** [comment]
Understood. 😊 I'll see if I can work out some time to get it sussed and a PR over there.
