### ISSUE TITLE
System.ArgumentOutOfRangeException in HtmlParser

### ISSUE THREAD

**Issue by mretlenj** [AngleSharp/AngleSharp#111]
Hi, we encountered an issue in HtmlParser.

We have a following piece of code:
var config = new Configuration().WithCss();
var document = new HtmlParser(text, config).Parse();

where "text" is some html email we need to process. When e-mail contain style that have "mso-style-link" or "mso-style-name" attribute that starts with "\", collection of styles on document object is not accessible. It throws System.ArgumentOutOfRangeException with explanation: "A valid UTF32 value is between 0x000000 and 0x10ffff, inclusive, and should not include surrogate codepoint values (0x00d800 ~ 0x00dfff)". Example of problematic style is as following:

span.berschrift2Zchn
    {mso-style-name:"\00DCberschrift 2 Zchn";
    mso-style-priority:9;
    mso-style-link:"\00DCberschrift 2";
    font-family:"Cambria","serif";
    color:#4F81BD;
    font-weight:bold;}

What is best way to address this issue? Will this be addressed in upcoming releases? We reproduced it in both 0.8.3 and 0.8.5. versions.

**Comment by FlorianRappl** [comment]
The next release should take care of that. I think v0.8.6 will be published this Wednesday. Thanks for the report!

**Comment by mretlenj** [comment]
Whoah, that was quick!
Thx, again :)

**Comment by FlorianRappl** [comment]
I guess MSO style strings are written in a way to be invalid from an CSS3 POV. CSS3 will consume 6 hex-digits. In this case not only `00DC` are consumed, but also two more letters, resulting in `00DCbe`. This not only lead to the surrogate violation (which should have been handled - and is now handled), but will also result in a different string than anticipated. However, against the latter there is nothing I can do. The CSS3 syntax specification tells me to gather up to 6 hex digits; A-Fa-f0-9.
