### ISSUE TITLE
SelfClosing Tags have incorrect html, generated unclosed tags.

### ISSUE THREAD

**Issue by jbrayfaithlife** [AngleSharp/AngleSharp#1111]
# Bug Report

## Prerequisites

- [/] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [/] Are you running the latest version of AngleSharp?
- [/] Did you check the FAQs to see if that helps you?
- [/] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [/] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Given a self-closing tag such as `<input type='text' />`, doing a `ToHtml()` on it, or using the `OuterHtml` property both return an unclosed tag.

## Steps to Reproduce
```
var config = Configuration.Default;
var context= BrowsingContext.New(config);
var source = "<input type='text' />";
var document = await context.OpenAsync(req => req.Content(source));
var input = document.QuerySelector("input");
input.OuterHtml.Dump();
input.ToHtml().Dump();
```
**Expected behavior:** returns `<input type='text' />`

**Actual behavior:** returns `<input type='text'>`

**Environment details:** Windows, .NET 6.0.14

## Possible Solution

https://github.com/AngleSharp/AngleSharp/blob/3a21e4c65b53dbd53d35dee4b1f692659a7f535e/src/AngleSharp/Html/HtmlMarkupFormatter.cs#L69

I believe the above line needs to have a code path that adds `/>` when `selfClosing` is true.

**Comment by jbrayfaithlife** [comment]
I can make a PR for this, feel free to assign me.

**Comment by jbrayfaithlife** [comment]
PR made https://github.com/AngleSharp/AngleSharp/pull/1112

**Comment by FlorianRappl** [comment]
Please read the HTML5 specification.

Self-closed tags are represented as `<img>` or `<input>` in HTML. The XML syntax is just tolerated on those elements, but its not an actual syntax (e.g.,  `<div />` is actually just `<div>`, i.e., an open div-element).

Before reporting an issue here check with your browser. You'll see that it has the same behavior as browsers also follow the same specification.

**Comment by jbrayfaithlife** [comment]
Learn something new every day. For anyone's future reference, this came out of a project where we are manipulating XHTML. Apparently I misunderstood the relationship between the various specs.

**Comment by FlorianRappl** [comment]
We also have an XHTML formatter - so the parsed DOM could be represented in XHTML (here, we place the solidus; see https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Xhtml/XhtmlMarkupFormatter.cs#L103).
