### ISSUE TITLE
Make HtmlTokenizer public

### ISSUE THREAD

**Issue by SebastianStehle** [AngleSharp/AngleSharp#1113]
# New Feature Proposal

## Description

This is more a discussion and not really a feature request. The question is:

1. Would you make the HtmlTokenizer public?
2. Is there an easy way to understand when a subtree has been handled? e.g. like https://learn.microsoft.com/de-de/dotnet/api/system.xml.xmlreader.readsubtree?view=net-7.0

## Background

Together with a contributor from Github I have created a port of the mjml to .NET: https://github.com/SebastianStehle/mjml-net

If you don't know mjml: It is a markup language for HTML emails (https://mjml.io/try-it-live) and our goal was to provide a very fast implementation for .NET. This has succeeded and it is actually the fastest 

But MJML is not really xml, it can contain html snippets. So like 2% of the input files cannot be parsed directly and need some preprocessing. Especially for things like. We have written a simple fix that can be applied before saving a template to disk or to database, but it just works and is not very sophisticated: https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net/XmlFixer.cs

* Ambersand in attribute values.
* Self closing HTML tags like `<br>` or `<input>`
* `<` or `>` characters in text.

So the idea was to either...

1. Move to html parsing and anglesharp seems to be the only candidate here. This would mean a decrease in performance because XmlReader is very fast.
2.  Reimplement the fixer with HTML parsing to convert the input to valid XML.

For both solutions it would be great if the tokenizer can be made public, because we don't need features and the overhead of HtmlDocument.

## Specification

In case of updates that adhere to specification changes, please reference the used specification.

**Comment by FlorianRappl** [comment]
The reason for not making it public is that it's another API that needs to be kept stable. While the API seems to be quite fixed, I can imagine cases where functionality just needs to be added / changed.

You should be able to use the tokenizer already via reflection. I understand that using it directly via a public API would be easier, but I fear that this would exceed the available maintenance capacity. I'm still open for a discussion and maybe there is a good way in the middle to achieve this.

**Comment by SebastianStehle** [comment]
Yes, I totally understand that. Perhaps we could make it like this:

```
public class HtmlTokenizer {
   internal HtmlTokenizer() {
   }
}

public class ExperimentalHtmlTokenizer : HtmlTokenizer {
}
```

or something like this to mark the tokenizer as unstable. Otherwise I would fork the project and publish my own version (as private nuget package).

**Comment by FlorianRappl** [comment]
OK the API surface is rather minimal and the constructor as well as the methods should be fine. This will be public with the next release.
