### ISSUE TITLE
Stripping off prefixes to attributes in XhtmlMarkupFormatter

### ISSUE THREAD

**Issue by jbrayfaithlife** [AngleSharp/AngleSharp#1114]
# Bug Report
Not sure whether this is a bug with the `XhtmlMarkupFormatter` or the `XmlElement`, so I'm not 100% sure this is the right repo for the bug report, but I was able to temporarily work around the issue by subclassing the XhtmlMarkupFormatter

Given an XmlElement that contains an attribute `epub:type`, the XhtmlMarkupFormatter renders the element with the attribute `type` instead. 

## Prerequisites

- [/] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [/] Are you running the latest version of AngleSharp?
- [/] Did you check the FAQs to see if that helps you?
- [/] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [/] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

`XmlElement` attributes are not written correctly by the XhtmlMarkupFormatter.

## Steps to Reproduce
```
var xmlParser = new XmlParser();
var doc = xmlParser.ParseDocument("<span epub:type='jump'>Test</span>");
using (var stringWriter = new StringWriter()){
	doc.ToHtml(stringWriter, new XhtmlMarkupFormatter());
	stringWriter.ToString().Dump();
}
```

**Expected behavior:** Dump returns `<span epub:type='jump'>Test</span>`

**Actual behavior:** Dump returns `<span type='jump'>Test</span>`

**Environment details:** Win 10; .NET 6.0.15

## Possible Solution

I was able to get the markup to render correctly by overriding the `Attribute` method in the MarkupFormatter modifying the following lines https://github.com/AngleSharp/AngleSharp/blob/ebf660279f9f4c74cbade95e38e7d7d93b74dac2/src/AngleSharp/Xhtml/XhtmlMarkupFormatter.cs#L130-L135

to 
```
var namespaceUri = attribute.NamespaceUri;
var prefix = attribute.Prefix;
var localName = attribute.LocalName;
var value = attribute.Value;
var temp = StringBuilderPool.Obtain();

// Added the `string.IsNullOrEmpty(prefix)` in a variation from the AngleSharp code
// because otherwise it was stripping off the prefix and making malformed XML
if (string.IsNullOrEmpty(namespaceUri) && string.IsNullOrEmpty(prefix))
{
temp.Append(localName);
}
```
which causes it to fall into the `else` case, just appending the `Name` directly, including the prefix. (https://github.com/AngleSharp/AngleSharp/blob/ebf660279f9f4c74cbade95e38e7d7d93b74dac2/src/AngleSharp/Xhtml/XhtmlMarkupFormatter.cs#L153)

If my assessment of the issue is correct I'd be happy to open a PR with this change

**Comment by FlorianRappl** [comment]
Yes we can do a PR, but keep in mind that the expectation, e.g., for HTML attribute serialization should not change. I'm not sure if the logic has to be more complicated to avoid side-effects, but we'll see. PR appreciated!
