### ISSUE TITLE
Range start or end cannot be set to a specific offset in a TextNode

### ISSUE THREAD

**Issue by zickb** [AngleSharp/AngleSharp#1118]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

The `Range` start or end cannot be set to a specific offset in a `TextNode`.

## Steps to Reproduce

1. Create a text node: `var testNode = _document.CreateTextNode("this is a test");`
2. Try to create a 'Range' which starts on a offset greater then 0:
```csharp
var testRange = _document.CreateRange();
testRange.StartWith(testNode, 5);
```

**Expected behavior:** The `Range` starts with the specified node and offset.

**Actual behavior:** A `DomException` is thrown. (AngleSharp.Dom.DomException: The index is not in the allowed range.)

## Possible Solution

Maybe it is enough to special case `TextNode`s in the `StartWith` method.
https://github.com/AngleSharp/AngleSharp/blob/1b7a7a1410ce272b0600b9cee6aafefdf7ee8e99/src/AngleSharp/Dom/Internal/Range.cs#L84

**Comment by FlorianRappl** [comment]
Will be part of 1.0.2.
