### ISSUE TITLE
Range.CommonAncestor returns always null if Range.Head is not the same or a descandent node of Range.Tail

### ISSUE THREAD

**Issue by zickb** [AngleSharp/AngleSharp#1119]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

If `Range.Head` is not the same or a descendant node of `Range.Tail`, then `Range.CommonAncestor` returns always null instead of the real common ancestor.

## Steps to Reproduce

1. Create a dom tree like `<p><em>Text1</em>Text2</p>`
2. Set the range start to "Text1" and the range end to "Text2"
3. Call `Range.CommonAncestor`

**Expected behavior:** returns the paragraph node

**Actual behavior:** return `null`

## Possible Solution

Check for `container.Contains(Tail)` in the `Range.CommonAncestor` getter. (instead of `Tail.Contains(container)`)
https://github.com/AngleSharp/AngleSharp/blob/1b7a7a1410ce272b0600b9cee6aafefdf7ee8e99/src/AngleSharp/Dom/Internal/Range.cs#L59

**Comment by FlorianRappl** [comment]
Will be part of 1.0.2.
