### ISSUE TITLE
CSS parsing issue with unknown rules with parser option set

### ISSUE THREAD

**Issue by D92130** [AngleSharp/AngleSharp#112]
For the following testing code:

 var cssParserOptions = new AngleSharp.Parser.Css.CssParserOptions();
            cssParserOptions.IsIncludingUnknownDeclarations = true;
            cssParserOptions.IsIncludingUnknownRules = true;
            cssParserOptions.IsToleratingInvalidConstraints = true;
            cssParserOptions.IsToleratingInvalidValues = true;

```
        string css = "@-ms-viewport{width:device-width} .dsip { display: block; }";

        var doc = new AngleSharp.Parser.Css.CssParser(css).Parse();
        string cssResult1 = doc.CssText;

        doc = new AngleSharp.Parser.Css.CssParser(css).Parse(cssParserOptions);
        string cssResult2 = doc.CssText;

        css = "@media screen and (max-width: 400px) {  @-ms-viewport { width: 320px; }  }  .dsip { display: block; }";

        doc = new AngleSharp.Parser.Css.CssParser(css).Parse();
        string cssResult3 = doc.CssText;

        doc = new AngleSharp.Parser.Css.CssParser(css).Parse(cssParserOptions);
        string cssResult4 = doc.CssText;
```

The end result for cssResult 1 is:  
.dsip { display: block; }  
This is kind of acceptable.

cssResult 2:  
@-ms-viewport { }
This is not acceptable because style definitions after the @-ms-viewport definition got stripped out.

cssResult 3:
@media screen and (max-width: 400px) { }
.dsip { display: block; }
This is kind of acceptable

cssResult 4:
@media screen and (max-width: 400px) { @-ms-viewport   { .dsip { display: block;
 } } }
This is not acceptable, 2 rules definition got messed up together.

**Comment by FlorianRappl** [comment]
I will have a look at this.
