### ISSUE TITLE
Moving to the new .NET Foundation CLA service

### ISSUE THREAD

**Issue by ChrisSfanos** [AngleSharp/AngleSharp#1120]
Hi AngleSharp admins - the .NET Foundation is moving all projects to the new CLA service.  We need to make a set of config changes to your project to get that setup.  Please drop me a note at chris.sfanos @ dotnetfoundation.org to chat - either we can do the work for you or you can cover it - whichever you prefer

Thanks
Chris
.NET Foundation Operations Team

**Comment by FlorianRappl** [comment]
Can you elaborate what the benefit of that is? We have our own CLA service and it works just great. I don't see any need to change that, which is why I would require some insights on the value-add.

**Comment by ChrisSfanos** [comment]
Hi @FlorianRappl - as a member project of the .NET Foundation, we centralize all projects on the same CLA.  That said, I'm happy to have some internal conversations around this

**Comment by FlorianRappl** [comment]
Please do so - I don't see the value-add.

**Comment by ChrisSfanos** [comment]
Will do - it'll be next week when the team meets.  I'll follow up after - thanks!

**Comment by ChrisSfanos** [comment]
Hi @FlorianRappl - I wanted to clarify the .NET Foundation Contributor License Agreement (CLA) policy.

In general, CLA's offer the following benefits.

•	A consistent experience for developers who contribute to projects and repos that share a CLA.  They are only required to sign one CLA.
•	Perfect clarity on project copyright at the point of PR merge. 
•	Enable the .NET Foundation to (straightforwardly) defend project copyright in the case of legal disputes.

The .NET Foundation CLA policy aligns with [Apache](https://www.apache.org/licenses/contributor-agreements.html). We see Apache as defining the best practice for OSS foundations. [LLVM](https://llvm.org/) is another interesting [case study](https://blog.llvm.org/posts/2021-11-18-relicensing-update/). The [difficult process](https://lwn.net/Articles/701155/) they went through was primarily required due to not having used a CLA (even though they didn't adopt one in the end). Most projects don't have that scale of challenges, however, CLAs enable significant future clarity and flexibility that may be valued in the future.

We have uniform licensing policies for all projects, which includes using the CLA. As a member project, we need you to move forward with adopting the .NET Foundation CLA.  Our Operations team will happily assist with installation and configuration and any questions you have.

We're also happy to have a call to discuss this further if that would help.
 
Thanks
Chris
DNF Operations Team

**Comment by FlorianRappl** [comment]
Well, that answer seems scripted. I know what a CLA is and AngleSharp is already using a CLA. So the main point is missing; how is this now different to what we have right now? Also, what benefits does it have for the project (in the sense of changing from the current CLA to this one)?

Right now being in the .NET Foundation has no real benefit for this project. There is no additional support or any contribution incoming. If I am now forced into weird bureaucratic demands I'll need to withdraw from being a member - as it stands there is enough work to be done on the project; I don't need any additional obligations (especially if nothing comes out of it in return).

**Comment by ChrisSfanos** [comment]
Hi @FlorianRappl  - yes, this change is primarily to protect the .NET Foundation and provide a uniform CLA experience across all our member projects.
