### ISSUE TITLE
CSS property not removed by RemoveProperty

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp#113]
`RemoveProperty` does not in fact remove the property in some cases:

``` C#
var html = @"<DIV STYLE='background: url(""javascript:alert(foo)"")'>";
var parser = new HtmlParser(new Configuration().WithCss(e => e.Options = new CssParserOptions
{
    IsIncludingUnknownDeclarations = true,
    IsIncludingUnknownRules = true,
    IsToleratingInvalidConstraints = true,
    IsToleratingInvalidValues = true
}));
var dom = parser.Parse(html);
var div = (IHtmlElement)dom.QuerySelector("div");
var bg = div.Style.First(p => p.Name == "background");
div.Style.RemoveProperty(bg.Name);
var removed = !div.Style.Any(p => p.Name == "background"); // false
var s = div.ToHtml(); // <div style="background: url(&quot;javascript:alert(foo)&quot;);"></div>
```

**Comment by FlorianRappl** [comment]
You know that `background` is a shorthand and no real property. That being said in the provided scenario you are using unknown declarations, which do not distinguish between shorthands and longhands. Here all declarations are treated as longhands.

At that moment I don't know how to change the behavior. The method just takes a string. Hence we can't evaluate if `Factory.Properties.IsShorthand(propertyName)` makes sense. Maybe it should be checked if the provided shorthand has also been added (which only applies in case unknown declarations are allowed) to the list of declarations. If so, the added property will be removed as usual longhands.

However, I do not know the implications of such a change. I can't come up with any scenario where shorthands are added, thus it might be the best choice. I will also need to check the other algorithms. Seems they may have some hickups with unknown declarations that carry the name of known ones.

**Comment by FlorianRappl** [comment]
I adjusted the behavior of the `CssStyleDeclaration`. It distinguishes now between these two cases. Most algorithms that differentiated between shorthand and longhand now start with the (mostly trivial) longhand check. The shorthand is used only if unknown declarations are forbidden. Otherwise it is known that any name is allowed and nothing specific will be instantiated.
