### ISSUE TITLE
PrettyMarkupFormatter removes newlines from <pre> and <code> elements

### ISSUE THREAD

**Issue by ThanosPapathanasiou** [AngleSharp/AngleSharp#1131]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

When I use PrettyMarkupFormatter to pretty print html it removes newlines from ```<code>``` blocks thus not keeping the code as it was formatted. 

### Steps to reproduce: 

1. Save the code below as example.fsx
2. open terminal in that location and run
3. dotnet fsi example.fsx

```f#
#r "nuget: AngleSharp"

let prettyPrint (rawHtml:string) = 
  let mutable options = AngleSharp.Html.Parser.HtmlParserOptions()
  options.IsSupportingProcessingInstructions <- true

  let parser = AngleSharp.Html.Parser.HtmlParser(options)
  let document = parser.ParseDocument(rawHtml)
  let sw = new System.IO.StringWriter()
  document.ToHtml(sw, new AngleSharp.Html.PrettyMarkupFormatter())
  sw.ToString()

let example_1 = """
<!DOCTYPE html>
<html lang="en"><head><title>Some Title</title></head><body><h1>Test</h1>
<pre><code class="language-F#">let a = "something"
let b = "something else"
let c = "something completely different"
</code></pre>
</body></html>
"""

let formatted_example_1 = prettyPrint example_1

printfn "%s" "Expected:"
printfn "%s" """
<!DOCTYPE html>
<html lang="en">
        <head>
                <title>Some Title</title>
        </head>
        <body>
                <h1>Test</h1>
                <pre>
                        <code class="language-F#">let a = "something"
                        let b = "something else"
                        let c = "something completely different"
                        </code>
                </pre>
        </body>
</html>
"""


printfn "%s" "Actual:"
printfn "%s" formatted_example_1
```

### Steps to Reproduce 

Save this html in a file and feed it as input to PrettyMarkupFormatter

```html
<!DOCTYPE html>
<html lang="en"><head><title>Some Title</title></head><body><h1>Test</h1>
<pre><code class="language-F#">let a = "something"
let b = "something else"
let c = "something completely different"
</code></pre>
</body></html>
```

### Expected Behavior

The html should keep the code formatting as follows

```html
<!DOCTYPE html>
<html lang="en">
        <head>
                <title>Some Title</title>
        </head>
        <body>
                <h1>Test</h1>
                <pre>
                        <code class="language-F#">let a = "something"
                        let b = "something else"
                        let c = "something completely different"
                        </code>
                        </code>
                </pre>
        </body>
</html>
```

### Actual Behavior

This is what happens: (notice, that the code block is all in one line)

```html
<!DOCTYPE html>
<html lang="en">
        <head>
                <title>Some Title</title>
        </head>
        <body>
                <h1>Test</h1>
                <pre>
                        <code class="language-F#">let a = "something" let b = "something else" let c = "something completely different"
                        </code>
                </pre>
        </body>
</html>
```

### Possible Solution / Known Workarounds

Could we have an option to make sure that the content of ```<code>``` blocks is left as is?

**Comment by FlorianRappl** [comment]
Hm, difficult one as the pretty markup formatter is actually not about preserving the structural representation, but rather about making it easier to read / "prettier".

While preserving "pre" and "code" seems obvious in general it is not - their rendering is fully determined by CSS and the `pre` handling of white-space could be turned off here (or turned on for some other element).

Presumably the best way is to introduce an option as you suggested; the option should have an array of elements to preserve their content text (i.e., ignore prettifying it). By default, `code` and `pre` would be in that list.

PRs welcome on this one!

**Comment by dramlian** [comment]
Seems like an interesting issue, could you please assign this on to me? Would really love to work on this one!

**Comment by FlorianRappl** [comment]
Sure @dramlian - thanks for picking this one up. Let me know if you want to have a discussion / need some pointers.
