### ISSUE TITLE
Nuget update to 1.0.4

### ISSUE THREAD

**Issue by Wayne-Mather** [AngleSharp/AngleSharp#1132]
### Description

Hi,

Do you have an ETA when you will push 1.0.4 to nuget?

**Comment by WolfgangKluge** [comment]
Maybe a cache problem?

https://www.nuget.org/packages/AngleSharp
![image](https://github.com/AngleSharp/AngleSharp/assets/639482/6d961f55-a889-4c2b-b22b-8cca4a166682)

**Comment by Wayne-Mather** [comment]
Hi,

Thanks for your response but  i asked about AngleSharp.CSS not being the
alpha release: https://www.nuget.org/packages/AngleSharp.Css/1.0.0-alpha-99.
Maybe I posted my question to the wrong repository then?

**Comment by FlorianRappl** [comment]
AngleSharp CSS is right now not even 1.0.0, so your question is misleading for a couple of reasons.
