### ISSUE TITLE
DOM Tree inside <pre> if URL ends with ".txt"

### ISSUE THREAD

**Issue by acidus99** [AngleSharp/AngleSharp#1138]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

When parsing a string of HTML using a virtual request, AngleSharp returns a DOM tree where the HTML is HTML encoded and placed inside a `<pre>` if the URL used in the `Address()` method ends with a ".txt". It's like a pretty print special mode for a text file.

Despite the URL ending in ".txt" the supplied HTML string really is HTML. Perhaps "special output for .txt files" is a specific feature. However:
* It's not obvious that this is what will happen. I can't find any mention in the docs about this behavior, searching for "txt" or "text file"
* Plenty of URLs exist in the wild where what .NET URI class thinks of as a filename or file extension is ".txt" when the content is not a .txt
* I cannot figure out how to disable this if it is a purposeful feature.

### Steps to Reproduce

The run the snippet of code below. The URL ends with `.html` and the output is correct.

```
var context = BrowsingContext.New(Configuration.Default);
var parser = context.GetService<IHtmlParser>();

string url = "https://www.example.com/foo.html";
string html = "<h1>this is a test</h1>";

IDocument document = context.OpenAsync(req => req.Address(url).Content(html)).Result;
Console.WriteLine(document.DocumentElement.OuterHtml);
```
Prints:
```
<html><head></head><body><h1>this is a test</h1></body></html>
```

Where as this URL has a `.txt` ending, and the output of AngleSharp is some kind of pretty-print formatting for a text file.
```
url = "https://www.example.com/foo.html.txt";
document = context.OpenAsync(req => req.Address(url).Content(html)).Result;
Console.WriteLine(document.DocumentElement.OuterHtml);
```
Prints
```
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">&lt;h1&gt;this is a test&lt;/h1&gt;</pre></body></html>

```

### Expected Behavior

If I pass in an HTML string, AngleSharp should parse that into a DOM tree, regardless of the file name/ extension of the URL for that HTML string. 

More specifically, output from both `Console.WriteLine()` calls should be "<html><head></head><body><h1>this is a test</h1></body></html>"

### Actual Behavior

Output for URLs ending in .txt is an odd, incorrect DOM representation of HTML string:

```
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">&lt;h1&gt;this is a test&lt;/h1&gt;</pre></body></html>
```

### Possible Solution / Known Workarounds

I could possibly not use the `Address()` method in the virtual request. However that means I could not use `anchor.HyperReference(anchor.Href)` to get absolute URLs for resources as I'm walking the DOM

**Comment by FlorianRappl** [comment]
It is a purposeful feature - and actually it is not mainly determined by the extension (this is a fallback), but rather what the webserver says the content is.

```cs
var context = BrowsingContext.New();
var url = "https://www.example.com/foo.html.txt";
var html = "<p>Hello!</p>";
var document = context.OpenAsync(req => req.Address(url).Content(html)).Result;
Console.WriteLine(document.DocumentElement.OuterHtml);
```

This results in:

```html
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">&lt;p&gt;Hello!&lt;/p&gt;</pre></body></html>
```

Let's add the appropriate `Content-Type` header, which determines the content type:

```cs
var context = BrowsingContext.New();
var url = "https://www.example.com/foo.html.txt";
var html = "<p>Hello!</p>";
var document = context.OpenAsync(req => req.Address(url).Header("Content-Type", "text/html").Content(html)).Result;
Console.WriteLine(document.DocumentElement.OuterHtml);
```

The result is:

```html
<html><head></head><body><p>Hello!</p></body></html>
```

The behavior matches the one found in browsers, which also look up the mime type from the extension if no explicit content-type is given from the webserver.

Hope that helps!
