### ISSUE TITLE
Entities decoded in InnerHtml of noscript

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp#1139]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

Entities always seem to be decoded when getting `InnerHtml` of a `noscript` element.

This only occurs if `IsScripting` is true.

Is this related to #1070?

### Steps to Reproduce

```c#
var html = @"<html></head><body><noscript><div></div></noscript></body></html>";
var parser = new HtmlParser(new HtmlParserOptions { IsScripting = true }, 
    BrowsingContext.New(Configuration.Default.WithCss(new CssParserOptions())));
var dom = parser.ParseDocument(html);
var noscript = dom.QuerySelector("noscript");
var text = noscript.InnerHtml; // "<div></div>"
text = text.Replace("<", "&lt;").Replace(">", "&gt;"); // "&lt;div&gt;&lt;/div&gt;"
noscript.InnerHtml = text; // still "<div></div>"
```

### Expected Behavior

`InnerHtml` yields `"&lt;div&gt;&lt;/div&gt;"` after setting.

### Actual Behavior

`InnerHtml` yields `"<div></div>"`.

### Possible Solution / Known Workarounds

Workaround: Call `SetInnerText()`

**Comment by FlorianRappl** [comment]
Fixed and part of 1.0.6.
