### ISSUE TITLE
Range's functions StartWith and EndWith don't set the End offset

### ISSUE THREAD

**Issue by zukarusan** [AngleSharp/AngleSharp#1147]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

I happened to use `ClearContent` function on AngleSharp.Dom.IRange 

To use that I created a Range object from an existing document and then set both start & end nodes.
After that I intended to clear the content within the selection of the range but it didn't.
Later when I debug my code and I found that after it called `StartWith()` it did set the `Start` offset property in the range object.
But when it called `EndWith()` function afterwards, it didn't set `End` property, i.e. didn't change at all (Usually in VS debug mode we can see whether a variable did change within Locals panel).

So I trace the code in the github and saw at src/AngleSharp.Core.Tests/Library/Range.cs:
```csharp
...
            if (!_start.IsExplicit)
            {
                _start = bp;
                _end = bp;
            }
            else if (bp < _start || Root != refNode.GetRoot())
            {
                _end = bp;
            }
...
```

The expression `bp < _start` compares two objects with the class Boundary, the operator function I saw:
```csharp
        private readonly struct Boundary : IEquatable<Boundary>
        {
...
            public static Boolean operator >(Boundary a, Boundary b)
            {
                return false;
            }

            public static Boolean operator <(Boundary a, Boundary b)
            {
                return false;
            }
...
```

It by default returns false value. 
Which I believe it is the reason why my ClearContent didn't work due to End property not being set.

### Steps to Reproduce

I have this function to remove between strings
```csharp
        private static void RemoveBetweenStrings(string start, string end, INode nodeStart, INode nodeEnd, IDocument doc)
        {
            var parentStart = nodeStart.Parent;
            var parentEnd = nodeEnd.Parent;
            var range = doc.CreateRange();
            var offsetStart = nodeStart.NodeValue.IndexOf(start); // I checked this value, non-zero, non-negative
            var offsetEnd = nodeEnd.NodeValue.IndexOf(end) + end.Length; // this too

            range.StartWith(nodeStart, offsetStart); // successfully set both Start and End property
            range.EndWith(nodeEnd, offsetEnd); // didn't set/modify the End property

            range.ClearContent(); // didn't clear the content in-between start & node range

            Action<INode> removeIfEmpty = (node) => {
                var text = node.Text();
                if (doc.Contains(node) && string.IsNullOrWhiteSpace(text))
                    node.Parent.RemoveChild(node);
            };
            removeIfEmpty(parentStart);
            removeIfEmpty(parentEnd);
        }
```

so I can test it using parser and AngleSharp.XPath:
```csharp
string start = "{!START}";
string end = "{!END}";
var parser = new HtmlParser();
var doc = parser.ParseDocument(@"<html>
<head></head>
<body>
<p> no deletion before start {!START} this should be cleared </p>
<p> this should be deleted too {!END} This is not to be deleted</p>
<p> this should not be deleted either</p>
</body></html>");
var startNode = doc.Body.SelectSingleNode($"//*//text()[contains(., '{start}')]");
var endNode = doc.Body.SelectSingleNode($"//*//text()[contains(., '{end}')]");
RemoveBetweenStrings(start, end, startNode, endNode, doc); //  this is an expected bug, not being able to delete
```

### Expected Behavior

I think it's because of
```csharp
public static Boolean operator <(Boundary a, Boundary b)
{
          return false;
}
```

the operator should return the actual position comparison value between both nodes within the html dom tree.

### Actual Behavior

This piece of code didn't set the end property after setting the start property
```csharp
range.EndWith(nodeEnd, offsetEnd); // didn't set/modify the End property
```

### Possible Solution / Known Workarounds

I saw the algorithm to set whether the boundary point is equal, before, or after in this ref:
https://dom.spec.whatwg.org/#boundary-points

**Comment by FlorianRappl** [comment]
Yes, this is indeed an issue. Thanks for proposing the fix already! We should soon get this merged and released.
