### ISSUE TITLE
Sign an assembly with a strong name

### ISSUE THREAD

**Issue by alexanderkozlenko** [AngleSharp/AngleSharp#115]
Please make the AngleSharp assembly as strong-named to make it possible to reference and use it from another strong-named assembly.

**Comment by FlorianRappl** [comment]
I don't have a strong opinion on the topic. Most NuGet packages do not use strong naming and there are also problems with strong-names.

What is your specific use-case (which platform and is using [Nivot.StrongNaming](https://www.nuget.org/packages/Nivot.StrongNaming) an option?). 

I am not against using strong-names, but maybe there are other drawbacks that outweigh the possible gain in convenience. So a discussion would be appreciated.

**Comment by alexanderkozlenko** [comment]
In general all assembly should be signed with a strong name unless you have a reason not to.

In my case I have an assembly which is installed in GAC so it should be strong-named. I'm planning to use AngleSharp from my assembly, but in this case I can reference only strong-named assemblies.

As an option I can compile local version of the AngleSharp assembly with custom strong key and use it, but reference to a NuGet package with string-named version will be of course preferable.

**Comment by FlorianRappl** [comment]
My reason for not using a signed assembly was simply to improve the possibility for partial updates of applications. If a strong-named library changes the whole application has to be re-build and re-distributed. 

With a weakly-named assembly on the library can just be changed and the application still works (or does not, of course, if the API or possibly the behavior, changed -- but that should have been tested beforehand).

I think I will go for the strong-name, but I will possibly not introduce it in v0.8.8, but rather in v0.9. Would that be a major problem?

**Comment by alexanderkozlenko** [comment]
That will not be a major problem. I will use local signed version until v0.9. Thanks!

**Comment by FlorianRappl** [comment]
Short update: Implementation is finished and ready for v0.9. 

I choose to not use a password for the key file, as this makes a lot of things significantly easier. The main purpose of signing in this case is to reference AngleSharp from other strong-name signed libraries.

Sounds good to you?

**Comment by alexanderkozlenko** [comment]
Yes, sounds good. Thanks again.

**Comment by FlorianRappl** [comment]
It is included and will be deployed with v0.9 (tomorrow).
