### ISSUE TITLE
Read only DOM and other ways to reduce allocation rate

### ISSUE THREAD

**Issue by dv00d00** [AngleSharp/AngleSharp#1154]
### Description

First of all, thank you for this amazing library, I've been using it for almost 10 years now.

I was fiddling with memory optimisations in my app, and figured AngleSharp document parsing allocates a lot. 

I have a feeling that at least part of it is due to eager string allocations for all the properties.

In the runtime there is definitely some cost to accessing TextContent (new string each call + iterator itself)

And maybe parsing have to be eager because of potential DOM manipulations.

Dom manipulation I something very rare, at lease in my case. And it feels like 95% of use cases is just obtaining read only DOM model to extract some data.

The idea is to present a new ReadOnly dome which could potentially be optimized by storing ReadOnlyMemory<char> references to the underlying buffer and be converted to string only where it is requested. And once the DOM is read only, we would be able to cache those results.

My question is how plausible this sounds? 

Could you provide some general guidance on how to implement this thing? If there is an interest on your side I would be glad to help.

### Background

| Method | FileName          | Mean        | Error       | StdDev      | Median      | Allocated  |
|------- |------------------ |------------:|------------:|------------:|------------:|-----------:|
| stream | generic_276k.html | 13,526.0 us |  1,394.1 us |    76.41 us | 13,557.1 us | 3932.04 KB |
| string | generic_276k.html | 14,908.7 us |  1,374.6 us |    75.35 us | 14,885.8 us | 4934.67 KB |
| stream | history_16K.html  |    788.9 us |    803.7 us |    44.05 us |    789.6 us |  255.66 KB |
| string | history_16K.html  |  1,173.3 us |  1,047.1 us |    57.39 us |  1,186.5 us |  302.09 KB |
| stream | landing_15k.html  |  1,616.7 us |  1,744.5 us |    95.62 us |  1,670.4 us |  444.47 KB |
| string | landing_15k.html  |  2,023.6 us |  1,480.5 us |    81.15 us |  2,055.2 us |  383.09 KB |
| stream | landing_252k.html | 13,630.0 us |  3,267.7 us |   179.11 us | 13,541.5 us | 3822.49 KB |
| string | landing_252k.html | 14,485.9 us |  5,151.2 us |   282.35 us | 14,362.4 us | 4726.46 KB |
| stream | landing_83K.html  |  3,684.9 us |  2,386.3 us |   130.80 us |  3,759.6 us | 1134.58 KB |
| string | landing_83K.html  |  4,859.8 us |    842.2 us |    46.16 us |  4,836.9 us | 1367.23 KB |
| stream | response_25k.html |  4,602.2 us | 75,681.3 us | 4,148.34 us |  2,299.1 us |  596.13 KB |
| string | response_25k.html |  5,287.5 us | 76,247.1 us | 4,179.36 us |  2,991.0 us |   572.2 KB |
| stream | result_134k.html  |  7,499.2 us |  4,099.8 us |   224.73 us |  7,507.9 us | 2077.55 KB |
| string | result_134k.html  |  8,847.8 us | 17,207.9 us |   943.22 us |  8,827.0 us |  2541.2 KB |

```csharp
[Config(typeof(Config))]
[MemoryDiagnoser]
public class AngleSharpBenchmarks
{
    private class Config : ManualConfig
    {
        public Config()
        {
            AddJob(Job.ShortRun.WithStrategy(RunStrategy.Monitoring));
        }
    }
    
    [Params(
        @"generic_276k.html",
        @"landing_252k.html",
        @"result_134k.html",
        @"landing_15k.html",
        @"response_25k.html",
        @"history_16K.html",
        @"landing_83K.html"
    )]
    public string FileName { get; set; }
    
    [Benchmark(Description = "stream")]
    public async Task Stream()
    {
        await using var file = File.OpenRead($@".\files\all\{FileName}");
        var parser = new HtmlParser();
        await parser.ParseDocumentAsync(file);
    }
    
    [Benchmark(Description = "string")]
    public async Task String()
    {
        var file = await File.ReadAllTextAsync($@".\files\all\{FileName}");
        var parser = new HtmlParser();
        parser.ParseDocument(file);
    }
}
```

based on this particular sample of html files ratio is around 14x per input html byte 

From what I have observed (not in this benchmark) it feels like there is a constant 140KB overhead for parsing html from stream rather than from string if tests exclude content load in the first place.

**Comment by FlorianRappl** [comment]
Well, surely you can optimize a lot - if you just take the parser and have, potentially a completely different factory attached to the DOM builder.

That the object model consumes more memory than the raw string is expected.

**Comment by dv00d00** [comment]
Can you please pinpoint the specific file under question

**Comment by FlorianRappl** [comment]
> Can you please pinpoint the specific file under question

Not sure what you refer to - I was talking generally. Anyway, the [DOM Builder](https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Html/Parser/HtmlDomBuilder.cs) is using the [HtmlElementFactory](https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Html/HtmlElementFactory.cs) as stated.

So any kind of readonly DOM would use / change / override this.

**Comment by dv00d00** [comment]
I've managed to get some sample compiling and almost passing all tests except single encoding test.

https://github.com/dv00d00/AngleSharp/pull/1

I would appreciate your input on the topic

**Comment by FlorianRappl** [comment]
Some of the ideas in there are good (e.g., stackalloc for for arrays) but in general we can't change the target framework. So any PR that is acceptable needs to keep the target framework as is (or only add frameworks, never remove / change them).

Same goes for changes that would make the API or ABI backwards incompatible. It should be a v1 release.

**Comment by dv00d00** [comment]
I've been trying to come up with zero alloc tokenizer lately. Got something looking promising

|  Method |      UrlTest |          Mean |         Error |     StdDev | Ratio |       Gen0 |     Gen1 |     Gen2 |   Allocated | Alloc Ratio |
|-------- |------------- |--------------:|--------------:|-----------:|------:|-----------:|---------:|---------:|------------:|------------:|
| Classes |   aliexpress |   5,570.91 us |    682.420 us |  37.406 us |  1.00 |   570.3125 | 109.3750 |  39.0625 |   7224645 B |       1.000 |
| Structs |   aliexpress |   1,419.88 us |     16.497 us |   0.904 us |  0.25 |     3.9063 |        - |        - |     34929 B |       0.005 |
|         |              |               |               |            |       |            |          |          |             |             |
| Classes | en.wikipedia |   5,480.09 us |    530.227 us |  29.064 us |  1.00 |   570.3125 | 117.1875 |  39.0625 |   7224654 B |       1.000 |
| Structs | en.wikipedia |   6,137.31 us |    129.994 us |   7.125 us |  1.12 |          - |        - |        - |     59427 B |       0.008 |
|         |              |               |               |            |       |            |          |          |             |             |
| Classes |       neobux |      23.21 us |      2.964 us |   0.162 us |  1.00 |     2.5635 |        - |        - |     21472 B |        1.00 |
| Structs |       neobux |      26.46 us |      0.906 us |   0.050 us |  1.14 |     0.0610 |        - |        - |       544 B |        0.03 |
|         |              |               |               |            |       |            |          |          |             |             |
| Classes |      netflix |     756.28 us |     58.805 us |   3.223 us |  1.00 |    49.8047 |  10.7422 |   3.9063 |    721125 B |        1.00 |
| Structs |      netflix |   1,267.05 us |     81.635 us |   4.475 us |  1.68 |    11.7188 |        - |        - |    112769 B |        0.16 |
|         |              |               |               |            |       |            |          |          |             |             |
| Classes |      nytimes |   4,874.98 us |  1,158.083 us |  63.478 us |  1.00 |   421.8750 | 109.3750 |  93.7500 |   7279407 B |       1.000 |
| Structs |      nytimes |   4,653.28 us |    180.749 us |   9.907 us |  0.95 |          - |        - |        - |     49443 B |       0.007 |
|         |              |               |               |            |       |            |          |          |             |             |
| Classes |           w3 | 124,869.27 us | 17,891.353 us | 980.685 us |  1.00 | 17000.0000 | 800.0000 | 400.0000 | 193556954 B |       1.000 |
| Structs |           w3 | 172,589.50 us | 15,625.271 us | 856.474 us |  1.38 |          - |        - |        - |     32597 B |       0.000 |

all tests are passing using hacked in Struct Tokenizer

Only after spending several hours trying to fix broken test it becomes obvious how much effort was involved with this lib in the first place

Anyway it feels like custom dom builder is possible now and I was able to backport struct parser into the existing ecosystem

What would the requirements for the code to be merged in be?

**Comment by dv00d00** [comment]
I am pretty confident if I would not be able to backport span code to the net472 I would be able to comeup with some shims.
I've removed target frameworks as a temp measure to focus on the speedup itself

Latest set of changes in my fork can be viewed here: https://github.com/dv00d00/AngleSharp/pull/2/files

**Comment by FlorianRappl** [comment]
This is awesome news and the perf. comparison above looks just magnificent!

I'd need to look at the changes, but assuming (without looking into details now) we have no breaking change and the tests pass I'd say merging it is a no brainer.

**Comment by dv00d00** [comment]
It is really messy atm, and due to speed it is not faster (usually) as it allocates almost no RAM

I had to make several assumptions on which this approach works atm and if I just plug the new tokenizer it allocates like 30 percent less. Major wins could be achieved if , let's say, you would have a token filter to select specific tag by Id or class and then only materialize just "interesting" tokens. 

Another scenario is probably push not yet materialized strings further to the dom, but I'm not sure how much of the difference it will make
