### ISSUE TITLE
DSL or fluent API for document construction?

### ISSUE THREAD

**Issue by lloydjatkinson** [AngleSharp/AngleSharp#1156]
### Description

Create a DSL allowing for easier and more robust document generation.

### Background

Using AngleSharp to *generate* HTML feels incredibly imperative and repetitive. Outside of the .NET ecosystem there are many [domain-specific languages](https://en.wikipedia.org/wiki/Domain-specific_language) that are used in the construction of HTML trees.

One of these DSL's is JSX (and TSX). It looks like this:

```tsx
<div>
    <ul>
        {
            names.map((name, index, categories) =>
                <li>
                    <a href={`/categories/#${name}`}>
                        {name}{index != (categories.length - 1) ? ',' : ''}
                    </a>
                </li>
            )
        }
    </ul>
    <footer />
</div>
```

With AngleSharp's current API *similar* code looks like this:

```csharp
var list = document.CreateElement("ul");
document.Body.AppendChild(list);
for (int i = 0; i < 20; i++)
{
    var listItem = document.CreateElement("li");
    listItem.TextContent = $"{i} lorem ipsum something something";
    list.AppendChild(listItem);
}

var footer = document.CreateElement("footer");

document.Body.AppendChild(footer);
```

- It's harder to write inline conditional logic
- It's harder to write conditional logic at all
- You need to *remember* to append created nodes to parent nodes
- It doesn't have the same ergonomics in terms of readability and immediate understandability
- Consistent reusability patterns become slightly harder
- Can't create attributes or child nodes for a node via it's constructor meaning more lines are required

Looking within the .NET ecosystem there are some options, for example a web framework for F#:

```fsharp
open Feliz.ViewEngine

let view = 
    Html.html [
        Html.head [ Html.title "Feliz" ]
        Html.body [
            Html.header [ prop.text "Feliz" ]
        ]
    ]

let card1 = 
    div [
        card [
            slotedHeader [
                h1 [ text "This is my custom card"]
            ]
            p [ text "this is the body of the card" ]
            cardFooter [
                custom("data-my-attr", "extra attributes")
                children (p [text "This is my footer"])
            ]
        ]
    ]

let document = Render.htmlDocument view

printfn "%s" document
```

One article [here](https://khalidabuhakmeh.com/building-html-with-csharp) proposes a fluent-ish API:

```csharp
new Html(
    new H1("Hello, World!")
)
```

### Specification

NA

**Comment by FlorianRappl** [comment]
I think you might have missed the goal of AngleSharp. Just to quote the README:

> The API is close to the DOM4 specification, however, the naming has been adjusted to apply with .NET conventions.

Therefore, all your mentioned points have nothing to do with AngleSharp, but rather with the official W3C specified API. Note that models that you mentioned (such as JSX) are in implementation directly working on the DOM API - therefore having the API that AngleSharp provides is like a basis for any other API.

In summary: What you want can actually be done - I'd recommend creating a project such as `AngleSharp.FluentDom` or similar creating an abstraction on top of AngleSharp. This will give you exactly what you want (and tailored for your needs).

Hope that helps!
