### ISSUE TITLE
Im not able to get any element from the site

### ISSUE THREAD

**Issue by umeshshende** [AngleSharp/AngleSharp#1160]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

I tried using below code issue is for only below website i tried amazon it works on both local and production env
```
    public IBrowsingContext GetContext()
        {
            var handler = new HttpClientHandler
            {
                AutomaticDecompression = System.Net.DecompressionMethods.GZip | System.Net.DecompressionMethods.Deflate
            };
            var client = new HttpClient(handler);
            client.DefaultRequestHeaders.Add("Connection", "keep-alive");
            var requester = new HttpClientRequester(client);
            var context = BrowsingContext.New(
      AngleSharp.Configuration.Default
              .WithRequester(requester)
              .WithDefaultLoader());

            return context;
        }
```
```
      public async Task GetDetailsbedbathandbeyondAsync()
        {

            // this is for viewProductDetailLink
            var context = GetContext();
         // actual site is different for security reason site is change
            var document = await GetDocument("https://www.test.com/c/product-cover?t=42&productid=27433344", context);
            string viewProductDetailLink = document.QuerySelector("a[class='featuredDesktop_viewDetailsLink__B1K9t']")?.GetAttribute("href");


            // this is for where product actual present
            //  var context = BrowsingContext.New(config);
            document = await GetDocument(viewProductDetailLink, context);
            string title = document.QuerySelector("h1[data-test='product-title']")?.TextContent.Trim();

}
```

Above code is working on local development but not on production site im getting error html page from website saying "There was an error processing your request." also i tried [810](https://github.com/AngleSharp/AngleSharp/issues/810)

### Steps to Reproduce

1. Copy code 
2. Execute GetDetailsbedbathandbeyondAsync()
3.  You should get title 

### Expected Behavior

It should get title as it is working on local env

### Actual Behavior

It does not retrieve title from website as it is working on local env issue is for production site or azure site

**Comment by FlorianRappl** [comment]
Sorry we cannot solve your problem - if you think this is an issue with AngleSharp then please distill it to the point where you can give us a MWE that does not rely on some site / forces us to debug everything for you.

Time is limited and this is a free project - if this is indeed a bug you should be able to create a proper MWE.

I leave it open for now.

**Comment by umeshshende** [comment]
@FlorianRappl I can not understand where it is failing is this bug or what? it simply triggering website to get title but it is only fail for given website other website are working.

given failed website is working on local env but not on production site.

given two functions which can easily replicate. Can you suggest any site [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)? where i can replicate for you

**Comment by FlorianRappl** [comment]
> given failed website is working on local env but not on production site.

This is an indicator that its not about AngleSharp, but about the environment. Potentially either the IP is blocked or something is unsupported (e.g., the machine uses an outdated TLS version).

Since there is no title / no content it is a strong indicator that there is a problem already at HTTP level.

**Comment by umeshshende** [comment]
Through out our investigation we found that website does not allow traffic for Canada as we have tested this using local region which is working but same not working on Canada and US region also work.

We have hosted on US region now.

**Comment by FlorianRappl** [comment]
Glad that you could solve your issue!
