### ISSUE TITLE
Priority in CSS Rules is incorrectly calculated

### ISSUE THREAD

**Issue by jbrayfaithlife** [AngleSharp/AngleSharp#1161]
# Bug Report

## Prerequisites

- [/] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [/] Are you running the latest version of AngleSharp?
- [/] Did you check the FAQs to see if that helps you?
- [/] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [/] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

The way priority is calculated, each rule gets a static priority assigned to it, however, the correct application is that each rule should have its priority determined by how many dimensions it matches the element in question. Thus, priority can only be established with respect to a particular element.

For example
```
#target {
  color: blue;
}

p, #nottarget {
  color: purple
}
```

When this is applied to a `<p>` with id `target`, the second rule takes precedence because it has been calculated to have a priority of `(0,1,0,1)` or `65537`, whereas the first is `(0,1,0,0)` or `65536`. However, the second rule only matches on the `p` dimension and should thus have a priority of `(0,0,0,1)` or `1` when applied to this particular element.

## Steps to Reproduce

Linqpad Script
```
var config = Configuration.Default.WithCss();
var document = await BrowsingContext.New(config)
    .OpenAsync(res => res.Content(@"<!doctype html>
<html lang=en>
<head>
<meta charset='utf-8'>
<title>Test Doc</title>
</head>
<body>
<h3 id='target'>Test</h3>
</body>
</html>"));
var style = document.CreateElement<IHtmlStyleElement>();
style.TextContent = @"#target {color: blue} h3, #nottarget { color: purple; } ";
document.Head.AppendChild(style);
document.DefaultView.GetComputedStyle(document.QuerySelector("h3")).Single(x => x.Name == "color").Dump();
```

**Expected behavior:** `rgba(0, 0, 255, 1)`

**Actual behavior:** `rgba(128, 0, 128, 1)`

**Environment details:** Win, .NET 6.0.16

## Possible Solution

I suspect rather than calculating a Priority when creating the rule, the priority should be dynamically calculated when a match is made.

**Comment by FlorianRappl** [comment]
> I suspect rather than calculating a Priority when creating the rule, the priority should be dynamically calculated when a match is made.

I'd not go there. Instead, I would suggest to decompose the selectors in such cases. Hence, at the end the priority is rather attached to the selector than the rule - the matching selector then also determines the priority.

**Comment by FlorianRappl** [comment]
Solved with AngleSharp.Css 1.0.0.
