### ISSUE TITLE
IHtmlDocument has IDisposable - for what?)

### ISSUE THREAD

**Issue by boraicho** [AngleSharp/AngleSharp#1164]
Hello all. 
May someone tell me for what IHtmlDocument has IDisposable? And why it doesn't has Finalize?

Some informtaion about my app - dozen parallel async console with site parsing. And we create a lot of HtmlDocument by life cycle consoles. 
I trying to Dispose all old HtmlDocument, but after that my consoles work slower.

**Comment by FlorianRappl** [comment]
It explicitly frees resources esp. considering cyclic references or pending downloads.

Not sure what you would need finalize for.
