### ISSUE TITLE
Redirect to Custom URL Scheme

### ISSUE THREAD

**Issue by CRC32EX** [AngleSharp/AngleSharp#1165]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

I want get URL from `Location` header.
But Custom URL Scheme does not supported.

### Steps to Reproduce

1. Create a PHP file

**index.php**
```php
<?php
// Custom URL Scheme
header('Location: myphotoapp:/oauth?param=123');

// This is fine.
// header('Location: http://127.0.0.1/a');
```

2. Run local PHP server
```
php -S 0.0.0.0:80
```

3. Create a C# file

**Program.cs**
```cs
var handler = new HttpClientHandler();
handler.AllowAutoRedirect = true;

var url = "http://127.0.0.1";

var config = AngleSharp.Configuration.Default
  .WithDefaultLoader()
  .WithRequesters(handler);
var context = BrowsingContext.New(config);
var page = await context.OpenAsync(url);

Console.WriteLine(context.Active!.Url);
Console.WriteLine(page.Location);
```

4. Run C# code
```
dotnet run
```

### Expected Behavior

`myphotoapp:/oauth?param=123`

### Actual Behavior

`http://127.0.0.1/`

**Comment by FlorianRappl** [comment]
Just use an interceptor and read out the response.

See `Filter` property on the loader configuration.

**Comment by CRC32EX** [comment]
Thank you for answer.
I finally got `Location` with bellow code.

But always twice HTTP request.
Do you have any good ideas for solve this issues?

```diff
 var handler = new HttpClientHandler();
- handler.AllowAutoRedirect = true;
+ handler.AllowAutoRedirect = false;

+ var client = new HttpClient(handler);

 var url = "http://127.0.0.1";

 var lastUrl = string.Empty;
 var config = AngleSharp.Configuration.Default
   .WithRequesters(handler)
+  .WithDefaultLoader(new LoaderOptions
+  {
+    Filter = req =>
+    {
+      var response = client.GetAsync(req.Address).GetAwaiter().GetResult();
+      Console.WriteLine($"Location: {response.Headers.Location}");
+      return true;
+    }
+  })
   .WithRequesters(handler);
 var context = BrowsingContext.New(config);
 var page = await context.OpenAsync(url).ConfigureAwait(false);
```
