### ISSUE TITLE
Issues with Headers

### ISSUE THREAD

**Issue by notrub32** [AngleSharp/AngleSharp#1166]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

I'm using Anglesharp 1.0, not latest because I use Anglesharp.IO which currently doesn't work with Anglesharp 1.1

Trying to set headers in my HTTP Post requests I'm running into difficulties. Some get set, some do not and some only get half-set.

I'm quite rusty at development work, so it's probably me doing something wrong.

### Steps to Reproduce

public static async Task<IDocument> Create(Browser browser, DocumentRequest requestDoc)
        {
            browser.HttpClient.DefaultRequestHeaders.Add("Referer", "https://www.somewebsite.com");
            browser.HttpClient.DefaultRequestHeaders.Remove("Accept");
            browser.HttpClient.DefaultRequestHeaders.Add("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7");
            
            var response = await browser.Context.OpenAsync(requestDoc);
}

### Expected Behavior

Headers set are sent to the website.

### Actual Behavior

Using Fiddler I can see that the Referrer is not set at all, and the "Accept" heading is trucated after application/xml.

If I look at the Context object in the final line, I can see within the OriginalServices that there are two requesters. The Anglesharp.IO.Network.HttpClientRequester and the Anglesharp.IO.DefaultHttpRequester. 
The former contains my added headers, the latter does not. 

What should I be using to set Headers manually and how do I do it?

**Comment by FlorianRappl** [comment]
> I'm using Anglesharp 1.0, not latest because I use Anglesharp.IO which currently doesn't work with Anglesharp 1.1

Can you elaborate on this?

**Comment by notrub32** [comment]
Apologies, I was getting error messages resulting from mismatched Assemblies which were resolved when I regressed Anglesharp to 1.0. I've just put it back to 1.1 and everything still works.

Also I've now realised the headers need to go on the Request, not the Context, so after 2 days I've finally solved that problem! Something still isn't working but I don't know what it is so will close this bug.
