### ISSUE TITLE
Use libraries provided by framework

### ISSUE THREAD

**Issue by thompson-tomo** [AngleSharp/AngleSharp#1167]
### Description

I want System.Text.Encoding.CodePages  to only be included as a dependency when the framework doesn't provide it

### Background

I want to reduce my surface area for CVE's and an efficent way of doing this is by reducing the amount of manually managed dependencies.

**Comment by FlorianRappl** [comment]
It's a standard NuGet from Microsoft and not provided by the "framework".

**Comment by thompson-tomo** [comment]
@FlorianRappl i just double checked and System.Text.Encoding.Codepage is actually included in atleast net6 framework and possibly earlier, hence this issue has not been completed.

It is available as a nuget to allow new functionality to be back ported to older frameworks etc.

**Comment by FlorianRappl** [comment]
It was discussed a while ago. Search is your friend #1124.
