### ISSUE TITLE
QuerySelectorAll problem

### ISSUE THREAD

**Issue by avrbovsky** [AngleSharp/AngleSharp#1170]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

When having IsPreservingAttributeNames to true, the QuerySelectorAll does not seem to be working for attributes having upperCase in them

### Steps to Reproduce

Code:
string fileContent = @"<div fxLayout=""row""></div>";
HtmlParser parser = new HtmlParser(new HtmlParserOptions
{
    IsPreservingAttributeNames = true
});
IDocument document = parser.ParseDocument(fileContent);
IHtmlCollection<IElement> elements = document.QuerySelectorAll("[fxLayout]");

### Expected Behavior

elements variable contains <div fxLayout="row"></div> element

### Actual Behavior

elements variable contains nothing

**Comment by FlorianRappl** [comment]
This is something we won't fix. The query selectors work like in the browsers, by doing an opt-in to preserve the attribute name you automatically opt out of the official model. Now you cannot expect that all the algorithms, which are based on the official model, keep working as beforehand. They don't.

I am not sure why you want to preserve the attribute names. This is not intended to be used like that. In fact it was mostly desired by people that have some Angular templates and want to parse those.
