### ISSUE TITLE
Multipart/form-data support

### ISSUE THREAD

**Issue by TonyDev314** [AngleSharp/AngleSharp#1173]
### Description

Support the creation and handling of requests that use MultipartFormDataContent

### Background

I have built an application using Anglesharp and now encounter a page which requires a post using MultipartFormDataContent.
I have created a MultipartFormDataContent (formData) and then built a DocumentRequest as follows:

var request = DocumentRequest.Post(new Url(_MyURL), formData.ReadAsStream(), formData.Headers.ContentType.ToString());

and I create a Dictionary of headers and then call 

return await _context.OpenAsyncWithHeaders(request, testheaders);

This mostly works, but it is a bit clunky and the binary data, included in the MultiPartData is getting corrupted somewhere - still investigating why/where.

**Comment by FlorianRappl** [comment]
I think what's missing is the right boundary / specify it as content type.

In any case I've added an abstraction / helper to simplify this (`DocumentRequest.PostAsMultipart`).

Part of 1.1.1.
