### ISSUE TITLE
IndexOutOfRangeException in AngleSharp.Common.ArrayPoolBuffer.Append

### ISSUE THREAD

**Issue by mschessler** [AngleSharp/AngleSharp#1174]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

Malformed input found by fuzzer crashes HtmlParser.ParseDocument.

### Steps to Reproduce

```
var html = Encoding.UTF8.GetString(File.ReadAllBytes("crash-1a949173befa2cc26c41985adefc49b3d79cdad4.txt"));
var parser = new AngleSharp.Html.Parser.HtmlParser();
parser.ParseDocument(html.ToCharArray(), 0);
```

Input file appended:

[crash-1a949173befa2cc26c41985adefc49b3d79cdad4.txt](https://github.com/AngleSharp/AngleSharp/files/14440587/crash-1a949173befa2cc26c41985adefc49b3d79cdad4.txt)

### Expected Behavior

Don't crash :)

### Actual Behavior

Crash :(

### Possible Solution / Known Workarounds

I see recent changes to ArrayPoolBuffer.

**Comment by FlorianRappl** [comment]
Fixed in 1.1.1.
