### ISSUE TITLE
Getting Attributes for each Element

### ISSUE THREAD

**Issue by PhillipSargeant** [AngleSharp/AngleSharp#1175]
### Description

I am using AngleSharp but I appear to be missing something.

I would like parse the attributes in an element along the lines of:

var allElements = htlmDocument.QuerySelectorAll("*");
foreach Element in allElements
{
	Foreach Attribute in Elements.Attributes
}

However, as you know, there is no public member “Attributes” on the Node/Tag/Element (HtmlHtmlIElement)

I do note that the attributes in an element are included in the Non-Public Members under AngleSharp.DOM.IElement.Attributes. However, these are non-public and are locked.

Is there another way to get all the attributes per Tag/Element using AngleSharp?

**Comment by FlorianRappl** [comment]
I think you have some mistake in your code. `Attributes` is not internal. It's available on the public interface `IElement`.

Example:

```cs
var context = BrowsingContext.New();
var document = context.OpenAsync(res => res.Content("<div foo='bar' data-xyz='blub' class='other'></div>")).Result;
var divs = document.QuerySelectorAll("div");

foreach (var div in divs)
{
	div.Attributes.Dump();
}
```

Results in:

![image](https://github.com/AngleSharp/AngleSharp/assets/1766191/3be846d5-7b46-4c1a-ba50-04ebea18bf85)
