### ISSUE TITLE
Attributes in Elements

### ISSUE THREAD

**Issue by PhillipSargeant** [AngleSharp/AngleSharp#1177]
### Description

Thank you Florian BUT I followed your example EXACTLY.

var context = BrowsingContext.New();
var document = context.OpenAsync(res => res.Content("<div foo='bar' data-xyz='blub' class='other'></div>")).Result;
var divs = document.QuerySelectorAll("div");

foreach (var div in divs)
{
	div.Attributes.Dump();
}

When it hit the statement div.Attributes.Dump();

I got the error message "System.MissingMemberException" 'Public member 'Attributes' on type 'HtmlDivElement' not found'

**Comment by FlorianRappl** [comment]
Please don't open issues unnecessarily.

From your exception it seems you use some really old / not up-to-date version of AngleSharp. Please follow our guidelines.

**Comment by PhillipSargeant** [comment]
Hello Florian.

I do apologize I would not open issues unnecessarily. 

I have used AngleSharp a lot, quite successfully. The version I use is 1.1.0



My program:

using AngleSharp;
using AngleSharp.Dom;
using AngleSharp.Html;
using AngleSharp.Html.Dom;
using AngleSharp.Io;
using AngleSharp.Io.Dom;

namespace AngleSharpTest
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {

            var config = Configuration.Default;
            var context = BrowsingContext.New();
            var document = context.OpenAsync(res => res.Content("<div foo='bar' data-xyz='blub' class='other'></div>")).Result;
            var divs = document.QuerySelectorAll("div");

            foreach (var div in divs)
            {
                div.Attributes();

            }

        }
    }
}




The error with the line “div.Attributes()” is CS1955: Non-invocable member ‘IElement.Attributes’ cannot be used like a method

If I were to use the line “div.Attributes.dump()” I get an error CS1061: ‘INamedNodeMap’ does not contain a definition for ‘dump’



Sorry if I have wasted your time.

Regards
Phil Sargeant

**Comment by PhillipSargeant** [comment]
Hello Florian.

 

I do apologise I would not open issues unnecessarily. 

 

I have used AngleSharp a lot, quite successfully. The version I use is 1.1.0

 

 

 

My program:

 

using AngleSharp;

using AngleSharp.Dom;

using AngleSharp.Html;

using AngleSharp.Html.Dom;

using AngleSharp.Io;

using AngleSharp.Io.Dom;

 

namespace AngleSharpTest

{

    public partial class Form1 : Form

    {

        public Form1()

        {

            InitializeComponent();

        }

 

        private void Form1_Load(object sender, EventArgs e)

        {

 

        }

 

        private void button1_Click(object sender, EventArgs e)

        {

 

            var config = Configuration.Default;

            var context = BrowsingContext.New();

            var document = context.OpenAsync(res => res.Content("<div foo='bar' data-xyz='blub' class='other'></div>")).Result;

            var divs = document.QuerySelectorAll("div");

 

            foreach (var div in divs)

            {

                div.Attributes();

 

            }

 

        }

    }

}

 

 

 

 

The error with the line “div.Attributes()” is CS1955: Non-invocable member ‘IElement.Attributes’ cannot be used like a method

 

If I were to use the line “div.Attributes.dump()” I get an error CS1061: ‘INamedNodeMap’ does not contain a definition for ‘dump’

 

 

 

Sorry if I have wasted your time.

 

Regards

Phil Sargeant
