### ISSUE TITLE
Parser Issue Findings from Fuzzing

### ISSUE THREAD

**Issue by mschessler** [AngleSharp/AngleSharp#1179]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

A small input is enough to hang the HTML parser (indefinitly?).

### Steps to Reproduce

`var html = "<table><a><menu><svg><template></a><nobr><p><nobr>";`
or
`var html = "<table><a><main><svg><template></a><a><main><a>";`

```
var parser = new AngleSharp.Html.Parser.HtmlParser();
parser.ParseDocument(html.ToCharArray(), 0);
```

### Expected Behavior

Don't take that long.

### Actual Behavior

Hangs for at least 10min. Did not test longer.

**Comment by FlorianRappl** [comment]
I appreciate the fuzzing here - but could you aggregate the findings?

Also better titles would also help (this one is misleading as its not at all about the length of the input, but rather on what invalid tree is to be constructed).

I've changed this one to use the issue for all the findings.

**Comment by mschessler** [comment]
If that makes it clearer and easier, of course. But I don't expect much more findings.

**Comment by mschessler** [comment]
Found one input that still timeouts on the newest 1.1.1 release:

`var html = "<table><A><template><tr><A><s><object><svg><template></object></object><A>";`

**Comment by FlorianRappl** [comment]
I've brought it over to a new issue for the 1.1.2. Please put all your findings in this one; the HTML snippet / input is sufficient.
