### ISSUE TITLE
Additional Findings from Fuzzing

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#1180]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

To continue the issues found in #1179 we use this thread.

All issues found will be fixed in 1.1.2.

### Steps to Reproduce

See individual posts here.

### Expected Behavior

Should work.

### Actual Behavior

Causes a parser panic (either crash, indefinite loop, or other non-desired behavior).

### Possible Solution / Known Workarounds

Issue with tree construction due to invalid input / edge case / problem in the HTML5 error handling area.

**Comment by FlorianRappl** [comment]
First case reported by @SyrasX:

```html
<table><A><template><tr><A><s><object><svg><template></object></object><A>
```

**Comment by mschessler** [comment]
> First case reported by @SyrasX:
> 
> ```
> <table><A><template><tr><A><s><object><svg><template></object></object><A>
> ```

Another similar input that also timeouts:

`<template><tr><A><template><tr><A><object><svg><template></object></object><e><A>`

I will add all found further timeouts here, grouped by perceived similarity.

`<nobr><table><caption><table><caption><svg><html><html></table><nobr><g><svg><html><html></table><nobr>`

`<nobr><table><caption><table><caption><svg><html><html></table><nobr><F><math><html><html></table><nobr>`

**Comment by FlorianRappl** [comment]
Completed in 1.1.2.
