### ISSUE TITLE
How to Change the Accept header in DocumentRequest

### ISSUE THREAD

**Issue by TonyDev314** [AngleSharp/AngleSharp#1183]
### Description

As title really.

As things stand I'm trying to find a clean way around it because I need to set a different specific header on every request I make.
Because it's a general thing, I have a custom version of HttpClient that I configure when I create the Browser. This sets all the headers on every request unless they are dictated differently in the DocumentRequest headers.

So currently I need to either explictly remove the Accept header in my code each request, or comment out the line in DocumentRequest and built Anglesharp without it - this is of course fine, but I wondered if there was a need for the header to be included by default in the way it is?

Maybe I'm missing something obvious, or perhaps my needs are an edge case. It's just everything else is so configurable you can easily extend and adapt things.

**Comment by FlorianRappl** [comment]
You can always just grab the stream yourself and push that to AngleSharp. If you let AngleSharp make the request then AngleSharp adds the standard headers that a browser also adds.

Hope that helps!
