### ISSUE TITLE
AngleSharp 1.2.0-beta.410 can not be loaded in .Net Framework because of System.Memory version error

### ISSUE THREAD

**Issue by GruberMarkus** [AngleSharp/AngleSharp#1186]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

On .Net Framework, not on .Net Core, AngleSharp 1.2.0-beta.410 can not be loaded because System.Memory 4.0.1.1 can not be found: `Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.`

NuGet does not have System.Memory in version 4.0.1.1, and NuGet dependencies resolve to System.Memory >= 4.5.5.

It does not matter if you use the net461 or netstandard2.0 DLLs. Both fail on .Net Framework, both work fine on .Net (Core).

### Steps to Reproduce

1. `nuget.exe install AngleSharp -Framework net461 -Version "1.2.0-beta.410" -OutputDirectory ".\AngleSharp_with-deps_net461" -NoHttpCache -DirectDownload -Verbosity quiet -DependencyVersion lowest`
2. Extract all net461 DLLs and place them in the same folder
3. Import AngleSharp.dll in .Net Framework,not in .Net (Core)<br>`System.Reflection.Assembly.LoadFrom("path-to-anglesharp.dll")`<br>or in PowerShell 5: `import-module -Path "path-to-anglesharp.dll"`
4. Error: `Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.`

### Expected Behavior

AngleSharp.dll can be loaded successfully on .Net Framework.

### Actual Behavior

See description.

### Possible Solution / Known Workarounds

Maybe an (automatic) binding redirect is missing (https://github.com/dotnet/announcements/issues/31)?

**Comment by FlorianRappl** [comment]
In general this is a strange thing. We use the `System.MemoryExtensions` in one area, however, this area is also part of the unit tests - which run for the different targets. So if something would go sideways with a dependency that is otherwise not mentioned anywhere (there is no direct reference in any csproj, as well as in the nuget) then I am unsure if this is really an AngleSharp issue (especially since I also use it in some .NET Framework projects and there it just works).

As per repro steps: I want to see a csproj that when I open it, build or run it will fail.

**Comment by GruberMarkus** [comment]
I can't reproduce it in C#. Although being just another language in the .Net universe, PowerShell seems to load/locate  DLLs differently.

There is something I have found, though: The System.Memory dependency is caused by the following condition defined in csproj:
```
<ItemGroup
  Condition=" '$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'net461' or '$(TargetFramework)' == 'net472' or '$(TargetFramework)' == 'net6.0' ">
  <PackageReference Include="System.Text.Encoding.CodePages" Version="6.0.0" />
</ItemGroup>
```

System.Text.encoding.Codepages 6.0.0 references System.Memory 4.0.1.1: NuGet Package Explorer https://nuget.info/packages/System.Text.Encoding.CodePages/6.0.0, select lib\netstadard2.0\System.Text.encoding.Codepages.dll, and have a look at "referenced assemblies" in the lower frame.

The other packages used in AngleSharp reference System.Memory 4.0.1.2, which is in the NuGet package System.Memory 4.5.5.


**Test 1** 
In AngleSharp.Core.csproj, add a package reference to System.Memory 4.5.5:
```
<ItemGroup
  Condition=" '$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'net461' or '$(TargetFramework)' == 'net472' or '$(TargetFramework)' == 'net6.0' ">
  <PackageReference Include="System.Text.Encoding.CodePages" Version="6.0.0" />
  <PackageReference Include="System.Memory" Version="4.5.5" />
</ItemGroup>
```

**Test 2**
Switching to System.Text.Encoding.Codepages 8.0.0, but that requires moving from net461 to net462. This might be reasonable, as net461 reached its end of support 2022. Also, this only changes the error message from "System.Memory, Version=4.0.1.1" to "System.Memory, Version=4.0.1.2".


Maybe you have a clue how to move forward from here, I am stuck for the moment.

**Comment by FlorianRappl** [comment]
Updated to CodePages 8.0.0. We won't include System.Memory as its a dependency of CodePages, not us. If you don't follow the standard NuGet commands, which automatically resolve deps of deps, then you might miss out assemblies. That's not an AngleSharp issue, but rather how a package manager works.
