### ISSUE TITLE
obsolete reference

### ISSUE THREAD

**Issue by angelofb** [AngleSharp/AngleSharp#1191]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

looks like AngleSharp.Css references an old version of AngleSharp
![image](https://github.com/AngleSharp/AngleSharp/assets/2032257/726f33e4-2691-4314-bcb6-cf7aaefbd7c5)

### Steps to Reproduce

add AngleSharp.Css to project

### Expected Behavior

reference to latest release of AngleSharp or at least same major

### Actual Behavior

constrained to < 0.18.0

### Possible Solution / Known Workarounds

republish the package with updated reference

**Comment by FlorianRappl** [comment]
1. This is the repository of AngleSharp, not AngleSharp.Css
2. AngleSharp.Css 0.17 targets AngleSharp 0.17 - take the preview of AngleSharp.Css 1.0 if you want to target AngleSharp 1.x

Please review the bug issuing guidelines before blindly posting. Thanks!

**Comment by angelofb** [comment]
sorry
