### ISSUE TITLE
Digitally Sign AngleSharp NuGet Package Assemblies

### ISSUE THREAD

**Issue by timo352** [AngleSharp/AngleSharp#1192]
### Description

Currently, the AngleSharp NuGet Package contains assemblies that are unsigned. There is a chance that AV software will flag the .dlls as untrustworthy. 

It is probably best practice to get these DLLs signed inside the NuGet package to verify that they are from a VERY trustworthy source 😄

**Comment by FlorianRappl** [comment]
We use `SignAssembly` set to true. We don't sign the NuGet package itself.

Unless specifically required or when somebody wants to add this/make a proposal I'd close this one.
