### ISSUE TITLE
Document Behavior of IsVisible and Other Placeholder Methods

### ISSUE THREAD

**Issue by memiamp** [AngleSharp/AngleSharp#1194]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

The source code has this in currently for the aforementioned extension method:

```
/// <summary>
/// Checks if the element is visible on screen.
/// </summary>
/// <param name="element">The element to check.</param>
/// <returns>True if the element is visible, otherwise false.</returns>
public static Boolean IsVisible(this IElement element)
{
    //TODO
    return false;
}
```

Any idea if this is going to be implemented?  If not, is there a better way to achieve this?

### Steps to Reproduce

Call `IsVisible()` on any `IElement` and it will return false regardless of it's visibility status.

### Expected Behavior

The result should be indicative of whether the element is visible.

### Actual Behavior

The result is always false, regardless of visibility.

**Comment by FlorianRappl** [comment]
Out of scope - requires a renderer.

**Comment by memiamp** [comment]
With the greatest of respect then, can you remove it from the code as it's not clear at all that it's non-functional.

**Comment by FlorianRappl** [comment]
This has to be present by spec - and the value (`false`) also makes sense as its not rendering.

Removing it would be breaking.

What we could do is to indicate the current lack of implementation in form of a docgen comment. So if you'd like to see that then a PR on the matter would be welcome.

**Comment by memiamp** [comment]
Thanks for the response.  Would the simple addition of a `<remarks>` tag be suitable?  Something like:

```c#
/// <summary>
/// Checks if the element is visible on screen. Not implemented, and
/// will always return false.
/// </summary>
/// <param name="element">The element to check.</param>
/// <returns>True if the element is visible, otherwise false.</returns>
/// <remarks>
/// Calls to this method will always return false as there is no renderer
/// and, therefore, the element is never visible.
/// </remarks>
public static Boolean IsVisible(this IElement element) => false;
```

I notice that there are some other, similar, methods that return false by default.  Is there any value in making similar changes to those call so their implementation (or lack of, as it were) is explicit?

**Comment by FlorianRappl** [comment]
> Thanks for the response. Would the simple addition of a <remarks> tag be suitable?

I think so, yes.

> I notice that there are some other, similar, methods that return false by default. Is there any value in making similar changes to those call so their implementation (or lack of, as it were) is explicit?

Depends / but in general yes. There might be some exceptions to this, but in general it would be good (and then also consistent if we start with a remark for the `IsVisible`) to have this communicated somewhat. Thanks for bringing it up!

**Comment by memiamp** [comment]
I'd be happy to look at this if you are comfortable to assign it to me.

**Comment by FlorianRappl** [comment]
Awesome - much appreciated!
