### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by hflexgrig** [AngleSharp/AngleSharp#1196]
### Description

I see there's mathml support, just wonder if it worths to have Latex support as well?
https://www.latex-project.org

### Background

User wants to synchronize Mathml and Latex through same model. E.g. convert from Latex to MathML and vise versa.

**Comment by FlorianRappl** [comment]
Definitely not in `AngleSharp.Core`. There could be some library that does that, but I'm not sure if this should be an official AngleSharp lib as LaTeX is not part of HTML (and never will be).

So it would only be a convenience lib that parses LaTeX math expressions to MathML and vice versa.

(rudimentary MathML support is required as per HTML5 spec, which allows using MathML in HTML; this case is similar to SVG)
