### ISSUE TITLE
DocumentRequest body stream not positioned to zero when resending the same request

### ISSUE THREAD

**Issue by leftbrasil** [AngleSharp/AngleSharp#1199]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

DocumentRequest.Body streams needs to be positioned to the beginning before sending the request.

I`m doing few requests reusing the same object, found out that I had to manually set the postion of the stream to zero

### Steps to Reproduce

```
req = new DocumentRequest(new Url(QRCodeStatus));
req.Headers["User-Agent"] =  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36";
req.Method = AngleSharp.Io.HttpMethod.Post;
req.MimeType = "application/json";
req.Headers["Origin"] = @"https://[redacted]";
req.Referer = referer;

StringWriter sw = new StringWriter();
string p = JsonConvert.SerializeObject(new { token = "my string"});
       
req.Body = new MemoryStream(Encoding.ASCII.GetBytes(p ));
bool consulta = true;
DateTime until = DateTime.Now.AddSeconds(60);
do
{
    Thread.Sleep(5000);
    doc = await context.OpenAsync(req);
    if (doc.StatusCode == HttpStatusCode.OK || doc.StatusCode == HttpStatusCode.InternalServerError)
        break;
    if (DateTime.Now > until)
        consulta = false;

} while (consulta);

```
### Expected Behavior

The post should send the content everytime.

### Actual Behavior

After the first send, the stream are not reset to beginning of the stream.

### Possible Solution / Known Workarounds

set DocumentRequest.Body.Position = 0;

**Comment by FlorianRappl** [comment]
How is this a bug? AngleSharp is not responsible for your stream - it cannot know that this is a memory stream and can be reset. Why don't you reset it?
