### ISSUE TITLE
StringBuilderPool performance improvements: Turn off locking

### ISSUE THREAD

**Issue by micahbresette** [AngleSharp/AngleSharp#1201]
### Description

The locking mechanism that is used in the StringBuilderPool can cause a high amount of waits with systems that use a lot of threads to process multiple documents concurrently.  This has been a finding during some profiling on a heavily used process.  

Have a new Property/Setting on the StringBuilderPool class to optionally turn off pooling which will effectively skip the locking call (https://github.com/AngleSharp/AngleSharp/blob/6c4be442576f7524c8e3bb99540323537c7de2dd/src/AngleSharp/Text/StringBuilderPool.cs#L41).   
- Should stay off by default to preserve current behavior.
- If turned off, this could increase memory cost since pooling won't be used.

**Comment by FlorianRappl** [comment]
Sounds good to me. Do you want to make a PR on this one?

**Comment by micahbresette** [comment]
I'd be happy to create a PR for this!

**Comment by lahma** [comment]
You could possibly also consider the `ValueStringBuilder` originating from .NET sources. No locking and very few allocations: https://github.com/sebastienros/jint/blob/main/Jint/Pooling/ValueStringBuilder.cs

**Comment by micahbresette** [comment]
PR: https://github.com/AngleSharp/AngleSharp/pull/1203

**Comment by FlorianRappl** [comment]
Landed in the preview! Thanks @micahbresette 🚀
