### ISSUE TITLE
File 'src/AngleSharp.Core.Tests/Html/Heisenberg.Bug.txt 'contains multiple viruses.

### ISSUE THREAD

**Issue by TGofNordBeat** [AngleSharp/AngleSharp#1202]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

You should check the file: src/AngleSharp.Core.Tests/Html/Heisenberg.Bug.txt
It was reported as a virus container.

### Steps to Reproduce

Check for viruses

### Expected Behavior

Check for viruses

### Actual Behavior

Check for viruses

**Comment by FlorianRappl** [comment]
We get such a BS every once in a while. The file certainly does not contain a virus - it's a false positive (just look at it). Report this to your AV provider instead.

**Comment by FlorianRappl** [comment]
In the future please search the issues first.

#1058 and #1033
