### ISSUE TITLE
context.OpenAsync(dataurl) returns null on browser wasm

### ISSUE THREAD

**Issue by Worldwidebrine** [AngleSharp/AngleSharp#1204]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

I'm trying to parse html in webworker.

### Steps to Reproduce

```
dotnet.exe new wasmbrowser
dotnet add package AngleSharp --version 1.1.2
```
Open `Program.cs`.
Replace `string Greeting()` with `async Task<string> Greeting()`.
Paste readme Simple Demo into `Greeeting`.
`dotnet run`

### Expected Behavior

Not sure.

### Actual Behavior

`document` is null.

**Comment by iyume** [comment]
~~Same problem with `AngleSharp 1.1.2` and `AngleSharp.Css 0.17.0`.~~

~~`await context.OpenAsync(address)` always return null, but virtual request works:~~

```csharp
        using var httpClient = new HttpClient();
        var html = await httpClient.GetStringAsync(GetSubjectUrl(subjectId));
        var document = await _context.OpenAsync(req => req.Content(html));
        var element = document.QuerySelector("#infobox");
```

**Edit:** I'm not using `AngleSharp.Wasm`. In my case I just forget to add `.WithDefaultLoader()`.

**Comment by FlorianRappl** [comment]
I think we can close this.

In general WASM does not have a requester - so it won't work. Such things need to be passed in externally / via some bridging. Presumably, the more modern requester in .NET is bridged (not sure what the JS part does / which things are brought into the WASM); so I'd recommend investigating there first (and if this is true then `AngleSharp.Io` / the now standard requester will just work).
