### ISSUE TITLE
IsStepMismatch validation fails when using floating point numbers (e.g., Lat/Long)

### ISSUE THREAD

**Issue by rhuebner76** [AngleSharp/AngleSharp#1210]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

Validity checks for step value mismatch returns false positive. 

For example, defining validation attributes on an HTML number input for geographic coordinates (latitude/longitude) to six places.

```html
<input type="number" max="-116.915989" min="-124.763068" step=".000001" value="-117" />
```
The value (-117) above should be and is valid in most browsers, however, it is reported as being invalid in `AngleSharp (v1.1.2)`.

Reviewing the source code, it appears the issue is in the `AngleSharp.Html.InputTypes.BaseInputType` class `IsStepMismatch()` method [permalink](https://github.com/AngleSharp/AngleSharp/blob/5dc976bb0c4b30799e28a0ea43eff180f4259964/src/AngleSharp/Html/InputTypes/BaseInputType.cs#L147).

```csharp
        /// <summary>
        /// Checks if the current value does not match the steps.
        /// </summary>
        protected Boolean IsStepMismatch()
        {
            var step = GetStep();
            var value = ConvertToNumber(_input.Value);
            var offset = GetStepBase();
            return step != 0.0 && (value - offset) % step != 0.0;    // <-- this expression does not account for rounding errors with floating point numbers
        }
```

### Steps to Reproduce

The following test demonstrates the failed assertion:

```csharp
[Test]
public void TestInputStepMismatchWithFloatingNumber()
{
    var context = BrowsingContext.New(Configuration.Default);
    var htmlParser = context.GetService<IHtmlParser>()!;
    var document = htmlParser.ParseDocument("");

    var element = document.CreateElement("input") as IHtmlInputElement;
    Assert.IsNotNull(element);
    element.Type = "number";
    element.RemoveAttribute("required");
    element.RemoveAttribute("pattern");
    element.RemoveAttribute("step");
    element.RemoveAttribute("max");
    element.RemoveAttribute("min");
    element.RemoveAttribute("maxlength");
    element.RemoveAttribute("value");
    element.RemoveAttribute("multiple");
    element.RemoveAttribute("checked");
    element.RemoveAttribute("selected");

    element.SetAttribute("min", "-124.763068");
    element.SetAttribute("step", ".000001");
    element.Value = "-117";

    Assert.AreEqual("number", element.Type);
    Assert.AreEqual(false, element.Validity.IsStepMismatch);
}
```

### Expected Behavior

The expected behavior is that `element.Validity.IsStepMismatch` is `false`

### Actual Behavior

The expected behavior is that `element.Validity.IsStepMismatch` is `true`, resulting in a false validation error.

### Possible Solution / Known Workarounds

A possible fix is to replace the return expression with an expression more friendly to floating points.

Instead of:
```csharp
return step != 0.0 && (value - offset) % step != 0.0;
```
use:
```csharp
return step != 0.0 && Math.Floor((value - offset) / step) * step) != 0.0;
```

**Comment by FlorianRappl** [comment]
Yeah that's right it's not very stable w.r.t. to floating point numbers.

The given solution looks like a step in the right direction. Mind doing a PR for this?

Thanks!

**Comment by rhuebner76** [comment]
@FlorianRappl.  I can certainly do a PR for it.

**Comment by rhuebner76** [comment]
@FlorianRappl spent some time with the testing and code and submitted a PR that should fix the validation issue.
