### ISSUE TITLE
CheckedInputType.ConstructDataSet() ignore Input.Value

### ISSUE THREAD

**Issue by tsu1980** [AngleSharp/AngleSharp#124]
Relate #120, CheckedInputType.ConstructDataSet() ignore Input.Value. so Input.Value does't appeared in form dataset even if set by someone.

I think the code should like below,

``` cs
        public override void ConstructDataSet(FormDataSet dataSet)
        {
            if (Input.IsChecked)
            {
                string value;
                if (!String.IsNullOrEmpty(Input.Value))
                    value = Input.Value;
                else
                    value = Input.GetAttribute(AttributeNames.Value) ?? Keywords.On;
                dataSet.Append(Input.Name, value, Input.Type);
            }
        }
```

**Comment by FlorianRappl** [comment]
Well, I am not so sure. How should it be handled if it was intentionally set to an empty value? I'll check that.

(But the main purpose of the issue is certainly right; set values are ignored at the moment - which is certainly a bug)

**Comment by FlorianRappl** [comment]
Obviously empty values need to be transported as empty values. So it makes a difference if it is the empty string or null. Unfortunately currently only the empty string is returned from `Value`. But I'll find a way.

**Comment by tsu1980** [comment]
Thanks!
