### ISSUE TITLE
Output redundant "&" in x-www-form-urlencoded

### ISSUE THREAD

**Issue by tsu1980** [AngleSharp/AngleSharp#125]
In FormDataSet.AsUrlEncoded(), requireAmpersand is always true except first time. so it is possible output redundant "&" like "?foo=&&bar=".

I've not faced server error by this behavior yet, but if fixed this my comparing work makes easy.

I think the code should like below,

``` cs
            while (offset < _entries.Count)
            {
                if (_entries[offset].HasName)
                {
                    if (requireAmpersand)
                        tw.Write('&');

                    //_entries[offset].AsUrlEncoded(tw);
                    //requireAmpersand = true;
                    requireAmpersand = _entries[offset].AsUrlEncoded(tw);    // return true if output something
                }

                offset++;
            }
```

**Comment by FlorianRappl** [comment]
In a way that is the level of control that is offered by `HasName`. Maybe an additional `HasValue` would be useful. I'll make the enhancement.

**Comment by FlorianRappl** [comment]
Can you please post a sample form where this happened? The test cases I've come up with are already covered.

**Comment by tsu1980** [comment]
Reproduction environment didn't saved, but I think it certainly looked like:

``` html
<form method="POST" action="/item/confirm">
  <input type="hidden" name="status" value="1">
  <input type="file" name="photo">
  <input type="hidden" name="status2" value="1">
  <input type="submit" name="send" value="Send">
</from>
```

request body is

```
status=1&&status2=1&send=Send
```

**Comment by FlorianRappl** [comment]
Thanks!
