### ISSUE TITLE
Escaping in script elements in XHTML

### ISSUE THREAD

**Issue by thorn0** [AngleSharp/AngleSharp#128]
``` c#
var document = new HtmlParser().Parse("<script>console.log(a<a>a)</script>");
var formatter = new AngleSharp.Xml.XmlMarkupFormatter();
var result = document.ToHtml(formatter);
```

result:

``` html
<html><head><script>console.log(a<a>a)</script></head><body></body></html>
```

I thought it should've been

``` xml
<html><head><script>console.log(a&lt;a&gt;a)</script></head><body></body></html>
```

but it turns out the browsers don't understand the entities inside scripts, so CDATA and JS comments must be used for JS:

``` xml
<html><head><script>//<![CDATA[
console.log(a<a>a)//]]></script></head><body></body></html>
```

However, this is too JS-specific whereas script elements can contain other languages that might have a different syntax for comments. So I don't see how this problem can be solved in the general case.

Actually, I'm not trying to achieve compatibility with specifically XHTML. I merely want my markup to be valid XML. It's a reasonable expectation from a class named `XmlMarkupFormatter`, isn't it?

**Comment by FlorianRappl** [comment]
Well, I don't know. The `XmlMarkupFormatter` can be used in conjunction with HTML, but do not expect it to output valid XML. Not everything that is valid in HTML can be translated to XML - HTML has a 5 tokenization states unlike XML. Things like script state (for script tags) or rawtext (e.g. style) or even raw characters (title, textarea) are not present in XML. The `XmlMarkupFormatter` is not prepared for these edge cases.

Instead the `XmlMarkupFormatter` is only prepared for output generated in an `XmlDocument` or `SvgDocument`. Here the parser already generated the tree using XML rules.

I would not exclude the option of making something like the `XmlMarkupFormatter` ready to output valid XML even from an HTML tree, but a lot more work would be required. Right now there is no priority on that from my side - but you are free to help out here.

**Comment by thorn0** [comment]
As I mentioned, I myself don't see a generic solution to this problem, but at least it looks strange that `IMarkupFormatter` implementations can't control output for `script` elements at all.

**Comment by FlorianRappl** [comment]
Well, how should they? The `TextContent` is already set, but it has been generated by the parser. The element itself does not know how it has been generated. It only knows about its current state.

**Comment by thorn0** [comment]
I just was under an impression that `IMarkupFormatter` is supposed to have total control over the output. so it was a bit of surprise to find out there are cases when the content is output directly without invoking any methods of the formatter. I'm not saying it should be changed though. It's just my feedback.

**Comment by FlorianRappl** [comment]
Yeah sure, but as I said: Its loosely coupled and it has no way of knowing that. If you want such a control and the behavior is not pleasing you, then you can easily compose your own implementation. The existing formatters are only there to provide some convenience and to already output to the specified text representation (HTML -> HTML, XML -> XML).

**Comment by thorn0** [comment]
Another question about `XmlMarkupFormatter`. Why doesn't it escape `<` and `>` in attributes? 

Reading something like `attr='<'` makes .NET's XML parser throw an exception.

**Comment by FlorianRappl** [comment]
The latter (`>`) is allowed and shouldn't be transformed to an entity. But with the former (`<`) you are definitely right.

Thanks for spotting the issue!

**Comment by FlorianRappl** [comment]
Merged, see #323.

**Comment by thorn0** [comment]
I don't see how #323 solves this issue.

**Comment by FlorianRappl** [comment]
I see it. The original issue, as given in the discussion, invalid and won't be "solved". The thing that came out is that an XHTML formatter may be useful (that's the reason the issue stayed open). The PR implemented an XHTML formatter, thus this issue is closed.

**Comment by thorn0** [comment]
The issue can't be solved in the most general case, nevertheless a big part of it is solvable

You wrote:

> Not everything that is valid in HTML can be translated to XML - HTML has a 5 tokenization states unlike XML. Things like script state (for script tags) or rawtext (e.g. style) or even raw characters (title, textarea) are not present in XML. The XmlMarkupFormatter is not prepared for these edge cases.

As far as I understand, the new formatter still doesn't have any control over formatting these things: scripts, rawtext, raw characters, which means for example that it doesn't escape enities in the content of `textarea` elements whereas browsers parse those elements in different ways in the HTML and XHTML modes.

``` html
<textarea>1<b>foo</b>2</textarea>
```

Given this markup, Chrome renders following results in different modes.

HTML:
![image](https://cloud.githubusercontent.com/assets/94334/14887249/96461eda-0d5d-11e6-9721-02d011a0cb51.png)

XHTML:
![image](https://cloud.githubusercontent.com/assets/94334/14887306/e6ef0f22-0d5d-11e6-82e3-eada13c69e70.png)

As you can see, it'd be totally reasonable 1) to allow `IMarkupFormatter` to control output for raw characters, 2) to implement this method in the XHTML formatter so that it'd escape entities in textareas.

As for the issue with scripts, it can be solved at least for JS, which is not bad at all.

**Comment by thorn0** [comment]
Oh, sorry, it turns out AngleSharp always escapes entities in textareas. Still why not allow the XHTML formatter to fix script elements with JS?

**Comment by FlorianRappl** [comment]
I think we are on the wrong path here. If you want the XHTML formatter to behave differently, then just file a PR (https://help.github.com/articles/using-pull-requests/). I would be happy to review and merge!
