### ISSUE TITLE
Split the creation and execution of the form DocumentRequest

### ISSUE THREAD

**Issue by joelverhagen** [AngleSharp/AngleSharp#129]
Currently `HtmlFormElement.Submit()` creates a `DocumentRequest` and submits it to the underlying `IDocumentLoader` via `BrowsingContextExtensions.OpenAsync(...)` as two consecutive steps.

For my use case, it is beneficial to split these two distinct actions into two methods. I would like to serialize and persist the intermediate `DocumentRequest` to allow deferred navigation. For example, imagine the submission of a form as the continuation to a subsequent web page. This `DocumentRequest` instance can be considered as a continuation token. There are some small details like restoring cookie state that are out of scope for the form itself.

Pull request forthcoming.

**Comment by FlorianRappl** [comment]
Yes, I guess this definitely makes sense. I'll have to think about it (and potential implications) in more detail, but generally speaking, making the whole process easier to extend and therefore providing several smaller steps is certainly beneficial. 

I'll look at the PR right away and feedback there! Thanks already for the good thoughts and enhancements.
