### ISSUE TITLE
Color Declaration value's CssText does not preserve original text 

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#131]
If this is parsed:

`p {background-color:#ffffff;}`

The CssText of the declaration value returns `rgb(255,255,255)` instead of the original text.

The fix is a single line, in StringExtensions.cs.

Change:

```
        if (Color.TryFromHex(value, out color))
            return color.ToString(null, CultureInfo.InvariantCulture);
```

to

```
        if (Color.TryFromHex(value, out color))
            return "#" + value;
```

Hope you agree with this fix.

**Comment by FlorianRappl** [comment]
This is intentional and won't be fixed like that. What you want is the original value - which you can easily obtained by ignoring invalid values.

Also you may look for something like #38 - which will come in v0.9. That way not only the inserted value, but also the inserted position is preserved.

**Comment by corliss** [comment]
Please, I don't understand your comment - what do you mean by "obtain by ignoring invalid values"? There isn't anything invalid here. I'm just trying to find out what the original css contains!

How do I do this?

**Comment by FlorianRappl** [comment]
You pass in options to the CSS parser. If invalid values are ignored no validation will be done. Without validation the incoming value is not recognized as a color, hence no color will be serialized.

You are looking for the serialization of the given tokens, not the provided value. The value is serialized in rgb / rgba form, the token will be serialized as given.

**Comment by corliss** [comment]
Again, I don't understand what you mean. It seems like you are talking about something totally different.

This is a simple piece of valid CSS. I'm just trying to parse it with AngleSharp, and read the original text of the property value using

`(p as Dom.CssProperty).DeclaredValue.CssText`

which is currently converting the color to an rgb format instead of returning the original value.

The css parser options are:

``` C#
                    IsIncludingUnknownDeclarations = true,
                    IsIncludingUnknownRules = true,
                    IsToleratingInvalidConstraints = true,
                    IsToleratingInvalidValues = true,
```

Please try and understand my question - I don't think we're on the same page here. 
(It could be that I am the one who doesn't understand what you're saying, so please bear with me here.)
