### ISSUE TITLE
Send value from Javascript to C# function?

### ISSUE THREAD

**Issue by GuerrillaCoder** [AngleSharp/AngleSharp#135]
Hi,

I am looking at replacing the web browser control in my C# winforms app with AngleSharp.

Is it possible to pass values back and forth from C# and JavaScript methods?  I saw the sample with listening with events but wasn't sure how to pass a value.

With the web browser control the way I currently do it is:

JavaScript to C#:
var return = window.external.MyCSharpFunc(myValue);

C# to JavaScript:
var return = WebBrowser.Document.InvokeScript("MyJSFunc", new object[] { myValue });

Is there an equivalent way to do this in AngleSharp?

**Comment by FlorianRappl** [comment]
AngleSharp does not provide any JavaScript bindings out of the box. I think you are looking for the AngleSharp.Scripting project (https://github.com/AngleSharp/AngleSharp.Scripting). Here Jint is used by default as JavaScript engine.

Can you repost in the appropriate place? Unfortunately I can't move issues. This question is too closely related to the JavaScript engine to be answered here.

But to be brief: Yes you can do that. You need to store the value in some accessible position and retrieve it with Jint. In the end it all boils down to using Jint.
