### ISSUE TITLE
CSS Unicode escapes not properly parsed

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp#141]
Whitespace other than a single space after Unicode escapes in CSS is parsed incorrectly. Example:

``` C#
var html = @"<DIV STYLE='background: \000075
rl(javascript:alert(""foo""))'>";
var parser = new HtmlParser(new Configuration().WithCss(e => e.Options = new CssParserOptions
{
    IsIncludingUnknownDeclarations = true,
    IsIncludingUnknownRules = true,
    IsToleratingInvalidConstraints = true,
    IsToleratingInvalidValues = true
}));
var dom = parser.Parse(html);
var div = (IHtmlElement)dom.QuerySelector("div");
var bg = div.Style.First().Value; // "u\nrl(...)", should be "url(...)"
```

The relevant specification is at http://www.w3.org/TR/CSS2/syndata.html#escaped-characters
The code is at https://github.com/AngleSharp/AngleSharp/blob/0f56203a4ee28b3ce7dffaf9d8a5891daf91a243/AngleSharp/Parser/Css/CssTokenizer.cs#L1472-L1473

I can submit a PR if you want.

**Comment by FlorianRappl** [comment]
Yes, that would be welcome (but please to the `devel` branch). Instead of the comparison with a space, I recommend you to use the `IsSpaceCharacter` char extension method. It does the right thing according to the spec (space, tab, lf, cr and ff are covered).
