### ISSUE TITLE
Css Parser: expose selector information via the API

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#146]
Migrated from #38:

There is no way to find out (using either the parse tree or OM) many selector properties. Instead, AngleSharp directly converts these into functions (lambdas) for its own internal use only. For example:
a) In nth-child of the format an+b, AngleSharp does not expose a and b.
b) Other examples: the AttrAvailable and AttrBegins forms of simple selectors do not expose their parameters.

**Comment by FlorianRappl** [comment]
This will be done in #352 via a visitor pattern.
