### ISSUE TITLE
UnknownSelector returned for text

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#151]
This is an "information" issue. I don't know what the right behavior is here, so just checking with you.

This stylesheet snippet

```
#content {
    /* Fixes old versions of FireFox */
    /* @noflip */
    body.rtl div.vectorMenu > div.menu,
    x:-moz-any-link {
        margin-left: 23px;
    }
}
```

Yields an UnknownSelector with text
`"body.rtl div.vectorMenu > div.menu,\n\tx:-moz-any-link "`

Is this expected?

**Comment by FlorianRappl** [comment]
Yes, the pseudo class _-moz-any-link_ is unknown and therefore the whole selector is unknown.
