### ISSUE TITLE
Textarea value is not available to innerHtml/outerHtml

### ISSUE THREAD

**Issue by jobolito** [AngleSharp/AngleSharp#152]
I think that the Textarea value attribute is does not work as expected. In a browser setting, the textarea value (eg content of the textarea) can be read and set using the value attribute which also makes it available as part of the document content, but in AngleSharp (0.9.1) it will not be available in the document content.

This test illustrates the issue:

``` C#
[Test]
        public void CanPopulateTextareaRaw()
        {
            var htmlDoc = new HtmlParser().Parse("<textarea id='txt1' name='textarea1'></textarea>");
            var txtArea = (IHtmlTextAreaElement)htmlDoc.GetElementById("txt1");
            txtArea.Value = "textarea1value";
            Assert.AreEqual("textarea1value", txtArea.Value); //value is set ok

            var text = htmlDoc.DocumentElement.InnerHtml;
            Assert.That(text.Contains("textarea1value"), "textarea not populated");
        }
```

Setting the value using TextContent works fine, but I believe setting value should have the same effect.

Btw, AngleSharp is a great library, thanks!

**Comment by FlorianRappl** [comment]
Thanks for reporting this issue. Much appreciated! I will investigate it. Here's a MWE to reproduce the behavior regarding setting `textarea.value` in the browser.

``` html
<!DOCTYPE html>
<html>
<body>
<textarea>Test</textarea>
<script>
var t = document.querySelector('textarea');
console.log('before', t.outerHTML);
t.value = 'Foo bar';
console.log('after', t.outerHTML);
</script>
</body>
</html>
```

What I see is the following (Opera 32):

![image](https://cloud.githubusercontent.com/assets/1766191/9931729/8dbf1764-5d3e-11e5-9b42-c12e7b111ca5.png)

I guess this is the behavior of AngleSharp at the moment. Am I doing something wrong here? Does the presented MWE align with your report or did I miss something?

**Comment by jobolito** [comment]
You're right, I'm wrong. Sorry about that. So setting TextContent is actually the right way to do it (for my scenario). 

The one thing that threw me off is this though: After setting TextContent, Value will equal TextContent, which I also thought was inconsistent, but after browser testing it turns out that the same behavior applies there. 

This is obviously the desired behavior :)

``` html
<!DOCTYPE html>
<html>
<body>
<textarea>Initial</textarea>
<script>
var t = document.querySelector('textarea');
console.log('does setting textContent affect value?');
console.log('value before:', t.value);
t.textContent = 'Foo bar';
console.log('value after:', t.value)

console.log('does setting value affect textcontent?');
console.log('textContent before:', t.textContent);
t.value = 'Finally';
console.log('textContent after:', t.textContent)

</script>
</body>
</html>
```

**Comment by FlorianRappl** [comment]
Glad to hear that! But keep posting such potential issues, the spec. is vast and implementation mistakes can happen.
