### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by useruser1** [AngleSharp/AngleSharp#153]
document.QuerySelector("form[action=someaction]"); // return form
document.QuerySelector("form").QuerySelector("[action=someaction]"); // return null

QuerySelector like $.find ?

**Comment by FlorianRappl** [comment]
Nope, `QuerySelector` in AngleSharp is the same as `querySelector` in the browser.

Running the following sample in any evergreen browser yields `(form, null)`.

``` html
<!DOCTYPE html>
<html>
<body>
<form action="someaction">
</form>
<script>
console.log(document.querySelector('form[action=someaction]'));
console.log(document.querySelector('form').querySelector('[action=someaction]'));
</script>
</body>
</html>
```

In a way `querySelectorAll` is like `$.find`. Both only operate on children. The difference between `querySelector` and `querySelectorAll` is that the former stops on the first hit, while the second one iterates over all the descendants.

**Comment by useruser1** [comment]
any variants for $.Filter ?
