### ISSUE TITLE
Attribute name contains namespace

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#155]
Parsing this html: https://en.wikipedia.org/wiki/Gregorian_calendar
generates an attribute somewhere during parsing, whose `LocalName` is `xml:lang`, and whose `prefix` and `NamespaceUri` are both `null`.

I'd expect the `xml:` to be returned in the `prefix`.

Is this a bug? Thanks.

**Comment by FlorianRappl** [comment]
I think its no bug. My browser shows the same behavior. For testing I took the following element: `span[lang=la]`. In HTML it was defined as `<span lang="la" xml:lang="la">`. `xml:lang` is a special attribute.

> Authors must not use the lang attribute in the XML namespace on HTML elements in HTML documents. To ease migration to and from XHTML, authors may specify an attribute in no namespace with no prefix and with the literal localname "xml:lang" on HTML elements in HTML documents, but such attributes must only be specified if a lang attribute in no namespace is also specified, and both attributes must have the same value when compared in an ASCII case-insensitive manner.

**Comment by corliss** [comment]
OK, great. Thanks.

A totally unrelated question (but from the same wikipedia page). What does the `!ie` mean at the end of `background-image:url("//en.wikipedia.org/static/1.26wmf23/skins/Vector/images/tab-break.png?2df0f")!ie;`? 

Does the css spec allow for such declarations? This [part](http://www.w3.org/TR/CSS21/syndata.html#value-def-uri) of the specification only says:

The format of a URI value is 'url(' followed by optional white space followed by an optional single quote (') or double quote (") character followed by the URI itself, followed by an optional single quote (') or double quote (") character followed by optional white space followed by ')'. The two quote characters must be the same.

It doesn't mention anything about suffixes such as `!ie`. Does another part of the specification cover this?

**Comment by FlorianRappl** [comment]
This is an old CSS hack afaik. It works for IE 6 / 7 and has the same effect as "!important", however, other browsers will identify it as invalid. Thus making the given declaration only valid for IE 6 / 7.

**Comment by corliss** [comment]
Got it. Thanks again. BTW I've noticed all the cool stuff coming in the feature branches - just wondering when the v0.9.2 integration will occur?

**Comment by FlorianRappl** [comment]
I merged the ones that will make it to v0.9.2 into the `devel` brnach yesterday, but it was too late (and I was too tired) to release it. I will look over it tonight. So I will release the v0.9.2 (and update `master`) either tonight or tomorrow!
The CSSOM (issues #145, #146) are unfortunately not finished yet. I started working on them, so I'm optimistic that they will make it in v0.9.3.

**Comment by corliss** [comment]
No worries. Thanks!
