### ISSUE TITLE
Flex hex parsing (Color)

### ISSUE THREAD

**Issue by mretlenj** [AngleSharp/AngleSharp#166]
Hi,
It is said that latest release provides flex hex parsing (Color). Does that mean that I can keep original hex color representation when parsing, instead of changing to rgba. 
If so, can you please give a simple example how to achieve that, or how to efficiently round-trip document to convert changed color representation back.

Thanks in advance.

**Comment by FlorianRappl** [comment]
The flex hex parsing is independent of CSS. Flex hex is something "invented" by the IE team (?) for HTML attributes such as `bgcolor`. In AngleSharp we can parse flex hex colors via a static method of the `Color` type.

As far as your question is concerned I'd love to see a MWE of your code (and what / why you want to get the hex values). Then I will try to alter it to achieve your desired scenario. In general it is possible already, yes.

**Comment by mretlenj** [comment]
We're using AngleSharp to parse html that is actually eMail. Changing color codes from rbg to hex is done because some eMail clients does not support rgb function. New ones probably support, but old ones does not.

In pseudo code, we're currently doing something like this:

``` csharp
{
var styleSheet = new CssParser.Parse(string css);
foreach(var rule in styleSheet.Rules)
    ChangeColors(rule);
}

ChangeColors(ICssRule)
{
   someRegex.Match(rule.cssText) ;
   rule.cssText.Replace(rgbPatern, hexPatern);
}
```

Some more detailed code example and full regex expression is attached.
Thx in advance.

_FR: Edited the question a bit regarding the formatting._

**Comment by mretlenj** [comment]
I can't attach file directly in browser, here is full regex.

_Sincerely / Mit freundlichen Grüßen_
_Dragutin Čičulić_

2015-10-01 14:41 GMT+02:00 Florian Rappl notifications@github.com:

> The flex hex parsing is independent of CSS. Flex hex is something
> "invented" by the IE team (?) for HTML attributes such as bgcolor. In
> AngleSharp we can parse flex hex colors via a static method of the Color
> type.
> 
> As far as your question is concerned I'd love to see a MWE of your code
> (and what / why you want to get the hex values). Then I will try to alter
> it to achieve your desired scenario. In general it is possible already, yes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AngleSharp/AngleSharp/issues/166#issuecomment-144715055
> .

﻿using System;
using System.Text;
using System.Text.RegularExpressions;
using AngleSharp.Dom.Css;
using AngleSharp.Parser.Css;
using HtmlAgilityPack;

namespace Test
{
    internal class Program
    {
        private static void Main(string[] args)
        {
        }

```
    internal static string PrepareContent(string html, string css)
    {
        //our HtmlDocument class, basically using HtmlAgilityPack
        //var body = HtmlDocument.GetBodyNode(html);
        //var document = GenerateHtmlDocument(body);
        if (!string.IsNullOrWhiteSpace(css))
        {
            var styleSheet = new CssParser().ParseStylesheet(css);
            //ApplyInlineStyles(ref body, styleSheet);
        }


        //just dummy return;
        return string.Empty;
        //return document.WriteToString();
    }


    private static void ApplyInlineStyles(ref HtmlNode node, ICssStyleSheet styleSheet)
    {
        if (styleSheet != null && !string.IsNullOrWhiteSpace(styleSheet.CssText))
        {

            var css = FixDeclarations(styleSheet);

            //do some other works

        }
    }

    private static string ReplaceRgba(Match match)
    {
        var r = byte.Parse(match.Groups[1].Value);
        var g = byte.Parse(match.Groups[2].Value);
        var b = byte.Parse(match.Groups[3].Value);
        var hex = string.Format("#{0:X2}{1:X2}{2:X2}", r, g, b);
        return hex;
    }

    // AngleSharp workaround: the lib replaces HEX color codes by rgba() function; for email compability they have to be converted back
    private static string FixDeclarations(ICssRule rule)
    {
        const string pattern = @"rgba[(](\d{1,3})\s?,\s?(\d{1,3})\s?,\s?(\d{1,3})\s?,\s?(\d{1,3})[)]";
        var css = rule.CssText.Replace(Environment.NewLine, string.Empty).Trim();
        var evaluator = new MatchEvaluator(ReplaceRgba);
        css = Regex.Replace(css, pattern, evaluator, RegexOptions.IgnoreCase);
        return css;
    }

    private static string FixDeclarations(ICssStyleSheet styleSheet)
    {
        if (styleSheet == null || string.IsNullOrWhiteSpace(styleSheet.CssText))
            return string.Empty;

        var builder = new StringBuilder(styleSheet.CssText.Length);

        foreach (var rule in styleSheet.Rules)
        {
            var css = FixDeclarations(rule);
            builder.AppendLine(css);
        }
        return builder.ToString().TrimEnd();
    }
}
```

}
