### ISSUE TITLE
Using HttpClient implementation for IRequester

### ISSUE THREAD

**Issue by joelverhagen** [AngleSharp/AngleSharp#169]
The implementation of `IRequester` built into AngleSharp uses the `System.Net.HttpWebRequest` API from the .NET Framework. However, the newer `System.Net.Http.HttpClient` allows for easier extensibility (primarily through chaining `DelegatingHandler` around a `HttpClientHandler` or `WebRequestHandler`) and has built-in `async` support.

I have build an implementation of `IRequester` that takes an `HttpClient` as a constructor parameter and does not use `HttpWebRequest` at all. Would an appropriate place for this implementation be in AngleSharp itself? Or should I create my own NuGet, e.g. AngleSharp.NetHttp or something like that?

**Comment by FlorianRappl** [comment]
That should / would be part of _AngleSharp.Io_. There would be a lot more things in such a project, but the most important one is - as you noticed - `IRequester`. I guess you understand that AngleSharp itself is a PCL and therefore cannot use the `HttpClient`. _AngleSharp.Io_ would not be constraint to a PCL.

So if you want to start with _AngleSharp.Io_ I could give you everything you need. In the beginning it is certainly sufficient to have only an improved `IRequester` implementation. Once I find the time I would then add more things (such as possibilities to, e.g., integrate caching).

**Comment by joelverhagen** [comment]
Sure, that sounds reasonable. I don't see a AngleSharp.Io project in this git repository or see any AngleSharp/AngleSharp.Io git repository. I presume this is a new project then?

I can start the framework of the new project in this git repository if you'd like but I imagine there are some conventions you'd like to establish first that I can build on. Just let me know what you want.

To give you an idea of what I have implemented, here is the code that I will merge into AngleSharp.Io: [HttpClientRequester](https://github.com/joelverhagen/AngleSharp.NetHttp/blob/master/AngleSharp.NetHttp/HttpClientRequester.cs).

**Comment by FlorianRappl** [comment]
Yes, it is a new project. I guess it makes sense that I create project. I will do that later tonight and notify you then.

The code looks fine - it will be a great addition!

**Comment by FlorianRappl** [comment]
Alright @joelverhagen - I've setup _AngleSharp.Io_ (https://github.com/AngleSharp/AngleSharp.Io). Consider it your playground :sunglasses:.
