### ISSUE TITLE
CSS bug: Can't set set the Display property of Style

### ISSUE THREAD

**Issue by silverbird** [AngleSharp/AngleSharp#17]
Hi,I've use AngleSharp version 0.4 for months, and it is robust and works very well for so long, until today when I tried to change the Style of a table row.

My project crashed at this line:
   tr.Style.Display = "none";
where tr is of type HTMLTableRowElement. The error message is as below:

A first chance exception of type 'System.NullReferenceException' occurred in AngleSharp.DLL
Additional information: Object reference not set to an instance of an object.

Probably it is something wrong in the internal, because I can inspect that the Display property is not null and has the value of "inherited".

btw, great job!

**Comment by FlorianRappl** [comment]
Thanks for the report. I had a short look into this problem and my very simple test did not show this problem. Could you please post a distilled version of your code and / or the HTML file you are working with (needs only to be the problematic subset).

Thanks for your comment, much appreciated.

**Comment by silverbird** [comment]
thanks for the quick reply. The web page I am parsing is in Chinese(charset=gb2312). The link is http://trade.500.com/bjdc/. The page contains several  match list table and I want to hide some match row in them.
here is the detailed code:

using System.Runtime.InteropServices.WindowsRuntime; //NOTE: needed

```
    public static async Task test()
    {

        var httpClient = new HttpClient();
        var downloadTask = httpClient.GetBufferAsync(new Uri("http://trade.500.com/bjdc/?expect=140107"));

        var response = await downloadTask;

        string pageSource = Encoding.GetEncoding("gb2312").GetString(response.ToArray(), 0, (int)response.Length - 1);
        HTMLDocument document = DocumentBuilder.Html(pageSource);

        var ls = document.GetElementsByClassName("vs_lines");
        var ls2 = document.GetElementsByClassName("vs_lines even");
        var c = ls.Concat(ls2);

        foreach (var item in c)
        {
            var tr = item as HTMLTableRowElement;
            if (tr.RowIndex % 2 ==0)
            {
                tr.Style.Display = "none";
            }
        }


    }
```

**Comment by FlorianRappl** [comment]
Hm, that still works on my machine, however, I suppose that the problem might only occur on a certain platform. I tested it with .NET 4.5 in a console application - is your platform Windows Store (targetting Windows 8 or Windows 8.1?) or Windows Phone (8?) or ... ?

I think I'll need to investigate further. Thanks for the source.

**Comment by silverbird** [comment]
Sorry for forgetting to mention that my project is Windows Store app. I have tested it on both Win 8.1 pro and WinRT and got the same error. 

btw:I am using VS 2013 for Windows express, so I can not open PCL project to debug the source code of AngleSharp. 

Many thanks for your time! Great job. Really love AngleSharp.

**Comment by FlorianRappl** [comment]
Hm, is there anything new? Is the bug still available in the latest version of AngleSharp?

As mentioned above unfortunately (or fortunately?!) the code above worked on my machine, which is why I could not reproduce the exception. If you are still experiencing this bug, then I am more than open for trying to resolve it. Thanks!

**Comment by FlorianRappl** [comment]
Seems to be fixed.
