### ISSUE TITLE
HTML comments in CSS

### ISSUE THREAD

**Issue by zumbuschms** [AngleSharp/AngleSharp#170]
How is the CSS parser supposed to handle HTML comments inside a CSS? Some web authors and email clients still include `<!-- -->` in embedded style tags to prevent CSS shown in very old browsers that do not support CSS.

Here is an example:

`<style><!-- body { font-family: Verdana } div.hidden { display: none } --></style>`

If I have CSS parser process the stylesheet including the comment tags the body rule is ignored by the parser.

**Comment by FlorianRappl** [comment]
In case of the HTML comments the tokenizer emits special tokens (CDO / CDC) which should be ignored by the parser. Everything in the HTML comment is thus parsed as usual.

**Comment by zumbuschms** [comment]
We tried to parse such a CSS with the lastest version of AngleSharp from master and only the second rule was included in the CssStylesheet DOM.

**Comment by FlorianRappl** [comment]
Seems like a bug to me. I will investigate. Will be fixed in the upcoming release.
