### ISSUE TITLE
How to get full html via ajax.

### ISSUE THREAD

**Issue by nguyengiap1467** [AngleSharp/AngleSharp#171]
I'm using AngleSharp with WebClient get html page. But result response only html static without content return via ajax jquery.
How to using AngleSharp complete this task.
Thanks !

**Comment by FlorianRappl** [comment]
AngleSharp itself only delivers an HTML and CSS parser. What you want is JavaScript evaluation. It could be that _AngleSharp.Scripting.JavaScript_ is already good enough for you, however, some things are not implemented and not all scripts will work at the moment. I would just give it a try.

**Comment by nguyengiap1467** [comment]
Thanks FlorianRappl !
I know and I'm using AngleSharp.Scripting.JavaScript in my project. But I don't know step by step get content return ajax. 
You can provide a sample step by step about using AngleSharp.Scripting.JavaScript get content return ajax ?
Thanks so much.

**Comment by FlorianRappl** [comment]
What exactly is the scenario you try to cover? You need to be as explicit as possible. Also: Did you look already at [the samples](https://github.com/AngleSharp/AngleSharp.Samples)? Maybe the answer is already there.
