### ISSUE TITLE
Cannot access style property of a element

### ISSUE THREAD

**Issue by mjfaga** [AngleSharp/AngleSharp#172]
Hi there,

Love what this library is trying to do!!! I'm actually trying to take advantage of your JavaScript evaluation functionality, but am having an issue accessing a property off of the element object. I've boiled it down using a modified version of your example online for reference. This runs fine in the browser, but the `document.write(node.style.fontSize);` line seems to blow up when using AngleSharp. Any help you can provide is appreciated!

``` c#
//We require a custom configuration
var config = Configuration.Default.WithJavaScript();
//Let's create a new parser using this configuration
var parser = new HtmlParser(config);

//This is our sample source, we will set the title and write on the document
var source = @"<!doctype html>
                <html>
                <head><title>Sample</title></head>
                <body>
                    <div id='full-name' style='display:inline-block;font-size:40px;line-height:40px;margin:10px auto 0 auto;word-wrap:none;white-space:nowrap;'>Sample</div>
                    <script>
                        document.title = 'Simple manipulation...';
                        var node = document.getElementById('full-name');
                        document.write(node.id);
                        document.write(node.style.fontSize);
                    </script>
                </body>
                </html>";

var document = parser.Parse(source);

//Modified HTML will be output
Console.WriteLine(document.DocumentElement.OuterHtml);

Console.ReadLine();
```

**Comment by FlorianRappl** [comment]
Thanks for your question. The problem I see here is that the CSS engine is not loaded. Can you try to modify the code to use:

``` csharp
var config = Configuration.Default.WithJavaScript().WithCss();
```

That will provide the default style engine with CSS. Does it work now?
(I get the two values reversed, which seems to be a bug in the `document.write` method - but apart from that it works.)

**Comment by mjfaga** [comment]
Yep, agreed per your reversed comment above. That is all set. 

Any change you could tell me when you guys think you will have support for window added in? I need to get the rending size of elements in my script... something like `window.getComputedStyle(node, null).getPropertyValue('width')`. Is something that you will support, or for that matter, have a work around for?

**Comment by FlorianRappl** [comment]
This scenario will definitely supported, but unfortunately I can't tell you when it will be available. BTW: `window` is already available (and I think the `getComputedStyle` method works as well), but the results could be different from browsers.
