### ISSUE TITLE
xml-stylesheet on XML Document

### ISSUE THREAD

**Issue by Violante** [AngleSharp/AngleSharp#175]
Hello,
I'v tried to parse (width XML parser) somethong like  :
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href=""xml.css""?>
<DOCUMENT><P id='test'>Text Content</P></DOCUMENT>
but afetr getting P element with test id, the function GetComputedStyle on DefaultView gives an empty ICssStyleDeclaration object.
Is applying CSS to XML DOM possible width anglesharp ?
Thank's

**Comment by FlorianRappl** [comment]
In theory it is possible, but you have to write the evaluation yourself. XML is unlike HTML not directly wired to CSS. However, selectors work the same way and if you inject stylesheets the `GetComputedStyle` method could also work (even though I have not tried it yet).
- `style` attributes will not work (unless you parse them somehow and map element -> style yourself)
- `link` or `style` elements will not be parsed automatically (and they are plain XML elements, not, e.g., `IHtmlLinkElement` instances) - you need to do that and inject the results

Possibly its easier to just use the HTML parser. I don't know the exact markup you have.

**Comment by Violante** [comment]
Thank you for responding Florian.
Could you tell me in which file(s) (in anglesharp sources) I could see how are applied CSS styles to HTML elements.
Thank's a lot for your awsome work.

**Comment by FlorianRappl** [comment]
Thanks! If you like AngleSharp make sure to star it ;).

The [`Element` class](https://github.com/AngleSharp/AngleSharp/blob/master/AngleSharp/Dom/Element.cs) already contains a `CreateStyle()` method. This method is then used in for instance [`HtmlElement`](https://github.com/AngleSharp/AngleSharp/blob/master/AngleSharp/Dom/Html/HtmlElement.cs). Here we find the following lazy-loaded property:

``` csharp
public ICssStyleDeclaration Style
{
    get { return _style ?? (_style = CreateStyle()); }
}
```

The constructor of `HtmlElement` makes sure to add an handler, which triggers changes on update (only if the style has been loaded):

``` csharp
/* ... */
            RegisterAttributeObserver(AttributeNames.Style, value =>
            {
                var bindable = _style as IBindable;

                if (String.IsNullOrEmpty(value))
                    RemoveAttribute(AttributeNames.Style);

                if (bindable != null)
                    bindable.Update(value);
            });
/* ... */
```

Other classes are, e.g., [`HtmlStyleElement`](https://github.com/AngleSharp/AngleSharp/blob/master/AngleSharp/Dom/Html/HtmlStyleElement.cs), where we update the contained stylesheet once the sub-nodes change.
