### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by rcronin** [AngleSharp/AngleSharp#181]
How do I specify cookies in my request? No matter what I do the cookies do not save or change my request that I am pulling back.

Here's my code:

```
        var config = Configuration.Default.WithDefaultLoader();
        var request = new DocumentRequest(new Url("http://www.google.com"));
        request.Headers.Add("Cookie", "location=39.5978465%2C-84.15406589999998;" + string.Format("expires={0};", DateTime.MinValue.ToString("yyyy-MM-dd-HH:mm:ss:ffffff")));
        var page = await BrowsingContext.New(config).OpenAsync(request, new System.Threading.CancellationToken());
```

**Comment by FlorianRappl** [comment]
Please integrate cookies in your configuration. The default configuration is cookie-less.

``` csharp
var config = Configuration.Default.WithDefaultLoader().WithCookies();
```

By the way: The simplest way to create some pseudo cancellation token is `CancellationToken.None`. Additionally, there AngleSharp offers some overloads that will pass that on for you. Hence you do not have to specify a pseudo cancellation token.

**Comment by rcronin** [comment]
@FlorianRappl Thanks for the response. I forget to mention I did add the WithCookies() extension. However, it only shows my first cookie in the Cookie property of the HTMLDocument object. Is there anyway I can specify multiple cookies?

**Comment by FlorianRappl** [comment]
There is always just a single cookie string. This is by HTTP specification. What you are referring to is how the cookie string is split up. By default AngleSharp uses `CookieContainer` from the .NET framework. This way cookie strings are decomposed and aggregated per domain.

If that part is not behaving like you want you can just provide your own `ICookieService` implementation.

_Like AngleSharp and want to support it? Giving it a star would be a good start!_

**Comment by rcronin** [comment]
Ah, that would make sense. Here's what I ended up doing to get my second cookie recognized by the website for anyone that is interested.

```
        var config = Configuration.Default.WithDefaultLoader();


        CookieContainer cookies = new CookieContainer();
        cookies.Add(new Uri("http://www.google.com"), new Cookie("location", "39.5978465%2C-84.15406589999998"));
        cookies.Add(new Uri("http://www.google.com"), new Cookie("expires", DateTime.MinValue.ToString("yyyy-MM-dd-HH:mm:ss:ffffff")));

        var request = (HttpWebRequest)WebRequest.Create("http://www.google.com");
        request.CookieContainer = cookies;

        var response = await request.GetResponseAsync();

        var page = new HtmlParser().ParseAsync(response.GetResponseStream());
```

**Comment by FlorianRappl** [comment]
Even though that works I would not recommend it. The `BrowsingContext` also does a lot of other things (besides using the requester correctly). Furthermore, all the headers will be forgotten in your approach (or you need to take care of them yourself). Plus subsequent requests (e.g., imported documents, frames, ...) won't happen.

It's much easier (and more flexible) to just instantiate the default cookie service, create a new configuration with it, and manipulate the underlying `CookieCollection` before / after requests.

**Comment by jlchmura** [comment]
I've been having issues too, and I believe it is because the cookie string returned by the request (via `GetCookieHeader()`) is delimited by semicolons.  However, the `CookieContainer.SetCookies` method used by the default cookie service is expecting commas. 

Per [https://msdn.microsoft.com/en-us/library/system.net.cookiecontainer.getcookieheader.aspx](https://msdn.microsoft.com/en-us/library/system.net.cookiecontainer.getcookieheader.aspx):

> _This string is not in the correct format for use as the second parameter of the SetCookies method._

**Comment by FlorianRappl** [comment]
Well, the provided cookie service is just the default one. I don't know if it makes sense to bring up a full machinery to parse _all_ cookies correctly (actually, I was hoping the structure provided by Microsoft does that) - at least in the core library. Is there a _simple_ fix that is supposed to work for _all_ (legal) cookies?

Any contribution welcome!

**Comment by jlchmura** [comment]
My theory for a simple fix is to pass the cookie container directly to and from the `HttpWebRequest` and `HttpWebResponse` objects instead of a string of the cookie header, and let those classes handle everything. From what I've read, it should work.  

If I have some time, I'll write my own service and test this. Will post here if it does.

All to say, you may want to re-open this issue...

**Comment by FlorianRappl** [comment]
Well, but wouldn't that create a strong coupling between this cookie container and any requester? In general I tend to avoid such couplings as it would reduce extensibility. Maybe there is another way... Otherwise, we can always think of improving the situation, e.g., by placing a better container in _AngleSharp.Io_.

**Comment by engbryan** [comment]
My sugestion:

IDocument.Request.Headers[string]
IDocument.Request.Cookies[string]
IDocument.Response.Headers[string]
IDocument.Response.Cookies[string]

**Comment by engbryan** [comment]
The way it is done now, it is required to work with RestSharp for HTTP followed by AngleSharp for DOM.

My sugestion:
IDocument.Request.Headers[string_name]
IDocument.Request.Cookies[string_name]
IDocument.Response.Headers[string_name]
IDocument.Response.Cookies[string_name]


A workaround for those who may be interested: 
```

            var request = new RestRequest(Method.POST);
            request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            request.AddHeader("Authorization", $"Basic {configuration.AuthToken}");

            IRestResponse response = await new RestClient(Address).ExecuteAsync(request);

            var document = await Context.OpenAsync(_ =>
            {
                //for DOM logic compatibility
                var cookieStr = response.Headers.FirstOrDefault(_ => _.Name.Equals("set-cookie", StringComparison.InvariantCultureIgnoreCase)).Value as string;

                _.Address(response.ResponseUri);
                _.Content(response.Content);

                _.Cookie(cookieStr);
                _.Headers(response.Headers.ToDictionary(_ => _.Name, _ => _.Value));
                _.Status(response.StatusCode);
            });

            //response.Cookies[]
            //response.Headers[]
            //request.Cookies[]
            //request.Headers[]

            //document.QuerySelectors()
```
