### ISSUE TITLE
Ability to register a custom pseudo selector type by name

### ISSUE THREAD

**Issue by datatooldev** [AngleSharp/AngleSharp#182]
Is it possible to add an option to register a custom selector or filter in CssSelectorConstructor? That would be a very useful enhancement.

**Comment by FlorianRappl** [comment]
This is currently not possible, but with the library approaching v1 I wanted to add the ability for _every_ factory to be extended. Your request would indeed be a very useful enhancement.

I'll add it to the list.

At the moment I can't work on AngleSharp as I am about to hand in my thesis, but I'll continue afterwards (=> in December).

**Comment by datatooldev** [comment]
To be really powerful the Match method should be able to receive a list of already collected nodes besides the current node. Also it would be very good to have a customisable Transfor method that takes a node and returns another node or nodes. 
In the end I want to implement "nth-match", "eq" and "get-parent" pseudo classes. They are not a part of the CSS4 standard but I need them in my project. 
I was able to do that with CsQuery engine because it has a base Index Selector and the extensibility support.  

I will glad to help you with testing if you go ahead with the changes.
Thank you very much for your prompt responses and an excellent job you did for this project!

**Comment by FlorianRappl** [comment]
Implemented see #329.
