### ISSUE TITLE
Index-related selectors

### ISSUE THREAD

**Issue by datatooldev** [AngleSharp/AngleSharp#183]
Will you support the index-related selectors (:eq(), :lt(), :gt(), :even, :odd) that filter the set of elements that have matched the expressions that precede them?

**Comment by FlorianRappl** [comment]
Those are not real selectors (as far as I know they only exist in jQuery). Of course, you could use LINQ to emulate their behavior on a returned set.

I will think about adding them (either in selector form or as extension methods, e.g., `Eq(...)`, `OnlyEven()`.

**Comment by FlorianRappl** [comment]
I've implemented them as extension methods. If one really wants them as part of the selector strings, then the upcoming feature #182 (release v0.9.6) will make that possible.
