### ISSUE TITLE
Query elements with a namespace prefix

### ISSUE THREAD

**Issue by j055** [AngleSharp/AngleSharp#185]
Hi

When I try to query the snippet below with the following:

```
var cellSelector = "o:p";
var cells = document.Body.QuerySelectorAll(cellSelector);
```

I get AngleSharp.Dom.DomException: The string did not match the expected pattern.

Can the `o:p` element be selected using AngleSharp?

```
        <p class="MsoNormal">
            <o:p>&nbsp;</o:p>
        </p>
```

Thanks
Andrew

**Comment by FlorianRappl** [comment]
This has nothing to do with AngleSharp. The way to select elements under a namespace is using the "|" operator.

See:
- [W3C Selectors API](http://www.w3.org/TR/selectors-api/)
- [StackOverflow Question](https://stackoverflow.com/questions/23034283/is-it-possible-to-use-htmls-queryselector-to-select-by-xlink-attribute-in-an)

Read the accepted StackOverflow answer carefully - it really covers most details you are interested in.

**Comment by j055** [comment]
Thanks for the quick reply. I couldn't get the pipe character to work but escaping the colon does give the results I'm expecting.

```
 var cellSelector = "o\\:p";
```

Thanks again
Andrew

**Comment by FlorianRappl** [comment]
Yes, as explained in the SO answer the pipe character requires CSS namespaces and conflicts with HTML5 treatment (but not with the XML version). Glad to hear that the escaping works as expected!
