### ISSUE TITLE
Accessing Styles with Relative Units

### ISSUE THREAD

**Issue by merthsoft** [AngleSharp/AngleSharp#186]
I'm trying to do `document.DefaultView.GetComputedStyle(element)`, but I get the following error: `System.InvalidOperationException: A relative unit cannot be converted`. Is there a way for me to get the style for an element without running into this when there are relative units? I just need to get what this element's style is to get some sizing information.

**Comment by FlorianRappl** [comment]
Yeah, I see your problem. I would love to attack this issue - but I also would love to have a full implementation of `GetComputedStyle`. Right now, its both, experimental and incomplete.

Here's what I propose: In the next patch (yes, I will have time to continue working on it shortly) I will remove the `InvalidOperationException` (thus only omitting such values instead of alarming the user with an exception).

Right now, the only way I see is to iterate over all styles and set relative units to zero.

**Comment by merthsoft** [comment]
I like your proposal! That would help me a lot. How would I go about iterating over all the styles and setting their relative units to zero? Right now I'm basically just going through the styleSheet.Rules and doing some LINQ to get out the rule I want, and then using some RegEx to parse it, which isn't quite ideal.

**Comment by FlorianRappl** [comment]
Hm the following code could work:

``` cs
foreach (var sheet in document.StyleSheets.OfType<ICssStyleSheet>())
{
    foreach (var rule in sheet.Rules.OfType<ICssStyleRule>())
    {
        var declarationNames = rule.Style.Where(m => m.Value.Contains("%")).Select(m => m.Name).ToArray();

        foreach (var declarationName in declarationNames)
        {
            rule.Style.RemoveProperty(declarationName);
        }
    }
}
```

I only used `%`, but you can (or should) use a regular expression with all the units. Also, this will improve in future versions, but right now its only the string representation. One more thing to keep in mind is that a better variant of this would use a recursive function call, as grouping rules (`ICssGroupingRule`) may contain (directly or indirectly) `ICssStyleRule` instances.

Hope this code helps you a bit!

**Comment by merthsoft** [comment]
Yes, thanks!

**Comment by FlorianRappl** [comment]
This will come with a much improved CSSOM. I am to bring this in for v0.9.6.

**Comment by FlorianRappl** [comment]
v0.9.7 will be dedicated to API (CSSOM and general) improvements.

**Comment by FlorianRappl** [comment]
Continued in AngleSharp.Css!
