### ISSUE TITLE
The header Cookie has an empty value.

### ISSUE THREAD

**Issue by merthsoft** [AngleSharp/AngleSharp#187]
I'm making an app for Windows Phone 8.1, using AngleSharp.0.9.3 from nuget, "portable-windows8+net45+windowsphone8+wpa". When I do the following:

```
var config = new Configuration().WithDefaultLoader(l => l.IsResourceLoadingEnabled = true).WithCss().WithCookies();
var document = await BrowsingContext.New(config).OpenAsync("http://google.com");
```

I get this error:
`System.ArgumentException {"The header Cookie has an empty value."}`

Stack trace:

```
at MS.Internal.Modern.ClientHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
at MS.Internal.Modern.ClientHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

This works as expected when using the net45 library in a console app.

I tried using an `HttpClient` to get the page itself, and that works fine, but it doesn't load in the CSS when I do it this way:

```
var mainPage = await client.GetStringAsync(MAIN_URL);
var config = new Configuration().WithDefaultLoader(l => l.IsResourceLoadingEnabled = true).WithCss().WithCookies();
var browsingContext = BrowsingContext.New(config);
var options = new HtmlParserOptions();
HtmlParser htmlParser = new HtmlParser(options, browsingContext);

var document = await htmlParser.ParseAsync(mainPage);
```

Is there an alternative to doing it these two ways that will still load the CSS in as expected?

**Comment by FlorianRappl** [comment]
As far as the first `ArgumentException` is concerned I'll investigate. From the stack trace it seems that the problem is within the .NET implementation in the PCL subset of the `HttpWebRequest`. If it is that way, then the best way would be to use the `HttpClient` in an `IRequester` implementation (there is one already pre-made in the _AngleSharp.Io_ package).

Giving AngleSharp another requester is also the possibility of using everything (e.g., automatic download of included resources) the way you know it - just with the other requester.

The `WithDefaultLoader` extension method accepts a second argument, which is supposed to be an enumerable of requesters to use. If nothing is passed in (`null` or no second argument), then the default requester(s) are used.

**Comment by merthsoft** [comment]
Okay, cool, I'll try those things--thanks! I'm actually going to be changing it around a bit, so I'll just be doing it through a console app and storing the data to a DB which when I'll access from the phone through a webservice, but I'll still try out these alternatives just to see what works.

**Comment by FlorianRappl** [comment]
I can't reproduce this issue. I can only assume that the requester on the given platform (WP 8.1) has a bug (the stack trace confirms this).

**Comment by csmorley** [comment]
On Windows 10 I have a similair issue where the default HttpWebRequest based requester hangs on download, it does not do it with HttpClientRequester().

The site i was running tests again is https://serverspace.ae.

Code here

`    public class AngleSharpTestService
    {
        readonly IBrowsingContext _context;
        readonly CancellationTokenSource _cts;
    
        public AngleSharpTestService()
        {
            _cts = new CancellationTokenSource();

            // for some reason, the default HttpWebRequest based requester seems to hanf
            var requesters = new IRequester[] { new DataRequester(), new HttpClientRequester() };

            var config = Configuration
                            .Default
                            .WithCss()
                            .WithDefaultLoader(c => c.IsResourceLoadingEnabled = true, requesters);

            _context = BrowsingContext.New(config);

            _context.Parsing += TrackParsing;
            _context.Parsed += TrackParsed;
            _context.Requesting += TrackRequesting;
            _context.Requested += TrackRequested;
        }

        private void TrackRequested(object sender, Event ev)
        {
            var data = ev as RequestEvent;

            if (data == null)
                return;

            Console.WriteLine("TrackRequested: " + data.Request.Address.Href);
        }

        private void TrackRequesting(object sender, Event ev)
        {
            var data = ev as RequestEvent;

            if (data == null)
                return;

            Console.WriteLine("TrackRequesting: " + data.Request);
        }

        private void TrackParsed(object sender, Event ev)
        {
            var html = ev as HtmlParseEvent;
            var css = ev as CssParseEvent;

            if (html != null)
            {
                Console.WriteLine("TrackParsed: " + html.Document.Url);
            }
            else if (css != null)
            {
                Console.WriteLine("TrackParsed: " + css.StyleSheet.Href);
            }
        }

        private void TrackParsing(object sender, Event ev)
        {
            var html = ev as HtmlParseEvent;
            var css = ev as CssParseEvent;

            if (html != null)
            {
                Console.WriteLine("TrackParsing: " + html.Document.Url);
            }
            else if (css != null)
            {
                Console.WriteLine("TrackParsing: " + css.StyleSheet.Href);
            }
        }

        public async Task LoadAsync(string address)
        {
            var url = Url.Create(address);
            var document = await _context.OpenAsync(url, _cts.Token);

            /*var elementsWithBackground = document.All.Where(e => e.Style.BackgroundImage.Length > 0);

            foreach (var element in elementsWithBackground)
            {
                var src = element.Style.BackgroundImage;
            }*/
        }
    }`

Output when using the default HttpRequester here:

`TrackRequesting: AngleSharp.Network.Default.Request
TrackRequested: https://serverspace.ae/
TrackParsing: https://serverspace.ae/
TrackRequesting: AngleSharp.Network.Default.Request
TrackRequesting: AngleSharp.Network.Default.Request
TrackRequesting: AngleSharp.Network.Default.Request
TrackRequesting: AngleSharp.Network.Default.Request
TrackRequesting: AngleSharp.Network.Default.Request
TrackRequested: https://serverspace.ae/style/normalize?v=5DJlcjsVTbCXxSrQHJVjokvP8JlOPvgpEExKvfVaPck1
TrackParsing: https://serverspace.ae/style/normalize?v=5DJlcjsVTbCXxSrQHJVjokvP8JlOPvgpEExKvfVaPck1
TrackRequested: https://serverspace.ae/style/font-awesome?v=QqiES8bMVFD1YGmU_C7h6nsgr358Xu-gbi4VJ0NwJNs1
TrackParsing: https://serverspace.ae/style/font-awesome?v=QqiES8bMVFD1YGmU_C7h6nsgr358Xu-gbi4VJ0NwJNs1
TrackRequested: https://serverspace.ae/style/flags?v=D5M4zHZPBYrDeBt6JUMyyYFnMaNIz31n58YHNvytXVA1
TrackParsing: https://serverspace.ae/style/flags?v=D5M4zHZPBYrDeBt6JUMyyYFnMaNIz31n58YHNvytXVA1
TrackParsed: https://serverspace.ae/style/normalize?v=5DJlcjsVTbCXxSrQHJVjokvP8JlOPvgpEExKvfVaPck1
TrackParsed: https://serverspace.ae/style/font-awesome?v=QqiES8bMVFD1YGmU_C7h6nsgr358Xu-gbi4VJ0NwJNs1
TrackParsed: https://serverspace.ae/style/flags?v=D5M4zHZPBYrDeBt6JUMyyYFnMaNIz31n58YHNvytXVA1
TrackRequested: https://fonts.googleapis.com/css?family=Montserrat:400,700
TrackParsing: https://fonts.googleapis.com/css?family=Montserrat:400,700
TrackParsed: https://fonts.googleapis.com/css?family=Montserrat:400,700
`
