### ISSUE TITLE
Loading background-image from CSS

### ISSUE THREAD

**Issue by merthsoft** [AngleSharp/AngleSharp#188]
Sorry for all these questions, but I've got another one! The document I'm loading has a stylesheet with a rule that has `background: url(blah)`. Does this image get automatically loaded in? I checked document.Images, but it's not in there.

**Comment by FlorianRappl** [comment]
Nope, currently no resources from CSS are loaded. At the moment this is intentional, however, in the long run AngleSharp will also load such resources (if not turned off).

**Comment by merthsoft** [comment]
Is there an easy way to go about loading this from the rule-level? I can parse out the URL and load it myself if not.

**Comment by FlorianRappl** [comment]
Unfortunately not. In previous versions the CSSOM was a little bit more exposed, which would give you (after some type casting battle) access to the value instances, e.g., `Url`. But I am looking for ways to make AngleSharp a pleasure to work with - even with the static typed C#.

**Comment by FlorianRappl** [comment]
Continued in AngleSharp.Css!
