### ISSUE TITLE
Virtual file system

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#189]
The internal tasks (loading resources, potentially processing these resources, ...) need to be more transparent. Ideally, we require a system that makes it easy to look at the whole "package" (website + potential resources) in a tree-like structure.

Essentially, this allows awaiting particular tasks or group of tasks. Each downloaded resource will be represented as a "virtual" file with the HTTP request and response being available.

This will replace the current `Requests` property and will be exposed by `IBrowsingContext` in relation to the current document.

**Comment by manne** [comment]
Hi @FlorianRappl,
do you  have any specific requirements?

**Comment by FlorianRappl** [comment]
Nope, no specific ones yet. From my thoughts I would create something like a `VirtualFile` class potentially containing the request / response objects (but probably not the original ones). Instances of this class are aggregated in a `VirtualFileSystem` class, that - among others - has the ability to output a list of "files", list of "directories" (domain / path / ...), and the status of (potentially still running) requests.

The `VirtualFileSystem` should be the primary one to talk to for internal requests, but I don't know if that is already required for this proposal.

I am not yet sure if every window or every document should have one instance. I tend to favor using the `Document`.

Any thoughts here?

**Comment by manne** [comment]
is the `VirtualFileSystem` responsible for holding the "files" or also responsible to process these?

**Comment by FlorianRappl** [comment]
Only holding. Processing has to be done by the various requesters / their aggregates (which is, e..g, the concrete `IResourceLoader` implementation for standard resources).
