### ISSUE TITLE
Best way to get ICssStyleDeclaration from IElement

### ISSUE THREAD

**Issue by j055** [AngleSharp/AngleSharp#193]
Hi

How can I get the ICssStyleDeclaration from an IElement? It looks like the only way is to use the CssStyleEngine and ParseInline method.

I see that the HtmlElement class has a Style property but the class is internal.

Can you help point me in the right direction?

A minor thing with `AngleSharp.Css.Values.Length.TryParse`, can a string "0" return true with Unit.None?

Thanks

**Comment by FlorianRappl** [comment]
There is the `IHtmlElement` interface, which exposes the `Style` property. The string "0" is (from the perspective of AngleSharp) not a valid length, as it does not contain any unit. It is a number. Internally, most CSS declarations that accept length units will also accept the number "0".

Probably, I could simplify things in two areas here:
- Every `IElement` exposes `Style`, even though only special subclasses implement it (all others will return `null`).
- "0" is also a valid exception for units. It will probably be treated like "0px" (denoting an absolute unit of measure).

Hope this helps you!
As far as the improvements are concerned, they'll make it into v0.9.5.

**Comment by j055** [comment]
Just to clarify, when would one have access to '''IHtmlElement'''?

If I parse `margin-top: 0px;` with the `CssStyleEngine` The `ICssStyleDeclaration.MarginTop` property will return "0". This is why I felt things were a little inconsistent.

Your suggestions sound fine to me.

**Comment by FlorianRappl** [comment]
Well, this is as inconsistent as browsers do it. I tried to mimic their behavior as close (and reasonable) as possible. But this is yet another reason to also allow parsing "0" as length - yes.

You always have access to `IHtmlElement`. Its a public interface, like most (I guess all?) DOM interfaces. Just try casting.

**Comment by j055** [comment]
I see but `Style` is null in this example:

```
var parser = new HtmlParser();
var document = parser.Parse("<p style=\"margin-top: 0px;\">Hello</p>");
var querySelector = (IHtmlElement)document.QuerySelector("p");
```

**Comment by FlorianRappl** [comment]
Of course it is. You did not activate CSS. Please provide a configuration that enabled CSS.

**Comment by j055** [comment]
Oops! Got it! Thanks for your patience.

**Comment by FlorianRappl** [comment]
No worries. Little things like these hint that the API is not perfect yet. Noticed and I'll still try to improve it before reaching v1.
