### ISSUE TITLE
HttpRequester reentry

### ISSUE THREAD

**Issue by zedr0n** [AngleSharp/AngleSharp#194]
When running several OpenAsync in parallel on different threads _propCache as a static variable seems to be populated several times. In SetProperty

```
        void SetProperty(String name, Object value)
        {
            if (!_propCache.ContainsKey(name))
            {
                _propCache.Add(name, _http.GetType().GetTypeInfo().GetDeclaredProperty(name));
            }
```

somehow the ContainsKey can be executed before the value is added on a different thread resulting in a null reference exception. 

For some reason though

```
        void SetProperty(String name, Object value)
        {
            if (!_propCache.ContainsKey(name))
            {
                var prop = _http.GetType().GetTypeInfo().GetDeclaredProperty(name);
                if(!_propCache.ContainsKey(name))
                    _propCache.Add(name,prop);
```

seems to work fine.

Any ideas if HttpRequester can be made thread-safe?

**Comment by FlorianRappl** [comment]
I think it could and should. I will investigate / improve the situation together with the next release.

In the meantime you could wrap the existing `HttpRequester` in another `IRequester`, which creates the task in a synchronized block.

**Comment by zedr0n** [comment]
As a quick fix the fields can be just made ThreadStatic

```
    [ThreadStatic] private static Dictionary<String, PropertyInfo> _propCache;
    public static Dictionary<String, PropertyInfo> PropCache => _propCache ?? (_propCache = new Dictionary<string, PropertyInfo>());

    [ThreadStatic] private static List<String> _restricted;
    public static List<String> Restricted => _restricted ?? (_restricted = new List<string>());
```

**Comment by FlorianRappl** [comment]
Yes, but this would defeat the main purpose of having a bag of already known reflection information. Redoing it for every thread is definitely not desired. Also the dictionary is supposed to be read a lot more often than written (ideally, it will only be written "once").
