### ISSUE TITLE
CSS comments break CssParser

### ISSUE THREAD

**Issue by GieltjE** [AngleSharp/AngleSharp#197]
Simple comments will break the CssParser, removing them fixes the problem.

```
/*!
 *  Font Awesome 4.2.0 by @davegandy - http://fontawesome.io - @fontawesome
 *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
 */@import url(https://fonts.googlea
```

**Comment by FlorianRappl** [comment]
If that's your test CSS then this is wrong - I don't see a legal comment there (where is the `/*`?).

Otherwise, please post the full CSS and also elaborate on why the parser is broken (does it crash? what behavior is shown and what should be the behavior?).

**Comment by GieltjE** [comment]
Sorry, it got cut off by the github markup, i have fixed that.

**Comment by FlorianRappl** [comment]
Question remains: How does it _break_ the parser?

**Comment by GieltjE** [comment]
```
                        CssParser parser = new CssParser();
                        ICssStyleSheet test = parser.ParseStylesheet(css);
```

Returns no rules, it's worth noticing that in this case the entire css is minifed directly after the */

**Comment by FlorianRappl** [comment]
Please post a MWE. The snippet that I see should result in no rules. I assume that the real snippet and is larger and that rules should be there, but with the given snippet I see no bug.
Also which version of AngleSharp are you using?

**Comment by GieltjE** [comment]
http://marcomathieu.nl/themes/marcomathieu/css/bootstrap.css
Anglesharp: 0.9.3

**Comment by FlorianRappl** [comment]
This is no [MWE](https://stackoverflow.com/help/mcve) (also see [Wikipedia](https://en.wikipedia.org/wiki/Minimal_Working_Example)), but I'll try to boil it down anyway. Thanks!

**Comment by GieltjE** [comment]
Suddenly started working again, nvm.
