### ISSUE TITLE
Javascript Rendering

### ISSUE THREAD

**Issue by LeMoussel** [AngleSharp/AngleSharp#198]
Many web pages on the internet today use javascript to create the final page rendering.
[HTML Agility Pack](https://htmlagilitypack.codeplex.com/) do not render the javascript but instead just process the raw html sent back by the server.
Is it possible with AngleSharp to render javascript before processing?

**Comment by FlorianRappl** [comment]
I think you mean "JavaScript processing". I refer you to AngleSharp.Scripting. See https://github.com/AngleSharp/AngleSharp.Scripting.

**Comment by LeMoussel** [comment]
I have some websites that render links with JavaScript. 
I understand AngleSharp has a Javascript rendering engine based on Jint. Thus AngleSharp can render links with JavaScript code.

Ref : [Connecting JavaScript evaluation](https://github.com/AngleSharp/AngleSharp/wiki/Examples#connecting-javascript-evaluation)

is it correct?

**Comment by FlorianRappl** [comment]
Yes, this is correct. But you have to keep in mind that the AngleSharp.Scripting project is still very young and may not work for your problem. In the future I plan to spend more time on that project (truly giving it all the capabilities / possibilities you'll have in any evergreen browser), but for now there's a chance that your JavaScript code may not work.

I would just give it a try and see what the currently released version is capable of. Potentially, one of the next versions (of the AngleSharp.Scripting library) will be already able to handle the situation much better.

**Comment by LeMoussel** [comment]
OK. I test it.
To do it, In my Project, I must have references to AngleSharp & AngleSharp.Scripting.

**Comment by FlorianRappl** [comment]
Just get them via NuGet.

**Comment by LeMoussel** [comment]
OK. En avant toute !
