### ISSUE TITLE
Other mime types support - Images

### ISSUE THREAD

**Issue by zedr0n** [AngleSharp/AngleSharp#200]
I'm trying to incorporate image loading as well as html parsing and I seem to see that support for this is planned from the code at some future point as the Response object underlying the async request can contain whichever stream

```
    static async Task<IDocument> LoadDocumentAsync(this IBrowsingContext context, IResponse response, MimeType contentType, TextSource source, CancellationToken cancel)
    {
        if (contentType.Represents(MimeTypes.Xml) || contentType.Represents(MimeTypes.ApplicationXml))
            return await XmlDocument.LoadAsync(context, response, contentType, source, cancel).ConfigureAwait(false);
        else if (contentType.Represents(MimeTypes.Svg))
            return await SvgDocument.LoadAsync(context, response, contentType, source, cancel).ConfigureAwait(false);

        return await HtmlDocument.LoadAsync(context, response, contentType, source, cancel).ConfigureAwait(false);
    }
```

At the moment the stream is encapsulated in the TextSource built from response but I could imagine having an ImageSource which would just wrap the image contents.

OpenAsync also already supports non-html types although the resulting Idocument becomes inconsistent but the actual content loading is already working as ContentType reports correct image type.

Now I see several ways to expose the stream:
1) Create IAbstractDocument interface which would just hold the contents and then add ImageDocument support which will create ImageDocument with Stream property to allow conversion to Image for display in XAML
2) Directly load the image indepently using IHtmlImage Source but the problem here is that some images can be behind the cookie wall requiring login via HTMLDocument handling of the login page so it becomes quite messy
3) Hack the Idocument to always hold the Stream and ignore the inconsistency

Have you given thought to this? Am I missing something here? 

Is this supposed to be handled via Resources instead? I can see the GetImage() method of IHtmlImageElement which returns IImageInfo via LoadResource, do you think the best way is to extend this to also be able to return IImageContent which wraps the actual response data?

**Comment by FlorianRappl** [comment]
> Is this supposed to be handled via Resources instead? I can see the GetImage() method of IHtmlImageElement which returns IImageInfo via LoadResource, do you think the best way is to extend this to also be able to return IImageContent which wraps the actual response data?

Yes, this is exactly how I thought about it. The `IImageInfo` only exposes the information required for the DOM, while your concrete implementation would also have an underlying stream to the (decoded) image data.

The loading of images should be (or will be) done automatically if you allow external resources to be loaded from the document. All requests contain the appropriate cookies (and possibly other relevant information for the request). Internally, the `IRequester` interface is used (via the `IResourceLoader` interface).

I guess you can also load the image manually. You only have to have a reference to the document. If I am not completely mistaken the `Loader` field should contain a reference to the `IResourceLoader` instance (if resource loading is allowed). This would allow you to make arbitrary requests (and thus get the response).

I will try to make this more elegant / efficient in the future. Possibly, in the currently online version (v0.9.3) `Loader` is not exposed. But this will change and, e.g., XHR will be possible with, e.g., AngleSharp.Scripting.JavaScript, as well.

**Comment by zedr0n** [comment]
I see, it makes sense, thanks. While I agree that automatic loading would be useful in most cases but that would mean that each document request would trigger multiple request to all underlying resources causing more downloads than might be necessary. Or are you planning on async lazy resource lading?

**Comment by FlorianRappl** [comment]
There are multiple ways to prevent this. One is to introduce your own `IRequester` implementation, which does not perform all requested downloads. The most simple one, however, is to provide a filter to the (default) `ResourceLoader` instance, which would only allow certain requests.

There are no plans for an "async lazy resource loading". Reasoning is simple: If you don't need it, don't load it. If you might need it - load it (loading may take some time, hence you want to start as early as possible).

**Comment by FlorianRappl** [comment]
(I closed it for now as I think no new enhancement / feature request will originate from here. Otherwise, please start a new one with a specific feature request.)

Last remark: Yes, I know that allowing resource loading by default (w/o requiring the user to take actions) would result in MANY unnecessary requests. That is the reason why resource loading is disabled by default and needs to be enabled explicitly.
