### ISSUE TITLE
Cannot use AngleSharp together with Fiddler

### ISSUE THREAD

**Issue by YehudahA** [AngleSharp/AngleSharp#201]
AngleSharp fills fiddler with spam requests to localhost.

This is my code:
[AsyncContext is a part of AsyncEx library]

``` csharp
    class Program
    {
        static void Main(string[] args)
        {
            var reader = new WebReader();
            AsyncContext.Run(reader.ReadDotNetBlog);

            Console.ReadKey();
        }
    }

    public sealed class WebReader
    {
        public async Task ReadDotNetBlog()
        {
            var config = Configuration.Default.WithDefaultLoader()
                .WithCss();

            var context = BrowsingContext.New(config);
            var dom = await context.OpenAsync("http://blogs.msdn.com/b/dotnet/");
            var imageUrls = dom
                .QuerySelectorAll("img")
                .Select(n => n.Attributes["src"].Value)
                .Distinct();
            foreach (var url in imageUrls)
            {
                Console.WriteLine(url);
            }
        }
    }


```

**Comment by FlorianRappl** [comment]
Please elaborate what you mean with _spam requests to localhost_.

What requests are created which presumably shouldn't exist?

**Comment by YehudahA** [comment]
![fiddler](https://cloud.githubusercontent.com/assets/12732432/11766960/3613066e-a1a5-11e5-9292-8c4a41277411.PNG)

**Comment by FlorianRappl** [comment]
This does not look like its coming from AngleSharp at all. Why that body, why all those headers? Especially, the user-agent does not indicate that AngleSharp is the originator. The default HTTP requester uses a special string that shares nothing with the one present in the screenshot above.

**Comment by YehudahA** [comment]
I don't know what to tell you.
Fiddler is quiet, until I'm running the project, and then begins the heavy bombardment...

The requests process is "scriptedsendbox64:9620".

**Comment by FlorianRappl** [comment]
Are you running from within Visual Studio (attached, i.e., debuggign)? Have you tried to directly invoke the application (e.g., from command line? or ctrl-F5?).

I can only tell you that I don't believe AngleSharp is starting requests to some localhost URL. At least I didn't write such a code. Right now my guess is that your VS is talking home.

Have you ever looked at: https://github.com/aspnet/Mvc/issues/3655
The URLs look quite similar ... There is also a link to a SO topic that seems to have an appropriate answer.

**Comment by YehudahA** [comment]
@FlorianRappl, yes. the problem occurs only when I run the project from VS.
I will read the link you brought.

**Comment by FlorianRappl** [comment]
Alright, so I'll close the issue for now then.
