### ISSUE TITLE
How to get the status code of the response?

### ISSUE THREAD

**Issue by LeMoussel** [AngleSharp/AngleSharp#206]
I do this but I have not found on how to get the status code of the response.
How to get the status code of the response?

``` C#
       public sealed class WebReader
        {
            private IDocument _ashDocument;

            public async Task Load(string Url)
            {
                IConfiguration config = Configuration.Default.WithDefaultLoader().WithJavaScript().WithCss();
                _ashDocument = await BrowsingContext.New(config).OpenAsync(Url);
                await Task.WhenAll(_ashDocument.Requests);
            }

            public IHtmlCollection<IElement> Images { get { return _ashDocument.QuerySelectorAll("img"); } }             

            public IHtmlCollection<IElement> Links { get { return _ashDocument.Links; } } 
        }

        static void Main(string[] args)
        {
            WebReader wReader = new WebReader();  

            // HTTP Status code: 200
            wReader.Load("http://blogs.msdn.com/b/dotnet/").Wait();

            // HTTP Status code: 404
            wReader.Load("http://httpbin.org/status/404").Wait();

             Console.ReadKey();
        }
```

**Comment by FlorianRappl** [comment]
At the moment (without introducing your own requester) no chance. That is why #189 exists. With that you will have capabilities like in evergreen browsers, where you can look at loaded resources with their request headers, response headers (incl. the status-code), and response.

**Comment by LeMoussel** [comment]
Can I make my own requester like [MockRequester](https://github.com/AngleSharp/AngleSharp/blob/9b066100515dc7138a44c8ca6e81a8d109f923dd/AngleSharp.Core.Tests/Mocks/MockRequester.cs#L11)?

**Comment by FlorianRappl** [comment]
Sure. The easiest way is to implement IRequester and then to supply this instance in the configuration (`WithDefaultRequester` allows you to supply your own requester(s)).

**Comment by vickyRathee** [comment]
I was looking for the same and found this thread is closed, was this implemented in 0.9.4? any example?

**Comment by bugproof** [comment]
Any example how to do this? I currently just use external http client directly and just use AngleSharp to parse the html if status code == 200

**Comment by StephenGilboy** [comment]
@bugproof  and for anyone else wondering you can get the status on the document. 

```
var document = await context.OpenAsync(url);
if (document.StatusCode == HttpStatusCode.NotFound)
{
   ...
}
```
