### ISSUE TITLE
Locations of CSS/HTML elements in original source code

### ISSUE THREAD

**Issue by n-l-vasilyev** [AngleSharp/AngleSharp#209]
Hi!

I've been looking for HTML/CSS parser(s) that would allow to analyze the the structure of a HTML/CSS, find certain HTML elements and CSS properties/rules and report **exact positions in the original HTML/CSS source code**. 

Is there a way to do it with AngleSharp? I've noticed there's a class called TextPosition, that is used in AngleSharp.Css.CssNode for Start/End properties, but it's unclear to me if this information could be accessed while working with CssStyleSheet object model.

_HtmlAgilityPack provides what I need for HTML sources, but none of the .NET CSS parsers I've checked (including ExCSS) keeps any references to the original source code, except for validation errors._

**Comment by FlorianRappl** [comment]
The information would be only bound to the tokens, and would not be available on the actual nodes. There are many reasons for that. Since (at the moment) there is no way to get the tokens (in any way) I dropped support for the exact location in HTML. Potentially, I will add this ability in the future.

As far as the CSSOM is concerned you'll need to look at the `ParseTree` (look at older discussions here in the issues). But be aware that `ParseTree` will be replaced in the next version already.

**Comment by n-l-vasilyev** [comment]
Thanks! Now I see what was actually missing in my previous experiments: I've seen that `ParseTree` was null in `CssStyleSheet`, but have forgotten to set `IsStoringTrivia` configuration option for the parser.

The following snippet now works as desired:

``` C#
var cssText = @".someClass { 
-o-border-radius: 5px;
-webkit-border-radius: 5px;
/*border-radius: 5px;*/
display: -webkit-box;
display: -webkit-flex;
display: -ms-flexbox;
display: flex;
background: -webkit-linear-gradient(red, green);
background: linear-gradient(red, green);
}";

var parser = new CssParser(new CssParserOptions
{
    IsStoringTrivia = true
});
var styleSheet = parser.ParseStylesheet(cssText);
var styleRule = styleSheet.Rules[0] as ICssStyleRule;
var node = styleSheet.ParseTree.GetAssociatedNode(styleRule);

Console.WriteLine("Original code:");
Console.WriteLine(node.GetSource());
Console.WriteLine();
Console.WriteLine("Start: {0}, End: {1}", node.Start, node.End);
Console.WriteLine();
Console.WriteLine("Generated code:");
Console.WriteLine(styleRule.ToCss());
```

**Comment by n-l-vasilyev** [comment]
About HTML: thanks, understood. I could you use HtmlAgilityPack for now, as it provides original source position information for the HTML elements. Besides, it does support XPath queries.

**Comment by n-l-vasilyev** [comment]
Could you please give a bit more details about replacing `ParseTree` in the next version already? Will this feature be completely gone or extended or ...?

**Comment by FlorianRappl** [comment]
The idea is to have a CSSOM that has all parts of the one specified by the W3C, but with more information and a better OM exposure, i.e., a CSSOM that could be thought of as a superset of the W3C CSSOM. This OM would then directly contain the information from the `ParseTree`, such that there are no two separate trees / sources of information.

**Comment by n-l-vasilyev** [comment]
Thanks Florian! So the source code information will be preserved, but the API is going to change and shall become easier to use. Sounds good.

**Comment by FlorianRappl** [comment]
Yes, this is the basic idea. Hope that it turns out as well as I hope it does.
