### ISSUE TITLE
How do i dictate the Encoding in 0.9.3? 

### ISSUE THREAD

**Issue by taori** [AngleSharp/AngleSharp#216]
I've seen #42 and #84 on this and tried out a couple of your comments (since you suggested it for another version) and cloned the repository to find it in tests. Unfortunately i was unable to find a sample for it and "Suggest" isn't being called.

```
var configuration = new Configuration(GetParserServices(), null, null);

var p = new HtmlParser(configuration);
var document = p.Parse(content);

private static IEnumerable<IService> GetParserServices()
{
    yield return new EncodingService();
}
private class EncodingService : IEncodingService
{
    public Encoding Suggest(string locale)
    {
        return Encoding.UTF8;
    }
}
```

Amazing project btw. Very impressed by all the effort you've put into this, laying it out with such a beautiful architecture.

**Comment by FlorianRappl** [comment]
Hi, first of all thanks for all the nice words. Much appreciated! Second, can you give me some hint what `content` is in your example? If its already a `string`, then `Suggest` won't be called at all (encoding will be ignored). The encoding is only used for a `Stream`.

**Comment by taori** [comment]
content is a string indeed and in hindsight after posting this question it made a whole lot of sense. Oddly enough it works just fine in unit tests when i pass those strings, but once the string is the value from a textbox i'm getting that exception.
![anglesharpparseargumentexception](https://cloud.githubusercontent.com/assets/5545184/11999711/18fb5b2a-aac5-11e5-93e0-a30b9f0044bf.PNG)

**Comment by taori** [comment]
![image](https://cloud.githubusercontent.com/assets/5545184/11999809/5bdc8b74-aac7-11e5-8e00-28e13b444573.png)

Callstack is probably useful in case it's a bug

**Comment by FlorianRappl** [comment]
I don't think its a bug. Even when the encoding is fixed (or won't be changed) the information from the `meta` tag w. `charsert` (if available) is transported to the corresponding `TextSource` (responsible for reading from the content). Hence the encoding needs to be resolved. 

Unfortunately, the .NET system does not provide a method to check if an encoding exists. Different platforms come with different encodings and there may be a missing / or just wrong encoding to be resolved. Therefore, the only way is to call `GetEncoding` and check if there is an exception. This potential exception is handled in a try-catch block.

I can therefore only assume that your debugging session breaks on every exception, i.e., the exception you are seeing won't be triggered w/o VS being attached. *

I would prefer to use another way to check if a given encoding exists, but I don't know any other reliable method that works on all platforms / within the PCL AngleSharp is using. Maybe you know some solution.

See:
https://github.com/AngleSharp/AngleSharp/blob/master/AngleSharp/TextEncoding.cs#L528

*) This explains the behavior you describe with "odd" where the unit tests pass, but you see the exception during "runtime" (runtime = running the app with VS attached).

**Comment by taori** [comment]
Yeah, you're right. The exception is caught properly. I had "Just my code" disabled. Too bad they don't provide Encoding.GetEncodings in the PCL :/ 

Thanks for your help. Have a nice christmas.

**Comment by FlorianRappl** [comment]
Sure, no problem! Glad we figured it out, though. Merry Christmas and a relaxing holiday to you and your family, too!
