### ISSUE TITLE
Some code example for CssParseErrorEvent

### ISSUE THREAD

**Issue by n-l-vasilyev** [AngleSharp/AngleSharp#227]
I need to get a list of parsing errors for a CSS stylesheet. I see there is `CssParseErrorEvent` class, but was unable to find corresponding sample code in the unit tests or in the documentation. Is there any relevant example (CSS/HTML parsing errors)?

``` c#
            var cssText = @"body {background-image *: url(paper.png);"; // invalid
            var parser = new CssParser();
            var css = parser.ParseStylesheet(cssText);
            // how do we get parsing error(s) here?
```

**Comment by FlorianRappl** [comment]
The best examples can be found in the _AngleSharp.Samples_ repository, namely the sample application. However, as the current pattern (event aggregator) will change soon (see #156), relevant examples would be outdated soon.

Currently, the process is as follows:
- Register an `IEventAggregator` instance (you don't need to create one: there's a simple implementation in form of `SimpleEventAggregator`)
- Subscribe to a desired event, e.g., `CssParseErrorEvent`
- Once the event is published your handler will be called

The reason for changing this pattern is that I don't like the separation between AngleSharp events and DOM events. This separation may sound appealing at first, but it has some disadvantages (such as having the follow the pattern described above, being inconsistent with the other approach, or not being able to attach handlers in, e.g., JavaScript).

**Comment by n-l-vasilyev** [comment]
Thanks Florian!

The following unit test shows a working example of getting CSS parsing errors (_for the current API of AngleSharp_):

``` c#
        [Test]
        public void AngleSharp_PoC_CssErrors()
        {
            var cssText = @"body {background-image *: url(paper.png); }"; // invalid
            var parseErrors = new List<CssParseErrorEvent>();

            var aggregator = new SimpleEventAggregator();
            aggregator.Subscribe(new Subscriber<CssParseErrorEvent>(m => parseErrors.Add(m)));

            var parser = new CssParser(new AngleSharp.Configuration(events: aggregator));
            parser.ParseStylesheet(cssText);

            Assert.IsTrue(parseErrors.Count > 0);
            foreach (var error in parseErrors)
            {
                Console.WriteLine($"{error.Position.ToString()} - {error.Code} - {error.Message}");
            }
        }

        private class Subscriber<T> : ISubscriber<T>
        {
            readonly Action<T> _listener;

            public Subscriber(Action<T> listener)
            {
                _listener = listener;
            }

            public void OnEventData(T data)
            {
                _listener(data);
            }
        }
```

**Comment by FlorianRappl** [comment]
Yes, this is the correct usage.

_Please note that stars are the currency on GitHub. If useful repositories are not starred then further support may be abandoned. After all, why maintain something that seems to be uninteresting?_

**Comment by n-l-vasilyev** [comment]
_Sorry, I'm new to GitHub, didn't know about the stars before :smile:. Starred AngleSharp main repo and Samples repo as well._

**Comment by FlorianRappl** [comment]
Thanks, appreciated! :+1:
