### ISSUE TITLE
CssParserOptions.IsIncludingUnknownDeclarations

### ISSUE THREAD

**Issue by n-l-vasilyev** [AngleSharp/AngleSharp#228]
Is it by design that when `IsIncludingUnknownDeclarations` option is set true all CSS properties become `CssUnknownProperty`? Initially I was expecting that only those which are unknown to AngleSharp will appear in the list as extra entities. However the snippet below shows otherwise.

``` c#
        [Test]
        public void AngleSharp_PoC_UknownProperties()
        {
            Action<bool> print = unknown => 
            {
                var cssText = @"h3 {
                font-weight: normal;
                font-size: 20px;
                color: #666666;
                font-family: Helvetica, Arial, FreeSans, sans-serif;
                margin: 0 0 15px 0;
                -webkit-column-span: all;
                -webkit-border-image: round;
                -webkit-animation-name: movearound;
                -webkit-box-orient: block-axis;
                -moz-box-shadow: none;
                }";

                var parser = new CssParser(new CssParserOptions
                {
                    IsStoringTrivia = true,
                    IsIncludingUnknownDeclarations = unknown
                });
                var styleSheet = parser.ParseStylesheet(cssText);
                var styleRule = styleSheet.Rules[0] as ICssStyleRule;

                foreach (var property in styleRule.Style)
                {
                    Console.WriteLine($"{property.GetType()} - {property.ToCss()}");
                }
            };

            print(true);
            print(false);
        }
```

```
AngleSharp.Dom.Css.CssUnknownProperty - font-weight: normal;
AngleSharp.Dom.Css.CssUnknownProperty - font-size: 20px;
AngleSharp.Dom.Css.CssUnknownProperty - color: #666666;
AngleSharp.Dom.Css.CssUnknownProperty - font-family: Helvetica, Arial, FreeSans, sans-serif;
AngleSharp.Dom.Css.CssUnknownProperty - margin: 0 0 15px 0;
AngleSharp.Dom.Css.CssUnknownProperty - -webkit-column-span: all;
AngleSharp.Dom.Css.CssUnknownProperty - -webkit-border-image: round;
AngleSharp.Dom.Css.CssUnknownProperty - -webkit-animation-name: movearound;
AngleSharp.Dom.Css.CssUnknownProperty - -webkit-box-orient: block-axis;
AngleSharp.Dom.Css.CssUnknownProperty - -moz-box-shadow: none;

AngleSharp.Dom.Css.CssFontWeightProperty - font-weight: normal;
AngleSharp.Dom.Css.CssFontSizeProperty - font-size: 20px;
AngleSharp.Dom.Css.CssColorProperty - color: rgb(102, 102, 102);
AngleSharp.Dom.Css.CssFontFamilyProperty - font-family: Helvetica, Arial, FreeSans, sans-serif;
AngleSharp.Dom.Css.CssMarginTopProperty - margin-top: 0;
AngleSharp.Dom.Css.CssMarginRightProperty - margin-right: 0;
AngleSharp.Dom.Css.CssMarginBottomProperty - margin-bottom: 15px;
AngleSharp.Dom.Css.CssMarginLeftProperty - margin-left: 0;
```

**Comment by FlorianRappl** [comment]
Yes, this is by design. There are multiple reasons for this behavior, but the most important one is that even "known" declarations should then accept all kind of values. The "known" ones only support a certain value string, which may not be the anticipated behavior. You see that in your example with, e.g., `color`. While unknown properties leave the CSS value untouched, the known property is only interested in real CSS colors. It thus looks if the provided value can be transformed to a color.

Remark: The CSSOM will see further changes in the next (~2) upcoming releases. It is very likely that the behavior can be more fine-tuned. Furthermore, the CSSOM will also expose much more methods and properties, making it easier to grasp information and make changes.

**Comment by n-l-vasilyev** [comment]
Thanks Florian!

Actually I've realized that I need "unknown" ("raw") properties in some cases (e.g. to highlight vendor-specific properties or 3-character hex color codes), while for the other types of analysis I need "known" ("converted to OM") properties (e.g. to have shorthand properties expanded). Thus I've decided to use two instances of `CssParser` with different values of `IsIncludingUnknownDeclarations` setting to produce two instances of `ICssStylesheet` from a single CSS source text and then choose the one to look at depending on the task.

**Comment by FlorianRappl** [comment]
Yeah I see. My ultimate goal for the API is to have a representation that gives you both, such that (in your specific case) you don't have to spawn two instances and walk the extra mile. In fact all that information should be readily and most conveniently be available for you.

I'll keep you updated about my progress in that area!
