### ISSUE TITLE
Exception parsing css source with a comment at the start

### ISSUE THREAD

**Issue by rsuk** [AngleSharp/AngleSharp#229]
Fabulous library that is proving invaluable. Parsing some CSS with a comment at the start results in an InvalidOperation Exception (with error text of "Stack empty").

e.g.

```
/* Comment at the start */
body {
    font-size: 10pt;
}
```

**Comment by FlorianRappl** [comment]
Hm sounds strange. Can you give a MWE to reproduce the error? Which version of AngleSharp are you using?

**Comment by rsuk** [comment]
I was trying the latest nuget 0.9.4 version, but have tried a version built from the current development branch too. This would do it:

```
var options = new CssParserOptions();
options.IsStoringTrivia = true;
var parser = new CssParser(options);
var document = parser.ParseStylesheet(@"/* Comment at the start */ body { font-size: 10pt; }");
```

**Comment by FlorianRappl** [comment]
Thanks for the MWE. Yes, problem reproduced, detected and fixed.
