### ISSUE TITLE
Extensible factories

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#233]
AngleSharp uses a lot of factories internally (e.g., to construct DOM elements, CSS declarations, events, ...). The goal is allow custom registration, removal, and adjustment to these factories and (even better) replacing some factories with custom variants.

The problem is that changes to a factory in one configuration should not be taken to the factory in another configuration, however, (re-)creating all factories per configuration is a waste of performance. Therefore, the default factory (if used) will possibly always be present (and read-only). Its keys will then be shadowed by user modifications.

Nevertheless, the former is just an implementation detail - the crucial part is: I'll try to find a way to preserve performance while gaining (a lot) more flexibility.

**Comment by Code-Grump** [comment]
Do you have any example scenarios you would like to support? I'm having a hard time visualizing what the goal here is.

**Comment by FlorianRappl** [comment]
Example: Injecting custom elements, custom CSS declarations, ... - anything that may be useful in the future and is currently "hard-wired" (even though internally some factories are used; but as they are "global" (i.e., `static`) it would be a nightmare to open them in their current state). Also things like custom input types, custom relation types, etc. comes to my mind.

The goal of this is to give other libraries placed on top of AngleSharp more power. One library could then, e.g., integrate new relation types, such as `prefetch`, `preload`, or `import`. Right now, all of this has to be handled within the core library, which is far from ideal (less flexible and modular).
