### ISSUE TITLE
Q: How to download only the main page without external resources

### ISSUE THREAD

**Issue by YehudahA** [AngleSharp/AngleSharp#235]
AngleSharp processes all the link tags and downloads them. I want to avoid it. It's possible?

Thanks!

**Comment by FlorianRappl** [comment]
Do you find AngleSharp useful? Useful repositories should be starred on GitHub, otherwise authors may not maintain them anymore.

Simple answer: AngleSharp does not do more than you configure it to. If you configure it with a resource loader then all resources will be loaded. If you don't configure it with a resource loader then no resources will be loaded. You can fine-grain what resources to load by placing a filter.

**Comment by YehudahA** [comment]
I encountered a very strange problem.
This is my code:

``` cs
using AngleSharp;
using AngleSharp.Io.Network;
using AngleSharp.Network;
using AngleSharp.Network.Default;
using AngleSharp.Services.Default;
using Nito.AsyncEx;
using System.Threading.Tasks;

namespace AngleSharp93Test
{
    class Program
    {
        static void Main(string[] args)
        {
            AsyncContext.Run(WebTask);
        }

        private static async Task WebTask()
        {
            var config = GetHttpClientConfiguration();
            var browser = BrowsingContext.New(config);
            await browser.OpenAsync("http://github.com");
        }

        public static IConfiguration GetHttpClientConfiguration()
        {
            var configuration = Configuration.Default;
            var requesters = new IRequester[] { new HttpClientRequester(), new DataRequester() };
            var service = new LoaderService(requesters);
            return configuration.With(service);
        }
    }
}
```

It's work perfectly, and only the home page is loaded without external resources.
Now, I move the `GetHttpClientConfiguration` to another [static or not] class, and run it again. Now all external resources are loaded! [I monitor it with Fieddler]
I tried it multiple times, and got the same result.

**Comment by FlorianRappl** [comment]
The `LoaderService` from AngleSharp.Io does not prevent resource requests. Therefore, I just assume that this is expected. Either implement the `ILoaderService` again (basically wrapping the one from AngleSharp.Io) or use the default one supplied by AngleSharp (which can be populated with the special requesters from AngleSharp.Io). The one from AngleSharp does allow you to prevent resource requests from happening.

Example:

``` cs
public static IConfiguration GetHttpClientConfiguration()
{
  var configuration = Configuration.Default;
  var requesters = new IRequester[] { new HttpClientRequester(), new DataRequester() };
  return configuration.WithDefaultLoader(requesters: requesters);
}
```

Hope this helps you.

**Comment by YehudahA** [comment]
@FlorianRappl Thank you!

**Comment by YehudahA** [comment]
I finally understood!
There are two different `LoaderService` classes with the same name!

Why is this? why AngleSharp.Io need his own `LoaderService`?
Why `AngleSharp.Io.ConfigurationExtension` uses `AngleSharp.Io.LoaderService` as a default loader?

**Comment by FlorianRappl** [comment]
I'm not sure, but it could be that in a previous version of AngleSharp the default one was `internal`. Another possibility is that the one from AngleSharp.Io may diverge in the future and using a custom one is therefore more future proof. At the moment I tend to believe the first version. As a consequence I will change this soon to remove that ambiguity.
