### ISSUE TITLE
Is CSS object model thread-safe for read-only operations?

### ISSUE THREAD

**Issue by n-l-vasilyev** [AngleSharp/AngleSharp#237]
Basically once an instance of `ICssStyleSheet` is produced from a CSS source text could it be accessed in read-only mode from multiple threads simultaneously? For example, using LINQ queries to find certain CSS rules, properties, selectors. Then using `ParseTree` (AngleSharp 0.9.3) to find corresponding elements in the source text.

Sorry if this topic was already discussed, but I wasn't able to find anything relevant in the previous issues or documentation.

**Comment by FlorianRappl** [comment]
I am not aware that any read operation modifies some internal structure anywhere in AngleSharp. Therefore, yes, of course, for read-only operations you can surely use multiple threads.

Let me know if anything behaves unexpectedly or if you have more questions.

**Comment by n-l-vasilyev** [comment]
Thanks Florian! Will let you know if anything strange is encountered.
