### ISSUE TITLE
How to parse the values I get from ICssStyleDeclaration?

### ISSUE THREAD

**Issue by yariker** [AngleSharp/AngleSharp#240]
Let's say I parse the following piece of HTML code:

```
<a style="background-image: url(http://example.com/image.jpg);"/>
```

I create an instance of `HtmlParser` with `WithCss`, get the `IHtmlAnchorElement` using CSS selector or whatever, and then read the `Style.BackgroundImage` property value, which is a string. And it gives me the following:

```
url("http://example.com/image.jpg")
```

So the question is how to get an `Uri` (or `Url`) object from that string? Do I have to parse it myself?

**Comment by FlorianRappl** [comment]
Well, currently yes (however, internally this is already stored in some pre-parsed format). The CSSOM will expose these internal states in the future, but right now I found no ideal way to circumvent the casting mess that will make the whole process tedious. I'll try to come up with a good strategy in v0.9.6.

Essentially, the steps in this WI involve a _cleanification_ of the current way to validate / process values in the CSSOM. Furthermore, the `IPropertyValue` will most likely change to a "union-like" interface, which gives you access to any possible outcome. If its there, you can access it.

**Comment by yariker** [comment]
I ended up using a regex. Having a universal `IPropertyValue` is probably a good idea. Looking forward for 0.9.6 release. Thanks!

**Comment by FlorianRappl** [comment]
I changed it to v0.9.7 as this is an API improvement (CSSOM), which will be aggregated in v0.9.7.

**Comment by FlorianRappl** [comment]
Continued in AngleSharp.Css!
