### ISSUE TITLE
Set a Style Property unkown to AngleSharp

### ISSUE THREAD

**Issue by jogibear9988** [AngleSharp/AngleSharp#241]
I use AngleSharp for a XAML to HTML converter.

I now set a css Property unkown to AngleSharp like this:

```
 element.Style.SetProperty("grid-row", property.ValueOnInstance.ToString());
```

but the Property is not included in my html output!

(using AngleSharp v0.9.3.15404)

**Comment by jogibear9988** [comment]
Does also not work with 0.94

**Comment by jogibear9988** [comment]
It will work, if I set "IsIncludingUnknownDeclarations = true" but how could I set it when initializeing the Parser like this:

```
var config = AngleSharp.Configuration.Default.WithCss();
var parser = new HtmlParser(config);
```

**Comment by FlorianRappl** [comment]
You can set it if you provide a setup callback, e.g.:

``` cs
var config = AngleSharp.Configuration.Default.WithCss(engine => 
{
  engine.Options.IsIncludingUnknownDeclarations = true
});
var parser = new HtmlParser(config);
```

Hope this helps you!

**Comment by jogibear9988** [comment]
Does not work:

![image](https://cloud.githubusercontent.com/assets/364896/12288490/1b5a19c8-b9d5-11e5-8008-58f583a49a90.png)

**Comment by jogibear9988** [comment]
Maybe the Options should be a class instead of a struct, but like this it works:

```
 var config = AngleSharp.Configuration.Default.WithCss(x => 
        {
            var opt = x.Options;
            opt.IsIncludingUnknownDeclarations = true;
            x.Options = opt;
        });
```

**Comment by jogibear9988** [comment]
Or better:

```
        var config = AngleSharp.Configuration.Default.WithCss(x =>
        {
            x.Options = new CssParserOptions() {IsIncludingUnknownDeclarations = true};
        });
```

but then I maybe don't have the same default values...

**Comment by FlorianRappl** [comment]
They (the options) are a `struct` on purpose. The default value is really just the empty struct, i.e., by default nothing is really set.
