### ISSUE TITLE
Form submission examples

### ISSUE THREAD

**Issue by vickyRathee** [AngleSharp/AngleSharp#242]
I was looking for form submission examples using CSS selectors but couldn't find any?.

For example login form submission or simple html form submission like iMacro(http://wiki.imacros.net/Form_Filling) to automate the web task and web scraping.

Test case #1
Step 1 : Visit a URL
Step 2  : Enter user name & password using css selectors (input.name : username, input.pass : password, input.check : true/false)
Step 3 : Click on Login button
Step 4 : Keep the cookie, session maintained for login state to crawl next 100-200 urls using webrequest after logged in.

Test case #2
Step 1 : Visit google
Step 2  : Enter a keyword on search input
Step 3 : Click on Search button
Step 4 : Return the response content.

Test case #3
Step 1 : Visit a pagging web page
Step 2  : Click on next/previous/ajax load more button using CSS selector
Step 3 : Return the next page response

I'd love to create sample HTMLs to contribute if your resource are busy on other priorities.

**Comment by FlorianRappl** [comment]
Actually, such a contribution would be much welcome. I also realize the lack of documentation is a problem, which is why I'll start working on a large documentation (basically answering all questions - in-depth + quick start + examples for every (known) use-case) soon (probably after v0.9.6, certainly before v1.0).

**Comment by vickyRathee** [comment]
Great, by the time any chance you can help out to write code for one case below.

Test case #1
Step 1 : Visit a URL
Step 2 : Enter user name & password using css selectors (input.name : username, input.pass : password, input.check : true/false)
Step 3 : Click on Login button
Step 4 : Keep the cookie, session maintained for login state to crawl next 100-200 urls using webrequest after logged in.

**Comment by FlorianRappl** [comment]
In know that the demos that are all contained under the umbrella of this orga are a bit scattered. Nevertheless, in the [Developer Week Demo](https://github.com/AngleSharp/AngleSharp.Demos.DeveloperWeek) you'll find something.

The `MainViewModel` contains the following code:

``` cs
await _accessor.NavigateToLink(".log-in");
await _accessor.SubmitForm(new Dictionary<String, String>(StringComparer.OrdinalIgnoreCase)
{
    ["user"] = "User",
    ["password"] = "secret"
});
await _accessor.NavigateToLink(".secret-link");
var secret = _accessor.GetTextOf("#secret");
```

The `_accessor` field points to an abstraction called `WebsiteAccessor`, which is just a wrapper around `IBrowsingContext` (`_context`). The used methods are defined as follows:

``` cs
public async Task NavigateToLink(string selector)
{
    var document = _context.Active;
    var link = document.QuerySelector<IHtmlAnchorElement>(selector);
    await (link?.Navigate() ?? (Task)Task.FromResult(false));
}

public string GetTextOf(string selector)
{
    var document = _context.Active;
    return document.QuerySelector(selector)?.TextContent;
}

public async Task SubmitForm(IDictionary<String, String> fields)
{
    var document = _context.Active;
    var form = document.Forms.FirstOrDefault();
    var elements = form?.Elements ?? Enumerable.Empty<IHtmlElement>();

    foreach (var element in elements.OfType<IHtmlInputElement>())
    {
        var value = default(String);

        if (fields.TryGetValue(element.Name ?? String.Empty, out value))
            element.Value = value;
    }

    await form.Submit();
}
```

The `SubmitForm` helper also exists as an extension in the AngleSharp.Core library.

Hope this helps you!

**Comment by vickyRathee** [comment]
I was trying to implement this but facing null exception. What is UserName/Password here, is it name of input filed or ID or something else?

``` cs
static async void submitForm()
        {
            var config = Configuration.Default.WithDefaultLoader().WithCookies();
            var browsingContext = BrowsingContext.New(config);            
            await browsingContext.OpenAsync("http://client.vnpglobal.com/Client/Default.aspx");            
            Console.Write(browsingContext.Active.Title);
            await browsingContext.Active.QuerySelector<IHtmlFormElement>("form[action='Login.aspx']").Submit(new
            {
                UserName = "***",
                Password = "***"
            });
            await browsingContext.OpenAsync("an internal page");
            Console.Write(browsingContext.Active.Title);
            Console.Read();
        }
```

Can't i simply write code something like.
- Go to url
- Enter username to (selector : input.username)
- Enter password to (selector : input.password)
- Click button (selector input.submit)

Because there are many website where form is submitted on client side AJAX and i can't use this technique. And looking for a way which can enter value or click on text box/check box/radio button/links etc. using CSS Selector firstordefault

**Comment by FlorianRappl** [comment]
Of course, you can write code like this (this is pretty much the code given above).

Instead of `await browsingContext.Active.QuerySelector<IHtmlFormElement>("form[action='Login.aspx']")` you can also use `await browsingContext.Active.Forms[0]` (if you know already the number / order of forms on that page).

Regarding your question: In the example above user / password are the names of the related input fields.

**Comment by vickyRathee** [comment]
Login didn't success, while working in browser.

Looking for more easy solution to implement form submission/login on any website. Something like. 

``` cs
browsingContext.Active(Find.BySelector("input.name"))?.TypeText("username");
browsingContext.Active(Find.BySelector("input.password"))?.TypeText("password");
browsingContext.Active(Find.BySelector("input.remember"))?.Check(true);
browsingContext.Active(Find.BySelector("input.submit"))?.Click();
```

(May be in upcoming versions if not now.)

**Comment by FlorianRappl** [comment]
The proposed way won't work. What is `Find`? You already have `QuerySelector` on the `document` such that you can just use `document.QuerySelector<IHtmlInputElement>("input[type=text][name=foo]").Value = "username"`. You may come up with an extension method for `INode` such as

``` cs
INode SetInputValue(this INode host, String name, String value);
```

Also using the `Click` is really not a good practice. What you really want is to trigger `form.Submit()`. It works in AngleSharp already, however, usually I would expect it only to work in conjunction with a renderer.

**Comment by vickyRathee** [comment]
Yes Find is wrong here(I was just referring, how its done in http://watin.org/ ).

`form.Submit()` won't work on AJAX websites so need something which can type text, check the checkbox, click on button etc using .

Now i came up with below code and it's also not giving me title of internal page (which means not logged in ?)

``` cs
static async void loginForm(){
var config = Configuration.Default.WithDefaultLoader().WithCookies();
var browsingContext = BrowsingContext.New(config);

await browsingContext.OpenAsync("http://client.vnpglobal.com/Login.aspx");

//Console.Write(browsingContext.Active.Title);
browsingContext.Active.QuerySelector<IHtmlInputElement>("#Login1_UserName").Value = "****";
browsingContext.Active.QuerySelector<IHtmlInputElement>("#Login1_Password").Value = "****";
browsingContext.Active.QuerySelector<IHtmlInputElement>("#Login1_LoginButton").DoClick();

await browsingContext.OpenAsync("internal page");

Console.Write(browsingContext.Active.Title);
}
```

**Comment by FlorianRappl** [comment]
Why should `form.Submit()` not work on "AJAX websites"? If that's the case then the author of the website did something very wrong. Instead of hooking on the `submit` event, he hooked on the `click` event. This is terrible (not only from a programming perspective, but also from a UX point of view).

In any case this is not the scenario you should look for. You should look for a general form submission process.

By the way, have you ever checked out the samples? Maybe you should first try to understand them. I don't know what you are doing wrong, but usually the website is not understood well enough to submit forms (e.g., are those really the IDs you are looking for?, are the values set correctly?, are there other fields that need to be filled out?, those the process work w/o JavaScript?, ...).

**Comment by vickyRathee** [comment]
Yes i've seen the examples and Form Ids are also correct, see below HTML. And there is not any other field or javascript need to be filled out.

HTML DOM (`http://client.vnpglobal.com/Login.aspx`)

``` html
<form method="post" action="Login.aspx" onsubmit="javascript:return WebForm_OnSubmit();" id="signup">
    <input name="Login1$UserName" type="text" id="Login1_UserName" placeholder="Username" />
    <input name="Login1$Password" type="password" id="Login1_Password" placeholder="Password" />
    <input type="submit" name="Login1$LoginButton" value="Sign In" onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;Login1$LoginButton&quot;, &quot;&quot;, true, &quot;ctl00$Login1&quot;, &quot;&quot;, false, false))" id="Login1_LoginButton" class="submit" />
</form>
```

My Code

``` cs
static async void loginForm(){
var config = Configuration.Default.WithDefaultLoader().WithCookies();
var browsingContext = BrowsingContext.New(config);

await browsingContext.OpenAsync("http://client.vnpglobal.com/Login.aspx");

//Console.Write(browsingContext.Active.Title);
browsingContext.Active.QuerySelector<IHtmlInputElement>("#Login1_UserName").Value = "****";
browsingContext.Active.QuerySelector<IHtmlInputElement>("#Login1_Password").Value = "****";
browsingContext.Active.QuerySelector<IHtmlInputElement>("#Login1_LoginButton").DoClick();

await browsingContext.OpenAsync("internal page");

Console.Write(browsingContext.Active.Title);
}
```

**Comment by FlorianRappl** [comment]
Do you see the `onclick` field? Have you ever tried submitting the form w/o JavaScript?

BTW: What you posted is the HTML code, not the DOM. The DOM is an object model, i.e., the elements in a tree-like structure with an exposed API.

**Comment by vickyRathee** [comment]
It won't work without JavaScript I guess, how can I enable JavaScript?

**Comment by FlorianRappl** [comment]
There's AngleSharp.Scripting, but its in an early stage and it does not integrate event handlers integrated via attributes (as presented above) at the moment.

**Comment by vickyRathee** [comment]
Yes i changed the config as well to include `WithJavaScript()` but it wasn't working

So since JavaScript is not working, now I'm trying to do with form submit method and it's throwing syntax error.(even i double quote the input field names). Any way i can use CSS selector(Id or Class) here instead of input field name?

```
await browsingContext.Active.Forms[0].Submit(new
{
   Login1$UserName = "***",
   Login1$Password = "***"
});
```

HTML

```
<form method="post" action="Login.aspx" onsubmit="javascript:return WebForm_OnSubmit();" id="signup">
    <input name="Login1$UserName" type="text" id="Login1_UserName" placeholder="Username" />
    <input name="Login1$Password" type="password" id="Login1_Password" placeholder="Password" />
    <input type="submit" name="Login1$LoginButton" value="Sign In" onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;Login1$LoginButton&quot;, &quot;&quot;, true, &quot;ctl00$Login1&quot;, &quot;&quot;, false, false))" id="Login1_LoginButton" class="submit" />
</form>
```

Also, any plan in upcoming version of AngleShap to integrate event handlers via attributes with scripting to allow interaction per my example above ?

**Comment by Enxyphered** [comment]
![image](https://user-images.githubusercontent.com/13829948/32595345-602d5b8a-c551-11e7-82c3-89099c9a3cbd.png)
Help ?

**Comment by FlorianRappl** [comment]
Non-`async` methods cannot be converted to an async state machinery (thus no `await` operator can be used). Just to get you going I would suggest to change

```csharp
await context.openAsync(messengerUrl);
```

to

```csharp
var document = context.openAsync(messengerUrl).Result;
```

Note: This is blocking and therefore not a best practice (instead you should either use a proper async state machinery or a `ContinueWith` construct using a callback).

Next time please post code instead of an image. HTH!

**Comment by isaacrlevin** [comment]
Any update on this? When I perform OnClick() and get context.Active.Url, it stays on the login page
