### ISSUE TITLE
Error parsing bootstrap css

### ISSUE THREAD

**Issue by arbh89** [AngleSharp/AngleSharp#246]
I am getting an error when tring to parse bootstrap css framework.

The string did not match the expected pattern.
at AngleSharp.Extensions.QueryExtensions.QuerySelectorAll(INodeList elements, String selectors)
at AngleSharp.Dom.Document.QuerySelectorAll(String selectors)

The string passed to QuerySelectorAll was @keyframes progress-bar-stripes

Do you have any idea?

**Comment by FlorianRappl** [comment]
I'll look into that. Which version? What options? Can you give a MWE to reproduce the problem?

**Comment by FlorianRappl** [comment]
Tested with Bootstrap 2.3.2, 3.0.1, and 3.3.6. No errors for me.
