### ISSUE TITLE
Selection of direct children of an HTML element

### ISSUE THREAD

**Issue by ghost** [AngleSharp/AngleSharp#247]
It seems that the possibility is missing to find direct childrens of an HTML element. According to http://stackoverflow.com/questions/3687637/how-to-get-only-direct-child-elements-by-jquery-function in jQuery there exist two possibilities to do this. In AngleSharp I would expect that the function QuerySelectorAll(">tr") used on an tbody element would only return the table rows which are the direct childs of this table body but not the ones in a nested table.

**Comment by FlorianRappl** [comment]
No the child selector should work (actually, jQuery has nothing to do with this - this is a standard CSS selector). Can you post a MWE to illustrate your problem?

**Comment by ghost** [comment]
``` csharp
            string source = @"
                <!DOCTYPE html>
                <html>
                <head>
                    <title></title>
                </head>
                <body>
                <table>
                    <tr>
                        <td>data1</td>
                        <td>data2</td>            
                    </tr>
                    <tr>
                        <td>data3</td>
                        <td>
                            <table>
                                <tr>
                                    <td>subdata1</td>
                                    <td>subdata2</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                </body>
                </html>";
            HtmlParser parser = new HtmlParser();
            IHtmlDocument document = parser.Parse(source);

            IElement tableElement = document.QuerySelector("table");
            IHtmlCollection<IElement> tableRows = tableElement.QuerySelectorAll(">tr");
            Console.WriteLine(tableRows.Length);
```

Above is a simple example. I would have expected to see only the two child rows returned, but the tableRows collection contains three elements, including the one within the nested table.

**Comment by FlorianRappl** [comment]
The result is as expected. The selected you provided is converted to `* > tr`, which means all `tr` elements that are (_direct_) childs of any element.

BTW: Before you think there is something wrong with AngleSharp, please first check with _any_ evergreen browser you got installed. Every browser will also return `3` in this case.

If you try the following you'll get the two rows you want:

``` cs
var tableRows = document.QuerySelectorAll("body > table > tbody > tr");
```

Then you will get the expected result. Please note that I explicitly use `body`. If I would just omit this I would get 3:

``` cs
var tableRows = document.QuerySelectorAll("table > tbody > tr");
```

**Comment by ghost** [comment]
For me your suggestion does not work, and that's why I quoted the jQuery solution: in my program I found already a specific element and want to select certain child nodes from it (e.g. the tr elements from above). In CsQuery I could have used element.Children("tr") for this (which is also supported by jQuery), but I cannot find a simple solution using AngleSharp.

**Comment by FlorianRappl** [comment]
Hm, this is strange as AngleSharp makes such things quite simple (imho). If you know LINQ and the DOM its easy.

``` cs
var tableElement = document.QuerySelector("table");
var tableRows = tableElement.Children.Where(m => m.LocalName == "tr");
```

Please note that the example will result in 0 elements as `tr` are elements of `tbody` and not `table`, but this should be sufficient give you the right idea.

**Comment by ghost** [comment]
Thanks, this solves my problem!

**Comment by speige** [comment]
For posterity:
```
document.QuerySelector("tbody").QuerySelectorAll(">tr") // converted to * > tr & starts from document root, essentially the "tbody" portion is ignored. finds all tr in entire document.
document.QuerySelector("tbody").QuerySelectorAll(":scope>tr") // looks for direct descendent tr of tbody
```

This isn't specific to AngleSharp, it's how all browsers work. However, it's unintuitive to need the :scope before >, so others probably made the same mistake.
