### ISSUE TITLE
"Bottom" is missing in Style Properties

### ISSUE THREAD

**Issue by jogibear9988** [AngleSharp/AngleSharp#253]

**Comment by FlorianRappl** [comment]
As its just a little change a PR would be welcome.

**Comment by jogibear9988** [comment]
https://github.com/AngleSharp/AngleSharp/pull/254

**Comment by jogibear9988** [comment]
Would it also be okay if I add the attributes for CSS Grid?

**Comment by FlorianRappl** [comment]
I guess you can do that but please place all PR to `devel`.
