### ISSUE TITLE
WithJavaScript

### ISSUE THREAD

**Issue by useruser1** [AngleSharp/AngleSharp#259]
Could not load type 'AngleSharp.Network.MimeTypes' from assembly 'AngleSharp, Version=0.9.4.42449, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'.

when load ANY url with Configuration.Default.WithCss().WithJavaScript();

**Comment by FlorianRappl** [comment]
Invalid for many reasons, e.g.,
- Belongs to AngleSharp.Scripting
- Is known => you are using incompatible versions
