### ISSUE TITLE
Extra <head></head><body></body> in inner html

### ISSUE THREAD

**Issue by SOHODeveloper** [AngleSharp/AngleSharp#260]
I am sure that I have must be doing something wrong.  I am attempting to replace the inner html of an existing div with new content.

```
IHtmlDocument myDocument = new HtmlParser().Parse(myFileStream);
IElement e = myDocument.GetElementById("id");
e.InnerHtml = newHtml;

```

I look at newHtml in the debugger and it is fine.
I look at e.InnerHtml and it has newHtml with extra &lt;head>&lt;/head>&lt;body>&lt;/body> appended to the end

**Comment by FlorianRappl** [comment]
Can you work out a MWE? Distill the original source and the text represented by `newHtml`. I'll look into it then.

**Comment by SOHODeveloper** [comment]
I have attached a repro.  The webpage and replacement html are files in the project and they copy to the output folder so all you have to do is run the project.

Thanks

[InnerHtmlRepro.zip](https://github.com/AngleSharp/AngleSharp/files/113965/InnerHtmlRepro.zip)

**Comment by FlorianRappl** [comment]
Two things:
1. If you want support / keep AngleSharp alive then star it (its the currency on GitHub; repos then are not starred are abandoned)
2. Next time please try to create a real MWE (as concise as possible) and bring everything together in a single source (please do not upload zip files!)

**Comment by FlorianRappl** [comment]
So this is the MWE for the described scenario:

``` cs
var parser = new HtmlParser();
var document = parser.Parse("<!DOCTYPE html><div id=outputPanel></div>");
var element = document.GetElementById("outputPanel");
element.InnerHtml = "<table></table>";
Console.WriteLine(element.InnerHtml);
```

Yes, looks like a bug to me. I will investigate and fix it asap.

**Comment by SOHODeveloper** [comment]
I wanted you to have my data, just in case it was somehow data specific.
What you reduced this to is indeed the very basic

Thanks

---

Roy Chastain
