### ISSUE TITLE
Multiple classes on query selectors

### ISSUE THREAD

**Issue by 0ffTopic** [AngleSharp/AngleSharp#262]
Hello

I'm trying to find an element that has 3 classes, is it possible to add all classes to a selector?
I'm using this:
var selector = "img.lzyPlcHld";
would it be possible to use
var selector = "img.lzyPlcHld lzyLoaded lzyLnk"

Thanks

**Comment by FlorianRappl** [comment]
Just place a dot in front of each class, e.g.:

``` cs
var selector = "img.a.b.c"; //tag img with class a, class b, and class c
```

**Comment by weedkiller** [comment]
I think this is what I was looking for, can I do this with a Div too?
and will it give inner text or outer?

**Comment by FlorianRappl** [comment]
It will return the elements, e.g.,

```csharp
var elements= document.QuerySelectorAll('div.foo.bar');
Console.WriteLine(elements.Length); // get the number of found elements

foreach (var element in elements)
{
  // Do something with each element, e.g.:
  Console.WriteLine(element.OuterHtml); //Outer serialized DOM
}
```
