### ISSUE TITLE
Is this library unstable?

### ISSUE THREAD

**Issue by 304NotModified** [AngleSharp/AngleSharp#265]
Is this library unstable? If not, please use [semver](http://semver.org/) - it makes it easier for us developers to use this great library! That means - move to 1.0 at least and don't make (binary) breaking changes between non-major versions. 

PS: 0.9.4 had a breaking change. https://github.com/mganss/HtmlSanitizer/issues/53

**Comment by FlorianRappl** [comment]
Please read the Wiki first, especially https://github.com/AngleSharp/AngleSharp/wiki/Contributing! There you'll find that prior to v1 the API is not considered stable.

PS: Nearly any release had a breaking change (as there was no v1 release yet).
