### ISSUE TITLE
Incorrect DOM parsing in AngleSharp 0.9.4

### ISSUE THREAD

**Issue by amitandhale** [AngleSharp/AngleSharp#268]
Hi,
I am using AngleSharp 0.9.4 version with my HtmlSanitizer library. I am facing issuing while parsing below XML. The parsed DOM is incorrectly generated.
The input to HtmlParser.Parse method is
<Audit>
  <AuditLogItem DateCreated="0001-01-01T00:00:00.0000000Z" AttributeName="Last Name" PreviousValue="B" NewValue="A"/>
  <AuditLogItem DateCreated="0001-01-01T00:00:00.0000000Z" AttributeName="First Name" PreviousValue="B1" NewValue="A1"/>
</Audit>

The output after parsing is 
<audit>
  <auditlogitem datecreated="0001-01-01T00:00:00.0000000Z" attributename="Last Name" previousvalue="B" newvalue="A">
  <auditlogitem datecreated="0001-01-01T00:00:00.0000000Z" attributename="First Name" previousvalue="B1" newvalue="A1">
</auditlogitem></auditlogitem></audit>

The ending </auditlogitem> is incorrectly structured. 

Can you please consider this as high priority issue and please let me know the timeline for the fix.

Thanks
Amit

**Comment by amitandhale** [comment]
Input to HtmlParser.Parse method is

`<Audit>
  <AuditLogItem DateCreated="0001-01-01T00:00:00.0000000Z" AttributeName="Last Name" PreviousValue="B" NewValue="A"/>
  <AuditLogItem DateCreated="0001-01-01T00:00:00.0000000Z" AttributeName="First Name" PreviousValue="B1" NewValue="A1"/>
</Audit>`

The output after parsing is 
`<audit>
  <auditlogitem datecreated="0001-01-01T00:00:00.0000000Z" attributename="Last Name" previousvalue="B" newvalue="A">
  <auditlogitem datecreated="0001-01-01T00:00:00.0000000Z" attributename="First Name" previousvalue="B1" newvalue="A1">
</auditlogitem></auditlogitem></audit>`

The closing </auditlogitem> is incorrectly structured and also all tags and attributes are in lower case.

**Comment by FlorianRappl** [comment]
No this all seems to be correct. Ever tested with any browser? Attribute names are actually case-insensitive (e.g., see http://stackoverflow.com/questions/4351857/is-html-case-sensitive) as are tags.

Please, before reporting "bugs" make sure you tested with browsers. Statements such as

> The parsed DOM is incorrectly generated

need to be backed up (e.g., be referring to the specification or by comparing with a reference implementation).
