### ISSUE TITLE
Parse custom nodes

### ISSUE THREAD

**Issue by cirpitch** [AngleSharp/AngleSharp#269]
In HTML code I have custom elements `[[some text/]]`
I need get all this variables. How I can do this?

Thank!

**Comment by FlorianRappl** [comment]
I am not sure if I understand the question. I assume you mean

``` html
<some text />
```

hence I guess you want the attribute(s) (e.g., `text`) and the tag name (e.g., `some`). Here, the properties `LocalName` and `Attributes` contain what you want.
