### ISSUE TITLE
DocumentElement.TextContent incorrectly processed style tag

### ISSUE THREAD

**Issue by cnblogs-dudu** [AngleSharp/AngleSharp#272]
Test code:

``` csharp
var html = @"<style><!-- 
    img { 
        border: 0;
    }
    --></style>
    <p>hello</p>";

var parser = new HtmlParser();
var dom = parser.Parse(html);
var text = dom.DocumentElement.TextContent;
Console.WriteLine(text);
```

Output:

``` text
  <!-- 
                img { 
                    border: 0;
                }
                -->
                hello
```

**Comment by FlorianRappl** [comment]
This all seems to be alright. The output in modern browsers is:

``` html
<!-- 
    img { 
        border: 0;
    }
    -->
    hello
```

This seems to be the same. What exactly is your issue? What do you expect? Are you familiar with the HTML specification or have you tried to reproduce your issue in at least one of the evergreen browsers?

**Comment by cnblogs-dudu** [comment]
Expect: 

``` text
hello
```

**Comment by FlorianRappl** [comment]
This is wrong. Please make sure you understand the HTML specification / test with browsers in case of doubt.

Style uses a different mode (rawtext, more about these modes [in the HTML5 mastery series](http://webdesign.tutsplus.com/tutorials/html5-mastery-fragments--cms-24842)) for its content, but its still using a `Text` node to store its content. I understand your confusion, but this is all as specified by the W3C.

However, nothing prevents you in AngleSharp to serialize a document according to your wishes (and thus skipping text from special nodes, e.g., script or style tags).
