### ISSUE TITLE
System.TypeInitializationException at AngleSharp.Parser.Html.HtmlDomBuilder.AddElement

### ISSUE THREAD

**Issue by GieltjE** [AngleSharp/AngleSharp#273]
Some machines break when a document is parsed using Anglesharp 0.9.4:

`Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.MulticastDelegate.CtorOpened(System.Object, IntPtr, IntPtr)
   at AngleSharp.Factories.InputTypeFactory..ctor()
   at AngleSharp.Factory..cctor()

Exception Info: System.TypeInitializationException
   at AngleSharp.Parser.Html.HtmlDomBuilder.AddElement(AngleSharp.Parser.Html.HtmlTagToken, Boolean)
   at AngleSharp.Parser.Html.HtmlDomBuilder.InHead(AngleSharp.Parser.Html.HtmlToken)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Parse(AngleSharp.Parser.Html.HtmlParserOptions)`

Since this only happens on two machines (non dev) this is a bit tricky to debug.
If requested I can send the exact code.

**Comment by FlorianRappl** [comment]
Interesting... `AccessViolationException`. It's hard to believe. Most interestingly, it does not seem to be that easy to reproduce (making it quite random, right?).

But since the origin is somewhere in `InputTypeFactory` I assume that one of the `InputType` classes is closely related to this exception. I'll look over it (but I can't promise to solve it due to the induced randomness).

**Comment by GieltjE** [comment]
No it's not random but it is limited to certain machine's (the same document parses just fine on all others). For now it's only on windows 8.1 x64.

**Comment by FlorianRappl** [comment]
If its not random then please provide the code to reproduce (A couple of machines seems to be random. Why these machines? If you know what distinguishes a working machine from one where the error occurs, then its reproducible).

**Comment by jogibear9988** [comment]
do you try running from network share? are the dlls marked as "downloaded from the internet"?

**Comment by GieltjE** [comment]
It is not running from a network share (our program doesn't support it), and the dll's are not marked as "downloaded from the internet", I will try to make an example code lateron.

**Comment by GieltjE** [comment]
Must have been a compiler error, no matter how hard I try to reproduce it it seems to have gone. Lets hope it stays that way. Thanks for your support!

**Comment by FlorianRappl** [comment]
Yes, potentially. Thanks for your efforts!
