### ISSUE TITLE
Build server compilation error using 4.6.1 profile.

### ISSUE THREAD

**Issue by jfrank14** [AngleSharp/AngleSharp#275]
Using the current (0.9.4.42449) version of AngleSharp (AS), everything works perfectly on my local machine.

But on our build server, I'm getting the following error on every line that uses code from AS:

```
Reference required to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' containing the type '[Object]'. Add one to your project.
```

My solution is using .NET Framework 4.6.1 and I think this must have something to do with AS dependencies not matching up with what's installed on the build server, but this message isn't very helpful. It looks to me like AS may have a dependency on .NET 4.0, and this may not be installed on the build server. But I don't really want to install a whole SDK on the build server just for one component.

Is there a way to get a clean AS legacy build targeted for .NET 4.6.1?

**Comment by FlorianRappl** [comment]
Why are you using the legacy version (dependent on .NET 4) and not the PCL? Any reason for that or can you force your solution to use the PCL?

**Comment by jfrank14** [comment]
I'm not trying to use the legacy version. I installed via NuGet and it pointed my project at `\packages\AngleSharp.0.9.4\lib\net45\AngleSharp.dll`. I see that there is another version of this at `\packages\AngleSharp.0.9.4\lib\portable-windows8+net45+windowsphone8+wpa\AngleSharp.dll` and I'm happy to use that one instead, but I'd like to understand what NuGet was thinking here.

**Comment by jfrank14** [comment]
I just tried pointing my project to the PCL version and I get the same compilation error. Is the PCL _also_ dependent on 4.0?

**Comment by FlorianRappl** [comment]
No, the PCL is profile 259 and does not depend on any particular framework version.

However, .NET 4.5 (included in that subset) may be different to .NET 4.6 (unfortunately). According to [this SO answer](http://stackoverflow.com/questions/32094383/portable-class-library-has-no-datacontract-or-serialization-functions-with-net) an explicit reference may seal the deal (no need to install .NET 4 or something on the server, just add the reference via NuGet or similar).

**Comment by FlorianRappl** [comment]
Just two remarks:
1. With #271 the situation for VS 2015 onwards should be better.
2. The SO answer I referred to uses data contracts, which are not used in AS (at least I can't think of any right now), however, there may be other parts. Therefore I think its worth a try!

**Comment by jfrank14** [comment]
I'm puzzled, though, because DataContracts are a fairly specific library, but my problem is that it doesn't like `Object` from `System.Runtime`, which is as fundamental as it gets. So I don't really see how to apply that SO answer to my situation.

Is there a release timeframe for 0.9.5?

**Comment by jfrank14** [comment]
For now I have worked around this by compiling the source of the Core.Legacy library for 4.6.1. To do this, I had to rename `TaskEx` instances to `Task`, because they have apparently been merged in 4.5+, per this SO topic:

http://stackoverflow.com/questions/16467022/convert-projects-to-net-4-5-that-uses-tpl

This is not great, though, because it means that a NuGet update will break my version. Can the next AS update include a version that works properly on 4.6.1 without dependency on 4.0?

**Comment by FlorianRappl** [comment]
I don't think so. This is not a problem with AS, but unfortunately with NuGet / the PCL system. Again, there is no _direct_ dependency on 4.0. The next AS will have dotnet target, which should alleviate the situation for your case, but generally this has nothing to do with AngleSharp.

Also I wonder why you take the legacy library (this is legacy because it targets 4.0) - why not just target 4.6 from the PCL version? Seems much more straightforward to me.

**Comment by jfrank14** [comment]
Hmm, you're right, that would have made more sense. I avoided the PCL because it had a bunch of build restrictions I didn't understand, and I didn't have a 4.6 "profile" installed. But I'm sure I could have solved this with a little more understanding.
