### ISSUE TITLE
Broken links on the Wiki

### ISSUE THREAD

**Issue by thecodejunkie** [AngleSharp/AngleSharp#276]
The following Wiki page links

![image](https://cloud.githubusercontent.com/assets/50543/13352046/f82a558e-dc8a-11e5-8c27-ee75d1c9dc75.png)

All seems to point to the equivalent pages on @FlorianRappl fork, which all are empty. The links in the sidebar works fine.

I could not edit them myself because community edits are disabled

**Comment by FlorianRappl** [comment]
Thanks, yes updated. I wanted to move away Wiki anyway with a full documentation, but currently this is all being delayed due to my workload.
