### ISSUE TITLE
The lib file is so big

### ISSUE THREAD

**Issue by qaqz111** [AngleSharp/AngleSharp#277]
The dll file is so big that it contains everything AS implemented into a single file, but in fact many works, for example a small tool or a simple crawler bot that just to extract data from html code string, do not need everything of AS implemented.

So I wonder that is there a plan to split AS into some separate libs that each contains only one major function?

**Comment by FlorianRappl** [comment]
Yes, see #139. It was debated, but it seemed that most people do not want this. Let's continue the discussion in #139!
