### ISSUE TITLE
Async method naming

### ISSUE THREAD

**Issue by Code-Grump** [AngleSharp/AngleSharp#279]
There's a bit of inconsistency in the project with its use of asynchronous naming conventions:

Sometimes a method follows the Microsoft naming guidelines, including an -Async suffix (e.g. `OpenAsync`) and other times the suffix is not present (e.g. `IHtmlFormElement.Submit()`).

What is the preferred coding style and should there be a cleanup to make the project conform?

**Comment by FlorianRappl** [comment]
I think its pretty much coherent. Yes, `Submit` should most probably be renamed, however, this has a historic reason as at first methods (of DOM interfaces / classes) have been named exactly (ignore case) as they should have been. Now this is no longer the case (thanks to attributes), we may give methods like `Submit` their proper name.

Can you name more examples where the suffix is missing? Just from the top of my head I would say its fairly consistent.

Two more things to mention here:
1. The suffix only makes sense if its a hot task.
2. It was mostly chosen to not conflict with existing methods that have the same parameters, but do not return a (hot) task (and may be blocking).

So in a world with overload resolution that takes into account the sink we would probably not have seen it.

**Comment by Code-Grump** [comment]
Whether the `Task` is "hot" or not is an implementation detail that should be hidden to the caller. There are many scenarios in asynchronous programming where the call can be asynchronous or synchronous depending on the input parameters or whether values are being cached, so it's best to just treat all `Task` instances equally.

The following methods are implemented to return a `Task` but don't have an `Async` suffix:

**Dom\Css\CssStyleEngine.cs**
  `Line 162:         async Task<CssStyleSheet> Parse(CssParser parser, CssStyleSheet sheet, TextSource source)`

**Dom\Css\Rules\CssImportRule.cs**
  `Line 59:         internal async Task LoadStylesheetFrom(Document document)`

**Dom\Document.cs**
  `Line 1610:         internal void DelayLoad(Task task)`
  `Line 1627:         internal async Task FinishLoading()`

**Dom\Html\HtmlFormElement.cs**
  `Line 174:         public Task<IDocument> Submit()`
  `Line 183:         public Task<IDocument> Submit(IHtmlElement sourceElement)`

**Dom\Html\HtmlFrameElementBase.cs**
  `Line 167:             public async Task Perform(Action<IDocument> callback)`

**Dom\Window.cs**
  `Line 679:         async Task DoTimeout(Action<IWindow> callback, Int32 timeout, CancellationToken token)`
  `Line 689:         async Task DoInterval(Action<IWindow> callback, Int32 timeout, CancellationToken token)`

**Extensions\ApiExtensions.cs**
  `Line 106:         public static async Task<Event> AwaitEvent<TEventTarget>(this TEventTarget node, String eventName)`
  `Line 302:         public static Task<IDocument> Navigate<TElement>(this TElement element)`
  `Line 315:         public static Task<IDocument> Navigate<TElement>(this TElement element, CancellationToken cancel)`
  `Line 335:         public static Task<IDocument> Submit(this IHtmlFormElement form, Object fields)`
  `Line 347:         public static Task<IDocument> Submit(this IHtmlFormElement form, IDictionary<String, String> fields)`

**Extensions\DocumentExtensions.cs**
  `Line 286:         public static async Task WaitForReady(this Document document)`

**Extensions\ElementExtensions.cs**
  `Line 811:         public static Task<Boolean> ProcessResource<TResource>(this Element element, IDownload download, Action<TResource> callback)`
  `Line 842:         public static async Task<Boolean> ProcessResponse(this Element element, IDownload download, Action<IResponse> callback)`
  `Line 921:         public static async Task<IDocument> NavigateTo(this Element element, DocumentRequest request)`

**Extensions\PortableExtensions.cs**
  `Line 33:         public static Task Delay(this CancellationToken token, Int32 timeout)`

**Interfaces\Html\IHtmlFormElement.cs**
  `Line 84:         Task<IDocument> Submit();`
  `Line 90:         Task<IDocument> Submit(IHtmlElement sourceElement);`

**Parser\Html\HtmlDomBuilder.cs**
  `Line 3439:         async Task RunScript(HtmlScriptElement script)`

**TextSource.cs**
  `Line 276:         public Task Prefetch(Int32 length, CancellationToken cancellationToken)`
  `Line 286:         public async Task PrefetchAll(CancellationToken cancellationToken)`

I didn't scrutinize the test suites.

**Comment by FlorianRappl** [comment]
> Whether the Task is "hot" or not is an implementation detail that should be hidden to the caller.

Actually, no. This is crucial, as a hot task is not started and still needs to be triggered. You don't call `Start` on tasks returned from `Async` methods, right? Actually, this is where this convention really shines. But I think it does not matter for the discussion.

Most things from the list above are actually internal and pretty clear from the context (there is also no synchronous counter-part).

I would not put to much weight on this. After all, this is cosmetics and there are much more important issues on the list.

**Comment by Code-Grump** [comment]
Sorry, I didn't appreciate there were places where `Task.Start` was being invoked. I don't believe there's any reason to use `Task.Start`. I would strongly advocate refactoring to remove this pattern.

From a calling perspective, I expect any Task given to me to be something encapsulating a piece of work which was set up by the method call. Either the task is scheduled, is already running, or has already completed. The key thing is that the task should be created and scheduled before it returns to the caller.

Stephen Cleary has a quick read on the topic of starting tasks which I feel is relevant: 
http://blog.stephencleary.com/2015/02/a-tour-of-task-part-8-starting.html

**Comment by FlorianRappl** [comment]
Clearly we are discussing different things.

**Comment by FlorianRappl** [comment]
Implemented, see PR #301.
