### ISSUE TITLE
Children of cloned element are parent-less

### ISSUE THREAD

**Issue by jglinsek** [AngleSharp/AngleSharp#28]
It seems that if you clone an element, remove it from the document, and then re-add it (append it), that the element itself will have the correct Parent, but none of it's children (or grandchildren) have any parent at all. This seems wrong - unless I am misunderstanding something.

I was attempting to use this to use an element (and it's contents) as a template, that I could use to stamp out modified copies - but I also need to get at the parents of the children of the cloned elements.

Here is a failing test:
Gist: https://gist.github.com/jglinsek/dab7f950a3054cf97301

```
public void replace_the_parent_with_a_clone_and_the_children_of_the_cloned_parent_should_have_a_parent()
{
    const string html = @"
<html>
<body>
    <div class='parent'>
        <div class='child'>
        </div>
    </div>
</body>
</html>
";
    var doc = DocumentBuilder.Html(html);
    var originalParent = doc.QuerySelector(".parent");

    //clone the parent
    var clonedParent = originalParent.Clone();
    clonedParent.Parent.ShouldBe(null);

    //remove the original parent
    var grandparent = originalParent.Parent;
    originalParent.Remove();
    originalParent.Parent.ShouldBe(null);
    grandparent.ShouldNotBe(null);

    //replace the original parent with the cloned parent
    grandparent.AppendChild(clonedParent);
    //the clone itself has the correct parent
    clonedParent.Parent.ShouldBe(grandparent);

    //all the children (and grandchildren) of the cloned element have no parent?
    var cloneElement = (IElement) clonedParent;
    cloneElement.FirstChild.Parent.ShouldNotBe(null); //FAILS
}
```

**Comment by FlorianRappl** [comment]
Thanks for the report. 

Yes, this certainly is a bug. The children of cloned elements do not set the parent at all. I included your test (and others, similar to this one). The upcoming release (0.7) already fixes this issue.
