### ISSUE TITLE
How do you change the active document?

### ISSUE THREAD

**Issue by Code-Grump** [AngleSharp/AngleSharp#281]
I'm attempting to provide a basic implementation of `IHistory` and `IHistoryService`, but I can't see a way to alter the active document without using `IBrowsingContext.NavigateTo(IDocument)`, which in turn attempts to add to the history.

Where should I be looking?

**Comment by FlorianRappl** [comment]
I don't think there is anything yet. A proper design is needed first that does only pass on the "controlling" capabilities to certain services (such as the history services).

Feel free to play around in this area.

**Comment by Code-Grump** [comment]
I can only see three mechanisms that should be able to change the current document:
- Explicit navigation to a URL
- Interaction with the loaded document which causes navigation to a new document (e.g. follow a link or submit a form)
- Navigating through the history with back / forward actions

Do you think these actions should all call into a common service to load the document into the browsing context?

**Comment by FlorianRappl** [comment]
Some of these actions have to go over the history proxy as they'll need to modify the state of the history (if available / push or pop). I guess in general all navigation actions have to go over the history proxy except the history proxy itself, which has to have direct access to the browsing context (setting the active document with all related properties).

It's up to us to decide if the ability to change the active document (w/o going over the history proxy) should be exposed or not. I think it should not (because everyone should be able to implement his / her own history proxy, which can then do it).

What is your opinion here?

**Comment by Code-Grump** [comment]
I'm a fan of restricting state modifications as much as possible; if it was possible to just "set" the active document, it would open the door to a lot of unspecified state transitions and the application becomes a lot harder to reason about.

I'm wondering whether history needs to be a "baked in" service to some degree, like Navigate is.

The way I perceive the controlling API is as something of a "user-agent", a controller which acts on behalf of the user:

``` cs
interface IUserAgent
{
    IDocument Current { get; }
    IHistory History { get; }
    Task NavigateAsync(Url location, CancellationToken cancellationToken);
}

interface IHistory : IEnumerable<IHistoryEntry>
{
    Task GoToAsync(IHistoryEntry entry, CancellationToken cancellationToken);
    Task NavigateBackAsync(CancellationToken cancellationToken);
    Task NavigateForwardAsync(CancellationToken cancellationToken);
}

interface IHistoryEntry
{
    String Title { get; }
    Url Location { get; }
    DateTimeOffset VisitedAt { get; }
}
```

This is essentially the interface a browser provides to the user and it lines up with the `BrowsingContext`, except for the History property. I feel like the context should be internalizing its own state and only accept transitions via this style of controlling interface.

The history service itself is probably more interesting to implement in terms of what gets added to the **visible** history and what does not, as well as how it treats providing the requested resources, particulary in regards to whether to re-issue a cached document or to repeat the original request. This could be done by having the `BrowsingContext` (acting on a request to its controller `IHistory` interface) make requests for the appropriate documents which the context can then treat as any other document load.

This is a crude starting position for how such a service could be presented:

``` cs
interface IHistoryService
{
    IEnumerable<IHistoryEntry> Entries { get; }
    Task AppendAsync(IDocument document);
    Task<IDocument> GetDocumentAsync(IHistoryEntry entry, CancellationToken cancellationToken);
}
```

I think we should be trying to separate the idea of maintaining and accessing the history graph from the controller which seeks to change the state of the browsing context by navigating through the history.

**Comment by FlorianRappl** [comment]
This separation is definitely a must-have.

So for the `IHistoryService` the `AppendAsync` appends an already loaded (maybe not fully loaded / currently loading) document, while the `GetDocumentAsync` tries to get an already added document (if still available) or otherwise re-loads the document, right?

Regarding the `IUserAgent`: Shouldn't we just expose the `History` or on the `IBrowsingContext`? Having two interfaces, which share a common principle (except for one property) sounds a bit like redundancy to me. But maybe I have the wrong impression on how `IUserAgent` would be used.

**Comment by Code-Grump** [comment]
Sorry for any confusion - `IUserAgent` was intended to illustrate the "controller" functionality without pulling in other other functions exposed by `IBrowsingContext`. Though it might have value to extract this behaviour to a separate interface and have `IBrowsingContext` extend it, I don't have especially strong feelings about it. It would be perfectly good to add the missing `History` property to `IBrowsingContext`.

You have my intentions correct around the behaviour of the service: `AppendAsync` to add to the history, called by the browsing context after a response document is loaded, and `GetDocumentAsync` to obtain the document represented by an entry in the history.

Unfortunately it doesn't properly address the complexities of history re-writing that happens in browsers. Imagine the following use-case:
1. User navigates to location `\`
2. User follows link in location to `\foo`
3. User navigates backwards in the history to `\`
4. User follows a different link in location to `\bar`

After the second step the history should look like:
- `\`
- `\foo`

After the fourth step the history should look like:
- `\`
- `\bar`

This kind of history re-writing is what I would expect to see. There are probably some more complex cases, but there needs to be some way to "change" history in this fashion. I'm thinking I should have a look at some of the data-structures used by Git for inspiration.

**Comment by FlorianRappl** [comment]
Well, I think the history service would be responsible for keeping track of the current item. Then the append method would first remove all entries from the current history index (exclusive) to the end (inclusive) - which may not remove any entries if we are at the end already - before adding the new entry.

It would be indeed good to have a railroad-like data structure, which may be very powerful. The browser just shows a linear history (with the rewriting exposed), but does not have the multi-level tree topology (as in git) exposed. Yes, I think looking on how git does it would be beneficial. 

The complexity is indeed high, especially since you can alter the history w/o changing the document (the `IHistoryEntry` needs to point to a document (weak pointer would be a good choice I guess). Actually there is a n:1 relation from history entries to documents as the same document may be referenced from multiple (contiguous) entries.

So the history service also needs also to keep track of these states, right?

**Comment by Code-Grump** [comment]
The entries probably shouldn't point to a document. If an entry captures the request and a summary of the result, to return to that state the action should be to re-issue the request. If there's caching available, you may get a cache-hit and don't have to go over the wire.

This should make it easier to implement as well. When the `BrowsingContext` wants to transition to a historical state, it only needs to get the request from the history and pass it down the normal requesting route.

If we think about history as primarily a series of events (ignoring the idea of "current" for the moment), the model becomes:

```
interface IHistoryEntry
{
    IRequest Request { get; }
    string Title { get; }
    DateTimeOffset VisistedAt { get; }

    IHistoryEntry Previous { get; }
    IHistoryEntry Next { get; }
    IEnumerable<IHistoryEntry> AlternativeNext { get; }
}
```

I should be clear: **I don't think this model is very good**, because the idea of "next" becomes very muddied. I think every entry should have a reference to its parent state (except for the initial entry which has no previous state), but direct references to child states aren't so clean.

I think to continue the discussion, we need to separate the idea of "all history" from "session history". I'm thinking of the difference between going to your browser history and seeing all the pages visited across all time, and the history you see when you interact with the Forward and Back buttons. If you have any better terminology for these concepts, we should try to use it.

Whilst we may not be especially interested in "all history", I think that if we model the problem correctly, the "session history" just becomes a view over "all history", a bit like looking at your current branch, versus looking at the entire Git graph. It would also have the advantage of making history an append-only model, so there's no need to prune nodes.

```
interface IHistoryService
{
    Task<IEnumerable<IHistoryEntry>> GetEntriesAsync(DateTimeOffset from, DateTimeOffset to);
    Task AppendAsync(IHistoryEntry parent, IRequest request, string title);
    Task<IRequest> GetRequestAsync(IHistoryEntry entry);
}
```

The downside of this approach is that the data-structures aren't going to be optimal for the Back|Forward interaction. It's trivial to go back when you have a reference to your parent node, but harder to go forwards when there's the possibility of multiple child nodes, unless there's some construct to wrap those nodes into a timeline of sorts.

```
interface ISessionHistory
{
    bool CanGoBack { get; }
    bool CanGoForward { get; }
    IHistoryEntry Current { get; }
    void Back();
    void Forward();
    Task AppendAsync(IRequest request, string title);
}
```

This interface is getting a close to the proposed `IHistory` controller interface, but it includes an `AppendAsync` method to allow us to write some history based on the current position. I expect this `IHistory` interface to be implemented using this session history interface to manage that current position.

I think maintaining a "current" value is a trickier business in the the history service, since it will have to have understanding of the state transitions of Back and Forward to be able to manipulate that "current" value. I think `BrowsingContext` is better suited to handle these concerns, or rather whatever the implementation is for its `History` property, as that also needs to know if going back or forward is possible: to answer the question "is there a back or forward element in the current timeline?"

**Comment by Code-Grump** [comment]
Oh and as an extra bit of complication, when dealing with HTTP we should probably take care to include only a single request when a redirection takes place. Having an entry for every "hop" is not correct.

**Comment by FlorianRappl** [comment]
The redirection (from HTTP) is handled from the HTTP requester (being sensitive to 3xx status codes) - so there won't (shouldn't) be multiple entries.

I don't understand why the entries shouldn't point to documents. If you go back (or forward) on a real browser, you'll also get the result immediately (unless it has been GC'ed), which should be the same behavior here. 

To make things easier we should define "history" as the "session history". There is no "all history" (and if there should be, it could be implemented on top of the document requester, which keeps track of all requested documents; then one would only need to keep track of "requested documents" and the time of their requests).

One of the key questions at this point in time is: Do we really want to implement this all in AngleSharp.Core or shouldn't it be placed in a new library called AngleSharp.Browser? The idea is: Let's integrate the core interfaces and connections in AngleSharp.Core and let's bring everything together (for, e.g., a headless browser, which may also be connected to a rendering engine some day) in a new library (that depends on AngleSharp.Core, AngleSharp.Scripting, maybe AngleSharp.Io, ...).

Maybe the use case of a correct history is so important that it has to be implemented in AngleSharp.Core - I don't know. I certainly think that the interfaces (and their connections / usages) need to be defined here, but I am not sure if (default) implementations need to be supplied as well. One example is the "all history": For a standard user (just download / parse one simple page) this would be overkill, but if one wants a fully programmable (headless) browser, it may be very useful.

**Comment by Code-Grump** [comment]
You will only get the cached entries if the cache allows it: if the request itself is "safe" according to the HTTP verb and the cached entry itself is still valid. You will surely have encountered the dialog popup when you navigate back to page generated by a form submission and it warns you that the request is going to be re-issued, potentially changing state on the server.

It sounds like you have a clear idea of the direction you want to take AngleSharp. I'm viewing this from the perspective of having a headless browser to automate testing. Perhaps it would be good to get a clear statement of the scope of AngleSharp and its components before proceeding down this specific discussion of implementing History? Maybe issue #139 needs to be resolved first?

It's not possible for me to judge whether there should be an AngleSharp.Browser package containing these navigation-oriented behaviours without first knowing where the end of the AngleSharp.Core scope lies.

**Comment by FlorianRappl** [comment]
I answered the question easily by introducing a setter to the `Active` property. This seemed to me the most simple, elegant, yet flexible way forward without introducing too many things beyond the originally intended scope.

Also, this way AngleSharp.Core does not care about history specifics and is flexible by itself. The proposed history would be something for the yet not started AngleSharp.Browser extension library.

For the solution see PR #342.
