### ISSUE TITLE
Html Parser returns an incomplete DOM when encountering a special right arrow character

### ISSUE THREAD

**Issue by davrob01** [AngleSharp/AngleSharp#282]
Hello,

When attempting to parse the following Amazon page:

[http://www.amazon.fr/gp/bestsellers/english-books/80179011/?pg=1](http://www.amazon.fr/gp/bestsellers/english-books/80179011/?pg=1)

I have noticed that the parser is stopped short and returns an incomplete DOM when it encounters this special character, which appears to be a very small right arrow. This character does not render in any of the browsers I have tested thus far. I am only able to see the character in Visual Studio or notepad, which displays this character as follows (It is in between 'd' and 'articles'):

![cannot parse this right arrow character](https://cloud.githubusercontent.com/assets/16584191/13597579/faf1082e-e4de-11e5-9f48-6e521bc2c2e9.png)

I have tried setting different encodings for the parser, including the encoding that Amazon is setting in the response headers for these pages.

Attached is code that can reproduce the issue. (I could not paste the code properly in this message block for some reason).
[Example code.txt](https://github.com/AngleSharp/AngleSharp/files/162928/Example.code.txt)

Note: I was able to parse the page successfully using other Html parsers, such as HAP.

**Comment by davrob01** [comment]
After diving into the AngleSharp code, I've learned that this character is character 26, 0x1a and is often considered an "end of file symbol." The AngleSharp parser is checking against this character during tokenization. And furthermore depends on this symbol because it will actually define and use this symbol when the end of the content array is reached during parsing.

AngleSharp\AngleSharp\TextSource.cs:

![endoffilesymbol check](https://cloud.githubusercontent.com/assets/16584191/13627637/58a046ee-e591-11e5-8d57-6a5b7165efc1.png)
AngleSharp\AngleSharp\Foundation\Symbols.cs:

![symbolclass](https://cloud.githubusercontent.com/assets/16584191/13627993/2e1ef7a0-e594-11e5-93cb-9e37153746ad.png)

I was questioning whether or not Amazon is actually sending this symbol, or if something is inputting this symbol in the response stream for some reason... But according to Fiddler, it is indeed in the response from Amazon.

![fiddler proof3](https://cloud.githubusercontent.com/assets/16584191/13627926/b3cacb82-e593-11e5-9a43-a85471fc5db4.png)

Maybe Amazon is doing this to counter web scraping attempts... 

In any case, I am curious to know if this would call for a change in the way the parser is checking for end of file during parsing... But I can imagine that might be a change with a lot of collateral effects. But I have not looked any further in that regard.

I suppose the solution is to check against a different symbol when determining if it is the end of the file. I may have to do this in my own forked version for now...

**Comment by FlorianRappl** [comment]
Hm, there are two options. One could replace the returned character with a `Nullable<Char>`, indicating that the end of the content array has been reached by returning a "null" value, i.e., the state of the `Nullable<Char>` instance set to false. However, this approach would of course come with some (the least amount of) overhead. I could make some experiments to check if the performance implication is severe, or is negligible. The second option is to introduce another character, but there is none that may be unused.

Before doing so I would love to know if AngleSharp seems still fishy at this point in time. From what I understand (but please correct me if I am on the wrong path) the symbol is already in the transmitted source. The difference from AngleSharp to, e.g., HAP, is that AngleSharp carries this symbol to the DOM, while others seem to remove it (what is the browser's behavior? as it is a non-printable symbol it is clear that we do not see it printed, but is it also in a browsers DOM?

Are we sure Fiddler is showing the right thing? I realized that the character seems to be an apostrophe `’`, so it might just be an encoding error / missing surrogate pair. The charcode seems to be 8217 or 0x2019, which should be no problem. In UTF-8 these are three bytes (226, 128, 153); I see no collision here.

**Comment by Suchiman** [comment]
@FlorianRappl you could use the "character" roslyn uses, http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Parser/SlidingTextWindow.cs,24

**Comment by FlorianRappl** [comment]
Yes @Suchiman that's a good hint, `Char.MaxValue` would work. However, right now I am not sure what exactly the issue is (if the issue is related to the choice, then certainly `Char.MaxValue` would be the best option).

**Comment by davrob01** [comment]
Thank you for the replies, very helpful and timely.

It would make sense if the actual character was supposed to be an apostrophe, but no matter how I attempt to download this page in C# I am still receiving the end of file character instead. I have tried different encodings when converting the stream to a string but still get the same result.

I do not know at what point the character is being converted or if at all (Amazon may actually be transmitting it).

If anyone can download this page in C# without there being this end of file character in the middle of the page, I would be interested to know the settings of your request headers, encoding used, etc.

I've tried UTF-8, ISO-8859-15, ISO-8859-1, UTF-16.

Thanks

**Comment by FlorianRappl** [comment]
I've written the following LINQ script:

``` cs
void Main()
{
    var client = new HttpClient();
    var uri = "http://www.amazon.fr";
    var response = client.GetAsync(uri).Result;
    var ms = new MemoryStream();
    response.Content.CopyToAsync(ms).Wait();
    var bytes = ms.ToArray();

    for (var i = 0; i < bytes.Length - 2; i++)
    {
        if (bytes[i] == 226 && bytes[i + 1] == 128 && bytes[i + 2] == 153)
        {
            i.Dump();
        }
    }

    ms.Position = 0;
    var reader = new StreamReader(ms);
    reader.ReadToEnd().Dump();
}
```

Using this I find 2 such apostrophes, which are in close proximity to each other (within ~300 characters). I guess in VS you'll find the same result. The remaining question is: Is it maybe just a VS display bug or a deeper issue? You need to look at the raw bytes for this.

The raw bytes are okay for me - and LINQPad / the browser control intergrated in LINQPad shows the string contents correctly. So the issue is definitely no in .NET's char or the download stream.

**Comment by FlorianRappl** [comment]
Alright so I've written a little test against the current version in `devel` and everything seems to be alright...

``` cs
var address = "http://www.amazon.fr";
var config = new Configuration().WithDefaultLoader();
var document = await BrowsingContext.New(config).OpenAsync(address);
var div = document.QuerySelector("#nav-prime-tooltip .nav-npt-text-title");

Assert.IsNotNull(div);
Assert.AreEqual(" Livraison en 1 jour ouvré gratuite et illimitée sur des millions d’articles ", div.TextContent);
```

Maybe you can recheck. But the problem has either been fixed from the version you use, or is located somewhere else.

**Comment by davrob01** [comment]
I am surprised Amazon goof'd their website because its very inconsistent in this regard. So it appears that the apostrophe is indeed present and visible at the root of their french domain https://www.amazon.fr 

However, the URL I am concerned with is http://www.amazon.fr/gp/bestsellers/english-books/80179011/?pg=1

Call me crazy, but there's a difference. Amazon is not sending an apostrophe on the english best seller books page of their french domain in between the d and article, just hover over the word "premium" in top left corner in any browser and you will see. Please run your test against this specific URL. 

Actually the apostrophe is not on the general best sellers page either:

http://www.amazon.fr/gp/bestsellers/

I know this sounds rediculous, but thats what I am seeing. Please test.

**Comment by FlorianRappl** [comment]
There for sure is a difference. First of all, the page encoding is different (ISO-8859-15 vs UTF-8 previously), however, that does not matter as far as I can see. What is more crucial is that the homepage does not contain a `meta` tag with the `charset` attribute.

Right now AngleSharp does not consider the transported encoding from the headers - but this is a case where it really has to use it. Otherwise it ends up with UTF-8, which is not capable of displaying some of the characters (e.g., `é`) as they are differently placed in ISO-8859-15.

The other issue with the former ending also exists, and is investigated separately.

This is a good test case and I will fix it with the next release. Thanks for your contribution!

**Comment by davrob01** [comment]
No problem. Thank you for the awesome work you put into this. Happy coding

**Comment by FlorianRappl** [comment]
This is fixed and will be deployed tomorrow.
