### ISSUE TITLE
Extra colon in SVG tag's name

### ISSUE THREAD

**Issue by yoongu** [AngleSharp/AngleSharp#286]
I've been using AngleSharp to parse the HTML dump of some websites, and then just printing out all their tag names in depth-first traversal order.

For Youtube's HTML dump [1], I've noticed that AngleSharp parses some <svg> elements' tag name as "svg:", and not "svg". (Please see [2].) Just as a comparison point, I don't see this happening for CsQuery [3] or HAP [4].
- [1] [youtube.com.html.txt](https://github.com/AngleSharp/AngleSharp/files/179916/youtube.com.html.txt)
- [2] [youtube.com.angle.txt](https://github.com/AngleSharp/AngleSharp/files/179913/youtube.com.angle.txt)
- [3] [youtube.com.csq.txt](https://github.com/AngleSharp/AngleSharp/files/179915/youtube.com.csq.txt)
- [4] [youtube.com.hap.txt](https://github.com/AngleSharp/AngleSharp/files/179914/youtube.com.hap.txt)

**Comment by FlorianRappl** [comment]
CsQuery and HAP should not be considered as comparisons. Also while the HTML is of course useful, more useful is the code to reach the referenced txt file. From this code I can compare to the behavior of real browsers - which is much more important as a point of reference.

That is not to say there is no bug; it indeed sounds like a bug, however, HAP has problems with a lot of HTML5 pages and CsQuery is not maintained any more. Just because _they_ differ does not mean that there is bug.

**Comment by yoongu** [comment]
Hi Florian,

After parsing an HTML file, here's how I generated the txt file. (The HTML files themselves were extracted through Selenium WebDriver.) I am aware that CsQuery/HAP are abandoned, but I was just curious how they would fare for websites in the wild. I'm already a fan of AngleSharp :) 

``` csharp
    public static string Serialize(IElement root)
    {
        var tags = new StringBuilder();
        DepthFirstTraversal(root, tags);
        return tags.ToString();
    }

    static void DepthFirstTraversal(IElement node, StringBuilder tags, int depth = 0)
    {
        tags.Append(new string(' ', 2 * depth));
        tags.Append(node.TagName.ToLower());
        tags.Append("\n");

        foreach (var child in node.Children) 
            DepthFirstTraversal(child, tags, depth + 1);
    }
```

**Comment by FlorianRappl** [comment]
Thanks for the code :+1: ! I look at it in more detail and fix the issue.

**Comment by FlorianRappl** [comment]
I found the issue and fixed it (already available in the `devel` branch).
