### ISSUE TITLE
RSS requesting bug

### ISSUE THREAD

**Issue by ushenkodmitry** [AngleSharp/AngleSharp#290]
Requested RSS enclosed within the html body element like this:
`<!--?xml version="1.0" encoding="UTF-8"?--><html><head></head><body><rss version="2.0">...</rss></body></html>`.

**Comment by FlorianRappl** [comment]
If you try to read XML as HTML then this is expected. How does your code look like?

Output of such an RSS feed (parsed as HTML) from an evergreen browser:

![image](https://cloud.githubusercontent.com/assets/1766191/13919757/af0ed59e-ef6f-11e5-915c-e29643ef1efa.png)

**Comment by ushenkodmitry** [comment]
Exactly!
