### ISSUE TITLE
Comments with spaces cause parser anomalies

### ISSUE THREAD

**Issue by tghamm** [AngleSharp/AngleSharp#292]
I've encountered a scenario in a html scrubber we built with AngleSharp that presents when there are spaces in the comment tags. It causes content after the closing node to not be put into the body when parsed, it is instead considered part of the comment.

Consider the following example:

``` xml
<!--[if gte mso 9]><xml>
 <o:OfficeDocumentSettings>
  <o:AllowPNG></o:AllowPNG>
 </o:OfficeDocumentSettings>
</xml>< ![endif]-- >Test
```

The spaces in `< ![endif]-- >` cause `Test` to be parsed as part of the comment when reviewing the parsed nodes.

When parsing like so, where `text` is the text above:

``` cs
var parser = new HtmlParser(new Configuration().WithCss(e => e.Options = new CssParserOptions
{
  IsIncludingUnknownDeclarations = true,
  IsIncludingUnknownRules = true,
  IsToleratingInvalidConstraints = true,
  IsToleratingInvalidValues = true,
}));
var doc = parser.ParseFragment(text, null).ToHtml(new XmlMarkupFormatter());
```

Produces:

``` xml
<!--[if gte mso 9]><xml>
 <o:OfficeDocumentSettings>
  <o:AllowPNG></o:AllowPNG>
 </o:OfficeDocumentSettings>
</xml>< ![endif]-- >Test--><html><head></head><body></body></html>
```

Removing the spaces produces the proper:

``` xml
<!--[if gte mso 9]><xml>
 <o:OfficeDocumentSettings>
  <o:AllowPNG></o:AllowPNG>
 </o:OfficeDocumentSettings>
</xml><![endif]--><html><head></head><body>Test</body></html>
```

Is this a bug in AngleSharp, or is it proper that this edge case will be handled in this fashion?

**Comment by FlorianRappl** [comment]
This is the expected behavior. You can see the same behavior in any evergreen browser, e.g. in Opera (based on Chromium):

![image](https://cloud.githubusercontent.com/assets/1766191/13946921/e2ae2b40-f017-11e5-9607-f54dab139ec3.png)
