### ISSUE TITLE
Encoding issue when html meta charset differs from HTTP header Content-Type charset

### ISSUE THREAD

**Issue by vtherry** [AngleSharp/AngleSharp#295]
When crawling a website which respond using HTTP header 

`Content-Type: "text/html; charset=windows-1252"`

And HTML contains :

`<meta charset="utf-8">`

We end up with accented characters being badly encoded because the real encoding is windows-1252 but while parsing the DOM we are using UTF8

An other issue seems to appear with charset not being detected when there is a space juste after the semi colon.

In MimeType.cs > GetParameter(String key) method, the StartsWith should take into account spaces, or the variable `_params` should be trimmed in the ctor ?.

**Comment by FlorianRappl** [comment]
Which version are you using? This should have been fixed (as a sideeffect) in #282 (see PR #284).

**Comment by vtherry** [comment]
Hi,

thank you for your quick answer.
I was using the following version in NuGet :
`<package id="AngleSharp" version="0.9.5" targetFramework="net461" />`

and I encountered the issue when the charset that differs between meta tag and content-type header.

So i switch to the latest release v0.9 to download a stable copy and investigate attaching to my code. That is why I have found the other but with the leading space that is now fixed when I look at the latest code..

But I do not see in the issue #282 something close to my issue ?

**Comment by FlorianRappl** [comment]
> We end up with accented characters being badly encoded because the real encoding is windows-1252 but while parsing the DOM we are using UTF8.

This is exactly one of the things that happened in #282, which happened due to the leading space. Nevertheless, yes - you are right that here we have one additional aspect (that I initially overlooked): The charset precedence.

Right now AngleSharp only uses the charset provided from the `Content-Type` header as an initial suggestion. The `meta` tag is preferred to set the encoding.

I guess the precedence in browsers is different. If an encoding is specified in the HTTP headers, this will be taken. I'll change the behavior!

**Comment by vtherry** [comment]
Yes you can test with www.leboncoin.fr as an exemple.

Even if the charset in the header couldn't be parsed,  by chance for my
locale windows1252 was used,  but when parsing the DOM the parser changes
to Utf8.

I guess too that browsers prefers to use the charset in header vs in meta
tag if both exist.

Thank you for your analysis on this issue !
Le 23 mars 2016 8:33 AM, "Florian Rappl" notifications@github.com a
écrit :

**Comment by FlorianRappl** [comment]
So the encoding precedence that will be implemented will follow [W3C recommendations](https://www.w3.org/International/questions/qa-html-encoding-declarations.en) (from high to low):
1. BOM
2. HTTP Header
3. meta tag
4. Suggested default one (e.g., locale-based)

The idea is that the BOM findings will override any set encoding (and fix the mode, to disallow further changes). Supplied encodings via the header will be set via the `Encoding` property, practically fixing it from the outside.

I will come up with a set of unit tests that need to be fulfilled for this item to be closed.

**Comment by FlorianRappl** [comment]
Will be available in the next release, see PR #299.
