### ISSUE TITLE
please support windows phone 8.1

### ISSUE THREAD

**Issue by h82258652** [AngleSharp/AngleSharp#30]
I'm founding a html parser for wp8.1. AngleSharp is powerful, but I could not use it with wp8.1. Please support wp8.1. Thanks.

**Comment by FlorianRappl** [comment]
The next Nuget package will also include the support for Windows Phone 8.1. Right now you can already use it, however, Nuget does not realize it also works. As a workaround either download the Nuget package manually and include the reference manually, or download the source and compile it. It definitely works.

Sorry for the inconvenience, v0.7 should be released in a couple of hours -- then it should also work directly via Nuget.

**Comment by FlorianRappl** [comment]
Nuget is available, please check if it works.

**Comment by h82258652** [comment]
Thanks very much! AngleSharp helps me to replace my old regex codes.

**Comment by h82258652** [comment]
Thanks , It works correctly . I just try querySelector and xpath , both of them are correctly. Many thanks.

**Comment by FlorianRappl** [comment]
QuerySelector will work as expected, however, please note that xpath is not implemented / included yet.
