### ISSUE TITLE
Pooled instances have the possibility of conflicting with other instances

### ISSUE THREAD

**Issue by TheCloudlessSky** [AngleSharp/AngleSharp#300]
There are a few places there instances created from `Pool` live longer than they should. They can be used after calling `ToPool()`. This causes the instances to be released to the pool, but it could still be used when someone else has allocated it from the pool.

For example, `TextSource.Disposed()` could be called more than once which causes _other_ `TextSource` instances to conflict. Here's a sample test (obviously calling `Dispose` twice shouldn't be done, but it illustrates the problem):

``` csharp
[Test]
public void failing_when_disposed_more_than_once()
{
    var parser = new HtmlParser();
    var document1 = parser.Parse("<!doctype><html><head></head><body><h1>Hello World</h1></body></html>");
    Assert.Equal("<!DOCTYPE ><html><head></head><body><h1>Hello World</h1></body></html>", document1.ToHtml());
    document1.Dispose();
    document1.Dispose();

    var document2 = parser.Parse("<!doctype><html><head></head><body><h1>Hello World</h1></body></html>");
    Assert.Equal("<!DOCTYPE ><html><head></head><body><h1>Hello World</h1></body></html>", document2.ToHtml());
    document2.Dispose();
    document2.Dispose();
}
```

Therefore, I suggest anything created from the `Pool` class be wrapped in some sort of pool wrapper. Accessing the instance will throw/be a no-op when accessing the instance after it's been disposed/released to the pool.

The alternative is manually managing the instances returned from the pool (setting them to null) which is similar to the dangers of manual memory management :cry:.

I have a couple of implementation options that I'd be glad to submit as a PR:
1. Never allow accessing the _real_ instance (e.g. `PooledStringBuilder`). Create proxy methods on the pooled class. This is the safest guarantee that instances won't be accidentally shared and there is significantly less possibility of dangling references later.
2. Create some sort of `Pooled<T>` wrapper. This has the disadvantage that consumer's could call `GetInstance()` and re-use that instance:
   
   ``` csharp
   class Pooled<T> : IDisposable
   {
       private bool disposed;
       private T instance;
       private readonly Action<T> release;
   
       public T GetInstance()
       {
           return instance;
       }
   
       public Pooled(T instance, Action<T> release)
       {
           this.disposed = false;
           this.instance = instance;
           this.release = release;
       }
   
       public void Dispose()
       {
           if (disposed) return;
   
           disposed = true;
           var localInstance = instance;
           instance = null;
           release(localInstance);
       }
   }
   ```
3. Partially combine 1/2 and expose some sort of `Use(Action<T> useInstance)` and `Use<TResult>(Func<T, TResult> useInstance)` rather than returning an instance with `GetInstance()`. This would create a scoping for the instance rather than letting the consumer decide.

Also, a `Pool<T>` could be created as storage for each `Pooled<T>` so that it can have a common instance factory/way to reset an instance before being re-used.

**Comment by FlorianRappl** [comment]
While I see the problem I think there are simpler solutions to this than creating yet another layer of abstraction. In most cases the pooled resources are used only _locally_, i.e., within a function. For obvious reasons the _TextSource_, as well (for performance reasons) the _BaseTokenizer_ use a global one. I don't know if any other classes use pooled resources globally.

Nevertheless, I would suggest to improve the disposal in such a way, that illegal usage of the pooled resource is impossible. However, I will need to have a closer look at the problem / the usages to fully grasp the scope of this. If its too hard then I would aim for solution 1), as this seems to be the most robust one.

I think we should aim for a fix in the next version.

**Comment by TheCloudlessSky** [comment]
I agree with you about the advantage of locally-created pooled objects and wanting to keep the abstractions to a minimum. However, just because a object is locally created, doesn't mean it can't be used once it's been released back to the pool.

Perhaps an alternative would be to change the releasing signature to `string Pool.Release(ref StringBuilder instance)` to ensure that the `instance` could get nulled (fixing any local problems).

A pooled `StringBuilder` is stored as a private variable for (and thus could be reused):
- `BaseTokenizer`
- `TextSource`

A pooled `CssSelectorConstructor` is stored as a private variable for (and thus could be reused):
- `CssSelectorConstructor.NotFunctionState`
- `CssSelectorConstructor.HasFunctionState`
- `CssSelectorConstructor.MatchesFunctionState`
- `CssSelectorConstructor.HostContextFunctionState`
- `CssSelectorConstructor.ChildFunctionState<T>`

A pooled `CssSelectorConstructor` is used inside of `CssBuilder.CreateSelector()` _after_ `ToPool()` is called.

A pooled `CssValueBuilder` is used inside of `CssBuilder.CreateValue()` _after_ `ToPool()` is called.

I believe these are all the places where pooled objects have the potential to be reused.

I'd be happy to submit a PR with the direction you'd like to go.

**Comment by FlorianRappl** [comment]
Alright, so here is what I propose:

For `BaseTokenizer` and `TextSource` let's have the pooled `StringBuilder` mutable (not readonly) and `null` it in the `Dispose` method (after it has been returned to the pool). Use the state of the variable of the pooled `StringBuilder` to see if the resource (e.g., the `TextSource`) was already disposed -- this way saving a little `Boolean`.

The `...State` classes handling the `CssSelectorConstructor` I will inspect (maybe this can be solved more elegantly).

The ones that use pooled resources after returning it need to be fixed. Here the path should be adjusted such that the resource is guaranteed to be returned to the pool + not be used afterwards.

If you could submit a PR for these things I would highly appreciate it. I will have a look at the private `...State` classes in the mean time.

Thanks! :+1:

**Comment by FlorianRappl** [comment]
Fixed and up for the next release. See PR #309, #310. Thanks @TheCloudlessSky for pointing this out and making it more robust.
