### ISSUE TITLE
Can't parse html correctly despite browser can

### ISSUE THREAD

**Issue by YakupIpek** [AngleSharp/AngleSharp#311]
Parser is not able parse the url at below despite browser can. It parse the page without throw exception but parsed document contains almost nothing.

here is url http://www.glittercottage.com

It is tested on latest commit on main branch.

**Comment by FlorianRappl** [comment]
This has nothing to do with the parser. Have you ever tried receiving the content via, e.g., `curl`? The body I receive there is the same I receive / parse with AngleSharp.

**Comment by FlorianRappl** [comment]
What I can tell you is that the site you try to parse is protected by Incapsula. You will need to break this protection to gather the information. AngleSharp.Scripting.JavaScript may be helpful for that; but there is no version of the JS scripting library for v0.9.5 (there will be, however, one for v0.9.6).
