### ISSUE TITLE
nth selector with contains doesn't work

### ISSUE THREAD

**Issue by vickyRathee** [AngleSharp/AngleSharp#312]
I need to select the H3 tag based on it's content so I used the contains and it worked great, h3:contains('Feature One'). But the list is repeated multiple times and i need to extract the 2nd list so :nth(1) worked for me in chrome Jquery.

But this doesn't work in Query Selector all in AngleSharp = **h3:contains('Feature One'):nth(1)**

```
<ul>
<li>
<h3>
    <span class="feature-title">Feature One</span>
    <em class="feature-value">Value 1</em>
</h3>
</li>
<li>
<h3>
    <span class="feature-title">Feature Two</span>
    <em class="feature-value">Value 2</em>
</h3>
</li>
<li>
<h3>
    <span class="feature-title">Feature Three</span>
    <em class="feature-value">Value 3</em>
</h3>
</li>
</ul>
```

**Comment by FlorianRappl** [comment]
This is no CSS Selector. You probably mean `nth-child` (see [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child)).

**Comment by vickyRathee** [comment]
@FlorianRappl  But it's working with contain  **h3:contains('Feature One')**. So my question was why not with n-th

![image](https://cloud.githubusercontent.com/assets/6106479/14134136/74790e22-f672-11e5-89a2-ad24a0f52936.png)

![image](https://cloud.githubusercontent.com/assets/6106479/14134151/80e44924-f672-11e5-89f7-860f352e027f.png)

**Comment by FlorianRappl** [comment]
Please read my answer carefully. `nth` is **not** a CSS selector and therefore not in AngleSharp. Hence it should be obvious why its not working. You cannot take whatever stuff you've seen _somewhere_ and believe its working _somewhere_ else. Just to emphasize this again:

``` cs
var document = ...;
var elementsA = document.QuerySelectorAll("div:contains('foo')");//works! :)
var elementsB = document.QuerySelectorAll("div:contains('foo'):banana-pie");//does not works ... :(
```

The second does not work even though the first one works. I hope you can make the transfer to see why a working A does not immediately resolve to a working B. In this case `banana-pie` is no official CSS selector, hence its not supported.

Remark: Why do you expect support when you do not give support (e.g., use "stars" to give credit to projects you find / found useful / interesting)?
