### ISSUE TITLE
Error is given for self-closing img tag ending with "/>" (unlike ending with just ">")

### ISSUE THREAD

**Issue by savehansson** [AngleSharp/AngleSharp#313]
According to W3C `img` is a "void element" and as such the start tag _may_ end with `/>`. From [the W3C specification](https://www.w3.org/TR/html5/syntax.html#syntax-start-tag):

> 6_._ Then, if the element is one of the void elements, or if the element is a foreign element, then there may be a single "/" (U+002F) character. This character has no effect on void elements, but on foreign elements it marks the start tag as self-closing.

AngleSharp gives error code `34 The given tag cannot be self-closed`. If the `/` character is omitted no error is given.

**Comment by FlorianRappl** [comment]
Maybe I understood the specification wrong. But as far as I understood it HTML5 just tolerates trailing slashes, it does not advocate them. The advocated way is to omit the slash actually.

Now going to the [HTML 5.1 specification](https://www.w3.org/TR/2016/WD-html51-20160310/syntax.html#the-in-body-insertion-mode) I see _A start tag whose tag name is one of: "area", "br", "embed", "img", "keygen", "wbr"_. This leads to [the definition for the following quote](https://www.w3.org/TR/2016/WD-html51-20160310/syntax.html#acknowledge-the-tokens-self-closing-flag).

> Acknowledge the token’s self-closing flag, if it is set.

The interpretation that has been used to far lead to the current implementation.

Using validator.nu also does not show any errors with the trailing slash. I will file this as a bug / enhancement and solve it for the next release.

**Comment by FlorianRappl** [comment]
See PR #315 for a fix.
