### ISSUE TITLE
Simple demo not working

### ISSUE THREAD

**Issue by mralexivy** [AngleSharp/AngleSharp#316]
Simple demo not working , application is shut down when executing this line:
`await BrowsingContext.New(config).OpenAsync(address)`

**Comment by FlorianRappl** [comment]
What is address? Which version are you using? What is your environment? What is the exact error message? You cannot open issues without providing a bare minimum, which clearly is not met here.

Please consider opening a separate issue with more information. Also consider starring AngleSharp; support is only given if support is desired.

**Comment by qwert789** [comment]
I'm using the latest version 0.9 , the code is from the simple demo.


// Setup the configuration to support document loading
var config = Configuration.Default.WithDefaultLoader();
// Load the names of all The Big Bang Theory episodes from Wikipedia
var address = "https://en.wikipedia.org/wiki/List_of_The_Big_Bang_Theory_episodes";
// Asynchronously get the document in a new context using the configuration
var document = await BrowsingContext.New(config).OpenAsync(address);
// This CSS selector gets the desired content
var cellSelector = "tr.vevent td:nth-child(3)";
// Perform the query to get all cells with the content
var cells = document.QuerySelectorAll(cellSelector);
// We are only interested in the text - select it with LINQ
var titles = cells.Select(m => m.TextContent);
