### ISSUE TITLE
Use of static readonly string properties vs const

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#317]
Hi,

I noticed that e.g., PropertyNames.cs declares its properties `static readonly` instead of `const`.

Based on this (http://stackoverflow.com/questions/755685/static-readonly-vs-const) post it would seem that `const` might be faster since the literal is burned into the call site. Since this is a safe change to make, I recommend it. 

BTW I came across this issue since my own code has an almost identical list, and uses `const string` instead. I was trying to do away with my code in favor of AngleSharp's declarations.

Oh, and it would be helpful to make `class PropertyNames` public.

Cheers.

**Edit**: I just realized that if each assembly has its own copy of the string, fast compare by reference will not work. Is this why they are declared as static readonly? Does that consideration outweigh the overhead of a property access (I guess it does.) Ah well, .net performance never seems to stop being a puzzle even for the most basic things :)

**Comment by FlorianRappl** [comment]
Yes, `PropertyNames` will be public in the long run. And yes, it is `static readonly` intentionally. The SO thread should be digested thoughtfully; in micro-benchmarks the direct reference is faster, but for AS `static readonly` makes more sense.
