### ISSUE TITLE
Where is the ToText() that is mentioned in the Wiki?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [AngleSharp/AngleSharp#318]
https://github.com/AngleSharp/AngleSharp/wiki/Examples#getting-single-elements

> The other variants are all different. While `ToText()` is just a helper to strip text (and omit unwanted text contents like in `<script>` tags), the other two variants behave like the official W3C specified properties, leaving everything as it is.

I cannot seem to find this function? Also, in the code example, it is mentioned as `Text()`.

**Comment by FlorianRappl** [comment]
Yes, its called `Text()` and (as all helpers / extensions) its available by using `AngleSharp.Extensions`.
