### ISSUE TITLE
CssSelectorConstructor - for pseudoelement - ::selection

### ISSUE THREAD

**Issue by mediabuff** [AngleSharp/AngleSharp#32]
Hi
The css parser doesn't pick pseudo element '::selection' because of the following. I set the state back to State.Data.  Was this your design interntion ?

<pre>
Boolean OnPseudoElement(CssToken token)
        {
            if (token.Type == CssTokenType.Ident)
            {
                state = State.Data;  ///  Added. This seems to move the parser along ??
                var data = ((CssKeywordToken)token).Data;

                switch (data)
                {
                }
         }
</pre>

**Comment by FlorianRappl** [comment]
To be honest I don't know any more - its been a while since I wrote that one. All I can say is that pseudo elements are currently not supported. Of course the parser should still work for them, but since there is no mechanism for, e.g. having a visual tree that is then modified by a pseudo elements such as before and after, such a mechanism cannot take place. At some point, however, it is obviously desired.

I think that v0.8 will probably not ship with a solution for pseudo elements, but v0.9 will definitely contain some something to deal with them. Maybe you have a good idea how to bring them in efficiently.

**Comment by mediabuff** [comment]
Same compliments as for issue #31. Thank you for the fixes.

**Comment by mediabuff** [comment]
Ok. The fixes seem to work.

**Comment by mediabuff** [comment]
Related Item - Parsing of URL in background in line images - no support. Might be a good addition to convert the following to object model.

<pre>
eg.
.App_Header_ .logo { background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEcAAAAcCAMAAAAEJ1IZAAAABGdBTUEAALGPC/xhBQAAVAI/VAI/VAI/VAI/VAI/VAI/VAAAA////AI/VRZ0U8AAAAFJ0Uk5TYNV4S2UbgT/Gk6uQt585w2wGXS0zJO2lhGttJK6j4YqZSobH1AAAAAElFTkSuQmCC"); background-size: 71px 28px; background-position: 0 19px; width: 71px; }
</pre>

So, I ended doing Regex parsing as follows

<pre>
    public class UrlInlineContent
    {
        static Regex regexCssInlineImage = new Regex(@"data:(?<mimeType>.+);(?<encodeType>.+),(?<content>.+)", RegexOptions.CultureInvariant | RegexOptions.Compiled);
        static Regex regexTrimQuotes = new Regex(@"'(.*?)'", RegexOptions.CultureInvariant | RegexOptions.Compiled);
        static Regex regexUrls = new Regex(
        @"url\s*\(" +                                   // Match url, optionally some whitespaces and then (
        @"\s*" +                                        // Match optionally some whitespaces
        @"(""|\'|)" +                                   // It seems that the quotes are optional according to http://www.w3.org/TR/CSS2/syndata.html#uri
            //\K                                            // Reset the match
        @"(?![""\']?(?:https?://|ftp://))  " +          // Put your negative-rules here (do not match url\'s with http, https or ftp)
        @"(?<urlContent>(?:[^\\\\]|\\\\.)*?  )" +       // Match anything except a backslash or backslash and a character zero or more times ungreedy
        @"(?= " +                                       // Lookahead
            @"\1" +                                         // Match what was matched in group 2
            @"\s*" +                                        // Match optionally some whitespaces
            @"\)" +                                         // Match )
        @")",
        RegexOptions.CultureInvariant | RegexOptions.Compiled | RegexOptions.IgnorePatternWhitespace);
        public string mimeType;
        public string encodeType;
        public byte[] content;
        public string extension;
        static public IEnumerable<string> GetUrls(string source)
        {
            return regexUrls.Matches(source).Cast<Match>().Select(url => url.Groups["urlContent"].Value);
        }
        static public UrlInlineContent GetContent(string url)
        {
            var ui = new UrlInlineContent();
            var groups = regexCssInlineImage.Match(url).Groups;
            ui.mimeType = groups["mimeType"].Value;
            ui.encodeType = groups["encodeType"].Value;
            if (ui.encodeType == "base64")
            {
                var contentBase64 = groups["content"].Value;
                ui.content = Convert.FromBase64String(contentBase64);
                ui.extension = '.' + ui.mimeType.Split('/')[1];
            }
            return ui;
        }
        static public string TrimQuotes(string text)
        {
            return regexTrimQuotes.Match(text).Groups[1].Value;
        }
    }
</pre>

**Comment by FlorianRappl** [comment]
Hm that URL should be supported already, since the argument of the `url` function will be passed on to an `Url` constructor, which I think should be also designed for base64 data URLs. I will look into that.

**Comment by FlorianRappl** [comment]
Alright I think I get what you are missing (since parsing seems to work, unit test is ok): You want the URL to be exposed! That is actually planned. Right now I still expose an old value model, that will be removed in one of the next versions. Then a much better variant that is only accessible via C# will be available (since JS only relies on strings - which is why the W3C marked the former specification obsolete).
