### ISSUE TITLE
Why the HtmlParser will auto add the html tag?

### ISSUE THREAD

**Issue by QBTomzhu** [AngleSharp/AngleSharp#322]
Here is the tag
`<p><center></center></p>`

When I try to use 

```
var document = new HtmlParser().Parse(input);
messagebox.show(document.QuerySelector("body").InnerHtml);
```

The result will be
`<p></p><center></center><p></p>`

**Comment by QBTomzhu** [comment]
And I find only the `p` tag contain the`center` tag will cause this issue.

**Comment by FlorianRappl** [comment]
This is all according to the HTML5 specification. The center and the p elements are both scoped and auto-close (similar to address and others).

You can find some of these rules explained in my [HTML5 Mastery Class series on tuts+](http://code.tutsplus.com/series/html5-mastery-class--cms-897). For anything beyond I recommend the  [W3C specification](https://www.w3.org/TR/html5/syntax.html#parsing).
