### ISSUE TITLE
Element.Insert AdjacentPosition.AfterEnd

### ISSUE THREAD

**Issue by pitschbr** [AngleSharp/AngleSharp#325]
I believe that when using Element.Insert with AdjacentPosition.AfterEnd and the referenced element is the last element of the parent, then an "index out of bounds" exception is thrown.

Dom/Element.cs line 570
Parent.InsertChild(Parent.IndexOf(this) + 1, nodes);

If 'this' is the last child of Parent, then that +1 makes it out of range in 

Dom/Node.cs line 311
public INode InsertChild(Int32 index, INode child)
{
      return this.PreInsert(child, _children[index]);  -- Line 311
}
I believe _children[index] will throw

**Comment by FlorianRappl** [comment]
Thanks for the report - I'll look into it!

**Comment by FlorianRappl** [comment]
Honestly, I forgot to look into this. Also I therefore skipped placing a Milestone (my bad!). I will take care of this in v0.9.7.

**Comment by pitschbr** [comment]
Awesome.  Thanks!

**Comment by FlorianRappl** [comment]
Fixed, see PR #335.
