### ISSUE TITLE
iso-22-cn is not supported encoding

### ISSUE THREAD

**Issue by ushenkodmitry** [AngleSharp/AngleSharp#326]
Hello again,
Took the latest code from devel branch to fix the issue #324 and now i'm getting exception in TextEncoding class
`Additional information: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.`
Here is screenshot
![iso22cn](https://cloud.githubusercontent.com/assets/16700959/14880885/0e860186-0d3a-11e6-97a7-f6bbd06167b7.png)

**Comment by FlorianRappl** [comment]
Unfortunately, I can't fix the .NET framework. Depending on the platform one or the other encoding may not be available. However, there is no way of knowing that (x-plat) beforehand, therefore the ugly catch'em all had to be inserted. If you simply press F5 the debugging will continue.

**Comment by douglasg14b** [comment]
@FlorianRappl  Is Html Agility Pack doing something different? I only get this error with AngleSharp.

**Comment by FlorianRappl** [comment]
Potentially. There are two options:

- Using a different framework
- Avoid all encodings except a certain subset

**Comment by jogibear9988** [comment]
Why not use GetEncodings and then create a Hashtable of the names, so the exception can be avoided?

**Comment by FlorianRappl** [comment]
Unfortunately not available on all platforms (always remember that this is a NetStandard 1.0 compatible library).

**Comment by jakesays-old** [comment]
Ok so how do we fix this using a framework that has support? I'm using 4.7.

**Comment by ronenfe** [comment]
I am using .net core 2.0 and got many first chance exceptions of unsupported encoding names.
I followed this link and it fixes all exceptions except the one that shows in the title.
https://stackoverflow.com/questions/39065988/utf8-is-not-a-supported-encoding-name
I searched for this encoding in the Anglesharp source code and didn't find it hard coded so I'm not sure where it is sent from.

**Comment by FlorianRappl** [comment]
@ronenfe - not supported in the given intersection that AS operates in. Its a PCL with a specific project that is .NET Standard 1.0 compliant.

The exception is a problem with your settings as the exception is handled within AS actually. In the subset we are operating in there is unfortunately no chance of getting to know if an encoding is supported upfront...

**Comment by ronenfe** [comment]
Hi, looking more into it, seems like the iso-2022-cn encoding isn't in the list of supported code page encoding of .net. Look at this list:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx
I think the solution can be to remove this encoding from:
https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Text/TextEncoding.cs
and also add this code:
```
System.Text.EncodingProvider provider = System.Text.CodePagesEncodingProvider.Instance;
Encoding.RegisterProvider(provider);
```
To support all other missing encoding of .net core, see also here:
https://msdn.microsoft.com/en-us/library/system.text.codepagesencodingprovider(v=vs.110).aspx

**Comment by FlorianRappl** [comment]
@ronenfe have you read my comment at all? The given possibility is not available in the subset of the .NET framework AS uses...

Also it is not helpful to remove this encoding as some platforms may support it. Removing it is the same as the behavior we have now - falling back to UTF8.

**Comment by mganss** [comment]
You could add one or all of the attributes `[DebuggerStepThrough]`, `[DebuggerHidden]` or `[DebuggerNonUserCode]` to the method. Some of these [might not work](https://blogs.msdn.microsoft.com/devops/2016/02/12/using-the-debuggernonusercode-attribute-in-visual-studio-2015/) in some versions of VS, but AFAICT they all work in VS 2017.

**Comment by rstm-sf** [comment]
@FlorianRappl, hello!

Try using `x-cp50227` instead of `iso-2022-ch` (see [doc/win32](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers) or [src/corefx](https://github.com/dotnet/corefx/blob/cf28b7896a762f71c990a5896a160a4138d833c9/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs#L342))

**Comment by IgorHoruzha** [comment]
It can help  you if your real encoding is UTF-8.
Work for me.
 ```
   byte[] bytes = Encoding.UTF8.GetBytes(candToMod.Value);
   string myString = Encoding.UTF8.GetString(bytes); 
```

**Comment by firecrauter** [comment]
> @FlorianRappl, hello!
> 
> Try using `x-cp50227` instead of `iso-2022-ch` (see [doc/win32](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers) or [src/corefx](https://github.com/dotnet/corefx/blob/cf28b7896a762f71c990a5896a160a4138d833c9/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs#L342))

So, what is the solution?.
