### ISSUE TITLE
HasChilds to HasChildren ?

### ISSUE THREAD

**Issue by mediabuff** [AngleSharp/AngleSharp#33]
Small grammatical ? Thanks

**Comment by FlorianRappl** [comment]
Makes sense. However, I did that on purpose. The original naming is "hasChildNodes". Obviously that is a little too verbose, but naming it "hasChildren" may be confused with the "children" property of "IElement" that is subset from "childNodes" that is specified by "INode". 

So yeah, renaming it makes sense, but I fear that some people may be confused. What is your opinion, how can this confusion be avoided?

**Comment by mediabuff** [comment]
I may still vote for hasChildNodes. hasChilds really doesn't rhyme.

**Comment by FlorianRappl** [comment]
Let's go with the standard one then!

**Comment by jogibear9988** [comment]
haschildnodes is also used on xmlelement
