### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by flagbug** [AngleSharp/AngleSharp#336]
Hey there, awesome library!

I was wondering if there is some kind of "strict mode" that I can enable in AngleSharp, i.e throw on invalid HTML elements, like the following snippet.

Let's take the following HTML snippet:

```
<!DOCTYPE html>
<html>
<body>
    <div myAttribute="blabla>123</div>
</body>
</html>
```

AngleSharp will parse this happiliy (and I guess it should, according to the HTML specification), even though the last quotation mark in `myAttribute="blabla` is missing, but I want the parser to thow/give me an indication that the HTML is malformed.

Thoughts?

**Comment by FlorianRappl** [comment]
Thanks a lot! You are right, AngleSharp follows the spec. and does not throw any exception here. However, AngleSharp does invoke events indicating errors (and warnings).

I guess we can extend the parser with another option that essentially is called `IsStrictMode` (normally set to `false`). If enabled the parser will throw exceptions instead of publishing events.

I am not sure yet if this feature would make it in v0.9.7 (the list is quite long and I want to get v0.9.7 out earlier than with v0.9.6), but I'll put in v0.9.8 for the moment with the possibility of having it in v0.9.7.

How does that sound?

**Comment by flagbug** [comment]
> However, AngleSharp does invoke events indicating errors (and warnings).

Ha, I didn't know about that, awesome!

> I guess we can extend the parser with another option that essentially is called IsStrictMode (normally set to false). If enabled the parser will throw exceptions instead of publishing events.

Yes, this is exactly how I'd imagine it, great! :smile:

**Comment by flagbug** [comment]
@FlorianRappl I'm currently trying to use the `Error` and `Invalid` events to detect HTML errors, but none of them fire. Any ideas how to set this up correctly?

**Comment by FlorianRappl** [comment]
You can find an example in the test code base (_AngleSharp.Core.Tests/Library/Error.cs_). Generally, you'll use the `IBrowsingContext` and the `ParseError` event.

``` cs
var context = BrowsingContext.New(Configuration.Default);
context.ParseError += (s, ev) => HandleError(ev as HtmlErrorEvent);
var document = await context.OpenAsync(res => res.Content("..."));
```

This should give you the main idea. Let me know if something's unclear or not working properly.

**Comment by flagbug** [comment]
@FlorianRappl I'm doing the following:

``` csharp
var parser = new HtmlParser();
parser.Context.ParseError += (sender, e) =>
{
    // Breakpoint here
};

this.document = await parser.ParseAsync(theHtml);
```

Am I doing this wrong? Do I have to use `BrowsingContext.New`?

**Comment by FlorianRappl** [comment]
No, but I would actually rarely use the `HtmlParser` directly. This way you are implicitly creating a new context, just to use it.

**Comment by flagbug** [comment]
> No, but I would actually rarely use the HtmlParser

Huh, can you expand on this? I just wanted to parse some HTML, so `HtmlParser` seemed like the obvious choice to me :smile:

**Comment by FlorianRappl** [comment]
The `BrowsingContext` is the obvious choice as it is located in the root namespace. As you can see from your little code the parser implicitly created a context, i.e., the context _is_ required - no matter what you do.

By using the `HtmlParser` front-end, you'll have a little bit more control on parsing HTML, however, less control over interpreting websites. In the usual case you'll want the latter, as most HTML is downloaded from the web in form of websites. If its already available in form of a string and you don't want the full dynamic DOM you are fine with the parser.

Most examples use the `BrowsingContext` to parse HTML - hence I believe that this choice is more straight forward ...

**Comment by flagbug** [comment]
So, just to clarify my use-case here: I'm not loading any website, I'm loading some HTML that I've created in our system, that we use as a custom data structure. Now this may sound strange, but it actually makes sense for us.

What I'm doing, is reading a string that I receive, and validating that it conforms an expected format that we have (it can only contain specific tags, in a specific order), does that make sense to you?

I just looked at the `BrowsingContext.OpenAsync` method, but it seems to expect to load something from the network, but I want to just load a string, which is why I used the `HtmlParser`

**Comment by FlorianRappl** [comment]
Yes, sure - makes sense. BTW: The `OpenAsync` has a lot of overloads and can be used to pseudo-load a website from an available HTML string. Here the code looks similar to

``` cs
var document = await context.OpenAsync(res => 
    res.Content("<div>my html</div>").Address("http://localhost"));
```

Note: The `Address` is not required, but is only used to illustrate the possibilities of this overload. Essentially, we are mocking the response of an HTTP request.

This may be too much for your scenario, but knowing this overload could be useful in the future.

**Comment by FlorianRappl** [comment]
See PR #372.
