### ISSUE TITLE
Finding all Rules that match a selector - useful additon

### ISSUE THREAD

**Issue by mediabuff** [AngleSharp/AngleSharp#34]
<pre>
namespace AngleSharp.Extensions
{
    using System;
    using System.Linq;
    using AngleSharp.DOM.Css;
    using AngleSharp.DOM;
    using System.Collections.Generic;
    public static class QueryExtensionsEx
    {
        public static List<ICssRule> QueryRulesAll(this IDocument document, ISelector selector = null)
        {
            var result = new List<ICssRule>();

            document.RulesIterator((CSSRuleList rules) =>
            {
                foreach (var rule in rules.OfType<ICssRule>())
                {
                    var cssStyleRule = rule as ICssStyleRule;
                    if (selector == null || (cssStyleRule != null && cssStyleRule.Selector.Text == selector.Text))
                        result.Add(rule);
                }
                return true;
            });

            return result;
        }
    }
}
</pre>

<pre>
internal static bool RulesIterator(this IDocument document, Func<CSSRuleList, bool> func)
        {
            var stylesheets = document.Head.Children.OfType<IHtmlLinkElement>().Where(hle => hle.Sheet != null).Select(hle => hle.Sheet).Concat(document.StyleSheets);
            foreach (var stylesheet in stylesheets)
            {
                var sheet = stylesheet as CSSStyleSheet;

                if (sheet != null && !stylesheet.IsDisabled)
                {
                    var rules = (CSSRuleList)sheet.Rules;
                    var continueIterate = func(rules);
                    if (!continueIterate)
                        return false;
                }
            }
            return true;
        }
</pre>

**Comment by mediabuff** [comment]
<pre>
 public interface ICssStyleRule : ICssRule
    {
     ....
   ISelector Selector { get; }
    }
</pre>

**Comment by FlorianRappl** [comment]
So I expose the ISelector again (makes sense anyway, as ISelector is also public) and I added two extension methods for the IStyleSheetList objects. I think having extension on these kinds of objects is in fact useful.
