### ISSUE TITLE
HtmlMarkupFormatter doesn't write all attributes properly

### ISSUE THREAD

**Issue by jcarrenog** [AngleSharp/AngleSharp#348]
When I want to serialize an element, the underlying HtmlMarkupFormatter transforms any "&" characters contained in attributes into "&amp;amp;"

Example: 

```
    var btn = document.CreateElement("a");
    btn.InnerHtml = "Test";
    btn.SetAttribute("href", "http://google.com?param=param&q=test");
    var html = btn.OuterHtml; // <-- http://google.com?param=param&amp;q=test
```

Digging into the code, I've found this in HtmlMarkupFormatter.cs, line 118

```
String IMarkupFormatter.Attribute(IAttr attribute)
...
    for (var i = 0; i < value.Length; i++)
    {
        switch (value[i])
        {
            case Symbols.Ampersand: temp.Append("&amp;"); break;
            case Symbols.NoBreakSpace: temp.Append("&nbsp;"); break;
            case Symbols.DoubleQuote: temp.Append("&quot;"); break;
            default: temp.Append(value[i]); break;
        }
    }

```

I think that, apart from the double quote, the rest of symbols are all valid into an attribute value.

**Comment by FlorianRappl** [comment]
This is by [specification](https://www.w3.org/TR/html5/single-page.html#serializing-html-fragments), see the [string escaping](https://www.w3.org/TR/html5/single-page.html#escapingString) that needs to be applied on attribute values..

**Comment by jcarrenog** [comment]
You are right. I haven't noticed that any browser behaves this way. 

Thank you for your response!
