### ISSUE TITLE
Add "monoandroid" and "monotouch" to the nuspec, otherwise AngleSharp can't be installed on Xamarin

### ISSUE THREAD

**Issue by flagbug** [AngleSharp/AngleSharp#349]
NuGet will try to install the "dotnet" or "netstandard" target into Xamarin Android and iOS projects, but since the dependencies listed there aren't compatible, the install fails

**Comment by FlorianRappl** [comment]
In what form? I mean, please fill a PR with the desired format - since I can't test on the platforms I would appreciate a PR from somebody with knowledge and desire to use it.

**Comment by flagbug** [comment]
It should work by just adding `+monoandroid+monotouch" to https://github.com/AngleSharp/AngleSharp/blob/dc85fd5f6329647b2a3577c57de90f5ff68f23a4/src/AngleSharp.nuspec#L36, I didn't submit a PR because I'm not very familiar with you CI script and didn't want to break things

**Comment by FlorianRappl** [comment]
Don't worry about breaking things. In such a case I will usually just ask to provide yet another commit in the PR; usually works fine.

Back to the subject, yes I could do that (but I have to test it first), however, this all sounds rather like a bug in Xamarin - right? I mean if it is not compatible with `netstandard` or `dotnet` it shouldn't prefer it over `net45`. The listed dependencies are all standard. In fact they are included in the `net45` (the PCL target is fully compatible with the `dotnet` target).

Overall this issue (and the proposed fix) may be strongly related to #85.

**Comment by flagbug** [comment]
Well, if it's a bug, it lies within NuGet, and not Xamarin :smile:

The error is `Could not install package 'System.Reflection.Extensions 4.0.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v4.0.3', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.` BTW, which has a `MonoAndroid` target only since version `4.0.1-rc2-24027`

The problem is also that, since NuGet chooses `netstandard` or `dotnet` as target for Android, it installs every (empty) dependency that the target contains, which clutters the `packages.config` file.

**Comment by FlorianRappl** [comment]
Well, I am not sure who is responsible (Xamarin or Nuget). I formerly thought that it must be a bug in Nuget, however, if that really would be the case then Nuget would be a rather bad platform. Think like this: How can Nuget possibly know how framework / target xyz wants to be handled? New players come to the party every day and it should not be Nugets responsibility to handle all of them correctly. Instead, each target should resolve itself correctly.

Now I know that this is all not entirely true and Nuget plays a crucial role in the final resolution. Nevertheless, the answer to all these questions possibly lies somewhere in the middle with the responsible party (either Xamarin or Nuget) being potentially grayed out. Who knows. I think we can agree that the system is not behaving well in this scenario.

In the `devel` branch a more recent version of the nuspec file is used. Here you'll also see an update to the references (not v4.0.0 any more).

**Comment by FlorianRappl** [comment]
Thanks for the PR #350! Much appreciated :+1:.

**Comment by flagbug** [comment]
@FlorianRappl By the way, I just noticed:

> In the devel branch a more recent version of the nuspec file is used. Here you'll also see an update to the references (not v4.0.0 any more).

The problem with the new dependencies is, that they are prerelease NuGet packages, meaning that AngleSharp would also need to be a prerelease package in order to use them, otherwise NuGet will complain with the following message: `A stable release of a package should not have on a prerelease dependency. Either modify the version spec of dependency "
System.Collections [4.0.11-rc2-24027, )" or update the version field.`

**Comment by FlorianRappl** [comment]
Yes @flagbug - you are right. Its still time before I deploy the next version, but we should figure out what to do about it. The `4.0.10` versions seem to be stable releases.

Right now - as far as I can see it - the whole state of .NET Core is more fragile than ever. For instance even the project.json is again a thing of the past. I really want to provide support here, but this target is changing too frequently and without control.

It's still acceptable since AngleSharp is also going through some changes and evolves until v1, but v1 is definitely happening in the next couple of months and I would love to have something 100% stable also on the NuGet side.

**Comment by flagbug** [comment]
I'd just depend on the stable packages for now. If the consumer of this library needs a higher version, they can still upgrade it manually in their app.

**Comment by FlorianRappl** [comment]
Agreed - I will change them to v4.0.10.
