### ISSUE TITLE
Renew CSS selectors

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#352]
The CSS selectors - as they are currently - are limited.

For one they can be only constructed internally, thus also limiting the extensibility. This has been addressed somehow, however, now we have some factories and no uniform standard. Also the factories as they are cannot cover all cases.

One example is #347. The `:scope` requires an additional argument being used (what is current scope?) in construction. This, however, is not given. Only a `string` can be passed to the selector "constructor", which - in fact - does not do any constructing but rather just "selects" the right selector (pun intended).

It was decided that this topic goes hand in hand with #146 and will be addressed in v0.9.8.

**Comment by FlorianRappl** [comment]
With the renewed way of constructing selectors `:scope` from #347 will be finished (currently set to be equivalent to `:root`).

For specification, see [MDN](https://developer.mozilla.org/de/docs/Web/CSS/:scope) and [W3C Selector L4](https://drafts.csswg.org/selectors-4/#the-scope-pseudo).

**Comment by atifaziz** [comment]
> The :scope requires an additional argument being used (what is current scope?) in construction. This, however, is not given. Only a string can be passed to the selector "constructor"

I believe the `:scope` is defined by the element on which, for example, [`querySelectorAll`](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll) is being called.

**Comment by FlorianRappl** [comment]
Yes - that is the mentioned argument. It is called `context`. But the `context` could be also given implicitly, e.g., if the selector is part of a sheet that comes from a `style` element with the `scoped` attribute being set. In this case the `style`s parent is the `context`.

**Comment by atifaziz** [comment]
Understood. I was only coming from the angle of using CSS selectors as a method for querying and selecting DOM elements.

**Comment by FlorianRappl** [comment]
Essentially done (see PR #487). The rest will coupled to / handled in the `css-extension` branch.
