### ISSUE TITLE
Unable to install AngleSharp into a Xamarin forms shared project

### ISSUE THREAD

**Issue by pmoran1947** [AngleSharp/AngleSharp#364]
I am using 0.9.6 version of AngleSharp.
I tried to install AngleSharp into a Xamarin forms shared project. I found it would not install into either the IOS or the Android projects with the failure

```
Package 'System.Reflection.Extensions.4.0.0 : System.Reflection [4.0.0, ), System.Runtime [4.0.0, )' does not exist in project 'CelticPools.Droid'
```

It is OK in a PCL based solution of the same project.

**Comment by FlorianRappl** [comment]
I think this is an old issue (see #85, #349 with PR #350). It's a little bit strange that it still does not work properly. That being said: Can you give more insights on the version of Xamarin you are using? That could potentially be helpful.

Generally, I hope that someone with more experience / knowledge in Xamarin is able to pick this up. I fear I am not able to come up with a good solution here.

**Comment by pmoran1947** [comment]
I am using Xamarin forms version 2.3.0107. The strange thing is that both the shared and the PCL version are referencing the same .NET framework implementation. MonoAndroid V1.0 and Xamarin.IOS V1.0.

**Comment by jgold6** [comment]
Hi, 

I'm from Xamarin support. It seems that, in Visual Studio only (seems to work in Xamarin Studio [Mac])  that AngleSharp version .0.9.5 and 0.9.6 won't install into Xamarin.Android or Xamarin.iOS projects. 0.8.9 - 0.9.4 install as expected. And this is true for either a Xamarin Forms PCL solution or Xamarin Forms Shared solution. 

I would think the PR for #350 would resolve this?

**Comment by FlorianRappl** [comment]
Hi @jgold6 - thanks for your remark. I also thought this would help, but apparently it didn't. Is there anything else we can do (i.e., what improvements do you see to the Nuget package)?

Any help is highly welcome. Thanks!

**Comment by jgold6** [comment]
Unfortunately I am no NuGet expert, I was just reporting what I found as the customer who reported this issue also wrote in to Xamarin Support. I would think you can see what differences there are between the working version and non-working versions and what might affect the ability to add the package to Xamarin,Android and Xamarin.iOS projects. 

Note also that this works in Xamarin Studio, i.e. I can install AngleSharp versions 0.9.5 and 0.9.6 into an Xamarin Android or Xamarin iOS project in Xamarin Studio on a Mac.

**Comment by FlorianRappl** [comment]
Thanks for the clarification @jgold6 - much appreciated. I will try to resolve the issue!

**Comment by genie137** [comment]
It works for me, I use Windows Visual Studio with AngleSharp v0.9.9 and Xamarin Forms 2.3.3.168 . I am targeting Shared, Droid, iOS  and UWP. I can provide you with more info if needed.

**Comment by FlorianRappl** [comment]
Thanks for the info @genie137 - if it works in a standard setup (sounds that way) I guess we can close this issue, right?

**Comment by FlorianRappl** [comment]
It seems like this works now, see #617 (obviously successfully installed). If this is a wrong assumption then please notify me!
