### ISSUE TITLE
Specifying an User-Agent

### ISSUE THREAD

**Issue by tallesl** [AngleSharp/AngleSharp#367]
How do I set an User-Agent?

I found this snippet on an [old issue](https://github.com/AngleSharp/AngleSharp/issues/16#issuecomment-29034435), but looks like the library has changed in the meantime:

``` cs
var headers = new Dictionary<string, string>();
headers.Add("User-Agent", "Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3");
Configuration.UseDefaultHttpRequester = true;
Configuration.GetHttpRequester().DefaultHeaders = headers;
```

**Comment by FlorianRappl** [comment]
Indeed, the library has changed, but the essential mechanism is the same: The user-agent is something that is controlled by the particular requester. 

In the simplest case you could change it as follows:

``` cs
var requester = new HttpRequester();
requester.Headers["User-Agent"] = "Whatever you like";
var configuration = Configuration.Default.WithDefaultLoader(requesters: new [] { requester });
// etc.
```

You could, of course, also implement your own `IRequester` variant for http(s) requests.

Hope this helps!

**Comment by tallesl** [comment]
Thanks for answering, appreciated.

Also, kudos for the library, it's been a pleasure using it so far.

**Comment by FlorianRappl** [comment]
Thanks! I'm glad I could help. I hope to finish the latest release soon (it's way overdue) and then a far more detailed documentation is on my todo list!

In the meantime please ask questions; they give me hints where documentation is lacking and the API could be more clear.

**Comment by Rodrobi** [comment]
I am trying to logon to Schwab.com so (hopefully) I can scrape data off a couple pages on their site.

Every time I logon with SubmitAsync, I get “invalid User name or Password.   I know what I am passing, is correct. As result, I thought it was due to a missing header.  

When I use the following code to add the header, I get a compile error.   Can you tell me what I’m doing wrong?

    var requester = new DefaultHttpRequester();
    requester.Headers["User-Agent"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0";

    var context = BrowsingContext.New(Configuration.Default.WithDefaultLoader(requesters: new[] { requester }));
            

Error	CS1739	The best overload for 'WithDefaultLoader' does not have a parameter named 'requesters'

**Comment by mbpakalin** [comment]
@Rodrobi i have the same problem. Didnt find any solution to this :/

**Comment by FlorianRappl** [comment]
@mbpakalin see #816 for @Rodrobi thread and answer. Hope that helps!

**Comment by mbpakalin** [comment]
@FlorianRappl Thanks so much. I saw the example on #816 and it solved my problem :)
