### ISSUE TITLE
Retrieving HTML Comments

### ISSUE THREAD

**Issue by psarno** [AngleSharp/AngleSharp#377]
I am using AngleSharp v0.9.7.21214 and I need to get HTML comment nodes in the parsed document.

I see the comments when I check the InnerHtml property of a AngleSharp.Dom.Element object during parsing.

However, querying the document for the only type that I can see exists for comments, IComment, returns no results.

The same code is working properly for links (anchor elements) via the following:

> document.QuerySelectorAll(selector).OfType< IHtmlAnchorElement >();

If I change this to:

> document.QuerySelectorAll(selector).OfType< IComment >();

I get back nothing.

I don't see it parsing the HTML comments into nodes in the debugger, but I do see them in the InnerHtml.

Is this possibly due to a malformed document issue?   Or something I need to specify in the configuration?

**Comment by FlorianRappl** [comment]
A comment is not an element. You can only query elements! So its not a malformed document or something else; its the expected behavior.

If you need the comments you can either iterate the tree yourself, or use a treewalker. For some examples, see https://stackoverflow.com/questions/13363946/how-do-i-get-an-html-comment-with-javascript. Yes, the one uses JavaScript, but AngleSharp also offers a nodeiterator with the same interface. Also the DOM structure is the same.

Hope this helps!

**Comment by psarno** [comment]
Understood about comments not being elements.  

However, I see the example project for AngleSharp does create the TreeView (which includes the comments) by casting an IElement to an INode, and then checking on that.

> if(node is IElement)
>                 return Create((IElement)node);

Is this the correct way I should handle this?  A comment may not be "an element", but it is being cast directly from an element interface, to a node interface, and being checked as such:

`(node is IComment)`

So I'm still a bit confused on that part.  Is there a way to query this easily without a custom walker, such as with LINQ?

**Comment by FlorianRappl** [comment]
An `IElement` will never be an `IComment`, but an `INode` may be an `IComment`.

Its very simple: Every element is a node, but not every node is an element. Same holds for comments. Every comment is a node, but not every node is a comment.

I think the following call solves your problem:

``` cs
var allComments = document.Descendents<IComment>();
```

Its an extension method that essentially gets the `ChildNodes` property recursively. Works on any `INode`. The generic is a handy wrapper to implicitly call the `OfType<T>` LINQ extension method.

**If you like / use AngleSharp consider starring it.**

**Comment by psarno** [comment]
Thanks again I get the idea regarding nodes and elements.

Your code does work, however I need the absolute most performant case in this situation.

At the point I need to pull the comments, I already have a particular section of the page I'm interested in, which I have retrieved via:

`var elements = document.QuerySelectorAll(selector);`

Obviously, `QuerySelectorAll`is returning to me a collection of `IElement`objects, so that would not include the comments (node != element).

Is there any way to still get the comments from this step   Or are these excluded by the fact they are not elements, and I have to do this recursively from the document root?

I will perf. test this, as I am guessing the document has already been parsed and querying the in-memory document tree may not be any issue compared to the initial parse.

I was hoping if I already had a section that was nested 10+ elements down that I was interested in, I could work off that fragment.

This is now just a performance question.   I need all `IHtmlAnchorElement`**and** all nodes of `IComment`in a section of the page that I can get via a CSS selector.

Oh, and it's definitely starred. :)

Thanks!

**Comment by FlorianRappl** [comment]
One way to deal with your scenario is to test all descendants against a particular selector. Taking the selector as a string would be devastating, but you could "compile" it once to an `ISelector` instance and use it with the `Match` method.

So much to the general case. Now if you already have the sections via the selector, e.g.,

``` cs
foreach (var section in document.QuerySelectorAll(selector))
{
  var nodes = section.Descendents().Select(node => new 
  {
    Comment = node as IComment,
    Anchor = node as IHtmlAnchorElement
  }).Where(m => m.Comment != null || m.Anchor != null).ToList();
  // Do something with nodes, e.g., comments = nodes.Where(m => m.Comment != null)
}
```

**Comment by psarno** [comment]
Thanks ... I was close, but was not bringing in the `AngleSharp.Extensions` namespace so I didn't see the `Descendents()` extension method on the `IElement` (which you did mention, so that one's on me).

The selector "compile" to ISelector is also very useful.

It doesn't like the LINQ `Where()` on the anonymous type in your code but I will work through that.

Thanks again!

**Comment by FlorianRappl** [comment]
Sorry forgot a closing parenthesis; fixed the code above!

**Comment by psarno** [comment]
You're also missing an "m." in the or :)

m => m.Comment != null || **m.**Anchor != null

We'll consider this one closed (actually, it has been for a while now)!  Thanks for the help.

**Comment by FlorianRappl** [comment]
True ;).
