### ISSUE TITLE
ID is null

### ISSUE THREAD

**Issue by mdarabi** [AngleSharp/AngleSharp#378]
Hi,

I have the following html:

`<span class="class1 class2" id="main:j_id164" style="width: 150px;">TEXT</span>`

When I use the following code to parse it, the value for ID is null.

```
        var parser = new HtmlParser();
        var document = parser.Parse(html);
        var element = document.DocumentElement;
```

I know the value of ID is not a valid string but still it should be parsed into element's ID field.

Thank you for your great library.

**Comment by mdarabi** [comment]
Also It does not parse classes!

**Comment by FlorianRappl** [comment]
Hm please write down the full code (MWE) you are using, then we can discuss. The `element` in your case will _always_ be an element of type `html` (the "root"); this is - I guess - not your intention. So I assume you are probably looking at the wrong element.

**Comment by mdarabi** [comment]
Thanks for quick response.
I do not have any more code than what I originally posted. I read the Id of the element as follow:

            if (!String.IsNullOrEmpty(element.Id))
                el.Id = element.Id;

**Comment by mdarabi** [comment]
Thanks for quick response. If the first element is always root ("html") then everything make sense. Sorry for my post. Feel free to remove it as long as it is not a problem.

**Comment by FlorianRappl** [comment]
In such a case always try in the browser; you should see _exactly_ the same behavior (minus JavaScript things if applicable). The HTML5 specification is written in such a way to always guarantee a proper HTML structure, i.e., it should always look like

``` plain
html
  head
  body
    <content>
```

I'll close it as a question / invalid then! Thanks for your patience.
