### ISSUE TITLE
Can we use BrowsingContext to get Images?

### ISSUE THREAD

**Issue by t123yh** [AngleSharp/AngleSharp#379]
I want to get a captcha using the same context I used to get the page (requires cookies to be kept). Is that possible? Or I have to use C# HttpRequest to implement it?

**Comment by FlorianRappl** [comment]
Yes of course its possible, just active the download of resources (by default only documents are downloaded from the requester).

``` cs
var config = Configuration.Default.WithDefaultLoader(loader =>loader.IsResourceLoadingEnabled = true);
// use this config
```

Hope this helps!

**Comment by t123yh** [comment]
How can I get binary of an image? For example I want to get `http://xxx.xxx/verifycode.php` (MIME: image/gif), how do I get a byte[] for that gif instead of decoded string?

**Comment by FlorianRappl** [comment]
The following code is an example of what you want to achieve (coded in LINQPad): 

``` cs
void Main()
{
    var imageLoaderService = new PlainImageResourceService();
    var configuration = Configuration.Default.
            WithDefaultLoader(m => m.IsResourceLoadingEnabled = true).
            With(imageLoaderService);
    var context = BrowsingContext.New(configuration);
    var document = context.OpenAsync(res => 
            res.Content("<img src='https://static1.squarespace.com/static/52a05cf6e4b03ec9dbc58f7d/52a05e5be4b0bdf80ef886d6/54ddd59ee4b0dc86d09f357f/1430902457710/?format=20w'>")).Result;
}

sealed class PlainImageResourceService : IResourceService<IImageInfo>
{
    public Boolean SupportsType(String type)
    {
        return type == "image/png";
    }

    public async Task<IImageInfo> CreateAsync(IResponse response, CancellationToken token)
    {
        var documents = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
        var target = Path.Combine(documents, "foo.png");

        using (var fs = File.Create(target))
        {
            await response.Content.CopyToAsync(fs);
        }

        return new ImageInfo { Source = response.Address, Width = 0, Height = 0 };
    }
}

sealed class ImageInfo : IImageInfo
{
    public Int32 Width { get; set; }

    public Int32 Height { get; set; }

    public Url Source { get; set; }
}
```

This does something (here: saving the image) _automatically_ with the given response. More directly, you could disable automatic resource downloading and perform the download manual for the images you are interested in.

The shown approach works nice if you want to apply it to _any_ image in the document (or to images restricted to a certain URL), but works terrible if you only want to have the automatic download for one specific image element (as the element is currently not delivered).

Hope this helps!
