### ISSUE TITLE
QuerySelector Id canot start with number?

### ISSUE THREAD

**Issue by hyq1860** [AngleSharp/AngleSharp#384]
my code is 
var parser = new HtmlParser();
var document= parser.Parse(firstHtml);
document.QuerySelectorAll("#1801_cxda_tab1_goid")
it throw 
The string did not match the expected pattern.
AngleSharp.Dom.DomException
Id canot start with number?

**Comment by FlorianRappl** [comment]
Yes, the provided id is invalid. See: http://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors.

Have you tried it in _any_ browser first?

![image](https://cloud.githubusercontent.com/assets/1766191/17642858/da15463e-6156-11e6-9d0d-11e75325a39a.png)

Hope this helps.
