### ISSUE TITLE
OpenAsync only sending first known cookie from CookieContainer

### ISSUE THREAD

**Issue by johnhargrove** [AngleSharp/AngleSharp#385]
I believe this issue has existed in the past (#274 appears to be the same issue but was apparently fixed and closed.)

My scenario is this:
1. Fetch a login page (GET)
2. Submit the form with credentials (POST) 
3. A bunch of cookies get set upon successful authentication. The `CookieContainer` associated with the `MemoryCookieProvider` sees all 8 of them.
4. I then attempt to re-use the same `BrowsingContext` via `OpenAsync`, to hit a URL requiring the various auth cookies.
5. The server gives me a 401, because only the first of the 8 cookies are showing up in the HTTP request.

I believe this is a bug caused by re-creating the `CookieContainer` for each `RequestState` object in `HttpRequester`. Basically, the cookie header is being retrieved from the BrowsingContext's current ICookieProvider, which ultimately references the underlying `CookieContainer`. The result of that is passed back into the new `CookieContainer` (via the cookie header) used on the `WebRequest` without accounting for the bug in `CookieContainer` (the whole ; vs , thing mentioned in #274).

Here's the code where the cookie header is being pulled from the existing context: https://github.com/AngleSharp/AngleSharp/blob/5139da94d7dfece420c02f000b3d5729168242af/src/AngleSharp/Network/Default/DocumentLoader.cs#L45-L52

Here's where it is then being used and triggering the bug in CookieContainer:
https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Network/Default/HttpRequester.cs#L136

I have worked around the issue successfully by replacing ; with , in the RequestState constructor but it is perhaps not the greatest solution:

`_cookies.SetCookies(_http.RequestUri, cookieHeader.Replace(';',','));`

Hope this helps.

**Comment by FlorianRappl** [comment]
Yes this is a duplicate, see #368. Thanks for your detailed post though, I will cross-reference it in the mentioned issue.

**Comment by bsivanov** [comment]
@johnhargrove That was exactly the issue I was hitting. Thanks for the workaround, it works.
