### ISSUE TITLE
Any way to save source html code without replacing by symbol?

### ISSUE THREAD

**Issue by ramankarman** [AngleSharp/AngleSharp#386]
While trying to parse this html `<body><p>Ž</p><p>&#381;</p></body>`  I find that html code `&#381;` is replaced by symbol, i.e. by `Ž`. Is it a bug? How can I save the "source" html?

<img width="620" alt="screenshot_24" src="https://cloud.githubusercontent.com/assets/2933194/17791021/cfc05ea4-65a1-11e6-93eb-10e4a42852b0.png">

**Comment by FlorianRappl** [comment]
This is by the standard (please try first in any evergreen browser). The source HTML is still transported (but unfortunately not marked as `public` - I think I can change this).
