### ISSUE TITLE
Styles from external sheet(s) not being applied to element

### ISSUE THREAD

**Issue by csmorley** [AngleSharp/AngleSharp#388]
I am trying to make a scraper that finds all images used on a site (both explicity via the img tag, and also via CSS styles using background-image).

However i cant see that any styles are applied as i step through the elements of the DOM.

Any ideas please, or are my expectations wrong? Any way that i can have the style sheets apply the styles to the DOM as i traverse each element?

![titleblock-inner](https://cloud.githubusercontent.com/assets/5579733/18029260/433d8d44-6ca4-11e6-8d9a-c6eca23fea23.png)
![zero-styles](https://cloud.githubusercontent.com/assets/5579733/18029261/4362cd66-6ca4-11e6-8e0f-a9906870f040.png)

**Comment by FlorianRappl** [comment]
The two things you compare are not the same. You compare the debugger view of the browser with the `Style` property of an element. The former shows the _computed_ style for an element, the latter the CSS declaration representation of the `style` attribute.

AngleSharp has a way to compute the style of an element (which will consider the external style sheets), but I would call this an experimental technology and I am not sure if it meets your requirements / demands. It is attached to the `IWindow` of the `IDocument` instance (`GetComputedStyle`).

Hope this helps!

**Comment by csmorley** [comment]
`element.ComputeCurrentStyle().BackgroundImage.ToLower();` works perfectly thank you.

Image data is downloaded (when IsResourceLoadingEnabled = true), I presume is setting image data with the downloaded contents as a byte array.

Is there any way to have the document load the image from the URL and set the background-image as an array of bytes?

Sorry if a silly question, basically trying to make a profiler to see how long a site takes to load (including img src elements, and background-image via css).

**Comment by FlorianRappl** [comment]
Glad that this works fine for your use case.

Currently, AngleSharp does not come with any option to load resources from CSS stylesheets. However, this is certainly on the agenda (and will happen once the CSS part is split in its own library). You could - in theory - go over the CSS rules and perform the loading yourself, however, in practice the CSSOM (in its current shape) is way too bulky and complex to do that.

I have thought about some specific API improvements to handle such situations much more easily. I think once CSS is sitting in its own library and the core AngleSharp library is at v1 much more progress will happen with the CSSOM.

The issue for this is: #188.

**Comment by csmorley** [comment]
Thanks @FlorianRappl, I am now loading these images externally in a loop with the following:

```
var elementsWithBackgroundImages = new List<Tuple<IElement, string>>();

foreach (var element in _document.All)
{
    if (!IsBackgroundSetPossible(element)) continue;

    var image = element.ComputeCurrentStyle().BackgroundImage.ToLower();

    if (!image.StartsWith("url")) continue;

    image = image.TrimFromEnds(@"url(""/", @""")");

    // how to get the baseUri of the css file from which the style is obtained??
    elementsWithBackgroundImages.Add(new Tuple<IElement, string>(element, element.BaseUri + image));
}
```

Images will be relative to the CSS file from which they are referenced, if we are using an external style sheet is there any way we can get the URL of the stylesheet that the element gets its styles from? 
`element.BaseUri` will point to the document base, not the style sheet - a property like `element.Style.BackgroundImage.StyleSheetUri` would be ideal.

So I started hacking the source and I can get the owning stylesheet of the rule in `WindowExtension.cs` with:

```
static class WindowExtensionsEx
{
    static IEnumerable<CssStyleRule> SortBySpecifity(this IEnumerable<CssStyleRule> rules, IElement element)
    {
        return rules.Where(m => m.Selector.Match(element)).OrderBy(m => m.Selector.Specifity);
    }

    public static Tuple<CssStyleDeclaration,IEnumerable<string>> ComputeCascadedStyleWithStylesheets(this StyleCollection styleCollection, IElement element)
    {
        var computedStyle = new CssStyleDeclaration();
        var rules = styleCollection.SortBySpecifity(element);
        var stylesheets = new List<string>();

        foreach (var rule in rules)
        {
            var inlineStyle = rule.Style;
            stylesheets.Add(rule.Owner.Href);
            computedStyle.SetDeclarations(inlineStyle.Declarations);
        }

        return new Tuple<CssStyleDeclaration, IEnumerable<string>>(computedStyle,stylesheets.Distinct());
    }
}

static class StyleExtensionsEx
{
    public static Tuple<CssStyleDeclaration,IEnumerable<string>> ComputeDeclarationsWithStylesheets(this StyleCollection rules, IElement element, String pseudoSelector = null)
    {
        var computedStyle = new CssStyleDeclaration();
        var pseudoElement = PseudoElement.Create(element, pseudoSelector);

        if (pseudoElement != null)
        {
            element = pseudoElement;
        }

        var result = rules.ComputeCascadedStyleWithStylesheets(element);

        computedStyle.SetDeclarations(result.Item1.Declarations);
        var htmlElement = element as IHtmlElement;

        if (htmlElement != null)
        {
            var declarations = htmlElement.Style.OfType<CssProperty>();
            computedStyle.SetDeclarations(declarations);
        }

        var nodes = element.GetAncestors().OfType<IElement>();

        foreach (var node in nodes)
        {
            var style = rules.ComputeCascadedStyle(node);
            computedStyle.UpdateDeclarations(style.Declarations);
        }

        return new Tuple<CssStyleDeclaration, IEnumerable<string>>(computedStyle,result.Item2);
    }
}

// inside Window.cs is sealed so had to edit directly the source and add the below, add method to IWindow also
public Tuple<ICssStyleDeclaration, IEnumerable<string>> GetComputedStyleWithStylesheets(IElement element, String pseudo = null)
{
    var styleCollection = this.GetStyleCollection();
    var result = styleCollection.ComputeDeclarationsWithStylesheets(element, pseudo);
    return new Tuple<ICssStyleDeclaration, IEnumerable<string>>((ICssStyleDeclaration)result.Item1, result.Item2);
}
```

But will have to do much more hacking to make this work (i will break more than i fix!)... the above seems to work but probably bug ridden.

![list](https://cloud.githubusercontent.com/assets/5579733/18107664/ef83b8e0-6f19-11e6-812a-ea9b95c6b23a.png)

Assuming I haven't just reinvented the wheel, any pointers much appreciated to get the output, pretty much like how Chrome shows its classes and related style sheets:

![css urls](https://cloud.githubusercontent.com/assets/5579733/18106132/65b19692-6f13-11e6-99f3-2a57bd4ca732.png)

**Comment by FlorianRappl** [comment]
Yeah good point. We should raise an issue for each of the improvements (e.g., provide the location in the stylesheet instance) to indicate the work to be done / progress.

**Comment by csmorley** [comment]
Ok cool, if that didn't exist before it may now with the above (the test code does pull across the stylesheets with which the element styles are derived - but its not particularly fast), albeit don't fully understand the ComputeDeclarations and cascading so treat with caution. Once the stylesheet is known, the image can then be downloaded relative to the stylesheet url. Will take a look again after sleep/coffee!

**Comment by csmorley** [comment]
The attached zip (that needs to be put within the core, i couldn't extend externally due to sealed and non-public classes) works for me for images and giving a breakdown of which styles came from which stylesheets.

```
foreach (var element in _document.All)
{
    if (element.ClassList.Length == 0 && string.IsNullOrEmpty(element.Id)) continue;

    // todo: remember classes which have no backgrounds (after style is calculated), and skip immediately if encountered

    var name = element.TagName.ToLower();
    if name != "head" && name != "script" && name != "link" && name != "meta" continue;

    var style = element.ComputeCurrentStyleWithStylesheet();
    var image = style.CompositeStyleDeclaration.BackgroundImage;

    if (!image.StartsWith("url")) continue; // todo: remember class to prevent rendering in future

    Console.WriteLine(image);
    foreach (var component in style.Components)
    {
         Console.WriteLine("\t" + component.CssStyleDeclaration.CssText);
         Console.WriteLine("\t" + component.Url);
    }
}
```

Will add some helper functions so that if an image url uses paths changing directory (..) so that the correct full path to image is obtained relative to stylesheet url.

Not sure if there were other ways to implement the same more simpler, seems to be enough to get around for now.

[StylesheetUrlAddon.zip](https://github.com/AngleSharp/AngleSharp/files/450968/StylesheetUrlAddon.zip)
