### ISSUE TITLE
AngleSharp forces tag placement in HEAD and BODY tags

### ISSUE THREAD

**Issue by deanebarker** [AngleSharp/AngleSharp#398]
I'm curious if this is by design or not, but AngleSharp will move tags around into `HEAD` and `BODY` tags inside the HTML document it creates. Consider this HTML fragment:

```
 <title>My Title</title>
 <p>My paragraph</p>
```

The resulting document looks like this:

```
<html>
  <head>
    <title>My Title</title>
  </head>
  <body>
    <p>My paragraph</p>
  </body>
<html>
```

Notice that document is complete, and the tags have been moved into "correct" locations, in a `HEAD` and `BODY` tag.  This means that my fragment is no longer intact inside the document.

I could do this to try and get it back:

```
string.Concat(document.Head.InnerHtml, document.Body.InnerHtml)
```

But what if my fragment was reversed, with the `TITLE` tag _after_ the `P` tag?

Clearly, AngleSharp might be correct here, but it also means that there's no way for me to get my original fragment back out (nonsensical as it might be).  If I have a situation where I have jacked-up HTML that _needs to stay jacked up_ (for whatever reason), AngleSharp won't let this happen. There are situations when we might just want AngleSharp to _parse_ without _interpreting_.

Is this by design?  Is there some other way I could get a parsed version of the original fragment back, intact?  Or is AngleSharp always going to interpret the tags in an attempt to create a valid document?

**Comment by FlorianRappl** [comment]
One of the goals of AngleSharp is to be HTML5 compliant, i.e., it follows the specification. Clearly, you did not try this out in _any_ browser as this is the behavior you would have seen.

Fragments are a different story (I think what you mean with fragments is different from the original terminology; but in order to get the behavior you want to see I guess you should have a look at what fragments are, e.g., https://dev.w3.org/html5/spec-preview/the-end.html#fragment-case) - here AngleSharp also follows the official W3C specification.

So you might want to try out fragment parsing for your needs. Otherwise, I fear what you gave AngleSharp is an _official_ document (as specified) and the parsing will always result in a _complete_ document.

**Comment by deanebarker** [comment]
Would it be possible to parse it as XML but make it as forgiving or self-correcting as HTML?  The `XmlDomBuilder` wouldn't create `HEAD` or `BODY` tags.  The problem, of course, is that I can't guarantee valid XML, since HTML is all over the place.

I tried setting `XmlParserOptions.IsSuppressingErrors` to `false`, but it still tripped over invalid tags.

**Comment by FlorianRappl** [comment]
You mean you set it to `true`? Because `false` is the default setting (and does _not_ suppress errors!).

**Comment by deanebarker** [comment]
Sorry, I meant `true`.

This still throws an exception, for example (note the invalid nesting):

```
var html = "<x><y><z>foo</y></z></x>";
var options = new XmlParserOptions()
{
    IsSuppressingErrors = true
};
var dom = new XmlParser(options).Parse(html);
```

My goal is to get to the forgiveness of the HTML parser, while not having AngleSharp form an actual HTML document -- rather, just leave the markup unchanged.

**Comment by FlorianRappl** [comment]
Hm, which version of AngleSharp are we talking about? The reason for me asking is that I think v0.9.8.0 (and previous versions) had an unnoticed bug that the options have not been considered in the synchronous XML parsing process.

Have you tried with the latest version?

**Comment by deanebarker** [comment]
It was a versioning problem. I updated the version, and it worked fine.

However, I was testing different scenarios and found that while it fixed invalid nesting and unclosed tags, it will still throw an exception on invalid entities.  For example, trying to parse this will throw an exception:

```
<x>foo&nbsp;</x>
```

However, this works fine:

```
<x>foo&amp;</x>
```

This is presumably because the entity for ampersand is expected in XML, but HTML entities are not. And an ampersand by itself will also throw an exception:

```
<x>&</x>
```

Is this a known issue?

**Comment by FlorianRappl** [comment]
It's not! Thanks for recognizing this - invalid entities (such as the `&nbsp;`, which is only defined in HTML) should be transported somehow.

I'll set it on the agenda for v0.9.9 (but I'll open a new item for it)!

**Comment by deanebarker** [comment]
Yay! I redeemed myself!

Thanks for your help on this. For now, we'll just do an ugly string replace on entities before parsing.
