### ISSUE TITLE
There is no "mark" element 

### ISSUE THREAD

**Issue by canol** [AngleSharp/AngleSharp#399]
I was doing some type safe comparisons to check the type of an element and realized that there is no IHtmlMarkElement.

http://www.w3schools.com/tags/tag_mark.asp

**Comment by FlorianRappl** [comment]
There won't be an `IHtmlMarkElement` as there is nothing distinct on the mark (and the W3C does state its just an `IHtmlElement`, see https://www.w3.org/TR/html5/text-level-semantics.html#the-mark-element).

However, currently it is not part of the factory and hence will spawn a new `IHtmlUnknownElement`, which is wrong.

So this one needs to be enhanced, thanks for spotting the issue 👍 ! I plan it for v0.9.9.

**Comment by FlorianRappl** [comment]
See PR #402.
