### ISSUE TITLE
[Question] List Redirects Using AngleSharp

### ISSUE THREAD

**Issue by greenbergjosh** [AngleSharp/AngleSharp#400]
I also posted this as a question on stackoverflow, but I thought this might be a more relevant location for the question. Please forgive me if posting this here is inappropriate. It is, very specifically, an AngleSharp question.

I have a requirement to follow a URI in the same fashion as a browser and to collect each redirect URI from the original URI to the final URI. I need to capture the complete set of intermediary URIs, not just the start and finish.

There are multiple types of redirects, 302, 30x, meta, and javascript (window.location=). I need to be able to capture and follow all types.

I have written an application using C#, HTMLAgilityPack, NReco, and PhantomJS that allows me to meet this exact requirement. However, my code is a very nice async/parallel application that effectively avoids using threads. PhantomJS, unfortunately, instantiates a process whenever I ask it to traverse a path of redirects. I have also looked at Zombie and Awesomium. However, I believe that AngleSharp/Jint may be the best solution.

I would like to asynchronously send links into my parallel workflow, and follow many links, asynchronously, in parallel, identifying their complete redirect chain. I have the parallelism working, but creating a PhantomJS process for each link is defeating the point.

I believe that the majority of the time spent following a chain of redirects is waiting for network I/O. There will, of course, be time required to parse the HTML that comes back from the request (creating a DOM), and loading the page (running the JavaScript). This is where I wish to use AngleSharp and Jint.

The code should look something like:

List&lt;Uri&gt; redirectLinks = await GetRedirectLinks(Uri startLink)

This code should not spawn a process, and preferably not even spawn a thread. It should follow the redirects, one at a time, asynchronously loading each URI, starting from startLink, until it reaches the end of the chain. (Since a redirect can be based on a timer, the definition of the end of the chain can be a page that does not redirect itself after a configurable amount of time).

Can this be done using AngleSharp/Jint? Can an expert in this technology please provide me with sample code? Specifically, the code that would be placed in the body of the GetRedirectLinks() method. Please remember that I would like to run hundreds of the GetRedirectLinks() methods simultaneously, as I am working under the assumption that the majority of the time spent following a redirect chain is spent waiting on IOCompletion - which means it is not holding a thread or process. Of course, in the case of a timed delay redirect, I imagine that the javascript delay or meta delay may not be able to be handled asynchronously, but I don't know that for certain. They are just delays, it would be lovely if they could be somehow realized as Task.Delay or some equivalent.

If the async part of my request is simply not possible, I would still be very grateful to see the AngleSharp/Jint solution to this problem as I suspect, even with multiple threads, it will greatly outperform the PhantomJS multiple process solution.

Many thanks for your kind assistance.

**Comment by FlorianRappl** [comment]
In AngleSharp you can provide your own `IRequester`, e.g., to issue requests directly. Then you have it fully in your hands.

Furthermore, you could wrap _any_ existing `IRequester` implementation, e.g., the `HttpRequester` and therefore obtain a list of all the redirects. For any redirect a request is issued to the underlying requester, easily allowing you to keep track of all the redirects.

If that is not sufficient you can also come up with your own `IResourceLoader` implementation.

(I excluded Jint completely from the answer as Jint is related to the JavaScript implementation found in AngleSharp.Scripting - this is the core library).

Hope this helps!

**Comment by greenbergjosh** [comment]
Florian,

Thank you very much for your reply and for pointing me to AngleSharp.Scripting.  I had not seen that link.  I actually found your product through your codeproject article http://www.codeproject.com/Articles/839588/AngleSharp-and-JavaScript and then I just googled AngleSharp.

I am very anxious to try what you suggested in your reply, but can you please clarify one point of confusion. You mentioned that you excluded Jint from the answer (perhaps, because I posted to the wrong area?).  I could not tell if you were also implying that I did not need Jint (or an equivalent).  I believe I would require Jint to handle the window.location.href= redirects.  Is there something in the AngleSharp library alone that will handle these redirects? I believe they require running the javascript of the page, so am I correct in assuming that I absolutely require AngleSharp.Scripting?

Thank you again for your help.

**Comment by FlorianRappl** [comment]
Yes you are correct: You need _AngleSharp.Scripting_ to include the dynamics that come with JavaScript. And here Jint comes into play. Also, as the described process of setting `location.href` will trigger the loading of a page, everything is done here.

Now the internal part comes into play, where you mentioned:

``` cs
List<Uri> redirectLinks = await GetRedirectLinks(Uri startLink)
```

And here my proposed solution would be to capture all requests via an `IRequester` wrapper. That one you have to setup by supplying it in the `WithDefaultLoader` extension method, specifying the `requesters` property (e.g., with an array containing your wrapper).

**Comment by greenbergjosh** [comment]
Florian,

Thank you very much for your reply.  You have given me a very clear path to approach the problem.  Thank you also for AngleSharp.  It is a very impressive library.

Kind Regards

**Comment by FlorianRappl** [comment]
Thanks, glad I could help 😎
