### ISSUE TITLE
Yahoo Login Page Doesn't Load Properly

### ISSUE THREAD

**Issue by greenbergjosh** [AngleSharp/AngleSharp#405]
The code below runs (no exceptions), and it properly identifies and populates the form fields, but it never results in a successful login. There is a hidden parameter called `_crumb` on the Yahoo login page.  If I navigate to the Yahoo login page with Chrome (or IE), I find the `_crumb` to be populated with a value.  If I navigate to `login.yahoo.com`, as shown in the first few lines below, with `context.OpenAsync()`, the `_crumb` is not populated with a value. 

This leads me to believe that, perhaps, there is JavaScript on the page that is not properly executing.  Is there something special that I have to do (which is normally automatically done by a browser) when loading the page?

As an aside, you will notice in the code below that I have tried both submit (presently commented) and click (the lesser solution).  Both function as I believe they should, but neither are the problem, since the very first page does not properly load (as evidenced by the missing crumb value).  Please don't let that aspect of my code be a distraction.

I am pretty much stumped.  Thank you for any help you can provide.  

``` cs
var url = Url.Create("https://login.yahoo.com/?.src=ym&.intl=us&.lang=en-US&.done=https%3A%2F%2Fmail.yahoo.com");

if (url.IsInvalid)
    throw new ArgumentException("The provided parameter does not form a valid URL.", nameof(baseUrl));

var config = Configuration.Default
    .WithDefaultLoader()
    .WithCookies()
    .WithJavaScript();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(url);
var form = document.Forms.FirstOrDefault();
var elements = form?.Elements ?? Enumerable.Empty<IHtmlElement>();
var fieldsPage1 = new Dictionary<String, String>()
{
    { "username", "xxx@yahoo.com" }
};

foreach (var element in elements.OfType<IHtmlInputElement>())
{
    var value = default(String);

    if (fieldsPage1.TryGetValue(element.Name ?? String.Empty, out value))
        element.Value = value;
}

var btn = default(IHtmlButtonElement);

foreach (var element in elements.OfType<IHtmlButtonElement>())
{
    if (element.Name == "signin") 
        btn = element as IHtmlButtonElement;
}

if (btn != null)
    btn.DoClick();

//AngleSharp.Dom.IDocument x = await form.SubmitAsync();
document = context.Active;
form = document.Forms.FirstOrDefault();
elements = form?.Elements ?? Enumerable.Empty<IHtmlElement>();

var fieldsPage2 = new Dictionary<String, String>
{
    { "passwd", "*******" }
};

foreach (var element in elements.OfType<IHtmlInputElement>())
{
    var value = default(String);

    if (fieldsPage2.TryGetValue(element.Name ?? String.Empty, out value))
        element.Value = value;
}

btn = null;

foreach (var element in elements.OfType<IHtmlButtonElement>())
{
    if (element.Name == "signin")
        btn = element as IHtmlButtonElement;
}

if (btn != null)
    btn.DoClick();

//AngleSharp.Dom.IDocument x2 = await form.SubmitAsync();
document = context.Active;

var x3 = await context.OpenAsync("https://mail.yahoo.com");
var el = x3.QuerySelector("#mail-search-btn");

int i = 1;
```

**Comment by FlorianRappl** [comment]
What I can tell you is that there are some nice extension methods available in the `AngleSharp.Extensions` namespace, which may be helpful for submitting forms.

Regarding the core of the issue, yes - after a brief look your assumption seems to be right. However, I need to perform a more extensive validation (and I do not have a Yahoo account to verify it). Hopefully I'll find the time for this today or tomorrow. I'll keep you updated.

**Comment by FlorianRappl** [comment]
So Yahoo apparently tries to make it hard for people only "downloading" the webpage. It seems that they want to receive a request as from evergreen browsers, i.e., "correct" user-agent and similar values in other request headers. Then the Yahoo login also works w/o JavaScript.
