### ISSUE TITLE
IDocument missing StatusCode property

### ISSUE THREAD

**Issue by svickers** [AngleSharp/AngleSharp#408]
Should StatusCode be included in IDocument?  It is hanging off of Document but I can't see a way to access it.  Perhaps I should be doing things differently?

`var document = await _context.OpenAsync(address);`

Just want to make sure a 200 was returned before I continue on.

**Comment by FlorianRappl** [comment]
Quite useful - I will add it in v0.9.9 (actually I had the impression / intention to add it, but apparently I forgot / did not do it).

Thanks for the suggestion.

**Comment by FlorianRappl** [comment]
Added it, see PR #415.
