### ISSUE TITLE
Some pages don't seem to have right encoding

### ISSUE THREAD

**Issue by GuerrillaCoder** [AngleSharp/AngleSharp#416]
On a few pages I have noticed this:

![wrongtext](https://cloud.githubusercontent.com/assets/11444395/18828908/e50daa0c-83d1-11e6-8aa3-e52929556001.png)

The website in question is: http://www.empireaerials.net/

Source looks OK.  Why is anglesharp getting messed up text?  Is there a better way to access the pure text version of the page?

**Comment by FlorianRappl** [comment]
I assume that this has to do with the content encoding (it is gzipped). What are the options you use? I guess throwing in _AngleSharp.Io_  with an requester implementation based on the more modern `HttpClient` may solve the problem.

**Comment by GuerrillaCoder** [comment]
I'm using `Configuration.Default.WithDefaultLoader();`

So the problem is they have enabled compression on webserver?

**Comment by FlorianRappl** [comment]
Yes, they are using compression even though the client did not send the compression capability (header: `Accept-Encoding: gzip`). In general a webserver should only send back compressed content if the client supports it (but all evergreen browsers support this).

The PCL `HttpWebRequest` does not come with options to set / allow compression (I'll try some black magic to get it working on supporting platforms), but `HttpClient` will allow you to enable this.

**Comment by GuerrillaCoder** [comment]
Thanks.  I guess I can test for content and if I don't find it have a `HttpClient" fallback.

**Comment by FlorianRappl** [comment]
Fixed in upcoming release, see PR #418.
