### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by h82258652** [AngleSharp/AngleSharp#42]
Test code is here:

```
internal class Program
{
    private const string TestUrl = @"http://www.baidu.com";
    private static readonly Regex TitleRegex = new Regex("<title>(.*?)</title>");

    private static void Main(string[] args)
    {
        var angleSharpTitle = DocumentBuilder.Html(new Uri(TestUrl, UriKind.Absolute)).Title;
        var htmlAgilityPackTitle = new HtmlWeb().Load(TestUrl).DocumentNode.SelectSingleNode("//title").InnerText;
        var webClientTitle = WebClientDownload();
    }

    private static string WebClientDownload()
    {
        return
            TitleRegex.Match((new WebClient() {Encoding = Encoding.UTF8}.DownloadString(TestUrl)))
                .Groups[1].Value;
    }
}
```

www.baidu.com is a website in China. In the test code, HtmlAgilityPack and WebClient are both correct, but AngleSharp does not, one character is not display correctly.

**Comment by FlorianRappl** [comment]
Thanks, I will look into that!

**Comment by FlorianRappl** [comment]
With what version of AngleSharp have you tried? The latest one on NuGet, a specific (maybe older) version or the latest one available here?

I used the following code:

```
const String TestUrl = @"http://www.baidu.com";
Regex TitleRegex = new Regex("<title>(.*?)</title>");

var angleSharpTitle = DocumentBuilder.Html(new Uri(TestUrl, UriKind.Absolute)).Title;
var plainTitle = TitleRegex.Match(new HttpClient().GetStringAsync(TestUrl).Result).Groups[1].Value;
```

Then I inspected the two titles (as you did, I guess). However, to me both look the same:

![image](https://cloud.githubusercontent.com/assets/1766191/5218735/3bfd757c-7650-11e4-8e40-5152a141bfd5.png)

I also compared the byte content via (e.g.)

```
Encoding.Unicode.GetBytes(plainTitle)
```

Both strings have 18 bytes and the same sequence / values (126,118,166,94,0,78,11,78,12,255,96,79,49,92,229,119,83,144). Can you re-check please? What is the title supposed to be (in bytes)?

I can only compare pictures here. For me the VS and browser generated symbols (Opera 26) look the same:

![image](https://cloud.githubusercontent.com/assets/1766191/5218821/31625c1c-7651-11e4-80db-ca9d3b35c8ff.png)

Thanks!

**Comment by h82258652** [comment]
![qq 20141128002909](https://cloud.githubusercontent.com/assets/5144550/5219702/e5b08fe2-7695-11e4-99e7-1c89dca94fd9.png)
the third character is not correct.

**Comment by FlorianRappl** [comment]
Again: Version? I can't reproduce it...

**Comment by h82258652** [comment]
I think I may be found why this error occurred.
If the response content encoding is different with the meta charset, it will occurred.
I make an example, here is the link:
https://onedrive.live.com/redir?resid=B406AF403E9168EA!13195&authkey=!AB4w4T2GQOur2XE&ithint=file%2c7z

I run it in IE11, Chrome, the title and body are no problems.
But in AngleSharp, it is wrong.
PS: I use AngleSharp version is 0.7, published at 2014-11-08.

**Comment by FlorianRappl** [comment]
I also tried the current version on NuGet. Still - I get the same for the HttpClient raw and the AngleSharp. The chosen character set is `utf-8`. What character set do you have? The only explanation I have is the local encoding start value... (therefore what document encoding has been selected for you might be an indicator in this case).

```
var document = DocumentBuilder.Html(new Uri(TestUrl, UriKind.Absolute));
var charset = document.CharacterSet;
```

Maybe this way we can catch the origin of the bug.

**Comment by h82258652** [comment]
Today, I try another test.

<pre><code>
    class Program
    {
        static void Main(string[] args)
        {
            const String TestUrl = @"http://www.baidu.com/";
            Regex TitleRegex = new Regex("<title>(.*?)</title>");
            var angleSharpTitle = DocumentBuilder.Html(new Uri(TestUrl, UriKind.Absolute), new Configuration()
            {
                Culture = new CultureInfo("en-US")
            }).Title;
            var angleSharpTitle2 = DocumentBuilder.Html(new Uri(TestUrl, UriKind.Absolute), new Configuration()
            {
                Culture = new CultureInfo("zh-CN")
            }).Title;
            var plainTitle = TitleRegex.Match(new HttpClient().GetStringAsync(TestUrl).Result).Groups[1].Value;
        }
    }
</code></pre>

en-US is right and zh-CN is wrong.
In your computer, en-US is the default culture info, but zh-CN is my computer's default culture info.
If we don't tell the DocumentBuilder which culture info it use, it will use the local culture info same with the computer, that's the reason the same codes will get different result between you and me.

and `document.CharacterSet` is utf-8 the same with you.

**Comment by FlorianRappl** [comment]
Alright, that means my guess (and the only remaining possibility) was right that the already consumed stream might be transformed wrong after the encoding changes (Windows-1252 to UTF-8 vs GB18030 to UTF-8). I can reproduce the bug now, thanks. Will be fixed soon.
