### ISSUE TITLE
Attribute API refinements

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#422]
As discussed in #419 the following additions / refinements should be made to the API:
- An extension method to clear all attributes
- Return a boolean if an attribute was indeed removed (instead of nothing)

The changes will be part of the upcoming release.

**Comment by FlorianRappl** [comment]
Implemented, see PR #424.

**Comment by JamesNK** [comment]
FYI, changing a method's return type is a breaking change

https://github.com/milkshakesoftware/PreMailer.Net/issues/130

**Comment by FlorianRappl** [comment]
Yep of course it is!
