### ISSUE TITLE
Image not in IDocument.Images collection

### ISSUE THREAD

**Issue by ushenkodmitry** [AngleSharp/AngleSharp#425]
Hello,
Document, opened with BrowsingContext from the url "http://www.businessinsider.com/sean-hannity-fires-back-at-megyn-kelly-after-she-criticizes-trump-for-only-going-on-hannitys-show-2016-10",  is missing some images. I can not find main image in the Images collection. Same for url "http://www.businessinsider.com/hurricane-matthew-south-carolina-evacuations-florida-2016-10". All of the images in text are not present in the collection.
Could you please look into this and say why?

**Comment by FlorianRappl** [comment]
Please provide some code to reproduce first. Thanks!

**Comment by ushenkodmitry** [comment]
Oh, sorry sorry, my bad. Accidentally delete this element from the DOM.
PS Thanks for the lib, use it for several months and this is the best thing that happened to me during that time!

**Comment by FlorianRappl** [comment]
It's alright - thanks for looking at it in detail. Also much welcome on the kudos - appreciated 👍
