### ISSUE TITLE
AngleSharp not always detecting forms

### ISSUE THREAD

**Issue by GuerrillaCoder** [AngleSharp/AngleSharp#429]
Sometimes AngleSharp is not getting forms for some reason but they actually exist.  

For instance on this URL `http://www.thekmn.co.uk/contact-us.html`

I am trying to get the form like:

``` c#
var config = Configuration.Default.WithDefaultLoader().WithRequesters();
var document = await BrowsingContext.New(config).OpenAsync(address);
var forms = document.QuerySelectorAll("form").OfType<IHtmlFormElement>();
```

Am I doing something wrong or should AngleSharp be detecting this?  The same code works fine on other pages.

Also on pages with multiple forms sometimes it will only find one form. 

Edit:

It works if I access `document.Forms` it seems to just be an issue when trying to use the `form` selector.

**Comment by FlorianRappl** [comment]
Seems strange to me - I will have a look into it. Which version of AngleSharp did you use?

**Comment by GuerrillaCoder** [comment]
0.9.8.1

I just noticed there is update so I'll try the update.

**Comment by FlorianRappl** [comment]
Hm, I can't really reproduce. Maybe the transmission failed in such cases. The query selectors should work without any problem and the `Forms` property is also just using the DOM with a direct query (without any magic).

The following code

``` cs
var config = Configuration.Default.WithDefaultLoader();
var document = await BrowsingContext.New(config).OpenAsync(address);
var forms = document.QuerySelectorAll("form").OfType<IHtmlFormElement>();
Console.WriteLine(forms.Count());
```

gave me "1" when used with the website you stated. I think "1" is the right result here. I used the latest version of AngleSharp to obtain this.

**Comment by FlorianRappl** [comment]
(Currently marked as "invalid", but if anything changes / you have examples where it reliable does not work then just shoot and I reopen the issue - thanks!)
