### ISSUE TITLE
HttpMessageHandler Example

### ISSUE THREAD

**Issue by GuerrillaCoder** [AngleSharp/AngleSharp#430]
I am running a process that uses AngleSharp on many threads.  It starts out really fast and then it slows down as threads start to hang and then eventually stops when all threads hang.  It seems to be hanging on getting the page.

I saw in another post you mentioned that a timeout could be specified if I pass my own implementation of HttpMessageHandler.  I setup a child class but I am not exactly sure exactly how I am supposed to override the SendAsync() method.

Are there any examples I can view?

**Comment by FlorianRappl** [comment]
This is rather something that belongs to _AngleSharp.Io_. _AngleSharp_ is a PCL and does not (cannot) use the `HttpClient`. Also be sure to always provide a MWE if you have a specific question.

Please use the appropriate repository (https://github.com/AngleSharp/AngleSharp.Io). Thanks!

**Comment by GuerrillaCoder** [comment]
Will do next time sorry.  I reorganised code to assign all variables of one page before calling the next page and now it doesn't hang so it was problem at my end.
