### ISSUE TITLE
CSS enhancement

### ISSUE THREAD

**Issue by Violante** [AngleSharp/AngleSharp#436]
Hello,
It would be very nice and usefull for futur development to have CSS3 GCPM (https://www.w3.org/TR/css-gcpm-3/) (@page, element(); running(), footnote, string-set, string...)
Thank's a lot for your work.

**Comment by FlorianRappl** [comment]
Yep, I agree.

Info here: CSS will be gone with the next version anyway. No worries - it will be continued, but in a separate library (AngleSharp.Css).

So this issue will be moved to the new repository once the new CSS library is up for a push.

**Comment by FlorianRappl** [comment]
Continued in AngleSharp.Css!
