### ISSUE TITLE
Enhancement: CSS Parent Selector

### ISSUE THREAD

**Issue by DSupuran** [AngleSharp/AngleSharp#437]
I believe it's a CSS3 selector that would be useful (and appears unsupported), to select the parent of a matched element.  Are you able to confirm if this is in the roadmap and still unavailable?

example: "a < img"
purpose: to match the <a> element that has an <img> child.

**Comment by FlorianRappl** [comment]
Unfortunately, there is no such selector. CSS Selectors L4 has a special syntax with the `:has()` selector, which is what you actually look for (`a:has(>img)`).
