### ISSUE TITLE
prevent downloading images videos audio  etc... everything (Except javascript file)

### ISSUE THREAD

**Issue by blackholeearth** [AngleSharp/AngleSharp#438]
hi
is there a way  to 
prevent downloading images videos audio  etc... everything (Except javascript file).

if there that would be super . thank you

**Comment by FlorianRappl** [comment]
These files are normally not downloaded. If you enable resource loading you can prevent downloading such files by setting a proper filter for the requester. In your case I would only let requests pass that end with ".js" (or which originate from a script element).

``` cs
var config = Configuration.Default.WithDefaultLoader(setup =>
{
    setup.Filter = req => req.Address.Href.EndsWith(".js", StringComparison.OrdinalIgnoreCase);
    setup.IsResourceLoadingEnabled = true;
});
```
