### ISSUE TITLE
Avoid string and other allocations 

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#443]
As mentioned in #442, the most important perf factor in a .net library is keeping allocations down. AngleSharp uses pooling and string builders extensively. However there are a few powerful ways to reduce or eliminate temporary string and other object creation.
- StringBuilder.ToString()` is called in several places where the result is the key in a map. This can be avoided by using a struct containing a StringBuilder and a HashCode as the key, like this:

``` C#
        /// <summary>
        /// A StringBuilder together with its hash. used for fast lookups.
        /// </summary>
        struct StringKey : IEquatable<StringKey>
        {
            public StringKey(StringBuilder sb)
            {
                this.sb = sb;
                hash = Hash.GetFNVHashCode(sb);
            }

            public StringBuilder sb;

            public int hash;

            public bool Equals(StringKey other) =>
                sb != null && other.sb != null && sb.Equals(other.sb);

            public override int GetHashCode() => hash;
        }

```

The `Hash.GetFNVHashCode()` function has been implemented in the [Roslyn](http://source.roslyn.io/#microsoft.codeanalysis/InternalUtilities/Hash.cs) codebase.
- Instead of breaking up the document into a number of small strings, a [`StringSlice`](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/StringSlice.cs) can be used. This also uses an FNV hash code. 
- Avoid `IEnumerable` and instead use Lists or other objects that have struct enumerators. `IEnumerable` is heavyweight and calls a _virtual_ `GetEnumerator()` method that allocates and returns a enumerator object. None of this is needed for foreach style enumeration in C#, because foreach is in fact pattern based; it works if the right methods are implemented, even without interfaces. `List<T>`'s GetEnumerator() method returns a struct - which is not boxed. I've used this to get rid of all implemtations of `IEnumerable` and `IEnumerable<T>` in my code base. Now I just use List<T> directly in the method signature. For custom types, I make sure that their implementation of GetEnumerator() returns a struct. (To repeat, they implement `GetEnumerator()` but not `IEnumerable` or `IEnumerable<T>`.
- Avoid implementing `IComparable<T>` and implement `IEquatable<T>` instead, for the same reason - to avoid boxing.
- Avoid yield return, which again allocates an enumerable class, an enumerator and so on. Instead pass a (pooled) list into the method, which fills it. That is, instead of 
  
  ```
  IEnumerable<T> Foo() {yield return a; yield return b; }
  ```

do this:

```
    void Foo(List<T> result) {result.Add(a); result.Add(b);} // caller pools the list
```
- Avoid Linq like the plague. I use Linq only in test code. The number of objects that linq statements allocate is prohibitive for production code, and should IMHO never be in a library. This is another learning from the Roslyn team that I took to heart. Previously I used Linq extensively - and suffered greatly as a result.
- Use structs instead of classes wherever possible and avoid boxing. This can be tricky, but can dramatically reduce the number of allocations. Structs are C#'s major improvement over Java IMHO.. Best to avoid implementing interfaces (with the exception of `IEquatable<T>`) on structs. 

All these go a long way to reducing those GCs (and those milliseconds.)

There is a tradeoff between some of these suggestions and API cleanliness, but I do think that all of these should be considered seriously. They've made a huge difference to the performance of Roslyn and to my own code.

What do you think?

**Comment by FlorianRappl** [comment]
Most string allocations aren't actually allocations, but use the interned string. As long as no benchmark is proving an optimization (e.g., the string allocations in the character references you mentioned in #442 do not contribute _at all_ to the performance - seen in benchmarks).

All of the things you mention are done by AngleSharp in essentially all the hotpaths (these are the paths that matter). So your list is nothing new to me and if no direct wins with reproducable benchmarks are provided I can't / won't do anything.

There are some possible optimizations for the parser; but none of the things you mentioned above will lead to them (again: the parser does not use LINQ or heavy allocations for most of the things). They are rather of algorithmic nature + optimized structures combined with pooling and lazy loading.
