### ISSUE TITLE
Errors in XML namespace parsing

### ISSUE THREAD

**Issue by fogzot** [AngleSharp/AngleSharp#448]
When parsing an XML document the elements don't get the correct `NamespaceUri` value for the default namespace. Also, specifying a namespace throws a parse error. Example:

``` cs
using System;
using AngleSharp;
using AngleSharp.Dom;

namespace AngleSharpTest
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            const string xml1 = @"<a t='42'><b/><c>TEXT</c></a>";
            const string xml2 = @"<a xmlns=""http://www.w3.org/1999/xhtml"" t=""42""><b/><c>TEXT</c></a>";
            const string xml3 = @"<x:a xmlns:x=""http://initd.org/ns/tesseract-1.0"" t=""42""><b/><c>TEXT</c></a>";

            var d = BrowsingContext.New().OpenAsync(req => 
                req.Content(xml1).Header("Content-Type", "text/xml")).Result;
            Console.WriteLine(d.DocumentElement.NamespaceUri);
            // Prints http://www.w3.org/XML/1998/namespace, wrong, should be null

            d = BrowsingContext.New().OpenAsync(req => 
                req.Content(xml2).Header("Content-Type", "text/xml")).Result;
            Console.WriteLine(d.DocumentElement.NamespaceUri);
            // Prints http://www.w3.org/XML/1998/namespace, wrong, should be http://www.w3.org/1999/xhtml

            d = BrowsingContext.New().OpenAsync(req => 
                req.Content(xml3).Header("Content-Type", "text/xml")).Result;
            Console.WriteLine(d.DocumentElement.NamespaceUri);
            // Throws an exception
        }
    }
}

```

This happened while parsing a template where all extra tags have namespaces and, after some processing, the result is a valid XHTML document.

**Comment by FlorianRappl** [comment]
The last example is invalid. I think it should look as follows (note the closing root element):

``` xml
<x:a xmlns:x="http://initd.org/ns/tesseract-1.0" t="42"><b/><c>TEXT</c></x:a>
```

The other things I will investigate. If they are bugs I will fix them in the upcoming release v0.10.0. Thanks for the report!

**Comment by fogzot** [comment]
Sorry for the last one, my mistake. :(

**Comment by FlorianRappl** [comment]
Fixed - see PR #451. However, I would like to invite @fogzot into a more detailed review:
- Are there any other problems you see with XML namespaces?
- What else needs to be covered?
- Anything obvious missing, faulty, or behaving strangely?

Comments / discussion on this is highly welcome. I would love to have the topic of namespaceURI resolution closed after this one ;).

**Comment by fogzot** [comment]
First of all, sorry for being so late but github never notified me of the changes to this issue and even about your @-citation. Anyway... I'd like to add some more tests (you can nest default/explicit namespaces in some very nasty ways) but apparently I am unable to build AngleSharp (devel branch) on Linux. Using the build script results in:
```
unknown.cake (106,17): A local variable named `target' cannot be declared in this scope because it would give a different meaning to `target', which is already used in a `parent or current' scope to denote something else
Error: A local variable named `target' cannot be declared in this scope because it would give a different meaning to `target', which is already used in a `parent or current' scope to denote something else
```
Using `cake` by hand results in the same error.

I can build with `msbuild` (after changing some Assets.resx paths, `msbuild` has problems with `\` as path separator on Linux) but then I can't run the tests. Are they supposed to be run in a special way? `nunit3-conole-runner.exe` says:
```
1) Invalid : /home/fog/Workspaces/wok/AngleSharp/src/AngleSharp.Core.Tests/bin/Debug/AngleSharp.Core.Tests.dll
No suitable tests found in '/home/fog/Workspaces/wok/AngleSharp/src/AngleSharp.Core.Tests/bin/Debug/AngleSharp.Core.Tests.dll'.
Either assembly contains no tests or proper test driver has not been found.
```

**Comment by FlorianRappl** [comment]
Thanks for having a look @fogzot.

Regarding the build / test process: Works on all my Windows machines (fresh, nothing fancy installed besides Visual Studio - running Cake via the bootstrapper). I'll take a look on a Linux machine soon (will open a separate issue for that tomorrow). Generally, the sources *should* build on non-Windows machines, but I did not test that in a while ...
