### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gruan01** [AngleSharp/AngleSharp#45]
Hello.
Sorry about my English.

I have job , download and parse data from about 30000 web pages.

In parse Method , I use AngleSharp like this :

```
public override IEnumerable<DIRTY_SCHEDULE> Fetch(string ctx, string url = "") {
    var dom = DocumentBuilder.Html(ctx);
    //不支持 even
    //var trs = dom.QuerySelectorAll("#accordion2 table tbody tr:even");
    var trs = dom.QuerySelectorAll("#accordion2>.accordion-group>.accordion-heading>table>tbody>tr");
    for (var i = 0; i < trs.Length; i = i + 2) {
        var tr = trs[i];
        var tds = tr.QuerySelectorAll("td");
        var entry = new DIRTY_SCHEDULE {
            CARRIER = tds[0].Text(),
            ROUTE = tds[1].Text().Trim(),
            VESSEL = tds[2].Text().Trim(),
            VOYAGE = tds[3].Text().Trim(),
            ORGIN = tds[4].Text().Trim(),
            ETD = tds[5].Text().Trim().ToDateTime("yyyy-MM-dd", DateTime.Now),
            DEST = tds[6].Text().Trim(),
            ETA = tds[7].Text().Trim().ToDateTime("yyyy-MM-dd", DateTime.Now),
            TT = tds[8].Text().Trim().ToDecimalOrNull(),
            DIRTY_SCHEDULE_TRANSF = this.FetchTransf(trs[i + 1]).ToList(),
            SOURCE = url,
            APP = "Fetcher.Soushipping",
        };

        entry.UNQTAG = entry.GetUNQTag();

        yield return entry;
    }
}

private IEnumerable<DIRTY_SCHEDULE_TRANSF> FetchTransf(IElement tr) {
    var tbls = tr.QuerySelectorAll("table.widget");
    //第一个列出的是起始地
    for (var i = 1; i < tbls.Length; i++) {
        var rows = tbls[i].QuerySelectorAll("tr");
        if (rows.Length == 3)
            yield return new DIRTY_SCHEDULE_TRANSF {
                VESSEL = rows[0].Text().Trim(),
                AT = rows[1].QuerySelector("td").Text().Trim(), //rows[1].FirstChild.Text().Trim(),
                VOYAGE = rows[2].Text().Trim(),
                SEQ = i - 1
            };
    }
}
```

It work fine.
But, Memory leaked very serious.

You can see it from here :
![Image of Yaktocat](http://images.cnitblog.com/blog/154354/201501/291650256121505.png)
3:20    1.8G!
What's wrong ?
IElement not disposed ?

But use HtmlAgilityPack :
![Image of Yaktocat](http://images.cnitblog.com/blog/154354/201501/291650324561897.png)
3:20   only 270 M.

The code use HtmlAgilityPack:

```
public override IEnumerable<DIRTY_SCHEDULE> Fetch(string ctx, string url = "") {
    var doc = new HtmlDocument();
    doc.LoadHtml2(ctx);
    var root = doc.DocumentNode;
    var trs = root.QuerySelectorAll("#accordion2>.accordion-group>.accordion-heading>table>tbody>tr")
        .ToList();
    for (var i = 0; i < trs.Count(); i = i + 2) {
        var tr = trs[i];
        var tds = tr.QuerySelectorAll("td").ToList();
        var entry = new DIRTY_SCHEDULE {
            CARRIER = tds[0].InnerText.Clear(),
            ROUTE = tds[1].InnerText.Clear(),
            VESSEL = tds[2].InnerText.Clear(),
            VOYAGE = tds[3].InnerText.Clear(),
            ORGIN = tds[4].InnerText.Clear(),
            ETD = tds[5].InnerText.Clear().ToDateTime("yyyy-MM-dd", DateTime.Now),
            DEST = tds[6].InnerText.Clear(),
            ETA = tds[7].InnerText.Clear().ToDateTime("yyyy-MM-dd", DateTime.Now),
            TT = tds[8].InnerText.Clear().ToDecimalOrNull(),
            DIRTY_SCHEDULE_TRANSF = this.FetchTransf(trs[i + 1]).ToList(),
            SOURCE = url,
            APP = "Fetcher.Soushipping",
        };

        entry.UNQTAG = entry.GetUNQTag();

        yield return entry;
    }
}


private IEnumerable<DIRTY_SCHEDULE_TRANSF> FetchTransf(HtmlNode tr) {
    var tbls = tr.QuerySelectorAll("table.widget").ToList();
    //第一个列出的是起始地
    for (var i = 1; i < tbls.Count(); i++) {
        var rows = tbls[i].QuerySelectorAll("tr").ToList();
        if (rows.Count == 3)
            yield return new DIRTY_SCHEDULE_TRANSF {
                VESSEL = rows[0].InnerText.Clear(),
                AT = rows[1].QuerySelector("td").InnerText.Clear(), //rows[1].FirstChild.Text().Trim(),
                VOYAGE = rows[2].InnerText.Clear(),
                SEQ = i - 1
            };
    }
}
```

**Comment by gruan01** [comment]
Forget to say , I'm use AngleSharp  0.7.0.37131
Download from NuGet

**Comment by FlorianRappl** [comment]
First: Thanks for submitting this issue.
Second: Can you try with the latest version from the source? We are close to v0.8 and some things changed internally, so there is a chance that this leak is already fixed.
Third: If second does not help, can you try to call `dom.Dispose()` explicitly after the loop in the `Fetch()` method?

If you give me more code than I can try to debug / optimize the memory management myself.

**Comment by gruan01** [comment]
Hello 

I have downloaded the last version source code from Git.
But, v0.8 ? I can't see it , only :

`
[assembly: AssemblyVersion("0.7.0.*")]
[assembly: AssemblyFileVersion("0.7.0")]
`

DocumentBuilder.Html(string) return type is "IDocument",
IDocument not Implementation IDisposable
But type "Document" can dispose , You mean like the following ?:
`
var dom = (Document)DocumentBuilder.Html(string);
...
dom.Dispose();
`
But Document is private class.

I think if the IDocument implementation IDisposeable it will be good.

**Comment by gruan01** [comment]
Ok, 
I'm doing like this :

```
var dom = DocumentBuilder.Html(ctx);
...
...
dom.Close();
((IDisposable)dom).Dispose();
dom = null;
```

It have a little help for the memmory, but still leack very serious:

![2015-01-30_11-09-55](https://cloud.githubusercontent.com/assets/7332414/5970636/b04a5470-a870-11e4-9e1b-c5f1e62c315b.png)

**Comment by FlorianRappl** [comment]
As said "we are close to v0.8", hence it is not labeled as v0.8 yet.
Alright can you give me some more code that I can go and fix this? Would be highly helpful. I don't care about the custom objects, I am mostly interested in your general algorithm (what page(s) you are downloading). Having such a minimal working example would be highly helpful in general.

Maybe I will expose the `IDisposable`, however, in the end it is not a critical (e.g. release otherwise locked resources such as files) release, just a few explicit cleanups. Therefore the `Dispose()` should be sufficient if called from the runtime. That is the reason I did not expose it.

**Comment by gruan01** [comment]
I have split the source from my Project.

Please download from here :
http://files.cnblogs.com/files/xling/Test1.7z

Change  ScheduleFetcherJob.cs line 47 to ScheduleFetcherByANGS

Thanks.

**Comment by FlorianRappl** [comment]
Thanks for the sources. I could track down the source of the problem and v0.8 will provide a solution for this behavior.

**Comment by FlorianRappl** [comment]
Just to give you a feel for the current status:

After 5:20 the memory still didn't go beyond 39.4 MB:
![image](https://cloud.githubusercontent.com/assets/1766191/5999986/6dd8e326-aad8-11e4-943b-8a4630456dd8.png)

**Comment by gruan01** [comment]
Very good. :+1:

**Comment by FlorianRappl** [comment]
Alright, so I fixed the memory leak. Unfortunately the call to the `Dispose()` method seems to be required, since the GC can't (or won't) free the resources otherwise (due to the circular relationship, I suppose). I could try to work around that, but I suppose that exposing the `IDisposable` (i.e. include it in `IDocument`) IF implementation is sufficient.

![image](https://cloud.githubusercontent.com/assets/1766191/6001743/36d43ece-aaed-11e4-892b-4a2c2cb43c91.png)

**Comment by FlorianRappl** [comment]
It was important to really remove the nodes from the document, however, even more important was to change the continuation tasks. Obviously they are a (potential) memory leak, which could be avoided by just using the async state machine.
