### ISSUE TITLE
Exception when parsing this page

### ISSUE THREAD

**Issue by zhujiangang** [AngleSharp/AngleSharp#452]
Caught exception System.ArgumentOutOfRangeException "Index must be within the bounds of the List" when parsing this page "http://ebay.com/itm/1840-medaille-louis-philippe-retour-cendres-napoleon-invalides-/401137431347", can anyone help to fix this bug? Thanks!
Btw, I used HtmlAgilityPack to parse page "http://hhs51.blogspot.jp/2006/04/hhs-class-of-1956-50th-reunion.html" but got Stackoverflow exception because this page is too complex to parse. Then I tried AngleSharp and the page can be parsed. I am curious about how AngleSharp deal with this case?

**Comment by FlorianRappl** [comment]
Can you provide a MWE to reproduce the issue? Which version are you using? For me the given page works without problems.

``` cs
var address = "http://ebay.com/itm/1840-medaille-louis-philippe-retour-cendres-napoleon-invalides-/401137431347";
var config = Configuration.Default.WithDefaultLoader();
var document = await BrowsingContext.New(config).OpenAsync(address);
```

Regarding the other question: AngleSharp's tokenizer does some tricks to avoid recursion. By moving multiple methods into a single method with a state machine SO exceptions can be avoided. Even though this makes the code a little bit harder to reader (longer method) the benefits (no SO exceptions, faster parsing) are worth it.

**Comment by zhujiangang** [comment]
I copied the source code of this page (http://ebay.com/itm/1840-medaille-louis-philippe-retour-cendres-napoleon-invalides-/401137431347) and used AngleSharp.dll (0.9.9.0)
`var parser = new HtmlParser();
var doc = parser.Parse(html);`

**Comment by FlorianRappl** [comment]
Works for me - the problem must be somewhere on your site.
