### ISSUE TITLE
Full documentation

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#458]
The v1 release is coming closing (as is the v0.10; the last milestone before v1), which means a full documentation will be required.

This has a lot of impact:

- Move parts of the Wiki to the docs
- Create a common documentation infrastructure (common means: good for all AngleSharp projects)
  * Format of the documentation (potentially markdown with many extensions)
  * Special diagram language (I prefer source code; which gets translated into static images in the build process)
  * Place of the documentation (folder will be `docs` in the root directory of each project)
- Integrate the full (i.e., aggregated from all projects) documentation on the website; in HTML
- Have the code for reading the documentation on GitHub
- Create a PDF for simple download

As this is the core project the outline will be (roughly):

- Introduction
- Architecture
- Parsing and requester pipeline
- (Sample) use-cases w. (simple) examples
- Core interfaces
- Services and extensibility

**Comment by ishanpranav** [comment]
Are there plans for a full API documentation for the libraries, such as a DocFx?

**Comment by FlorianRappl** [comment]
> Are there plans for a full API documentation for the libraries, such as a DocFx?

No such plans exist right now; for some of the interfaces ("Core interfaces") an automatic conversion to our documentation is planned.
