### ISSUE TITLE
NthChild with formula does not work

### ISSUE THREAD

**Issue by mitja-p** [AngleSharp/AngleSharp#46]
Hi,

I found a bug. When using QuerySelectorAll and using nth-child with calculations, for example tr:nth-child(n+2) it does not work correctly. It returns all children instead of the ones from second node on.

**Comment by FlorianRappl** [comment]
Which version of AngleSharp are you using? I've seen that the nth-child calculation had a bug and fixed one a couple of weeks ago, hence in the latest sources the bug could be gone.

Otherwise please provide a MWE such that I can create a unit test and fix the bug.
Thanks a lot for reporting this issue!

**Comment by mitja-p** [comment]
This was in version 0.7. I tried the current source code and it works. Sorry for not testing before reporting it.

Thanks for developing this library!

**Comment by FlorianRappl** [comment]
No - thank you for trying it! I am sorry that v0.8 is not yet released, but that will definitely change quite soon. I also plan to do pre-released starting after v0.8 has been released. That just alleviate the problem.

Please feel free to report further problems. Such contribution means a lot to me.

**Comment by mitja-p** [comment]
I have another nth-child problem. :) 
Try loading the html from this page:
http://www.htmlcodetutorial.com/tables/_TD_COLSPAN.html

And then do the following operation:
doc.DocumentElement.QuerySelectorAll("table:nth-child(21)")

Browser (firefox) has no problem with this selector, but AngleSharp does not find anything.

**Comment by FlorianRappl** [comment]
I will look into it :)

**Comment by FlorianRappl** [comment]
Obviously this is no selector bug, but rather a bug in the HTML parsing. Has to be fixed. As this is a major bug I will also release a new version on NuGet.

**Comment by FlorianRappl** [comment]
The issue was found an fixed. Thanks for your report!
