### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#460]
From the discussion in #448 it seems that AngleSharp currently has problems to build on Linux.

This should be fixed and instructions on how to build on Linux (and Windows, Mac OS) should be provided for completeness (e.g., install .NET Core using ..., clone the code, ... run x).

The instructions should be part of the upcoming documentation.

**Comment by FlorianRappl** [comment]
⚠️ ⚠️ ⚠️ 

**The following content is a WIP**

Follow the instructions on the [.NET core homepage](https://www.microsoft.com/net/core#linuxubuntu), e.g., for Ubuntu:

```bash
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
sudo apt-get update
sudo apt-get install dotnet-dev-1.0.0-preview2-003131
```

The version of .NET core to be installed can also be [obtained from the list of downloads](https://www.microsoft.com/net/download/linux).

Furthermore, due to current limitations in [Cake](http://cakebuild.net) we also require Mono for the Bootstrapper.

```bash
sudo sh -c 'echo "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
sudo apt-get update
sudo apt-get install mono-devel
sudo apt-get install referenceassemblies-pcl 
```

*Apparently, NuGet v3 with Mono has a severe bug that does not work when the UTC offset is positive (e.g., Germany has UTC+1). The solution is to (at least temporarily) set the time to some other country, e.g., UK where we have UTC+0.*

Potentially, Mono needs to be updated to the latest version. To identify this the command `mono --version` may be used. The minimum tested version is `4.6.2`. We recommend running

```bash
sudo apt-get upgrade mono-devel
```

to ensure that the latest version is definitely installed.

To prevent NuGet bugs spoiling the build the following download command is recommended:

```bash
curl https://dist.nuget.org/win-x86-commandline/v2.8.6/nuget.exe -o tools/nuget.exe
``` 

Clone AngleSharp:

```bash
git clone https://github.com/AngleSharp/AngleSharp.git
cd AngleSharp
```

Enable execution of the build script:

```bash
chmod +x build.sh
```

Run the build script:

```bash
./build.sh
```

The build should complete with all unit tests being run successfully. If anything fails it may be due to an incompatibility of AngleSharp with the installed toolset. Potentially, a more recent version is available. In any case an [issue should be filed](https://github.com/AngleSharp/AngleSharp/issues) to get things working properly.

Right now the build does not try to create binaries for targets other than .NET Standard. Therefore the build does not bundle a NuGet package. We could (and eventually will) enable this, however, in order to illustrate that builds on Linux are not as complete as on Windows we disabled the package bundling.

**Comment by FlorianRappl** [comment]
Right now some unit tests are failing on Linux. I will investigate why.

Two regions are impacted:

* Encoding (could be bad transport or not/wrong implemented in Mono, e.g., Windows-1252)
* Cookie handling (potentially an issue with the CookieContainer in Mono)

I will see if we can get around these issues. Maybe anyone has an idea by seeing the [output of the failing tests](https://gist.github.com/FlorianRappl/51a9cadfa5ca66f15aa156ce0a33dae2).

**Comment by fogzot** [comment]
With some minimal changes to the build scripts I was able to build and run the tests on Linux using Mono 4.6.3.

1. Checkout a fresh copy of "devel".
2. Substitute nuget.exe in tools as explained above.
3. Applied pull request #469 to fix default TARGET and avoid dotnet core build.
4. ./build.sh

I got the same test failures. I'll investigate later.

**Comment by FlorianRappl** [comment]
Maybe I should have added the WIP branch I am working on. See PR #469 for the location.

**Comment by FlorianRappl** [comment]
Actually, let's have this for v1. I don't want to make v0.10 dependent on this one.

**Comment by FlorianRappl** [comment]
I was successfully able to download and build on WSL. Thus I believe we can do it now. The only thing missing is documentation. I will update the README soon.

**Comment by 304NotModified** [comment]
I think it's pretty easy to get this library build on Linux, if:

- the project file is moved to the 2017 csproj format 
- we don't use cake. With the `dotnet` command, it's pretty easy to get things building

**Comment by FlorianRappl** [comment]
Well, Cake is of course required, but that should **and is** not really a problem. Our Cake build uses the dotnet tools of course. Unfortunately, Cake also / still requires Mono.

But this issue is no longer about the build (on Linux) itself, rather just about the documentation (just for completeness).

**Comment by 304NotModified** [comment]
why is cake required? IMO it's overkill if you could build your library with just 2 lines:

```
dotnet restore
dotnet build
```

**Comment by FlorianRappl** [comment]
If you remove multi-platform for most cases yes, but for CI/CD we still want Cake for other things...

- Update the version wrt changelog (consistency)
- Bundle the NuGet package
- Publish the NuGet package

All contained in a single workflow. So why have these two lines (plus X more, e.g., to run tests etc.) if you can just do `./build.sh`?

So again don't get me wrong - of course what you describe can be done, but it was always possible. Even prior to dotnet you could trigger the build with either msbuild or xbuild. But since Cake is there (for CI/CD) it *should* also work on Linux.

**Comment by 304NotModified** [comment]
OK, just trying to make things a bit easier.



> If you remove multi-platform for most cases yes,

FYI, `dotnet restore/build/pack` will work for multi-platforms. To be clear, building a creating a nupkg for NLog for 11 platforms is  essential one line. (note we use the msbuild syntax here for flexibility) 

```
msbuild /t:Restore,Pack .\src\NLog\ /p:targetFrameworks='"net45;net40-client;net35;netstandard1.3;netstandard1.5;netstandard2.0;sl4;sl5;wp8;monoandroid44;xamarinios10"'
```

**Comment by FlorianRappl** [comment]
> FYI, dotnet restore/build/pack will work for multi-platforms.

Yes I know but how does this solve the documentation issue?

**Comment by 304NotModified** [comment]
well less (3rd-party) commands makes the documentation easier. The docs could be "like every other .NET (standard) library". (OK, I skipped the release notes and publishing releases)

**Comment by FlorianRappl** [comment]
I agree, but the only command is "./build.sh".

The rest is just how Mono and the right version of NuGet is installed. Some parts (e.g., `sudo apt-get install referenceassemblies-pcl`) or the NuGet part will be omitted when the multi-platform (see #709) requirements goes away with a single .NET Standard target.

Did you read the proposed documentation extension? It is only touching the installation part to make sure one does not get stuck in that area.

**Comment by alexanderuv** [comment]
After migrating the `devel` branch to support .NET core, the build is fine but the tests are failing due to specific .NET core implementation:

```
Error Message:
 System.PlatformNotSupportedException : The information requested in unavailable on the current platform.
Stack Trace:
   at System.Net.NetworkInformation.LinuxNetworkInterface.get_Speed()
   at AngleSharp.Core.Tests.Helper.IsNetworkAvailable(Int64 minimumSpeed) in /media/sddata/data/AngleSharp/src/AngleSharp.Core.Tests/Helper.cs:line 53
   at AngleSharp.Core.Tests.Helper.IsNetworkAvailable() in /media/sddata/data/AngleSharp/src/AngleSharp.Core.Tests/Helper.cs:line 24
```

Just tested this on Ubuntu 18.04

**Comment by FlorianRappl** [comment]
Thanks @alexanderuv - I disabled the network tests on Linux as this should not make a difference (the requesters itself are also tested w/o network); tests pass now!

Think this can be closed now ...
