### ISSUE TITLE
Empty response on Xamarin.Droid project after calling OpenAsync(url)

### ISSUE THREAD

**Issue by genie137** [AngleSharp/AngleSharp#466]
Hello, 
I don't know if this is the right place to ask this, so remove it if necessary.

I am using Xamarin.Forms 2.3.3 (targeting droid, ios and uwp) and the AngleSharp 0.9.9 (in the shared part).
I am trying to get the document of the page to automate the login page of my school.
It seems to work on UWP and Ios (project is still in early stages), but not on android (yes i have the internet permission).
Im also relatively new to C# so burn me if you need to.

My problem:
There are no Exceptions for any errors occurring in the _context.OpenAsync(url). 
Do I do something wrong? Is it a bug? Who knows.
I have placed this [question on Stackoverflow](http://stackoverflow.com/questions/40705925/anglesharp-and-xamarin-forms-openasync-does-not-work-in-droid-project) too, but have not received any answer.

```cs
public async Task<string> LoginAsync(string username, string password)
{
    try
    {
        var url = "correcturl";
        var _context = BrowsingContext.New(Configuration.Default.WithDefaultLoader().WithCookies());

        try
        {
            _document = await _context.OpenAsync(url);
        }
        catch (Exception e)
        {
            Debug.WriteLine("ERROR " + e);
            return "Error";
        }
        IHtmlInputElement usernameElement = _document.QuerySelector("input[id='username']") as IHtmlInputElement;
        IHtmlInputElement passwordElement = _document.QuerySelector("input[id='password']") as IHtmlInputElement;
        IHtmlFormElement loginformElement = _document.QuerySelector("form[id='logonForm']") as IHtmlFormElement;

        Helpers.Settings.Username = username;
        Helpers.Settings.Password = password;

        usernameElement.Value = username;
        passwordElement.Value = password;
        _document = await loginformElement.SubmitAsync();

        _loginstatus =  CheckLoginStatus(_context.Active.Url);
        return _userdata;
    }
    catch (Exception e)
    {
        Debug.WriteLine("ERROR " + e);
        return "Error";
    }
}
```

**Comment by FlorianRappl** [comment]
Ok, can you please go into details what behavior you expect. You mention that there are no "exceptions for any errors", so I wonder which errors you are referring to? `OpenAsync` should never throw unless you do something evil (e.g., provide `null` as `IBrowsingContext`).

Where does the behavior between UWP and Android deviate? Is the rest of your code working (i.e., is the `_userdata` returned as anticipated)?

**Comment by genie137** [comment]
Thanks for your reaction.

As for the nature of Xamarin.Forms I excpect the same behaviour on all platforms.
With my testing it works on both UWP and iOS.
On those devices i receive a document, which is converted in a number of elements which fills the username/password and submits that form. After that there are some cookies set and the page is redirected into the "secure" part. If the redirected page is the correct page, and not a redirect to the same site (which indicates the password is wrong). A section of the page is extracted containing a JSON with userdata. This works very well using the native Java Android app using the Json libary.

The following things occur on the Android side:
1. When I use the correct credentials and press the login button in my login page, the LoginAsync method is executed.
2. Then the Mono log continuously says messages as "Uphill battle" and "Nursery full" things concerning threading (will post a screenshot tomorrow).  This takes about 30 seconds on my Galaxy S7 after a clean > rebuild deployment.
3. The 2nd catch will report a NullRefereicnceException, which is true. Because when i want to fill the field of the username, the IHtmlInputElement usernameElement is not instanciated. 
4. The method stops, because its inside an async

On UWP/iOS, step 2 takes about 2-5 seconds. After which it finishes and the userdata is printed in the log (code not shown here).

Apparently the _document object is filled after the OpenASync. When I dont receive anything, I expect the object to be Null or at least throw an exception of some sort. So I can retry ( because of a terribly slow connection.). 

If you want to I can post images tomorrow afternoon (im in CET+1).
Thanks in advance.

**Comment by FlorianRappl** [comment]
Ok, so I now think it is as follows (correct me if I misunderstood):

* `_document = await _context.OpenAsync(url)` never throws (it also should never throw), but there may be an "uphill battle" or some other continuous redirect loop (I suppose that might be it; otherwise I am not sure why it should be stuck)
* The returned document may be different to the one you expect (that can always happen; either because the page you requested changed or because, e.g., some network failure which may appear on the client *or* server side) - in this case, of course, some (if not all) of the query selectors may return `null`
* On UWP/iOS the response to the request is as anticipated, on Android you run into problems and get a response that looks different

All in all that sounds like a problem in Xamarin.Droid. However, we need to investigate a little bit more. For now the analysis should focus on this "uphill battle" / "nursery full". The latter comes from [the way Xamarin does GC](http://www.mono-project.com/docs/advanced/garbage-collector/sgen/). So indeed, something seems to be spinning in a loop, potentially continuously creating new objects.

**Comment by FlorianRappl** [comment]
Do we know yet if this is something in AngleSharp or Xamarin? If it is in AS, what can be done to improve the situation?

An estimate or any kind of statement would be helpful for me to decide whether to tackle it in v0.10 already, or to have it in the backlog for v1.

**Comment by genie137** [comment]
Hey, sorry for the late reaction. Yesterday I had time to work on the project. 

I dont know if the problem is in AngleSharp or Xamarin.
However I found a solution that it does give the intended result.

- Using the app [Package Capture](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=nl) I install the SSL certificate, and start the capture session. If I then proceed to use the app and login, i get the expected result. Not once, but every time.
- Running the capture session without the SSL certificate gives the expected result
- Capture session not running, gives an error.
- It is not device specific, tried it on different branded phones. Same result.

However this is not really a good solution for end-users....
My suspicion is that the problem is in the android ecosystem itself. Probably something to do with the Firewall,  because the package capture connects to the firewall.
It is also possible that the issue is concerned in how AngleSharp is communicating with the internet. But I do not know the specifics of this.

I would like to see a more verbose logging option in the .OpenASync() method. So i can further debug this issue.

**Comment by FlorianRappl** [comment]
The `OpenAsync` won't solve your issue - this does nothing directly; just orchestration. Just create a requester wrapper around, e.g., the `DefaultHttpRequester` and you are good to debug what is actually going on.

**Comment by genie137** [comment]
I will try that in the upcoming days. Thanks.

**Comment by FlorianRappl** [comment]
I think the origin of the problem does not lie in AngleSharp. I am closing this for now. If you have anything to add / investigate please share, thanks!
