### ISSUE TITLE
Parsing style tag in HTML document that includes comments

### ISSUE THREAD

**Issue by 206mph** [AngleSharp/AngleSharp#467]
How can I parse the following HTML and access the comment next to each CSS selector and know which selector the comment belongs too? Also, if there are comments on their own lines within the style tag, I'd like to be able to access those as well.

`<html>
    <head>
        <style type="text/css">
            /*CommentFlag1*/ img {border:0}
            table {background-color: red;}
        </style>
    </head>
    <body>
    ....
    </body>
</html>`

**Comment by FlorianRappl** [comment]
Comments are not part of the CSSOM. Once they could be included, but the solution was not elegant.

They may come back with AngleSharp.Css eventually, but the final decision on this has not been made.
