### ISSUE TITLE
Url IsInvalid is incorrect

### ISSUE THREAD

**Issue by Suchiman** [AngleSharp/AngleSharp#47]
``` csharp
Url url = new Url("https://www.google.de/");
url.IsInvalid //true
```

It looks like that there's a missing negation in [Url.cs line 404](https://github.com/FlorianRappl/AngleSharp/blob/master/AngleSharp/Url.cs#L404):

``` csharp
_error = ParseScheme(input.Trim());
```

**Comment by FlorianRappl** [comment]
That seems to be the case... Thanks for spotting that!
