### ISSUE TITLE
Why does IHtmlInputElement.Value have a setter?

### ISSUE THREAD

**Issue by j055** [AngleSharp/AngleSharp#472]
Hi

I apologise for the poor tests here https://github.com/AngleSharp/AngleSharp/issues/471. It was also not meant to be a bug report, just a way of illustrating the problems I was having in understanding what's going on.

I think part of the problem is that the ```IHtmlInputElement``` interface allows us to set the value property but the value is not outputted in the ```document.Body.InnerHtml```, for example. A ```DefaultValue``` is provided and this does output the value. 

Therefore, is it reasonable to expect that the ```IHtmlInputElement.Value``` should not have a setter? 

Thank you
Andrew

**Comment by FlorianRappl** [comment]
This is false. Please first read my last post regarding #471 carefully. There is difference between properties and attributes. The value property sets the value state, which is connected to the value attribute only such that the attribute is used as "fallback" / default value. When you set the value you don't change the default value.

This behavior is 100% as described by the W3C. Again, please try in the browser first before making any statement what is wrong in AngleSharp.
