### ISSUE TITLE
WithJavaScript() does not work with <script src=""/>

### ISSUE THREAD

**Issue by DruSatori** [AngleSharp/AngleSharp#473]
At least that's what I think is happening.  

Looking at the below page: 

http://www.druware.com/unittests/library.external.html

it simply loads an external script element ( <script type="text/javascript" src="external-script.js" ></script> ) and expects it to execute.  Using the exact same script within the script tag, rather than a src attribute, it executes as expected.

http://www.druware.com/unittests/library.internal.html

Is it possible to extend the loader in a portable manner to fetch the nested scripts prior to execution?

**Comment by FlorianRappl** [comment]
Resource loading requires a *resource* loader (I assume this is your problem - otherwise this is done automatically). If you don't give a MWE to reproduce your problem I can't help you much.

**Comment by DruSatori** [comment]
Sorry, still trying to dig through this moving code from HtmlAgilityPack and ClearScript.  Resource Loader?  I don't see that in the documentation anywhere, but I could be blind too...  Is there an example that uses a resource loader?

**Comment by FlorianRappl** [comment]
When you use the `WithDefaultLoader()` you'll see it by using the callback, e.g.,

```cs
var configuration = Configuration.Default.WithDefaultLoader(setup => setup.IsResourceLoadingEnabled = true);
```

It's also available in the samples repository, e.g., in the WPF sample.

**Comment by DruSatori** [comment]
That explains it. I'm not using Windows for any of this work so haven't looked at any of the WPF code.
Thanks!

**Comment by FlorianRappl** [comment]
By default AngleSharp does not load external resources (or allow any kind of navigation). You really need to tell AngleSharp to do this. The option was disabled by default to avoid unnecessary network load and evaluation.

Glad I could help!
