### ISSUE TITLE
AngleSharp\Url.cs in Line 844 - Assignment in coditional expression

### ISSUE THREAD

**Issue by masterinspire** [AngleSharp/AngleSharp#48]
`if (fragment = (!onlyQuery && input[index] == Symbols.Num))`

![2015-02-04-1153-001](https://cloud.githubusercontent.com/assets/9047578/6034936/a2963e46-ac64-11e4-8a96-b64eb8c6bfd0.png)

**Comment by FlorianRappl** [comment]
Yeah one could discuss this (I did not get a warning here using the Roslyn compiler). Obviously one possibility what have been to add additional parenthesis around the assignment (this is at least how Clang is notified about the intention).

Nevertheless, in the end I guess doing the check before is a better coding style. Therefore thanks for the spotting the potential confusing line!
