### ISSUE TITLE
:root selector doesn't work on child elements

### ISSUE THREAD

**Issue by kaso17** [AngleSharp/AngleSharp#480]
Here's some example code:
https://gist.github.com/kaso17/009d3360eb939db324435daefe06554c

The first query on the document (root1) works as expected.
The Second one (root2) on a child element returns null (root node of the document is expected).

**Comment by FlorianRappl** [comment]
This is the specified behavior. Everything's alright here. How should the root node of the document be returned when its not part of the tree you are querying?
