### ISSUE TITLE
Is GetComputedStyle working?

### ISSUE THREAD

**Issue by DmitriiShamrikov** [AngleSharp/AngleSharp#486]
Simple code:
```C#
var html = @"
	<!DOCTYPE html>
	<html>
	<head></head>
	<body></body>
	</html>";

var doc = new HtmlParser().Parse( html );
var style = doc.DefaultView.GetComputedStyle( doc.Body );
```
Throws an exception `System.ArgumentNullException`. Am i doing something wrong?

I am using version 0.9.9

**Comment by FlorianRappl** [comment]
Yes - you are not including CSS. The default configuration (as you are not using any configuration - it is the implied default one) does not come with anything - no requester, no CSS, no cookies, ...

Style computation requires CSS to be present.

Remark: Be aware that the style computation is very rudimentary and should not be considered production ready. It may work quite well, but it is unfinished work. It also depends heavily on the agent stylesheet (and AngleSharp uses the most basic agent stylesheet as specified).

**Comment by DmitriiShamrikov** [comment]
Thanks, I finally got how to create necessary configuration.
I know that it is unfinished, just checking if it will work in my case.

**Comment by erdomke** [comment]
For future readers of this issue who are hoping to find the solution, the following tweak is what worked for me:

```csharp
var config = Configuration.Default.WithCss();
var html = @"
	<!DOCTYPE html>
	<html>
	<head></head>
	<body></body>
	</html>";

var doc = new HtmlParser(config).Parse( html );
var style = doc.DefaultView.GetComputedStyle( doc.Body );
```
