### ISSUE TITLE
Attributes with no value get ="" added to them

### ISSUE THREAD

**Issue by ChrisMaunder** [AngleSharp/AngleSharp#490]
[Boolean Attributes](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes)  are valid HTML but AngleSharp's default [formatter](https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Html/HtmlMarkupFormatter.cs#L118) will always add ="" to attributes that have no value. A simple  change of

```
    if (value.Length > 0) // Add this check
    {
            for (var i = 0; i < value.Length; i++)
            {
                switch (value[i])
                {
                    case Symbols.Ampersand: temp.Append("&amp;"); break;
                    case Symbols.NoBreakSpace: temp.Append("&nbsp;"); break;
                    case Symbols.DoubleQuote: temp.Append("&quot;"); break;
                    default: temp.Append(value[i]); break;
                }
            }
    }
```
would fix this

**Comment by FlorianRappl** [comment]
This is by specification. If you would try it in evergreen browsers you'd see that they do it the same way!

If you don't like this behavior you should just use your own formatter. You can simply wrap the default formatter if that one forms a good basis for your desired output.

Keep in mind that the standard formatter was written in such a way to work exactly as browsers do.

**Comment by ChrisMaunder** [comment]
Seems the specs allow attributes without the ="" but I can see that adding the empty string is certainly within specs.

I have an unusual case that is causing issues: trying to clean bad HTML.

Consider this snippet of HTML
```
<p>This is my code.</p>
<code>
for (int i = 0; i<n; i++) ...
</code>
```
The "i<n" should be "i&lt;n" but that's not what we always get. If I load this HTML doc in AngleSharp then it  will thin <n is a tag and everything after it (including the closing brackets, quotes - lots of stuff) is an attribute with no value, and so appends ="" all over the place.

Obviously the solution is to catch the bad "<"s and encode them first, but often AngleSharp does an excellent job of handling these bad brackets - except for the added ="".

I've created a custom formatter and that works fine, but a simple (OK, maybe API-messy!) flag to toggle this behaviour would save me some code.

In any case, I understand and support your call on this. It never hurts to ask.

**Comment by FlorianRappl** [comment]
The parser follows the HTML 5.1 specification 100% - so in the described edge case the behavior is the specified one (however, as you noted - not the handling you need).

Maybe there is a potential way around this (either via a setting I could introduce or some service that gives you the ability to directly inject behavior into the parsing stages).

I will think about it and try out some implementations. In the end performance could be the potential killer here, but let's see first!

**Comment by ChrisMaunder** [comment]
I'm open to all suggestions!
