### ISSUE TITLE
Major performance problem with ComputeCurrentStyle

### ISSUE THREAD

**Issue by oliverw** [AngleSharp/AngleSharp#495]
So far I'm enjoying working with AngleSharp. Today I've discovered a major performance problem for my use-case even when dealing with medium size HTML content (580 KB,  2700 lines).

I'm converting a IHtmlDocument to a different format and in the process I'm invoking <code>IHtmlElement.ComputeCurrentStyle()</code> for every element in the document. This takes roughly 20 minutes on a Core i7. When omitting the the call to <code>IHtmlElement.ComputeCurrentStyle()</code> the conversion process completes almost instant.

I've cloned the repo and for benchmarking and made <code>WindowExtensions.GetStyleCollection</code> publicy accessible. Caching the result and just calling <code>styleCollection.ComputeDeclarations(el)</code> shrank the execution time to just 5 seconds.

Therefore I would like to propose to expose <code>WindowExtensions.GetStyleCollection</code> to users of the library.

**Comment by FlorianRappl** [comment]
Please repost on [AngleSharp.Css](https://github.com/AngleSharp/AngleSharp.Css). The CSS part will be completely removed from the core with the next version that will be made available next week.

Thanks for your insights; the `GetStyleCollection` should indeed by exposed.

Also note that `ComputeCurrentStyle` was not designed to be used for each element (as it performs quite some redundant operations). I guess your use-case is to build a render tree. This will also be covered by AngleSharp.Css in the long run.

**Comment by oliverw** [comment]
> I guess your use-case is to build a render tree. This will also be covered by AngleSharp.Css in the long run.

Exactly. 👍
