### ISSUE TITLE
How to set Proxy details for context

### ISSUE THREAD

**Issue by youranupama** [AngleSharp/AngleSharp#498]
Can you tell me how I can set proxy details for web request. Is it supported?
If we use XmlHttp then there are option to set proxy like this
oXMLHTTP.setProxy 2, "myProxyServer:80", ""

A simple example is appreciated. 
Thanks

**Comment by FlorianRappl** [comment]
AngleSharp is no HTTP requester library - it does not dictate you which requester to use (and how that one is configured).

I recommend using AngleSharp.Io - as it rolls with a more modern HTTP requester (`HttpClient`).

```cs
var handler = new HttpClientHandler
{
    Proxy = new WebProxy("http://myProxyServer:80", false),
    UseProxy = true
};
var config = Configuration.Default.WithRequesters(handler);
var context = BrowsingContext.New(config);
//Use context
```
