### ISSUE TITLE
Link click emulation

### ISSUE THREAD

**Issue by ShuraKonrsa** [AngleSharp/AngleSharp#504]
AngleSharp has the option of clicking the link? For example, is there a website where by clicking on the link- anchor that triggered the AJAX request and displays hidden text. Is there a way to read the hidden text with link click emulation?
`<a href="#" class="show-content" rel="3362562" label="LA/3362562">Show Content</a>`

**Comment by FlorianRappl** [comment]
You are not looking for "click emulation"; you are looking for running JavaScript (a JS adds an event listener for the click event on the link - this event listener runs the code that will eventually reveal the hidden text).

[AngleSharp.Scripting](https://github.com/AngleSharp/AngleSharp.Scripting) is in an alpha stage and may be able to help you there.
