### ISSUE TITLE
Please add HTML5/WHATWG NamedConstructors

### ISSUE THREAD

**Issue by atefshehata** [AngleSharp/AngleSharp#506]
Please add HTML5/WHATWG NamedConstructors

Some implementations of HTML elements missing the named constructors as defined in HTML5/WHATWG specifications.
For example HTMLImageElement has "Image" constructor, HtmlAudioElement also has "Audio" constructor.

Also, is it worth to change class modifiers for sealed elements to "public" instead of "sealed" so we can extend these classes easily.

Thanks
Atef

**Comment by FlorianRappl** [comment]
Classes which are intended to be inherited are not marked as `sealed`. As, e.g., the `HtmlImageElement` is constructed internally (e.g., from the parser) inheritance would not be useful to you.

The named constructors are only available in scripting languages as currently there is no way to make internal classes (the examples you named will always remain internal, externally the interfaces are used) available for construction.
