### ISSUE TITLE
IParentNode.Append adds the nodes twice

### ISSUE THREAD

**Issue by thorn0** [AngleSharp/AngleSharp#51]
Consider this snippet.

``` C#
var doc = DocumentBuilder.Html("");
var children = new[] {
    doc.CreateElement("span"),
    doc.CreateElement("em")
};
Console.WriteLine(children.Length);
doc.Body.Append(children);
Console.WriteLine(doc.Body.ChildNodes.Length);
Console.WriteLine(doc.Body.InnerHtml);
```

One might expect that it would print

``` html
2
2
<span></span><em></em>
```

But it actually prints

``` html
2
4
<span></span><em></em><span></span><em></em>
```

**Comment by FlorianRappl** [comment]
Yep, this is a bug [and a big one]. But thanks to your code it was easy to reproduce and tackle. Fixed it and I will most likely push it to Nuget (v0.8.2) in the next few days.

Thanks for your useful contribution!
