### ISSUE TITLE
IndexOutOfRangeException while trying to remove scripts

### ISSUE THREAD

**Issue by ushenkodmitry** [AngleSharp/AngleSharp#510]
Hi,

		[TestMethod]
		public async Task TestMethod1()
		{
			IBrowsingContext bc = BrowsingContext.New(Configuration.Default.WithDefaultLoader());
			var document = await bc.OpenAsync("http://allmf.ru/BCom/BComShow.asp?ID=102778");
			foreach (IHtmlScriptElement script in document.Scripts)
				script.Remove();
		}

		[TestMethod]
		public async Task TestMethod2()
		{
			IBrowsingContext bc = BrowsingContext.New(Configuration.Default.WithDefaultLoader());
			var document = await bc.OpenAsync("http://www.vesti.ru/doc.html?id=2841187");
			foreach (IHtmlScriptElement script in document.Scripts)
				script.Remove();
		}

TestMethod1 throws IndexOutOfRangeException, TestMethod2 doesn't. AngleSharp v.0.9.9.0.

**Comment by FlorianRappl** [comment]
Thanks 👍 . I will look into that. Links are always quite hard to deal with (content may change at any time) - I will need to break it down anyway.

If it can be reproduced it will be fixed in the next release.

**Comment by FlorianRappl** [comment]
Both are behaving equally for me. Either both fail (as you remove elements from an iterator, same as in .NET) or both work if handled via a loop.

```cs
var bc = BrowsingContext.New(Configuration.Default.WithDefaultLoader());
var document = await bc.OpenAsync("http://allmf.ru/BCom/BComShow.asp?ID=102778");

for (var i = document.Scripts.Length; i >= 0; i--)
    document.Scripts[i].Remove();
```
