### ISSUE TITLE
Type initializer exception

### ISSUE THREAD

**Issue by ChrisMaunder** [AngleSharp/AngleSharp#512]
I'm getting this occasionally:

> The type initializer for 'AngleSharp.Dom.Html.HtmlStyleElement' threw an exception. (inner: Index was outside the bounds of the array.) 

Stacktrace

```
at AngleSharp.Services.Default.HtmlElementFactory.<>c.<.ctor>b__3_50(Document document, String prefix)
   at AngleSharp.Services.Default.HtmlElementFactory.Create(Document document, String localName, String prefix)
   at AngleSharp.Parser.Html.HtmlDomBuilder.AddElement(HtmlTagToken tag, Boolean acknowledgeSelfClosing)
   at AngleSharp.Parser.Html.HtmlDomBuilder.InHead(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.InBodyStartTag(HtmlTagToken tag)
   at AngleSharp.Parser.Html.HtmlDomBuilder.InBody(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Parse(HtmlParserOptions options)
   at AngleSharp.Parser.Html.HtmlParser.Parse(String source)
```

**Comment by FlorianRappl** [comment]
I think this is a duplicate of #406, which was solved in #489 (PR #491). Should be fixed with the next release.

**Comment by ChrisMaunder** [comment]
We’re on the latest version and we’re seeing this problem today.

Wish I had some data to send you, but our logs don’t have the good bits
saved in this case.

Chris Maunder | Co-founder
chris@codeproject.com | www.codeproject.com

**Comment by FlorianRappl** [comment]
Hi Chris, unless you've build from `devel` and have the 0.10.0 release (which I doubt) sending the data makes no sense. Maybe you have misinterpreted my post (see "Should be fixed with the next release.").

**Comment by vivekjMSFT** [comment]
Hi Chris, did you work out the solution for it, yet? I am thinking to fork the 0.9.9 and apply the fix on top of it since V.0.10 is taking forever to get released and its another bad run time exception.

**Comment by ChrisMaunder** [comment]
No – we've just worked around it.

Funnily enough just last night I was thinking exactly the same thing and I've sent Florian an email today about it: v1 is way overdue.

Cheers
Chris

**Comment by vivekjMSFT** [comment]
what is the workaround you have used? Its just so random and very hard to reproduce. I am creating a singleton object to AngleSharp but still it traps into this concurrent issue somehow.

**Comment by georgiosd** [comment]
Why are you creating a singleton object? Context should be local, not a
singleton.

**Comment by vivekjMSFT** [comment]
I am using it through HTMLSanitizer, and create a singleton object of HTMLSanitizer with the desired configuration. So there isn't a way two threads are initializing the Anglesharp. Mine is a web app.

**Comment by ChrisMaunder** [comment]
We were getting this issue by way of other components (CssInliner, HtmlSanitizer) that were using AngleSharp. We patched them (sorry, forget details) and have our own version of them that use the latest version of AngleSharp. We're hoping that once AS goes v1.0 the components that use Anglesharp will stop tying their builds to a specific AS version and allow updates in AS to trickle through to them properly.

I did speak with Florian and he's keen to get 1.0 out, but there's pesky things called "hours in the day" and "a job" and "paying the rent" and stuff that are inconveniencing him

**Comment by vivekjMSFT** [comment]
"We were getting this issue by way of other components (CssInliner, HtmlSanitizer) that were using AngleSharp

Are you saying this issue is triggered by calling components and not inside anglesharp? it would be great if you could share your branch. I am getting hit by this more often, trying to get my head around the codebase, will appreciate if you could share the fix.

**Comment by ChrisMaunder** [comment]
@vivekscripts Looks like I spoke prematurely. I thought we'd worked around the issues by doing some pre-cleanup but we're seeing the issue still. We can but wait for an update...
