### ISSUE TITLE
Parsing or setting style attributes with [out of range values] should not throw exceptions

### ISSUE THREAD

**Issue by atefshehata** [AngleSharp/AngleSharp#516]
Thanks for creating this excellent project. I really like it.

When using CssEngine, some of the websites I try to load throw OverflowException: Value was either too large or too small for an (Int32, ...). 

The parser throws this error and ignores the rest of the style sheet.

Here is a shortened call stack where the error happens: (sorry, the call stack is to large to paste it here)
AngleSharp.Parser.Css.CssNumberToken.get_IntegerValue()
...
...
AngleSharp.Parser.Css.CssParser.ParseStylesheetAsync()  

Practically, web browsers treat this errors in more relaxed mode and they don't throw any exceptions; they check the supplied value and set either the maximum or the minimum for the given data type. The same also applies for setting style values directly using CSSStyleDeclaration class

for example, the following script tries to set zIndex with too large value.

var elm=document.getElementById('ID');
elm.style.zIndex='99999999999999999999999999999999999999999';
elm.style.zIndex;

If you run this script in debugger console of any web browser you will get the maximum value of Int32 "2147483647"

While setting too small value like the following example
elm.style.zIndex='-99999999999999999999999999999999999999999';

will return the minimum value of Int32 "-2147483648"

So, does AngleSharp has any option to control whether to automatically convert out of range values or to throw exceptions (maybe something like strict mode). I'm talking about configuration option because I didn't read the specifications of parsing CSS style sheets and I don't want you to break any specs. But if the specs allow automatic conversion then there is no need for any option and the conversion should automatically applied.

Thanks and good luck,
Atef

**Comment by FlorianRappl** [comment]
CSS is not handled in the core anymore. Please report this in the dedicated [repository](https://github.com/AngleSharp/AngleSharp.Css).
