### ISSUE TITLE
inject Cookies to AngleSharp

### ISSUE THREAD

**Issue by Memphis19** [AngleSharp/AngleSharp#517]
I need AngleSharp read a cookie session to get open a secure website, i try this but it is not working.

```HttpWebRequest req = (HttpWebRequest)WebRequest.Create(url);
req.Credentials = new NetworkCredential("user", "pass","domain");
var response = (HttpWebResponse)request.GetResponse();
var statusCode = response.StatusCode;
if (statusCode == HttpStatusCode.OK)
{
    var configuration = Configuration.Default.WithCookies().WithDefaultLoader();
    var context = BrowsingContext.New(configuration);
   await context.OpenAsync(url);
}
```
But i obtain 401(not authorised) from server.
How can i achieve this?

**Comment by FlorianRappl** [comment]
The code is incomplete.

Besides the code not being a MWE you should also include the network credentials in the requester used by AngleSharp. The way you illustrated there you are just repeating the same request, but without the credentials.

And btw: You are not using cookies here. You want to authenticate via NTLM as far as I can see it.

**Comment by Memphis19** [comment]
then, How can i include the network credentials in the AngleSharp request?
A simple example is appreciated.

**Comment by FlorianRappl** [comment]
Either you implement your own `IRequester` or use AngleSharp.Io with the HTTP Client and the ability to bring in your own client handler.

Code below to cover your case:

```cs
var credentials = new NetworkCredential("user", "pass", "domain");
var handler = new HttpClientHandler { Credentials = credentials };
var config = Configuration.Default.WithRequesters(handler).WithCookies();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(url);
// ...
```

**Comment by NorDroN** [comment]
I can't find method WithRequesters.
Could you give full example how it'll work?

**Comment by pkudrel** [comment]
WithRequesters is an extension in AngleSharp.Io package.

**Comment by NorDroN** [comment]
THNX, but unfortunately it's supporting only net45 now. 
I hope it'll be fixed soon - https://github.com/AngleSharp/AngleSharp.Io/issues/9
