### ISSUE TITLE
Incorrectly parsed Html

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#52]
Using the AngleSharp html parser on the file below causes an invalid attribute node to be created.
The attribute name is something line "\\documentary".

(Btw, the content is from a [news article](http://www.irishcentral.com/roots/history/Irish-documentary-exposes-93-year-old-woman-as-a-Holocaust-suspect-.html) in the Irish Times.)
https://www.dropbox.com/s/9joo87xf05ssynw/error_in_attribute.html?dl=0

**Comment by FlorianRappl** [comment]
Thanks for the report - I will investigate this issue.

**Comment by FlorianRappl** [comment]
Hm I cannot reproduce this issue. Can you confirm that the following selector gets the element which causes the possible problems: `document.QuerySelector("img.img-responsive")`?

I pretty much compared AngleSharp's result with the current results delivered by the Blink engine (Opera 28) and both are the same. Am I missing something?

**Comment by corliss** [comment]
Yes, that's the one. It has an attribute named documentary.\" that includes the period, backslash and quote. I'm using the nuget assembly, version 0.7.0.37131. Is that too old?

**Comment by corliss** [comment]
I updated the assembly and verified that the same problem occurs with 0.8.1 as well.
Incidentally, I'm reading the file with 
   `var html = File.ReadAllText(filename).`
And parsing with an empty `Configuration` object.

Also: Windows 8.1, .net 4.5.

**Comment by FlorianRappl** [comment]
It's supposed to be like that. So this is not an issue, but rather one of HTML's "features". Please compare to the implementations in all HTML5 conforming browsers.

**Comment by corliss** [comment]
Just so I understand, could you explain this a bit more please?

**Comment by FlorianRappl** [comment]
Well, what else is there to say. I could write about tokenization in HTML5 documents, but all you need to know is that the given snippet that is responsible for the image element generation contains a dot and a backslash, which are legal characters in an attribute name. Also quotation marks are allowed. However, quotation marks (among some other characters) are parse errors.

These errors will never result in an exception or anything bad, but are indications that the page might not result in the desired tree.

HTML5 contains a lot of "features" that are included to be as backward compatible (not only with HTML, but also with former HTML error correction which was freely implemented by browser vendors, as there was no official error correction) as possible.

**Comment by corliss** [comment]
Understood. Some of my code converts the parsed Html into Xml (i.e. x-html) so I guess I'll have to eliminate tags that are unrecognized.

Great job on compatibility with the standard HTML5 parsing algorithm.
