### ISSUE TITLE
Get response size

### ISSUE THREAD

**Issue by oliverwhk** [AngleSharp/AngleSharp#520]
This is how I get the document object:

`var document = await _context.OpenAsync(PAGE_URL);`

Is there a way to get content length off the response header?

Thanks

**Comment by FlorianRappl** [comment]
Not with the way how you do it. Only the requester knows this, so either wrap the existing one or implement your own (`IRequester`). I think the one in `AngleSharp.Io` can be easy customized w/o doing much work.

Hope this helps!

**Comment by oliverwhk** [comment]
Thanks, I saw the example code from Unit Test, which looks like:

```
var httpClient = new HttpClient();
var requester = new HttpClientRequester(httpClient);
var configuration = Configuration.Default.With(requester).WithDefaultLoader();
var context = BrowsingContext.New(configuration);
var request = DocumentRequest.Get(Url.Create("http://httpbin.org/html"));

var response = await context.GetService<IDocumentLoader>().FetchAsync(request).Task;
var contentLength = int.Parse(response.Headers["Content-Length"]);
```

**Comment by FlorianRappl** [comment]
That works! But keep in mind that no document has been processed yet (only the response has been delivered w/o processing the body).

**Comment by oliverwhk** [comment]
Yup, saw in the code there is a separate line to process the document. Thx
