### ISSUE TITLE
Angle Sharp sample breaks when browsing local HTML static files

### ISSUE THREAD

**Issue by weedkiller** [AngleSharp/AngleSharp#521]
Hi, 

1. I added a file browser near the go button on top, to support browsing of browse local HTML files and when I browse local html files it breaks.

2. In the query section, I was also trying to add a listener , where when I clicked on the div, it would show the _query text for the element clicked_ in the textbox below for  the Xpath or QuerySelector of the Div with the attributes, what function code would give me that?

![image](https://cloud.githubusercontent.com/assets/21086190/22393997/ff77750a-e4e1-11e6-8723-c56e53cc9977.png)

3. Can you tell me how to add my own functions, like comments or strings, currently its mostly HTML elements and I would like to extend and write to the DOM tree

 Is the Dom and IDocument the same in the sample, or are they different pruposed?

thanks

**Comment by FlorianRappl** [comment]
DOM = Document Object Model. `IDocument` is the document interface of the DOM. Thus the DOM contains the `IDocument`, and the `IDocument` is part of the DOM.

1. Can't say anything about your changes. You need either a valid `file:` path (be sure to have a proper requester set up for that) or process the text or stream content of the file.
2. There is no such thing. You entered the query right? So the query is the same thing as you entered. If you would select some element then there is no *one* query for that. Multiple queries may lead to that element and thus one cannot show a particular query to end up with one element (plus the query may break if the DOM changes, so this is impossible).
3. I don't understand this question. Comments and text are part of the DOM and available in AngleSharp.
