### ISSUE TITLE
Settings for parsing raw HTML, and how to get element path from root?

### ISSUE THREAD

**Issue by VoidMonk** [AngleSharp/AngleSharp#527]
Hi, I have two questions:

1. If we were to parse some raw HTML, like `new HtmlParser().Parse(html)`, where `html` is a string with some raw HTML as text (in UTF-8 or other relevant charset encoding), then are any other settings (`options` or `configuration`) needed to make the DOM parser work best/optimized?

2. Given an element (`IElement`), is it possible to get its path or depth (from root)? For example, CsQuery can return a numeric array `NodePath` ([code reference here](https://github.com/jamietre/CsQuery/blob/5a22e28a39c139cbb8170a0eeeee59e73f9e02f9/source/CsQuery/Dom/Implementation/DomObject.cs#L163)), and other DOM parsers have similar APIs.

Thanks!

**Comment by FlorianRappl** [comment]
1. I don't think so, but I would highly recommend using `BrowsingContext`. It's created anyway and it allows you to select (add or remove) services that are being used (btw if you pass in a `String` it is always UTF-16, otherwise you pass in a `Stream`).
2. The code for such a functionality is like 3 or 4 lines. What is your root? The document root or the `body` element? Maybe some other element? I guess the `Ancestors` extensions is what you are looking for. It returns an iterator such that you could do `myelement.Ancestors().ToArray()` in order to get all the ancestor elements.

HTH!

**Comment by VoidMonk** [comment]
Thanks Florian. Regarding the path from root (`body`), I didn't mean a list of parent elements but rather a list of positions from the root till that element.

For example, given the sample HTML fragment below, if the selected element is `div > article > p`, then is there a way to get or build an array like `[001, 002, 001]` denoting its ancestors position and its own position (last in array) from root?

```html
<body>
    <div>
        <div>
            <h1>...</h1>
        </div>
        <article>
            <h2>...</h2>
            <p>...</p>
            <span>...</span>
        </article>
        <div>
            <h4>...</h4>
            <span>...</span>
        </div>
    </div>
</body>
```

**Comment by FlorianRappl** [comment]
There is the index helper. Just use Linq (`Select`) with the statement above?

From your example I assume you refer to elements (`Children` for indices. Otherwise the text nodes would be counted in).

```cs
myelement
  .Ancestors()
  .Where(node => node.ParentElement != null)
  .Select(element => element.ParentElement.Children.Index(element))
  .ToArray()
```

**Comment by VoidMonk** [comment]
Cool, thanks. The index extension is what I was looking for. But, `myelement.Ancestors()` returns parents' siblings as well: `[ article, div, div, div, body, html ]`. Anyway, to just get the element parents (hierarchy) like: `[ article, div, body, html ]`.

**Comment by VoidMonk** [comment]
My bad. Sample HTML was invalid (missing closing `div` tag).

Thanks again!

**Comment by FlorianRappl** [comment]
Glad I could help!
