### ISSUE TITLE
System.InvalidOperationException, EUC-JP is not a supported.

### ISSUE THREAD

**Issue by NishiokaTakeo** [AngleSharp/AngleSharp#528]
Hi, I am facing this error in the DotNET Core version.

{System.InvalidOperationException: The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set. ---> System.ArgumentException: 'EUC-JP' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at System.Net.Http.HttpContent.ReadBufferedContentAsString()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.ReadBufferedContentAsString()
   at System.Net.Http.HttpContent.<>c.<ReadAsStringAsync>b__36_0(HttpContent s)
   at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__62`2.MoveNext()}

Here is more information.
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

How can I avoid this problem ? Thanks.

**Comment by FlorianRappl** [comment]
Please show me the code to reproduce this. I find it rather unlikely that the problem originates from AngleSharp (if so then I did not use the `TextEncoding` helper to get the encoding - as this one will fall back to UTF-8 when the encoding is not available).

I see a lot of `HttpContent` calls in there, apparently `ReadBufferedContentAsString` is used (AngleSharp does not read the string though, but rather the stream directly).
