### ISSUE TITLE
Find which selector matched each element

### ISSUE THREAD

**Issue by VoidMonk** [AngleSharp/AngleSharp#529]
Hi, if some elements match `document.QuerySelectorAll("h2, span.row, div > p")` (which has multiple selectors), then is it possible to find out which selector matched each individual element? I see there's a `Matches` method, but that will require it to be run again on each matched element, multiple times (one for each selector).

**Comment by FlorianRappl** [comment]
Nope, elements have no clue that they have been retrieved from a selector, thus there is no relationship between the selector and the element.

However, I think you can implement that yourself.

In the current version of AngleSharp you'll split the selector string into the different selector substrings, generate an `ISelector` for each selector substring, iterate over all elements in the document and use the matches method for each generated selector.

In the upcoming version of AngleSharp you can generate an `ISelector` once and get the different contained selectors. Then you perform the iteration as currently.
