### ISSUE TITLE
PrettyMarkupFormatter adds unexpected whitespace into tags

### ISSUE THREAD

**Issue by duncanawoods** [AngleSharp/AngleSharp#531]
AngleSharp 0.9.9

Hi,

I'm finding PrettyMarkupFormatter is producing inconsistent whitespace and changing tag content e.g I'm expecting this code:

            var parser = new HtmlParser();
            
            var document = parser.Parse("<html><head></head><body><i></i></body></html>");

            var sw = new StringWriter();
            document.ToHtml(sw, new PrettyMarkupFormatter());

            Console.Write(sw.ToString());

To produce this

	<html>
		<head>
		</head>
		<body>
			<i></i>
		</body>
	</html>

But it adds whitespace into the tag to produce this:

	<html>
		<head>
		</head>
		<body>
			<i>		</i>
		</body>
	</html>

Is this intentional, can it be controlled? I suspect its a bug because the following shows it indent the same tag inconsistently e.g.

            var parser = new HtmlParser();

            var document = parser.Parse("<html><head></head><body><script src=\"//ajax.aspnetcdn.com/ajax/bootstrap/3.0.1/bootstrap.min.js\"></script><script src=\"//ajax.aspnetcdn.com/ajax/bootstrap/3.0.1/bootstrap.min.js\"></script></body></html>");

            var sw = new StringWriter();
            document.ToHtml(sw, new PrettyMarkupFormatter());

            Console.Write(sw.ToString());

Produces

	<html>
		<head>
		</head>
		<body>
			<script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.1/bootstrap.min.js">
			</script>
			<script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.1/bootstrap.min.js">		</script>
		</body>
	</html>

**Comment by FlorianRappl** [comment]
Yes, seems like a bug to me. It should be properly indented. I will also include this in the v0.10 scope!

Thanks for the report 👍 !

**Comment by duncanawoods** [comment]
Thanks, you are a star!

**Comment by duncanawoods** [comment]
Similar issue that is probably related, extra lines between null elements

            var parser = new HtmlParser();

            var document = parser.Parse("<html><head><meta name=\"this\" content=\"that\"><meta name=\"this\" content=\"that\"></head><body></body></html>");

            var sw = new StringWriter();
            document.ToHtml(sw, new PrettyMarkupFormatter());

            Console.Write(sw.ToString());

Creates

	<html>
		<head>
			<meta name="this" content="that">
			
			<meta name="this" content="that">		
		</head>
		<body>	</body>
	</html>

**Comment by FlorianRappl** [comment]
Will include this one in the test cases - thanks!

**Comment by duncanawoods** [comment]
One more test case for you. I just tried pushing already formatted html through it and the results were... troubled.

            var parser = new HtmlParser();

            var indented =
	@"
	<html>
		<head>
			<meta name=""this"" content=""that"">
			<meta name=""this"" content=""that"">
		</head>
		<body>
		</body>
	</html>
	";

            var document = parser.Parse(indented);

            var sw = new StringWriter();
            document.ToHtml(sw, new PrettyMarkupFormatter());

            Console.Write(sw.ToString());

Produces

	<html>
		<head>         <meta name="this" content="that">		         <meta name="this" content="that">		     </head>     <body>       </body>
	</html>

**Comment by FlorianRappl** [comment]
I am not sure about the last test case. The issue here is that text content should be / will be preserved. We can talk about reducing s+ to s (s = any whitespace character), but beyond that a wrong visual representation may be the result. That being said, the pretty markup formatter could anyway result in a wrong visual representation (when re-consumed in a browser) as it already adds some whitespace.

I'll see what I can do about it.

**Comment by FlorianRappl** [comment]
Fixed, see PR #533. Please check with the test cases if the behavior satisfies your needs, or if you see anything else that was not considered or seems undesired.

**Comment by duncanawoods** [comment]
Thanks, looks better. There are lots of tricky format conditions that are not tested e.g. scripts, text nodes, commented out elements etc.

One thought, perhaps also assert that it is idempotent i.e. pretty(html) == pretty(pretty(html)). You could switch in a custom assert for that and any other desirable constraints e.g.

    private static void AssertPretty(string expected, string html)
    {
        var result = Print(html);
        var twice = Print(result);
        Assert.AreEqual(expected, result);
        Assert.AreEqual(expected, twice);
    }

**Comment by FlorianRappl** [comment]
Idempotency preservation is not relevant imho - HTML itself is not idempotent (by the specification). The pretty printer does not aim to be better than the standard itself.

The pretty markup formatter also does not try to be the ultimate solution, but a rather handy way of getting an opinionated pretty print with some options.

The edge cases you referred to are covered by the defaults in some way. If there is something terrible ill ongoing I will definitely fix it. If its just about aesthetics I probably won't go for it.

Thanks for the input!
