### ISSUE TITLE
HtmlDomBuilder Deadlock issue

### ISSUE THREAD

**Issue by atefshehata** [AngleSharp/AngleSharp#536]
Hi,

I’m trying to integrate Chakra JavaScript engine with AngleSharp. Till now, the integration goes well except for some issues. The most annoying one is a deadlock issue occurs in HtmlDomBuilder when parsing document fragments initiated from JavaScript code.

Here are some details about this issue:

- When HtmlDomBuilder encounters a script, it fires EvaluateScriptAsync to execute the script.

- If the script has some statements that modify or create new document fragments such as setting innerHtml, the parser will create a new document fragment and start to parse it using HtmlDomBuilder.Parse().

- This will deadlock because the parser logic in HtmlDomBuilder.Parse() is waiting for EvaluateScriptAsync to complete before finishing the parse of the new document fragment, while in the same time, EvaluateScriptAsync can’t finish until it executes the setter of innerHtml and subsequent code; which in turn causes a dead lock.

What do you think is the best solution for this deadlock? Given that The execution of javascripts must be performed in a single thread.

Regards,
Atef

**Comment by FlorianRappl** [comment]
I am not seeing the deadlock. We are talking about two different instances of the `HtmlDomBuilder` here. They don't know of each other. Am I missing something?

So its not A -> B and B -> A, but rather A1 -> B and B -> A2, so I see no reason that the latter should not be able to finish thus allowing the former to be processed completely.

Can you add a MWE (should be independent of your specific scenario and targeted at the problem alone)?

In any case - thanks for the report. If its indeed a deadlock it needs to removed asap. Therefore any input would be highly appreciated! 👍

**Comment by atefshehata** [comment]
Thanks for your reply,

I know they are different instances, but the fact that the code must be executed in a single thread is the main reason for the lock.

Unfortunately, writing a MWE may take some days to complete as I need to strip out a lot of code from several dependent projects.

I’ll try to describe the important steps in my code; I believe it will let you get to the cause of the issue.

- The most important constraint is the fact that JavaScript engines are single threaded, so all code must be executed in a single/same thread.

- In my code, I have an ExecutionContext that acts as a message loop for queuing and executing JavaScript code.

- At startup, JS engine is started and my ExecutionContext is created and the message loop is started.

- A call to EvaluateScriptAsync leads to creation of JavaScriptTask and queues it in the queue of the execution context. JavaScriptTask is a simple container for executing different types of JavaScript code such as plain source code, callbacks/events and etc.

- The JavaScriptTask holds a reference to internal Task object that will be completed upon execution.

- EvaluateScriptAsync returns that internal task (JavaScriptTask.Task)

- Later, the message loop pulls the available JavaScriptTask(s), switch to the correct JavaScript Context and then execute each task in its context (one by one in sequential order). There is no locking at all of the above steps. The only note here is that: execution of JavaScriptTask(s) is of course synchronous. Upon execution, the internal task of JavaScriptTask is flagged as complete.

I looked at HtmlDomBuilder to double check the issue again, and I can confirm the deadlock issue.
Here are some extra details not mentioned in my previous comment. The lock happens in this exact scenario:

- Start with parsing a top document using HtmlDomBuilder.ParseAsync()

- Some JavaScript code sets InnerHtml to some value which leads to creation of a new DocumentFragment

- The created document fragment start to parse using HtmlDomBuilder.Parse(), as you know Parse() is a synchronous method. **During this phase it hits some other scripts** (in the document fragment) and then it asks for the execution of theses scripts using EvaluateScriptAsync.

- At the end of the parse, the parser calls HtmlDomBuilder.End() method which in turns executes the following code:
` _waiting = _document.FinishLoadingAsync();`

FinishLoadingAsync() as you know is waiting for all pending tasks to complete and while it is waiting, the HtmlDomBuilder.Parse() method will also wait for that task to complete (waiting on _waiting). Here is the code which create the lock:

`do
 {
    token = _tokenizer.Get();
    Consume(token);

     _waiting?.Wait();
    _waiting = null;
  }
 while (token.Type != HtmlTokenType.EndOfFile); `

The problem here is that: FinishLoadingAsync() is waiting for pending tasks to complete (JS execution tasks). In my debugging session, I see three pending tasks. The first one is the task created for the code which sets the innerHtml. The other two tasks are subsequent JS execution tasks created while parsing the document fragment.

So, the _waiting?.Wait(); is waiting for the three tasks to complete while in the same time it blocks the code which sets innerHtml to complete. Which in turn blocks the other two scripts from being executed (JS execution is done one by one). 

To better describe the problem: on my execution context; the message loop has three tasks, one is being executed and can’t complete due to the wait() lock and the other two tasks are queued which means that FinishLoadingAsync will wait for the three tasks forever.

Here is a screenshot of the call stack of the running thread taken upon lock
![lock](https://cloud.githubusercontent.com/assets/24980454/23000877/d2553b88-f3e2-11e6-848b-031230b32e6b.jpg)

I have some other minor issues as well, but nothing is much important, most of them are just exposing some classes and methods. I had to update the source code (which I don’t like to keep my source up to date and compatible with your future updates). I’ll try to compile all of these minor issues after completing the integration project and performing more tests against complex web sites.

Regards,
Atef

**Comment by FlorianRappl** [comment]
That's quite some text. But I just want to go into the most important one here:

> I know they are different instances, but the fact that the code must be executed in a single thread is the main reason for the lock.

That is not true. First of all, JS code is normally run in a reactor, which gives you a single thread of execution (true), but does not apply to external code being forced to run in the same thread. Thus, your JS code should run in a different thread than the main code (incl. the parser).

Real browsers have multiple threads per tab - one is reserved for JavaScript and that one is never blocking parsing (parsers may wait for scripts to be finished due to historical reasons, but technically they could just go without any interruption). Ideally, your script engine is running in its own thread.

Generally, I would advise you to use the async methods (they are the preferred choice; the other one is available for convenience and as you have seen may be problematic for scripts which need others threads). I am not sure how to solve this with the sync methods. The problem arises by definition from my POV.

**Comment by atefshehata** [comment]
I don’t usually have time to comment nor write any posts, but because AngleSharp is a promising project, I have to take some time to give a minimal help. That is why you see some long text !!

> That is not true. First of all, JS code is normally run in a reactor, which gives you a single thread of execution (true), but does not apply to external code being forced to run in the same thread. Thus, your JS code should run in a different thread than the main code (incl. the parser).

Please don’t take my words literally; I believe we all know how multithreading should work. What I meant here is that: execution in single thread is what causing the problem, because calling recursive synchronous methods in a single thread and waiting for the completion may easily introduce a dead lock.

In addition, the last statement is not correct “Thus, your JS code should run in a different thread than the main code (incl. the parser)”.

Off course, JavaScript Engine is running in a different thread, and the initial parser request is also running is a different thread, but this is not correct when the parser is then initiated by a call from JavaScript code such as innerHTML or other dynamic methods such as Document.Write and etc. The code that is initiated from JavaScript thread must complete synchronously in that thread (including the parser). The only exception is when using JavaScript promises which is not the case here.

> Generally, I would advise you to use the async methods (they are the preferred choice; the other one is available for convenience and as you have seen may be problematic for scripts which need others threads). I am not sure how to solve this with the sync methods. The problem arises by definition from my POV

What async methods? Parsing of DocumentFragment must complete synchronously, please don’t forget that the parser is started by setting innerHtml or using Document.Write from within a JavaScript source code. We don’t have control to change this (and we shouldn’t change it, code must complete synchronously)

> Real browsers have multiple threads per tab - one is reserved for JavaScript and that one is never blocking parsing (parsers may wait for scripts to be finished due to historical reasons, but technically they could just go without any interruption). Ideally, your script engine is running in its own thread

Real browsers may block parser if the parser is not taking into consideration all implementation requirements. For example, if the parse doesn’t correctly implement script’s async or defer then it may block the parser. Here is a quoted statement from [https://developer.mozilla.org/en/docs/Web/HTML/Element/script](url)

> In older browsers that don't support the async attribute, parser-inserted scripts **block the parser**; script-inserted scripts execute asynchronously in IE and WebKit, but synchronously in Opera and pre-4.0 Firefox. In Firefox 4.0, the async DOM property defaults to true for script-created scripts, so the default behavior matches the behavior of IE and WebKit”
“Starting in Gecko 2.0 (Firefox 4 / Thunderbird 3.3 / SeaMonkey 2.1), inserting script elements that have been created by calling document.createElement("script") into the DOM no longer enforces execution in insertion order. This change lets Gecko properly abide by the HTML5 specification. To make script-inserted external scripts execute in their insertion order, set .async=false on them

Finally, I noticed that when loading the page that causes the parser to block, the execution order of JavaScripts using AngleSharp differ than what I see in IE or chrome. This notice, and also the above quoted statements let me look at how AngleSharp handle dynamic scripts. 

The case that causes the parser to block has a dynamic script with the async flag set to true, but AngleSharp was loading it synchronously which blocks the parser as mentioned in previous comments. I did a small modification to force dynamically created scripts to set its “parser-inserted” flag to true which solve the blocking issue partially (it blocks in later script, which I didn't investigate the reason yet)

This is just a quick test, not a solution, thus I think you need to double check the logic that set “parser-inserted” and the preparation/invocation for dynamic html script elements.

BTW, please consider this as a notification, you don’t have to act. We usually can modify the code directly, but I believe you deserve to be aware about the critical issues at least.

Good luck,
Atef

**Comment by FlorianRappl** [comment]
If you see that the order is different then please supply a MWE. Otherwise, it is hard to judge if that is a subjective or objective POV. The tests I supplied are valid (but may not be complete).

Also I think you missed the point with async. I was *not* referring to the async attribute, but obviously to Async-Suffixed parsing methods (not implying the usage of the document fragement). As far as I can tell you invoked the whole parsing synchronously. Maybe I am misinterpreting your initial post - but then please show code it's the only undeniable truth.

> We usually can modify the code directly, but I believe you deserve to be aware about the critical issues at least.

I don't know how to interpret that. If something is wrong the way is to submit a PR (that is also the only correct way if you care about an OSS project). Otherwise you will always be most likely in trouble with future releases.

I would still like to see and solve the issue, but you need to give me more than words. Show a MWE that can reproduce the issue and we are on. Thanks 👍 .

**Comment by atefshehata** [comment]
Sorry to say that, but really you surprise me with every reply!!

> Also I think you missed the point with async. I was not referring to the async attribute, but obviously to Async-Suffixed parsing methods (not implying the usage of the document fragement). As far as I can tell you invoked the whole parsing synchronously. Maybe I am misinterpreting your initial post - but then please show code it's the only undeniable truth

I said in replying to your recommendation about async methods that the Parse() method is called from within a JavaScriptCode as a result for setting innerHtml. This means that we have no control over changing this to ParseAsync() variant (even if we have control we should not change it to async because synchronous call is the correct way to continue the execution in JavaScript context, except for promises), otherwise, subsequent JavaScript code will not get the expected result. 

Also, who said that I have invoked the whole parsing synchromously? I said that the JavaScript execution context is started in its thread and the initial Parse() request is also started in its thread. I didn’t mention that I’m using BrowsingContext.OpenAsync() which will call ParseAsync(), but there is no need to mention that and it should go without saying. Also it doesn’t matter as setting the innerHtml will always call the synchronous parse regardless from the initial context.

Finally, to make sure you got how the parser is called; here is a pseudo call sequence:

From JavaScript Context, some code set innerHtml
…
div. innerHtml="some html";
...
// Some other JS code that will access the dynamically created elements

Setting the innerHtml will forward the call to Native Context (C# code)

Element.InnerHtml 
{
        set { ReplaceAll(new DocumentFragment(this, value), false); }
}
DocumentFragment.ctor()
{	
	…
       var root = parser.ParseFragment(options, context).DocumentElement;
}

HtmlDomBuilder. ParseFragment()
{
	…
       return Parse(options);
}

And finally it goes to
HtmlDomBuilder.Parse()

After completion of Parse(), the call will return back to JavaScript Context to execute the rest of JS code

//Some other JS code that will access the dynamically created elements

I hope the picture is clear now.

> I don't know how to interpret that. If something is wrong the way is to submit a PR (that is also the only correct way if you care about an OSS project). Otherwise you will always be most likely in trouble with future releases.

Again, you surprised me!! I said that I didn’t like to directly modify the code and want to keep up to date with future releases, and Also I said that you “DESERVE” which means “RESPECT”, and I said I'm trying to give a minimal help; what else should I say!! 
 
Finally, I didn’t give you words; I gave you obvious observations and my modest explanations for the issue. Also I said that I can’t build MWE as it will take time to prepare it from large number of dependent projects. Actually, I have more than 25 projects composing my full foundations which I’m building for more than 6 years. Believe me it is not that easy.

Frankly, the problem is very obvious and it doesn’t need all of these comments and efforts. Did you read the link about behavior of modern browsers to avoid blocking? Did you check whether AngleSharp defaults dynamically added scripts to be asynchronously executed? You didn’t mention a word about that.

I can feel your resistance. It is Okay, you are the author and it is your decision. That is why I always keep myself away from giving comments to OSS. Just, I was trying to help.

Please feel free to close this issue if you want; let’s go forward and safe our precious time. 

Good luck,
Atef

**Comment by FlorianRappl** [comment]
> I can feel your resistance. It is Okay, you are the author and it is your decision. That is why I always keep myself away from giving comments to OSS. Just, I was trying to help.

I think you still don't get the point. We are surely talking in different directions here. Please look at the reference implementation for a JS engine using AS and you will see that the script execution is done in another thread. I am not seeing this done here, but then again you did not show much for me to get to know the details. I was also just trying to understand the issue...

An MWE (see [Wikipedia](https://en.wikipedia.org/wiki/Minimal_Working_Example)) is a snippet of code I can reuse without having to make any assumptions. You start directly in the loop. I am not sure if you need to include all the things from over 6 years in it. I actually doubt it - but its alright. The parts you showed in your last post are all redundant - I clearly stated that I am aware of the fact that the document fragment is being called synchronously. This is not the crucial point.

Sorry if you felt being left out - your attitude here feels a little bit wrong to me. Also quoting things I do know seemed inappropriate (but I skipped over it as you clearly wanted to discuss some issue that concerned you).
