### ISSUE TITLE
Css parsing: no way to see if a specific style property is inherited or explicit

### ISSUE THREAD

**Issue by bluecat76** [AngleSharp/AngleSharp#537]
### Use case
My use case is to read a CSS file via Anglesharp CssParser, storing the rule/declaration structure and at a later time using the stored structure to generate output with a custom CssStyleFormatter.

### Issue
Anglesharp does expand shorthand properties (e.g. background) to specific properties (background-image, background-color, etc.) which is a good thing.
My problem is, that some properties default to the value "initial", and I can see no way to distinguish between a value that was not explicitly given or a specific value of "initial".  

This normally is no problem, because if I produce output of the same parsed stylesheet, no "initial" values are written. I think this is because internally (in `CssProperty`), there  is a flag `PropertyFlags.Inherited` which denotes, that the "initial" value is not explicit, but I cannot read the flag from the`ICssProperty` interface.

### Example
Here is my MWE to illustrate the case:

```csharp
var parser = new AngleSharp.Parser.Css.CssParser();

string css_in = "body { background: url(\"//foo.bar/baz\"); }";

var stylesheet = parser.ParseStylesheet(css_in);

foreach (ICssRule rule in stylesheet.Rules)
{
    if (rule.Type == CssRuleType.Style)
    {
        var style = (ICssStyleRule)rule;
        
        foreach (ICssProperty decl in style.Style)
        {
            Console.WriteLine(String.Format("STYLE {0}: {1}", decl.Name, decl.Value));
        }
    }
}
```
Output (Anglesharp Version: 0.9.9.0):
```
STYLE background-attachment: initial
STYLE background-clip: initial
STYLE background-color: initial
STYLE background-image: url("//foo.bar/baz")
STYLE background-origin: initial
STYLE background-position: initial
STYLE background-repeat: initial
STYLE background-size: initial
```

### Possible Solution
The solution I came up with would be to expose a function in `ICssProperty` to check, if the property was inferred or explicitly set (like `hasValue` maybe). 

I would be very interested in your opinion on this. Thanks.

**Comment by FlorianRappl** [comment]
Hi, thanks for posting the question.

With the upcoming v0.10 version of AngleSharp the CSS part will be extension living in its own repository. The repository is already available with the code being in flux (see https://github.com/AngleSharp/AngleSharp.Css). Therefore, if this question will resolve in a feature request / bug / or anything else to consider in the backlog I will create the respective issue(s) in the new repository (just that you know).

The described behavior will change with the new version of the CSS library. Nevertheless, I'll try to describe why this is happening and how you can work against it:

- CSS contains two types of properties - longhand and shorthand. In your declaration (from the example) you use the shorthand, which allows you to combine several longhand declarations into one (Note: a declaration is the assignment of a property to a value).
- To recognize overrides in a fast way (e.g., `background: red; background-color: white`) AngleSharp detects that the given declaration corresponds to a shorthand and performs an expansion (obtaining all contained longhands).
- Internally, AngleSharp stores the longhand properties in a list - the flag is fixed (i.e., it is property bound and not declaration bound) and will not be touched.
- When AngleSharp is asked to print a string that corresponds to the style declaration (containing all the declarations for a selector or element) it will follow the W3C algorithm for serialization. Thus, it always looks for potential declarations to be re-combined (collapsed) into a shorthand.

As you can see, it is rather algorithmic that the serialization prints out the "right" thing, while the full iteration yields all kinds of (unwanted) details to you.

Workaround: The internal `CssProperty` class has a property called `HasValue`. Essentially, this property checks if a value has been assigned or not. In explicit declarations `foo: initial;` there is a value (`Initial`), but in expanded declarations w/o the corresponding longhand value there is nothing. Unfortunately, this one is `internal` (not exposed via the `ICssProperty` interface. However, you can access it via reflection.

Hope this helps!

**Comment by bluecat76** [comment]
OK, thanks for the elaborate response. I'm looking forward for the 0.10 release to try out the new CSS engine. 

Followup question: is 'initial' the correct value for uninitialized fallbacks? I thought maybe it should be 'inherited'?

**Comment by FlorianRappl** [comment]
Initial is the same as inherited if inherited is a possible state of the declaration (some properties cannot be inherited; these are missing the flag that you mentioned earlier).

Remark: To unset / remove the inheritance there are `unset` and `revert` (but I think none of these two are supported in the current AngleSharp implementation - `unset` is supported in the new one though).

**Comment by bluecat76** [comment]
Ah, that's clear now, thank you.
