### ISSUE TITLE
Element with style "display:none" should have IsHidden as true

### ISSUE THREAD

**Issue by mdarabi** [AngleSharp/AngleSharp#538]
Hi, 
I am not sure it is a bug or I missed some thing but when an html element has style value of "display:none" the IsHidden property should be true which is not in the current version.

**Comment by FlorianRappl** [comment]
There is no relation between these two.

```html
<!DOCTYPE html>
<body style="display:none">
</body>
<script>
console.log(document.querySelector('body').hidden);
</script>
```

This one will log `false`.

**Comment by mdarabi** [comment]
Thanks for the explanation.
