### ISSUE TITLE
Anglesharp can't handle Cookie "Path" properly

### ISSUE THREAD

**Issue by tvildo** [AngleSharp/AngleSharp#539]
Website can set cookie specific to path.  Leatest version of Anglesharp 0.9.9 contains Bug and do not handles cookie path properly.

1. response `http://example.com` sets cookie : `sessionid=ABC1; path=/`
2. response `http://example.com/document` sets cookie: `sessionid=ABC2; path=/document`

Than request `http://example.com/document?somethins=234` should include cookie: `sessionid=ABC; sessionid=ABC2;`

**Comment by FlorianRappl** [comment]
I believe this is a duplicate. See #431, #519, and #477.  See PR #522 and #488. Please check `devel` first.
