### ISSUE TITLE
Smart ToString overrides for AngleSharp.Url and other classes

### ISSUE THREAD

**Issue by thorn0** [AngleSharp/AngleSharp#54]
It's something that is natural to expect. And the newer .NET APIs have it. For example

``` c#
XElement.Parse("<x/>").ToString()
```

gives us

```
<x />
```

I would expect an alike behaviour from AngleSharp.Url, IHtmlElement etc.

**Comment by FlorianRappl** [comment]
That depends. There are a lot of questions. Do you want the inner HTML ? The outer HTML ? Only the element (with no children) ? Do you just want to know the name of element ? 

The natural stringification of a DOM element is the name of the representing interface. Therefore this is a topic that raises more questions than answers. Everyone expects something different from `ToString()`, as there are many possible strings that can be created.

Also this is quite fishy in the code. If I have the choice of using `foo.InnerHtml` vs `foo.ToString()` I will always prefer the first one. Reason? It is obvious from the naming what will be the behavior. Therefore my recommendation is to stay with the obvious choices (e.g. `Href` for `Url`, `OuterHtml` for `IHtmlElement`, etc.).

**Comment by thorn0** [comment]
I expected it to be the outer HTML just because XElement does this.

**Comment by thorn0** [comment]
And what about URLs? Why is `Href` better than `ToString`? Might different people expect different results from `url.ToString()`? It looks unambiguous to me.

**Comment by FlorianRappl** [comment]
I agree, for an URL it looks fine to me.
