### ISSUE TITLE
[Question] How to set the baseUrl

### ISSUE THREAD

**Issue by wjzhou** [AngleSharp/AngleSharp#541]
Thank you for this this fantastic project.

I have a question about setting the baseUrl for document from string. (or make the link relative to a site)
I can find some reference about DocumentBuilder, which doesn't exist in the current version.

**Comment by FlorianRappl** [comment]
There are several ways to do that - it all depends on your use-case. Assuming you have some HTML source and you want to parse it + additionally set the URL as-if the page was loaded from that URL you can do as follows:

```cs
var configuration = Configuration.Default;
var context = BrowsingContext.New(configuration);
var document = await context.OpenAsync(res => res.Content(yourSource).Address(baseUrl));
```

Essentially, the callback style is a "virtual response", i.e., it gives you possibility to construct a full response like it could be send from a server.

Does that cover your use-case or am I on the wrong track here?

**Comment by wjzhou** [comment]
Thank you very much.
This is exactly what I'm looking for and fast.

I came across this code before, I was not sure this is the recommended way to set the baseUrl.
Maybe, it will be helpful for others if we add it to the document.
