### ISSUE TITLE
Make CachePolicy configurable for HttpRequester

### ISSUE THREAD

**Issue by appel1** [AngleSharp/AngleSharp#542]
See https://msdn.microsoft.com/en-us/library/system.net.webrequest.cachepolicy(v=vs.110).aspx

**Comment by FlorianRappl** [comment]
I am not sure if this is part of the PCL (actually I doubt it). Also - even if it would be: The default `HttpRequester` is just that - a default (opinionated) version. If you have more advanced use cases then please consider implementing the `IRequester` interface in a custom class.

**Comment by appel1** [comment]
Ok.
