### ISSUE TITLE
StackOverflowException when parsing many invalid HTML Tags

### ISSUE THREAD

**Issue by aschiffmann** [AngleSharp/AngleSharp#543]
When parsing html which contains a lot (~21.000) invalid html tags, AngleSharp produces a StackOverflow exception.
Unfortunatly I cannot provide any code to reproduce it, because I am using the [HtmlSanitizer](https://github.com/mganss/HtmlSanitizer) lib, which again uses AngleSharp.

However I can provide the [sample HTML](http://pastebin.com/g4nsaUYh) which produces the stackoverflow and also a [screenshot](https://ibin.co/3ExBplOz9Knt.png) which shows, that the error is caused by AngleSharp itself.

I noticed, that this exception only happens when running the code within an IIS AppPool. When running it within an unitTest instead, the parsing (and sanitizing) runs without any problems in less than one second.

This bug is very crucial, because it can lead to a complete shutdown of an application and stackoverflow-exceptions are not easy to predict/catch.

Can you fix this issue or provide any workaround, so this won't happen when parsing large html within an IIS appPool?

**Comment by dennisgorelik** [comment]
See https://github.com/AngleSharp/AngleSharp/issues/523 and https://github.com/AngleSharp/AngleSharp/pull/524.

**Comment by FlorianRappl** [comment]
As @dennisgorelik mentioned this one should be solved within `devel`. Can you try that please? Otherwise, I'll try when I get the chance.

(yes, I know we are all still waiting for the next release, but I am currently heavily under load with some other stuff)

**Comment by mganss** [comment]
No, this does also occur in devel. Here's how to repro in a console app:

```C#
var parser = new HtmlParser();
var dom = parser.ParseDocument("<html><body></body></html>");
var h = string.Join("", Enumerable.Repeat("<xyz>", 50 * 1000));
dom.Body.InnerHtml = h;
```

This results in a StackOverflowException in `AngleSharp.Dom.Node.Owner.set` which calls itself recursively. If you change the HTML to this:

```C#
var h = string.Join("", Enumerable.Repeat("<xyz>", 50 * 1000)) + "<img src=\"http://www.example.com/\">";
```

Then the exception occurs in `AngleSharp.Dom.Node.BaseUrl.get`.

The reason why the sample by @aschiffmann faulted only in IIS and not in a console app is because the maximum thread stack size is 256K by default in IIS and 1MB in a console app. Here's how you can check (on Windows 8 and above):

```C#
[DllImport("kernel32.dll", SetLastError = true)]
static extern void GetCurrentThreadStackLimits(out uint lowLimit, out uint highLimit);

uint low;
uint high;

GetCurrentThreadStackLimits(out low, out high);
var size = (high - low) / 1024; // in KB
```

**Comment by FlorianRappl** [comment]
Thanks for the test @mganss. I will fix this bug in v0.10 (or anyone else - who finds the time to do so). 👍

**Comment by FlorianRappl** [comment]
Fixed, see PR #544. Thanks to @campersau 🎉 .

**Comment by aschiffmann** [comment]
@FlorianRappl Is there already a schedule for the release of version 0.10?
This bug is a major security issue when using this lib including all users of mganns/htmlSanitzier and we are desperately waiting for this fix to be released.
Thanks heaps!

**Comment by FlorianRappl** [comment]
There was, but currently I have way to much work to do... as such I cannot commit to this project currently, which postpones the v0.10 for at least 1 more month.

As already explained on other issues any contribution would be welcome to make v0.10 final. Volunteers are highly welcome and would get all help they need from my side to make it happen.
