### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by rzvdaniel** [AngleSharp/AngleSharp#545]
Hello Florian,

I just discovered this wonderful project and I would like to stay with it for a while. I don't know where I can ask questions, that's why I'm creating this (unnecessary) issue. Sorry for this.

I'm a software developer who's investigating the possibility to create a C#/OpenGL HTML/CSS renderer and use AngleSharp as parser because It looks very promising for my needs.

I would like to ask you few things like:

1. Where I can ask questions, when getting stuck with AngleSharp? :)

2. Is ComputeCurrentStyle() needed in order to have a Style property properly initialized for an HtmlElement? Without, the Style just looks uninitialized.

3. There is any support to translate the string Style properties to their hexadecimal, integer, float or other kind of representation? Or this has to be written?

That's t for now, I would try to dig more your very nice project and ask more questions.

Best Regards,
Razvan

**Comment by FlorianRappl** [comment]
Hi @rzvdaniel - this is certainly a legitimate place to ask questions.

1. The other one would be [Stackoverflow](https://stackoverflow.com) with the *anglesharp* [tag](https://stackoverflow.com/questions/tagged/anglesharp).
2. There is no need to "initialize" style computation. That one would be automatically provided by a proper rendering engine. Keep in mind that CSS alone will never "compute" a style - style computation requires HTML and CSS knowledge and would thus be the result of a render tree.
3. This is more or less a question to [AngleSharp.Css](https://github.com/AngleSharp/AngleSharp.Css). In general all these strings are only representations of a `Color` value. By default one representation is chosen (`rgba` naturally), however, you are free to choose another one.
