### ISSUE TITLE
Pool with high memory usage on high load

### ISSUE THREAD

**Issue by drungrin** [AngleSharp/AngleSharp#546]
Hi, the Pool implementation can grow really huge on high load. And doesn't go down.
Maybe we can have an option to disable it, or have an idle object limit, or maybe only clearing the StringBuilder  on the ToPoll() can minimize the issue.

Edit: StringBuilder doesn't resize on Clear(). Clearing it still keep the memory.

static ConditionalWeakTable on Node is growing also.

**Comment by FlorianRappl** [comment]
This is definitely right. A cache without an eviction rule is equivalent to a memory leak.

I propose the following:

- Allow defining the maximum of pooled `StringBuilder` instances (library global)
- By default take a max. of 4 `StringBuilder` instances (tbd)
- After a minimum number of `min(2, defined_max)` only consider adding larger instances
- If the maximum number of instances is reached the one with the least capacity is dropped
- `StringBuilder` instances exceeding 2 MB will be dropped

The growth of the weak table would be another issue. However, here the issue can also lie on the user's side (should be checked first). If many documents are created, which are never disposed / released by the user, the weak table will still map the assigned owners.

How does the proposal sound - anything that I missed or should be changed from your point of view?

**Comment by drungrin** [comment]
Sounds good, I believe that'll solve the issue.

About the weak table, I'll need to double check on my side to make sure that I didn't miss something.

**Comment by drungrin** [comment]
The static ConditionalWeakTable on Node is grow was on my side, it is ok for me.

**Comment by FlorianRappl** [comment]
Thanks for the heads up!

**Comment by FlorianRappl** [comment]
Is being fixed in PR #549.
