### ISSUE TITLE
Encoding sniffing algorithm

### ISSUE THREAD

**Issue by iSazonov** [AngleSharp/AngleSharp#547]
In [PowerShell Core project ](https://github.com/PowerShell/PowerShell/issues/3267#issuecomment-286917402)we want use the library as portable parser.
Currently we have a Issue about requesting sites with broken encoding. Recent PowerShell Core code and .Net Core don't support [full HTML5 standard](http://www.w3.org/TR/html5/syntax.html#the-input-byte-stream).

Do you plan to implement the "Encoding sniffing algorithm" and related encoding point from the doc?
It would be greatly simplified and accelerated our work.

**Comment by FlorianRappl** [comment]
I think that one is implemented, see [TextSource](https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/TextSource.cs). Besides that part AngleSharp also takes the correct precedence in terms of encoding via content-type, stream (BOM), meta tag etc. Also the three encoding states (tentative, certain, irrelevant) are respected.

Nevertheless, as encoding is quite a beast and AngleSharp uses .NET Standard 1.0 we are limited in terms of, e.g., punycode or some other (esoteric?) variants that appear in the spec. I would still guess it does a decent job in most (all relevant?) edge cases.

You can find the available mappings [in TextEncoding](https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/TextEncoding.cs).

Does that help you? Did I miss something? If you need anything let me know.

Also just a heads up: The current version is v0.9.9 - the v0.10 is planned / should be out soon (we are a month over the planned release, but I miss the time to give it the final touch). I guess the v0.10 should be also interesting for you guys, as it is performance-wise a little bit better, some bugs are solved, and most importantly the CSS part was outsourced to a dedicated library (thus making the lib more lightweight / straight forward for the HTML use case).

**Comment by iSazonov** [comment]
@FlorianRappl Thanks for clarify! I am trying to learn the API.
