### ISSUE TITLE
Issue with cookies - default path value

### ISSUE THREAD

**Issue by drungrin** [AngleSharp/AngleSharp#548]
Hi, the cookies set with a redirect aren't working on level branch (worked fine with the master and HttpClientRequester + CookieContainer).

request 1: /path1, set a cookie THECOOKIE=value1
request 2: /path1/somefile.jsp redirects to /path2/file2.jsp
     /path2/file2.jsp request is going with the cookie from path1 (THECOOKIE=value1)

**Comment by FlorianRappl** [comment]
Seems to me like the default path value is not set correctly. I guess it will just be set to `/`. I will investigate and release a fix.
