### ISSUE TITLE
Consider removing the constraint from ApiExtensions.Descendants

### ISSUE THREAD

**Issue by thorn0** [AngleSharp/AngleSharp#55]
The constraint `where TNode : INode` makes it impossible to write something like this:

``` c#
document.Body.Descendents<IUrlUtilities>()
```

which could be convenient if `IHtmlImageElement` implemented `IUrlUtilities` (it doesn't though).

**Comment by FlorianRappl** [comment]
Why don't you use Linq for that? There is a handy `OfType<T>()` method, which should be used for scenarios like this. `IUrlUtilities` does not carry any children, nor it is a logical part of a tree. It is just an interface that might be implemented in a node that is part of the tree.

**Comment by thorn0** [comment]
If I need to get all the descendants that implement an interface, of course, I can write `node.Descendants<INode>.OfType<IFoo>`, but what does `Descendants` need its type parameter for then? Just for the same purpose, doesn't it? So why do we need that constraint?

**Comment by FlorianRappl** [comment]
Well, the constraint is not needed. But the implementation also just uses a LINQ-`OfType<T>` extension method. Nevertheless I see where this is going. The expressiveness in doing it in one step is really appealing.

The basic idea of the constraint was to give a hint what could be filtered (texts, elements, ...). But of course that rules out the scenario you'd like to have.
