### ISSUE TITLE
Question: Is AngleSharp 0.9.9 stable to upgrade to?

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#553]
I haven't updated since October, I believe you suggested I wait till the CSS code stabilized. At this point do you think I should update?

Also, I've seen the AngleSharp repo organization, and am unsure of which projects I need to include. As you know I use xml, html and css serialization/deserialization only. So which projects will I need? (I include the AngleSharp sources in my project, not the nugets.)

Thanks!

**Comment by FlorianRappl** [comment]
Depends on your definition of stable. API-wise stability will be reached with v1, but 0.9.9 did not have much changes to, e.g., 0.9.8. So here it is a good upgrade. Also some bugs have been fixed. Of course, there are some bugs in there, but most of these bugs are/should also be available in former versions. So all in all I would say yes. You only need the main repository for your use case.

It is a different thing when we talk about 0.10.0, but I think you have not been referring to that, right?
