### ISSUE TITLE
context.openAsync() does not recognize a greek character

### ISSUE THREAD

**Issue by entelostre** [AngleSharp/AngleSharp#554]
I have already asked in stackoverflow too.. 

http://stackoverflow.com/questions/43246282/anglesharp-context-openasync-returns-unrecognized-character-what-can-i-do

PS. Not sure if it is good practice to post a link from stackoverflow. Excuse me.

**Comment by FlorianRappl** [comment]
What is the encoding used for the webpage? This is clearly an encoding issue and I guess not particular to AngleSharp. Does the webpage work in a browser? Does the browser detect the same encoding as AngleSharp?

I am not seeing a proper meta encoding tag on the document. As you did not post the HTTP response, I assume a proper encoding heading is not supplied? Is there some BOM?

**Comment by entelostre** [comment]
1. Encoding is not defined as you see.

2. The webpage works fine in the browser but the browser tab automatically sets encoding to Greek(ISO) (opening source view shows the greek A correctly). If I manually change the encoding to Unicode it does not work. And if I open source view I can see the same unrecognized char I see in .net code.

3. The above statement means that the browser detects encoding: Greek(ISO). Anglesharp detects characterSet: utf-8

4. No, no encoding heading is supplied.

5. No, no BOM.

**Comment by entelostre** [comment]
I know it is silly and that the proper way is to fix the HTML but we aren't allowed to apply changes.. 

So, is there a workaround? Maybe a way to set the encoding of the `context` ?

**Comment by FlorianRappl** [comment]
Yeah of course there is a workaround. You have multiple options:

1. Try to use the WithLocaleBasedEncoding encoding to closely mimic the browser's encoding fallback behavior.
2. Implement your own `IEncodingProvider` service to dictate AngleSharp which encoding to use by default.
3. Load the stream manually, pass it on to a virtual response (using the callback overload) and provide an additional header that tells AngleSharp which encoding to use.

**Comment by entelostre** [comment]
Hi again and thank you. I tried the 1st option before posting the issue!
The 2nd option seem promising but I don't know how to implement it. 

At first I thought I had to create a new class that inherits from BrowserContext and Implements IEncodingProvider but then I saw BrowserContext class is NonInheritable.

Could you provide a link or some mini info as a guidance for me to continue?

**Comment by FlorianRappl** [comment]
Just implement that interface and supply it to the configuration via the `With` method.

**Comment by entelostre** [comment]
I tried many different ways to 'Just implement that interface and supply it to the configuration via the With method'. Apparently I am not in the skill level to understand the simplicity of your statement. But I believe it is something practically easy to do.

So, could you give an example of the process?

**Comment by FlorianRappl** [comment]
```cs
class FixedEncodingProvider : IEncodingProvider
{
    public Encoding Suggest(String locale)
    {
         return Encoding.UTF8; // Change to the Greek (ISO)
    }
}

var config = Configuration.Default.With(new FixedEncodingProvider());
```

HTH!

**Comment by entelostre** [comment]
Yup Thank you mate! Have a nice day!

**Comment by entelostre** [comment]
And also THANKS for this great lib!!

**Comment by FlorianRappl** [comment]
Glad that did the job for you!
