### ISSUE TITLE
Pseudo-class :scope does not properly selecting children

### ISSUE THREAD

**Issue by lorond** [AngleSharp/AngleSharp#555]
Selecting direct children of an element with pseudo-class `:scope` returns empty collection.
Test:

```C#
var html = @"<!DOCTYPE html>
<html>
<head><meta charset=""utf-8"" /></head>
<body>
    <div>
        <div><p>nested</p></div>
        <p>direct</p>
    </div>
</body>
</html>";

var doc = new HtmlParser().Parse(html);
var div = doc.QuerySelector("body > div");

var items = div.QuerySelectorAll(":scope > p");
Assert.AreEqual(1, items.Length); // AssertionException - Expected: 1 But was: 0 

var p = items[0];
Assert.AreEqual("direct", p.TextContent);
```

https://github.com/AngleSharp/AngleSharp/issues/347#issuecomment-221979803 states it was implemented in 0.9.8. But it does not work in 0.9.9 version.

**Comment by FlorianRappl** [comment]
I think this is a bug that was already seen - see #352 with the PR #487.

My workload is still far too high to release v0.10, which unfortunately cannot be released in its current state. The project is desperately looking for another maintainer, but so far the .NET community does not seem to be interested.

(if you believe the duplicate is wrong please scream out loud 🥇 )
