### ISSUE TITLE
OpenAsync throws JavascriptExteption

### ISSUE THREAD

**Issue by georgiosd** [AngleSharp/AngleSharp#559]
Hi,

On some sites that have JS errors, `BrowsingContext.OpenAsync` will throw a `JavascriptException`.

Shouldn't these be handled by the `BrowsingContext` itself?

Georgios

**Comment by FlorianRappl** [comment]
In my opinion this has to be taken care of by the respective scripting engine, e.g., in this case the AngleSharp.Scripting part.

**Comment by georgiosd** [comment]
@FlorianRappl what do you think is the right action in this case? Handle the exception and ignore it?
Shouldn't the loader log them somewhere?

**Comment by FlorianRappl** [comment]
Yes, in my opinion it should emit an error event on the window (as standard JS does).

**Comment by georgiosd** [comment]
@FlorianRappl it looks like this exception is thrown from `DomDelegates.ToListener` so I'll catch it there - how would I emit the error event from there?

**Comment by georgiosd** [comment]
Btw, the exception is generated with google.com (will redirect to google.gr in my case) using a user-agent of `User-Agent, Mozilla/5.0 (X11; Linux i686; rv:32.0) Gecko/20100101 Firefox/32.0` - this should work right? I couldn't figure out why, if you don't mind taking a look.

**Comment by FlorianRappl** [comment]
You need the engine instance, which has a reference to its hosting window. Then you can just use the standard DOM event API to create an event and emit it.

The user agent works - should not have anything to do with it. It is some JS code that is not recognized (potentially some automatic string conversion that is missing or an API that was not implemented).

**Comment by georgiosd** [comment]
a) Some more guidance on the event stuff please :)

b) How would I go about finding out what part of the JS failed?

**Comment by FlorianRappl** [comment]
a) All event targets implement the `IEventTarget` interface (https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Interfaces/IEventTarget.cs) - which contains a `Dispatch` method. You just need to create an instance of the event to be dispatched. There are some helpers available that can be invoked from an event target.
b) That is where Jint comes into play. I think the JavaScriptException contains a property for this, but not sure.
