### ISSUE TITLE
XHTMLish output

### ISSUE THREAD

**Issue by thorn0** [AngleSharp/AngleSharp#56]
I need to convert a document to such a format that it should be both HTML and XML in the same time. That is, the markup like `<select/>` is not allowed, should be `<select></select>` instead, but the markup like `<img src="..." />` is required. Would be nice if AngularSharp could provide some control over the process of DOM serialization.

Html Agility Pack has something like this. At least, it can output XHTML.

**Comment by FlorianRappl** [comment]
Well, the DOM serialization is specified (hence fixed). However, we could now do two things. Either you call a method that takes options, which will do the serialization (well, this is somewhat flexible, but not as much as I would like), or there will be a visitor like pattern, where the user gets to choose what serialization he wants to take - and how he wants to deal with it.

**Comment by FlorianRappl** [comment]
I now provide another `ToHtml` method that takes any instance implementing the `IMarkupFormatter`. Right now there is just a single class implementing this interface, which is the `HtmlMarkupFormatter`. I will probably also provide a `XHtmlMarkupFormatter` and / or a `XmlMarkupFormatter`, but you can also use your own formatter if the existing ones don't fit your needs.

My guess is that this approach is flexible enough to fit all needs associated with node serialization. Let me know if you think something is still missing.

**Comment by thorn0** [comment]
Thank you, looks great. There are cases when it's needed to format InnerHtml of an element. Would you consider adding `ToHtml` to `INodeList` to make it possible to write: `element.ChildNodes.ToHtml(formatter)`?

**Comment by FlorianRappl** [comment]
Yes!

**Comment by thorn0** [comment]
It'd be easier to inherit from `AngleSharp.Html.HtmlMarkupFormatter` if its methods were virtual and weren't declared as an explicit interface implementation. I submitted #57.

**Comment by FlorianRappl** [comment]
That all is on purpose. Please FCoI. The class itself has no data members and is only a functional construct. It should be treated as such. The class is also only visible, that you can actually use its methods.

**Comment by thorn0** [comment]
Got it. However, I have trouble with writing a formatter implementation for following requirements. Line breaks should be inserted before and after each block element (looking just at its name: `p`, `div`, etc.), but two consecutive line breaks must never be inserted.

For example:

``` html
<div>123</div>456<div>789</div><div>abc</div><ul><li>aa</li><li>bb</li></ul>
```

should be converted to

``` html
<div>123</div>
456
<div>789</div>
<div>abc</div>
<ul>
<li>aa</li>
<li>bb</li>
</ul>
```

TinyMCE formats HTML this way. The demo on the [main page](http://www.tinymce.com/) shows formatted HTML if you click **_Tools -> Source code**_. Just in case, here is their [implementation](https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/html/Writer.js#L58).

**Comment by thorn0** [comment]
I thought I implemented it, but suddenly it turned out that `CloseTag` for an element is called before the serialization of the children. :)

**Comment by FlorianRappl** [comment]
Yap, I call `CloseTag` before serializing the children. For me that was alright, but if you want to allow the scenario you are talking about, it should be called in logical order. I will fix this.
