### ISSUE TITLE
How to download a file after clicking an anchor element?

### ISSUE THREAD

**Issue by lanzorg** [AngleSharp/AngleSharp#563]
Is it possible to download a file after clicking an anchor element with AngleSharp?
I tried this code but it doesn't work.

    // Init User Agent.
    var requester = new HttpRequester();
    var agent = "Mozilla / 5.0(iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit / 534.46(KHTML, like Gecko) Version / 5.1 Mobile / 9A334 Safari/ 7534.48.3";
    requester.Headers["User-Agent"] = agent;

    // Init AngleSharp Configuration.
    var config = Configuration.Default.WithDefaultLoader(requesters: new[]{requester}).WithJavaScript().WithCss().WithCookies();
    var browser = BrowsingContext.New(config);

    // Scrape the first link.
    var document = await browser.OpenAsync("https://sourceforge.net/projects/mpv-player-windows/files/64bit/");
    var anchor = document.QuerySelector("#files_list > tbody > tr:nth-child(1) > th > a");
    var link = anchor.GetAttribute("href");

    // Open the download page, click the anchor and download the file.
    var document2 = await browser.OpenAsync(link);
    document2.QuerySelector<IHtmlAnchorElement>("#problems > a.direct-download").DoClick();

    MessageBox.Show("DownloadFinishedAndShouldReturnTheDownloadFilePath");

**Comment by FlorianRappl** [comment]
AngleSharp does not have a way to get that one type and store it somewhere. Additionally, the anchor element does not follow links.

Potentially, here we have two candidates:

1. Have `DoClick` following links (on anchor elements) by default
2. Provide the ability for a generic download handler, which would be fired when no other handler (e.g., HTML, XML, or text) seems to be applicable.

At the moment what you need to do is to get the URL of the anchor element and use (either the standard `HttpClient` or AngleSharp's requester) to download / stream the source.

**Comment by lanzorg** [comment]
OK, this is what I thought. I will try with the requester.
Does it share a session/context with BrowsingContext or is it a completely different thing?

**Comment by 304NotModified** [comment]
I think it's acceptable (or maybe even better) to use a "webclient" to download the URL. 

There are plenty of webclients and then you could tweak it as you like (headers, timeouts etc).

So proposal: won't fix
