### ISSUE TITLE
TypeInitializationException: The type initializer for 'AngleSharp.Dom.Html.HtmlUrlBaseElement' threw an exception. Inner: IndexOutOfRangeException: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by vivekjMSFT** [AngleSharp/AngleSharp#564]
Got this exception today, lots of them. In my test app same string seems to be working fine. Restarting app pool seems to fix the issue. this is a new one, probably. Any Idea what could be causing this?

**Comment by vivekjMSFT** [comment]
any clue guys what could be causing this? It doesn't seems like it was caused due to a particular string but it appears it failed in creating the object itself.

**Comment by FlorianRappl** [comment]
I think this is the old race condition that may appear in multi-threaded environments.

Without further information (e.g., your config that you use or from how many threads you use AS, which objects you share, ...) it is pretty much impossible to say - I could only guess.

**Comment by vivekjMSFT** [comment]
Make sense. when you say old race condition , do we already have the fix for it? if yes, could you share the  PR?
