### ISSUE TITLE
Exception thrown when GetCookie is called for invalid image element 

### ISSUE THREAD

**Issue by alexander-karnadi** [AngleSharp/AngleSharp#565]
Hi there,

Anglesharp is really good tool and we start to migrate more and more tests to use it. We want to use the latest anglesharp which is the 0.9.9 version since we need the fix for:
- Cookies are now sent for all requests (#420)
It is needed for our new tests.

However when we upgrade the new tests are ok but the existing ones are not. These tests fail when we are trying to GetCookie(String origin)... when the origin is null. What we've seen so far that this issue happens only on invalid image element in our page. These images don't have "src" attribute.

So one way is to fix all of the invalid image elements (but this is difficult and probably will never happen) or maybe we can just ignore invalid elements?

Please advice.

thanks!

**Comment by FlorianRappl** [comment]
To circumvent this bug you can implement your own `ICookieProvider`, which wraps the `MemoryCookieProvider`, e.g.:

```cs
class MemoryCookieProviderWrapper : ICookieProvider
{
  private readonly MemoryCookieProvider _original;

  public MemoryCookieProviderWrapper(MemoryCookieProvider original)
  {
    _original = original;
  }

  public String GetCookie(String origin)
  {
    if (original != null)
    {
      return _original.GetCookie(origin);
    }

    return null;
  }

  // ... wrap set cookie
}
```

Hope this helps!

**Comment by alexander-karnadi** [comment]
Sorry for late reply. It indeed helps. Thanks! Any plan to have this in a proper release?

**Comment by FlorianRappl** [comment]
It is in v0.10.
