### ISSUE TITLE
Null reference exception when content of a IRequest is not properly initialized

### ISSUE THREAD

**Issue by alexander-karnadi** [AngleSharp/AngleSharp#567]
Hello,

I am having an issue in some of our tests that they result in null reference exception on anglesharp.
The exception is originated from BaseLoader.CreateNewRequest when checking the content.Length > 0.

I looked into (and played around with) the source code and I saw there's a place where we instantiate a Request without defining the content which is in the ResourceLoader.DownloadAsync.

I put a default value of Stream.Null and this seems to fix it.

Any idea of what's going on?
Can an immediate fix be to have a wrapper for the default ResourceLoader?

cheers,

AK

**Comment by FlorianRappl** [comment]
Yes, the workaround will work. I think this issue was already solved in v0.10, but I am not sure. I will try to confirm it.
