### ISSUE TITLE
Json deserializing for html with only json throws exception

### ISSUE THREAD

**Issue by alexander-karnadi** [AngleSharp/AngleSharp#568]
Hi there,

This is just a question actually. If this is not the correct way to submit a question please let me know.

We have many tests that asserting json response from the website. The json response is wrapped in < Pre > tag and it has always been like this. 

However we notice that the tests break for version 0.9.9 (we used 0.9.7 and they worked there). This is because now in 0.9.9 document.Body.InnerHtml contains the < Pre > tag while on 0.9.7 this was not the case.

This seems like the correct behavior in my opinion but I want to confirm that it is. It's a bit hard to see what change in the AngleSharp code that modify the behavior. So questions are:

- is this what we want?
- if so could you point me to where the change for this?

cheers,

AK

**Comment by FlorianRappl** [comment]
Cannot make a statement with the given amount of information. Please post a MWE.
