### ISSUE TITLE
Guidance on following meta redirect

### ISSUE THREAD

**Issue by RyanONeill1970** [AngleSharp/AngleSharp#569]
Hi,

I'm finding pages that have meta http-equiv refresh tags in them and I was going to parse the url myself, but wondered if AngleSharp has a way to do this already that I should be using?

The HTML is as follows, it would be ideal if AngleSharp could follow this redirect or has a utility function for parsing out the redirect.

```
<HTML>
<HEAD>
<meta http-equiv="refresh" content="0; URL=./dir/file.htm">
</HEAD>
<BODY></BODY>
</HTML>
```

If not, no problem, it will be a quick hack.

Thanks

Ryan

**Comment by FlorianRappl** [comment]
Nope, there is nothing integrated yet, even though I think there will be one in the future (see discussion in #561, bullet point 1).

If you come up with a good (even though hackish) solution a quick share would be wonderful! Thanks 👍

**Comment by georgiosd** [comment]
@FlorianRappl I ran into this too. I think the only sane way to provide support for this, is to pull the `BrowsingContextExtensions.OpenAsync(DocumentRequest)` method into `IDocumentLoader` and provide an option to enable meta-following with the default loader. 

Thoughts?

**Comment by RyanONeill1970** [comment]
On the scale of documents I was parsing it was easier to look at the failed redirects and manually re-enter the correct address into my dataset. So I didn't even hack around it, just marked it as a failed parse.

I don't know the codebase at all, otherwise I might be tempted to do this. I can offer testing if you need though.

**Comment by georgiosd** [comment]
It's a simple addition, in terms of doing the redirect - the hard part is "where" to put it so it makes sense :)

**Comment by georgiosd** [comment]
See my PR: https://github.com/AngleSharp/AngleSharp/pull/571

**Comment by georgiosd** [comment]
Just realized this code would break with `content="0; other stuff here"`. If @FlorianRappl approves of the edit I'll fix that.

**Comment by RyanONeill1970** [comment]
Thanks @georgiosd , that looks really good.

One thing, as a consumer of this call the redirection delay does not make sense.
That's because if I parsed a page with a redirect in, the call would hang for x seconds before proceeding. I couldn't do anything else while waiting for that.

I think it makes more sense that if redirect is enabled, then it happens straight away, without a delay.

If you wanted finer control then instead of a boolean for redirect on / off, use an int which defines a threshold at which to redirect. for example, 1000 would mean if page redirects in less than 1000 seconds, redirect immediately, otherwise wait for the period the page has defined. Probably not needed / too much detail though.

**Comment by georgiosd** [comment]
@RyanONeill1970 I ended up refactoring that code into an extension because I wanted to be able to follow the redirect on an optional basis. If you look at the PR, @FlorianRappl has a better suggestion of implementing this which would cover your "want"
