### ISSUE TITLE
BaseRequester events do not properly remove event handlers

### ISSUE THREAD

**Issue by ArcanoxDragon** [AngleSharp/AngleSharp#572]
In the `devel` branch, the events defined in `AngleSharp.Io.BaseRequester` do not correctly remove event handlers when delegates are removed from the .NET events. On [BaseRequester.cs:20](/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Io/BaseRequester.cs#L20) and [BaseRequester.cs:29](/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Io/BaseRequester.cs#L29), the `remove` handler incorrectly calls `AddEventListener` again instead of calling `RemoveEventListener`.

**Comment by FlorianRappl** [comment]
Very good finding - thanks for the PR!
