### ISSUE TITLE
Can not set User-Agent in dotnet core

### ISSUE THREAD

**Issue by wjzhou** [AngleSharp/AngleSharp#574]
The User-Agent Header (and other standard headers) can not be set in the dotnet core 1.0 because the dotnet core version's HttpWebRequest doesn't have the User-Agent property.

https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest?view=netcore-1.1

The end-result is that the User-Agent can not be set and I can not find a workaround to set that. 

Can we conditional exclude the following line based on NETCOREAPP1_0?
https://github.com/AngleSharp/AngleSharp/blob/03971ebb3abcc3022652f2c96d615a1d048ab0a9/src/AngleSharp/Network/Default/HttpRequester.cs#L250-L273

**Comment by FlorianRappl** [comment]
These lines are in there to only set this if possible.

So question back: Is there some specific problems you face there or what is the exact purpose of this issue?

**Comment by wjzhou** [comment]
I need to send out the User-Agent header. Currently, it is not possible on dotnet core platform.

These SetProperty becomes no-op on dotnet core, and the 'User-Agent' is not added to the Headers dictionary.

``` c#
if (!Restricted.Contains(name) && property != null && property.CanWrite)
{
    try
    {
        //This might fail on certain platforms
        property.SetValue(_http, value, null);
    }
    catch
    {
        //Catch any failure and do not try again on the same platform
        lock (Restricted)
        {
            if (!Restricted.Contains(name))
            {
                Restricted.Add(name);
            }
        }
    }
}
```

**Comment by FlorianRappl** [comment]
Yes exactly. But AngleSharp cannot solve this problem for. As you already mentioned on .NET Core 1.0 the WebRequester does not allow that ...

But you are not restricted to the standard `IHttpRequester` implementation in AngleSharp. If you have another requester (for .NET Core) you can just expose it to AngleSharp.

**Comment by campersau** [comment]
Why not just fallback to ` _http.Headers[key] = value;` if the property is not found in `AddHeader`?

**Comment by FlorianRappl** [comment]
That will usually throw an exception. My first try in this area was to set all headers via the `Headers` collection, however, this sane approach was ruled out by the .NET team.
