### ISSUE TITLE
Cannot update Nuget packages due to multiple target frameworks

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#576]
Hi, long time!

I cannot update any NuGet packages in my solution (even non-AngleSharp packages.)

When trying to update a NuGet package, Visual Studio complains:

`Invalid restore input. UAP projects must contain exactly one target framework. Input files: C:\myproj\AngleSharp\src\AngleSharp\AngleSharp.Core.csproj, C:\myproj\AngleSharp\src\AngleSharp\project.json.`

This seems similar to #566 but the error here occurs in a different context.

This may help: https://github.com/NuGet/Home/issues/5247

Could you suggest a workaround? I'll try poking around as well.

Cheers

**Comment by georgiosd** [comment]
Workaround: Delete targets from the project file except the portable one.
Restore/install/whatever. Undo.

**Comment by FlorianRappl** [comment]
It is definitely related. I guess the workaround should work as it sounds that the targets may be ambiguous, but I can't tell.

**Comment by corliss** [comment]
Deleting `project.json` from `AngleSharp\src\AngleSharp` turns out to be a workaround.

Is this file there only to support `AngleSharp.NETCore.xproj`? If so, they should both be moved to a different directory. VS doesn't play nicely with multiple projects in a single directory these days.

**Comment by FlorianRappl** [comment]
Actually, the file is there to support all targets - it triggers a multi target build and was quite an important one. However, that was in the days were we had project.json - these days are over now.

**Comment by corliss** [comment]
> However, that was in the days were we had project.json - these days are over now.

I don't understand - the file still exists, at least on the master branch...

**Comment by FlorianRappl** [comment]
Yes, but that kind of project file was abandoned and as you already spotted #566 is not supported on AppVeyor or any other platform with up-to-date tooling.

**Comment by corliss** [comment]
I don't understand why this issue has been closed. This is a current bug caused by `project.json`. When building `AngleSharp` from source together with other libraries, the error occurs.

The fix is to delete `project.json` from the master branch.

> Yes, but that kind of project file was abandoned

This statement is unclear - abandoned by who? Very confusing. Could you please explain exactly what you mean?

**Comment by FlorianRappl** [comment]
Closed as it is a duplicate of #566. If you think there is something that needs to be done then please submit a PR. Thanks!

> This statement is unclear - abandoned by who? Very confusing.

Yes, sorry I assumed that you are familiar with .NET Core and Microsoft's announcements regarding things like project.json, MSBuild, and the whole xproj/csproj story. So without further ado here is some reading material for you: https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-net-core-tools-1-0/. There is more but I think that should be sufficient to get you started.

**Comment by corliss** [comment]
> If you think there is something that needs to be done then please submit a PR. Thanks!

As mentioned, the fix appears to be either removing project.json, or updating the projects to the new msbuild .csproj-only format. Hopefully that is sufficient info?

**Comment by georgiosd** [comment]
@corliss I think @FlorianRappl is hinting that this is an open-source library and thus unsupported. If you want a change to go in, submit a PR like the rest of us do. There is already an open PR with a fix for this problem.

**Comment by FlorianRappl** [comment]
Exactly. Thanks @georgiosd for explaining that. The mentioned PR is #578. Of course we know that the root cause is in project.json, however, any fix has to supply the following:

- Multi-target build
- AppVeyor compatible
- Cake compatible, which includes running the tests
