### ISSUE TITLE
Bug with CssBorderProperty

### ISSUE THREAD

**Issue by D92130** [AngleSharp/AngleSharp#58]
There is some logic errors with line 119 & 122 in file AngleSharp/DOM/Css/Properties/Border/CSSBorderProperty.cs, probably caused by copy and paste.  Also border style definition like "border: 1px outset currentColor" is not well supported.

**Comment by FlorianRappl** [comment]
Thanks for spotting the copy / paste error. Yes, `currentColor` should be supported and isn't (right now). I will definitely change that!
