### ISSUE TITLE
Weird iframe - correct behavior?

### ISSUE THREAD

**Issue by georgiosd** [AngleSharp/AngleSharp#581]
Hi :)

I found a website that had this markup in it:

`<iframe src="" class="updates-iframe"></iframe>`

It was hidden by CSS and it's used in the page's JS code to get some updates later on. 

However, with AngleSharp this resulted in an endless loop - the `src=""` resolved to `doc.DocumentUri` which kept loading itself again and again.

Not sure what the bug is here but doesn't sound like correct behavior.

What do you think?

**Comment by FlorianRappl** [comment]
This is certainly a bug. I am not quite sure about the correct behavior. I need to test this. If you ask me there are two possible ways:

1. It indeed would load the root page, but as this would be circular it would be forbidden (general circular detection for iframes)
2. It does not load anything when the source is empty

I will try to look this up on the spec, but my gut feeling is with 1, as it would also solve other potential problems (e.g., imagine a.html has an iframe to b.html, which again has an iframe to a.html).

**Comment by georgiosd** [comment]
Does CSS come into it? i.e. would the iframe load, even if it's hidden?

(1) is what I did as a quick fix: `if(frame.Source == frame.Owner.DocumentUri) abort` kinda thing.

**Comment by FlorianRappl** [comment]
CSS has no impact on the behavior in this case, i.e., yes, the iframe would be loaded even though CSS says otherwise.

**Comment by georgiosd** [comment]
Ok let me know what the spec is - I can send a PR, it's easy enough.
