### ISSUE TITLE
Document.Anchors is empty

### ISSUE THREAD

**Issue by duncanawoods** [AngleSharp/AngleSharp#582]
The documentation for IHtmlDocument is:

> Gets a list of all of the anchors in the document

So I would expect it to be have the same as QuerySelectorAll("a") but it appears to be empty:

```
    var html = "<html><body><a href='/page.html'>page</a></body></html>";
    var doc = new HtmlParser().Parse(html);
    Console.WriteLine("Document.Anchors count " + doc.Anchors.Count());
    Console.WriteLine("QuerySelectorAll count " + doc.QuerySelectorAll("a").Count());
```

Prints

> Document.Anchors count 0
> QuerySelectorAll count 1

**Comment by campersau** [comment]
An anchor is any element which has a `name` attribute.
What you want is `document.links`.
See https://stackoverflow.com/a/44007462
<sub>
(Note that `document.anchors` was removed from the HTML standard https://developer.mozilla.org/en-US/docs/Web/API/Document/anchors)
</sub>

**Comment by FlorianRappl** [comment]
Thanks @campersau for taking this one!

I agree that the naming is unfortunate, but this is the official name. I've chosen the path to take commonly known "false friends" instead of inventing new ones.
