### ISSUE TITLE
QuerySelectorAll - performance

### ISSUE THREAD

**Issue by jirisykora83** [AngleSharp/AngleSharp#584]
I try to profile my app because i facing issue with performance (main reason why i recently switch from HAP). And i notice `NodeList.get_Length()` in `QuerySelectorAll ` is take lot of time (almost 10%). Of course it depend on how much elements is in collection).

I want to try rewrite it with my custom QuerySelectorAll but i end with too many class is need to rewrite. Maybe you can try just save `elements.Length` to local variable it should get some percent of performance in this highly used function.

![image](https://user-images.githubusercontent.com/7279825/28018856-1641f012-657f-11e7-9754-2a036c7b6c88.png)

Testing with last stable version 0.9.9 but from first look at dev branch i think it is same in 0.1.0.
VS 2017 - release mode of course

**Comment by FlorianRappl** [comment]
I think caching one or the other thing may indeed be useful. 

Caching `elements.Length` sounds like a small / notable gain without any side-effects or risks - thanks for the suggestion!

**Comment by campersau** [comment]
An example to reproduce your results would be helpful. Used HTML and CSS selectors.

**Comment by jirisykora83** [comment]
Sorry for late response i have short vacation.

Here is simplify version of my testing scenario (in my testing scenario i also extract some data but 
 i call `QuerySelectorAll` just on one other place).

For benchmark i use [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet).

Example:
[AngleSharpBenchmark.zip](https://github.com/AngleSharp/AngleSharp/files/1147670/AngleSharpBenchmark.zip)

**Comment by FlorianRappl** [comment]
Would be simpler to have a Gist.

**Comment by jirisykora83** [comment]
Ok here is the gist.

[https://gist.github.com/jirisykora83/d1316a636d5f6c154872cc746c7654a1](https://gist.github.com/jirisykora83/d1316a636d5f6c154872cc746c7654a1)

**Comment by FlorianRappl** [comment]
Great, thanks!
