### ISSUE TITLE
QuerySelector all for XPath string

### ISSUE THREAD

**Issue by nextLane** [AngleSharp/AngleSharp#585]
How can I make a selection of element on xpath  *[@id="result_0"]/ul[1]/li[1]/a/span in AngleSharp? I am able to do selections like *[id="result_0"] > ul > li > a > span but how can the indexing (ul[1]/li[1])  
 be included?

**Comment by FlorianRappl** [comment]
Try n-th child. In general such a question is not AngleSharp related, but rather CSS selector related. Thus I recommend you asking / looking for answers in, e.g., StackOverflow. 

Just as an example: https://stackoverflow.com/questions/2751127/how-to-select-the-first-second-or-third-element-with-a-given-class-name

**Comment by nextLane** [comment]
@FlorianRappl Thanks for the example :) However I tried executing  var result = RunQuery("ul:nth-child(2)");
in the CssSelector test and added two ul lists to the test input file, but it is unable to pass, however :nth-last-child(2) happens to run fine.

**Comment by FlorianRappl** [comment]
I'm not sure what you are doing so I can't comment. If you think you've encountered a bug make a MWE and post an issue.

Keep in mind that you should first test in a standard web browser to verify your query is actually correct.
