### ISSUE TITLE
Does the “UsedStyle“” and “Target” first characters need to be lowercase?

### ISSUE THREAD

**Issue by imgits** [AngleSharp/AngleSharp#589]
filename:  Interfaces\Css\IStyleUtilities.cs
[DomName("UsedStyle")]   <--should it be [DomName("usedStyle")] ?
ICssStyleDeclaration UsedStyle
{
	get;
}

filename: Interfaces\Html\IHtmlBaseElement.cs
[DomName("Target")]   <--should it be [DomName("target")] ?
String Target
{
	get;
	set;
}

**Comment by FlorianRappl** [comment]
I think so - yes.
