### ISSUE TITLE
SubmitAsync() System.AggregateException -> ArgumentNullException

### ISSUE THREAD

**Issue by rikku47** [AngleSharp/AngleSharp#591]
Hi,

I get an System.AggregateException -> ArgumentNullException the value should not null on this

 `var y = await context.Active.Forms[0].SubmitAsync(dic, false);`

or

`var x = await context.Active.Forms[0].SubmitAsync(dic, true);`

on this:

            var dic = new Dictionary<string, string>();

            dic.Add("conversations_create_session_form[email]", "email");
            dic.Add("conversations_create_session_form[password]", @"password");

            var configuration = Configuration.Default.WithDefaultLoader().WithCookies();
            var context = BrowsingContext.New(configuration);
            await context.OpenAsync("https://id.unity.com/en/conversations/20392cfe-ce2b-4734-a9c6-e52afa82970501af");

            var action = "";

            if (context.Active.Forms.Length > 0)
            {
                action = context.Active.Forms[0].Action;

                var y = await context.Active.Forms[0].SubmitAsync(dic, false);

                var x = await context.Active.Forms[0].SubmitAsync(dic, true);
            }

Any idea, what I miss? The link is a little bit strange. I have to do request first the Login, to get the right link with the form for example in firefox and put it into the code. But as I see, it is not bad, because I can set "true" to the SubmitAsync(), to create the missing elements. Thanks.

Best regards rikku47

PS:

System.AggregateException ist aufgetreten.
  HResult=0x80131500
  Nachricht = Mindestens ein Fehler ist aufgetreten.
  Quelle = mscorlib
  Stapelüberwachung:
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Task.Wait()
   bei SimpleWebCrawler.WatchResultsWindow.<btnLogin_Click>b__35_0() in C:\Users\xxx\Documents\Visual Studio 2017\Projects\SimpleWebCrawler\SimpleWebCrawler\Windows\WatchResultsWindow.xaml.cs: Zeile457
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

Innere Ausnahme 1:
ArgumentNullException: Der Wert darf nicht NULL sein.

**Comment by FlorianRappl** [comment]
Sorry for being late here. The problem is definitely that you are submitting a form, thus making a page navigation. Therefore the active document has changed and may not contain a form anymore (and at least the previous form).
