### ISSUE TITLE
Body.Text() Includes JavaScript

### ISSUE THREAD

**Issue by GuerrillaCoder** [AngleSharp/AngleSharp#596]
I am using this method to extract text from a page:

    var html = parser.Parse(page);
    var innerText = html.Body.Text();

It works but it also extracts all javascript code and comments from page body.  Is this intended behaviour?  Is there a way to get text without the javascript?

edit: It also pull out html comments.  I tried accessing property via browser on same site and chrome doesn't show javascript or html comments on TextContent property.

I am working around it by tidying with regex but its not great for performance as I have a lot of pages to process

                    Regex rgx = new Regex(@"<script\b[^>]*>([\s\S]*?)<\/script>");
                    Regex rgx2 = new Regex(@"");
                    foreach(var page in pages)
                    {
                        var cleanPage = rgx.Replace(page, "");
                        cleanPage = rgx2.Replace(cleanPage, "");
                        var html = parser.Parse(cleanPage);
                        var innerText = html.Body.Text();
                    }

**Comment by FlorianRappl** [comment]
Always when you are in doubt try the same thing in a web browser. You will see that the JS content also shows up there. Remember that a script tag also just has a standard text node inside. There is no difference from the DOM (even though there are special parsing rules inside a script tag). The content of that text node is eventually used from a JS engine.

In my opinion it would make more sense to iterate over all nodes and clean the script nodes first. Would also be more robust than using the regular expression.

If you do not want to mutate the DOM you could wrap the HTML Formatter to not iterate / include the content of script elements.

**Comment by GuerrillaCoder** [comment]
Thanks Florian.  I must admit I did try it in the browser but I must have been doing it on a page with no JavaScript (oops embarrassing).

Your suggestion is right.  I have hit the limitation of using regex.  I must now filter out elements with certain selectors also so iterating over the nodes makes a lot more sense although getting the recursion right to go over all the nested collections is confusing me a bit.

Are there any methods in AngleSharp for iterating over every node recursively?  Also is there any way to remove nodes by selector?

**Comment by FlorianRappl** [comment]
I think there is no method to directly remove elements by selector, but what you can do is

```cs
var elements = document.QuerySelectorAll('your selector here');

foreach (var element in elements)
{
  element.Remove();
}
```

(This is more or less pseudo code, I hope it is correct ...).

Regarding the recursive iteration there is, e.g., the TreeWalker (which is a standard DOM helper, hence the documentation for the web (e.g., [see MDN](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker)) will guide you. Since script tags will only contain text nodes, you could also just use `document.All`, which is a "flat" collection with all contained nodes (i.e., it is already recursively resolved).

HTH!

**Comment by GuerrillaCoder** [comment]
Hey Florian,

I was just coming back to say something similar and noticed you replied.  Many thanks!

`element.Remove()` looks great!  Very easy.

This is what I had figured out:

```c#
            foreach (var element in elements)
            {
                var scripts = element.GetElementsByTagName("script");
                
                foreach(var script in scripts)
                {
                    script.Parent.RemoveChild(script);
                }
            }
```

I didn't realise I could just access parent from child and remove like that so it was simple and your way you suggest is even easier!  Anglesharp is such a great library and so is your support. Many thanks..

(also thanks for tree walker and document.all suggestions, they are very helpful)

**Comment by FlorianRappl** [comment]
Thanks for the info - glad I could help!
