### ISSUE TITLE
Cookie format error reported when accessing twitter.com #598 

### ISSUE THREAD

**Issue by pmoran1947** [AngleSharp/AngleSharp#599]
Sorry  could not workout how to reopen the issue.

I have replaced the ; with , and $ with empty string and get the same error as described in #519. but get the same error.

Any suggestions?

**Comment by FlorianRappl** [comment]
Have you tried with v0.10 from `devel`?

**Comment by pmoran1947** [comment]
The issue is the same with devel.
The problem is that the Expires timestamp is using a Timezone of UTC  but must be GMT for .Net.
I can fix that by replacing the UTC.
How to I installa new ICookieProvider to effect the change.

**Comment by FlorianRappl** [comment]
You just need to supply that service in the configuration within your browsing context. A service is supplied via the configuration, so e.g., Configuration.Default.With(myCustomCookieProviderInstance) would give you such a configuration.
