### ISSUE TITLE
Extract only Text

### ISSUE THREAD

**Issue by devmondo** [AngleSharp/AngleSharp#6]
hi, 
in Html Agility Pack there is a command " HtmlToText()" to strip out Html Tags and return only the raw text, how can we do this here.

thanks in advanced.

**Comment by FlorianRappl** [comment]
The HTML DOM has a property called textContent (this is TextContent in AngleSharp) for node objects. Usually if you use this on e.g. the document root (HTML) element it should give you the whole textual content.

But beware - there might be an unusual amount of spaces and newlines in there, since those are not getting stripped out by the parser - that you do not see most of them in rendered content is a feature of the HTML renderer.

Tell me if it does fit your needs, otherwise I will implement another method to deal with this (outside of the official specification).

**Comment by devmondo** [comment]
thanks for quick reply, excellent it worked, but the problem is it also gives you CSS and Scripts, we should strip them as we are only interested in Text inside body

**Comment by FlorianRappl** [comment]
Hm this is how real browsers also behave. I will write a method "ToText()" which will already give you stripped content.

**Comment by devmondo** [comment]
thanks a lot :)

**Comment by ricardobrandao** [comment]
@FlorianRappl this was not implemented yet, right? I didn't found anything that extracts the text from a INodeList or even from the IHtmlDocument.

**Comment by FlorianRappl** [comment]
The `Text<T>` method does. You get it by using `AngleSharp.Extensions` - as with all other extension methods. Hope this helps you @ricardobrandao!

**Comment by ricardobrandao** [comment]
I saw that one but I wasn't able to make it work then. For instance, this test fails (it retuns a null value):

``` C#
[Fact]
public void StripHtmlTagsTest1()
{
    var input = "<div><span>Hello, world! Some <a href=\"#\">link.</a></span></div>";
    var dom = new HtmlParser().Parse(input);
    Assert.Equal("Hello, world! Some link.", dom.Text());
}
```

However I've found now that this one does the trick:

``` C#
[Fact]
public void StripHtmlTagsTest2()
{
    var input = "<div><span>Hello, world! Some <a href=\"#\">link.</a></span></div>";
    var nodeList = new HtmlParser().ParseFragment(input, null);
    Assert.Equal("Hello, world! Some link.", string.Concat(nodeList.Select(x => x.Text())));
}
```

Thanks for the quick reply :)

**Comment by FlorianRappl** [comment]
The `dom` is a document - if you would use it on `dom.Body` or `dom.DocumentElement` it should actually work.

**Comment by fpavlic** [comment]
Is there a way to get just 'visible' content e.g. "DocumentElement.TextContent" without Scripts and Styles?

This is something @devmondo mentioned 2013th.

Thanks

**Comment by FlorianRappl** [comment]
AngleSharp can't decide which text is relevant for you and which isn't. It will just return what the spec says it should return.

**Comment by jeremycook** [comment]
@fpavlic this may not interest you anymore but you could remove elements you do not want from the DOM before calling `.Text()`. So find and remove all `<script>` and `<style>` elements first.
