### ISSUE TITLE
Url not being Loaded in Class Library

### ISSUE THREAD

**Issue by isaacrlevin** [AngleSharp/AngleSharp#600]
I have this block of code that seems to work fine when running from Console App or Azure Function, but from inside a Class Library, the value of HtmlDocument.Source.Text is empty string

````
var config = Configuration.Default.WithDefaultLoader();
var address = "https://www.fantasysharks.com/apps/bert/forecasts/projections.php?League=&Position=1&Segment=598&uid=4";
var document = BrowsingContext.New(config).OpenAsync(address).Result;
HtmlDocument doc = new HtmlDocument();
doc.LoadHtml(document.Source.Text);
````

Is there a limitation to where AngleSharp can be run from?

**Comment by FlorianRappl** [comment]
No there is no limitation, but maybe the following questions are helpful in tracking down the issue

- Are there any restrictions in the system?
- Are you seeing the request being performed?
- Can you debug it (i.e., do you see any exceptions occuring, e.g., in some loader)?
- Could you swap the loader to a custom one, e.g., from the HttpRequester from AngleSharp.Io?
- Can you check with some other page (potentially one available via standard HTTP) to verify if its the same behavior (maybe there is an issue with the certificate of fantasysharks.com)?

**Comment by isaacrlevin** [comment]
@FlorianRappl I will try when I get back to my laptop but just confused why it work in an inline azure function but doesn't in a CL consumed by a console app.

**Comment by isaacrlevin** [comment]
Figured it out, the site doesn't support TLS1, so this little snippet fixes the issue

````
ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
````

**Comment by FlorianRappl** [comment]
Great, thanks for the info!
