### ISSUE TITLE
Empty selector returns elements

### ISSUE THREAD

**Issue by GuerrillaCoder** [AngleSharp/AngleSharp#601]
I just tracked down a bug in my own code, I am not sure if it is due to expected behaviour or not.

I have this line of code:

```c#
var filter = element.QuerySelectorAll(filterSelector);
```

Sometimes `filterSelector` is empty string.  When it is empty string it sometimes returns some random elements.  In debugger I can see their access key is `""` so I guess that's why maybe.  I would expect empty selector not to return anything, is there a purpose for this?

Right now my workaround is pretty nasty.  If filter is empty I write a random string to it as I cant figure out how to create empty `HtmlCollection<IElement>`.

Something like:

```c#
HtmlCollection<IElement> filter = new HtmlCollection<IElement>();
if (!String.IsNullOrEmpty(filterSelector)) filter = element.QuerySelectorAll(filterSelector);
```

But `HtmlCollection` isn't public so this doesn't work.  I am guessing there is another public object that implements same interface I should be using but I cannot see it from looking at code.

Any suggestions?

**Comment by FlorianRappl** [comment]
Well, an empty selector should actually throw an exception, so I guess that this is actually a bug in AngleSharp. Does the bug also exist in v0.10 or which version of AngleSharp are you using?

Regarding the code: Why don't you make

```csharp
var filter = default(IHtmlCollection<IElement>);
if (!String.IsNullOrEmpty(filterSelector)) filter = element.QuerySelectorAll(filterSelector);
```

If you want to spare the null check for filter (I don't know your usage, but it may be) and you are only interested in the IEnumerable part, then

```csharp
var filter = Enumerable.Empty<IElement>();
if (!String.IsNullOrEmpty(filterSelector)) filter = element.QuerySelectorAll(filterSelector);
```

would also work.

**Comment by GuerrillaCoder** [comment]
Thanks.  I haven't seen default keyword before so that is really handy I will remember it,.  `Enumerable.Empty<IElement>();` fits my purposes exactly, many thanks for the suggestions.

I am using version 0.9.9.  I am not sure how to get version 0.10.

**Comment by FlorianRappl** [comment]
Alright, no worries about v0.10 (you have to clone the repo and build the `devel` branch). I'll flag it as a bug for so long (even though unknown for v0.10, but that way a test will be created anyway).
