### ISSUE TITLE
AngleSharp for static html pages?

### ISSUE THREAD

**Issue by mkzrt** [AngleSharp/AngleSharp#603]
I tested AngleSharp and not performed well. Especially when parsing dynamic content.
I think this package is suitable for static HTML pages not for web pages including dynamic or AngularJS {{anyvalue}}  expressions.

As you know Html page source is different from DOM inspector.
Hope I can get answer. Thanks.

**Comment by FlorianRappl** [comment]
I am not sure what you are after. AngleSharp.Core is only for static content as no JS engine is coming out of the box. I doubt AngleSharp.Scripting.JavaScript is ready for something as heavyweight as AngularJS - but any question related to this should be placed in the respective repo (e.g., in this case AngleSharp.Scripting.JavaScript).

BTW: The HTML page source has to be identical. What you mean is probably that the page DOM (hence you mention the DOM inspector - this does not show the page source, but the *current* tree, which may be totally different to one inferred by the HTML page source) does not meet your expectations.

**Comment by mkzrt** [comment]
Sure AngleSharp is only for static content not for apps built by AngularJS. Thanks.
