### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by verysimplenick** [AngleSharp/AngleSharp#606]
Hi, found this library, many thanks for your work.
But "devel" branch for now has 238 commits ahead of master, [nuget](https://www.nuget.org/packages/AngleSharp) not updated for one+ year.
Author maybe bump up version and go next?

**Comment by FlorianRappl** [comment]
Does not seem to happen soon. Reasons are lack of contributors and lack of Microsoft to support this project. If you read through some issues you will see the reason that `devel` is that far ahead is v0.10, which extracted the CSS part (AngleSharp.CSS), however, that one is not 100% ready / solved.

There could be an update for the 0.9.9, however, .NET tooling went orthogonal by dropping project.json and not supporting the same cross platform (e.g., .NET 4, SL5, and .NET Standard 1.0) builds as we've had in the earlier tooling. That way the AppVeyor build breaks, which is a showstopper.
