### ISSUE TITLE
Conditional tags are converted to conditional comments (nuget version 0.9.9)

### ISSUE THREAD

**Issue by alex-becker-startp** [AngleSharp/AngleSharp#609]
Hello,

when conditional tags are parsed, they are converted to conditional comments.

```
var source = "<![if IE]> if-IE comment revealed <![endif]>";
var doc = parser.Parse(source);
var out = doc.ToHtml();
out == "<!--[if IE]--> if-IE comment revealed <!--[endif]-->";
```
see [About conditional comments](https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx)

I do not think this should happen.
Alexander.

**Comment by FlorianRappl** [comment]
Hi Alexander, no this should happen. Please check with non-IE browsers. Conditional comments are IE only constructs and not specified. As such fully HTML5 compliant parsers will parse them like that.

Remark: Generally, before a parser bug is reported it is a best practice to check the same page in different browsers. In this case it may be tricky, as some browsers would deviate from the norm by supporting the IE specific conditionals (I tried Edge, Chrome, and Firefox - all three seem to behave as expected and therefore match AngleSharp's behavior; IE will certainly deviate).

**Comment by alex-becker-startp** [comment]
Hi Florian,

okay now I understand the source of my problem better. I did not expect that AngleSharp actually evaluate these tags. When I look in the DOM of such a parsed page in IE I can see the observed changes there, too.

My problem is that I use AngleSharp to prepate HTML for editing in an email client.
And especially when replaying to outlook mails there is a lot of these crappy code in the source mail...
When these comments are pre-processed by AngleSharp, the wpf webbrowser component and my wpf html editor control actually displays the modified comment tags (converts  to &lt;!--[xxx]--&gt;)

Now I solved this by "escaping" <![if]> before parsing with AngleSharp as  which will not be touched by AngleSharp at all. And simply remove --~~~~ and ~~~~-- after .ToHtml().

**Comment by FlorianRappl** [comment]
Hi Alexander, potentially a more reliable and faster way would be to let AngleSharp parse it and use a tree walker to remove these nodes. Alternatively, if you care most about the `ToHtml` method you could provide our own formatter, which could omit these tags / information. It's quite easy to detect as it is always startin with a comment tag and ending with a comment tag. The order is fixed making things straight forward. Big advantage of this process is that you could also easily adjust for other conditionals (e.g., certain versions of IE being matched, or Outlook specific comments such as ` [if gte mso 11]`). As a basis you would use the standard HTML formatter - you would just have your own comment serializer (to identify a start / end conditional) and your own tag function (to surpress serialization if a certain flag was set from the comment function).

Other than that your method of course works as well. Thanks for your insights! 👍

**Comment by mdesousa** [comment]
Hi, I'm running into this same issue. Unfortunately, if the document forces IE compatibility to an old version you actually get incorrect display in IE.
The code below illustrates the problem (you need to save the result in a file and open in IE). I'll try the recommendation to remove the nodes through the tree walker, and will post the code for that:
```
var html = "<html><head><meta http-equiv=\"X-UA-Compatible\" content=\"IE=5\"></head><body><![if !supportLists]><span>Hello World</span><![endif]></body></html>";
var parser = new HtmlParser();
var document = parser.Parse(html);
document.DocumentElement.OuterHtml.Should().Be(html);
```

**Comment by mdesousa** [comment]
Sharing the code that I used to delete the conditional comments... thanks
```
document.Descendents<IComment>().Where(x => x.NodeValue.StartsWith("[")).ToList().ForEach(x => x.Remove());
```
