### ISSUE TITLE
NullReferenceException when HTML payload starts with a comment

### ISSUE THREAD

**Issue by DaniilVeriga** [AngleSharp/AngleSharp#610]
Parsing this HTML throws a NullReferenceException.

```
<!-- Comment -->
<html>
<head></head>
<body></body>
</html>
```

There was a very similar report with a comment at the end which was fixed: #459

**Comment by FlorianRappl** [comment]
Which version? What platform? Does the error still occur on `devel` of 0.10? Thanks!

**Comment by Retoxified** [comment]
Hi Florian, the issue occurs in version 0.9.9.0 on ASP.NET under .NET 4.5.2

**Comment by Retoxified** [comment]
This issue also occurs with the following;
&lt;?xml version="1.0" encoding="utf-8" standalone="no"?&gt;

but the following works fine, despite being a similar styled tag.
&lt;!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"&gt;

**Comment by FlorianRappl** [comment]
> Does the error still occur on devel of 0.10?

**Comment by FlorianRappl** [comment]
I created a test for it. Does not fail. So this does not seem to be an issue.
