### ISSUE TITLE
Submitting a Form Documentation

### ISSUE THREAD

**Issue by isaacrlevin** [AngleSharp/AngleSharp#612]
I have tried going through the closed and open issues as well as the docs and cannot find an example of submitting a form. Is there a preferred approach? For instance do you use DoClick() or Submit the Form using #242? Neither have seemed to work for me

**Comment by FlorianRappl** [comment]
The usual way would be to use the `Submit` method. I'm not sure why it does not work for you - without the corresponding HTML and C# I cannot give you any hints. Have you integrated a loader / how does your config look like?

**Comment by FlorianRappl** [comment]
Closing this in favor of #242.
