### ISSUE TITLE
Stackoverflow crash when parsing element with multiple slashes

### ISSUE THREAD

**Issue by dennisgorelik** [AngleSharp/AngleSharp#613]
We compiled the most recent AngleSharp 0.10.0 version from "devel" branch.
This code reproduces fatal StackOverflowException crash:
```
[TestMethod]
public void AngleSharpExcessiveSlashesTest()
{
	string dangerousHtml = "<a " + new string('/', 10000); // 5000 passes, 8000 crashes both in debug and run mode
	new HtmlParser().ParseDocument(dangerousHtml);
}
```

Test run Output in Visual Studio:
> Error] The active Test Run was aborted because the execution process exited unexpectedly. To investigate further, enable local crash dumps either at the machine level or for process vstest.executionengine.x86.exe. Go to more details: http://go.microsoft.com/fwlink/?linkid=232477

**Comment by FlorianRappl** [comment]
Thanks for reporting the issue - I'll provide a fix!

**Comment by dennisgorelik** [comment]
That seems to be similar to https://github.com/AngleSharp/AngleSharp/issues/523
Is this StackOverflowException caused by recursive calls too [while processing slashes inside elements]?

**Comment by FlorianRappl** [comment]
Its a different one (even though both have obviously recursion as root cause). Yes the slash triggers a recursion - solution is to loop it / catch that edge case.
