### ISSUE TITLE
How to parse style attribute in svg element?

### ISSUE THREAD

**Issue by duncanawoods** [AngleSharp/AngleSharp#614]
I have tried:

i) Using the HtmlParser - but the Style property on the svg element is null.

ii) Parsing the style attribute value with the CssParser - but doesn't produce any rules

Is there a way to invoke the inline style parser outside of html parsing? I can't see it in the parser namespace.

thanks!

**Comment by duncanawoods** [comment]
I was able to get this far

    var cssStyleEngine = new CssStyleEngine();
    var cssStyleOptions = new StyleOptions(BrowsingContext.New());
    var style = cssStyleEngine.ParseDeclaration(element.GetAttribute("style"), cssStyleOptions);
    style.FontSize = newFontSize;
    element.SetAttribute("style", style.CssText);

But disappointed to find that .CssText butchered the attributes  such that this:

    font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:28.22222137px;line-height:1.25;font-family:'DejaVu Sans Mono';-inkscape-font-specification:'DejaVu Sans Mono, Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-feature-settings:normal;text-align:start;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;text-anchor:start;fill:#ff2a2a;fill-opacity:1;stroke:none;stroke-width:0.26458332;

becomes this

    font: normal normal bold normal 10px / 1.25 "DejaVu Sans Mono"; letter-spacing: 0; word-spacing: 0; text-anchor: start; stroke: none

Had to resort to regexes.

**Comment by FlorianRappl** [comment]
You can set the options of the CSS parser to avoid parsing the values (and other stuff which may alter the output). `CssText` is not the original text, but just the serialization of the parsed model.

If you would use `GetAttribute` you will get the content of the original attribute independent of any CSS options.

Hope this helps!

**Comment by duncanawoods** [comment]
Hi Florian, thanks for the reply.

> CssText is not the original text, but just the serialization of the parsed model

The issues with ParseDecl/CssText is that it has lost attributes e.g. fill:#ff2a2a has gone missing. Is that because they are svg attributes and the CssStyleEngine is html specific?

> GetAttribute you will get the content of the original attribute independent of any CSS options.

Yup. I have resorted to GetAttr/regex/SetAttr but I'd love to be able to parse and sett attributes values without my sketchy regexes.

**Comment by FlorianRappl** [comment]
> The issues with ParseDecl/CssText is that it has lost attributes e.g. fill:#ff2a2a has gone missing. Is that because they are svg attributes and the CssStyleEngine is html specific?

Yes, at the moment only HTML properties have been added, i.e., you would need to activate the ignore unknown declarations option in order to avoid dropping declarations with an unknown property names. Hope this helps!
