### ISSUE TITLE
How to Set ‘Referer’ value to  Requester.Headers?

### ISSUE THREAD

**Issue by oienwav** [AngleSharp/AngleSharp#617]
I try to set 'Referer' by myself:

`var Requester = new HttpRequester();`
`Requester.Headers["Referer"] = "http://abc.com/";`
`var configuration = Configuration.Default.WithDefaultLoader(_=> _.IsResourceLoadingEnabled = true, new[] { Requester });`
`var _context = BrowsingContext.New(configuration);`
`var _document = _context.OpenAsync("http://iguazi.wang/httphand.php").Result.DocumentElement.OuterHtml;`

but the result does not contain 'Referer' value:

`User-Agent: AngleSharp/0.9.9`
`Connection: keep-alive`
`Host: iguazi.wang`
`Accept-Encoding: gzip, deflate`

Is there any way to do it?

**Comment by FlorianRappl** [comment]
This looks rather like a bug to me. The thing with referer is that in some .NET implementations it was a property on the http web requester and ignored as a header. As such it is treated differently. On some platforms, unfortunately, the property is read-only or non-existing (but ignored nevertheless).

Can you please mention your boundary conditions (.NET implementation, system, ...)?

**Comment by oienwav** [comment]
Thank you for your reply。
I use it in my Xamarin.Forms project.

**Comment by FlorianRappl** [comment]
Ok, so I suppose its a rather custom implementation of the underlying requester. Could be that this implementation works differently.

What could you do about it / to verify it?

Copy the code from https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Network/Default/HttpRequester.cs in your own requester implementation (call it, e.g., `MyHttpRequester`).

1. Try to comment lines 266-269
2. If that does not help uncomment the lines and debug the `SetProperty` method

Reasoning: The `SetProperty` method is a "workaround" to let the different .NET implementations handle the special header declarations properly by setting the corresponding property (if possible). For efficiency, the decision is cached. I suspect that the `Referer` property is either gone in the Mono / Xamarin implementation or that the `SetProperty` has a bug that may be only reflected in such an edge case situation.

Any feedback appreciated!
