### ISSUE TITLE
Change proxy on an existing IBrowsingContext

### ISSUE THREAD

**Issue by PsykotropyK** [AngleSharp/AngleSharp#620]
Hello, 

I created an IBrowsingContext with an HttpClient that is setup with a specific proxy :

> HttpClientHandler httpClientHandler= new HttpClientHandler()
                {
                    Proxy = proxy.HttpProxy,
                    PreAuthenticate = true,
                    UseDefaultCredentials = false,
                };
HttpClient client = new HttpClient(httpClientHandler);
HttpClientRequester requester = new HttpClientRequester(client);
var configuration = AngleSharp.Configuration.Default.WithDefaultLoader(requesters: new[] { requester }).WithJavaScript().WithCss();
var context = BrowsingContext.New(configuration);

I want at runtime to be able to change the proxy on this context. How can I reassign a new configuration? I tried something like this but it's still the same proxy (with newrequester using a different proxy the rest is the same code as for requester):

> context.Configuration.WithDefaultLoader(requesters: new[] { newrequester }).WithJavaScript().WithCss();

Is it feasible ? Does it makes sense or recreating a whole new context is the way?

**Comment by FlorianRappl** [comment]
The configuration is immutable and the context uses the one instance of the configuration. So yes, with the means you used here the answer is clear. However, you are not restricted to using the `HttpClientRequester`. You could wrap it and change the underlying instance on the fly, therefore sparing the need for changing the full context.

Pseudo-ish code to show you the idea:

```cs
class MyWrappedRequester : IRequester {
  private HttpClientHandler _handler;
  private IRequester _requester;

  public HttpProxy Proxy {
    get {
      return _handler.Proxy;
    }
    set {
      _handler = new HttpClientHandler() {
        Proxy = value,
        PreAuthenticate = true,
        UseDefaultCredentials = false,
      };
      _requester = new HttpClientRequester(new HttpClient(_handler));
    }
  }

  // just forward the _requester methods / properties in the implementation
}
```

Ideally you would set a default in the constructor of this class. Otherwise, demand a default in the signature of the constructor.

Hope this helps!

**Comment by PsykotropyK** [comment]
Works tremendously.

For future users, here's my code (Requester & Context class that will have the IBrowsingContext)

```C#
public class Requester : IRequester
    {
        private HttpClientHandler _handler;
        private IRequester _requester;

        public IWebProxy Proxy
        {
            get
            {
                return _handler.Proxy;
            }
            set
            {
                _handler = new HttpClientHandler()
                {
                    Proxy = value,
                    PreAuthenticate = true,
                    UseDefaultCredentials = false,
                };
                _requester = new HttpClientRequester(new HttpClient(_handler));
            }
        }

        public Requester(IWebProxy proxy)
        {
            Proxy = proxy;
        }

        public Task<IResponse> RequestAsync(IRequest request, CancellationToken cancel)
        {
            return _requester.RequestAsync(request, cancel);
        }

        public bool SupportsProtocol(string protocol)
        {
            return _requester.SupportsProtocol(protocol);
        }
    }
```

```C#
public class Context
    {
        public Requester Requester { get; set; }
        public IBrowsingContext Page { get; set; }

        private IConfiguration _configuration;

        public Context(Requester requester)
        {
            Requester = requester;
            _configuration = Configuration.Default.WithDefaultLoader(requesters: new[] { Requester }).WithJavaScript().WithCss();
            Page = BrowsingContext.New(_configuration);
        }
    }
```

And to use 

```C#
_proxy = new WebProxy("[ip]:[port]");
Requester req = new Requester(_proxy);
context = new Context(req);
```

then I can change Context.Requester.Proxy

**Comment by FlorianRappl** [comment]
Awesome work! 🍻
