### ISSUE TITLE
AngleSharp 0.9.9 not installed to VS2017 project

### ISSUE THREAD

**Issue by ghost** [AngleSharp/AngleSharp#621]
Hello,
I am using AngleSharp 0.9.9 in my several VS2017 projects.
But, I am facing a strange symptom.
Some of the projects, I can successfully install AngleSharp 0.9.9 and it works fine.
But, in some of the projects, when I install AngleSharp 0.9.9 by nuget,
no error messages are shown and installation successfully done.
But, in the solution explorer, there is no AngleSharp 0.9.9 reference.
Then, I downgrade it to AngleSharp 0.9.8.1 by nuget, it is shown in the referense list.
So, I am using AngleSharp 0.9.8.1 and it works fine.
But, I want to know why I can not install 0.9.9 in my some of the projects.
If you can find the solution, please let me know.

**Comment by FlorianRappl** [comment]
Sounds strange to me - have you checked with NuGet that this is no bug? What does VS2017 projects refer to? Projects created with VS2017 or projects running in VS2017? Also what is the patch level of both, VS2017 and NuGet?

**Comment by ghost** [comment]
Hello,
&gt;have you checked with NuGet that this is no bug?
In VS2017, NuGet Package Manager is automatically installed.
So, I think that NuGet I am using is the latest one.

&gt;What does VS2017 projects refer to?
Sorry. I want to mean VS2017 C# projects. 
They are mainly ASP.NET MVC projects or class library projects.

&gt;Also what is the patch level of both, VS2017 and NuGet?
VS2017 Community Ver 15.5.2
NuGet Package Manager 4.5.0

I have ever experienced a similar symptom in VS2015 with another package that is not AngleSharp.
At that time, problem was solved by updating NuGet.
But, this time, I have no idea what to do.

**Comment by FlorianRappl** [comment]
Hi @hiromi3 thanks for providing the detailed info. Unfortunately on my VS2017 installation (I am on the latest preview 15.5 preview 5) I cannot reproduce. Maybe I find a machine with 15.5.2 to try it out. Maybe someone from the NuGet team could help you / us here? If its something with the AngleSharp package then my NuGet knowledge may be also too low to provide a solution.

**Comment by ghost** [comment]
Hi FlorianRappl,
Thank you for your reply.
If VS2017 ver 15.6 is released, I will install it and test the problem again.
I will report the result to you.

In my VS2017 ver 15.5.2 , the following procedure will reproduce the problem.
Create C# New Console Project with .NET Framework 4.7 .
Add AngleSharp 0.9.9 by NuGet Package Manager.
The messages in output window show that the installation was successfully done, but AngleSharp is not listed in reference.
Then I downgrade it to 0.9.8.1 , AngleSharp is shown in reference list.
Then, I upgrade it to 0.9.9, it is removed from the list.
So, it is very strange!

Anyway, currently I am using 0.9.8.1 and it is enough for me.

**Comment by FlorianRappl** [comment]
> The messages in output window show that the installation was successfully done, but AngleSharp is not listed in reference.

I think placing an issue [on the official GitHub repo](https://github.com/NuGet/Home/issues) would be super!

**Comment by ghost** [comment]
Hello,
I reported the symptom to NuGet official github.
https://github.com/NuGet/Home/issues/6347
I hope the problem will be fixed.

**Comment by FlorianRappl** [comment]
Thanks for the info! Let's see what comes out.

**Comment by ghost** [comment]
Hello,
Today, I installed the latest 0.9.9.1, I could install it successfully.
I do not know why previous 0.9.9 has a installation problem in my VS2017, anyway, the problem was solved.
If the problem happens again, I will report to you.

**Comment by FlorianRappl** [comment]
Ah great to hear. Well, from the tool chain perspective nothing changed, so maybe it was just a hiccup. Glad that it works now!
