### ISSUE TITLE
Can't Find Div

### ISSUE THREAD

**Issue by markolbert** [AngleSharp/AngleSharp#622]
I'm very new to AngleSharp, and not sure where to post these kinds of questions, as the latest AngleSharp stuff on stackoverflow.com seem to be fairly old.

I'm writing a simple screen scraper for NextDoor.com. I've been able to do the necessary login, and return the starting news feed page. But when I try to submit something to the search box on the top of the page, AS can't find the form element.

Here's a screen grab of the news feed page, along with the chrome debugger display of the page, showing the search form:

![as-news-feed](https://user-images.githubusercontent.com/9095610/34175413-344c125c-e4b1-11e7-92b5-d120b97c6abe.png)

![as-header-search](https://user-images.githubusercontent.com/9095610/34175424-3b4f0eba-e4b1-11e7-8c02-1d779ab46ee3.png)

Here's the code I'm using to find the search form, which is returning null:

`var searchForm = BrowsingContext.Active.QuerySelector<IHtmlFormElement>( ".header-bar-global-search-form" );
`

I've verified, as best I can, that the Active document is, in fact, the news feed page. Also, when I search for #layout_container, which is the ultimate parent of the form div I'm searching for, it's deemed to not have any child elements...which is odd.

I noticed that the search form is contained within a div marked with data-reactroot, and am wondering if there's some behind-the-scenes DOM manipulation going on which I'm not handling in AngleSharp.

**Comment by FlorianRappl** [comment]
I think the page actively uses JavaScript. I am not sure if you are using a JS engine within AS, however, even if you would - the JS used on the page may just be too much to handle in AS (at the moment).

Have a look at the transported source. If that one does not contain elements within `#layout_container` (but some scripts) you know this is the case.

**Comment by markolbert** [comment]
Thanx for the quick reply. You may be right about there being some fairly complex javascript work going on.

How do I check the transported source? I presume you’re referring to the raw response text, but, if so, I’m not sure how to access that through AngleSharp.


  *   Mark

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by FlorianRappl** [comment]
The `IDocument` has a property called `Source`. This is the text source as seen from the parser. It has a property called `Text`, so e.g., `document.Source.Text` could show you what you need to know. The other option is to use the browser and "show source" (this is also the transported source, the modified model is only available via JS / the JS console or the DOM explorer).

Hope this helps!

**Comment by markolbert** [comment]
Thanx. I suspect the problem is that the site I'm trying to scrape is a reasonably heavy user of React. At least, all the pages that use React are the ones that AngleSharp has problems with.

But I found a workaround: I use AngleSharp in conjunction with Selenium. Selenium, because "all" it does is run a regular browser does a good job of rendering pages. But it's slow when searching for things, and the API isn't as elegant as AngleSharp. So I just use HtmlParser to parse the Selenium-provided page source and I'm good to go. It's still not as fast as AngleSharp, but it works reasonably well.

BTW, in case it isn't obvious: AngleSharp is an >>awesome<< library, IMHO. Kudos to you for developing it!

**Comment by FlorianRappl** [comment]
Thanks for the nice words @markolbert - and also for providing details on the workaround you've found! I hope that in the future I (or hopefully some others as well) will find the time to make AngleSharp.Scripting / the whole AngleSharp project powerful enough to be able to cope with heavy frontend scripts such as React or Angular.
