### ISSUE TITLE
HTML Entity encoding incomplete

### ISSUE THREAD

**Issue by GieltjE** [AngleSharp/AngleSharp#623]
Some characters get decoded but not encoded (e.g. &#243; gets decoded to ó but not encoded in the end).

I would expect the end result to be "`<html><head></head><body>&#243; &#243; &amp;</body></html>`" but instead the result is "`<html><head></head><body>ó ó &amp;</body></html>`".

```
	HtmlParser parser = new HtmlParser();

	using (IHtmlDocument document = parser.Parse("<html><head></head><body>&#243; ó &</body></html>"))

		MessageBox.Show(document.ToHtml());``

**Comment by FlorianRappl** [comment]
I'm not sure if I can follow (both things look equal to me). Why should ó be encoded (and to what)? The string serialization is UTF-16 (.NET strings). What is missing here? Can you please be a little bit more specific? Thanks!

**Comment by GieltjE** [comment]
Sorry took me a while to get the github formatting to display the proper values, should be clearer now (some characters do get encoding, some don't).

For reference the .net encoding: ```MessageBox.Show(WebUtility.HtmlEncode("ó &"));```

**Comment by GieltjE** [comment]
After some thinking, it usualy wouldn't make much of a difference as:
- Most pages get send as UTF-8 which accept these characters without problems (I guess)
- It thus probably only matters for email where the encoding isn't specified in the head

But I still would recomend at least a Boolean orso to enforce "extended" encoding or not.

**Comment by FlorianRappl** [comment]
Hi @GieltjE - according to the official W3C serialization only a few characters are encoded (e.g., the ampersand, opening and closing diamond bracket). HTML is no format that is guaranteed to be HTML(1) -> DOM -> HTML(2), such that HTML(1) is the same as HTML(2). The individual characters are not stored as a previously encoded token or not (this is an entity, which is party of the XML DOM, but for different reasons).

Hope this helps!
