### ISSUE TITLE
.NET Core 2.0 support

### ISSUE THREAD

**Issue by Nefcanto** [AngleSharp/AngleSharp#626]
I saw Nuget page:

https://www.nuget.org/packages/AngleSharp/

It seems that version 0.9.9 is the latest version, and the way I understood it only supports .NET Core 1.0.

Do you have a plan to support .NET Core 2.0 also? Because our entire platform is in .NET Core 2.0, and based on an almost huge R&D we found this library to be awesome and we want to use it.

**Comment by FlorianRappl** [comment]
.NET Core 2.0 is a superset of 1.0 and thus this should work automatically if I am not mistaken. What problem are you running into?
