### ISSUE TITLE
include the "insertAdjacentHTML" method this is similar to jQuery Append

### ISSUE THREAD

**Issue by insinfo** [AngleSharp/AngleSharp#629]
insertAdjacentHTML() parses the specified text as HTML or XML and inserts the resulting nodes into the DOM tree at a specified position. It does not reparse the element it is being used on and thus it does not corrupt the existing elements inside that element. This avoids the extra step of serialization, making it much faster than direct innerHTML manipulation.

**benchmark showing that insertAdjacentHTML can be way faster in some cases.**
insertAdjacentHTML is supported by all browsers, and a W3C standard.
https://w3c.github.io/DOM-Parsing/#dom-element-insertadjacenthtml

**Syntax**
element.insertAdjacentHTML(position, text);

**Visualization of position names**
-- beforebegin --
p
  -- afterbegin --
  div
  -- beforeend --
/p
-- afterend --

**Comment by FlorianRappl** [comment]
Is already included, see `Insert`.
