### ISSUE TITLE
Trying to sanitize inputs using htmlsanitizer

### ISSUE THREAD

**Issue by mateiteo** [AngleSharp/AngleSharp#630]
Hello,
I've been trying  to use AngleSharp to sanitize the text inputs in my application.
I installed AngleSharp through VisualStudio 2017 and I've been faced with managing(adding and removing) cs files in order to provide the functionality with the necessary elements while avoiding conflicts with the core elements.
Can you please provide a few tips about what to include in the project so that the sanitization would be functional?
Thank you!

**Comment by FlorianRappl** [comment]
I am not quite sure I understand your question. What specifically do you want to do? Any code snippets? Also for questions (in general) please use StackOverflow (tag:anglesharp).

AngleSharp is not a sanatizer - it is the core of a browsing engine consisting of useful parsers and helpers such as an HTML5 parser. If your input is HTML then you can use AngleSharp to reason about it.
