### ISSUE TITLE
AngleSharp doesn't parse `noframes` element

### ISSUE THREAD

**Issue by cyotek** [AngleSharp/AngleSharp#631]
Hello,

I converted the bulk of my read-only HTML processing to be based on AngleSharp and I have a bunch of tests failing that all seem to have the same root cause - the contents of the `noframes` element aren't parsed into HTML objects.

Consider the following snippet

```html
<html>

  <frameset cols="30%,*">
    <frame src="frame1.php" name="frame1">
    <frame src="frame2.php" name="frame2">
    <noframes>
      <body>
        <p>This text will appear only if the browser does not support frames.</p>
        <p><img src="..\..\assets\img\city10.png" alt="city10"></p>
      </body>
    </noframes>
  </frameset>

</html>
```

I should be able to query the contents of the `noframes` element, but I can't - the entire contents have been reduced to a `TextNode` instead. Of course, using frames is supposed to be obsolete these days, but tell that to any number of sites out there :)

The only error raised (from `HtmlParser.Context.ParseError`, assuming that is how they are reported) was one stating the doc type wasn't defined, which is true enough.

I also attached a simple sample I used to reproduce externally of clunky tests.

Regards;
Richard Moss

[AngleSharpFrames.zip](https://github.com/AngleSharp/AngleSharp/files/1608844/AngleSharpFrames.zip)

**Comment by FlorianRappl** [comment]
The behavior is expected. `noframes` is only parsed if frames is not supported. The HTML5 algorithm switches into rawtext mode once such a tag is found.

Currently, there is no way to disable this (but I guess we can provide a way). I'll flag this as "enhancement" and "API" to note that we could extend the API with a flag to disable frame parsing (thus enabling `noframes` parsing).
  
By the way: Yes, `frames` are obsolete, but explicitly handled in the HTML5 spec. Therefore, what you see is the same behavior as in any evergreen browser.

**Comment by cyotek** [comment]
Thanks for the response. Can't say I'd ever noticed this in a real browser, but at the same time (apart from test cases/pages), I can't remember the last time I deliberately wrote a frameset! 

An option to force all parsing would be great, although I can probably workaround it in the interim. Are there any other elements where the parser behaves in a similar fashion?

**Comment by FlorianRappl** [comment]
If with similar fashion you mean rawtext then, e.g., `style` is coming to my mind. Also `noscript`, however, here the behavior is determined by the connection to a scripting engine. Without any `noscript` is parsed as a standard DOM tree, otherwise its content is ignored (and rawtext is parsed).

Again we will never be able to force all parsing, rather just be selective if we want to support a certain thing (if we don't support frames these elements will be parsed with rawtext, even though they *should* normally have no children).

**Comment by cyotek** [comment]
Thanks for the tips. CSS I don't mind as I currently "parse" that myself, and I had never considered `noscript` so I have no idea if it works or not, I'll need to check that. I currently don't do JavaScript either although when I saw that AngleSharp could actually do it and avoid me having to write a full blown system it was like Christmas all over again!

I tested adding a workaround to replace the raw contents with parsed elements. While this worked I noted it automatically added `html` and `head` elements (probably due to me passing `null` as the context to `ParseFragment`, but passing the original document's body didn't return anything and trying to cheat by passing in `document.CreateElement("div")` caused lost elements after adding them 😕 ). So I added a workaround to the workaround to find and process children of the new body... which is getting a bit silly.

As I noted in another issue, I don't particular care for standards compliance as I'm not in control of the data being parsed, so it can be (and often is) anything. I want to be able to read the _entire_ HTML DOM, extract bits from it, modify those bits, and write it back - without changing the original document beyond those expected modifications.

I think this last bit is potentially going to be a problem - when I serialize the snippet in the first post (regardless of if I do my own post manipulation or not), the output HTML is no longer the same as it has an empty `head` element in it and I'd much rather it output the original document the same way HtmlAgilityPack does.

**Comment by FlorianRappl** [comment]
Nah I think you confuse the meaning of *original document*. Every document has a `head` - even if its not in the source. That is just what the standard tells you. If no `head` is in the source, you will still get an `head` element. That is the **DOM** (it is an object model, not the source code! - be sure not to confuse the two).

That being written also the initial thing you get is the **DOM** - the only valid child of `noframes` is a text node (and by definition such a tag triggers the raw text mode, so anything inside will be text). Yes, what you can do you can do, but I would do it much different.

Note that the inner content is rather just a new document. Why not just parse the new document and append the body to the `noframes` (replacing the current text node).

I've written the following code in LINQpad:

```cs
var html = @"<html>

<frameset cols=""30%,*"">
<frame src=""frame1.php"" name=""frame1"">
<frame src=""frame2.php"" name=""frame2"">
<noframes>
 <body>
   <p>This text will appear only if the browser does not support frames.</p>
   <p><img src=""..\..\assets\img\city10.png"" alt=""city10""></p>
 </body>
</noframes>
</frameset>

</html>";
var config = Configuration.Default;
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(m => m.Content(html).Address("http://example.com"));
var noframes = document.QuerySelectorAll("noframes");
var parser = new HtmlParser(new HtmlParserOptions
{
	IsEmbedded = true,
	IsScripting = false,
}, config);

foreach (var noframe in noframes)
{
	noframe.TextContent.Dump();
	var content = await parser.ParseAsync(noframe.TextContent);
	noframe.ReplaceChild(content.Body, noframe.FirstChild);
	noframe.TextContent.Dump();
}
```

Compare the two outcomes: One is the full source of `noframes`, the other is just the text inside the DOM created by the source of the `noframes`.

Hope this helps!

**Comment by cyotek** [comment]
Thanks for that, that is much simpler than how I was doing it via `ParseFragment`. You are right, I am confusing the original source versus the _complete_ DOM as I'm thinking simply in terms of the final textual output from text source.

**Comment by FlorianRappl** [comment]
Yes, but if you think about the output from text source then you need to think about parsing. When you think about parsing you need to think about the rules. And the rule for parsing a `noframes` tag is as applied by AngleSharp (as it follows the official specification). Anything else is arbitrary.

**Comment by FlorianRappl** [comment]
Added `IsNotSupportingFrames` to the `HtmlParserOptions`.
