### ISSUE TITLE
Question: Accessing the Internal / Full CSS Model

### ISSUE THREAD

**Issue by atlastodor** [AngleSharp/AngleSharp#633]
Looking at the source, the CSS properties have a rich internal model. Is there a way to publically access that model?

For example, a "margin-left" property internally contains a AngleSharp.Css.Values.Length value. Using the ICssProperty.Value, I can only get a string representation of the value. It would be nice to get the full value, so I don't have to parse the string and basically re-implement features that are already in AngleSharp.

Thanks / Danke!

**Comment by FlorianRappl** [comment]
Yes, I totally agree. And it is part of the new [AngleSharp.Css](https://github.com/AngleSharp/AngleSharp.Css), which will be released together with AngleSharp v0.10, see https://github.com/AngleSharp/AngleSharp.Css/issues/5.

Hope this helps!

**Comment by atlastodor** [comment]
Hi Florian,

Can you give me (a non binding) indication of when AngleSharp.Css / AngleSharp 1.0 is expected to be released?

Thanks!
-Todor

**Comment by atlastodor** [comment]
Hi Florian,

What is the status of v0.10? Can you give me some non-binding estimate when this will be available? Also, what resources are needed to speed up the process?

-Todor

**Comment by FlorianRappl** [comment]
> What is the status of v0.10?

Most of it done, but needs to be revisited (with some of the issues mentioned here; what could / should still be in there). Mostly, AngleSharp.Css is in the way.

> Can you give me some non-binding estimate when this will be available?

Definitely in Q1 / 2018, but I guess not before March. Let's see... Can go quite quickly when I have some dedicated time for it, but at the moment some other projects are in the critical path.

> Also, what resources are needed to speed up the process?

Of course contributors would help (big issue for any OSS in .NET unfortunately; in JS or C++ the communities always seem to be much more active -- I don't know why and how to change this). Other than that making AngleSharp "paid" (e.g., have some sponsors for the development) would help (i.e., for myself usually paid projects have higher prio than non-paid ones; for two reasons: one is direct stakeholder(s) and thus a commitment towards them, two is that money is still paying the electricity bill for me). The danger in some kind of sponsorship is obviously that these sponsors would then "steer" the project.

Sorry for the late response; thought I answered already - but apparently I forgot about it 😨 .

**Comment by atlastodor** [comment]
Hi and thanks for the response.

We are working on a functionality that needs to parse some documents containing CSS and that we want to release in April. With a little bit of luck, we may be able to use AngleSharp.CSS and I won't have to code a hack by hand.

I was hoping that you would answer something in that direction. I understand the priority issue (been there myself) and that there are bills to be paid. I am sure that company I work for would not mind sponsoring some part of the development, if that can accelerate the release of the AngleSharp.CSS. Afterall, it costs money no matter if we sponsor AngleSharp or if I code CSS property values parser by hand. If you are interested to discuss further, please contact me per email (todor.todorov@atlasti.com) or Skype (todor.todorov.dk).
