### ISSUE TITLE
Some pages with redirection block execution

### ISSUE THREAD

**Issue by southpolenator** [AngleSharp/AngleSharp#634]
Try executing this code with nuget 0.9.9.1:

string address = "http://www.bancaintesa.rs/";
var config = Configuration.Default.WithDefaultLoader();
var context = BrowsingContext.New(config);
var document = context.OpenAsync(address).Result;

It will block on execution of getting document as result. If you change address to redirected address: http://www.bancaintesa.rs/pocetna.1.html it will load document correctly.

**Comment by FlorianRappl** [comment]
Hi - thanks for the report. I will look into that!

**Comment by FlorianRappl** [comment]
Yes, I can confirm the bug for v0.9.9.1, but it is already solved in v0.10.

**Comment by southpolenator** [comment]
Is there an ETA on when 0.10 will be available through nuget?

**Comment by FlorianRappl** [comment]
I'll try to make it happen in Q1, hopefully sooner than later. In the meantime you could workaround this either by providing your own loader (thus detecting the redirect and handling it) or performing the load yourself and giving AngleSharp the stream.

Alternatively, you can, of course, build from source. However, please note that v0.10 has some changes and that you may also need to build some other projects (e.g., AngleSharp.Css, if you need CSS support).
