### ISSUE TITLE
JavaScript 

### ISSUE THREAD

**Issue by PsykotropyK** [AngleSharp/AngleSharp#635]
Hello,

The following is mostly a copy paste of an issue I posted on Stackoverflow, which seems like a bug to me. [Here's the original link](https://stackoverflow.com/questions/48126071/submitting-item-within-a-form) .

I am struggling a bit with a form submitting using AngleSharp.

I use AngleSharp to Scrap [this website](http://www.gatherproxy.com/proxylist/anonymity/?t=Elite) for Proxies addresses. Basically I open the website with AngleSharp and a IBrowsingContext (Page in my code)

I then SubmitAsync the Forms[0] to have the full list of proxies (see the website link to understand what I mean) and read the different proxies there [this part is not presented here].

It then got more complicated when I want to navigate within the different pages (usually around 60 pages with a navigating bar at the bottom, i.e. Forms1 in the Page).

As advised by Florian Rappl I turned on the ressource loading based on an example he gave ([see here](https://github.com/AngleSharp/AngleSharp.Samples/blob/master/AngleSharp.Samples.App/ViewModels/MainViewModel.cs)). In the code posted below I commented with the memory usage as it seems the ressource loading is loop downloading something with the memory usage skyrocketting. For comparison I provided the memory usage without the ressource loading. This is a fully workable code for a console app.

```C#
static void Main(string[] args)
    {
        ASTester().GetAwaiter().GetResult();
        Console.ReadKey();
    }
```

```C#
static async Task ASTester()
    {
        var Handler = new HttpClientHandler()
        {
            PreAuthenticate = true,
            UseDefaultCredentials = false,
        };

        var Client = new HttpClient(Handler);
        Client.DefaultRequestHeaders.TryAddWithoutValidation("User-Agent", "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36");

        var Requester = new HttpClientRequester(Client);

        var Configuration = AngleSharp.Configuration.Default.WithDefaultLoader(setup =>
        {
            setup.IsResourceLoadingEnabled = true;
        }, requesters: new[] { Requester }).WithJavaScript().WithCss();
        var Page = BrowsingContext.New(Configuration);


        /*At this point : 
         *              Mem usage : ~15 MB
         */

        /*Open the page with the proxy list 
         *      with setup.IsResourceLoadingEnabled = true; 
         *              Mem usage : ~80 MB
         *      without
         *              Mem usage : ~35 MB
         */
        await Page.OpenAsync("http://www.gatherproxy.com/proxylist/anonymity/?t=Elite");

        /*Submit the first form (id = 0) which will activate the bar to navigate within the different pages
         *      with setup.IsResourceLoadingEnabled = true; 
         *              Mem usage : 300 MB
         *      without
         *              Mem usage : ~50 MB
         */
        await Page.Active.Forms[0].SubmitAsync();

        /*Activate the script to go to page 2
         *      with setup.IsResourceLoadingEnabled = true; 
         *              Mem usage : 1.5 GB
         *      without
         *              Mem usage : >> Exception
         */
        Page.Active.ExecuteScript("gp.pageClick(2);");

        //Giving time for the script to execute
        Thread.Sleep(40000);

    }
```

Half of the time the script execution throw an exception. For the rest the Page.Active evaluation is `'((AngleSharp.Dom.Document)((AngleSharp.BrowsingContext)Page).Active).ActiveElement' threw an exception of type 'System.NullReferenceException'`

**Comment by FlorianRappl** [comment]
For JS related issues the AngleSharp.Scripting repository should be used.

Again, the JS scripting engine is experimental and depending on the complexity and used DOM API surface a working solution may not be expected.

I do not see much of a bug, nor any evidence of it. The core page loads and obviously the page you deal with extensively uses JS.

**Comment by PsykotropyK** [comment]
For me having over a gigabit of memory usage for something that does not use a kb under a déborder

**Comment by PsykotropyK** [comment]
Sorry if I posted it in the wrong place. Still to me the fact that your library need over 1.5 GB to load scripts that takes below 10MB within a browser is a bug. I'll shift to CEF Sharp, which is way less nice than how you managed the tree structure of AngleSharp but handle properly JS. Thanks for the answers here and on Stackoverflow

**Comment by FlorianRappl** [comment]
You confuse things. It loads all the assets. Resource loading is not limited to scripts, but will load everything (I don't know what resources the page(s) use, so I can only guess - you would see significant traffic for the behavior you outlined).
