### ISSUE TITLE
Consider exposing HtmlTokenizer as public API

### ISSUE THREAD

**Issue by SteveSandersonMS** [AngleSharp/AngleSharp#636]
First, thanks for this excellent library! It's great to see such a well-maintained project at this scale.

I'm working on a new Razor syntax compiler and one of the things it needs to do is tokenize incomplete HTML fragments such as `"<h1 my-attribute="` so that it can generate instructions incrementally. The `HtmlTokenizer` in AngleSharp is perfect for this job, or at least it would be if it was `public`.

Would you consider exposing `HtmlTokenizer` as `public` in a future version of AngleSharp? As a library maintainer I'm aware of the extra documentation and maintenance cost, so I can entirely understand why it isn't already `public`. But since there are strong use cases for it as an independent API, and the `HtmlTokenizer` implementation is already solid and well documented internally, perhaps you would consider making it part of the AngleSharp feature set.

**Comment by FlorianRappl** [comment]
Yeah this is a sound request and definitely something I have on my mind for v1.

In general not much needs to be done here (except declaring some things public, e.g., the tokenizer, the tokens, ...), but trying to find a final layout and potentially some convenience abstractions.

Thanks!

**Comment by FlorianRappl** [comment]
Actually with the recent traction of Blazor I will already expose the tokenizer in the next hotfix (I know; the name hotfix then does not fit so much then...).

Expect this thing to be out in a week; I only need to find a good model for exposing the tokens and make it work easily. But performance-wise this will be exactly (I hope) what you want / desire.

Sounds good @SteveSandersonMS or anything else I could / should consider?

(For completeness the comment in the `dev` branch version of the AngleSharpBuilder of Blazor https://github.com/aspnet/Blazor/blob/dev/src/anglesharp/AngleSharpBuilder/Program.cs).

**Comment by SteveSandersonMS** [comment]
That's perfect @FlorianRappl - thanks very much!
