### ISSUE TITLE
How to get the OuterText only from an HTML element

### ISSUE THREAD

**Issue by vickyRathee** [AngleSharp/AngleSharp#638]
Any way I can get the OuterText only from an HTML element? 

For example "By Apple" only in below HTML example. I tried to use ".product" selector and then removed all children's from the element and then extract TextContent, that worked. But the problem is, that the RemoveChild method removes the children from original HTML and I can't extract the H1, SPAN 
thereafter

string result = element.RemoveChildren().TextContent;

**HTML**
```
<div class="product">
<h1>iPhone X</h1>
<span>64gb</span>
   By Apple
</div>
```
**RemoveChildren**

```
public static AngleSharp.Dom.IElement RemoveChildren(this AngleSharp.Dom.IElement element)
{
            var elementCopy = element;
            foreach (var node in elementCopy.Children)
            {
                elementCopy.RemoveChild(node); // Remove the children elements
            }
            return elementCopy;
}
```

**Comment by FlorianRappl** [comment]
There is essentially no outer HTML - I guess what you want is to only get the direct descendend text node children.

```cs
var textParts = element.ChildNodes.OfType<IText>().Select(m => m.TextContent);
var result = String.Join(" ", textParts);
```

Hope that helps!

**Comment by vickyRathee** [comment]
Yes, that works perfectly. I named it OuterText in my extension 👍

**Comment by FlorianRappl** [comment]
Cool! Glad I could help.
