### ISSUE TITLE
Html whitespaces to be excluded from Html dom

### ISSUE THREAD

**Issue by mazurewa** [AngleSharp/AngleSharp#639]
Hi,

We have a problem with parsing html using AngleSharp. Out input html body is:

![image](https://user-images.githubusercontent.com/23196464/35217659-f4b09668-ff63-11e7-9530-5228d5ca0153.png)

We use parser configured as below: 

var config = new AngleSharp.Configuration().WithCss(e => e.Options = new CssParserOptions
            {
                IsToleratingInvalidValues = true
            });
var html = new HtmlParser(config).Parse(rawHtml);

This results in having 7 child nodes, instead of 3, so that we have 4 TextNodes unwanted here (please see the screenshot below):

![image](https://user-images.githubusercontent.com/23196464/35216953-5ee0e324-ff61-11e7-9fe2-4b3cbe66b964.png)

We are aware that we can use Children property to retrieve elements, but then we lose any free text that could be put in <body> element. We are also aware that parser cannot automatically assess which text we want to be included and which to be extracted. 

Could you tell me please if you have any suggestion how can we distinguish those parts and not have html whitespaces be included in Html dom?

Thanks,
Ewa

**Comment by FlorianRappl** [comment]
Unfortunately, these whitespaces are part of the HTML spec (your browser sees them as well).

There is no way to distinuigh between them reliably - in theory you can do it like React and strip text nodes after elments that only consist of newline + optional spaces / tabs. However, please note that some of these may be wanted / needed.

Hope this helps!

**Comment by mazurewa** [comment]
Yes, we came to the same conclusion. Thanks you anyway!
