### ISSUE TITLE
Anglesharp web scrapping website with intervals and paging

### ISSUE THREAD

**Issue by sohaibameen** [AngleSharp/AngleSharp#640]
Hi, 

Its me Sohaib Ameen here from Lahore, Pakistan working as a software developer. 

I have been working on to find the best .NET library to scrap data from different websites. 

I have this one website where data is being displayed in a grid. On initial load, data is loaded in grid. 

1- Grid data gets refreshed every 60 seconds which is the default time but one can change the time and can expect system to refresh data by that time. 

2- Once data gets loaded in grid, user see a functionality to expand/collapse functionality as well provided in the grid because every row can contain multiple children. When user expands one record, system generates an AJAX request to fetch child records with respect to selected parent record and binds with grid. 

3- Once child records get displayed in grid once, system generates paging for the records if they are great number of records and on selecting on one page, system generates another AJAX request to display data with respect to selected page. 

Considering all these scenarios, I have few questions. 

1- How can we scrap data with AngleSharpwhen website gets refreshed every 60 seconds?

2- Do we have any possible JavaScript support to make this happen, If there is then how can we do it and scrap the possible data from given website? 

Note : I have read about checking out the network to see the how requests are being made so I am hoping if you guys have created any example to scrap data with these kind of scenarios. 

Please provide suitable answer because It is the most important thing to do. As there are large number of commits every now and them so I expect a detailed answer with a demo application. 

I would appreciate your answer and support on it. 

Best Regards, 

Sohaib Ameen

**Comment by FlorianRappl** [comment]
> Please provide suitable answer because It is the most important thing to do. As there are large number of commits every now and them so I expect a detailed answer with a demo application.

Just check out the [samples repository](https://github.com/AngleSharp/AngleSharp.Samples). For everything else please submit to [StackOverflow using the "anglesharp" tag](https://stackoverflow.com/questions/tagged/anglesharp).
