### ISSUE TITLE
Can not login to an ASP.Net Application

### ISSUE THREAD

**Issue by sohaibameen** [AngleSharp/AngleSharp#642]
Hi, 

I have downloaded your demo project just to check If I can submit a form. 

Whenever I run the WPF application and try to load the page, It redirects me to some other page of the website for some unknown reason and shows the content of that page instead of login page. 

Here is the link, you can try that by yourserlf : http://carrier.realtimefreight.com/login.aspx

Can you please take a look of why it is happening because there are numerous sites not showing the content, especially when It is using an Iframe. 

Basic purpose of this post is to know If we can submit a form with the help of anglesharp. 

I shall appreciate your answer and support. 

Best Regards,
Sohaib

**Comment by FlorianRappl** [comment]
For generic questions please use StackOverflow. Also make sure to provide a MWE, e.g., you are missing basics such as the configuration you are using (are you activating requests? is JS active / needed? ...). Which demo project are you using?

There is a demo project that does exactly that - submitting a form with AngleSharp. Maybe you should start with this one.

**Comment by sohaibameen** [comment]
I have gone through the stackoverflow as well but I could not find anything related to my problem. 

I have downloaded the demo project in which you have created a sample web application and a WPF application is using that web application to login and get the secret value.
 
https://github.com/AngleSharp/AngleSharp.Demos.DeveloperWeek

Can you explain a little about activating requests?

In some cases JS is needed as well, I am not sure how to check from demo application if it is activated. 

Please let me know if the anglesharp is parsing the web page from the link I gave to you.

**Comment by FlorianRappl** [comment]
> I have gone through the stackoverflow as well but I could not find anything related to my problem.

Yes, in such cases the next step is to post to SO. Other than that I did not check the page - I do not have time for this.

If you found a bug (please incl. a MWE) or have a feature request then please do so. Otherwise, just check out the WPF demo project code. Requests are activated there. It's really just a configuration of the requester. VS has quite good development support (something called IntelliSense), so just by exploring the code you should be able to solve your problem.
