### ISSUE TITLE
How to build (devel)?

### ISSUE THREAD

**Issue by FroggieFrog** [AngleSharp/AngleSharp#643]
I tried to build the branch "devel" but got following error, when executing "build.ps1":

Executing task: Restore-Packages
Failed to load msbuild Toolset

I only have VS2017 installed.

**Comment by FlorianRappl** [comment]
Unfortunately, this is a limitation of NuGet (see https://github.com/NuGet/Home/issues/3975). In the long run AngleSharp will update to NuGet v4, but right now the multi-target support is still wanted (and only available pre v4).

I think you could modify Cake / NuGet to look for MSBuild 15 (via an explicit path).

Hope this helps!

**Comment by zwcloud** [comment]
Just got the same error: `Failed to load msbuild Toolset` on the latest release.

![image](https://user-images.githubusercontent.com/6965758/45936545-83d7a380-bfea-11e8-8a3e-0663d6cb0d3d.png)

> Failed to load msbuild Toolset  
>   Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.  
> An error occurred when executing task 'Restore-Packages'.  
> Error: One or more errors occurred.  
>         NuGet: Process returned an error (exit code 1).

**Comment by FlorianRappl** [comment]
Build now works with latest VS tool chain!
