### ISSUE TITLE
selector works in browser, but not in AS

### ISSUE THREAD

**Issue by jawbrey** [AngleSharp/AngleSharp#646]
I have a selector that used to work great, but now is failing.  It still works in every browser I tested

[The page](http://calendar.kinsmenlutheran.org/VirtualEMS/BrowseEvents.aspx)

the selector is "li.calendarEvent".  In the browser it returns ~141 hits for the current month.

When I run in in AS, I get 0.  

```
var address = "http://calendar.kinsmenlutheran.org/VirtualEMS/BrowseEvents.aspx";
var document = await BrowsingContext.New(config).OpenAsync(address);
var cellSelector = "li.calendarEvent";
var events = document.QuerySelectorAll(cellSelector).ToList();
```

I'm sure this used to work a few weeks ago.  I'm not aware of any changes to the page structure, but I can't guarantee that it didn't change, as I don't control it.

Should this work?  Am I doing something wrong?

thanks!

**Comment by FlorianRappl** [comment]
I looked at the source, `calendarEvent` is not even mentioned. I guess the selector is only possible because some elements have been inserted by JS. AngleSharp alone clomes without JS.

Hope this helps!
