### ISSUE TITLE
On-Board Project to the .NET Foundation

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#648]
With the upcoming release v0.10 (and subsequently v1.0) AngleSharp needs to reform and regroup to prevent a stall in development as it was in the recent year.

The following list should be handled completely. We will use this issue to track progress and provide transparency in the process.

## Getting into the .NET Foundation

- [x] Make sure the project has a good name that is easy to remember and spell. Check that it doesn't [conflict with another existing project](http://ivantomic.com/projects/ospnc/)
- [x] Make sure the people involved in the project want to join the .NET Foundation
- [x] Make sure the project has a clear understanding about how it accepts contributions and the process
     it follows when selecting new committers to the project.
- [x] [Register an interest](https://dotnetfoundation.org/get-involved) in joining the .NET Foundation
- [x] Work with the .NET Foundation to fill out an On-Boarding Questionaire
- [x] .NET Foundation sends out completed questionaire to .NET Foundation Advisory Council for comments
- [x] .NET Foundation Executive Director submits new project proposal to the .NET Foundation Board
- [x] Configure a CI build for the project and ensure build status badges are available from the README

## Once accepted into the .NET Foundation

- [ ] Sign the contribution / assignment agreement
- [ ] Agree a date to move into the .NET Foundation
- [ ] Prepare a guest blog post announcing the move on the .NET Foundation Blog
- [ ] Read the [code of conduct](https://dotnetfoundation.org/code-of-conduct), [link to it in your code](be-nice.md) and understand what to do if you are concerned about any behaviour or have concerns reported to you.
- [ ] Tell the world we have joined!
- [ ] Get CLA Automation enabled to ensure contributors can easily sign the [Contribution License Agreement](https://cla2.dotnetfoundation.org/cladoc/net-foundation-contribution-license-agreement.pdf)
- [ ] Send a PR to add the Project into the .NET Foundation [list](https://github.com/dotnet/home/tree/master/projects)
- [ ] Ensure the repo contents are up to date with [.NET Foundation guidance](repo-guide.md)
- [ ] Review the [README guidance](readme-guide.md) and update if necessary
- [ ] If applicable [update the LICENSE file](copyright.md) to show Copyright has been assigned to the .NET Foundation and look to update any file headers.
- [ ] If applicable, update any copyright statements in websites owned by the project to reflect assignment to the .NET Foundation
- [ ] If applicable, update any websites associated with the project to include "Supported by the <a href="https://dotnetfoundation.org">.NET Foundation</a>" or similar link back to the .NET Foundation in the footer. If applicable, please include image links from [our swag repo](http://github.com/dotnet/swag). (We think a link in the footer using the horizontal logo looks very nice.)
- [x] [Sign up for Project Leader news](http://eepurl.com/bOCfJP)
- [ ] Configure any resources requested from the .NET Foundation (SSL Certs, Code Signing, Secret Management, Build Servers etc)

**Comment by FlorianRappl** [comment]
Since the .NET Foundation did never come back to me (despite their initial move) I will close this for now. Quite disappointed on how this is run and how this ended ...

I guess things can only get better from here on.

**Comment by jogibear9988** [comment]
In linq2db we have the same problem, never got an answer

**Comment by FlorianRappl** [comment]
Sounds like a common issue @jogibear9988. A little bit of background on how this story went: I actually already contacted them last year (in August), but never got an answer. So I spoke with them in person at the MVP Summit (in March). That helped and it seemed to go on from this point on (see this item + the blog post). However, I never heard back.

I really think this is a capacity issue. They acknowledged receiving the questionnaire and ensured me that it will be taken to the next level once they come back to me. That never happened.
