### ISSUE TITLE
[question] Get children recursively?

### ISSUE THREAD

**Issue by JustArchi** [AngleSharp/AngleSharp#649]
I'm currently looking for a way to get all children recursively. In particular for my example:

```html
<div class='tier'>
   <div class='tier-head'>
      <div class='tier-details'><span>Price: <strong>3,99&euro;</strong></span></div>
      <div class='tier-number'>
         <div class='tierNumberTriangle'></div>
         <div class='tierNumberContent'>Tier 2</div>
      </div>
      <div class='tier-note'></div>
   </div>
   <div class='tier-content'>
      <div class='bundle-item collected'>
         <div class='bi-content'><a href='#/page:game/info?plain=balancity'>BalanCity</a></div>
         <div class='bi-info'>
            <div class='bi-details'><a href='http://store.steampowered.com/app/462680/' class='bi-price bi-current shopMark steam'
               title='Current best price of the game'><span class='dealTagDesc'>cur: </span> 7,99&euro;</a><a href='#/page:game/info?plain=balancity' class='bi-price bi-lowest shopMark humblestore'
               title='The lowest recorder price this game has had'><span class='dealTagDesc'>low: </span> 0,45&euro;</a><a href='#/page:game/info?plain=balancity' class='bi-times shopMark'
               title='How many times has this game appeared in a bundle'>2<span class='dealTagDesc'>&times;</span></a></div>
            <div class='bi-rw f-tiny' title='75% positive Steam reviews'>75%</div>
            <div class='bi-tc'></div>
            <div class='bi-keys'><span class='shopTitle steam'>Steam</span></div>
            <div class='bi-platforms'><span class='platform windows'
               title='Windows'>W</span><span class='platform mac'
               title='Mac'>M</span><span class='platform linux'
               title='Linux'>L</span></div>
         </div>
      </div>
   </div>
</div>
```

I want to get `<div class='tier'>` (there will be more than one in original html) which contains somewhere inside itself `a` element with `href` attribute ending with `?plain=balancity`. I wrote following LINQ query:

```csharp
internal static IEnumerable<IElement> GetChildrenRecursively(this IElement e) => e.Children.Union(e.Children.SelectMany(c => c.GetChildrenRecursively()));

var result = htmlDocument.All.FirstOrDefault(p => p.LocalName.Equals("div") && p.ClassList.Contains("tier") && p.GetChildrenRecursively().Any(c => c.LocalName.Equals("a") && c.Attributes.Any(a => a.LocalName.Equals("href") && a.Value.EndsWith("?plain=balancity", StringComparison.Ordinal))));
```

As you can see I also wrote my own `GetChildrenRecursively()` function which does the trick for me, but I'm now wondering if there isn't a better way to achieve that with something more native to the library itself which would let me skip going through entire (useless for me) structure just to search for `a` element. Something like XPATH's `//` or HtmlAgilityPack's `Descendants()` done on `<div class='tier'>` element. Maybe it'd be worth to add this addition to library itself, or maybe it already exists and I'm unaware of it?

Thank you in advance.

**Comment by FlorianRappl** [comment]
AngleSharp is DOM first, so anything that works against the standard DOM works also in AngleSharp.

```cs
document.QuerySelectorAll("div.tier a[href$=?plain=balancity]")
```

This will get you all these anchor elements. You could now either take those as a standard point and find the respective div as one of the ancestors (there is such a convenience function available via the `AngleSharp.Extensions` namespace), or you do it differently:

```cs
document.QuerySelectorAll("div.tier").Where(m => m.QuerySelector("a[href$=?plain=balancity]") != null)
```

AngleSharp is really about embracing web technologies instead of fighting it. In the end the best of both worlds (e.g., query selectors and LINQ queries) can be combined to achieve things which would either be impossible (query selectors alone) or quite tedious (only LINQ).

Hope this helps!

**Comment by JustArchi** [comment]
Thank you a lot for answer 🙂
