### ISSUE TITLE
Unnecessary escaped Underscore

### ISSUE THREAD

**Issue by Suchiman** [AngleSharp/AngleSharp#65]
While performing a Form.Submit ("application/x-www-form-urlencoded") i noticed that a key contains a escaped underscore. This doesn't match browsers behaviour (tested in IE and FF) and other APIs for UrlEncoding.

I traced it down to this Method [StringExtensions.UrlEncode](https://github.com/FlorianRappl/AngleSharp/blob/215a4a1b713c7d0e9f46e337bb63a2ea47bf3ef9/AngleSharp/Extensions/StringExtensions.cs#L764)

**Comment by FlorianRappl** [comment]
Hm, can you name a good test case? I've build one on my own, but if you have a good one that is really sensitive to the transmitted data (i.e. any unnecessary percent encoding will result in an error) then I would prefer to use that.

(The commit should have fixed the issue -- but I would like to add some test(s) before closing it)

**Comment by Suchiman** [comment]
No, i'm sorry. I randomly saw that while figuring out why form post didn't work as expected and comparing browser made requests to AngleSharps. The reason for that wasn't the escaping but #67

**Comment by FlorianRappl** [comment]
Alright, you're initial issue had still to be resolved, hence no problem.
