### ISSUE TITLE
[Question] Form Submission

### ISSUE THREAD

**Issue by stcn89** [AngleSharp/AngleSharp#651]
Hello, I have just found AngleSharp and I have been testing for about 2 days on different websites.
And on some websites I get Insecure browser right after login, for example comcast :
`
            var requester = new AngleSharp.Network.Default.HttpRequester();
            requester.Headers["User-Agent"] = "Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0";
            var configuration = Configuration.Default.WithDefaultLoader(requesters: new[] { requester }).WithJavaScript().WithCookies();
            AngleSharp.Configuration.SetDefault(configuration);
            var browsingContext = BrowsingContext.New(configuration);
            browsingContext.Parsing += BrowsingContext_Parsing;
            browsingContext.Requesting += BrowsingContext_Requesting;

            await browsingContext.OpenAsync("https://login.xfinity.com/login");
            Console.Write(browsingContext.Active.Title);
            System.IO.File.WriteAllText("0.html", browsingContext.Current.Document.DocumentElement.OuterHtml);
            await browsingContext.Active.QuerySelector<IHtmlFormElement>("form[action='https://login.xfinity.com/login']").SubmitAsync(new
            {
                user = "user@comcast.net",
                passwd = "passwd"
            });
            Console.Write(browsingContext.Active.Title);
            Console.Write(browsingContext.Active.Url);
            await browsingContext.OpenAsync("https://my.xfinity.com/oauth/login?continue=http%3A%2F%2Fmy.xfinity.com%2F%3Fcid%3Dcust%26amcid%3DSEG_MYACCOUNT");
            Console.Write(browsingContext.Active.Title);
            Console.Write(browsingContext.Active.Url);
`

I don't know why but It does not want to log in, strange is that before settings the user-agent header , it was showing insecure browser from the first request , now it shows the login form but i can`t get in. Any ideas on how to fix that ? Thanks in advance.

**Comment by FlorianRappl** [comment]
I've  never seen that "Insecure Browser", however, many websites use the user agent for all kinds of weird things. Its unfortunate but that's the world we live in. So just changing the user agent (as you did) gets a step further in such cases.

Regarding the question: No I don't know - you already do the right things with cookies and such. I would therefore exclude an anti-forgery token as the problematic part.

Have you tried without JavaScript? If the site offers a non-JS version it would definitely help, otherwise you could have to deal with high-end JS libraries which are beyond the very simple AngleSharp scripting lib.

Hope this helps!

**Comment by stcn89** [comment]
OK, after some testing vs whoer.net here is what I found out:
-Even if I use WithJavaScript() , javascript is not detected : http://prntscr.com/ityymy
-The user-agent is sent via headers but not detected with JS since it is disabled/not detected.

Is there any solution to intercept the call to window.navigator.userAgent ? So that I could return the 
userAgent string ?
I tried non-JS version as you said , got the same problem, for me it does not make any sens cause a regular HTTP request using chilkat works, it logs in.


P.S. I have compared AngleSharp with NHtmlUnit and AngleSharp is much faster, so BRAVO !

**Comment by FlorianRappl** [comment]
Honestly, I have no clue how this page is doing a JS detection. But the navigator is already returning a similar string (see https://github.com/AngleSharp/AngleSharp.Scripting/blob/master/src/AngleSharp.Scripting.JavaScript/Dom/Navigator.cs).

There are multiple ways of extending AngleSharp to intercept the JS (but most of them wrap the JS execution). I am not sure if it would help though (a lot of effort, gain unknown at the moment).
