### ISSUE TITLE
[Question] Cookies

### ISSUE THREAD

**Issue by stcn89** [AngleSharp/AngleSharp#652]
How do you list all the cookies (cookie name, value,domaine,expiration date, path, etc) of a BrowsingContext ?
`            var requester = new AngleSharp.Network.Default.HttpRequester();
            requester.Headers["User-Agent"] = "Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0";
            var configuration = Configuration.Default.WithDefaultLoader(requesters: new[] { requester }).WithCookies().WithJavaScript();
            AngleSharp.Configuration.SetDefault(configuration);
            var browsingContext = BrowsingContext.New(configuration);`

is `browsingContext.Active.Cookie` the only way ?

**Comment by FlorianRappl** [comment]
The other way is accessing the used cookie service (e.g., `MemoryCookieService`). What you described only gives you access to the `document.cookie` of the active document.

Hope this helps you!
