### ISSUE TITLE
External stylesheets not loaded

### ISSUE THREAD

**Issue by j055** [AngleSharp/AngleSharp#653]
I want to find colours used in a web page. The following code only gets styles from embedded styles. No external stylesheets are loaded.

```
var address = new Uri("http://localhost");
var config = Configuration.Default.WithDefaultLoader().WithCss();
var document = await BrowsingContext.New(config).OpenAsync(address.AbsoluteUri);

foreach (var element in document.All)
{
	var style = document.DefaultView.GetComputedStyle(element);
	if (style.Color != string.Empty) Console.WriteLine(style.Color);
	if (style.BackgroundColor != string.Empty) Console.WriteLine(style.BackgroundColor);
}
```

Is there a configuration option I'm missing?

Thank you.

**Comment by FlorianRappl** [comment]
Yes, by default the loader does not load resources (only performs navigation). This is to prevent too much unnecessary loading (e.g., images, stylesheets, ...).

So replace

```cs
var config = Configuration.Default.WithDefaultLoader().WithCss();
```

with

```
var config = Configuration.Default.WithDefaultLoader(s => s.IsResourceLoadingEnabled = true).WithCss();
```

and the stylesheets should load. Hope this helps!

**Comment by j055** [comment]
Yes this helps. It would be nice if I could choose which resources to load. Getting the images as well is a bit costly. Do I need to create a custom loader? I could load the stylesheets separately and then embed them myself into the document but that seems a bit clunky. Can you suggest something?

**Comment by FlorianRappl** [comment]
There is a filter option. This one lets you choose which files to load.

```cs
WithDefaultLoader(s => 
{
    s.IsResourceLoadingEnabled = true;
    s.Filter = req => true; // allows all
})
```

The request gives you the URL, originator in form of an element or node (if any), as well as other information that can be useful when going for a pro / con decision. 

Hope this helps!
