### ISSUE TITLE
[Question] Socks 5

### ISSUE THREAD

**Issue by stcn89** [AngleSharp/AngleSharp#654]
Is it possible to use Extreme.Net or xNet with AngleSharp (to have socks5 support)?
Tried everything but with no luck.
And I know this the following is not related to AngleSharp, but is there any way to forward socks5 as HTTP proxy on localhost ?
I really am desperate to find a solution,
Thanks in advance.

**Comment by FlorianRappl** [comment]
Yes, totally possible.

AngleSharp really does not care what HTTP requester you use. As long as you throw a `Stream` in you are good. If you want to have more convenience just implement an `IHttpRequester` using the mechanism / technology you like.

Hope this helps!
