### ISSUE TITLE
How to get all song titles on wikipedia discography page?

### ISSUE THREAD

**Issue by TEDSON007** [AngleSharp/AngleSharp#657]
I want all song titles under the 'Singles' header
I'm trying this code...

>
> public static List<string> Songs(string url)
>             {
> 
>                 string pageSource = PageSource.Get(url);//https://en.wikipedia.org/wiki/The_Kinks_discography
>                 HtmlParser parser = new HtmlParser();
>                 var doc = parser.Parse(pageSource);
>                 var wikitables = doc.All.Where(tag => tag.LocalName == "table" && tag.GetAttribute("class") == "wikitable");
>                 if (wikitables == null)
>                 {
>                     return null;
>                 }
>                 List<string> LS = new List<string>();
>                 foreach (var item in wikitables)
>                 {
>                     if (item.PreviousSibling != null && 
>                         item.PreviousSibling.PreviousSibling != null &&
>                         item.PreviousSibling.PreviousSibling.HasChildNodes)
>                     {
>                         // <a
>                         var x = item.Children[0].Children[2].Children[1].Children[0];
>                         if (x != null)
>                         {
>                             var y = x.GetAttribute("title");
>                             LS.Add(y.Trim());
>                         }
>                     }
>                     
>                     
>                 }
>                 return LS;
>             }

but I only get the first song under each sub-header 
1960s, 1970s, 1980s, 1990s, 2000s

I'm coming from htmlagility pack but I was lousy at that too, I'm rather new to parsing.
Thank you for reading, all help appreciated.

**Comment by FlorianRappl** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/anglesharp) in the future for questions.

The following should give you a pointer in the right direction:

```cs
public static async Task<List<String>> Songs(String url)
{
    var context = BrowsingContext.New(Configuration.Default.WithDefaultLoader());
    var document = await context.OpenAsync(url);
    var rows = document.QuerySelectorAll("table.wikitable > tbody > tr");
    var songs = new List<String>();
	
	foreach (var row in rows)
	{
		var first = row.FirstElementChild;
		
		if (first == null || first.LocalName == "th")
			continue;
		
		var cell = first.HasAttribute("rowspan") ? row.Children[1] : first;
		
		if (cell != null && cell.LocalName == "td")
		{
			var link = cell.FirstElementChild;
			
			if (link != null && link.LocalName == "a")
			{
				songs.Add(link.TextContent);
			}
		}
	}
	
    return songs;
}
```

Hope this helps!
