### ISSUE TITLE
Getting different encoding in responses for the same request

### ISSUE THREAD

**Issue by a-a-k** [AngleSharp/AngleSharp#658]
I've faced that when testing parsing for several sites. One of them returns incorrect encoding when running together but working okay when running lonely in the own process. In other hand, response captured by fiddler is absolutely normal. 
```
var context = BrowsingContext.New(new Configuration().WithDefaultLoader().WithCookies());
var url = "https://volgograd.piluli.ru/search_result.html?searchback=&search=%ed%ee-%f8%ef%e0";
var document = await context.OpenAsync(url);
```

Response in Fiddler:

![image](https://user-images.githubusercontent.com/5455861/38634026-969835c4-3deb-11e8-9178-37e8c93a1a05.png)

![default](https://user-images.githubusercontent.com/5455861/38616439-3e42e270-3dbe-11e8-8f5f-ed0ea29c1cae.jpg)

At the same time in VS debugger view:

![2](https://user-images.githubusercontent.com/5455861/38616896-be3f9404-3dbf-11e8-950a-1c363d8b4308.jpg)

What should I check and fix, could you direct me for figuring out?

**Comment by a-a-k** [comment]
For reproducing I've created a console app repo - [AngleSharp_Issue-658](https://github.com/a-a-k/AngleSharp_Issue-658)

**UPDATED 13/04/2018 15:45 UTC**

**Comment by yauhenipakala** [comment]
Hi everyone!

I have absolutely the same issue.

    AngleSharp 0.9.9.2

Do you any updates or workaround?

**Comment by FlorianRappl** [comment]
I cannot reproduce the problem using standard .NET. Hence I assume it is a bug in .NET Core / what you used with the encoding provider registration and has nothing to do with AngleSharp. I'll close this for now. Please make sure you hit the right target for the issue / bug report.

Thanks!
