### ISSUE TITLE
Anglesharp turns relative links into absolute links when modifying

### ISSUE THREAD

**Issue by GuerrillaCoder** [AngleSharp/AngleSharp#659]
In angleSharp when I try to edit a relative link and then save it back to HTML it always saves it back as an absolute url.  For instance `<a href="/home.htm"></a>` will get turned to `<a href="http://example.com/home.htm"></a>`.

I found this GitHub issue referencing it where you say this is how browser works but I cannot see how to bypass this behavior: https://github.com/AngleSharp/AngleSharp/issues/53

I want to edit relative links and keep them relative, not convert all relative URLs to absolute URLs.

This is my code

```c#
var host = "example.com";
var editFiles = GetFilesToEdit();

var configuration = Configuration.Default;
var context = BrowsingContext.New(configuration);

foreach(var filePath in editFiles)
{
	var file = File.ReadAllText(filePath);

	var document = context.OpenAsync(res => res.Content(file).Address("http://" + host)).Result;

	var links = document.QuerySelectorAll("a").OfType<IHtmlAnchorElement>().ToList();

	var tests = links.Where(x => x.Host != host).ToList();

	foreach(var link in links)
	{
		var queryString = link.Search;
		if (!string.IsNullOrWhiteSpace(queryString))
		{
			link.Search = null;
			link.PathName = link.PathName + WebUtility.HtmlEncode(queryString);
		}
	}
	var html = document.DocumentElement.OuterHtml;
	File.WriteAllText(filePath, document.ToString());

}
```

How can I modify URLs without converting them to absolute URLs?

I have tried:

```
var document = context.OpenAsync(res => res.Content(file).Address("")).Result;
var document = context.OpenAsync(res => res.Content(file).Address("/")).Result;
```

But it changed root relative links `/page.htm` into document relative links `page.html`.  Also even though I set `Search` to null I am still getting a "?" on end of the urls.  How do I kill the query string?

**Comment by FlorianRappl** [comment]
I guess you can use `SetAttribute`. Have you tried that?

Regarding the referenced issue the outcome is related, but not identical to this one. Actually, *reading* `Href` should be as described. Setting the value should actually just behave like `SetAttribute`. If it does not then I guess we need to change this issue to a bug.

Need to see what is going on and recap what the specification says.

**Comment by GuerrillaCoder** [comment]
`SetAttribute` seems to work fine (thanks for suggestion), it accepts the string value I provide without adding the host name.  I guess this is a bug then if you want property setters to behave in similar fashion.

**Comment by FlorianRappl** [comment]
Looking now at the issue I don't see any issue at all.

```cs
var source = @"<a href=""/home.htm"">Foo</a>";
var cfg = Configuration.Default;
var document = await BrowsingContext.New(cfg).OpenAsync(res => res.Content(source).Address("http://example.com"));
var a = document.QuerySelector<IHtmlAnchorElement>("a");

Assert.AreEqual("http://example.com/home.htm", a.Href);
Assert.AreEqual("/home.htm", a.GetAttribute("href"));

a.Href = "/foo.htm";

Assert.AreEqual("http://example.com/foo.htm", a.Href);
Assert.AreEqual("/foo.htm", a.GetAttribute("href"));
```

Works as expected. What you are doing, however, is that you modify the URL properties of an anchor tag. Once you modify them you'll write out the full URL (since you touch the full URL). This is per spec.

What you should do / want to do is to either compute a new URL string or only work against the URL string. It's up to you; AngleSharp provides you with a lot of utilities to make that as convenient as possible.

Hope that helps!
