### ISSUE TITLE
No default requester in default configuration

### ISSUE THREAD

**Issue by Suchiman** [AngleSharp/AngleSharp#66]
The default Configuration for AngleSharp doesn't have any requesters.
This seems to be workarounded for example in
[DocumentBuilder.Html(Uri)](https://github.com/FlorianRappl/AngleSharp/blob/4ae17865a9a5ec290193049d930e0b452022285c/AngleSharp/DocumentBuilder.cs#L260) but will lead Form.Submit to return null for no apparent reason because it wasn't handled the same way  [here](https://github.com/FlorianRappl/AngleSharp/blob/c6aae8476c861cc4338c630255c2511a73f524e1/AngleSharp/Dom/Html/HtmlFormElement.cs#L485).

To workaround this i'm using

``` csharp
Configuration.SetDefault(new Configuration().WithDefaultRequester());
```

but this seems weird since i would expect a DefaultRequester to be used by default wherever needed unless configured otherwise.

P.S.: Thank you for making this awesome library :grin:

**Comment by FlorianRappl** [comment]
When you give the `DocumentBuilder` an `Uri` instance you expect it to work, right. However, having a requester added by default would mean that resources would be downloaded - even though you probably do not need them.

As you found out - this also impacts the `Submit` method of the form. I agree that you can apply the same argument as with the `DocumentBuilder.Html(Uri)`; if you invoke the method you expect it to work. I will force using the default requester (if no other requester is present) here as well.

Thanks for noticing this inconsistency!

**Comment by Suchiman** [comment]
But this also means that i couldn't have a custom requester (e.g. with cookie handling when submitting a login form) without enabling automatic resource downloading.

Shouldn't this probably have it's own configuration entry, e.g. AutomaticResourceLoading = true or ExternalResourceLoadingMode.[None|Lazy|Full]

**Comment by FlorianRappl** [comment]
However, then we would need to define what exactly is a resource. I'll refer this to the issue #64, because resources usually use the `Fetch` method, whereas other ones (form submit, load page) refer to navigation tasks. If nothing to do a `Fetch` is provided, then no resources (or other dependent objects) will be loaded, however, loading a `Document` or submitting form data is still possible.
