### ISSUE TITLE
Smart Html to Text Conversion Documentation / Examples

### ISSUE THREAD

**Issue by sheldmandu** [AngleSharp/AngleSharp#661]
Hi @FlorianRappl  great project, but documentation lacks a bit so makes it a bit difficult to use.  Are you able to suggest (perhaps add to documentation) how to best use AngleSharp to create good quality Html to Text converter that is able to handle things such as br, p, ul>li, ol>li, a, img and other tags in a way similar to how it's done with HtmlAgilityPack.  Similarly stripping script and style tags and their content altogether.

I've come across a suggestion, but it seems a bit simplistic in what it can handle.  Also not really sure it is the best way.  See [Stackoverflow AngleSharp Extracting Formatted Text](https://stackoverflow.com/questions/43540559/anglesharp-extracting-formatted-text)

Here's some examples of how it's done with HAP.
https://stackoverflow.com/questions/286813/how-do-you-convert-html-to-plain-text/286819#286819

There's also a bit of code and nuances (with nested divs) that are explored in http://qaru.site/questions/188848/convert-render-html-to-text-with-correct-line-breaks

For example when handling li tags it's always necessary to take into consideration if they're nested inside an ol or li and probably best to check nesting to determine what indentation is required if any.

Would be good to have some ideas, examples, documenation, guidance as it seems convering html to text is quite a common thing people need to do.

**Comment by sheldmandu** [comment]
I'm happy to document this, but struggling to understand some aspects of how AngleSharp handles processing and how IMarkupFormatter should be implemented.  In particular, there doesn't seem to be a way to access the element in IMarkupFormatter.Text as it's not passed in as an argument, which makes it difficult to identify text in a script or style tag which should be ignored when doing Html to text conversion.  Is there perhaps a way to handle it in Processing or would the interface need to be modified for this to work?

**Comment by FlorianRappl** [comment]
There is no element coming into the `Text`. Elements are not text nodes. Only text nodes are. Thus if you have, e.g., `<span>foo</span>` you would first see an element `span` then a text `foo` coming at you.

**Comment by sheldmandu** [comment]
Right, that's what I thought.  What this means however is that it's more difficult to create a Html to Text converter in which for example you wanted to format the text differently based on the node/element within which the text appeared.  If instead of a string argument the IMarkupFormatter.Text took an IText (that also had a reference to Parent added to it) or something along those lines it would make it far easier.  Obviously it's possible to do some checking of TextContent against Html in the OpenTag and write out the actual Text from within there but it feels rather dirty and as a bit of a workaround.   I understand that's a breaking change and probably not something you can implement easily for that reason, but would be great if you could before going to version 1.0.0.  I guess using Html Agility Pack which treats everything including Text as a Node and has a NodeType is a alternative, although I was really hoping to avoid using it (as I do everything with AngleSharp where possible).

**Comment by FlorianRappl** [comment]
If you need that information then just store the last element created in a field. Quite straight forward.

There is really no need to give you all the information about the tree on each call - instead you only get the new information. That's btw what a tree walker is good for.

For details look into the visitor pattern; it's an old and established pattern.

**Comment by sheldmandu** [comment]
Hi @FlorianRappl, not sure why it's been tagged invalid when it is a legitimate question regarding documentation, which is certainly lacking in this area.  There are plenty of examples for something similar in HAP which gives a reasonable starting point (e.g. https://github.com/Clancey/HtmlAgilityPack/blob/master/Html2Txt/HtmlConvert.cs), but HAP is certainly not structured anywhere near as well as AngleSharp.

It's not uncommon for people to use a solution like AngleSharp / HAP to convert Html to Text and some direction from someone who truly knows AngleSharp would be very helpful.  In terms of using a Tree Walker are you suggesting using IDocument.CreateTreeWalker is a better option or should one be looking towards implementing a custom IMarkupFormatter?  As I said I'm happy to document what I do to create a Html to text converter using AngleSharp, but obviously I don't know anywhere near as much about AngleSharp as someone like yourself and hence asking for direction.

**Comment by sheldmandu** [comment]
Perhaps to give you an idea of what I'm trying to do is convert something like:

`
<h1>Overview</h1>
<p>Some overview of something</p>
<h1>Some Key Points</h1>
<ul>
<li>First Bullet</li>
<li>Second Bullet</li>
<li>Third Bullet</li>
</ul>
<h1>Some Numbered Points</h1>
<ol>
<li>First Point</li>
<li>Second Point</li>
<li>Third Point</li>
</ol>
`

to something like:
`
OVERVIEW
Some overview of something

SOME KEY POINTS
- First Bullet
- Second Bullet
- Third Bullet

SOME NUMBERED POINTS
1. First Point
2. Second Point
3. Third Point
`

**Comment by sheldmandu** [comment]
https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Html/PrettyMarkupFormatter.cs gives a reasonably good starting point.  I'll put up what I've done once I've done it.

**Comment by lieszkol** [comment]
Walking down the same path this seems to be the end of the road. Did you ever manage to implement something using AngleSharp or did you give up and go the HAP route instead? Any info would be appreciated.
