### ISSUE TITLE
Intend instead of Indent

### ISSUE THREAD

**Issue by sheldmandu** [AngleSharp/AngleSharp#662]
Hi, you seem to have Indent written as Intend (instead of Indent) throughout the codebase.  For example IntendBefore instead of IndentBefore.  As you're dealing with indentation it should be Indent.

**Comment by FlorianRappl** [comment]
This is OSS. Please make a PR if it bothers you.

**Comment by sheldmandu** [comment]
No probs will do. Doesn't bother me as such but just noticed it so thought may as well let u know
