### ISSUE TITLE
error with unmasked lt charachter 

### ISSUE THREAD

**Issue by MartinDemberger** [AngleSharp/AngleSharp#665]
I have a (illegal) html 
`<html><p>a<b</p></html>`

When I read this with AngleSharp it results in the following html:
`<html><head /><body><p>a<b< p="" /></p></body></html>`

**Comment by FlorianRappl** [comment]
This is per specification. Every browser does the same thing.

**Comment by MartinDemberger** [comment]
You are right, each browser I tried produced the same output with both htmls but the xhtml-code which is produced isn't valid xhtml because `b<` isn't a valid tag name.

It's ok that the produced output is rubbish because the input is also rubbish but I think the output should be valid (x)html. 

I use AngleSharp to convert html-input-files from my customers to xhtml and than process this with xslt any further. AngleSharp is very good at this point even if the input is invalid. In this case it produces invalid xml and so I can't use the output.
As a "work around" I implement a loop over all nodes and check if there names are valid node names.

If you think the behavior of AngleSharp is correct even if the output isn't valid, it's ok. In my opinion it would make AngleSharp better if it is changed to produce correct xhtml.

**Comment by FlorianRappl** [comment]
Hm, the output is not supposed to be valid XHTML. AngleSharp is an HTML parser and the serialization works 100% within the spec.

If you are not satisfied with the serialization you can roll out your own - its actually quite easy (there are format providers and you can re-use the existing ones). The loop is unnecessary in this case as the formatters are already called in a tree walker fashion.
