### ISSUE TITLE
Issue with QuerySelectorAll's selector case insensitive for attributes

### ISSUE THREAD

**Issue by hin-longkid** [AngleSharp/AngleSharp#666]
Hi, @FlorianRappl, i want to query all hidden elements which mark `style="display: none"` or `style="DISPALY:NONE"` in document.
So, i use the selector `*[style*='display: none' i]` and `*[style*='display:none' i]`, [CSS4 (CSS Selector Level 4) ](https://www.w3.org/TR/selectors-4/#attribute-case) support for it.
Here's my csharp code below
```cs
var hiddens = document.QuerySelectorAll("*[style*='display: none' i],*[style*='display:none' i]");
```
But, i receive **exception** message at runtime: The string did not match the expected pattern.

**Comment by FlorianRappl** [comment]
This is not in the scope of the CSS selectors. Hence the exception is right.

You can contribute by extending the CSS parser to know about the attribute case syntax.
