### ISSUE TITLE
How to save document as html file output 

### ISSUE THREAD

**Issue by dhsg521** [AngleSharp/AngleSharp#667]

**Comment by pkudrel** [comment]
You should check Source property in IDocument:
```csharp
var source = @"
<!DOCTYPE html>
<html lang=""en"">
<head>
<title>Document</title>
</head>
<body>
<h1>test</h1>
</body>
</html>
";
var parser = new HtmlParser();
var document = parser.Parse(source);
var src = document.Source.Text;
File.WriteAllText(path,src);
```

**Comment by FlorianRappl** [comment]
@pkudrel is right, `Source` is the original source with the scanned text representation.

However, if @dhsg521 wants to save the document with some manipulations (e.g., after running JS, or after doing some direct manipulations such as `appendChild`) then you may be interested in simply calling `ToHtml` on the document.

Be aware that the latter performs a serialization, which is not round-trip conserving as per W3C specification.

Hope that helps!

**Comment by dhsg521** [comment]
Thanks！I've written a method to implement it.

**Comment by dhsg521** [comment]
Thanks！I've written a method to implement it.
