### ISSUE TITLE
How can i get attribute from a INode ?

### ISSUE THREAD

**Issue by GF-Huang** [AngleSharp/AngleSharp#668]

**Comment by GF-Huang** [comment]
too many namesapce, hard to find methods what i want.

**Comment by FlorianRappl** [comment]
MDN is your friend for anything regarding the DOM API, e.g., https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute

Maybe first read about the DOM in general (what is a node, what is an element).

Regarding namespaces I do not see the use for many. But feel free to come up with better structures / proposals - always welcome!
