### ISSUE TITLE
BOM in Form Post

### ISSUE THREAD

**Issue by Suchiman** [AngleSharp/AngleSharp#67]
After diffing a browser made request vs. AngleSharps formposts and minimizing differencies why it's not working, i finally noticed that they had different Content-Length sizes, then i saw that there were 3 characters not being displayed which i identified as utf-8 BOM. I couldn't figure out what the specification says about BOM but the initial page was received with `Content-Type: text/html; charset=UTF-8` and no BOM so AngleSharp decided that the page is utf-8 which lead the form post to be utf-8 too. Looking into [TextEncoding](https://github.com/FlorianRappl/AngleSharp/blob/841fbd55f69065e89012d87f02939e8f6aeef7cb/AngleSharp/TextEncoding.cs#L26) it uses `Encoding.UTF8` which emits the BOM. Changing it to `new UTF8Encoding(false)` disabled the BOM and made the form post work.

**Comment by FlorianRappl** [comment]
Alright, that is actually a good point. I've changed the referenced `Encoding` instances to disable emitting the BOM. That should solve the issue.
