### ISSUE TITLE
Blocked process in intensive multithreading

### ISSUE THREAD

**Issue by BenoitSa** [AngleSharp/AngleSharp#670]
Hello,

I use AngleSharp to parse HTML texts in multithread.  The process slows down progressively, reaches 100% CPU and then stays in a blocked state. First, here is the code:

```
        public static void Main(string[] args)
        {
            string url = "http://www.bfmtv.com/politique/melenchon-regrette-que-macron-soit-le-porte-parole-de-la-droite-1437284.html";
            string html = new HtmlWeb().Load(url).DocumentNode.OuterHtml;
            Console.WriteLine("Size : " + html.Length);
            while(true)
            {
                //Processing
                Stopwatch sw = new Stopwatch();
                sw.Start();
                Parallel.For(0, 10000, i => new HtmlParser().Parse(html));
                sw.Stop();
                //Logging
                using (var writer = File.AppendText("c:\\parsing.txt"))
                {
                    string text = DateTime.Now.ToString()+";" + (int)sw.Elapsed.TotalSeconds;
                    writer.WriteLine(text);
                    Console.WriteLine(text);
                }            
            }
        }
```

I get 20 lines of log before the process is blocked. The time to parse 10000 pages grows from 70s to 130s progressively. It takes around 40 minutes to reach the critical (blocked) stage. The process does not exit the blocked stage unless I kill it manually.

I run on 16 cores, 32 GB RAM. Here is what happens in the CPU and RAM (it's rather progressive):
- first stage: the CPU is around 10%, RAM grows slowly to 15 GB. Then RAM is collected from time to time. 
- second stage: the CPU goes up and down from 0% to 50%. RAM grows slowly and is collected just the same
- third stage: the CPU goes up and down from 50% to 100%. RAM grows slowly and is collected just the same
- critical stage: the CPU is constant at 100%, RAM is constant around 3 GB, the process is almost blocked. Parsing 10000 pages takes more than an hour.

Before the critical stage I sometimes see the full GC freezing all threads, running and freeing memory normally.

Of course, no other process runs on the machine. Can you reproduce and/or figure out what is going on? I can give more info if needed. Intuitively, I think the problem has to do with garbage collection.

**Comment by BenoitSa** [comment]
I was using the wrong GC. I added this to the config file and it works well:

```
  <runtime>
    <gcServer enabled="true"/>
    <gcConcurrent enabled="false" />
  </runtime>
```

Default GC works very bad on multithreaded apps with many memory allocations.

You can close. (or delete). Sorry

**Comment by FlorianRappl** [comment]
No problem. By the way: Any reason you use the blocking version? I always recommend the `Async` one as all IO intense operations are used asynchronously.

**Comment by BenoitSa** [comment]
The main reason it that it is buggy : https://stackoverflow.com/questions/19671843/how-to-cause-net-4-to-throw-executionengineexception. Actually this bug happens in all our CPU intensive services crashing all of them after a while. As a rule we decided to always disable it. I don't know if Microsoft ever succeeded in fixing the bug.

Also it sounds like it is not recommended for background processing aimed at maximal throughput. Pauses (freeze) in the processing are no way a problem for our purpose. Actually, I've seen a better speed in multithread with gcConcurrent disabled.
