### ISSUE TITLE
LogIn into a "non form"/ javascript site

### ISSUE THREAD

**Issue by ErgoProxy1337** [AngleSharp/AngleSharp#671]
Hi people,
as the title says am I strugling with the login into the page. I was able to login into another page with a login form but this one has no form so I can not use the <IHtmlFormElement>
How could I do this?
The Site is: <LinkRemovedByMe>

I would rly apreciate it.

**Comment by ErgoProxy1337** [comment]
I saw this thread https://github.com/AngleSharp/AngleSharp/issues/242 and this what I tried to do:


```
        public BaseClass(xx, xxx)
        {
            HP_DownloadLink = SetDownloadLink();
            BuildRequest().Wait();
        }
private async Task BuildRequest()
        {        
            Config = Configuration.Default.WithDefaultLoader().WithJavaScript().WithCookies().WithLocaleBasedEncoding();
            Context = BrowsingContext.New(Config);
            Document = await Context.OpenAsync("myLink");
        }

private void TestLogin()
        {
            IHtmlInputElement emailbox = Context.Active.QuerySelector<IHtmlInputElement>("#inp_kema");
            IHtmlInputElement pwbox = Context.Active.QuerySelector<IHtmlInputElement>("#inp_kpw2");
            IHtmlButtonElement submitB = Context.Active.QuerySelector<IHtmlButtonElement>("#btn_anm2");

            emailbox.Value = "*****";
            pwbox.Value = "*****";
            emailbox.TextContent = "*****";
            pwbox.TextContent = "*****";

            submitB.DoClick();

            var docInnerContent = Task.Run(async () => { return await Context.OpenAsync("myLinkAfterLoginWithCookies"); }).Result;
        }

```
Hope someone can help me with this because its rly important.

**Comment by ErgoProxy1337** [comment]
Edit: ok.. By not being able to use javascript I always thought it was not working but it seams to log in at it should. My problem is, that the scripts are not loading or building why I dont get the content that I expect.
Any help on how I can wait until it execute all the scripts to get the needed content like selenium?

**Comment by FlorianRappl** [comment]
Selenium is only an engine that works with a driver against real browsers. AngleSharp is a browser engine, but it has - by no means - the full scope of a browser. That being written one thing that it particularly misses is extensive JS support. Yes, there is AngleSharp.Scripting.JavaScript, but this is still quite experimental and nowhere near production ready use. It can work for rather simple scripts but once a full lib / framework that highly depends on a full (JS) DOM implementation chances are going to down to zero it will work. I fear this is the major problem you are facing ...

However, there is a second thing and that is asynchronous script execution. There are some ways to wait for the final script to be loaded, but it is never a guarantee (e.g., what if a script is loaded but that one fired an HTTP request and only after this one has completed the "real" content is loaded in?) that you have the full page available. The only reliable way is polling or attaching to some DOM events to see when some things changed. But I would first experiment if the script is loaded / run successfully at all.

HTH!

**Comment by ErgoProxy1337** [comment]
Ty very much for your help.
Do you maybe have an advice on how to do it? :) 
I will start to learn a bit on how javascript works at the weekend but it would help to know on how to work with angelsharp and javascript or on how to execute it.
An advice would be appreciated.

**Comment by ErgoProxy1337** [comment]
Edit: Ok, I was able to analyze the requests with firefox dev tools and got the requestlink of the json file that I need.
Now I am happy :).
Ty for your help.
