### ISSUE TITLE
extra white space in Outer html in parsed object

### ISSUE THREAD

**Issue by koonik** [AngleSharp/AngleSharp#674]
Hi,

I have run into a case where i am doing the following:
`var rawHtml = "<html>" +
                          "<head >" +
                          "<style type = \"text/css\" >" +
                          "h1 {" +
                          "background-color: rgb(255, 0, 0);" +
                          "}" +
                          "</style>" +
                          "</head>" +
                          "<body>" +
                          "<h1>test</h1>" +
                          "</body>" +
                          "</html> ";
var html = new HtmlParser(config).Parse(rawHtml);`

and in the parsed html object I got:
 ```
((AngleSharp.Dom.Element)((AngleSharp.Dom.Document)html).Body).OuterHtml 
= <body><h1>test</h1> </body> 
(please note the blank space between h1 closing tag and body closing tag.
Could you please take a look and let me know if it was intended?

Thansk
Aga

**Comment by koonik** [comment]
oh, really sorry - i have actually found the cause of the issue and it is not connected to anglesharp.
Closing!

**Comment by FlorianRappl** [comment]
The whitespace came from the whitespace after closing the `html` tag. This is per spec.
