### ISSUE TITLE
Issues with the Build.ps1 build system

### ISSUE THREAD

**Issue by atlastodor** [AngleSharp/AngleSharp#678]
I would like to test and probably help develop AngleSharp. Our company needs to programmatically access the CSS model of HTML documents. Florian suggested to look at the devel branch and build AngleSharp and AngleSharp.Css.

This brings me to the issue: I can build from within Visual Studio (except some NuGet UAP target framework issues), but I cannot build using the Build.ps1 script. The build script, among other things, generates the NuGet packages, which will be very-very handy for me while testing.

I have two options:
1. Have somebody explain to me what the Build.ps1 / Cake scripts are supposed to do, document this (so other people do not have the same issues) and help me fix the build scripts. If this is working, integrate the changes into the public branch.
2. Hack and manually change the references within AngleSharp and AngleSharp.Css and build only for a single target framework and only from within Visual Studio. Generate NuGet packages by hand. Cross fingers that nothing breaks after the next branch sync. This I can do without external help.

I would like to hear input on what people have done and recommend to do.

**Comment by FlorianRappl** [comment]
The problem is that you potentially have the wrong (more recent) NuGet.exe - it's a big problem. They broke compatibility and cannot build / support the multi-platform target.

One way forward is, e.g., to go to a single target (.NET Standard, preferred is 2.0 as it will already offer us the broadest / most accepted one) and drop all the other targets. As a side-effect using AngleSharp would no longer be possible with SL and older versions of .NET.

**Comment by atlastodor** [comment]
Thanks. I probably have the newest NuGet. 

How do I do that? How do I go with a single target?

**Comment by FlorianRappl** [comment]
What I described is a brutal change to AngleSharp. For doing it now you would need to change the build.cake heavily.

**Comment by atlastodor** [comment]
Thanks. Re-writing the build.cake is currently out of my competence. I decided to locally reference the AngleSharp.Core project from within AngleSharp.Css and build from within Visual Studio. Obviously not a long term solution, but OK in the development phase.
