### ISSUE TITLE
Select won't recognize option nested in optgroup

### ISSUE THREAD

**Issue by Suchiman** [AngleSharp/AngleSharp#68]
Select currently pays zero attention to options nested inside optgroups.
Considering following testcode

``` csharp
var testcase = DocumentBuilder.Html(@"<!DOCTYPE html>
<html>
<head>
    <meta charset=""utf-8"" />
    <title></title>
</head>
<body>
    <select id=""test"" name=""entry"">
        <optgroup label=""Main menu"">
            <option value=""1"">Exit</option>
        </optgroup>
    </select>
</body>
</html>");
var select = testcase.GetElementById("test") as IHtmlSelectElement;
var option = select.QuerySelector("option") as IHtmlOptionElement;
```
- `select[0]` won't return `option`
- `option.IsSelected` won't affect `select` at all
- `select.Value = "1"` neither has any effect because select only pays attention to direct children
- ...

**Comment by FlorianRappl** [comment]
Yes, `optgroup` is not considered yet, however, it should be. I will integrate it and make your test case run.
