### ISSUE TITLE
Get each element and their childrens text and set back to original after processing

### ISSUE THREAD

**Issue by vickyRathee** [AngleSharp/AngleSharp#680]
I am looking to test Anglesharp for a static website translation purpose 

To start with, I was able to get the tags and assign id attribute to them. Then I parsed back the modified HTML and queried using the QuerySelectorAll to pull the elements by assigned ID attribute. Now the question is how can I set back all the tags text and their childrens text back to the tag id where it belongs to ?

**HTML**

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<h1>My page heading</h1>
<h2>This is example static page to get all the HTML tags and their <strong>childrens content </strong> and then <span>translate</span>
that into </br> another language.
</h2>
<p>Something in footer</p>
</body>
</html>
```

**Code**

```
void Main()
{
	var html = File.ReadAllText(@"C:\example.html");
	var parser = new HtmlParser();
	var document = parser.Parse(html);
	var elements = document.All.Where(o => o.LocalName != "html" && o.LocalName != "body" && o.LocalName != "head"); // Get the body tags.
	// Assign the ID to each tag
	if(elements != null)
	{
		int number = 1;
		foreach(var element in elements)
		{
			element.SetAttribute("data-id", number.ToString());
			number++;
		}
	}
	// IDs assigned correctly
	document.DocumentElement.OuterHtml.Dump();
	
	// Parset the modified HTML now
	var modifiedDocument = parser.Parse(document.DocumentElement.OuterHtml);
	// Get all tags using selector assigned
	var selectors = modifiedDocument.QuerySelectorAll("[data-id]");
	var List = new List<Translation>();
	foreach(var element in selectors)
	{
		// Add the TagId, Text to List
		List.Add(new Translation{Id = element.GetAttribute("data-id"), OriginalText = element.TextContent, OriginalLanguage = "en-us"});
	}	
	
	// Translation API here to translate the Text
	
	// Now how to set back the text to each tag back
	
	List.Dump();
}

public class Translation
{
	public string Id {get;set;}
	public string OriginalText {get;set;}
	public string OriginalLanguage {get;set;}
	public string TranslatedText {get;set;}
	public string TranslatedLanguage {get;set;}
}
```

**Comment by FlorianRappl** [comment]
I am not sure I can follow. The best way to walk the tree is to use a `TreeWalker` (e.g., by using `createTreeWalker` on the `document`) and visiting all text nodes.

Alternatively, get the elements and set the `TextContent`. Note, however, that a node like

```html
<a>foo<b>bar</b></a>
```

cannot be just set like this. Since setting the `TextContent` of `a` to `...` would yield

```html
<a>...</a>
```

i.e., removing the `b`. Hence what you described can be quite difficult.

A better algorithm (better than placing ids) is to just send in the original and then recursively walk the three looking at all childnodes and placing data from text nodes found on the new document to the text nodes on the old (original) document. This method assumes that the structure of the document was not changed.

HTH!

**Comment by vickyRathee** [comment]
@FlorianRappl  I used the `TreeWalker` as well, but the problem is same for child tags. When setting text in loop, it removes the children's HTML tag

```
var parser = new HtmlParser();
var document = parser.Parse(html);
var rootnode = document.QuerySelector("body");
 
var walker = document.CreateTreeWalker(rootnode, FilterSettings.Element);
while (walker.ToNext() != null)
       walker.Current.TextContent = "-This Will be translated-";
			  
document.DocumentElement.OuterHtml.Dump();
```

Results in : 

```
<html><head>
</head>
<body>
<h1>-This Will be translated-</h1>
<h2>-This Will be translated-</h2>
<p>-This Will be translated-</p>

</body></html>
```

Which removed the `strong`, `span` and `br` tag from the `H2` . Any example about the new algorithm you said to place in new document?

**Comment by FlorianRappl** [comment]
Why it does not work I wrote you beforehand (see my answer). That this one only works when the structure is preserved I also remarked, so make sure you have the same structure first.

```cs
void MoveContent(IElement oldElement, IElement newElement)
{
  var count = oldElement.ChildNodes.Length;

  for (var i = 0; i < count; i++)
  {
    if (oldElement.ChildNodes[i] is IElement)
    {
      MoveContent(oldElement.ChildNodes[i], newElement.ChildNodes[i]);
    }
    else if (oldElement.ChildNodes[i] is IText)
    {
      oldElement.ChildNodes[i].Data = newElement.ChildNodes[i].Data;
    }
  }
}
```

Use like `MoveContent(oldDocument.Body, newDocument.Body)`.

Hope this helps!
