### ISSUE TITLE
Can't seem to submit my form

### ISSUE THREAD

**Issue by LeeAntW** [AngleSharp/AngleSharp#684]
Hello there

I am currently trying to submit a form using a username and password there is a button but it is of type="image"
DO i use Submit or Button.DoClick?

Current Code:-
        public static async void submitForm()
        {
            var configuration = Configuration.Default.WithDefaultLoader().WithCookies();
            var browsingContext = BrowsingContext.New(configuration);
            await browsingContext.OpenAsync(WebsiteUrlWelsh);
            await browsingContext.Active.QuerySelector<IHtmlFormElement>("form").Submit(new
            {
                User = "###",
                Password = "##"
            });

            await browsingContext.Active.QuerySelector<IHtmlAnchorElement>("#LeftPannel1_LnkMyDownloads").Navigate();

            Console.Write(browsingContext.Active.Title);
            Console.Read();
        }

**Comment by FlorianRappl** [comment]
Generally, use `Submit`. If "clicking the image" is somehow required by the server, you can always provide an element to the `Submit` method to specify a caller. The only difference with the "clicked element" in case of an `input type=image` is that this element transports special form properties for the clicked position.

Hope this helps!

**Comment by LeeAntW** [comment]
I am currently studying your FormSubmission project and following your pattern. Is there any error capturing i can use to find out what hidden variables are missing? I think i may need to add VIEWSTATE, __VIEWSTATEGENERATOR and __EVENTVALIDATION as variables, as i when i click F12 and submit the login manually those variables are part of the header request!

**Comment by LeeAntW** [comment]
I was hoping to contact you via your email address on your blog but the email link doesn't work

**Comment by LeeAntW** [comment]
The form data that gets posted across F12 looks:-
__VIEWSTATE: /wEPDwUKLTYxMDI0NzEzNg9kFgICAQ9kFgYCBQ9kFg4CCQ8PFgQeBFRleHQFDENyZWF0ZSBvcmRlch4HVmlzaWJsZWhkZAILDw8WBB8ABRBNeSBvcmRlciBoaXN0b3J5HwFoZGQCDQ8PFgQfAAUMTXkgZG93bmxvYWRzHwFoZGQCDw8PFgQfAAUKTXkgZGV0YWlscx8BaGRkAhEPDxYEHwAFEUFkbWluIC0gVXNlciBMaXN0HwFoZGQCEw8PFgQfAAUPQWRtaW4gLSBSZXBvcnRzHwFoZGQCFQ8PFgQfAAUGTG9nb3V0HwFoZGQCCQ8PFgQfAAUIUmVxdWlyZWQfAWhkZAINDw8WBB8ABQhSZXF1aXJlZB8BaGRkGAEFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYCBQtpbWdidG5Mb2dpbgUMaW1nYnRuQXBwbGljHtYvkD//5U5otRzL7OxpZuFWiIE=
__VIEWSTATEGENERATOR: AE612EBE
__EVENTVALIDATION: /wEWBQLz0criCQKl1bKzCQK1qbSRCwLHg6JXAq6gotoBYqAHDeRgar51pSEvr+9tRjZVDTg=
txtUserName: STLGroup
txtPassword: Stirling1
imgbtnLogin.x: 73
imgbtnLogin.y: 5


I have no idea how to set :-
imgbtnLogin.x: 73
imgbtnLogin.y: 5

**Comment by LeeAntW** [comment]
tried this but not working:-
public static async void submitForm()
        {
            var configuration = Configuration.Default.WithDefaultLoader().WithCookies();
            var browsingContext = BrowsingContext.New(configuration);
            await browsingContext.OpenAsync(WebsiteUrlWelsh);

            var viewstate = browsingContext.Active.QuerySelector<IHtmlInputElement>("#__VIEWSTATE").Value;
            var viewStateGenerator = browsingContext.Active.QuerySelector<IHtmlInputElement>("#__VIEWSTATEGENERATOR").Value;
            var eventValidation = browsingContext.Active.QuerySelector<IHtmlInputElement>("#__EVENTVALIDATION").Value;

            var button = browsingContext.Active.QuerySelector<IHtmlInputElement>("#imgbtnLogin");

            browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("__VIEWSTATE", viewstate);
            browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("__VIEWSTATEGENERATOR", viewStateGenerator);
            browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("__EVENTVALIDATION", eventValidation);

            browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("User", "####");
            browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("Password", "###");

            await browsingContext.Active.QuerySelector<IHtmlFormElement>("form").Submit(button);

            //await browsingContext.Active.QuerySelector<IHtmlFormElement>("form").Submit(new
            //{
            //    __VIEWSTATE = viewstate,
            //    __VIEWSTATEGENERATOR = viewStateGenerator,
            //    __EVENTVALIDATION = eventValidation,
            //    User = "STLGroup",
            //    Password = "Stirling1"
            //});

            Console.Write(browsingContext.Active.Title);
            //await browsingContext.Active.QuerySelector<IHtmlAnchorElement>("#LeftPannel1_LnkMyDownloads").Navigate();
            Console.Read();
        }

**Comment by LeeAntW** [comment]
I added:-
browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("imgbtnLogin.x", "49");
            browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("imgbtnLogin.y", "imgbtnLogin.y");
 Still nothing

**Comment by LeeAntW** [comment]
Wooops fixed :- browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("imgbtnLogin.y", "18");

Still not working

**Comment by LeeAntW** [comment]
another correction:-
            browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("txtUserName", "###");
            browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SetAttribute("txtPassword", "###");
 But still not working

After this maybe you could delete thispost so to delete sensitive information :)

**Comment by LeeAntW** [comment]
After submit the page should end up#

**Comment by LeeAntW** [comment]
I removed the NUGET package and downloaded the SRC and it worked immediately :) 
I guess your NUGET package is not up to date

**Comment by LeeAntW** [comment]
Your source works great but the latest nuget package doesnot work. 
One notable difference is when i use the source code i have to use **SubmitAsync** whereas the NUGET package only gives me **Submit**()

Any help please

public static async void submitForm()
        {
            var configuration = Configuration.Default.WithDefaultLoader().WithCookies();
            var browsingContext = BrowsingContext.New(configuration);

            await browsingContext.OpenAsync(WebsiteUrlWelsh);

            var document = browsingContext.Active;

            var form = document.QuerySelector<IHtmlFormElement>("form");
            form.QuerySelector<IHtmlInputElement>("input[type=text][name=txtUserName]").Value = "###";
            form.QuerySelector<IHtmlInputElement>("input[type=password][name=txtPassword]").Value = "###";
            await form.SubmitAsync(document.QuerySelector<IHtmlInputElement>("#imgbtnLogin"));

            Console.Write(browsingContext.Active.Title);

            var result = await browsingContext.Active.QuerySelector<IHtmlAnchorElement>("#LeftPannel1_LnkMyDownloads").NavigateAsync();

            Console.Write(result.DocumentUri);

            var tableElement = result.QuerySelector("table[id=\"grdSrqList\"]");
            var tableRows = tableElement.QuerySelectorAll(">tr");

            var list = new List<LinkData>();

            AngleSharp.Dom.IHtmlCollection<AngleSharp.Dom.IElement> cell = null;
            foreach (IHtmlTableRowElement row in tableRows)
            {
                cell = row.QuerySelectorAll(">td");
                list.Add(new LinkData(cell[3].TextContent, cell[4].TextContent));
            }

            Console.Read();
        }

**Comment by FlorianRappl** [comment]
I am not sure - what version of the NuGet package do you use?

`SubmitAsync` is there for a while now ...

**Comment by LeeAntW** [comment]
Hi Floiran. Sorry i didn#t get to you. I got it working. I have to install the Anglesharp.Javacscript nuget package as well.
Now i am trying to mock these objects for UNIT TEST, tricky:-
var form = new Mock<IHtmlFormElement>();
            form.Setup(f => f.QuerySelector<IHtmlInputElement>("input[type=text][name=txtUserName]"));
            form.Setup(f => f.QuerySelector<IHtmlInputElement>("input[type=password][name=txtPassword]"));
