### ISSUE TITLE
No definition of .WithJavaScript() 

### ISSUE THREAD

**Issue by totoroyyb** [AngleSharp/AngleSharp#685]
Hi, I tried to use `var config = Configuration.Default.WithJavaScript().WithCss();`
But vs told me that there is no definition of `.WithJavaScript`

Just like the pic below:
![img](https://user-images.githubusercontent.com/30278896/42303827-a7cb429e-8055-11e8-8b4c-07c545a2541f.png)

**Comment by FlorianRappl** [comment]
You need the right NuGet package for that. It does not come with the Core lib.

See `AngleSharp.Scripting.JavaScript`.
