### ISSUE TITLE
RowSpan default must one, not zero.

### ISSUE THREAD

**Issue by DonaldRich** [AngleSharp/AngleSharp#688]
The default value for RowSpan on a Table Data (TD) element the default value should be 1, not 0. A value of zero means that the contents of the TD cell extend to the end of the table section. As currently implemented it is not possible to distinguish between a value of 0 provided to extend the TD cell to the end of the table section and a default value provided for a TD element without a RowSpan attribute.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td

rowspan
This attribute contains a non-negative integer value that indicates for how many rows the cell extends. Its default value is 1; if its value is set to 0, it extends until the end of the table section (<thead>, <tbody>, <tfoot>, even if implicitly defined, that the cell belongs to. Values higher than 65534 are clipped down to 65534.

**Comment by FlorianRappl** [comment]
Yep great catch. Any contribution welcome!
