### ISSUE TITLE
ColSpan default should be 1.

### ISSUE THREAD

**Issue by DonaldRich** [AngleSharp/AngleSharp#689]
The default value for ColumnSpan on a Table Data (TD) element the default value should be 1, not 0. The meaning of a colspan with a value of zero is not well defined (same as 1? hidden?).

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td

colspan
This attribute contains a non-negative integer value that indicates for how many columns the cell extends. Its default value is 1. Values higher than 1000 will be considered as incorrect and will be set to the default value (1).

**Comment by FlorianRappl** [comment]
Yep great catch. Any contribution welcome!
