### ISSUE TITLE
Case of NodeName

### ISSUE THREAD

**Issue by thorn0** [AngleSharp/AngleSharp#69]
In my browser, both `tagName` and `nodeName` return same upper-case values for elements. In AngleSharp, `NodeName` returns lower case. Why does AngleSharp's behavior differ from the browser's one?

**Comment by FlorianRappl** [comment]
The browser's behavior is a legacy behavior. AngleSharp tries to move forward, at least for `NodeName` (which should reflect the original tag, which is only parsed in lower case letters in HTML5). Usually `tagName` is used in APIs, resulting in the same behavior (upper case). In case of `nodeName` we have to see if this is a good choice; but it makes things easier internally (of course I could distinguish between an internal and an external call, however, I assumed that people want to compare with lower case variants.

**Comment by thorn0** [comment]
Sounds logical. Consider copying this explanation to the documentation.

**Comment by FlorianRappl** [comment]
Good point. Yes, will be done in the Wiki and also the XML documentation.
