### ISSUE TITLE
NullReferenceException when removing elements

### ISSUE THREAD

**Issue by fgortiz** [AngleSharp/AngleSharp#690]
I'm getting a NullReferenceException after I remove a series of elements. Code:
```
var parser = new HtmlParser();
var doc = parser.Parse(source);
var linq = doc.All.Where(node => node.TextContent.Contains("{{DisplayName}}")).ToList();
linq.ForEach(x =>
{
    x.Remove();
});
var outer = doc.DocumentElement.OuterHtml;
Console.WriteLine(outer);
Console.ReadKey();
```

I don't know what causes it, since it only happens after removal, and the docs don't talk about removing elements.

**Comment by FlorianRappl** [comment]
Well, it is something along the lines "the iterator is created on a fixed set of elements, but these elements are removed while performing the iteration". It may be similar to "do not alter the iterator while performing the iteration".

I will look into this. From my perspective *it should just work* and if it does not - it needs to improved.

Maybe I can still squeeze it into the upcoming v0.9.10 release.

**Comment by fgortiz** [comment]
I see, thanks. In the meantime, what would be the correct approach to removing elements using AngleSharp? I can't find any samples of it, and the docs don't document an approach that works.

**Comment by fgortiz** [comment]
Update: The iterator, as it happens, seems to be completely broken. Doing 

`var node = doc.All.Where(n => n.TextContent.Contains("{{DisplayName}}")).ToList().First();`

will also make doc.DocumentElement null. I can't find absolutely any way to delete an element.

**Comment by FlorianRappl** [comment]
I am not sure I see your problem:

```cs
var context = BrowsingContext.New();
var document = context.OpenAsync(res => res.Content("<div></div><div>{{DisplayName}}</div>")).Result;
var node = document.All.Where(n => n.TextContent.Contains("{{DisplayName}}")).ToList().First();
node.Dump();
document.DocumentElement.Dump();
(node == document.DocumentElement).Dump();
```

Will dump the document element, the document element, and true. If you remove the document element from the document you will have a broken / decoupled DOM.

The `TextContent` recursively descends the tree to get all text nodes. Hence using `Contains` will most likely not do what you want. Instead use a `TreeWalker` for finding text nodes that contain what you want. Then you can use their parents (elements) and remove them (if that's what you want).

Hope that helps!

**Comment by fgortiz** [comment]
`.Dump()`? That method doesn't exist on `IElement`.

Also, I can't use async methods. Sorry.

I'd try the `TreeWalker` approach but I can't find any documentation on it, and using `Contains` did the job quite well. I just want to be able to use `IElement.Remove()`

**Comment by FlorianRappl** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker

`Dump` is an extension method of LinqPad (https://www.linqpad.net). Was only used for illustration purposes.

The async methods do not matter - what matter is the constructed DOM. Did you read my comment? You are definitely removing the wrong elements...

I will close this for now. The whole iteration works fine for me.

Otherwise, show me a MWE to illustrate what exactly fails.

**Comment by fgortiz** [comment]
Hm. Could you try running this? The objective is to remove the `<span>` elements.

```
    public class Program
    {
        static void Main(string[] args)
        {
            var source = @"
            <div>
                <div>
                    <span>
                        <strong>{{DisplayName}}</strong>
                    </span>
                </div>
            </div>
            ";
            var parser = new HtmlParser();
            var doc = parser.Parse(source);
            var nodes = doc.All.Where(node => node.TextContent.Contains("{{DisplayName}}")).ToList();
            nodes.ForEach(node => node.Remove());
            var outer = doc.DocumentElement.OuterHtml;
            Console.WriteLine(outer);
            Console.ReadKey();
        }
    }

```
After the `node.Remove()`, `doc.DocumentElement` is null. 

The reason I'm using TextContent.Contains is because this is supposed to accept arbitrary HTML (sanitized elsewhere), where the _only_ constant is {{DisplayName}} and such fields; hence looking it up by text.

**Comment by FlorianRappl** [comment]
I do not need to run this. What you will remove is the `DocumentElement`. If you want to remove the span elements, why don't you make `doc.QuerySelectorAll("span").Where(...)`?

With the code above you will *always* remove the `DocumentElement` when there is *any* text matching what you have...

In the previous example the following elements would *all* be matched *and* removed. `html`, `body`, `div`, `div`, `span`, `strong` (i.e., all except the inserted `head` element).

**Comment by fgortiz** [comment]
Ah, nevermind, then. Thanks!
