### ISSUE TITLE
Download a document using AnglesSharp Requester

### ISSUE THREAD

**Issue by LeeAntW** [AngleSharp/AngleSharp#691]
I am using my own download Webrequest using the PostData from the final AngleSharp document page and cookies from the final Anglesharp document page but is not downloading the page as the server thinks i am not logged on:-
public byte[] DownloadResults(string postData, IDocument document)
        {
            Uri uri = new Uri(ConfigurationManager.AppSettings["WelshDownloadsUrl"]);
            Cookie cookie = new Cookie("STLGroup", document.Cookie);

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(ConfigurationManager.AppSettings["WelshDownloadsUrl"]);
            request.Method = "POST";
            request.ContentType = "application/x-www-form-urlencoded";
            request.UserAgent = "HttpWebRequest";
            request.CookieContainer = new CookieContainer();
            request.CookieContainer.Add(uri, cookie);

            byte[] bPostData = Encoding.ASCII.GetBytes(postData);
            request.ContentLength = bPostData.Length;

            Stream os = request.GetRequestStream();
            os.Write(bPostData, 0, bPostData.Length);
            os.Close();

            WebResponse response = request.GetResponse();

            Stream stream = response.GetResponseStream();

            byte[] bytesInStream = ReadAllBytes(stream);

            return bytesInStream;
        }

Is there a way of doing this using anglesharp requester?

**Comment by LeeAntW** [comment]
Ultimately the link we are using to download looks like 👎 
<a href="javascript:__doPostBack('**grdSrqList$_ctl2$_ctl0**','')">Download</a>

The bolded segment becomes my EVENTTARGET in the postdata

**Comment by LeeAntW** [comment]
a href="javascript:__doPostBack('grdSrqList$_ctl2$_ctl0','')">Download

**Comment by FlorianRappl** [comment]
I guess there is, but as this is not part of the issue tracking I would rather like to see this question on SO.

The AngleSharp requester is only a standard .NET requester - the only difference is that some properties are set implicitly and that it is API compatible to be used within a loader.

Please refer in the future to SO to help others find your questions (if applicable for a larger audience) easier. Thanks!
