### ISSUE TITLE
[Question] Implementing IHttpRequester

### ISSUE THREAD

**Issue by stcn89** [AngleSharp/AngleSharp#692]
Can you give a basic GET or POST example on how to implement IHttpRequester ?
Thanks in advance.

**Comment by FlorianRappl** [comment]
Of course, just looking at the source of the default requester may be enlightning:

https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Network/Default/HttpRequester.cs

Alternatively, look at the implementation in AngleSharp.Io:

https://github.com/AngleSharp/AngleSharp.Io/blob/master/src/AngleSharp.Io/Network/HttpClientRequester.cs

Finally, there are some other implementations available in AngleSharp.Io. I think overall it should be quite straight forward (all you need are two methods, one to reflect what protocols can be handled, e.g., http and https, and another method to actually handle the request).

Hope that helps!
