### ISSUE TITLE
Parse HTML after javascript execution

### ISSUE THREAD

**Issue by nazarkryp** [AngleSharp/AngleSharp#693]
Sorry it it is not proper place for question. Could not find the answer any where else.
Is it possible to trigger javascript and then parse HTML?
As in my case DOM is updated few milliseconds after page loaded

**Comment by FlorianRappl** [comment]
There is `AngleSharp.Scripting.JavaScript` but it is experimental and does not work with really complex libraries.

Hope this helps!
