### ISSUE TITLE
Inheritor of DocumentLoader doesn't work as expected

### ISSUE THREAD

**Issue by a-a-k** [AngleSharp/AngleSharp#696]
Derived class:   
```
    public class MyLoader : DocumentLoader
    {
        public MyLoader(IBrowsingContext context, Predicate<IRequest> filter = null)
            : base(context, filter)
        {
           // do nothing
        }
    }
```
Building `BrowsingContext`:    
```
var context = BrowsingContext
                .New(new Configuration()
                .With<IDocumentLoader>(c => new MyLoader(c))
                .WithCookies());
```
Calling:  
`var hello = await context.OpenAsync(url);`  

It returns an empty html document but works fine if `BrowsingContext` builded with `.WithDefaultLoader()` instead of `.With<IDocumentLoader>(c => new MyLoader(c))`.   

What am I doing wrong?

**Comment by FlorianRappl** [comment]
Good question - looks fine from my POV. I will look inside!

**Comment by FlorianRappl** [comment]
Problem is that you are only included a loader, not a requester. Without a requester the loader is useless (both need to work together in loading a document).
