### ISSUE TITLE
Unused variable (IServiceFactory)?

### ISSUE THREAD

**Issue by a-a-k** [AngleSharp/AngleSharp#699]
https://github.com/AngleSharp/AngleSharp/blob/9da30e34c2c5cffd814d22f0e122db6bda968dd5/src/AngleSharp/ConfigurationExtensions.cs#L154  

It seems like useless.

**Comment by FlorianRappl** [comment]
Is not there in `devel` (i.e., even though it may be useless right now in `master` it won't appear in future versions anyway).

Thanks for spotting it!
