### ISSUE TITLE
HTML Element constructor access modifiers

### ISSUE THREAD

**Issue by Rajbandi** [AngleSharp/AngleSharp#7]
Currently, it is not possible to instantiate a HTML Element for example HTMLInputElement as its constructor declared with internal modifier. Sometimes we may need to create and add dynamic elements to DOM. Please change all the HTML elements  constructors so that they can be added dynamically. HtmlDocumet.AppendChild is of no use in this case.

**Comment by FlorianRappl** [comment]
This is to fulfill DOM specification. The only way to create an HTML element is by using the factory method provided in the HTMLDocument.
I know this is a hard statement but just to clarify: AngleSharp tries to follow the DOM, so using AngleSharp is like using the DOM. I could alter it, but it will have no benefit for people who want to start web dev (the DOM in the browser will also not be altered!) and it would create confusion for people already familiar with web development.

Hence please use the CreateElement method (DOM: createElement) in a Document (or derived like HTMLDocument) instance.

Hope this helps you!

PS: AppendChild is of great use as in the browser DOM! The internal keyword has been set on purpose.

**Comment by Rajbandi** [comment]
Ya true, I didn't realize that. AppendChild will be of great help if createElement is provided. Lack of documentation confused me.

**Comment by FlorianRappl** [comment]
Should be mentioned in the documention now.
