### ISSUE TITLE
A serialization scenario where IMarkupFormatter isn't too convenient

### ISSUE THREAD

**Issue by thorn0** [AngleSharp/AngleSharp#70]
I'm creating an implementation of `IMarkupFormatter` to serialize DOM to plain text. In particular, I need to convert `<a href="http://example.com">foo</a>` to `foo (http://example.com)`. It's possible to do this now by converting the attributes to a string of a special format in the `Attribute` method, pushing this string to a stack in `OpenTag` and popping it back in `CloseTag`. But this looks somewhat too complicated. Maybe it's not too late to change `IMarkupFormatter` for it to support such scenarios in a better way.

**Comment by FlorianRappl** [comment]
Hm, yes its certainly not too late. One possibility would be to just hand over an `IElement` (and replace `Attribute`, `OpenTag` and `CloseTag` by `Element`). But I did not go for that one, because the internal flags cannot be accessed then.
Do you have a specific proposal? How would the ideal `IMarkupFormatter` look like, which makes your case easier?

**Comment by thorn0** [comment]
I think just adding the `IElement` parameter to the existing `OpenTag` and `CloseTag` methods and leaving everything else as is will do. Although it might look inelegant, it wouldn't affect the performance of the out-of-the-box standard-based formatter, and at the same time would provide support for various scenarios like mine (with a little overhead of iterating over the attributes when they're not needed, which can be made lazy, BTW).

**Comment by FlorianRappl** [comment]
Or we just add `IElement` to the arguments for `OpenTag` / `CloseTag` and remove the `Attribute` method (incl. the `attributes` argument)? Then this is lazy for sure (because, e.g., `OpenTag` has to compute those) and we justified using `IElement`.

**Comment by thorn0** [comment]
Yes, a good option.

**Comment by FlorianRappl** [comment]
Can you please check if the provided code satisfies your needs?

**Comment by thorn0** [comment]
Yes, thanks, it does.
