### ISSUE TITLE
ArgumentNullException in MemoryCookieProvider.GetCookie

### ISSUE THREAD

**Issue by meziantou** [AngleSharp/AngleSharp#702]
`MemoryCookieProvider.GetCookie` may throw an `ArgumentNullException` when `origin` is null.

I don't know exactly which url during the navigation failed, but i think it's the `data:image/gif;base64,...`. In this case origin is null and the `MemoryCookieProvider.GetCookie` throw an exception because of `new Uri(origin)`.

I think it should return null in this case.

**Comment by FlorianRappl** [comment]
Good call. Yes, in such cases (no origin provided) no cookie should be retrieved (or updated).

**Comment by AsValeO** [comment]
Same issue. Example base URL: "https://msk.realty.mail.ru/offer/sale-liv-3074153110901441.html"
`x.IsResourceLoadingEnabled = true;` with `.WithCookies()` enabled gives `ArgumentNullException` from `MemoryCookieProvider.GetCookie`
