### ISSUE TITLE
Form Submit - submit button doesn't get included in Form data

### ISSUE THREAD

**Issue by holotrek** [AngleSharp/AngleSharp#703]
I have an issue when attempting to submit a form where the value for the submit button itself isn't sent. This is an issue because it is a website that I don't control and is requiring that form data. Here is the important bits of the HTML of the form being submitted, along with the code I'm using:

**HTML**
```html
<form action="/login" method="post" id="login">
 <fieldset>
    <dl>
      <dt><label for="username">Username:</label></dt>
      <dd><input type="text" name="username" id="username" /></dd>
    </dl>
    <dl>
      <dt><label for="password">Password:</label></dt>
      <dd><input type="password" id="password" name="password" /></dd>
    </dl>
    <dl>
      <dt>&nbsp;</dt>
      <dd><input type="submit" name="login" value="Login"></dd>
    </dl>
  </fieldset>
</form>
```

**C#**
```c#
var formData = new Dictionary<string, string>
{
  { "username", "Admin" },
  { "password", "password" }
};
var form = this.Document.QuerySelector<IHtmlFormElement>('#login');
var submitted = await form.SubmitAsync(formData);
```

I've narrowed the issue down to this line returning false. It looks like it is expecting the submit element to equal the form that the submit is inside, which doesn't make sense to me:
https://github.com/AngleSharp/AngleSharp/blob/9da30e34c2c5cffd814d22f0e122db6bda968dd5/src/AngleSharp/Html/InputTypes/SubmitInputType.cs#L21

I'm not sure what the intent of `Boolean IsAppendingData(IHtmlElement submitter)` is, but I pulled down your source and put it into my solution and modified the line to compare form-to-form rather than form-to-input, as so, which fixed the issue:
```c#
return Object.ReferenceEquals(submitter, Input.Form);
```

**Comment by FlorianRappl** [comment]
Hm, afaik the line you quote is from the spec. I guess it makes a difference if the form submit was triggered directly from the form (e.g., via JS using the submit) or via a user action, e.g., by pressing a button.

However, to be honest I forgot how (and why) this appending data function was brought in (for the type = submit input field). At least I could not find it via a quick Google search. As a consequence I see two options: Either I made a mistake here and it should indeed be `Input.Form` or it is all correct and the page expects a different kind of behavior here (e.g., via a real user to actually press that button).

How is the behavior in a real browser if you also submit the form via code instead of user input (i.e., also make `form.submit` instead of pressing something). How does the page behave and what do you see posted in the network (as compared to what AngleSharp submits)?

Thanks for the good insights!

HTH!

**Comment by holotrek** [comment]
Interesting. If I use JS to submit the form, it indeed behaves the same as AngleSharp and omits the 'login' post data. bit using JS to click the submit button works. Seems like bad website design. 

However, I modified my code to click the button instead, and it is recognizing it as a submit button, so it ends up going into the same form submit code and omitting the data due to hitting that same line of code.

```c#
var form = this.Document.QuerySelector<IHtmlFormElement>("#login");
form.QuerySelector<IHtmlInputElement>("#username").Value = "Admin";
form.QuerySelector<IHtmlInputElement>("#password").Value = "password";
form.QuerySelector<IHtmlInputElement>("input[type='submit']").DoClick();
```

I got it working, but I had to modify my `SubmitForm` method to a workaround that uses the loader directly to do a plain POST:

```c#
        public virtual async Task<bool> SubmitForm(string formSelector, IDictionary<string, string> formData)
        {
            var form = this.Document.QuerySelector<IHtmlFormElement>(formSelector);
            var bodyStream = new MemoryStream();
            var writer = new StreamWriter(bodyStream);
            var body = new StringBuilder();
            foreach (var item in formData)
            {
                body.Append($"{item.Key}={WebUtility.UrlEncode(item.Value)}&");
            }
            await writer.WriteAsync(body.ToString());
            await writer.FlushAsync();
            bodyStream.Position = 0;
            var request = new DocumentRequest(new Url(this.Document.BaseUrl, form.Action))
            {
                Body = bodyStream,
                Method = HttpMethod.Post,
                Referer = this.Document.BaseUri
            };
            request.Headers.Add("Content-Type", "application/x-www-form-urlencoded");
            var dl = this._browsingContext.Loader.DownloadAsync(request);
            var response = await dl.Task;
            return response.StatusCode == HttpStatusCode.OK;
        }
```

**Comment by FlorianRappl** [comment]
I think this all seems to be now domain specific and less relevant for AngleSharp (or do you think different?).

Anything else on the AngleSharp side to be tackled?

**Comment by holotrek** [comment]
I guess I'm still confused as to the purpose of the line referenced, as this still breaks when calling "DoClick()" on the submit button. In the Chrome console when clicking the submit button using JS, it does submit the "login" form data as expected.

```
return Object.ReferenceEquals(submitter, Input); 
```
"submitter" always seems to be the form in the above code and the Input is always the submit button based on the fact that it is within the class "SubmitInputType", so I'm not sure I understand when that would ever return true.

**Comment by LeastOne** [comment]
I've encountered this same problem. Having read the aforementioned distinction regarding the difference between a JavaScript `form.submit()` and a JavaScript `button.click()` I think one important detail is being overlooked which is that when JavaScript is disabled the browser does send the submit button name and value. Though AngleSharp doesn't support JavaScript, it seems to me that API members such as `IHtmlInputElement.DoClick()` strongly suggest its mimicking non-JavaScript browser behavior. Regardless of what spec may be implemented, I think this practical reality provides good reason to modify AngleSharp's behavior accordingly. Not that my anectodical situation should dictate the whole, but for me this prevented me from adopting AngleSharp in my most recent project. Do you think this could be revisted?

**Comment by chrolivier** [comment]
I have also encountered this. The workaround I used was to rename the submit button and add an input text field with the button's original name and value, before calling the SubmitAsync method.

```cs
var submitButton = form.QuerySelector<IHtmlButtonElement>(@"button[type=""submit""]");
if (submitButton != null)
{
    var buttonName = submitButton.Name;
    var buttonValue = submitButton.Value;
    if (!string.IsNullOrWhiteSpace(buttonName) && !string.IsNullOrWhiteSpace(buttonValue))
    {
        submitButton.Name = $"{buttonName}_old";

        var input = _document.CreateElement<IHtmlInputElement>();
        input.Name = buttonName;
        input.Type = "text";
        input.Value = buttonValue;
        form.AppendChild(input);
    }
}
.
.
.
await form.SubmitAsync(fields);
```

**Comment by BrunoJuchli** [comment]
I've run into this problem as well, but it looks like the workarounds are not necessary anymore since this is now possible out of the box:

    IHtmlFormElement form;
    var submitButton = form
        .Elements
        .OfType<IHtmlButtonElement>()
        .Single(b => b.Name.Is(buttonName));

     await form.SubmitAsync(submitButton);

Which results in the button name + value being part of the submitted data.
