### ISSUE TITLE
How button click and get value other element?

### ISSUE THREAD

**Issue by yurasakun** [AngleSharp/AngleSharp#704]
here is my code
var configuration = Configuration.Default.WithDefaultLoader()
                .WithRequesters(handler)
                .WithCss()
                .WithJavaScript();
            var _context = BrowsingContext.New(configuration);
            var _document = await _context.OpenAsync("this site");
            var button = _document.ActiveElement.QuerySelector<IHtmlButtonElement>("button.b-button");
            IHtmlButtonElement anc = _document.Anchors.First(x => x.ClassName == "b-button_width_available") as AngleSharp.Dom.Html.IHtmlButtonElement;
            anc.DoClick();
          
            var domParser = new HtmlParser();
            var result = domParser.Parse(_document.ToHtml());
           

            
             
            var items = _document.QuerySelectorAll($"div>a");
            foreach (var item in items)
            {
               
                    Console.WriteLine(item.Attributes["href"].Value.ToString());
                
            }`

**Comment by yurasakun** [comment]
Pleas Help me !

**Comment by FlorianRappl** [comment]
Sorry, I do not understand the question / problem.

Please rephrase.
