### ISSUE TITLE
I can't load just 2 tr and use them in anglesharp.

### ISSUE THREAD

**Issue by ghost** [AngleSharp/AngleSharp#707]
I have a two 2 tr that my html based app send to c# code and I need to parse it and find text in tr. I am not able to get it to work. for example

```
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
```

When I load this html in anglesharp, it doesn't work. it's how me null for outerHTML. does anyone have workaround for this.

**Comment by mausworks** [comment]
What happens if you stick it in a `<table>` tag?

**Comment by FlorianRappl** [comment]
This is illegal HTML and will not produce anything in any browser. Sure you are not missing a `<table>`?

**Comment by ghost** [comment]
@mausworks  it work if I send the whole table tag, I changed my code to send the whole table code in C# code.

@FlorianRappl  yes it's invalid code. I am looking for a solution which help me by sending only few tr without (whole table, @mausworks  this is exactly what I am doing now).


@FlorianRappl  your reply give me a another idea, yesterday I set a same id a lot of time (which is also invalid HTML code) but every time I loop over tr and read the #abc it's working.

I am thinking to change tr to something (like div or span) and send it to c# and see if this is working like multiple id case.

Thanks
