### ISSUE TITLE
Dealing with spaces

### ISSUE THREAD

**Issue by ajorkowski** [AngleSharp/AngleSharp#708]
Hi - I'm currently writing a html -> docx transformer and I am having a bit of trouble with making sure the spacing is correct when parsing out the html.

For example, lets use the following html: `<span>text[ ][ ][ ][ ][ ][ ][ ]&nbsp;&nbsp;[ ][ ][ ][ ]text</span>` (brackets for emphasis on spaces)

You can see in the preview [ie browser output] that it comes out with 4 spaces total: ie `text[ ][ ][ ][ ]text`. This is because the spaces/new lines/etc in the html are collapsed to single spaces, and then you have the encoded `&nbsp;`, which is converted afterwards.

I can't seem to replicate this when I am using AngleSharp - because it looks like when I get the IText element it has already un-encoded the html AND it doesn't pre-collapse the whitespace... so by the time I get the `IText.Text` value it has the additional spaces and I cannot tell the difference between a space and the `&nbsp;`. ie `IText.Text` will look like `text[ ][ ][ ][ ][ ][ ][ ][ ][ ][ ][ ][ ][ ]text`

Is there a way to get the original encoded html state for a text block? Alternatively, is there a way to make sure that AngleSharp does the whitespace collapsing as part of the IText parsing before unencoding the html?

**Comment by campersau** [comment]
You can check if the char is a [`Symbols.NoBreakSpace`](https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Foundation/Symbols.cs#L154) or a simple whitespace.

See https://github.com/AngleSharp/AngleSharp/pull/655#issuecomment-377633131 and

https://github.com/AngleSharp/AngleSharp/blob/9da30e34c2c5cffd814d22f0e122db6bda968dd5/src/AngleSharp/Dom/Html/HtmlElement.cs#L830

**Comment by ajorkowski** [comment]
Yeah, great! Thanks for that info, it was exactly what I needed! I can just ignore that character from a regex....

Cheers!
