### ISSUE TITLE
NRE when first element in form has no name

### ISSUE THREAD

**Issue by Suchiman** [AngleSharp/AngleSharp#71]
Following code will cause a NullReferenceException on [`_entries[0].Name.Equals`](https://github.com/FlorianRappl/AngleSharp/blob/c11b9d8a5b95fbbca76eb6ad2da43f418bcebfba/AngleSharp/Html/FormDataSet.cs#L96) since `Name` will be null

``` csharp
var test = DocumentBuilder.Html(@"
<form method=""post"">
    <input type=""button"" />
</form>");
var form = test.Forms.OfType<IHtmlFormElement>().FirstOrDefault();
var result = await form.Submit();
```

**Comment by FlorianRappl** [comment]
Definitely a bug. Will be fixed! Thanks a lot for the report!
