### ISSUE TITLE
Not parsing &nbsp; in HtmlParser

### ISSUE THREAD

**Issue by nikhilsreeni** [AngleSharp/AngleSharp#710]
Non-Breaking Space (&nbsp;) or (`&nbsp;`) are not parsing correctly

    public class Program
    {
        public static void Main(string[] args)
        {
            string xmlStringWorking = "<xml>&ast; &dollar; &nbsp;  &copy; &uml; </xml>";

            var parser3 = new HtmlParser();

            var document3 = parser3.Parse(xmlStringWorking);

            XmlDocument doc = new XmlDocument();

            doc.LoadXml(document3.DocumentElement.GetElementsByTagName(@"body").First().InnerHtml);
        }
    }

**Comment by FlorianRappl** [comment]
What do you expect?

If you look at [the fiddle](https://dotnetfiddle.net/eOHcYx) you'll see that the outcome is `* $ &nbsp;  © ¨ `, which is exactly the same outcome in all evergreen browser.

Just to simplify see [this snippet](https://www.w3schools.com/code/tryit.asp?filename=FVEZTNL077LE) which alerts the same string.

HTH!

**Comment by nikhilsreeni** [comment]
hi @FlorianRappl ideally `&nbsp;` should be convert in to non-breaking space, `&nbsp;` is not the decoded value

**Comment by FlorianRappl** [comment]
> ideally &nbsp; should be convert in to non-breaking space, &nbsp; is not the decoded value

That is a render information - see what your browser sees / the specification says. We follow the specification, otherwise we are doomed.

**Comment by campersau** [comment]
With `InnerText` you would get a non breaking space but obviously not the tag names.
https://dotnetfiddle.net/Lw7lQL
See also https://github.com/AngleSharp/AngleSharp/issues/708#issuecomment-419704926
