### ISSUE TITLE
Get an element size and position

### ISSUE THREAD

**Issue by mdesousa** [AngleSharp/AngleSharp#712]
Is there a way to get an element's size and position when using the BrowsingContext? That is, something similar to Element.getBoundingClientRect() in javascript.

Thanks

**Comment by FlorianRappl** [comment]
Right now not - at least not with the core library (we do not have any rendering capabilities and thus no rendering tree is generated which could contain such information).

Such features have been planned, but not for the core library, which will always only build the foundation for other libs.
