### ISSUE TITLE
getting error System.NullReferenceException when debuging

### ISSUE THREAD

**Issue by Amarnath143** [AngleSharp/AngleSharp#714]
Hi i am new to AngleSharp in c# i want to submit a form with textbox value and a captcha code i getting error like this `InnerText = '((AngleSharp.Dom.Html.HtmlElement)new System.Linq.SystemCore_EnumerableDebugView<AngleSharp.Dom.IElement>(((AngleSharp.Dom.Document)((AngleSharp.BrowsingContext)context).Active).All).Items[0]).InnerText' threw an exception of type 'System.NullReferenceExce...` i found this when i debug my code and here is my actual code

`var requester = new HttpRequester();

                requester.Headers["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36";
                var configuration = Configuration.Default.WithDefaultLoader(requesters: new[] { requester }).WithCookies();
                string url = "http://www.mca.gov.in/mcafoportal/viewSignatoryDetails.do";
                var context = BrowsingContext.New(configuration);
                await context.OpenAsync(url);
                IDocument doc = await BrowsingContext.New(configuration).OpenAsync(url);
                
                    await doc.Context.Active.QuerySelector<IHtmlFormElement>("form[name='signatoryForm']").SubmitAsync(new
                    {
                        companyID = "U30009KA2001PTC029692",
                        displayCaptcha = "false"
                    });`
i found the error at `var context = BrowsingContext.New(configuration);
                await context.OpenAsync(url);
                IDocument doc = await BrowsingContext.New(configuration).OpenAsync(url);` when debugging my code and same code was worked for my other link without error. so please me.

**Comment by FlorianRappl** [comment]
I am not sure this is a bug in AngleSharp or rather in the code above (e.g., the site you request via the URL does not have the element you look for).

MWE without an external URL?
