### ISSUE TITLE
can AngleSharp deal with dynamic pages with JS? document load as empty

### ISSUE THREAD

**Issue by Denis717** [AngleSharp/AngleSharp#718]
HI there,
I'm using AngleSharp to build an app for web file download .  but can't parse JavaScript Web Page in C# ,
How do I force AngleSharp to execute all of the JavaScript before I look for the specific element?

I try to find the download link(export as excel) from a website,  the download link is a part of datatables 
below is my code:
 
            var requester = new HttpRequester();

            var url = "https://www.central-bank.org.tt/statistics/data-centre/selected-econ-indics-quarterly";

            requester.Headers["User-Agent"] = _settings.PrimaryUserAgent;

            var config = Configuration.Default.WithDefaultLoader(requesters: new[] { requester }).WithJavaScript().WithCss();

            var document = await BrowsingContext.New(config).OpenAsync(url);

            var link = document.QuerySelector("a.dt-button:nth-child(3)")

the Idocument value is loaded, but the body content(document.Body.InnerHtml) is alway empty, 
I did add the anglesharp.scripting.javascript package to my project, but still not make it work.
my package version as below:
 package id="AngleSharp" version="0.9.9" targetFramework="net462" 
 package id="AngleSharp.Scripting.JavaScript" version="0.5.1" targetFramework="net462"

it is possible to parse the link from dynamic web pages with JS?
or is there any other solution to make it work.
Thanks

**Comment by FlorianRappl** [comment]
There are two things:

1. Allow AngleSharp to download resources (the way you set up the requester it can only download full pages, not resources, e.g., JS files, on it)
2. AngleSharp.Scripting.JavaScript works for simple scripts, but once scripts make use of e.g., non ES5, non standard, rendering DOM, ... APIs it will fail - every sophisticated web app will therefore not work

You can inspect and make it work by contributing / debugging with AngleSharp.Scripting.JavaScript. Its unfortunately a very tedious task.

HTH!

**Comment by Denis717** [comment]
Thanks a lot.
how to setup the requester to download page with resources for JS file? will it help me to load the HTML content with JS execution?
use my code, the download page is empty.

**Comment by FlorianRappl** [comment]
```cs
Configuration.Default.WithDefaultLoader(setup => { setup.IsResourceLoadingEnabled = true; }, new[] { requester });
```
