### ISSUE TITLE
AsUrlEncoded produces too many &

### ISSUE THREAD

**Issue by Suchiman** [AngleSharp/AngleSharp#72]
This is probably only cosmetic but due to the way how the `&` is added [here](https://github.com/FlorianRappl/AngleSharp/blob/c11b9d8a5b95fbbca76eb6ad2da43f418bcebfba/AngleSharp/Html/FormDataSet.cs#L103), following code:

``` csharp
var test = DocumentBuilder.Html(@"
<form method=""post"">
    <input type=""button"" />
    <input name=""other"" type=""text"" value=""something"" />
    <input type=""text"" value=""something"" />
    <input name=""another"" type=""text"" value=""test"" />
</form>");
var form = test.Forms.OfType<IHtmlFormElement>().FirstOrDefault();
var result = await form.Submit();
```

produces this urlencoded post body with too many `&`

```
&other=something&&another=test
```

**Comment by FlorianRappl** [comment]
I can see why one (name) is missing, but I doubt that the given URL is intentional formed that way. I will check to see if the URL construction is as specified, or if this is actually a bug. Either way I agree, there seem to be too many ampersands. Thanks for the hint!
