### ISSUE TITLE
Can AngleSharp manage GET requests made through AJAX?

### ISSUE THREAD

**Issue by nicktheone** [AngleSharp/AngleSharp#723]
I have a page that dinamically loads some data through GET requests passing several parameters and then displays said data in the page after a while. Will AngleSharp let me inspect and parse the page with the results from the script or will it only display the page before the script run?

**Comment by FlorianRappl** [comment]
AngleSharp does not display anything - it is just an HTML parser with some extended capabilities like a dynamic DOM.

The page can only dynamically load data after it has been loaded via JS which is not part of the core library. There is an experimental JS engine for AngleSharp, which can deal with some basic JS stuff. In this case the answer to your question is yes, however, keep in mind that if the JS used on the pages is sophisticated the JS engine cannot deal with it and the data won't be loaded and integrated correctly.

HTH!
