### ISSUE TITLE
Newbie question on how to monitor DOMContentLoaded event

### ISSUE THREAD

**Issue by zydjohnHotmail** [AngleSharp/AngleSharp#725]
Hello:
I am new to AngleSharp, but I like this project.  Now I have some questions:
I created a C# project using Visual Studio 2017 Version 15.9.1 on Windows 10, my goal is to monitor a web site, which uses Javascript to generate real time contents.
When using Chrome Devtools, I can see its Javascript scripts run and from time to time, the event:  XHR finished loading: GET "<URL>" is fired each time when new real time contents are generated.
I want to know if I can write a function to monitor XHR download event or not, but more importantly, I want to monitor another event: DOMContentLoaded, and use querySelectorAll to get the corresponding contents.  
Now I can do with AngleSharp that I use querySelectorAll to get the corresponding contents the first time I use browser to visit that web site.
My question is: how I can use AngleSharp to monitor that web site all the time and as soon as DOMContentLoaded event happens, I can run querySelectorAll to get the corresponding contents.
If you know how to do this, please share your code.
What I can do now seem: I use querySeletorAll to get the content first, then sleep 3 seconds, do a web page reload, then use querySelectorAll to get the contents again, and do a dead loop, but this seems to be not a good idea.  Any better idea?
Thanks,

**Comment by FlorianRappl** [comment]
When you use the browsing context and await the content then this is implicit for a full document load event (which is even after the dom content load). Otherwise, hooking on to the event is simple and straight forward - `AddEventListener` and just use the DOMContentLoaded event from the event names.

But again (unless I do not correctly understand the question) this is not necessary since any document load in AngleSharp will return to its caller *after* the DOMContentLoaded event.

Can you show some code?

**Comment by zydjohnHotmail** [comment]
Hello:
As I am new to both AngelSharp and Chrome Devtools, I can just describe what I have done and what I want to do.
For example, I am watching one web site, like “http://www.mysite.com/”, if I open Chrome to visit this web page, and run Devtools, I can setup XHR break points:
From Element view, I can select some DIV in the HTML page, then in Source view, I can click on the “+” to add a “XHR/fetch Breakpoints” and use URL contains “mysite.livetime.txt”, so each time, when the real time contents are downloading by the JavaScript, the script will pause at in the JavaScript as long as it contains “mysite.livetime.txt”.
However, the issue for me now is: I can’t set up a similar break point on DOM for specific download part of the contents.  I tried to set break points from “Event Listener Breakpoints” on the “Dom Mutation” for “DomSubTreeModified” and “DomContentLoaded”.
It seems when new contents downloaded, the JavaScript is paused, but it seems difficult to find some condition, just like the “XHR/fetch Breakpoints”, where I can restrict the JavaScript pause when the URL contains “mysite.livetime.txt”.
So my “Event Listener Breakpoints” on “Mom Mutation” will cause JavaScript pause on all DomContentLoaded event.  
But even this is currently OK, then what I want to do is: how I can use AngleSharp do the same job?
I mean, I want to use Browser to visit “http://www.mysite.com/”, then wait for “DomContentLoaded” happen, then what this happens, I can run something like:
IElement[] start_times = context.Active.QuerySelectorAll("div.time").ToArray();
To get the dynamic contents generated by the JavaScript.
Context is the IBrowsingContext context = BrowsingContext.New(config) with default configuation, and I visited web site using: await context.OpenAsync("http://www.mysite.com/");

For me, the first time, when I visit “http://www.mysite.com/” web site and use context.Active.QuerySelectorAll("div.time").ToArray() to get all dynamic contents always works; however. My goal is to continuing monitor the web site and use the similar code to get the dynamic contents, but I want to write the code to watch for “DomContentLoaded” event, just as I did in Chrome Devtools, I don’t want to reload the same page again and again.
Please let me know if I can do this or not.
If so, please show me the C# code using AngleSharp on how to monitor “DomContentLoded” event and get the dynamic content.
If I open the “http://www.mysite.com/” web site using Chrome browser, I can see the dynamic contents coming all the time, I don’t have to do anything, as they are generated by JavaScript in real time, but how I can use Event Listener to listen to “DomContentLoaded” event and get the dynamic contents using QuerySelectorAll to get them?  I don’t want to reload the page every a few seconds, as it is not good for performance, but my knowledge for AngleSharp is limited, no idea how to do this now.
Thanks,

**Comment by FlorianRappl** [comment]
AngleSharp does not contain any JS engine out of the box and anything that happens is always in your control, so the scenario you describe is impossible / not applicable.

Anything that loads is controlled by you anyway and as already written the callback in AngleSharp is always *after* the dom content loaded event, which means you do not need to do anything here.

HTH!
