### ISSUE TITLE
Some code samples for DOM

### ISSUE THREAD

**Issue by zydjohnHotmail** [AngleSharp/AngleSharp#728]
Hello:
I need to monitor a remote web site"www.randomNum.com", (a fake domain name), which has a lot of JavaScript scripts, one of them is like this one (I just show the important code to make things simple)

<!doctype html>
<html lang="en">
<title>Simple Random JavaScript</title>
<body>
<div id="CurrentNumber"></div>
</body>
<script type="text/javascript">
document.getElementById("CurrentNumber").innerHTML = Math.random().toString();
</script>
</html>

The web site will from time to time run the JavaScript to show a random number on its web site, the time, the script run is totally random.  I want to write a C# project using AngleSharp to monitor the web site, but try to use querySelectorAll to get the random number generated by the JavaScript.
I have some C# code like this: (I am using Visual Studio 2017 Version 15.9.2 with C# 7.3 on Window 10)

static async System.Threading.Tasks.Task Main(string[] args)
{
var random_numbers = new List<decimal>();
IConfiguration config = Configuration.Default.WithDefaultLoader().WithCookies();
IBrowsingContext context = BrowsingContext.New(config);
await context.OpenAsync("www.randomNum.com");
IElement[] numbers = context.Active.QuerySelectorAll("CurrentNumber").ToArray();
for(int i = 0; i < numbers.length ; i++)
{
random_numbers.add(decimal.parse(numbers[i].toString));
}
}
}

The above code works for the first time, when the web page fully loaded from "www.randomNum.com", but how I can rewrite my code, so each time, when the web page dynamically generates a random number, I can use C# code to get its current generated number.  The time when the JavaScript will generate the random is totally out of my control, it is controlled by other JavaScript scripts on the same web site, but I don’t care about the other JavaScript scripts, I only need to get the current generated random number.
So I want to know how I can write some code to monitor some JavaScript event like DomContentLoaded or some other Web event, like download_completed/document_completed or even if I can use something like Web Browser reload/refresh, but I can’t find AngleSharp has reload/refresh methods available to call.
Please advice, and as my knowledge for AngleSharp and JavaScript are both limited.
It is better to share me some C# code or at least give me some web link where I can see the C# code for this.
Thanks,

**Comment by FlorianRappl** [comment]
See #725.
