### ISSUE TITLE
Pseudo Selectors

### ISSUE THREAD

**Issue by dlalex83** [AngleSharp/AngleSharp#730]
Hi there,

just came across AngleSharp (always been using CSQuery) and it seems a great candidate to replace CSQuery. I was auditing my use cases and noticed that there are some pseudo selectors that I'm currently using in CSQuery that are not working in AngleSharp. More specifically: first(), last(), last-of-type(), visible(). Some others pseudos work perfectly fine (e.g. :has(), :nth-child(index), :not(selector).

The error I get back is: 
The string did not match the expected pattern.

Are those selectors just not supported? Or am I doing something wrong?

Thanks

**Comment by FlorianRappl** [comment]
Hi @dlalex83, CsQuery is a C# version of jQuery and supports most of the pseudo-selectors introduced by jQuery. AngleSharp is fully standards driven and only includes the pseudo selectors as described in the W3C Selectors Level 3 / (nearly all of) 4 specification.

Therefore some of the things you mentioned (e.g., `:visible`) are not there, but in some cases (e.g., `:first`) there is most likely a simple replacement (either directly in the query or just via C# / LINQ).

Hope that helps!

**Comment by dlalex83** [comment]
Hi @FlorianRappl that does help indeed! Thanks!

**Comment by winzig** [comment]
> but in some cases (e.g., :first) there is most likely a simple replacement (either directly in the query or just via C# / LINQ)

@FlorianRappl Could you point me to any documentation about alternatives for some of these pseudo selectors that you mention above? E.g. what is the alternative to `:first`? I realize I could use Linq to just get the first, but for the app I'm working on, it would offer the most flexibility to be able to do it all via DOM selectors.

**Comment by FlorianRappl** [comment]
Since selectors give you back an `IEnumerable` you can use any LINQ functionality that you like, such as `FirstOrDefault()`.

**Comment by winzig** [comment]
Yeah I definitely get it, but the issue for us is we're working on a system that operates in C# as well as in JavaScript, and so ideally we'd be able to share the DOM selector code between these environments instead of having to do custom C# work, so was just curious if there was any documentation on specifically which selectors are supported?

**Comment by FlorianRappl** [comment]
All L4 selectors are supported.

For pseudo classes, see https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Css/DefaultPseudoClassSelectorFactory.cs#L16.
