### ISSUE TITLE
The error “Non-generic method” IParentNode.QuerySelector (string) “cannot be used with type arguments. ”

### ISSUE THREAD

**Issue by it19862** [AngleSharp/AngleSharp#733]
I try to log in to the site using the AngleSharp library. I use code for this.

```
class Program
{
    const string sourceToSite = "https://mail.ru/";
    const string sourceToTarget = "https://e.mail.ru/messages/inbox/";

    static async void QueryToOrders()
    {
        var config = Configuration.Default.WithDefaultLoader().WithCookies();
        var context = BrowsingContext.New(config);
        await context.OpenAsync(sourceToSite);
        var check = context.Active.QuerySelector<IHtmlFormElement>("form#Auth").SubmitAsync(new { Login = EMAIL + "@mail.ru", Password = PASSWORD }).Result;
        var msgs = await context.OpenAsync(sourceToTarget);
    }
}
```
I get an error:
"The error "Non-generic method" IParentNode.QuerySelector (string) "cannot be used with type arguments." "
Question
How to fix the error?

**Comment by FlorianRappl** [comment]
This is more related to C# than AngleSharp.

- Either drop the type arguments (as you use the non-generic version)
- Or include the extension method via a `using` statement (you forgot to state the version of AngleSharp, but I assume its in `AngleSharp.Extensions`

HTH!

**Comment by LeastOne** [comment]
I encountered the same error however the exact using statement I needed to add was `using AngleSharp.Dom;`.

**Comment by FlorianRappl** [comment]
> I encountered the same error however the exact using statement I needed to add was using AngleSharp.Dom;.

Yes that is the state for AngleSharp 0.10 or later. The OP presumably used 0.9 or earlier (can be seen on the configuration).

I would be interested how the UX could be improved here. Should we rename the generic version to make this clear? Should we describe that on the non-generic version? Any insight appreciated @LeastOne . Thanks!
