### ISSUE TITLE
How to parse sites with authorization?

### ISSUE THREAD

**Issue by it19862** [AngleSharp/AngleSharp#734]
I try to write a parser.
If I understood the theory correctly, then the logic should be as follows:
 - authorization;
 - get cookies;
Movement through the pages
 - send cookies;
 - go to page_1;
 - send cookies;
 - go to page_2;

Authorization form:
` <form name="login" class="ui large form" action="/login/" method="POST"><div class="required field ui grid aligned left"><input name="login[login]" value="" type="text" placeholder="Электронная почта" maxlength="64" autocomplete="off"></div><div class="required field ui grid aligned left"><input name="login[password]" value="" type="password" maxlength="32" autocomplete="off" placeholder="Пароль"></div><div class="equal width fields" style="flex-wrap:nowrap;"><div class="field" style="text-align: left;"><div class="ui checkbox large step"><input id="remember" type="checkbox" name="login[remember]" tabindex="0" value="1" class="hidden"><label for="remember">Запомнить меня</label></div></div><div class="field" style="text-align: right;"><a href="/forgot/">Забыли пароль?</a></div></div><div class="field"><button class="fluid positive ui button big">Войти</button></div><input name="login[type]" type="hidden"><input name="login[init]" type="hidden" value=""></form>`

Minimum code
```
public async void Authorization(string pathPageLogin, string userName, string password)
        {
            IConfiguration config = Configuration.Default.WithDefaultLoader().WithCookies();
            IBrowsingContext browsingContext = BrowsingContext.New(config);

            browsingContext.OpenAsync(pathPageLogin).Wait();


            (browsingContext.Active.QuerySelector("input[name = 'login[login]']") as IHtmlInputElement).Value = userName;
            (browsingContext.Active.QuerySelector("input[name = 'login[password]']") as IHtmlInputElement).Value = password;
            (browsingContext.Active.QuerySelector("form") as IHtmlFormElement).SubmitAsync().Wait();


        }

        public async void Parsing(string url, string pathFileHtml)
        {
            HttpClient client = new HttpClient();
            var response = await client.GetAsync(url); // скачиваем страницу
            string source = await response.Content.ReadAsStringAsync(); // Переносим в переменную

            #region Сохранить страницу в файл
            File.WriteAllText(pathFileHtml, source);
            #endregion Сохранить страницу в файл

            #region Парсер
            // HTML парсер, который доступен из "AngleSharp".
            var domParser = new HtmlParser();

            // Спарсим асинхронно наш исходный код и получим документ с которым мы можем работать
             var document = await domParser.ParseAsync(source);

            // *** Парсер ****              
            // результат
            var list = new List<string>();

            var items = document.QuerySelectorAll("a").Where(item =>
                        item.ClassName != null && item.ClassName.Contains("post__title_link"));

            foreach (var item in items)
            {
                list.Add(item.TextContent);
            }
            #endregion

        }
```

Question.
How to make code with a minimum set of basic methods for simple sites so that the logic principle can be seen?

**Comment by FlorianRappl** [comment]
Usually you hide complicated logic via patterns or some refactoring to logical classes / functions that are then called from a kernel-like function.

Not sure if this helps you - the question is rather generic and any solution must adhere to your specific problem / project.
