### ISSUE TITLE
Project should target lower NetStandard version

### ISSUE THREAD

**Issue by maxkatz6** [AngleSharp/AngleSharp#738]
Hi!

### Description

Currently AngleSharp 0.10.0 targets NetFramework 4.6 and NetStandard 2.0, but it can target lower version.

### Background

As described in https://docs.microsoft.com/en-us/dotnet/standard/net-standard NS2.0 is supported only by newer platforms versions. But in real world there are cases, when we our applications have to support out of dated platfroms and we can't easelly use NS2.0 libralies.
In my case, I support UWP 14393.0, which allows to use only NS1.4 or lower.
Yes, you can say, that we should use also out of dated version of AngleSharp, but I don't think, that is good ending of problem.

### What we can do

**NetStandard 1.3**
We can target NS1.3 with adding some official nuget packages, which is not included by default
```xml  
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'">
  <PackageReference Include="System.Net.Requests" Version="4.3.0" />
  <PackageReference Include="System.Reflection.TypeExtensions" Version="4.5.1" />
</ItemGroup>
```

**NetStandard 1.1**
As @tbolon described in https://github.com/AngleSharp/AngleSharp/pull/715#issuecomment-434459838 we can target NS1.1 if we replace HttpWebRequest with HttpClient.
I tried to target 1.1 and noticed at first look, that we also should write refrection polyfills to replace System.Reflection.TypeExtensions package and should found alternative for System.Text.Encoding.CodePages.

Thanks for AngleSharp :)
Best regards, Max Katz.

**Comment by FlorianRappl** [comment]
Hi Max - awesome PR. Definitely a sound request and 1.3 sounds fine to me!

Even 1.1 sounds fine; but maybe 1.3 is low enough. Let's just see if someone else *really* wants 1.1, otherwise I would just go with 1.3.

**Comment by FlorianRappl** [comment]
(We'll ship it in the v0.11, which will be the filler to v1.0 - taking into consideration all comments; suggestions, fixes etc. - time-boxed, i.e., to be released Feb '19 or earlier)
