### ISSUE TITLE
DefaultRequester does not handle gzipped or deflated content

### ISSUE THREAD

**Issue by ossaltu** [AngleSharp/AngleSharp#74]
Some servers return gzipped or deflated content without asking (setting appropriate header), DefaultRequester does not decompress content and passes it to latter stages, which causes some trouble.

**Comment by FlorianRappl** [comment]
I don't know if I consider this a bug. The `DefaultRequester` is a very basic, rudimentary implementation that does not support a lot of things (for instance `https` is also not supported, even though it might work for some pages). If you really want to handle such content, you should implement the `IRequester` interface yourself.

**Comment by FlorianRappl** [comment]
Just to add an additional remark: I would have provided a better implementation, however, since AngleSharp is a PCL I only have access to the `WebRequester` (and even that is limited). Therefore platform specific implementations are far better. For an example if you go with the Microsoft HTTP Client libraries you'll already be in a better shape. Another library I can only recommend is EasyHttp.

**Comment by ossaltu** [comment]
I get your point, but I guess this will be an issue in future, because people are using libs to save time and can be annoyed when realize that they have to write multiple extensions to make it work properly. Don't get me wrong, no complains from my side, AngleSharp is best HTML parser compared to what I've seen before, but it's just a thing to think of :)

I've been using MS HTTP client in PSLs for some time, don't see any reason to use other alternatives.

**Comment by FlorianRappl** [comment]
If you know an easy way to support any of those things (e.g. supporting gzipped content) then any help would be appreciated. I do not exclude improving the requester, I just think it should not be the main purpose of AngleSharp (I will do other libraries on top of AngleSharp, that already implement something like that, but right now I can't focus on that).
