### ISSUE TITLE
Missing System.Text.Encoding.CodePages reference

### ISSUE THREAD

**Issue by kpkozak** [AngleSharp/AngleSharp#740]
### Description

Missing reference to System.Text.Encoding.CodePages in latest (0.10.0) version

### Steps to Reproduce

1. Reference AngleSharp NuGet package in your project
2. Use AngleSharp
```
class Program
    {
        static void Main(string[] args)
        {
            var parser = new HtmlParser();
            var result = parser.ParseDocument("<html></html>");
        }
    }
```
3. Result:  Exception
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'AngleSharp.Configuration' threw an exception. ---> System.IO.FileNotFoundException: Could not lo
ad file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

**Expected behavior:** 
AngleSharp does not throw initialization exception

**Actual behavior:** 
Exception thrown. 

**Environment details:** .netcore console app

### Possible Solution
Manually adding reference to mentioned package fixes the issue

**Comment by FlorianRappl** [comment]
Thanks for the report!

I think this is just missing from the NuGet - right? So the workaround is to explicitly reference it at the moment. Could you please confirm this?

**Comment by kpkozak** [comment]
@FlorianRappl yes, that's true. If referencing this explicitly, manually in the project, everything works (I had exactly this on my mind writing "Possible Solution" section) ;)

**Comment by FlorianRappl** [comment]
I'll release a hotfix soon! Thanks for the confirmation!

**Comment by jgrandydev** [comment]
I added to my project the NuGet package `System.Text.Encoding.CodePages` 

Project references now includes `System.Text.Encoding.CodePages` ( Version 4.1.1.0 , Runtime Version v4.0.30319 )

But this did not resolve this issue.

**Comment by FlorianRappl** [comment]
@jgrandydev not sure what you refer to - the latest version (0.11.0) ships with `System.Text.Encoding.CodePages` as a dependency on all platforms (so there is nothing you need to add).

If you face a problem then please describe it with all necessary details, otherwise I won't be able to give you any support.

**Comment by jeremymeng** [comment]
You probably meant to @jgrandydev

**Comment by FlorianRappl** [comment]
Right, thanks for the hint @jeremymeng !

**Comment by jgrandydev** [comment]
@FlorianRappl I was trying to piggy-back on this issue to avoid opening a new.

W10, VS17, .NET Framework 4.7.2 project 

`AngleSharp 0.11.0.0` installed via NuGet Package Manager

Yes it installs dependency `System.Text.Encoding.CodePages v4.5.0` but this does not resolve issue : 

```
class Program
    {
        static void Main(string[] args)
        {
            var parser = new HtmlParser();
            var result = parser.ParseDocument("<html></html>");
        }
    }
```

> Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

If I manually update to `System.Text.Encoding.CodePages v4.5.1` it does not help.

**Comment by FlorianRappl** [comment]
I think you may have an invalid binding redirect set up (look at your `app.config`).

I just did what you wrote and for me everything works (W10 VS17 with latest update, .NET Framework 4.6.1, console app).

**Comment by arteny** [comment]
I faced same problem when installed last version of AngleSharp from scratch:

```
System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл. ---> System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
    в AngleSharp.Browser.EncodingMetaHandler..ctor()
   в AngleSharp.Configuration..ctor(IEnumerable`1 services)
   в AngleSharp.BrowsingContext.New(IConfiguration configuration)

```
Why ticket is closed if the issue still reproduced?
I think it is necessary to correct NuGet package?

**Comment by FlorianRappl** [comment]
Because the last NuGet package includes the reference to `System.Text.Encoding.CodePages` for all targets not only .NET Standard compatible targets.

Not sure what you are facing has to do with AngleSharp. Have you gone through this thread (see, e.g., the binding redirect remark)?

@arteny your message is practically useless unless you put more infos in it that justify another investigation (at least OS, NuGet version, VS version, target framework, ...). Please supply this info if you think there is still something missing.

**Comment by havremunken** [comment]
Hi there, I'm having an issue that seems very similar to this. Works on my machine (tm), but when I deploy to an old Win2008R2 server that still needs to stay alive for a while, I get the exception. There is something very strange going on with all the version numbers of the `System.Text.Encoding.CodePages` package; Check out the stackoverflow issue I made, particularly the edit on May 14th: https://stackoverflow.com/questions/56102231/binding-redirect-when-importing-anglesharp-in-net-4-7-2-somehow-tries-to-pull-i/56102381

I'm not convinced this is an AngleSharp problem, but using AngleSharp is the context in which I am seeing it, so I have to use that as a starting point..

**Comment by FlorianRappl** [comment]
HI @havremunken I'll try to investigate this a bit.

The binding redirects are also one thing that drives me crazy. Since the issue is happening on a particular server I guess its a particular framework / implementation that tries to use something different (maybe this is a GAC issue?! - is there something special about the process this thing is running in?).

Maybe I'll find something.

**Remark**: I knew why I wanted to avoid dependencies ;).

**Comment by havremunken** [comment]
Hi Florian, awesome, thanks - also for the great work on AngleSharp! I'm a beginner in this world but except for the troublesome deployment the project has been a joy to use!

The process is a data collector, just a simple C# based console application, that is run at regular intervals as a scheduled task. I will check out the GAC next time I have access to the server, but nothing has been put in there "on purpose" that I am aware of - which of course does not rule out a problem on that side.

Yeah, I understand why staying free of external dependencies as far as possible is a sweet deal. This kind of "binding redirect hell" seems like a slightly more modern version of DLL hell. :)

If you come across anything you want me to test, please let me know, and I will do so!

**Comment by FlorianRappl** [comment]
Yep that would be appreciated. I will let you know!

**Comment by havremunken** [comment]
Small update here; No AngleSharp, System.Text.Encoding.CodePages or System.Runtime.CompilerServices.Unsafe in the GAC on the server.

**Comment by havremunken** [comment]
Happy update for you, @FlorianRappl! This was a version mismatch against the .NET framework itself. 4.7.2 was not installed on the server (it isn't supported on this ancient OS), even though my apps ran fine compiled for this version. I configured the projects (console app + class library) to use 4.6.2, and everything now works. So as suspected - no reason to blame AngleSharp at all, it was just the peeping hole through which I saw the problem. :)

**Comment by FlorianRappl** [comment]
No problem thanks for the info @havremunken - glad you figured it out! :beers:

If anything else pops up feel free to create another issue or message me directly. We also have a [Gitter chat](https://gitter.im/AngleSharp/AngleSharp) for more dynamic interactions.

**Comment by sheldmandu** [comment]
@FlorianRappl Please re-open this issue as it's certainly not fixed. I have the exact same issue as others in this thread.  I simply install AngleSharp using nuget (which also creates the binding redirects in app.config) in a simple class library project that's responsible for some html parsing.

When I try to actually parse something with AngleSharp I get:

Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

The app.config file looks like this, which was auto-created with nuget install! 

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Text.Encoding.CodePages" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>`

I've tried targeting .NET Framework 4.6.1 and 4.6.2 and same result.

It really shouldn't be this complex and broken as it just turns people off from the get go and they go back to the tried and tested HAP, which might not be as good but doesn't have these issues.

**Comment by FlorianRappl** [comment]
> It really shouldn't be this complex and broken as it just turns people off from the get go and they go back to the tried and tested HAP, which might not be as good but doesn't have these issues.

That really isn't helpful. Please try to be constructive.

I use AngleSharp in a couple of projects and know many people using it - no issues wherever and also in this thread (see, e.g., latest conversation) the issue was not with AngleSharp, but rather with the setup / .NET specifics. I cannot fix how NuGet and .NET works.

Regarding your setup: I just tried with .NET 4.6.1 and .NET 4.6.2 - both work fine. I get exactly the same `app.config` as you do. After installing AngleSharp the `packages.config` looked as follows:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AngleSharp" version="0.12.1" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.0" targetFramework="net461" />
  <package id="System.Text.Encoding.CodePages" version="4.5.0" targetFramework="net461" />
</packages>
```

I think your problem may be in relation to your application. Remember the .NET version of your class library is not what counts; its the target platform of the consuming application. Make sure to have a compatible target there.

Hope this helps!

**Comment by sheldmandu** [comment]
Worked out the issue, issue was because it was in class library and the main project needed to have the bindings also.

**Comment by KalpeshPopat** [comment]
I faced same issue, and resolved it by adding the binding. 

reference to the package and the binding, both are required in consuming library and the final executing library.

point to note though: earlier this was working without adding the binding - problem came after i updated the package.

**Comment by reevev** [comment]
I'm seeing the same issue now, this is happening on one deployment but it is fine on all other locations including development machines. All have .NET 4.7.2 installed. 

I know there must be a logical reason, however I can't figure it out.

I don't want to file a new bug report as it seems the same issue.

LOG: DisplayName = System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = ***
LOG: Initial PrivatePath = ***
Calling assembly : AngleSharp, Version=0.14.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea.
...
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

Adding the nuget package to AngleSharp results in the following binding redirect. This is definitely at the deployed location that has the issue.

         <dependentAssembly>
            <assemblyIdentity name="System.Text.Encoding.CodePages" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.1.3.0" newVersion="4.1.3.0" />
         </dependentAssembly>


The exact same file version of System.Text.Encoding.CodePages.dll is in the bin folder as well.

Is anyone still experiencing this issue or has resolved it with the latest version after experiencing it?

**Comment by FlorianRappl** [comment]
Hi @reevev did you also look at #842 ?

Can you give more details regarding differences between the different machines where AngleSharp was deployed? Maybe it has nothing do with AngleSharp after all, but rather with .NET / the . NET installation (e.g., was it built for the right target, are these .NET versions are accessible by the user etc.).

**Comment by reevev** [comment]
Hi @FlorianRappl,

Thanks for getting back to me. It may not be any problem with AngleSharp, but we've spent a long time trying to ascertain the differences and reasons for the error. The only call with this error is the AngleSharp usage and also mentioned in the fusion logs, so I was hopeful someone had the same error and found a solution.

I did look at #842 however we are already using the 0.14 version. We've also had this deployed for some time on various servers without issue.  The application is asp.net targeting .NET 4.7.2 definitely (both at build time and at runtime in configuration).

The only difference I can see is the server with the issue is 2012 R2 server, not sure if there is some difference there. 4.7.2 framework is installed (verified through registry and had it reinstalled for safe measure). 

I am building a standalone console application and working through some diagnostics to see if we can get any further detail on why this is happening.

If I find a solution I'll post it.

**Comment by reevev** [comment]
I think we've confirmed this is definitely not an AngleSharp issue. For anyone with the sae issue, what we've found is the binding redirect for System.Text.Encoding.CodePages is being ignored.

In environments that work fusion logs clearly show the binding redirect being picked up:

LOG: Redirect found in application configuration file: 4.1.1.0 redirected to 4.1.3.0.
LOG: Post-policy reference: System.Text.Encoding.CodePages, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

In the one environment where the error occurs, these lines are missing from the fusion logs.

We don't have a solution yet as other binding redirects are working from the applications configuration as expected.

I'll put this question elsewhere now to try and resolve.

**Comment by FlorianRappl** [comment]
Awesome thanks for the extensive research @reevev - if you find a solution I'd love to know. We should include it in the FAQ (with your permission)!

**Comment by igitur** [comment]
I had the same problem and in my case this was the setup and solution:

# Setup
In my solution I have:
`ConsoleProgram`
which depends on `MyLibrary`
which depends on `AngleSharp`.

All are .NET 4.7.2 projects using the old `.csproj` format, not the new SDK style format. Note that `ConsoleProgram` doesn't depend on `AngleSharp` directly.

I have removed all manual binding redirects from my `app.config` files and ensured that `Auto-generate binding redirects` was enabled for all my projects in the solution. [Read more](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection) about how automatic binding redirects work. The key here is that the original `app.config` files have no binding redirects, but the generated `.exe.config` and `.dll.config` files in our output directory *do* have binding redirects.

After inspection of the generated `.config` files, I noticed that the `System.Text.Encoding.CodePages` binding redirect that I expected wasn't generated. This explained why I was receiving a `FileNotFoundException`.

# Solution
The solution is to add a reference to `AngleSharp` or `System.Text.Encoding.CodePages` in my `ConsoleProgram`. It seems the automatic binding redirect generation works only for the top-level project. It doesn't traverse nested projects. By making `ConsoleProgram` depend directly on the required `.dll` files, the generated `ConsoleProgram.exe.config` then contains the necessary binding redirects (auto-generated) and hence solved my problem.

**Comment by zspitz** [comment]
@reevev Did you ever post the problem / solution / further updates elsewhere?

**Comment by deanebarker** [comment]
FYI: I saw this again in February 2025 after updating to the latest AngleSharp version (1.3.0-beta.468).

I resolved it by explicitly installing the `System.Text.Encoding.CodePages` NuGet package.

Weird.
