### ISSUE TITLE
Setting .OuterHtml property of iframe parse value as text and encodes it

### ISSUE THREAD

**Issue by kpkozak** [AngleSharp/AngleSharp#741]
### Description

Wrapping iframe by setting `OuterHtml` property renders encoded markup

### Steps to Reproduce
Run the following program:
```
    class Program
    {
        static void Main(string[] args)
        {
            var parser = new HtmlParser();
            var document = parser.ParseDocument("<html><body><iframe src=\"https://google.com\"></iframe></body></html>");

            var iframe = document.GetElementsByTagName("iframe").Single();

            iframe.OuterHtml = $"<div>{iframe.OuterHtml}</div>";
            
            Console.Out.WriteLine(document.ToHtml());
        }
```

**Expected behavior:** 
```
<html><head></head><body><div><iframe src="https://google.com"></iframe></div></body></html>
```

**Actual behavior:** 
HTML markup is encoded:
```
<html><head></head><body>&lt;div&gt;&lt;iframe src="https://google.com"&gt;&lt;/iframe&gt;&lt;/div&gt;</body></html>
```
**Environment details:** .netcore console app

### Possible Solution
Short peek into decompiled sources shows that setter of `OuterHtml` property for some reason tries to parse value provided to setter with `this` as context of parsing, while it probably should be parent of the element.

**Comment by FlorianRappl** [comment]
Thanks for reporting the issue.

I think your suggestion of a solution is correct. I need to look at the official spec though. Will be fixed shortly.

**Comment by kpkozak** [comment]
Thanks for quick action! I really appreciate your hard work on development and maintaining of this package.

However, it looks like there is another tricky case revealed in 0.10.1. Let's go with an example:

```
class Program
    {
        static void Main(string[] args)
        {
            var parser = new HtmlParser();
            var document = parser.ParseDocument("<html><head></head><body></body></html>");

            var fragment =
                parser.ParseFragment(
                    "<p>some text</p>",
                    document.Body);

            (fragment.First() as IHtmlElement).OuterHtml = "<br>";
            
            
            Console.Out.WriteLine(fragment.ToHtml());
        }
    }
```

Result (`v0.10.1`): `<head></head><body><br></body>`
Result (prior to `0.10.1`): `<br>`
I think it might be another bug introduced by this change...

**Comment by FlorianRappl** [comment]
Hm good point. So I visited the official algorithm which tells me in case of a fragment to use a body as context. So your test reveals it, but indeed (at least at first sight) in an unexpected fashion. I'll need to look into that.

Thanks for trying it all out so patiently! This project needs enthusiastic users like you! Much appreciated :beers!
