### ISSUE TITLE
How to update anglesharp to version `0.10.1`?

### ISSUE THREAD

**Issue by it19862** [AngleSharp/AngleSharp#742]
I did a project in the version `anglesharp - 0.9.11`.

I want to update anglesharp to version `0.10.11`
I do it through Nuget
![3203](https://user-images.githubusercontent.com/18245828/50815099-0469a800-132d-11e9-8375-d896b4411dcf.png)

After the update, I get 40 errors.
Error example see picture

![3202](https://user-images.githubusercontent.com/18245828/50815101-07649880-132d-11e9-9218-7854d10674f5.png)

Question
Do I need to fix all the errors myself or do I update the Anglesharp incorrectly?
How to update anglesharp to version `0.10.1`?

**Comment by denis-ivanov** [comment]
https://github.com/AngleSharp/AngleSharp/blob/master/doc/Migration.md

**Comment by FlorianRappl** [comment]
Indeed namespaces changed a bit - sorry for inconvenience (hence a breaking change).
