### ISSUE TITLE
3 Question for Code chnage when Migrating to v0.1

### ISSUE THREAD

**Issue by jogibear9988** [AngleSharp/AngleSharp#743]
1.) I create Config like this:

             var config = AngleSharp.Configuration.Default.WithCss(new CssParserOptions() {IsIncludingUnknownDeclarations = true});

but the HtmlParser does not work with it:

         var parser = new HtmlParser(config);

2.) I created a empty document like this, this does not work any more:

       var htmlDocument = parser.Parse("");

3.) I'd access the styles like this, how does this work now:

        ((IHtmlElement) element).Style.Display = "flex";

**Comment by FlorianRappl** [comment]
1. Prefer to use the browsing context. If you use the `HtmlParser` directly you need to give it a browsing context anyway (or just plain parsing options).

2. What is not working? Don't you mean `ParseDocument`?

3. There are new methods called `GetStyle()` and `SetStyle()` etc. - these are extension methods. All these are in AngleSharp.Css.

Did you read the migration guide? I think 1) and 2) should be added there, but 3) is briefly explained. Maybe you can make a PR to the migration guide (would be much appreciated) to make it more complete.

Thanks and sorry for the inconvenience! :beers:

**Comment by jogibear9988** [comment]
1.) I still do not understand what to do now? AngleSharp.Configuration.Default.WithCss returns a IConfiguration and I need a HtmlParserOptions

2.) Yes, this function with a string does not exist any more

**Comment by FlorianRappl** [comment]
Hence I wrote you to create a browsing context. A browsing context wants an `IConfiguration`.

See [getting started](https://github.com/AngleSharp/AngleSharp#simple-demo).

You can use the browsing context to create an HTML parser explicitly (I do not recommend this, but it is possible), or you get the parser from the context via `GetService<IHtmlParser>()`, or you just run it like

```cs
var config = Configuration.Default.WithCss();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(res => res.Content("your source"));
```
