### ISSUE TITLE
HtmlParser

### ISSUE THREAD

**Issue by useruser1** [AngleSharp/AngleSharp#744]
Could not load file or assembly 'System.Text.Encoding.CodePages in code:
var parser = new HtmlParser();

**Comment by FlorianRappl** [comment]
I miss the version. I assume you use v0.10.0, which has a peer dependency on CodePages. Thus you need to install the dependency yourself. Other (recommended) way is to install v0.10.1, which already has this dependency in the NuGet.

HTH!

**Comment by useruser1** [comment]
version that have this error is 0.10.1

code with the same error:
var config = Configuration.Default;

**Comment by FlorianRappl** [comment]
Again cannot work without any environment knowledge. Did you read the issue template? Missing, e.g., target framework (.NET Core, FX?, ...) - just tell me the details then we can investigate. Usually it just works, otherwise install the dependency explicitly (obviously you miss this dependency...).

**Comment by useruser1** [comment]
.net framework 4.7.2 
and using  ...packages\AngleSharp.0.10.1\lib\net46\AngleSharp.dll

for replay this err just create any console app with this fw version and paste this code 
var parser = new HtmlParser();
