### ISSUE TITLE
HtmlParser.  Failed to load file or assembly

### ISSUE THREAD

**Issue by it19862** [AngleSharp/AngleSharp#746]
## Bug Report
ystem.TypeInitializationException
  HResult = 0x80131534
  Message = Initializer type "AngleSharp.Configuration" threw an exception.
  Source = AngleSharp
  Stack trace:
   in AngleSharp.Configuration.get_Default ()
   in AngleSharp.BrowsingContext.NewFrom [TService] (TService instance)
   in AngleSharp.Html.Parser.HtmlParser..ctor ()
   in rsh.Parser_test..ctor () in Z: \ vs \ csharp \ prb \ rsh \ rsh \ Parser_test.cs: line 19
   in rsh.Form1..ctor () in Z: \ vs \ csharp \ prb \ rsh \ rsh \ Form1.cs: line 18
   in rsh.Program.Main () in Z: \ vs \ csharp \ prb \ rsh \ rsh \ Program.cs: line 19

Internal exception 1:
FileNotFoundException: Failed to load file or assembly
"System.Text.Encoding.CodePages, Version = 4.0.2.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a" or one of their dependencies. Cannot find the specified file.

### Prerequisites
no or don’t know

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
no

- [ ] Are you running the latest version of AngleSharp?
Version - 0.10.1

- [ ] Did you check the FAQs to see if that helps you?
used google search.  did not help

- [ ] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
see screen

- [ ] Did you perform a search in the issues?
Searched for phrase: "Failed to load file or assembly"

For more information, see the `CONTRIBUTING` guide.

### Description
I get the error "Failed to load file or assembly" during application launch

### Steps to Reproduce
Error occurs when starting the application

**Expected behavior:** [What you expected to happen]
---
**Actual behavior:** [What actually happened]
---
**Environment details:** [OS, .NET Runtime, ...]
Win 7x64.
VS - 2017 
.NET Framework 4.6.1

### Possible Solution
---

[Optionally, share your idea to fix the issue]
---

**Code**
```
using AngleSharp.Html.Parser;

namespace rsh
{
    class Parser_test
    {
        HtmlParser domParser;
       
        public Parser_test()
        {
            domParser = new HtmlParser();
        }

    }
}
```
![2019-01-15_09-34-27](https://user-images.githubusercontent.com/18245828/51163218-0d68f500-18aa-11e9-9efe-e2b8c3f6120d.png)
![2019-01-15_09-43-20](https://user-images.githubusercontent.com/18245828/51163221-1063e580-18aa-11e9-8d9b-3c032084173d.png)

**Installation**
- [ ] I installed AngleSharp on the following principle
![mspaint_2019-01-15_10-38-22](https://user-images.githubusercontent.com/18245828/51165643-ff1ed700-18b1-11e9-9f3b-a85456dd8ff0.png)

**Comment by FlorianRappl** [comment]
I don't know your environment (I assume its .NET Framework). You guess you miss the peer dependency as stated in the error message.

This is a dup of #740.

**Comment by it19862** [comment]
@FlorianRappl 
**1.** If I understood everything correctly, I specified Wednesday in the section "Environment details: [OS, .NET Runtime, ...]"
**Question: 1.** I correctly understood the requirements for the design of the question?

For information
**2.** I created a new test project in a separate folder.
When installing the library in the "select the format of the package manager NuGet" window, I selected the "Packages.config" item
Everything is working.

**3.** I created another test project in a separate one.
When installing the library in the window "select the format of the package manager NuGet" I selected the item "PackageReference"
Everything is working.

**4.** I go to my project where the error occurred.
When I installed the library, in the "select the format of the package manager NuGet" window, I selected the "PackageReference" option
I get an error.

**Question. 2**
I apologize, but I could not figure out what to do with the link you suggested.
Could you describe in more detail how I can solve my problem?

**Comment by it19862** [comment]
@FlorianRappl 
I think I understood.
I deleted the library.
The file "AngleSharp.dll" remains in the folder ".. \ bin \ Debug \"
I registered the path to it manually.

The error remained.

I also installed "AngleSharp".
The error remained.

![devenv_2019-01-15_12-04-36](https://user-images.githubusercontent.com/18245828/51169880-1499fe00-18be-11e9-9bcc-bb38d76555fa.png)

**Comment by FlorianRappl** [comment]
You need to install the peer dependency `System.Text.Encoding.CodePages` (as the error suggested, potentially it is a language barrier; sorry for that).

**Comment by it19862** [comment]
@FlorianRappl 
How to do it ?
Or what materials to study?

I apologize, but I am an aspiring programmer.

**Comment by FlorianRappl** [comment]
Just use NuGet to manage your third-party dependencies.

See https://www.devu.com/tutorials/cs-asp/articles/lesson-66-package-management-with-nuget or any other resource (StackOverflow is your friend) if you have any issues.

I don't know how you brought AngleSharp on your machine (I guess via NuGet), but the same way should be applied to any third-party dependency.

I would love to help you more, but unfortunately my time is limited. HTH!

**Comment by it19862** [comment]
@FlorianRappl
Installed 0.9.11
No errors.

Strange.
Why problems with 0.10.01 ...
It's not a question....
I just think this information will be useful ...
Published a question on "StackOverflow"

I am sorry.
What is "HTH!"?
Are you angry at me (swearing)? ))
I apologize if the questions are not relevant to this forum.

**Comment by FlorianRappl** [comment]
[HTH = Hope that helps](https://www.urbandictionary.com/define.php?term=HTH)

I don't see any "swearing" but I have a feeling there is a language barrier at work here.

As stated AngleSharp 0.10.1 has a peer dependency (like 0.10.x) to the given package. So I wonder why you think this is a valid question or why you think any behavior of 0.9.x should be relevant to 0.10.x? Its a new major release and it is breaking (please read the migration guide). Thanks and sorry for the inconvenience!

**Comment by kpkozak** [comment]
@it19862 if you still have a problem, maybe it's because of different versions being installed and referenced. 
The easiest way will be adding binding redirect. If you're using Visual Studio, go to Package Manager console (Tools -> NuGet Package Manager -> Package Manager console), and then execute following code: 
`Get-Project -All | Add-BindingRedirect`.

Verify if there is CodePages binding redirect entry in app.config, it should look like this:
```
      <dependentAssembly>
        <assemblyIdentity name="System.Text.Encoding.CodePages" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.5.1" newVersion="4.5.1" />
      </dependentAssembly>
```
if not, add it there manually, at following node 
```
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Text.Encoding.CodePages" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.5.1" newVersion="4.5.1" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
Make sure that it redirects to proper version (in my case, `4.5.1`, the latest version).
