### ISSUE TITLE
How to use HttpClientRequester in v0.10.x?

### ISSUE THREAD

**Issue by AsValeO** [AngleSharp/AngleSharp#747]
Hello! AngleSharp is great.
How to use a HttpClientRequester in new version?
Old approach does not work anymore:

```
            var requester = new HttpClientRequester(client);
            var config = Configuration.Default.WithDefaultLoader(x =>
            {
                x.IsNavigationEnabled = true;
                x.IsResourceLoadingEnabled = true;
            }, new[] {requester});
```

**Comment by FlorianRappl** [comment]
See the [migration guide](https://github.com/AngleSharp/AngleSharp/blob/master/doc/Migration.md#configuration).

If your question is more related to AngleSharp.Io, try first registering `WithRequesters(client)` and then `WithDefaultLoader()` (no need to state the requesters explicitly). There are multiple other ways, but the described one should work fine for you.

HTH!

**Comment by FlorianRappl** [comment]
(if the migration guide is somewhat unclear / fuzzyI would appreciate if you could make a PR with some improvements to it - for me it is very difficult to see what is clear / unclear; I try my best but I keep failing...)

**Comment by AsValeO** [comment]
`WithRequesters()` now accepts `HttpClientHandler : HttpMessageHandler` as argument.
In previous versions there was a `HttpClientRequester` with `HttpClient` argument.
I need to use exactly `HttpClient` because it has configured `DefaultRequestHeaders`.

**Comment by FlorianRappl** [comment]
I think this question really goes in the direction of AngleSharp.Io - but I think you can simply do `With<IRequester>(new HttpClientRequester(client)).WithDefaultLoader(yourOptions)`.

HTH (otherwise feel free to open an issue in the AngleSharp.Io repository)!
