### ISSUE TITLE
How set cookies?

### ISSUE THREAD

**Issue by yurasakun** [AngleSharp/AngleSharp#748]
Hi, found in issue this code :

```cs
var configuration = Configuration.Default.WithDefaultLoader().WithCookies();
var cookieProvider = configuration.Services.OfType<ICookieProvider>().First();
cookieProvider.SetCookie(new Url("https://exemple.com/"), cookies);
var document = await BrowsingContext.New(configuration).OpenAsync("https://exemple.com/post");
```

But I have an error : 

> CookieException: Invalid part "Domain"="exemple.com" file cookie

What am I doing wrong?

**Comment by FlorianRappl** [comment]
Can you post what is "cookies"? Also what is the set-cookie header of the response?

A few  more details are necessary to start investigating. Thanks!
