### ISSUE TITLE
System.NullReferenceException when parsing a <link> tag

### ISSUE THREAD

**Issue by bdbai** [AngleSharp/AngleSharp#753]
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp? (0.10.1)
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Description

When parsing a HTML document with a `<link>` tag using `AngleSharp.Html.Parser.ParseDocumentAsync`, a `System.NullReferenceException` is thrown.

```c#
using AngleSharp.Html.Parser;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;

namespace App1
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        private async void Page_Loaded (object sender, RoutedEventArgs e)
        {
            var content = "<!DOCTYPE html>\n<html>\n<head>\n<link href=\"/style.css\" rel=\"stylesheet\" />\n\n</head></html>";
            var parser = new HtmlParser();
            var doc = await parser.ParseDocumentAsync(content);
        }
    }
}
```

### Steps to Reproduce

1. Create a new Universal Windows App.
2. Add `AngleSharp` NuGet package.
3. Enter the code above in `MainPage.xaml.cs`.
4. Run the app in Debug mode.

**Expected behavior:** [What you expected to happen]
Only `System.ArgumentException` is thrown due to #326 .

**Actual behavior:** [What actually happened]
Both `System.ArgumentException` (due to #326 ) and `System.NullReferenceException` (this issue is for) are thrown.

The app does not crash though.

**Environment details:** [OS, .NET Runtime, ...]
Windows 10 10.0.17763.253
`Microsoft.NETCore.UniversalWindowsPlatform` 6.2.2 installed

### Possible Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Thanks for the report - I'll look into it!

**Comment by FlorianRappl** [comment]
Hi @bdbai I tried to reproduce your issue, but unfortunately for me your code above passes.

If you can try to come up with another MWE to reproduce your issue it would be nice, otherwise the issue must lie somewhere else.

**Comment by bdbai** [comment]
When the CSS url is not complete, its content cannot be downloaded. Therefore in [AngleSharp.Io.Processors.StyleSheetRequestProcessor.ProcessAsync](https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Io/Processors/StyleSheetRequestProcessor.cs#L63) , a `null` value is returned.

```c#
        public override Task ProcessAsync(ResourceRequest request)
        {
            if (IsAvailable && Engine != null && IsDifferentToCurrentDownloadUrl(request.Target))
            {
                CancelDownload();
                Download = DownloadWithCors(new CorsRequest(request)
                {
                    Setting = _link.CrossOrigin.ToEnum(CorsSetting.None),
                    Behavior = OriginBehavior.Taint,
                    Integrity = _context.GetProvider<IIntegrityProvider>()
                });
                return FinishDownloadAsync();
            }

            return null;
        }
```

Later in [AngleSharp.Html.LinkRels.StyleSheetLinkRelation.LoadAsync](https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Html/LinkRels/StyleSheetLinkRelation.cs#L32) , this `null` value is `await`ed and a `NullReferenceException` is thrown.

```c#
        public override async Task LoadAsync()
        {
            if (Url != null)
            {
                var request = Link.CreateRequestFor(Url);
                await Processor?.ProcessAsync(request);
            }
        }
```

I suggest using a `Task.Completed` as the return value. A PR will be proposed later.

**Comment by FlorianRappl** [comment]
@bdbai again my test with exactly your code did not fail. Therefore, something else seems to be going on (with the provided code also no requester is set up hence I am not sure why the code seen should be triggered at all).

Please provide first a test (that fails/ shows the issue) to reproduce your issue. You can do that in the PR as well (would be much appreciated as the PR would then also solve / successfully pass the test).

**Comment by bdbai** [comment]
A MWE is available [here](https://github.com/bdbai/AngleSharp/blob/issue-753/src/test/Program.cs) , please kindly check it out.

Since the exception does not propagate outside AngleSharp, the code should run and yield an expected result, only leaving a message saying `A first chance exception of type 'System.NullReferenceException occurred in mscorlib.dll` in Output window.
To find out where the exception is thrown, please go to `Exception Settings` -> `Break When Thrown` and enable `Common Language Runtime exceptions` -> `System.NullReferenceException` .

**Comment by FlorianRappl** [comment]
Cool 😎 - makes sense now @bdbai. Thanks for the explanation!

**Comment by bdbai** [comment]
Thanks too! Then this issue can be closed 😁
