### ISSUE TITLE
How do I parse the css with the html document

### ISSUE THREAD

**Issue by jl-rey** [AngleSharp/AngleSharp#757]
# Issue Templates

Please use one of the following templates to create your issue:

- [BUG REPORT](https://github.com/AngleSharp/AngleSharp/issues/new?template=bugs.md)
- [FEATURE PROPOSAL](https://github.com/AngleSharp/AngleSharp/issues/new?template=features.md)

**Comment by jl-rey** [comment]
Hello:

This is a documentation issue more than anything else.

I could not find documentation on how to access the css style sheets.
In Searching I found this https://stackoverflow.com/questions/41432540/how-to-get-css-properties-from-a-parsed-html-element-using-anglesharp

That said to do the following:

```
var config = Configuration.Default.WithDefaultLoader().WithCss();
var context = BrowsingContext.New(config);
var document = context.OpenAsync("http://localhost/test.html").Result;
var element = document.QuerySelector("span.foo");
var style = document.DefaultView.GetComputedStyle(element);
var size = style.BackgroundSize;`

```
I noticed that this reply is dated Dec 2017
I have Version 
```
var config = Configuration.Default.WithDefaultLoader().WithCss();
```

I get the following error.
CS1061	'IConfiguration' does not contain a definition for 'WithCss' and no extension method 'WithCss' accepting a first argument of type 'IConfiguration' could be found (are you missing a using directive or an assembly reference?)	

Searching the code I do not find that or anything that refers to css.

If there are some working examples please point me in that direction.

**Comment by jl-rey** [comment]
Did not mean to close.

**Comment by jl-rey** [comment]
Exploring further:

Attempting reading the file using a url I have a function to read.

```
        public void readDocWithUrl(string url)
        {
            var config = Configuration.Default.WithDefaultLoader();
            var context = BrowsingContext.New(config);
            var readcontext = context.OpenAsync(url);

            var document = readcontext.Result;
        }
```
The readcontext is is a Status of "WaitingForActivation'
The Result == null

**Where do I find something that works?**

**Comment by FlorianRappl** [comment]
I am not sure what you mean with

> Where do I find something that works?

This is a .NET library. The users need to have some knowledge of .NET (e.g., what is a `Task`) and should  be familiar with C# (e.g., how to use `async` / `await`). We cannot guide you through this.

As far as the CSS question is concerned - the SO answer is (as you pointed out) outdated and refers to an earlier version. The CSS part was extracted to its [own library](https://github.com/AngleSharp/AngleSharp.Css) and works differently now.

See the very big warning in the [README](https://github.com/AngleSharp/AngleSharp/blob/master/README.md) and the [migration guide](https://github.com/AngleSharp/AngleSharp/blob/master/doc/Migration.md) in the [documentation](https://github.com/AngleSharp/AngleSharp/blob/master/doc/index.md).

HTH!

**Comment by jl-rey** [comment]
Thanks for the reply I was indeed fooled by the await statement.
I will look for the into the migration guide.
The documentation is badly needed.
Don't forget to do namesapce and class documentation also.
I might be willing to help with the documentation.
