### ISSUE TITLE
xmlns:xlink attribute parse problem when there are multiple xmlns

### ISSUE THREAD

**Issue by dabutvin** [AngleSharp/AngleSharp#760]
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

### Description

An attribute name with a namespace prefix gets dropped when there are multiple namespaces.
This is a fairly common scenario for an SVG.

I have a failing unit test setup here: https://github.com/AngleSharp/AngleSharp/compare/master...dabutvin:namespace-prefixes?expand=1

### Steps to Reproduce

setup:

```cs
 var doc = (@"<!DOCTYPE html>
        <svg xmlns=http://www.w3.org/2000/svg xmlns:xlink=http://www.w3.org/1999/xlink>
        </svg>").ToHtmlDocument();

var svg = body.FirstElementChild;
Console.WriteLine(svg.ToHtml());
```

**Expected behavior:** 

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"></svg>
```

**Actual behavior:** 

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:="http://www.w3.org/1999/xlink"></svg>
```

**Environment details:**

OSX .NET Core 2.2

### Possible Solution

I believe the issue is happening in `ParseDocument()`
This attribute gets marked as having a namespace `XmlNsUri` instead of `XLinkUri` from [NamespaceNames](https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Dom/NamespaceNames.cs) because of the preceding attribute.

I wanted to reach out before I went to deep trying to understand in case you had any insight.

Thanks!

**Comment by FlorianRappl** [comment]
Hi @dabutvin thanks for reporting this issue. I'll try to release a fix ASAP.

(the unit test is really appreciated :beers:!)

**Comment by dabutvin** [comment]
that's great! thanks so much. Let me know if there is anything I can do to help. 
It sounds like you already have a hunch on how to fix?

**Comment by FlorianRappl** [comment]
Landed in `devel`.

**Comment by dabutvin** [comment]
:+1: :+1:
