### ISSUE TITLE
 [BUG REPORT] - Inner/Outer Html text lowercase problem

### ISSUE THREAD

**Issue by MasallahOZEN** [AngleSharp/AngleSharp#765]
Hi, how can I solve this problem?

Parsing document code block:
![image](https://user-images.githubusercontent.com/811777/53880646-8ec74300-4022-11e9-9986-226d6f094246.png)

Problem:
![image](https://user-images.githubusercontent.com/811777/53881454-cafba300-4024-11e9-91fd-b6ce9c893120.png)

Best Regards,

**Comment by FlorianRappl** [comment]
You have two different things here. The Angular template is not parsed using HTML5 but with Angular's own parser (yes, this is similar to HTML(5), but there are key differences - handling of attributes is one of them). HTML5 only knows lowercase attributes (see specification) and transforms all attributes to lowercase.

If you want to convince yourself try the following in your favorite browser:

```html
<!DOCTYPE html>
<h1 my-Custom-Foo>This is a Heading</h1>
<script>
alert(document.querySelector("h1").attributes[0].name);
</script>
```

You will get back the following:

![image](https://user-images.githubusercontent.com/1766191/53883445-50795600-4019-11e9-9021-588fcbfbd996.png)

**Remark**: As specified in the issue template please first make sure you have correctly identified a bug. Not everyone is a spec expert, but at least trying to run the sample in *any* browser would give you a good hint.

HTH!

**Comment by MasallahOZEN** [comment]
Thnx for quick response.
