### ISSUE TITLE
Span is reported as "The tag has been closed unexpectedly."

### ISSUE THREAD

**Issue by Suchiman** [AngleSharp/AngleSharp#77]
Following code

``` csharp
DocumentBuilder.Html(@"<!DOCTYPE html><html><head></head><body><span>test</span></body></html>"); 
```

will generate a HtmlParseErrorEvent stating:
`(Ln 1, Col 57): The tag has been closed unexpectedly.`

This seems to be caused by a check in [HtmlParser.cs Line 3073](https://github.com/FlorianRappl/AngleSharp/blob/af821e855282559bfd898ae5cd45911e21abd761/AngleSharp/Parser/Html/HtmlParser.cs#L3073) where it looks like it should have been `if (node.LocalName != tag.Name)` instead of `if (node.LocalName == tag.Name)`

**Comment by FlorianRappl** [comment]
I'm on it.

Seems like you are right: "If the tag name of the end tag token does not match the tag name of the current node, this is a parse error." in "Any other end tag" of sec. 8.2.5.10 of the HTML 5.1 specification.

Thanks for pointing that out!
