### ISSUE TITLE
Request WithCookies throws "Invalid URI: The Uri string is too long." exception

### ISSUE THREAD

**Issue by igor-olikh** [AngleSharp/AngleSharp#770]
### Prerequisites

- [yes ] Are you running the latest version of AngleSharp?
- [ yes] Did you check the FAQs to see if that helps you?
- [ looks so] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [yes ] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Description

I get "Invalid URI: The Uri string is too long." exception only when I add WithCookies() to the configuration.

### Steps to Reproduce

                var imageLoaderService = new PlainImageResourceService();
                var loaderOptions = new LoaderOptions { IsResourceLoadingEnabled = true };
                var config = Configuration.Default.WithDefaultLoader(loaderOptions)
                    .With(imageLoaderService)
                    .WithCookies()
                    .With(requester);

                var document = await BrowsingContext.New(config).OpenAsync(address);

**Expected behavior:** to get a response

**Actual behavior:** I get "Invalid URI: The Uri string is too long." exception

**Environment details:** Windows, .NET 4.7.1

**Comment by igor-olikh** [comment]
sealed class PlainImageResourceService : IResourceService<IImageInfo>
    {
        public Boolean SupportsType(String type)
        {
            return type == "image/jpeg";
        }

        public async Task<IImageInfo> CreateAsync(IResponse response, CancellationToken token)
        {
            try
            {
                var captchaUrl = "https://harb.cma.gov.il/BotDetectCaptcha.ashx?get=image";

                if (response.Address.Href.StartsWith(captchaUrl))
                {
                    var directoryName = AppDomain.CurrentDomain.SetupInformation.ApplicationBase;

                    LoggerManager.Debug($"directoryName: ({directoryName}).");

                    var target = Path.Combine(directoryName, "images", Guid.NewGuid() + ".jpeg");

                    using (var fs = File.Create(target))
                    {
                        await response.Content.CopyToAsync(fs);
                    }
                }

                return new ImageInfo { Source = response.Address, Width = 0, Height = 0 };
            }
            catch (Exception e)
            {
                LoggerManager.Error("CreateAsync", e);
                throw;
            }
            
        }
    }

    sealed class ImageInfo : IImageInfo
    {
        public int Width { get; set; }

        public int Height { get; set; }

        public Url Source { get; set; }
    }

**Comment by FlorianRappl** [comment]
Difficult to reproduce (especially with a website as MWE - would be good not to rely on external resources). I guess I see the issue, but it will be hard to circumvent with the standard `CookieContainer`. 

There are many issues with this .NET class and like with `Uri` I guess the only sane answer is to re-implement it in AngleSharp, however, I do not see this in the core, but rather in, e.g., `AngleSharp.Io`.

I'll try to come up with a solution - if you have a good idea any contribution (e.g., a PR) would be welcome! Thanks!

**Comment by FlorianRappl** [comment]
I actually do not think that cookie is to blame here.

The max length of an URI seems to be 2083 characters when being used by the `HttpClient`.  The `Uri` class in dotnet does not care at all.

I tested the following code:

```cs
"https://foo.com/" + new String(Enumerable.Repeat('a', 15000).ToArray()) + "?a=b"
```

works like a charm. So I think more information is needed on *where* exactly your problem occurs and *what* part of AngleSharp (if any) is throwing. I think that the bug is only triggered when cookies are used may be a side-effect of your flow (e.g., the page behaving differently and using some redirect / other paths). But that's all just guess-work.

We need a real MWE here that does not feature some live website somewhere with lots of custom code around it.

**Comment by FlorianRappl** [comment]
Ping @igoro1975 .
