### ISSUE TITLE
Getting started example issues

### ISSUE THREAD

**Issue by nhaskins** [AngleSharp/AngleSharp#771]
New to AngleSharp, I tried the 'get started example' and ran into problems:

https://github.com/AngleSharp/AngleSharp/blob/master/doc/Basics.md

To get this example working, I had to do the following:

- add 'using AngleSharp.Html.Parser'
- change parser.Parser to  parser.ParseDocument

**Comment by FlorianRappl** [comment]
Yep that document is mostly historical (but that does not mean it should stay outdated). Great finding - thanks for reporting :beers:!

I'll mark it as a documentation bug - if you want to you can make a PR correcting it (would be appreciated!). If you find anything else that is outdated or needs more clarification please post it (either here or in a new thread). Thanks!

**Comment by FlorianRappl** [comment]
Landed in `devel`.
