### ISSUE TITLE
Perform click action 

### ISSUE THREAD

**Issue by irfan-yusanif** [AngleSharp/AngleSharp#773]
Hi,
I could not find example of performing a click on a query selector (not on achor tag) and then getting data populated on page after that click.

Here is the sample url : https://www.olx.com.pk/item/pedestal-fan-iid-1004439258 
after page is loaded perform click: $("._2pbD3").click()
and finally get data after click: $("._1spGJ").textContent

**Comment by FlorianRappl** [comment]
The only thing you can click with AngleSharp (non-JS) is everything that has an anchor (the link will be followed) or submit buttons (the form will be submitted). If, e.g, we have a div that has a click handler defined in JS nothing would come out.

HTH!

**Comment by FlorianRappl** [comment]
Landed in `devel`.
