### ISSUE TITLE
AngleSharp in Unity, 'CodePagesEncodingProvider' 

### ISSUE THREAD

**Issue by PCoelho** [AngleSharp/AngleSharp#774]
I'm trying to use this with Unity (2018.3.6f1) on the _.NET 4.x runtime_. I'm getting an error:

`Assets\AngleSharp-master\src\AngleSharp\Browser\EncodingMetaHandler.cs(20,39): error CS0103: The name 'CodePagesEncodingProvider' does not exist in the current context`

Seems that System.Text.Encoding doesn't exist? I feel like I'm having issues with .NET versioning.

Can someone help?
Thanks!

**Comment by PCoelho** [comment]
I managed to make it work in windows by including AngleSharp-master\src\AngleSharp\bin\Debug\net46\System.Text.Encoding.CodePages.dll into the scene. But fails when I run the scene in Android.

**Comment by FlorianRappl** [comment]
Which version of AngleSharp? The latest version(s) do not target .NET 4.x anymore, but require at least .NET 4.6.

**Comment by PCoelho** [comment]
I took the latest from the AngleSharp Git repo. The description says it supports Unity (2018.1). Is that still the case?

**Comment by FlorianRappl** [comment]
It should be - the Unity information is taken from https://docs.microsoft.com/de-de/dotnet/standard/net-standard (matching our supported .NET Standard version).

So if you Unity version matches we need to find what is resolved by NuGet on installation. The `CodePagesEncodingProvider` comes from a dependency that should be available at least via a dependency (System.Text.Encoding.CodePages) (hence the reason it works on Windows when you add this manually; maybe the given dependency does not exist for *all* target platforms, e.g., Android). Strange that .NET Standard claims compatibility then...

Unfortunately, I have no real knowledge on Unity / the eco-system to know what could be the underlying (or known) issue here. I can just do guess work

**Comment by PCoelho** [comment]
I tried using the NuGet installed on a vanilla VS project and it works as expected. But, not playing well with unity. 

Installing NuGet packages through VS while with a unity project open, makes VS display no errors. However, unity can't recognize those classes. There is a NuGet package manager I use with unity (NuGet For Unity), but AngleSharp doesn't work with that one.

**Comment by FlorianRappl** [comment]
> There is a NuGet package manager I use with unity (NuGet For Unity), but AngleSharp doesn't work with that one.

What exactly is the problem here (any error output)? This seems to be more a problem of the tooling (NuGet for Unity) than AngleSharp. AngleSharp is using a very standard NuGet package spec, no post-install or any special things added. Maybe we can figure out what's going wrong and improve the NuGet spec to also work nicely in this situation (any help appreciated).

**Comment by PCoelho** [comment]
I can help you by testing things on my side, but honestly not familiar with managing packages at all. 
There is no error when I use the NuGet package manager in unity. It won't recognize any of the classes and creates this structure in the unity Assets folder:
```
AngleSharp.0.11.0/
├── lib/
│   ├── [nothing inside this folder]
├── AngleSharp.0.11.0.nupkg
```

The nupkg file is binary.

**Comment by FlorianRappl** [comment]
A NuGet package is just a ZIP archive that contains a bunch of files described in an XML file contained the archive.

From the given UI representation I assume it does not know what to do with the NuGet, potentially there is a target mismatch.

According to [this StackOverflow answer](https://stackoverflow.com/questions/53447595/nuget-packages-in-unity) this behavior is known and the advised approach is to use VS for installing the NuGet (which resolves the .NET Standard 2.0 dependency as it should be). Maybe this helps?

**Comment by PCoelho** [comment]
Ok, that was exactly it. It even works in Android! For the record here's how I did it:

1. Get the AngleSharp NuGet package from the VS NuGet Package manager.
2. Build the solution (Build -> Build Solution)
3. Copy the "netstandard2.0" folder into the unity Assets folder. You can find it in "[your project]\Packages\AngleSharp.0.11.0". Version may vary.

Thanks for the help Florian :)

**Comment by FlorianRappl** [comment]
Awesome thanks for the help! I'll include this in the documentation.

**Comment by FlorianRappl** [comment]
(Re-open until I've added it)

**Comment by FlorianRappl** [comment]
Landed in `devel`.
