### ISSUE TITLE
CssParser ParseSelector?

### ISSUE THREAD

**Issue by VoidMonk** [AngleSharp/AngleSharp#776]
Hi, I'm upgrading some code from `AngleSharp` v0.9.x to v0.11. Earlier we could do:

```csharp
CssParser parser = new CssParser();
ISelector selector = parser.ParseSelector("p > a");
```
But now it looks like `CssParser` is not part of the core lib, so is the `ParseSelector` method still available in the core lib, or do I need `AngleSharp.Css`, and how will the above code change?

**Comment by FlorianRappl** [comment]
Good question - yes, the CSS part was extracted out (see https://github.com/AngleSharp/AngleSharp/blob/master/doc/Migration.md).

I guess the use of the query selector parsing is not mentioned there.

What you can do is:

```cs
// use any config; important - either inherits from default
// or has an ICssSelectorParser registered ...
var config = Configuration.Default;

// use the consuming (or a new) context
var context = BrowsingContext.New(config);

// get the registered parser instance
var parser = context.GetService<ICssSelectorParser>();

// use as before
var selector = parser.ParseSelector("foo");
```

I'll mark this as improvement for the migration doc (any contribution there welcome, too).

**Comment by VoidMonk** [comment]
Thank you.

While trying a few things, I noticed that this seems to work too:

```csharp
CssSelectorParser parser = new CssSelectorParser();
ISelector selector = parser.ParseSelector("p > a");
```
Any reason not to use `CssSelectorParser` directly?

**Comment by FlorianRappl** [comment]
Because it may depend on other things coming from `context`. Also implementation of this (constructor) may change, but the interface is there for you. As long as you do not depend on the specific implementation details it always makes sense to go for the abstraction (plus in your code you can easily mock it, e.g., for unit testing).

I could also ask "why not use the interface"? :)

**Comment by FlorianRappl** [comment]
Landed in `devel`.
