### ISSUE TITLE
What's the proper way to create element from string?

### ISSUE THREAD

**Issue by FikretSanda** [AngleSharp/AngleSharp#778]
I want to create an element like the following:

```
<a class="macmillan" href="sound://sndaaa.spx">
    <img src="macmillan.png">
</a>
```

I know I can use `createElement` and `setAttribute` methods to it. However, I want to know is there an easy way to create this directly from the string. Thanks.

**Comment by FlorianRappl** [comment]
You can use a document fragment and innerHTML.
