### ISSUE TITLE
Url.Origin just returning Protocol

### ISSUE THREAD

**Issue by Suchiman** [AngleSharp/AngleSharp#78]
While having a look at the `DocumentLoader` i've noticed that `data.Headers[HeaderNames.Referer] = request.Origin` is always just `http:` or `https:`.
Comparing AngleSharps.Location to the Browsers document.location it seems that Origin is wrong.

| Key | Browser | AngleSharp |
| --- | --- | --- |
| hash | "" | "" |
| host | "github.com" | "github.com" |
| hostname | "github.com" | "github.com" |
| href | "https://github.com/FlorianRappl/AngleSharp" | "https://github.com/FlorianRappl/AngleSharp" |
| **_origin**_ | **_"https://github.com"**_ | **_"https:"**_ |
| pathname | "/FlorianRappl/AngleSharp" | "/FlorianRappl/AngleSharp" |
| port | "" | "" |
| protocol | "https:" | "https:" |
| search | "" | "" |

P.S.: Is it correct that Origin is set for Referer and not Href?

**Comment by FlorianRappl** [comment]
Hm. I think that depends on the context - but right now always `Origin` is used. I'll need to take a look, but in general `Href` should be used, yes.

The other issue is a bug - I think the origin should be everything until the path (hence excluding path, hash and search). Thanks for noticing.

**Comment by FlorianRappl** [comment]
Alright - for the `DocumentLoader` all cases have been converted to `Href`. That was actually a mistake. The `ResourceLoader` is different here. Should be all corrected now. Thanks again for spotting this!
