### ISSUE TITLE
IHtmlFormElement.GetSubmission returns a GET DocumentRequest despite <form method="post">

### ISSUE THREAD

**Issue by daiplusplus** [AngleSharp/AngleSharp#780]
### Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
    * AngleSharp 0.11.0
    * AngleSharp.Io 0.10.1

- [ ] Did you check the FAQs to see if that helps you?
    * No. No link to an FAQ is provided in the GitHub project root or readme.
    * Googling for "anglesharp faq" returns third-party webpages with outdated information (e.g. from 2015 and 2016). AngleSharp changed its API design significantly in recent years rendering most existing documentation obsolete.

- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
    * Yes, I believe so

- [x] Did you perform a search in the issues?
    * Yes. I searched for variations of "form GetSubmission", "DocumentRequest GetSubmission" and "form wrong method".

For more information, see the `CONTRIBUTING` guide.

### Description

* This is inside an XUnit test for an ASP.NET Core 2.2 web-application. 
* I'm loading a HTML form with content like this (simplified for brevity

         
        <form method="post" id="registrationForm" action="/register">

		<div class="field">
			<label for="TenantName" class="is-required">Company name</label>
			<input autocomplete="organization" placeholder="Amazing Company LLC" type="text" id="TenantName" name="TenantName" value="" />
			<span></span>
		</div>

		<div class="field">
			<label for="DisplayName" class="is-required">Your name</label>
			<input autocomplete="name" placeholder="John Smith" type="text" id="DisplayName" name="DisplayName" value="" />
			<span></span>
		</div>

         

        </form>
         

* The document is requested and loaded like so:

			IBrowsingContext ctx = BrowsingContext.New();
			using( HttpClient client = this.factory.CreateClient() )
			using( HttpResponseMessage getResponse = await client.GetAsync( "/register" ) )
			using( Stream getResponseStream = await getResponse.Content.ReadAsStreamAsync() )
			{
				// Assert:

				getResponse.EnsureSuccessStatusCode(); // Status Code 200-299
				Assert.Equal( "text/html; charset=utf-8", getResponse.Content.Headers.ContentType.ToString() );

				HtmlParser htmlParser = new HtmlParser();
				IHtmlDocument html = await htmlParser.ParseDocumentAsync( getResponseStream );

				IHtmlFormElement registrationForm = html.Forms.Single();

				////////////
				
				Dictionary<String,String> sampleValues = new Dictionary<String,String>()
				{
					{ nameof(RegistrationViewModel.TenantName), "New Test Tenant" },
					{ nameof(RegistrationViewModel.DisplayName), "New Test User" },
                                        // etc...
                                } // dict

                                using( HttpResponseMessage postResponse = await client.SendFormAsync( form: registrationForm, submitButton: submitButton, formValues: sampleValues ) )
				{
					postResponse.EnsureSuccessStatusCode();
                                }
                        } // using

* The `SendFormAsync` extension method is defined like so:

		public static Task<HttpResponseMessage> SendFormAsync
		(
			this HttpClient client,
			IHtmlFormElement form,
			IHtmlElement submitButton,
			IEnumerable<KeyValuePair<String,String>> formValues
		)
		{
			foreach( KeyValuePair<String,String> kvp in formValues )
			{
				IElement elementForFormName = form[ kvp.Key ];
				if( elementForFormName is IHtmlInputElement inputElement )
				{
					IHtmlInputElement element = Assert.IsAssignableFrom<IHtmlInputElement>( inputElement );
					element.Value = kvp.Value;
				}
				else if( elementForFormName is IHtmlTextAreaElement textAreaElement )
				{
					IHtmlTextAreaElement element = Assert.IsAssignableFrom<IHtmlTextAreaElement>( textAreaElement );
					element.Value = kvp.Value;
				}
				else if( elementForFormName is IHtmlButtonElement buttonElement )
				{
					IHtmlButtonElement element = Assert.IsAssignableFrom<IHtmlButtonElement>( buttonElement );
					element.Value = kvp.Value;
				}
				else
				{
					// Throw? Any element types I'm forgetting about?
				}
			}

			DocumentRequest formSubmission = form.GetSubmission( submitButton );
			Uri formTargetUri = (Uri)formSubmission.Target;

			if( submitButton.HasAttribute( "formaction" ) )
			{
				String formAction = submitButton.GetAttribute("formaction");
				Assert.True( Uri.TryCreate( formAction, UriKind.RelativeOrAbsolute, out Uri formActionUri ), userMessage: "Assert that the formaction=\"\" attribute is valid" );

				if( formActionUri.IsAbsoluteUri )
				{
					formTargetUri = formActionUri;
				}
				else
				{
					formTargetUri = new Uri( baseUri: client.BaseAddress, relativeUri: formActionUri );
				}
			}
			else
			{
				formTargetUri = new Uri( baseUri: client.BaseAddress, relativeUri: formTargetUri.PathAndQuery );
			}

			HttpRequestMessage submision = new HttpRequestMessage( method: new HttpMethod( formSubmission.Method.ToString().ToUpperInvariant() ), requestUri: formTargetUri )
			{
				Content = new StreamContent( formSubmission.Body )
			};

			foreach( KeyValuePair<String,String> header in formSubmission.Headers )
			{
				submision.Headers.TryAddWithoutValidation( header.Key, header.Value );
				submision.Content.Headers.TryAddWithoutValidation( header.Key, header.Value );
			}

			return client.SendAsync( submision );
		}

**Expected behavior:** [What you expected to happen]

The `client.SendAsync` call at the bottom resulted in a `GET` request where all of the form fields were provided as querystring parameters with an empty HTTP request body instead of as a `POST` request with the form fields in the body.

I noticed that the cause is on this line:

    DocumentRequest formSubmission = form.GetSubmission( submitButton );

The `formSubmission` object here has the wrong Method and has an empty request body and all the form fields are querystrings.

When I debug it, the `IHtmlFormElement form` object it has `.Method = "post"`. The `submitButton` does not have any attributes (like `formaction=""`) that would interfere with the form submission process. The form itself is submitted correctly in a desktop browser.

Why is `form.GetSubmission` ignoring the attributes on the `<form>`?

**Comment by FlorianRappl** [comment]
> Why is `form.GetSubmission` ignoring the attributes on the `<form>`?

I don't know but I'll find out :)

On a sidenote I do not understand the `SendFormAsync` method - I think you could potentially be better off using a `SubmitAsync` extension method (there are ones that accept, e.g., an anonymous object, or a dict, or ... - from what I see they do exactly what you do / need to do - just with more edge cases in mind). I'm not sure though.

**Comment by FlorianRappl** [comment]
Alright so I added some tests and everything is fine in AngleSharp. I inspected your code and apparently you do not set the URL of your document (you are using the `HtmlParser` and not the `BrowsingContext`, which is advised for anything that goes beyond parsing, e.g., dynamic DOM handling) - the standard URL as per W3C spec is `about:blank`.

By W3C spec the form method is only considered for `http` and `https` URLs. In this case a generic backup case is performed as `about` is not specifically handled.

Here is just one of the tests:

```cs
var config = Configuration.Default;
var context = BrowsingContext.New(config);
var content = "<form method=post><input name=a value=foo><input name=b value=bar></form>";
var document = await context.OpenAsync(req => req.Content(content).Address("http://example.com"));
var form = document.Forms[0];
var documentRequest = form.GetSubmission();

Assert.AreEqual(HttpMethod.Post, documentRequest.Method);
Assert.AreEqual("", documentRequest.Target.Href.Substring(document.Url.Length));
Assert.AreEqual("a=foo&b=bar", GetText(documentRequest.Body));
```
