### ISSUE TITLE
span class

### ISSUE THREAD

**Issue by ghost** [AngleSharp/AngleSharp#781]
Hey 
how i can get a names from span classes?

 <span shard-type=**"diamond"**>.....</span>
 <span shard-type="**heart"**>.....</span>

there's my current code and i don't know what to put in instead of **span**
`var bonuses = container.QuerySelectorAll(".new-runes__bonuses > .new-runes__shards > **span**")  `

**Comment by FlorianRappl** [comment]
I guess this is more a general HTML/CSS question than one for AngleSharp.

If I understand correctly you are after selecting a span like the one above? Just selecting an element is `span`, if you have a CSS class you can additionally add it (`span.foo` for a class `foo` or `span.foo.bar` if you have two classes `foo` and `bar`). Generically, for any attribute the attribute selector exists `[attrname=attrvalue]`, where `=` may also be one of many potential operators. Combining this with the element selector you get, e.g., `span[shard-type=diamond]`.

Your selector thus may look like

```cs
var bonuses = container.QuerySelectorAll(".new-runes__bonuses > .new-runes__shards > span[shard-type=diamond]");
```

HTH!
