### ISSUE TITLE
Creating a selector for the element

### ISSUE THREAD

**Issue by lvkins** [AngleSharp/AngleSharp#784]
Does AngleSharp make it able to create a selector for a certain node?

Consider this example:

```
<html>
	<body>
	<div id="header">
		<span class="decorator">Logo</span>
	</div>
	<div id="container">
		<div>
			<h1>This is a test</h1>
		</div>
                <div>...</div>
	</div>
	</body>
</html>
```

`selectedElement` points to `<h1>` node in the above HTML.

When called:
`selectedElement.CreateSelector();`

Sample output would be the element selector:
`body > div > div:nth-child(1) > h1`

I have slightly browsed the source code, but wasn't able to find anything for it. I would like be sure however, before making any efforts to implement it myself.

Regards
Lucas

**Comment by FlorianRappl** [comment]
Right now there is no such thing - so any contribution in that direction would be much appreciated!

**Comment by lvkins** [comment]
I have worked in this area and made this little extension that looks like something 😉. It took me a while to learn some of the huge API, so let me know if anything can be improved.

Feel free to test it. 

```
/// <summary>
/// Creates a unique selector path used to locate the element in the DOM.
/// </summary>
/// <param name="node">The starting node to create the selector path from.</param>
/// <returns>The unique selector path for this element.</returns>
public static string GetSelector(this IElement node)
{
	// Initialize path
	var path = string.Empty;

	// If the current node is having an unique id property
	var hasId = false;

	do
	{
		// Set if node has id attribute set...
		hasId = !string.IsNullOrEmpty(node.Id);

		// Get parent element of the node
		var parent = node.ParentElement;

		// Always lowercase node name in the path
		var name = node.NodeName.ToLowerInvariant();

		// If node has id attribute...
		if (hasId)
		{
			// Id is unique in the DOM, so we can use it to locate the element and skip other parents
			name = "#" + node.Id;
		}
		// If node has siblings of the same type...
		else if (parent != null && !node.IsOnlyOfType())
		{
			// Get node index in the parent node tree
			var index = parent.Children.Where(_ => _.GetType() == node.GetType()).Index(node);

			// Append nth child selector
			name += $":nth-child({index + 1})";
		}

		// Set current parent
		node = parent;

		// Recreate selector path
		path = name + (!string.IsNullOrEmpty(path) ? ">" + path : "");
	} while (node?.ParentElement != null && !hasId);

	// Return generated selector
	return path;
}
```
Worked fine test parsing the top give www giants. 

---

Let me know if I should create a pull request.

**Comment by FlorianRappl** [comment]
Hi @lvkins looks great - yes a PR would be much appreciated 👍 !

**Comment by FlorianRappl** [comment]
(I've added it to the v0.12 milestone as I think we can still make it until Thursday.)

**Comment by cmxl** [comment]
> Sample output would be the element selector:
> `body > div > div:nth-child(1) > h1`

@lvkins, your implementation does create the following:
`body > #container > div:nth-child(1) > h1`
Right?

Just wanted to make sure.

**Comment by FlorianRappl** [comment]
I think it stops when the first id selector is hit, e.g.,

```
#container > div:nth-child(1) > h1
```

but yes - that's also how I see it.

**Comment by lvkins** [comment]
@cmxl Since id selector is unique, it will do just what @FlorianRappl said. This is perfectly valid.

**Comment by FlorianRappl** [comment]
Landed in `devel`!
