### ISSUE TITLE
System.TypeInitializationException windowsphone 8.1

### ISSUE THREAD

**Issue by geralexgr** [AngleSharp/AngleSharp#79]
I have a problem. The code runs on windows 8.1 app , but not on windowsphone 8.1

```
        var http = new HttpClient();
        var request = await http.GetAsync(cineUrl);
        var response = await request.Content.ReadAsStreamAsync();
        var document = DocumentBuilder.Html(response);
        var alist = document.All.Where(m => m.LocalName == "p");
        var blist = document.QuerySelectorAll("*").Where(m => m.LocalName == "a");
```

An exception of type 'System.TypeInitializationException' occurred in AngleSharp.DLL but was not handled in user code

{System.ArgumentException: 'euc-jp' is not a supported encoding name.
Parameter name: name
   at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at AngleSharp.TextEncoding..cctor()}

**Comment by FlorianRappl** [comment]
Hm a similar bug occurred in a previous version so I know the problem. I think I can fix it!

**Comment by FlorianRappl** [comment]
I also updated the NuGet package.

**Comment by geralexgr** [comment]
The bug is fixed, but on windows i get some AngleSharp.Dom.Html.HtmlAnchorElement results in a collection and on windowsphone nothing is returned. (with the code above and the same url for boh applications)

**Comment by FlorianRappl** [comment]
Does the bug (no result) also occur if you use the following code instead?

```
    var config = new Configuration().WithDefaultLoader();
    var document = await BrowsingContext.New(config).OpenAsync(cineUrl);
    var alist = document.QuerySelectorAll("p");
    var blist = document.QuerySelectorAll("a");
```

(I've replace the last two lines with a better approach - but these two shouldn't be the problem)

**Comment by geralexgr** [comment]
Couldn't use because of invalid arguments.
    var config = new Configuration().WithDefaultLoader();
    var document = await BrowsingContext.New(config).OpenAsync(cineUrl);

But those 2 lines work and  return result on windowsphone and windows.

```
var alist = document.QuerySelectorAll("p");
var blist = document.QuerySelectorAll("a");
```

On windowsphone something is wrong with the linq syntax maybe

**Comment by FlorianRappl** [comment]
Hm I will investigate this. Seems odd, but there must be a reason for this.

One question though to the invalid arguments: Where is the problem exactly? Maybe using `Url.Create(cineUrl)` instead of `cineUrl` helps? (I wasn't sure about the type of `cineUrl`, but if its a string that works, if its an `Uri` then `Url.Convert(cineUrl)` should do the job).

**Comment by geralexgr** [comment]
Cineurl is a string. Error was: cannot convert from 'string' to 'AngleSharp.Url'
Url.Create(cineUrl) works fine.

**Comment by FlorianRappl** [comment]
Thanks! I'll investigate on the other issue. I think #80 is strongly related to this.
