### ISSUE TITLE
Angle Brackets around emails in text

### ISSUE THREAD

**Issue by gabbersepp** [AngleSharp/AngleSharp#790]
We use this lib to sanitize incoming emails.
Sometimes we get something like this:
`text text FROM XYZ <asd@example.com> text text text`

Of course, everything after the <asd.... is stripped off as this is an invalid HTML tag and not closed either. I think the email clients have bugs and produce this invalid HTML emails.

Are I'm able to handle such cases? I would like to look at every tag and check whether or not it contains an '@'.

**Comment by FlorianRappl** [comment]
There are multiple ways to handle this.

The two major ways that come to my mind:

1. You can iterate directly over the DOM and do modifications when you find an element name with an `@` sign
2. You can roll out your own `IMarkupFormatter` essentially using / wrapping a standard formatter (e.g., the pretty one). However, in the `OpenTag` (and `CloseTag` respectively) you'll watch for `@` in the tag name and output something else (or not output anything in `CloseTag`).

Does that help a bit?

**Comment by gabbersepp** [comment]
@FlorianRappl  Thanks for the suggestions. This solved our problems :-)
