### ISSUE TITLE
Normalize / fix html

### ISSUE THREAD

**Issue by tomaszmadeyski** [AngleSharp/AngleSharp#792]
I have this piece of html

```
<div>
  Outside paragraph
  <p>In paragraph</p>
</div>
```
As you can see there's `Outside paragraph` piece of text which, being outside paragraph, is not wanted situation.

Is there any AngleSharp method which would allow me to normalize / fix this piece of html so it looks like:

```
<div>
  <p>Outside paragraph</p>
  <p>In paragraph</p>
</div>
```

So, a piece of code which will put `Outside paragraph` in to paragraph.

I [asked this question at SO](https://stackoverflow.com/q/56182951/2393077) but apparently not much happening there

**Comment by FlorianRappl** [comment]
Unfortunately, AngleSharp cannot guess what you want / where you want to normalize to. The provided HTML is perfectly legit and can make sense, so there is no decision to be made.

Using AngleSharp's tree walkers (or in a simpler variant the formatters, which handle serialization - if that is sufficient for your case) you could write that normalization according to your rules.

I've posted an answer at SO for the question.

```
var context = BrowsingContext.New();
var document = await context.OpenAsync(res => res.Content("foo<div>Outside<p>Inside</p></div>bar"));
var walker = document.CreateTreeWalker(document.Body, AngleSharp.Dom.FilterSettings.Text);

while (walker.ToNext() != null)
{
    var current = walker.Current;

    // if just whitespace, e.g., formatting line breaks, or in p anyway - skip
    if (
        (current.TextContent.Trim().Length == 0) ||
        (current.ParentElement.LocalName == "p"))
    {
        continue;
    }
    // if next to paragraph perform the normalization
    else if (
        (current.PreviousSibling is IElement previous && previous.LocalName == "p") ||
        (current.NextSibling is IElement next && next.LocalName == "p"))
    {
        var newNode = document.CreateElement("p");
        current.ReplaceWith(newNode);
        newNode.Append(current);
    }
}
```

(more details in the SO thread)

Hope that helps!
