### ISSUE TITLE
IHtmlDocument using Dispose NPE

### ISSUE THREAD

**Issue by GieltjE** [AngleSharp/AngleSharp#794]
- [ x ] Minimum working example below
- [ x ] Using the latest version 0.13.0-alpha-742, works fine on 0.12.1
- [ x ] FAQ not applicable
- [ x ] Using nuget AngleSharp base only
- [ x ] Searched the issues

### Description
Latest alpha gives an NPE on IHtmlDocument's dispose

### Steps to Reproduce
Run code below
**Expected behavior: no crash on dispose
**Actual behavior: crash on dispose
**Environment details: Win 10, VS2019, .NET 4.7.2

### Example code, crashes on closing bracket

```cs
var parser = new HtmlParser();
            using (IHtmlDocument document = parser.ParseDocument("<html><head><meta http-equiv=\"Content - Type\">text/html; charset=utf-8</head><body></body></html>"))
            {
            }
```

**Comment by FlorianRappl** [comment]
Thanks for testing the alpha and thanks for the report!

Will be fixed in the 0.13 / next alpha release.

**Comment by GieltjE** [comment]
Damn that's some fast work, awesome :)

**Comment by FlorianRappl** [comment]
Landed in `devel`!

(I'm glad we have the preview versions now; and even more glad about awesome contributions like this one - thanks @GieltjE for playing around with the early bits!)
