### ISSUE TITLE
Question: Best way to create or parse a document.

### ISSUE THREAD

**Issue by atlastodor** [AngleSharp/AngleSharp#796]
This is not an issue - just a question.

Browsing your sources, I see that many unit tests use the construct below to create an HTML document from a memory string:
```
var context = BrowsingContext.New(configuration ?? Configuration.Default);
var htmlParser = context.GetService<IHtmlParser>();
return htmlParser.ParseDocument(sourceCode);
```
I am using a different approach. For existing documents, I use the following code:
```
CssParserOptions options = new CssParserOptions();
IConfiguration configuration = Configuration.Default.WithCss(options);
IBrowsingContext context = BrowsingContext.New(configuration);
var task = context.OpenAsync(request => { request.Content(htmlStream); request.Address(url); request.Status(HttpStatusCode.OK) }, cancel);
return (IHtmlDocument)task.Result;
```
… and when I need to create a new empty document, I use:
```
CssParserOptions options = new CssParserOptions();
IConfiguration configuration = Configuration.Default.WithCss(options);
IBrowsingContext context = BrowsingContext.New(configuration);
IHtmlDocument document = (IHtmlDocument)context.OpenNewAsync().Result;
document.InsertBefore(document.Implementation.CreateDocumentType("HTML", null, null), document.FirstChild);
return document;
```

My question is: Is this the optimal way to do this? Since my code is already running on a background / worker thread, I don't need things to be **async** and I would gladly opt for a direct call. Am I paying a penalty for using **OpenAsync** and **OpenNewAsync** and can this be avoided? Are there advantages of one or the other method (mine vs your method)?

**Comment by FlorianRappl** [comment]
Under the hood AngleSharp is deeply woven together with `async`. There are multiple reasons for this. One reason is that in general AngleSharp is reading from a `Stream` - which may be a network stram, another reason being that some services / interactions are used during parsing, which may be async in general.

That the `IHtmlParser` has a sync method is just for convenience (well it also uses a different path, which avoids a bit of async overhead) as well as historic baggage.

For the browsing context we avoided the sync path to not give the wrong impression that everything below will be synchronous (e.g., when resources should be loaded this is always done asynchronous). The penalty for async is (imho) quite small; especially with respect to the full cost of parsing an HTML document.

I'm afraid I can't give a better answer at the moment ...

Hope this helps anyway!

**Comment by FlorianRappl** [comment]
One addition:

Your way is actually the preferred way. The way you see in unit tests is just one possible way and there mostly for historic reasons. 

You can also chain the "virtual response" (that's how we named the overload with the callback):

```cs
var options = new CssParserOptions();
var configuration = Configuration.Default.WithCss(options);
var context = BrowsingContext.New(configuration);
var task = context.OpenAsync(res => res.Content(htmlStream).Address(url).Status(HttpStatusCode.OK), cancel);
return task.Result as IHtmlDocument;
```
