### ISSUE TITLE
Bug: Url host name parsing result is incorrect when hostname contains unicode character

### ISSUE THREAD

**Issue by hyspace** [AngleSharp/AngleSharp#797]
### Description

Url host name parsing result is incorrect when hostname contains unicode

### Steps to Reproduce

```cs
var url1 = new Url("http://ec².com");
var url2 = new Url("http://a.com/ec²");

Console.WriteLine(url1.Href);
Console.WriteLine(url2.Href);
```

**Expected output:**
```
http://ec².com/
(or maybe http://ec2.com/ which will be the final host name sent for dns lookup)
http://a.com/ec%C2%B2
```

**Actual output:**
```
http://ec.com/
http://a.com/ec%C2%B2
```

Note that ```²``` is missing.

**Environment details:**
Windows 10
.Net Framework 4.6.2

### Possible Solution
Problem only exist in hostname part

I saw comment:
```
//TODO finish with
//https://url.spec.whatwg.org/#concept-host-parser
```
I guess host name with Unicode characters is not implemented yet.
Do you have any plan on that or do you need help on that?

**Comment by FlorianRappl** [comment]
Indeed, the host parsing contains some encoding specific details that would have resulted in much more work / significant overhead (we already had that problem with punycode; which goes in that direction).

Any help on the matter would be appreciated.

Maybe in / for the given case a simple solution would already do: If the character is "printable" and not in the punycode table we can just output it. But I'm not sure what may break due to this simplification...

What are your thoughts on the topic? Thanks for raising this issue!

**Comment by hyspace** [comment]
In my opinion this problem should be handled in native `System.Uri` Class, but unfortunately `System.Uri` does not parse URL in the way defined in the spec.

I had trouble when using `System.Uri` Class recently and I really need to have a URL Class that parse URL in a standard driven way so that I can expect same result and behavior as browser. I also want to avoid reinventing the wheel. I'm not a veteran in C# world, so I don't know if there is any existing opensource project have already achieved this goal (parse URL in a standard driven way).

In worst case, if we really don't have any, I would like to help implementing it with some open source implementation in other language as reference, like `webkit` or `WebRender`.

I will do some further research on this, this problem is really blocking me now.

**Comment by FlorianRappl** [comment]
Since `System.Uri` is not standard (as you found out, too) we had to do our own implementation, which (as a matter of fact) passes more tests than, e.g., the implementation in Chromium (official W3C test suite, tests run in 2016).

> I'm not a veteran in C# world, so I don't know if there is any existing opensource project have already achieved this goal (parse URL in a standard driven way).

Well, AngleSharp is the one as explained. Just because we miss some part of the spec does not mean we are not following it. No browser implements all W3C specs and still they are following the standard.

However, in terms of encoding we don't like to also include it in our implementation (we expect / hope that the .NET Standard will promote an API for the missing parts). The `Url` helper alone is another 1k LOC and from a first glance all the necessary encodings would add another 5 to 10k LOC, which simply isn't worth it as URLs like the one you encountered are rather seldom (to say the least)...

Nevertheless, it's a bug / missing part of the spec and any contribution to it would be appreciated. Maybe the missing .NET APIs have been added since the `Url` class was written.

**Comment by FlorianRappl** [comment]
One more addition.

The expected output of `http://ec².com/` is wrong. The expected output has to be `http://ec2.com/`. At least, that's what Chromium makes out of it. I guess this another thing from Punycode (which describes the replacement characters; note that AngleSharp already implements *some* replacement characters, but the full table is long. Adding alternatives for "2", "3" etc. is possible though.

**Comment by FlorianRappl** [comment]
Fix for the specific bug / enhancement for the replacement characters landed in `devel`.

I'll leave the issue open as an "enhancement" for v1. Any contribution appreciated!

**Comment by hyspace** [comment]
Thanks for pointing out my mistake for result for "²", I will update my issue description to avoid confusion.

Thanks for letting me know that `AngleSharp.Url` is already doing better than Chromium. I thought they contribute to the standard so they must be 100% following the standard. I'm working on security area so any different behavior than a major browser can become vulnerability which hacker can use.

I saw your commit in `devel`. I don't think keep filling to the mapping is a good idea. After your explanation, I understand that full implementation may not fit goal of AngleSharp, for performance concerns.

Only considering Unicode characters in hostname, .Net already have [IdnMapping](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.idnmapping.getascii?view=netframework-4.8) Class. 

(If you already know but choose not to use it, please ignore).

```cs
var map = new System.Globalization.IdnMapping();
var two = map.GetAscii("²"); // will get "2";
var com = map.GetAscii("cºm"); // will get "com"
var zhou = map.GetAscii("周"); // will get "xn--zsr"
var ex = map.GetAscii("c؀om"); // will throw ArgumentException
```

Another problem I have is, after creating `AngleSharp.Url` object, I lose the opportunity to do further conversion or correction of parsing. Like my example, "²" is stripped out after `AngleSharp.Url` object is created. Even I'm aware that `AngleSharp.Uri` may produce wrong result for unicode hostnames for performance reason, I can not correct it later, but have to drop whole result and try to parse it differently.

**Comment by FlorianRappl** [comment]
I think using the `IdnMapping` class would be superb. I think I looked it up in the past and it was not available in the PCL, but it seems to be available for .NET Standard 2.0 on first glance. Note, however, that AngleSharp also supports .NET Standard 1.3, so we definitely cannot support this behavior on all platforms.

I also don't think the mapping should be filled extensively, but I filled it with some common replacements, such that it covers some more edge cases (e.g. yours). The level of filling should now be "complete enough" for platforms following .NET Standard < 2.0.

Suggestion: Let's use `IdnMapping` for .NET Standard 2.0 and the replacement table for unsupported platforms. How does that sound?

**Comment by hyspace** [comment]
This plan sounds good to me now. I will still spend some time on the URL standard and `IdnMapping` Class to see if there are any potential issue. 

Thanks!

**Comment by FlorianRappl** [comment]
Landed in `devel`.

**Comment by hyspace** [comment]
Please reopen this issue.

After reading the [host-parsing part of spec](https://url.spec.whatwg.org/#host-parsing)

I found the current implementation still have a problem.

Consider this example input:
```
http://www.exampl？e.com/
```
Spec will consider this host name as invalid but current `Url` will think it is valid.

The problem is on https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Url.cs#L1062
Current `TrySanatizeHost` function is doing a 2-passes validation of host name, while in the spec it is a 3 passes process:
1. 3.5.4 string percent decoding
1. 3.5.5 domain to ASCII
1. 3.5.7 check forbidden host code point

For example above, the result of step 2 may contains forbidden host code point.
`？` will be mapped to `?` and then should cause parse failure.

If you don't have concern, I would like to implement the correct domain parsing including the ipv4 and ipv6 part.
