### ISSUE TITLE
PCL unit testing strategy

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#80]
The recently occurred bug (issue #79) shows again that the current test strategy is insufficient. What is really required is driving a core set of functionality on all platforms and additionally perhaps specific tests individually per platform. This is not "Silverlight" and ".NET 4.0" - this is everything supported by the current PCL Profile of AngleSharp.

Can anyone recommend a good approach to do this or does anyone have experience with cross-platform testing of a PCL?

Any recommendation or comment would be highly appreciated!

**Comment by FlorianRappl** [comment]
Right now my tendency is to create a shared project, which will then be used in three other projects:
- One for .NET 4.5
- One for Windows Phone (8)
- One for Windows Store applications

But further investigation is required.

**Comment by 304NotModified** [comment]
IMO the support for PCL could be dropped. 

.NET standard is the future and more and more frameworks have support for .NET standard. 

So "wont fix"

**Comment by FlorianRappl** [comment]
That's right and most earlier issues also vanish. See my other point regarding platform support in #709.

Keep in mind the testing here had nothing to do with PCL directly, rather with the platforms and the implementations of .NET underneath. Similar things could occur of course with .NET Standard as there are still different implementations (e.g., Mono, .NET Framework X, .NET Core X) that could yield different behaviors in edge cases.
