### ISSUE TITLE
`Url` does not remove leading / trailing control characters

### ISSUE THREAD

**Issue by hyspace** [AngleSharp/AngleSharp#800]
### Description

Leading/trailing *C0 Control* is not removed correctly

For input
```cs
"\u001b\u0004\u0012 http://example.com/\u001f \u000d"
```
Expected parsing result: `http://example.com/`
Current parsing result: `"%1B%04%12%20http://example.com/%1F"`
Spec reference: [basic url parser 1.3](https://url.spec.whatwg.org/#concept-basic-url-parser)

**Comment by FlorianRappl** [comment]
In general, most of the items of this list do not fall in the bug category, but rather in the feature category.

Please note that WHATWG provides a living standard, i.e., the document changes over time. At the time of implementation the bullet point 1) was not there. Also I don't think it has *any real impact* (afaik not all evergreen browsers support this - hence websites *will not* make any use of this).

For 2) it was never stated that `Url` supports this - this was a decision for simplification (any contribution here welcome).

> Port number validation is not returning failure when port number is larger than 65535

I don't see any error here. Ports are currently 16-bit, however, who knows when (or if) this will change. It should be up to the specific requester to then block a request (let's say the port is 99999 - what should we do about it? Just drop the port? note that invalid URLs will result to a default URL -> it will have potential negative side-effects) if its doing something invalid. It's a potential enhancement, but I would regard it as highly optional and I'm fine with omitting it.

The only thing I see from this list that should be tackled is "Leading/trailing C0 Control is not removed correctly".

I've edited the title to reflect this correctly. Thanks!

**Comment by hyspace** [comment]
Thanks for the explanation.

The leading/trailing control characters problem is the only one need to be fixed now, but actually I do want to discuss about something else as well, I will open a feature issue about it later . I have removed unrelated topic in this issue.

For this particular bug, I will send a separate PR later today.

**Comment by FlorianRappl** [comment]
Thanks for the adjustment and the great PR!

Landed in `devel`.
