### ISSUE TITLE
I want to install AngleSharp to VS2017 windows Service Project

### ISSUE THREAD

**Issue by shuira** [AngleSharp/AngleSharp#807]
I can not install to  VS2017 windows Service Project

Please Help me , thank you

**Comment by FlorianRappl** [comment]
What version of the .NET Framework are you targeting? I assume the version you use there is too low.

Please see the requirements listed in the [README](https://github.com/AngleSharp/AngleSharp#supported-platforms). Hope that helps!

**Comment by shuira** [comment]
up frmewrk to 4.6  can install , thank you
