### ISSUE TITLE
Behavior change from 0.8.1 to 0.8.3: Node names are all uppercase

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#81]
At the start I should mention is something I can work around (although somewhat inconvenient and may cause issues down the road.) 

I am reporting this only because it might be useful for you in case you weren't aware.

Parsing this document:
`<html><div><b><i>Hello, World. What's up?</i></b></div></html>`

using AngleSharp 0.8.1 produces:
`<html><head></head><body><div><b><i>Hello, World. What's up?</i></b></div></body></html>`

But in AngleSharp 0.8.3 produces:
`<HTML><HEAD></HEAD><BODY><DIV><B><I>Hello, World. What's up?</I></B></DIV></BODY></HTML>`

As you can see, the case of all elements has been made upper case.

While HTML is case-insensitive, XHTML is not - in fact it requires all nodes to be lowercase. See this [specification](http://www.w3.org/TR/xhtml1/) - it is very clear about this point. 

Suggestions:
1) Keep the original case wherever possible.
2) If that isn't possible for whatever reason, use lowercase, not uppercase.

**Comment by FlorianRappl** [comment]
What you mean with produces? What changed from AngleSharp v0.8.1 to v0.8.3 is that `NodeName` is using the uppercase version as specified by the W3C. You should use `LocalName` if you want the exact spelling (case) of the element. Hence if you use something like the `ToHtml` method (without a custom markup formatter) then you should see the lowercase names as you expect. I am not a big enthusiast about that (historical) detail.

There was an issue a time ago where I explained why I did not use the uppercase version for `TagName`. However, I received a couple of requests for following the official spec. in such details, just for consistency. Hence the change. I am sorry if this conflicts with code you had.

**Comment by corliss** [comment]
I was using `NodeName`. Based on your suggestion, I've switched to using `LocalName`, and now everything is back to the previous behavior. Thanks.

**Comment by FlorianRappl** [comment]
Glad this fixed the issue and sorry for the confusion.
