### ISSUE TITLE
empty result with AngleSharp 0.9.11

### ISSUE THREAD

**Issue by qnguyen12** [AngleSharp/AngleSharp#810]
I am using AngleSharp v0.9.11.
Because our project is targeting .NET Framework 4.5.2. So the latest version of AngleSharp I can upgrade is 0.9.11.
Now, with same code but the project with .NET 4.6 returns ok but not ok in project with .NET 4.5.2
`private async Task<string> GetPageAsync()
 {
        string result = "ok";
        var page = "https://www.esuperfund.com.au/bank-account/transaction-account/interest-rates/cba-transaction-account";            
        var config = Configuration.Default.WithDefaultLoader();
        var doc = await BrowsingContext.New(config).OpenAsync(page);
        if (string.IsNullOrEmpty(doc.Body.InnerHtml))
            result = "Not ok";
        return result;
 }`

I think there are some codes/libraries which make that web returns empty as I tested with other urls (e.g. stackoverflow.com) and all are ok.
I don't know what should I do to make it works for .NET 4.5.2 project.

Many thanks

**Comment by FlorianRappl** [comment]
This is not a problem with AngleSharp, but I assume HTTPS.

Use the following link to see if you get it working: https://stackoverflow.com/questions/560804/how-do-i-use-webrequest-to-access-an-ssl-encrypted-site-using-https

Hope that helps!

**Comment by qnguyen12** [comment]
The library works on other websites, such as https://www.google.com/ or https://stackoverflow.com/
but not https://www.esuperfund.com.au/

**Comment by FlorianRappl** [comment]
Yes, because they have different certificates (the certificates are validated and the used CAs are much less (updated) than your standard browser...).

Again, please follow the link and add your certificate or allow all certificates.

**Comment by FlorianRappl** [comment]
Just another link for you to read (and the person in this post has a page that uses the same CA as esuperfund.com.au; GeoTrust): https://forums.asp.net/t/2145653.aspx?C+WebRequest+Could+not+create+SSL+TLS+secure+channel

**Comment by qnguyen12** [comment]
Thanks,
I added `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;` and it works now.
