### ISSUE TITLE
Problem to Login in site

### ISSUE THREAD

**Issue by jakconstantin** [AngleSharp/AngleSharp#812]
Good day.
I have a question regarding the login to the site. It may be lightweight, but I have not found how to implement it.
I am trying to login on the site. Started to execute the following code

```cs
var lopts = new LoaderOptions { IsResourceLoadingEnabled = true };
var config = Configuration.Default
  .WithDefaultLoader(lopts)
  .WithCookies()
  .WithJs()
  .WithCss();
var context = BrowsingContext.New(config);
var doc = await context.OpenAsync(sourceToSite);
var res = context.Active.QuerySelector("div [id='RB_React_Component_LoginFormContainer_0']");

res.OuterHtml return "<div id = \" RB_React_Component_LoginFormContainer_0 \ "class = \" login-form \ "> </div>"
```

But in reality, if you look through the Developer Tools, you can see something like this:

![image](https://user-images.githubusercontent.com/53932538/62768016-980b7e80-ba9e-11e9-9a4d-d7add29c07aa.png)

The question is, how do I implement the login to the site? why isn’t everything loaded? is it possible to somehow login throughGoogle and use this login in AngleSharp?
Thanks for any answer

**Comment by FlorianRappl** [comment]
Unfortunately the MWE is not complete (it would also not work due to some syntax error, but I've corrected that). What is source to site? Is it a URL?

Code looks fine so far, but anything with JS may not work (and would be rather an issue in the AngleSharp.Js repository).

Question from my side: What's not working? Why do you need CSS?

In general a login flow would work due to cookies etc., but if the login requires some parts loaded by JS then this may fail as explained.

**Comment by jakconstantin** [comment]
Here along this path I try to log in https://www.redbubble.com/auth/login
I started trying to execute my code in the AngleSharp.Js project. There in the RunScript method and script loading errors occur
  public JsValue RunScript(String source, JsValue context)
        {
            _engine.EnterExecutionContext(Lexicals, Variables, context);
            _engine.Execute(source);
            _engine.LeaveExecutionContext();
            return _engine.GetCompletionValue();
        }

I understand that this is a jint.dll problem.
And errors of the following nature:

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll

The thread 0x39d4 has exited with code 0 (0x0).
Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll
$ is not defined

The thread 0x5380 has exited with code 0 (0x0).
The thread 0x3978 has exited with code 0 (0x0).
Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll
$ is not defined

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll
Object has no method 'toGMTString'

The thread 0x1ce0 has exited with code 0 (0x0).
The thread 0x2560 has exited with code 0 (0x0).
Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll
$ is not defined

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll
__ is not defined

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll

The thread 0x4c74 has exited with code 0 (0x0).
Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll
__ is not defined

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll
in can only be used with an object

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll
__ is not defined

Exception thrown: 'Jint.Runtime.JavaScriptException' in jint.dll

**Comment by FlorianRappl** [comment]
Either the required script(s) are not loaded or cannot be evaluated using Jint. Still the questions are outstanding:

> What is source to site? Is it a URL?

This is important because if its not loaded from the remote source or the URL has not been set properly the (usually) relative script URLs will also not be useful and thus the scripts are not evaluated.

> What's not working? Why do you need CSS?

So JavaScript is not working (and this is usually the case - keep in mind you post the issue at AngleSharp and AngleSharp does not come with a JS engine - we have AngleSharp.Js, but its still experimental and will not work for sophisticated pages / scripts) - if the login requires JS there is no way to get this working with AngleSharp alone (except you go directly to the login page and get the cookie / JWT / whatever).

**Comment by jakconstantin** [comment]
Hello
"What is source to site? Is it a URL?" -https://www.redbubble.com/auth/login
"(except you go directly to the login page and get the cookie / JWT / whatever)" I don’t understand why the cookie credits that I saved for accessing the site are not work.
Configuration.Default.WithDefaultLoader(new LoaderOptions { IsResourceLoadingEnabled = true }).WithCookies().WithJs();

**Comment by FlorianRappl** [comment]
Depends on the login mechanism of that page. Most likely, its a SPA and despite its use of a cookie, the ultimate authenticator is some API. Thus only direct requests to that API yield a login state and transport the cookie.

Glancing at the page it seems to be a React SPA with SSR. Thus most probably JS needs to be active and working.

**Comment by jakconstantin** [comment]
I don’t quite understand which way I should move now. But thank you very much for the answers.

**Comment by jakconstantin** [comment]
I started trying in the AngleSharp.Js project and it turns out that quite a lot of errors happen when running RunScript (). And perhaps because of this, the necessary information is not loaded. Can I somehow get around this now without using React SPA with SSR? since i don't understand how to use React SPA with SSR



![image](https://user-images.githubusercontent.com/53932538/62920742-4705ce00-bdaf-11e9-8065-109e8c52b04a.png)

**Comment by jakconstantin** [comment]
There is one more question. AngleSharp.Js works with Jint version 2.10.4 (3/22/2017), and there is already 3.0.0-beta-1525 (04/04/2019). What is the reason for not working with newer versions?

![image](https://user-images.githubusercontent.com/53932538/62943223-a5986f80-bde2-11e9-8ec2-841a38c51442.png)

**Comment by FlorianRappl** [comment]
> There is one more question. AngleSharp.Js works with Jint version 2.10.4 (3/22/2017), and there is already 3.0.0-beta-1525 (04/04/2019). What is the reason for not working with newer versions?

Breaking changes - as usual. (Also the new one is a beta, we need a stable release first.)

Regarding the way how to go on: I would see what the browser does when logging in. Presumably, you can just do the same (e.g., follow the same URL). In my experience scraping the page and doing the login there is at least the same amount of work as doing just the request (w/o rendering the page first).

Remember: All you want is the right authorization / information - you don't care about the right rendering.

Hope that helps!

**Comment by jakconstantin** [comment]
Thank you very much for the recommendations and for the work you have done. I will try.
