### ISSUE TITLE
Is there an option to prettify HTML with CSS and JS?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [AngleSharp/AngleSharp#814]
Hi,

I'm a bit new to this library and was wondering if it's possible to format HTML with some CSS and JS?

I've found this code that does format HTML with C#
```
var parser = new AngleSharp.Html.Parser.HtmlParser();
var document = parser.ParseDocument("<html><body>Hello, world</body></html>");
 
var sw = new StringWriter();
document.ToHtml(sw, new AngleSharp.Html.PrettyMarkupFormatter());
 
var indentedHtml = sw.ToString();
```

and converted it to PowerShell equivalent 

```PowerShell
function Format-HTML {
    [CmdletBinding()]
    param(
        [string] $File,
        [string] $OutputFile
    )
    if ($File -and (Test-Path -LiteralPath $File)) {
        $FileContent = [IO.File]::ReadAllText($file)

        $HTMLParser = New-Object -TypeName AngleSharp.Html.Parser.HtmlParser
        $ParsedDocument = $HTMLParser.ParseDocument($FileContent)
        $StringWriter = [System.IO.StringWriter]::new()
        $PrettyMarkupFormatter = New-Object -TypeName AngleSharp.Html.PrettyMarkupFormatter
        $ParsedDocument.ToHtml($StringWriter, $PrettyMarkupFormatter)
        #$ParsedDocument.StyleSheets

        $FormattedHTML = $StringWriter.ToString()

        if ($FormattedHTML) {
            [IO.File]::WriteAllText($OutputFile, $FormattedHTML)
        }
    }
}
```

Which when I run HTML code thru it generates this: https://github.com/EvotecIT/PSParseHTML/blob/master/Examples/Output/Example.Toasts.html

And as you can see HTML is perfectly formatted but CSS/JS is untouched so the whole WOW effect is lower. 

Is it possible? Option I'm missing?

**Comment by FlorianRappl** [comment]
There is a CSS Prettifier (from `AngleSharp.Css`), but you would need to run it upfront (before serializing the HTML) and write back the result to the `style` elements.

The HTML Markup Prettifier only knows HTML - it will not touch any `TextContent`, e.g., the content of a `style` element, or inline `script` element (neither will it prettify attribute values, e.g., of `style` attributes).

Hope that helps!

**Comment by PrzemyslawKlys** [comment]
It does. Thank you.

**Comment by PrzemyslawKlys** [comment]
I could parse HTML for CSS/JS but I'm wondering how would AngleSharp.css / .js know proper indentation that is relevant to HTML that it's stored in?

**Comment by FlorianRappl** [comment]
That largely depends - should the content be indented or not?

If you want yes (and you need to do the steps above anyway manually) I would just count the number of ancestors (there is a helper for that - something like `Ancestors()`) and multiply by the number of spaces for the indent. IIRC the CSS prettifier accepts the current indentation and number of spaces - so you could just apply the right indent yourself.

By default the CSS prettifier does not know it "sits" inside a `style` element and thus starts with no indentation.

Regarding JS - right now no such solution (prettifier) exists. Maybe Jint (or some other JS library) helps you out there; doing the same as with inlined CSS.

Hope that helps!
