### ISSUE TITLE
Manipulation of Document.ReadyState

### ISSUE THREAD

**Issue by Jayx239** [AngleSharp/AngleSharp#815]
## New Feature Proposal
This is more of a question as to whether it is possible to manipulate the ReadyState.
### Description
I would like to be able to manually delay the ReadyState and trigger it at a later point after configuring some jQuery to execute.

### Background
I am working on a project that extracts JavaScript and executes it in the jint engine to run against the AngleSharp DOM. I am running into an issue when I import jQuery and have scripts running in $(document).ready blocks as this call is only triggered on the initial ready state. 

Provide any additional background for the feature. e.g., user scenarios.

My basic process is as follows:
1. Retrieve HTML
2. Render Document
3. Retrieve all JavaScript files
4. Load document into jint engine
5. Execute js files in jint engine

I think the problem stems from jQuery executing the ready function when it sees the Document.ReadyState is ready. Is it possible for me to manually modify this state to not be ready, then load the js, then set the ReadyState to trigger the execution of the jQuery.

### Specification
I'm pretty sure this goes against the specification so I don't expect you to implement anything new. I'm more curious as to whether there is any existing workaround to achieve the functionality I am looking for?

**Comment by FlorianRappl** [comment]
The interesting part is that I am also currently thinking about this - most notably that some AngleSharp extensions may want to bring in new (async) stuff in the initial pipeline that should delay the ready state / loading finished.

That all being said one of the following may (currently) work:

- Scripts are run between interactive and complete - these may also be "custom" scripts related to a custom script engine, which just returns a task - that could be adjusted to the needs
- We could (ab)use the (internal) `AttachReference` method in `Document`; yes we will need reflection to use it from outside, but this one offers us to directly place a `Task` that could be adjusted as described in the previous point

I guess opening some channel to, e.g., the `AttachReference` method would be good in general. Maybe there is an even better method - I don't know yet.

Hope that help!

**Comment by FlorianRappl** [comment]
Landed in `devel`.

**Comment by Jayx239** [comment]
Awesome thanks so much! That was quick

**Comment by Jayx239** [comment]
Did this make it into release 0.13.0-alpha-768 on nuget?

**Comment by FlorianRappl** [comment]
Yes, every release of `devel` triggers a NuGet pre-release.

**Comment by Jayx239** [comment]
Is there an easy way for me to publicly access the DelayLoad method? If not can it be added to the IHtmlDocument interface? I'm thinking about attaching an HtmlParseEvent listener to the parser that sets the DelayLoad task before it finishes parsing the document.

**Comment by FlorianRappl** [comment]
Could you try to cast to `Document`?
