### ISSUE TITLE
Cant use with proxy

### ISSUE THREAD

**Issue by mbpakalin** [AngleSharp/AngleSharp#817]
Hello,
I'm new at anglesharp. I tried the proxy change at the documentation but it didnt work. 
Now i'm using this, it works well with webclient but it isnt working with AngleSharp. 

The code i'm trying is ;

` var handler = new HttpClientHandler()
            {
                Proxy = new WebProxy(String.Format("{0}:{1}", "myProxy", "myPort"), false),
                PreAuthenticate = true,
                UseDefaultCredentials = false,
            };
            var config = Configuration.Default.WithJs().WithCookies().WithDefaultLoader().With(handler);

            //Create a new context for evaluating webpages with the given config
            var context = BrowsingContext.New(config);     
            var document = await context.OpenAsync("https://api.ipify.org?format=json");
            Console.WriteLine(document.DocumentElement.OuterHtml);`

I'm not getting any error, proxy is not working thats it. I'm getting my original ip not the proxys.
But with WebClient it works well.

**Comment by FlorianRappl** [comment]
What you try won't work. By default, AngleSharp does not use the `HttpClient`.

If you want to use the `HttpClient` (e.g., with a custom `HttpClientHandler`) have a look at [AngleSharp.Io](https://github.com/AngleSharp/AngleSharp.Io).

Hope that helps!

**Comment by mbpakalin** [comment]
Thanks for your reply,
I looked into it, but i didnt find any example on how to use it :/

**Comment by FlorianRappl** [comment]
@mbpakalin the README shows you everything you need to know. There is a `WithRequesters` that registers the requesters from AngleSharp.Io - it's as simple as that.
