### ISSUE TITLE
What happened to innerText?

### ISSUE THREAD

**Issue by oliverw** [AngleSharp/AngleSharp#825]
Support for the `innerText` property (similar to HAP) was merged in https://github.com/AngleSharp/AngleSharp/pull/655, yet I'm unable to spot it anywhere in the current codebase. What happened?

**Comment by campersau** [comment]
Since `innerText` relies havily on CSS it was moved to [`AngleSharp.Css`](https://github.com/AngleSharp/AngleSharp.Css/blob/f94b973c8862e2fdf1933bfc95f2c0f83cda0976/src/AngleSharp.Css/Extensions/ElementExtensions.cs#L34-L150).
You can also read about the decision in the PR.

**Comment by FlorianRappl** [comment]
It is now part of AngleSharp.Css, as @campersau mentioned. There the property is available in form of an extension method `GetInnerText()` for elements.

Hope that helps!
