### ISSUE TITLE
How to customize HttpClientRequester with Default Headers?

### ISSUE THREAD

**Issue by mariohik** [AngleSharp/AngleSharp#826]
How do I add a Header to a configuration using Proxy?
Every time I try to add Header, the proxy stops working.

With this code the proxy works:

`_handler = new HttpClientHandler()
            {
                Proxy = new WebProxy("127.0.0.1", 8888),
                UseProxy = true, 
            };
            _config = Configuration.Default.WithRequesters(_handler).WithJs().WithDefaultLoader().WithDefaultCookies();`

**Comment by FlorianRappl** [comment]
Can you show more code? The code you provide will definitely **not** work, since you did not **use** the configuration (you just created one; with creates a new configuration that you can then use).

```cs
var config = Configuration.Default...;
var context = BrowsingContext.New(config);
```

**Comment by mariohik** [comment]
I'm using this code to use Proxy:
```csharp
var handler = new HttpClientHandler()
            {
                Proxy = new WebProxy("127.0.0.1", 8888),
                UseProxy = true,
            };
var config = Configuration.Default.WithRequesters(handler).WithJs().WithDefaultLoader().WithDefaultCookies();
var context = BrowsingContext.New(config);
```

However, if I try to add a User-Agent, the Proxy stops recording:
```csharp
var handler = new HttpClientHandler()
            {
                Proxy = new WebProxy("127.0.0.1", 8888),
                UseProxy = true,
            };
var requester = new DefaultHttpRequester("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0");
var config = Configuration.Default.WithRequesters(handler).With(requester).WithJs().WithDefaultLoader().WithDefaultCookies();
var context = BrowsingContext.New(config);
```

**Comment by FlorianRappl** [comment]
These are two different things. The `handler` gets into the `HttpClientRequester` (from AngleSharp.Io), while `DefaultHttpRequester` is the (default) HTTP client coming AngleSharp. So you override the more special one with the default one ... Not a good choice!

Just use one or the other.

**Comment by FlorianRappl** [comment]
If you really want to change the agent for `HttpClientRequester` I would explicitly use it (with a `HttpClient` instance).

```cs
var handler = new HttpClientHandler
{
  Proxy = new WebProxy("127.0.0.1", 8888),   
  UseProxy = true,
  UseCookies = false,
  AllowAutoRedirect = false,
};
var client = new HttpClient(handler);
client.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0");
var requester = new HttpClientRequester(client);
var config = Configuration.Default
  .With(requester)
  .WithJs()
  .WithDefaultLoader()
  .WithTemporaryCookies();
```

Hint: if you load AngleSharp.Io anyway, then also use the much better / advanced cookie container from it.

Hope that helps!

**Comment by gsscoder** [comment]
Sorry for posting in a *closed issue*, but I'd like to avoid a duplicate...

I've a similar need, just trying to set **one** culture (`Accept-Language`) and the agent (`User-Agent`).

I'm using the latest version of AngleSharp (**0.14.0-alpha-787**) but it seems that `HttpClientRequester` is not present in the library (to follow the solution presented here). From the code it should be present in `AngleSharp.Io.Network` namespace (I found it [here](https://github.com/AngleSharp/AngleSharp.Io/blob/master/src/AngleSharp.Io/Network/HttpClientRequester.cs)).

It seems also that following code don't set the language to `en-US`:
`var context = BrowsingContext.New(Configuration.Default.WithCulture("en-US").WithDefaultLoader());`
Maybe because it just adds a locale.

Any help really appreciated!
This headless browser framework is simply superb.

**Comment by FlorianRappl** [comment]
`HttpClientRequester` comes from `AngleSharp.Io`, which is a different library. You can just install it in addition to `AngleSharp` via NuGet.

Hope that helps @gsscoder !

**Comment by gsscoder** [comment]
Thanks for fast reply, @FlorianRappl!
I suspected it was in another assembly... I've using your **framework** from yesterday, so I'm a complete *noob*.

I'm still unable to force the language to **en-US**. This is how I build the context instance:
```
var client = new HttpClient();
client.DefaultRequestHeaders.Remove("Accept-Language"); // I don't know if this is necessary
client.DefaultRequestHeaders.Add("Accept-Language", "en-US,en;q=0.5");
var requester = new HttpClientRequester(client);
var context = BrowsingContext.New(
  Configuration.Default
  .WithRequester(requester)
  .WithDefaultLoader());
```
I didn't digged into the code but I suppose that AngleSharp use something like `CultureInfo.DefaultThreadCurrent`.

Also setting this before `BrowsingContext.New` don't change things:
`Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-US");`

**Comment by FlorianRappl** [comment]
Hm, the `Accept-Language` header is IIRC a header we don't set (neither in the `DefaultHttpRequester`  nor in the `HttpClientRequester`).

I think you can intercept the call with a `Filter`. The `WithDefaultLoader` should have an overload that allows you to specify the Filter, which is just a callback that gets the `IRequest`.

I will also try to reflect that. Coming back to you in another second.
cc @gsscoder

**Comment by FlorianRappl** [comment]
Alright I used the following code:

```cs
var formatter = new PrettyMarkupFormatter();
var client = new HttpClient();
client.DefaultRequestHeaders.Add("Accept-Language", "en-US,en;q=0.812");
var requester = new HttpClientRequester(client);
var config = Configuration.Default.WithRequester(requester).WithDefaultLoader();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync("http://www.reliply.org/tools/requestheaders.php");
var table = document.QuerySelector("table.standard");
Console.WriteLine(table.ToHtml(formatter));
```

which is pretty much what you did.

I end up with a response:

```plain
<table class="standard" cellspacing="1" border="0" cellpadding="4">
        <tbody>
                <tr>
                        <th class="standard" colspan="3">
                                <center>
                                        <font size="+1">
                                                <b>HTTP Request Headers Sent From Your Browser, Plus Explaination</b>
                                        </font>
                                </center>
                        </th>
                </tr>
                <tr>
                        <td class="standard_evenrow">
                                <center>
                                        <b>Header Name</b>
                                </center>
                        </td>
                        <td class="standard_evenrow">
                                <center>
                                        <b>
                                                <i>Your</i>
                                                Header Value</b>
                                </center>
                        </td>
                        <td class="standard_evenrow">
                                <center>
                                        <b>Explaination</b>
                                </center>
                        </td>
                </tr>
                <tr>
                        <td class="standard_oddrow">Accept Language</td>
                        <td class="standard_oddrow">en-US, en; q=0.812</td>
                        <td class="standard_oddrow">This is the preferred language of the browser.  Some websites look at this header and change the language of the page according to the accept language.  In many browsers you can change the HTTP Accept Language if you look deep enough in the configuration/settins/options.  Look here for
                                <a href="../info/internet/http-accept-lang.html" title="How To Change My HTTP Accept Language">How To Change My HTTP Accept Language</a>
                        </td>
                </tr>
                <tr>
                        <td class="standard_evenrow">Accept Encoding</td>
                        <td class="standard_evenrow">
                                <i>Your browser did not send this request header</i>
                        </td>
                        <td class="standard_evenrow">This tells the webserver if your browser is able to accept compressed webpages.  This can make a big difference in download time and bandwidth usage.  For compressed webpages to be used, the browser must accept them
                                <i>and</i>
                                the webserver must send them.  Look here for an easy way to
                                <a href="../info/internt/enable-compressed-webpages.html" title="Enable Gzip Compression On Your Php Pages To Save Bandwith">Enable Gzip Compression on your Php Webpages</a>
                                (Saves bandwidth and reduces download times).</td>
                </tr>
                <tr>
                        <td class="standard_oddrow">User Agent</td>
                        <td class="standard_oddrow">
                                <i>Your browser did not send this request header</i>
                        </td>
                        <td class="standard_oddrow">This identifies the make and model of your browser.  Some websites use this information to indirectly know the capabilities of your browser and change (or tailor) the webpage for your best browsing experience.</td>
                </tr>
                <tr>
                        <td class="standard_evenrow">HTTP Connection</td>
                        <td class="standard_evenrow">
                                <i>Your browser did not send this request header</i>
                        </td>
                        <td class="standard_evenrow">Defines the type of connection your browser wants to establish with the webserver.</td>
                </tr>
                <tr>
                        <td class="standard_oddrow">Host</td>
                        <td class="standard_oddrow">www.reliply.org</td>
                        <td class="standard_oddrow">This is the host or domain name that the browser is attempting to connect to.</td>
                </tr>
                <tr>
                        <td class="standard_oddrow">Request Method</td>
                        <td class="standard_oddrow">GET</td>
                        <td class="standard_oddrow">This can be GET, POST, PUT or HEAD.  GET is the "normal" method for viewing a webpage. POST can be used to send form data and the HEAD request method is for retrieving only the headers of a page instead of downloading the entire page.</td>
                </tr>
        </tbody>
</table>
```

So this works. Maybe the particular webserver is ignoring this header or requires some other headers, too (maybe the agent?).

**Remark**: The site I used is [www.reliply.org/tools/requestheaders.php](http://www.reliply.org/tools/requestheaders.php).

**Comment by gsscoder** [comment]
@FlorianRappl, again thank you for your time and fast & depth reply.

Using `reliply.org` is very cool thing, thank you for showing it! Doing something would have been my next move. Impossible solve problems without certainties.

So now it's clear, the server (in my case `google.com`) is simply ignoring the `Accept-Language` headers. I'm posting same query string *by hand* with a Chrome setted to **en-US** and results are different. When I use `AngleSharp` I don't know why but *Google* understand that the request is made from Italy (where I live).

Thanks very much for your help, it was very useful. Beyond that it's no longer due to **AngleSharp** (which I'm starting really to love)...

Have a nice day!
