### ISSUE TITLE
Style item from IElement

### ISSUE THREAD

**Issue by Christian1980** [AngleSharp/AngleSharp#827]
I was using version 0.10.1 and I was using Style attribute from an IElement.

Now, I decided to update to the latest version 0.13 but now I can't use Style anymore and I don't see anything in the migration doc about the Style item.

My code was the following:

```
public Dictionary<string, string> Styles
        {
            get
            {
                Dictionary<string, string> styles = new Dictionary<string, string>();

                if (node.NodeType != NodeType.Text)
                {
                    IElement element = node as IElement;
                    foreach (var style in element.Style)
                    {
                        styles.Add(style.Name, style.Value);
                    }
                }

                return styles;
            }
        }
```

It complains now in `var style in element.Style`  .. No style definition in IElement.

How can I fix my code ?

**Comment by FlorianRappl** [comment]
Have you really read the migration doc?
https://github.com/AngleSharp/AngleSharp/blob/master/doc/Migration.md#css

You need to use AngleSharp.Css - the property has been replaced with the extension methods `GetStyle` / `SetStyle`. Hope it helps.
