### ISSUE TITLE
process document self-closing and non self-closing node

### ISSUE THREAD

**Issue by jiangpan** [AngleSharp/AngleSharp#828]
# New Feature Proposal

## Description

if a document contain self-closing and non self-closing node
when format then all is non self-closing node

## Background

if a document contain self-closing and non self-closing node
when format then all is non self-closing node

## Specification

In case of updates that adhere to specification changes, please reference the used specification.

**Comment by FlorianRappl** [comment]
Sorry I can't follow - can you please give an example @jiangpan ?

Keep in mind that we follow the W3C specification - thus we cannot just change how the HTML is interpreted / DOM is generated.
