### ISSUE TITLE
How to use .Value

### ISSUE THREAD

**Issue by ben1628** [AngleSharp/AngleSharp#829]
var queryInput = form.Elements["q"] as IHtmlInputElement;

if (queryInput != null)
{
   queryInput.Value = "anglesharp";
}

Cannot use .Value, it complains that it's not part of IHtmlInputElement extension

After I do this, can I retrieve the value to make sure it's set properly.

The submitsync doesn't seem to pick up those value and the authentication fails.

**Comment by FlorianRappl** [comment]
Can you bring up a bit more code (e.g., the HTML used to generate the DOM) for context?

**Comment by ben1628** [comment]
Thanks for giving me a pointer

<form name="loginform" class="login-form" id="loginform" role="form" action="/upw" method="post">
					                        	<input name="id" class="dummy1" id="id"  value="">
					                        	<input name="class" class="test" id="class" >
					                        	<input name="pw" class="pw" id="password" type="password" placeholder="Enter your Authenticator Password">
																	</div>
																	</div>

																	<input name="j_class" id="j_pin" type="hidden">
																	<input name="j_pw" id="j_pw" type="hidden">
					                        <button name="login" id="login" type="button"><strong>Click Here to Log On</strong></button>
					                    </form>

It looks like it has couple of hidden field and those must be filled as well. After that, it complains that browser does not support javascript.

So I did


            var config = Configuration.Default
          .WithDefaultLoader()
          .WithJavaScript()
          //.WithDefaultCookies();
          .WithCookies();

but then it errors out with

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'AngleSharp.Services.IScriptingProvider' from assembly 'AngleSharp, Version=0.13.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'.
  Source=AngleSharp.Scripting.JavaScript
  StackTrace:
   at AngleSharp.JsConfigurationExtensions.WithJavaScript(IConfiguration configuration)
   at AssetBot1.Program.<Main>d__0.MoveNext() in C:\Source\AssetBot1\AssetBot1\Program.cs:line 22

So I'm getting closer.

**Comment by FlorianRappl** [comment]
If you are using a new version of AngleSharp then you must use AngleSharp.Js. AngleSharp.Scripting.JavaScript is not supported and only works with versions pre 0.10.

**Comment by ben1628** [comment]
Thanks. That helps.

Now I'm using
    var config = Configuration.Default
          .WithDefaultLoader()
          .WithJs()
          //.WithDefaultCookies();
          .WithCookies();

and I'm getting this error

Since your browser does not support JavaScript,\n                you must press the Continue button once to proceed

Any suggestions?

**Comment by FlorianRappl** [comment]
Probably the JS is too complex and crashes. AngleSharp.Js is still experimental and does not work on state of the art web apps. You should see some output in the debug console.
