### ISSUE TITLE
Question regarding grabbing all links

### ISSUE THREAD

**Issue by vbisbest** [AngleSharp/AngleSharp#830]
I was wondering if this project has the ability to scrape an entire page for all links and navigation events (think of an automated crawler).  For instance, I know I can use a query selector to grab all HREF and SRC links.  But I also want to grab all dynamic/JS links as well.   So if I click on a form submission, I want the ability to grab the request before it is sent to the server (cancel the navigation event).  It would also need to include the post data for the submission.  Does this library have this ability?

Thanks!

**Comment by FlorianRappl** [comment]
Nope - there is no JS capability integrated in AngleSharp.

There is AngleSharp.Js and for simple script files its working. For more complex ones I'm afraid at this point not.

If the script is working then yes, obviously you can do it quite easily (AngleSharp's requester has middleware capabilities allowing interception of any request).

Hope that helps!
