### ISSUE TITLE
Consider updating the .NET dependency version to 4.6.1

### ISSUE THREAD

**Issue by skolima** [AngleSharp/AngleSharp#831]
# Bug Report

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

The package https://www.nuget.org/packages/AngleSharp declares NuGet dependencies for .NET Framework 4.6 and .NET Standard 2.0, without declaring 4.6.1 dependencies. This is against https://docs.microsoft.com/en-us/dotnet/standard/net-standard guidelines and sometimes results in difficult to hunt down build/restore issues.

For me, this breaks PreMailer update - the previous one depended on AngleSharp 0.9.1, which declared only pre-.NETStandard2.0 dependencies and restored correctly. The current AngleSharp triggers the buggy restore mechanisms for .NETFramework4.6

**Expected behavior:** NuGet gallery dependencies listed for .NETFramework 4.6.1 and .NETStandard 2.0

**Actual behavior:** .NETFramework 4.6 is listed as a valid target, while it has known bugs when restoring packages

## Possible Solution

Update build and NuGet package targets to net461 instead of net46.

**Comment by FlorianRappl** [comment]
Where do we start where do we end? I mean this sounds like a bug in Nuget with the package resolution.

Our intention here was to say "if its .NET Framework 4.6 or higher you can use this".

If you have a specific proposal then please make a PR - any contribution / discussion welcome :beers:!

**Comment by FlorianRappl** [comment]
Landed in `devel`.
