### ISSUE TITLE
WithJavaScript AngleSharp.Services.IScriptingProvider could not found

### ISSUE THREAD

**Issue by JLesuperb** [AngleSharp/AngleSharp#834]
'Could not load type 'AngleSharp.Services.IScriptingProvider' from assembly 'AngleSharp, Version=0.13.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'.'

**var config = Configuration.Default.WithJavaScript();**

**Comment by FlorianRappl** [comment]
Sorry the provided information is insufficient. You'll need to provide a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) to reproduce the issue. What's your configuration like? I assume there is a problem with your appconfig.
