### ISSUE TITLE
I got an error about nth-child it looks like a bug

### ISSUE THREAD

**Issue by SayHelloGsx** [AngleSharp/AngleSharp#835]
![QQ截图20191207103354](https://user-images.githubusercontent.com/36391162/70367716-a26b4700-18dd-11ea-8a9a-9aac2eca7031.png)

This is a part of the original HTML code

my c# code 
`var nameEle = element.QuerySelector("div.file-name");`
`var fileName = nameEle.TextContent;`
`var nameSelector = nameEle.QuerySelector("a").GetSelector();`

fileName  is myfile
nameSelector is `#layoutMain>div>div>div:nth-child(2)>div>div>div:nth-child(3)>div>div>dd:nth-child(1)>div:nth-child(2)>div:nth-child(1)>a`

There's something wrong with `dd:nth-child(1)>div:nth-child(2)>div:nth-child(1)>a`
It should be: `dd:nth-child(1)>div:nth-child(3)>div:nth-child(1)>a` 

I'm sure the page is loaded
I'm not sure if it's my problem

**Comment by FlorianRappl** [comment]
Something seems to be fishy somewhere.

I just wrote the following test:

```cs
[Test]
public void DivNthChildSelector_Issue835()
{
    var html = @"<dd>
  <span>
    <span>Sub1</span>
  </span>
  <div>First</div>
  <div>
    <div>
      <a>Second</a>
    </div>
  </div>
  <div>Third</div>
  <div>Fourth</div>
  <div>
    <span>Fifth</span>
  </div>
</dd>";
    var document = html.ToHtmlDocument();
    var link = document.Body.QuerySelector("dd:nth-child(1)>div:nth-child(3)>div:nth-child(1)>a");
    Assert.IsNotNull(link);
    Assert.AreEqual("Second", link.TextContent);
}
```

... and it passes. Thus I don't believe there is an issue with the selector. How's your configuration looking?

**Comment by SayHelloGsx** [comment]
var htmlString= @"<dd>
           <span>
           <span>Sub1</span>
           </span>
           <div>First</div>
            <div>
            <div>
            <a>Second</a>
            </div>
            </div>
            <div>Third</div>
            <div>Fourth</div>
            <div>
            <span>Fifth</span>
            </div>
            </dd>";
            var context = BrowsingContext.New(Configuration.Default);
            var parser = context.GetService<IHtmlParser>();
            var document = parser.ParseDocument(htmlString);

            var link = document.Body.QuerySelector("dd:nth-child(1)>div:nth-child(3)>div:nth-child(1)>a");
            Console.WriteLine(link.TextContent);

            var eles = document.QuerySelectorAll("dd");
            foreach (var ele in eles)
            {
                var fileEle = ele.QuerySelector("a");
                Console.WriteLine($"{fileEle.TextContent}---{fileEle.GetSelector()}");
            }
I used your code
The first Console.WriteLine is 'Second' it's ok,
but the second Console.WriteLine is 'Second---body>dd>div:nth-child(2)>div>a'
When I convert an IElement object to a selector string, the results were wrong

**Comment by SayHelloGsx** [comment]
var context = BrowsingContext.New(Configuration.Default);
            var parser = context.GetService<IHtmlParser>();
            var document = parser.ParseDocument(htmlString);

            var link = document.Body.QuerySelector("body>dd>div:nth-child(3)>div>a");
            Console.WriteLine(link.TextContent);

            var eles = document.QuerySelectorAll("dd");
            foreach (var ele in eles)
            {
                var fileEle = ele.QuerySelector("a");
                Console.WriteLine($"{fileEle.TextContent}---{fileEle.GetSelector()}");
            }
I change some code 
This time result is:
Second
Second---body>dd>div:nth-child(2)>div>a

**Comment by FlorianRappl** [comment]
I see so your problem is not in the CSS selector (e.g., used in query selector), but rather in the `GetSelector` utility? Do I see that correctly?

**Comment by SayHelloGsx** [comment]
> I see so your problem is not in the CSS selector (e.g., used in query selector), but rather in the `GetSelector` utility? Do I see that correctly?

https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Dom/ElementExtensions.cs 
here GetSelector method

**Comment by FlorianRappl** [comment]
I know the `GetSelector` method, but I was wondering if the behavior of that method is your issue ...

**Comment by SayHelloGsx** [comment]
> I see so your problem is not in the CSS selector (e.g., used in query selector), but rather in the `GetSelector` utility? Do I see that correctly?

Yes  CSS selector is ok. It gets the right result. The result of the GetSelector method is wrong

**Comment by FlorianRappl** [comment]
Fix published in `devel`. Preview should be up on NuGet soon, too.
