### ISSUE TITLE
"x-cp20936" cannot be used for some  Chinese coding, which will lead to some Chinese miscodes

### ISSUE THREAD

**Issue by Monns** [AngleSharp/AngleSharp#836]
**File：src/AngleSharp/Text/TextEncoding.cs  
line：507  var chinese = GetEncoding("GB18030");**

"X-cp20936" is "GB2312-80". There are too few character sets supported. Please change it to "GB18030" to resolve some Chinese characters. More characters can be supported.

**for example this url：**
http://xh.5156edu.com/html2/p101.html
Cannot parse "厑" 

Thanks！

**Comment by FlorianRappl** [comment]
Sorry English only.

Is this the same as https://github.com/AngleSharp/AngleSharp/issues/326#issuecomment-554525299?

**Comment by Monns** [comment]
> Sorry English only.
> 
> Is this the same as [#326 (comment)](https://github.com/AngleSharp/AngleSharp/issues/326#issuecomment-554525299)?

Sorry, it has been modified

**Comment by FlorianRappl** [comment]
Landed in `devel` - is in the preview.
