### ISSUE TITLE
Fix Version 0.13.0 to Run on .NET Framework 4.7.2

### ISSUE THREAD

**Issue by MK0204** [AngleSharp/AngleSharp#837]
I installed AngleSharp package version 0.13.0 and PreMailer.Net package version 2.1.3 from Nuget. At runtime I get an exception stating that the 'Source' is AngleSharp and the exception is that it cannot find System.Text.Encoding.CodePages version 4.0.2.0. I have System.Text.Encoding.CodePages version 4.7.0 installed. I'm using Visual Studio 2019 Professional, .NET Framework version 4.7.2
![AngleSharp_exception](https://user-images.githubusercontent.com/5655468/72185157-2a9ea980-33c0-11ea-846b-ee4320da9f6f.png)

**Comment by FlorianRappl** [comment]
Existing versions cannot be fixed. NuGet packages are immutable.

Have you tried running the preview of 0.14? See #831.

**Comment by serodya** [comment]
I installed **AngleSharp, PreMailer.Net, System.Text.Encoding.CodePages** in **.NET Framework 4.7.2**, with versions as shown in the image

![premailer-nuget](https://user-images.githubusercontent.com/18291695/74782249-b382ed80-5268-11ea-9a19-4b1859cdc0a1.png)

PreMailer.Net is trying to load AngleSharp version 0.13.0.0 even though the requirement is equal or greater than 0.13.0.0

![angleSharp-error](https://user-images.githubusercontent.com/18291695/74782690-8d118200-5269-11ea-94f4-003a29aa50f4.png)

Any advise on how to resolve this issue?

**Comment by FlorianRappl** [comment]
Do you maybe have a binding created (e.g., app.config)?

**Comment by serodya** [comment]
No, this is a web application and there is no any reference in the web.config file. 
I am using Nuget PackageReference

![PackageReference](https://user-images.githubusercontent.com/18291695/74784075-b8e23700-526c-11ea-9c6c-79470fac9af5.png)
