### ISSUE TITLE
Replace "iso-22-cn" encoding with substitute

### ISSUE THREAD

**Issue by AutismPatient** [AngleSharp/AngleSharp#839]
**I got an encoding error running any of the contexts:**
`var doc = await BrowsingContext.New().OpenAsync("https://stackoverflow.com/");`
My package version has been updated to the preview version,I don't know if this is a bug or my problem.
![QQ图片20200129004916](https://user-images.githubusercontent.com/37021551/73285829-95116f80-4231-11ea-88de-96e8704d9ddb.png)

**Comment by FlorianRappl** [comment]
We'll need a few more infos like on what platform you are running (e.g., .NET core), what version of AngleSharp, how the config was etc.

**Comment by AutismPatient** [comment]
Default configuration, and.net core 3.1-AngleSharp v 0.13.0

**Comment by AutismPatient** [comment]
[https://github.com/dotnet/corefx/issues/42844](url)
This seems to be a problem with.net CORE, but I can't figure out how to configure the code instead

**Comment by AutismPatient** [comment]
After my  test:
**Either.net CORE or the.net Framework reports this error**
@FlorianRappl

**Comment by FlorianRappl** [comment]
> Try using "x-cp50227" rather than "iso-22-cn"

can be done within AngleSharp as a fallback. We'll roll it out in the next 0.14 preview.

**Comment by AutismPatient** [comment]
Thank you for the answer. I hope to launch it soon, because I'm using it in a production environment

**Comment by FlorianRappl** [comment]
Landed in `devel` - is in the preview.

**Comment by fangfsz** [comment]
My situation is as below,   
1. AngleSharp 1.0.1
2. Windows 10 22H2(OS Build: 19045.2965)  and VS2022
3. Dotnet 6

code1:   Encoding.GetEncoding("iso-2022-cn");
code2:     IDocument document = parser.ParseDocument(body);
code3:     BrowsingContext.New(Configuration.Instance); await context.OpenAsync(body);
also met the exception regarding "iso-2022-cn" encoding...  


![01](https://github.com/AngleSharp/AngleSharp/assets/19644061/fca02b2c-b199-412b-b787-1ced93b3604e)
![02](https://github.com/AngleSharp/AngleSharp/assets/19644061/d2a3a2b3-963f-4c5c-8b19-b7ef405869b4)

**Comment by FlorianRappl** [comment]
Hi @fangfsz the error message is also telling you what to do; register the encoding. Not sure what you want AngleSharp to do here - if the encoding is missing the website would not be retrieved as it should, therefore throwing an exception here is critical. You can register the encoding either with the original encoding or some available fallback.

**Comment by sgf** [comment]
~~i have the same problem.~~
~~https://github.com/AngleSharp/AngleSharp.Css/issues/177~~

~~im not sure.my string is .net String.~~
~~i hope when AngleSharp direct call PreaseDocument(HtmlString) don't to check the charset meta in html.~~
~~because the programer has been do that by them self(this .net string has been UTF-16 encoding).~~

soloved,just need ignore the exception.
exception reason:AngleSharp trying to Create a IOS-2022-CN Encoding,but .net can't do that.
