### ISSUE TITLE
{System.TypeInitializationException: The type initializer for 'AngleSharp.TextEncoding' threw an exception. 

### ISSUE THREAD

**Issue by pmoran1947** [AngleSharp/AngleSharp#84]
The error occurs when I try invoke DocumentBuilder on a web page
The message associated with the exception is:

'euc-jp' is not a supported encoding name.
Parameter name: name

Is there anything I can do to avoid the error.

**Comment by FlorianRappl** [comment]
Yes - use the latest version. The bug you describe should not occur in the latest version (see #79). If you still encounter the issue then I'll need more information (e.g., platform, project-type, ...).
