### ISSUE TITLE
QuerySelector changed normal behavior?

### ISSUE THREAD

**Issue by kotyukov** [AngleSharp/AngleSharp#840]
# Bug Report
I'm not sure if its a bug, or it's a absolutely normal thing. Just saw Migration Guide and FAQ and I found nothing about my problem.

## Prerequisites

I am usually use v0.9.9.0 in my last projects. Now for new project I try v0.13.0.0 and I'v got [AngleSharp.Dom.DomException: "The string did not match the expected pattern."]

## Description

For example we have next html
```html
<body>
	<div class="awesome1">
		value
	</div>
	<div class="awesome2">
		<span> abc </span>
		<span> def </span>
		<span> ghi </span>
	</div>
	<div class="awesome3">
		another value
	</div>
</body>
```
In the v0.9.9.0 if I want to get a second span element I type
```c#
IElement secondSpan = document.QuerySelector("div.awesome2 > span[2]");
```
but for latest version it's do not work no more.
```c#
// This is still work
IElement span = document.QuerySelector("div.awesome2 > span");
string value = span.TextContent; // abc
```
Indexer is broken?

## Steps to Reproduce

```c#
public void GetSecondSpan()
        {
            string html = "<body><div class=\"awesome1\">value</div><div class=\"awesome2\"><span>abc</span><span>def</span><span>ghi</span></div><div class=\"awesome3\">another value</div></body>";
            HtmlParser parser = new HtmlParser();
            IHtmlDocument document = parser.ParseDocument(html);
            IElement secondSpan = document.QuerySelector("div.awesome2 > span[2]");
            string value = secondSpan.TextContent;
        }
```

**Expected behavior:** Get the second span element.

**Actual behavior:** AngleSharp.Dom.DomException: "The string did not match the expected pattern."

**Environment details:** Windows 7, .NET Framework 4.7.03062, AngleSharp 0.13.0.0

**Comment by FlorianRappl** [comment]
Have you tried running it in the browser?

The query string `div.awesome2 > span[2]` is not a valid syntax. I guess what you want is

```cs
document.QuerySelector("div.awesome2 > span:nth-child(2)");
```

The old version of AngleSharp was not really strict in that regard (actually, I'm surprised it was somewhat working). You can, however, use the query parser yourself and change the behavior (that's what the CSS parser is doing / same in the browser). It should be the old behavior if you just ignore the error flag.

The design goal of AngleSharp is to be aligned with browser behavior. As such when using `QuerySelector` or related methods we check the error flag and throw if a syntax error was found.

**Comment by kotyukov** [comment]
Ok, I got it. Sorry if I wasted your time.
When I start to use AngleSharp some years ago I found somewhere code examples with this variant of query string. I decided it's valid because it's look like xPath style query and it's actually working.
Thanks for your help.

**Comment by FlorianRappl** [comment]
> Ok, I got it. Sorry if I wasted your time.

Nope it's totally fine. Nothing to be sorry about!

Hope I could help you.

If you want to use XPath, maybe have a look at [AngleSharp.XPath](https://github.com/AngleSharp/AngleSharp.XPath).
