### ISSUE TITLE
WithJavaScript could not found

### ISSUE THREAD

**Issue by mikenlanggio** [AngleSharp/AngleSharp#841]
I'm using AngleSharp version 0.13.0 with Dot Net Core 3.0.
I'm trying to Connecting JavaScript Evaluation like [this document](https://anglesharp.github.io/docs/Examples.html#connecting-javascript-evaluation).

But the WithJavaScript() could not found anymore.
How can I fix that?
[Image](https://www.upsieutoc.com/images/2020/02/05/1f74944fcf43c10d7.png)
Thank you

Update 1: Okay, I fixed that problem by install package `AngleSharp.Scripting.JavaScript`.
But, It throw exception when `Runtime`. The package not suitable on DotNetCore?

**Comment by FlorianRappl** [comment]
Sorry, unfortunately, the document is outdated. The package is called `AngleSharp.Js`.

See: https://github.com/AngleSharp/AngleSharp/blob/master/doc/Migration.md

I'll leave this bug open as a documentation issue!

**Comment by mikenlanggio** [comment]
Seem like it's not working in modern framework like AngularJs, ReactJs?

**Comment by FlorianRappl** [comment]
> Seem like it's not working in modern framework like AngularJs, ReactJs?

That's correct. As stated in the README its experimental and does not work with advanced scripts.

If you like to change that then please contribute to the development of `AngleSharp.Js`. Thanks!
