### ISSUE TITLE
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0

### ISSUE THREAD

**Issue by churstz** [AngleSharp/AngleSharp#842]
# Bug Report
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

The short and sweet is the AngleSharp 0.13.0.0 dll has three multi-target dependencies (net46, netstandard1.3 and netstandard2.0).  Of these three targeted dlls, the first 2 contain references the System.Text.Encoding.CodePages v4.0.2.0 and only the netstandard2.0 contains a reference to the System.Text.Encoding.CodePages v4.1.1.0.  

This was determined by downloading the raw nupkg from https://www.nuget.org/packages/AngleSharp/0.13.0 and extracting the zipped contents and inspecting each targeted DLL with .NET Reflector

When compiling my console project the \debug output directory contains System.Text.Encoding.CodePages v4.6.26515.6 and executes as expected.  When I call this same functionality from powershell 5.1 it blows chunks with the same reported error (https://github.com/AngleSharp/AngleSharp/issues/740)

Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

In the case of powershell ISE 5.1 the TargetFramework is 4.5.1 instead of my console app's 4.7.1 (AppDomain.CurrentDomain.SetupInformation.TargetFrameworkName), but all the assemblies should be the same as I'm exporting the dependencies at build time to \Debug.  I suspect there are a few issues going on here on both the AngleSharp as well as my side.  This bug report is to fix the targeted deployment for the net46 and netstandard1.3 builds to reference the newer System.Text.Encoding.CodePages as is identified in the nuget package documentation

[Description of the bug]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** when newing up the HtmlParser it doesn't chuck a wobbly with an IO Exception

**Actual behavior:** IOException 
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Environment details:** W10, VS2019, Target Framework .NET Framework 4.7.1, C# library/console

## Possible Solution

N/A

**Comment by FlorianRappl** [comment]
Have you looked at #740, #774 or #837?

This is - after all - some problem with NuGet / its dependency resolution. Any contribution welcome!

**Comment by churstz** [comment]
I have looked at those.  

Basically the AngleSharp 0.13.0 targets the Framework v4.6 as one of the multi-target options 
and because it has a nuget reference to the System.Text.Encoding.CodePages "package" (version 4.5.0 or greater - note has nothing to do with the .NET Framework version) it adds the DLL dependency from the \net46 directory of that package.

The System.Text.Encoding.CodePages nuget package contains a few multi-target versions (including net46 and net461)
The \net46 target contains the System.Text.Encoding.CodePages.dll which has an assemblyversion of 4.0.2.0 and an AssemblyFileVersion of 4.6.24705.1
The \net461 target contains the System.Text.Encoding.CodePages.dll which has an assemblyversion of 4.1.1.0 and an AssemblyFileVersion of 4.6.26515.6

When AngleSharp is compiled then packaged up, it references the 4.0.2.0 version of System.Text.Encoding.CodePages.dll internally

In the multi-target project and nuspec if you change or add net461 dependency the same System.Text.Encoding.CodePages package (4.5.0) will extract from the \net461 and add the dependency for the v4.1.1.0 DLL.

I believe what's occurring are projects with newer target framework versions are picking up the most recent dependency from the nuget package and because there is a newer one (i.e. \net461) in the the System.Text.Encoding.CodePages package that DLL is what gets added to our projects thus causing the mismatch and the IOException.

**Comment by FlorianRappl** [comment]
> In the multi-target project and nuspec if you change or add net461 dependency the same System.Text.Encoding.CodePages package (4.5.0) will extract from the \net461 and add the dependency for the v4.1.1.0 DLL.

Sounds like you figured it out. Thanks for investigation, much appreciated! Want to do a PR?

You could do it as a hotfix for 0.13.0. The `devel` branch is already at 0.14, but you could just fork / checkout from `master`, change it there and make a PR targeting `master` again.

**Comment by FlorianRappl** [comment]
(I've added the 0.14 milestone, but in best case a hotfix for 0.13 would be released).

**Comment by FlorianRappl** [comment]
Landed in `devel` and the preview.

**Comment by dev-bre** [comment]
Has this been deployed on NuGet? I am still having the same issue. 
I am running v 0.16.1

**Comment by simonprice33** [comment]
did this get resolved as I too am getting the issue in 0.16.1 but with error {"Could not load file or assembly 'System.Text.Encoding.CodePages, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"System.Text.Encoding.CodePages, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}

**Comment by FlorianRappl** [comment]
Well, this is resolved (almost 3 years ago). If this happens it is a NuGet issue and nothing AngleSharp can do.

**Comment by donnaken15** [comment]
I'm trying out Mono C# Compiler on one of my projects made in VS22. I ran msbuild on it and it apparently returns this CodePages error when running CSC.

log if it's necessary:
csc:
```
E:\DotNetZip\Zip Reduced>"C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn\csc.exe" /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /errorreport:prompt /warn:4 /doc:bin\Debug\Ionic.Zip.xml /define:TRACE;DEBUG;AESCRYPTO;BZIP /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" /reference:"C:\Program Files\Mono\lib\mono\4.5\Facades\System.Text.Encoding.CodePages.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\Ionic.Zip.dll /target:library /utf8output /langversion:7.3 ..\Zip\ComHelper.cs ..\Zip\EncryptionAlgorithm.cs ..\Zip\Events.cs ..\Zip\Exceptions.cs ..\Zip\ExtractExistingFileAction.cs ..\Zip\FileSelector.cs ..\Zip\OffsetStream.cs ..\Zip\Shared.cs ..\Zip\WinZipAes.cs ..\Zip\ZipConstants.cs ..\Zip\ZipCrypto.cs ..\Zip\ZipDirEntry.cs ..\Zip\ZipEntry.cs ..\Zip\ZipEntry.Extract.cs ..\Zip\ZipEntry.Read.cs ..\Zip\ZipEntry.Write.cs ..\Zip\ZipEntrySource.cs ..\Zip\ZipErrorAction.cs ..\Zip\ZipFile.AddUpdate.cs ..\Zip\ZipFile.Check.cs ..\Zip\ZipFile.cs ..\Zip\ZipFile.Events...\Zip\ZipFile.Extract.cs ..\Zip\ZipFile.Read.cs ..\Zip\ZipFile.Save.cs ..\Zip\ZipFile.SaveSelfExtractor.cs ..\Zip\ZipFile.Selector.cs ..\Zip\ZipFile.x-IEnumerable.cs ..\Zip\ZipInputStream.cs ..\Zip\ZipOutputStream.cs ..\Zip\ZipSegmentedStream.cs ..\BZip2\BitWriter.cs ..\BZip2\BZip2Compressor.cs ..\BZip2\BZip2InputStream.cs ..\BZip2\BZip2OutputStream.cs ..\BZip2\ParallelBZip2OutputStream.cs ..\BZip2\Rand.cs ..\Zlib\Deflate.cs ..\Zlib\DeflateStream.cs ..\Zlib\GZipStream.cs ..\Zlib\Inflate.cs ..\Zlib\InfTree.cs ..\Zlib\ParallelDeflateOutputStream.cs ..\Zlib\Tree.cs ..\Zlib\Zlib.cs ..\Zlib\ZlibBaseStream.cs ..\Zlib\ZlibCodec.cs ..\Zlib\ZlibConstants.cs ..\Zlib\ZlibStream.cs ..\CommonSrc\CRC32.cs Properties\AssemblyInfo.cs ..\SolutionInfo.cs "obj\Debug\.NETFramework,Version=v4.0.AssemblyAttributes.cs"
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```
msbuild log:
```
E:\DotNetZip\Zip Reduced>msbuild
Microsoft (R) Build Engine version 16.10.1 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/21/2023 12:33:39 AM.
Project "E:\DotNetZip\Zip Reduced\Zip Reduced.csproj" on node 1 (default targets).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the in
put files.
C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Microsoft.CSharp.CurrentVersion.targets(137,9): warning MSB3884: Could n
ot find rule set file "AllRules.ruleset". [E:\DotNetZip\Zip Reduced\Zip Reduced.csproj]
CoreCompile:
  C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /erro
  rreport:prompt /warn:4 /doc:bin\Debug\Ionic.Zip.xml /define:TRACE;DEBUG;AESCRYPTO;BZIP /highentropyva- /reference:"C:\
  Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" /reference:"C:\Program F
  iles (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" /reference:"C:\Program Files (
  x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" /debug+ /debug:full /filealign:512 /optim
  ize- /out:obj\Debug\Ionic.Zip.dll /target:library /utf8output /langversion:7.3 ..\Zip\ComHelper.cs ..\Zip\EncryptionAl
  gorithm.cs ..\Zip\Events.cs ..\Zip\Exceptions.cs ..\Zip\ExtractExistingFileAction.cs ..\Zip\FileSelector.cs ..\Zip\Off
  setStream.cs ..\Zip\Shared.cs ..\Zip\WinZipAes.cs ..\Zip\ZipConstants.cs ..\Zip\ZipCrypto.cs ..\Zip\ZipDirEntry.cs ..\
  Zip\ZipEntry.cs ..\Zip\ZipEntry.Extract.cs ..\Zip\ZipEntry.Read.cs ..\Zip\ZipEntry.Write.cs ..\Zip\ZipEntrySource.cs .
  .\Zip\ZipErrorAction.cs ..\Zip\ZipFile.AddUpdate.cs ..\Zip\ZipFile.Check.cs ..\Zip\ZipFile.cs ..\Zip\ZipFile.Events.cs
   ..\Zip\ZipFile.Extract.cs ..\Zip\ZipFile.Read.cs ..\Zip\ZipFile.Save.cs ..\Zip\ZipFile.SaveSelfExtractor.cs ..\Zip\Zi
  pFile.Selector.cs ..\Zip\ZipFile.x-IEnumerable.cs ..\Zip\ZipInputStream.cs ..\Zip\ZipOutputStream.cs ..\Zip\ZipSegment
  edStream.cs ..\BZip2\BitWriter.cs ..\BZip2\BZip2Compressor.cs ..\BZip2\BZip2InputStream.cs ..\BZip2\BZip2OutputStream.
  cs ..\BZip2\ParallelBZip2OutputStream.cs ..\BZip2\Rand.cs ..\Zlib\Deflate.cs ..\Zlib\DeflateStream.cs ..\Zlib\GZipStre
  am.cs ..\Zlib\Inflate.cs ..\Zlib\InfTree.cs ..\Zlib\ParallelDeflateOutputStream.cs ..\Zlib\Tree.cs ..\Zlib\Zlib.cs ..\
  Zlib\ZlibBaseStream.cs ..\Zlib\ZlibCodec.cs ..\Zlib\ZlibConstants.cs ..\Zlib\ZlibStream.cs ..\CommonSrc\CRC32.cs Prope
  rties\AssemblyInfo.cs ..\SolutionInfo.cs "obj\Debug\.NETFramework,Version=v4.0.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn
C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB6006: "csc.exe" exi
ted with code 1. [E:\DotNetZip\Zip Reduced\Zip Reduced.csproj]
Done Building Project "E:\DotNetZip\Zip Reduced\Zip Reduced.csproj" (default targets) -- FAILED.


Build FAILED.

"E:\DotNetZip\Zip Reduced\Zip Reduced.csproj" (default target) (1) ->
(ResolveCodeAnalysisRuleSet target) ->
  C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Microsoft.CSharp.CurrentVersion.targets(137,9): warning MSB3884: Could
 not find rule set file "AllRules.ruleset". [E:\DotNetZip\Zip Reduced\Zip Reduced.csproj]


"E:\DotNetZip\Zip Reduced\Zip Reduced.csproj" (default target) (1) ->
(CoreCompile target) ->
  C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB6006: "csc.exe" e
xited with code 1. [E:\DotNetZip\Zip Reduced\Zip Reduced.csproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.78
```
