### ISSUE TITLE
AngleSharp.BrowsingContext: Cannot find an overload for "new"

### ISSUE THREAD

**Issue by Wardrop** [AngleSharp/AngleSharp#844]
Firstly, apologies if there's a better place to ask this.

I'm trying to use AngleSharp via PowerShell, but I keep getting the following error when trying to create a new BrowsingContext: `Cannot find an overload for "new" and the argument count: "1"`. This is likely a powershell quirk of some kind, but I'm completely stumped.

```
Add-Type -LiteralPath '.\AngleSharp.0.13.0\lib\net46\AngleSharp.dll'
Add-Type -LiteralPath '.\System.Text.Encoding.CodePages.4.5.0\lib\net46\System.Text.Encoding.CodePages.dll'

$config = [AngleSharp.Configuration]::Default
[AngleSharp.BrowsingContext]::New($config) # Cannot find an overload for "new" and the argument count: "1".
```
I've also tried giving type hints (e.g. [AngleSharp.BrowsingContext]::New([AngleSharp.IConfiguration]$config)), but the result in the same. 

Also, is there any online API reference/documentation?

Thanks

**Comment by Wardrop** [comment]
`[AngleSharp.BrowsingContext]::New.Invoke([AngleSharp.Configuration]::Default))` did the trick; looks like "new" is a resrved/built-in static method that PowerShell uses for instantiating new objects so it was trying to instantiate [AngleSharp.BrowsingContext] using the contructor instead of the "New" method.

I ran into another problem though. There no "OpenAsync" method on `AngleSharp.BrowsingContext`. Is the example documentation out of date?

**Comment by FlorianRappl** [comment]
No it's still `OpenAsync`, but this is a method (i.e., part of an instance of `IBrowsingContext`).

Regarding the `New` - I assumed that when I read the OP. I don't want to break the code here, but we can also add another way (e.g., allowing `new BrowsingContext`) to avoid this kind of scenario for PowerShell in the future.

**Comment by FlorianRappl** [comment]
Landed in `develop` (preview available on NuGet).
