### ISSUE TITLE
How to use custom cookies to do a Get request in AngleSharp?

### ISSUE THREAD

**Issue by lajiwangpan2** [AngleSharp/AngleSharp#845]
I have the following C# code using AngleSharp. As you can see the code starts a Get request to a URL. I've already read my cookies from the file cookies.txt (got by executing JavaScript statement `document.cookie`). How to use the cookie while making the request?

    var current_executable = Assembly.GetExecutingAssembly().Location;
    var current_dir = Path.GetDirectoryName(current_executable);
    string cookies = File.ReadAllText(Path.Join(current_dir, "cookies.txt"));
    if (cookies?.Length < 100)
    {
        Console.WriteLine("Please specify correct cookies in cookies.txt and try again!");
        return;
    }

    var mask_url = "https://example.com";

    var config = Configuration.Default.WithDefaultLoader();
    var context = BrowsingContext.New(config);
    var document = await context.OpenAsync(mask_url);
    var name = document.QuerySelector("a.username");
    Console.WriteLine(name.ToString());

**Comment by FlorianRappl** [comment]
You would need to use `WithCookies`.

This will use the .NET Cookie Container. If you want an improved version you should have a look at [AngleSharp.Io](https://github.com/AngleSharp/AngleSharp.Io).
