### ISSUE TITLE
Form submission differences with chrome

### ISSUE THREAD

**Issue by tsu1980** [AngleSharp/AngleSharp#847]
Hi, thanks for continuing development! I found differences with chrome for Form submission.

## Steps to Reproduce

**HTML**

``` html
<form action="action.php" method="post">
 Name: <input type="text" name="name" /><br>
 Age: <input type="text" name="age" /><br>
 Sex: <select name="sex">
    <option value="">--</option>
    <option value="male">Man</option>
    <option value="female">Woman</option>
 </select><br>
 Favarite color: <label><input type="radio" name="color" value="blue">Blue</label>
    <label><input type="radio" name="color" value="red" checked>Red</label>
    <label><input type="radio" name="color" value="red" checked>Red</label>
    <label><input type="radio" name="color" value="yellow">Yellow</label><br>
 <input type="submit" />
</form>
```

1. Set input values to "name" and "age"
2. submit

**Expected behavior:**

Chrome 80
```
name=Bob&age=3&sex=&color=red
```

**Actual behavior:**

AngleSharp master/devel
```
name=Bob&age=3&color=red&color=red
```

There are two ploblems.
1. `sex` value is not sent. It should send default value if no selected.
1. `color` value sent twice. It should send only the last checked value.

**Comment by FlorianRappl** [comment]
Great, thanks for the report!

Mind making a PR (always appreciated)? I can guide you where to start looking / improving if you want to! :beers:

**Comment by tsu1980** [comment]
Sure, i will do it.

**Comment by FlorianRappl** [comment]
Landed in `develop`. Thanks for your awesome contribution! :rocket:
