### ISSUE TITLE
Url.GetHashCode is not in agreement with Url.Equals

### ISSUE THREAD

**Issue by alex-fomin** [AngleSharp/AngleSharp#850]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

`Url.GetHashCode()` returns `base.GetHashCode()` which is based on object reference, while `Equals` actually compare url's parts.

## Steps to Reproduce
```
var url1 = new Url("https://example.com");
var url2 = new Url("https://example.com");
Console.WriteLine(url1.GetHashCode() == url.GetHashCode()); // False
Console.WriteLine(url1.Equals(url); // True

```
## Possible Solution

Implement `GetHashCode` based on `Equals` method.

**Comment by FlorianRappl** [comment]
Available in `devel` and the preview version.
