### ISSUE TITLE
New AttributeName property

### ISSUE THREAD

**Issue by joao2391** [AngleSharp/AngleSharp#852]
# Add attribute name "onclick"

## Description

Return the "onclick" attribute of its html element

## Background

When a button or any html element has a "onclick" event, I would like to know what event it is calling

## Specification

Add a property called "OnClick" in AngleSharp.Core/Dom/AttributeName.cs
Add unit test in AngleSharp.Core.Tests/DOMTests

**Comment by FlorianRappl** [comment]
All the event names are given in `EventNames` (https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Dom/EventNames.cs).

Can you outline your use case in code / what do you want and why is what you want not working right now? Thanks!

**Comment by joao2391** [comment]
Please correct me if I'm wrong, but this class you showed is for working with the EventListener, isn't it?
My scenario is this:
I want to know the name of an onclick event that it is in a html element.
Example:
`
    <div onclick="window.location.href='/questions/153065/como-adicionar-imagem-ao-launchscreen-storyboard'" class="cp">
    `
I want to get the value of onclick, **"window.location.href='/questions/153065/como-adicionar-imagem-ao-launchscreen-storyboard'"**

**Comment by FlorianRappl** [comment]
Have you tried:

```cs
var value = element.GetAttribute("onclick");
```

One full working example (in LINQPad):

```cs
var context = BrowsingContext.New();
var document = await context.OpenAsync(res => res.Content(
  @"<div onclick=""window.location.href='/foo/bar'"" class=""cp"">"
));
var element = document.QuerySelector(".cp");
var value = element.GetAttribute("onclick");
value.Dump(); // window.location.href='/foo/bar'
```

Note that in general every attribute can be read via `GetAttribute`. The C# properties are sometimes modifications / abstractions on top of attributes, sometimes internal states. They usually refer to their W3C specified properties.
