### ISSUE TITLE
Non-ASCII characters like ampersand (&) have their encoding changed, even when they should be considered valid HTML

### ISSUE THREAD

**Issue by CaptainStack** [AngleSharp/AngleSharp#856]
I noticed this issue while using PreMailer.Net and was able to isolate the cause down to AngleSharp. I describe the issue in some detail in an [issue on PreMailer.Net's repository](https://github.com/milkshakesoftware/PreMailer.Net/issues/193).

When the HTML I parse contains a non-ASCII value, like an ampersand, AngleSharp will encode the character. For example:

```C#
static async Task FirstExample()
{
    var config = Configuration.Default;
    var context = BrowsingContext.New(config);
    var document = await context.OpenAsync(req => req.Content("<html><head></head><body><p>&</p></body></html>"));
    Console.WriteLine(document.DocumentElement.OuterHtml);
}
```

The following code will take the input:
```HTML
<html><head></head><body><p>&</p></body></html>
```
And will output:
```HTML
<html><head></head><body><p>&amp;</p></body></html>
```

In my research on this issue, which has been reported and caused issues for many users, I found the following statement from @FlorianRappl in this [closed issue](https://github.com/AngleSharp/AngleSharp/issues/348#issuecomment-221334825).

> This is by specification, see the string escaping that needs to be applied on attribute values..

However, as demonstrated in my above example, this is not just encoding *attribute* values, it is actually encoding innerHTML *content* which unless I am mistaken, is certainly valid HTML. I am not aware of any standards that say that HTML content must only include encoded strings.

**Comment by FlorianRappl** [comment]
> However, as demonstrated in my above example, this is not just encoding attribute values, it is actually encoding innerHTML content which unless I am mistaken, is certainly valid HTML. I am not aware of any standards that say that HTML content must only include encoded strings.

It has nothing to do with attributes. This is the spec. It applies to general parsing and is already in the tokenization phase.

Please try running your example in the browser. A `&` character is `&amp;`. The HTML parser does convert it.

Run the following in your browser:

```html
<html><head></head><body><p>&</p><script>alert(document.querySelector("p").innerHTML)</script></body></html>
```

The output will be:

![image](https://user-images.githubusercontent.com/1766191/76826649-4e95c580-681d-11ea-9a88-6eea5a10a7ff.png)

We cannot (and will not) deviate from the specification.

**Comment by FlorianRappl** [comment]
I also want to mention that we have an alternative non-spec compliant handling of invalid char. references implemented via parser options:

https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Html/Parser/HtmlParserOptions.cs#L77
