### ISSUE TITLE
Cannot override default treatment of attributes with a custom IMarkupFormatter

### ISSUE THREAD

**Issue by CaptainStack** [AngleSharp/AngleSharp#858]
I am using AngleSharp v0.13.0

I am trying to override the default formatting behavior for HTML attributes by using a custom IMarkupFormatter and passing in an override for Attribute(IAttr attribute). However, no matter what I do I can't seem to get AngleSharp to use the override. For example:

Let's say I give my IMarkupFormatter the following Attribute method:

```C#
public string Attribute(IAttr attribute) => "hello";
```

I would expect this method to be hit when ParseDocument is called, but instead it hits the default Attribute method and ignores my custom rule. Here is my complete implementation:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PipelineTest
{
    using AngleSharp;
    using AngleSharp.Dom;
    using AngleSharp.Html;
    using AngleSharp.Html.Dom;
    using AngleSharp.Html.Parser;
    using AngleSharp.Xhtml;
    using PreMailer.Net;
    class Program
    {
        static void Main(string[] args)
        {
            RunAnglesharp();
            Console.WriteLine();
        }

        static async Task RunAnglesharp()
        {
            var parser = new HtmlParser(new HtmlParserOptions
            {
                IsNotConsumingCharacterReferences = true,
            });

            var formatter = new SupressEncodingFormatter();
            var document = parser.ParseDocument("<html><head></head><body><a href=\"https://www.foo.com/?h=4&w=8\">&foo</a></body></html>");
            var output = document.ToHtml(formatter);
            Console.WriteLine(output);
            // Expected Output: "<html><head></head><body><a href=\"hello">&foo</a></body></html>"
            // Actual Output: "<html><head></head><body><a href=\"https://www.foo.com/?h=4&amp;w=8\">&foo</a></body></html>"
        }

        class SupressEncodingFormatter : IMarkupFormatter
        {
            public string Attribute(IAttr attribute) => "hello";
            public string CloseTag(IElement element, bool selfClosing) => HtmlMarkupFormatter.Instance.CloseTag(element, selfClosing);
            public string Comment(IComment comment) => HtmlMarkupFormatter.Instance.Comment(comment);
            public string Doctype(IDocumentType doctype) => HtmlMarkupFormatter.Instance.Doctype(doctype);
            public string OpenTag(IElement element, bool selfClosing) => HtmlMarkupFormatter.Instance.OpenTag(element, selfClosing);
            public string Processing(IProcessingInstruction processing) => HtmlMarkupFormatter.Instance.Processing(processing);
            public string Text(ICharacterData text) => text.Data;
        }
    }
}

```

**Comment by FlorianRappl** [comment]
Hm this is as planned, but maybe an indicator that `Attribute` should be removed from the interface.

Attributes are serialized by `OpenTag`, which calls `Attribute`, but on its own instance (it does not know that it was called from another formatter).

Right now I see the following options:

1. Remove `Attribute`, which then at least communicates that this is something the formatter owner needs to take care of when implementing `OpenTag`.
2. Make the `HtmlMarkupFormatter` a "normal" class (i.e., not `sealed`) to allow inheritance. Allow overriding all methods. This way the code above could inherit from `HtmlMarkupFormatter`, but only implement the ones that need to be changed.
3. Change the signature of `OpenTag` to get the list of serialized attributes. That way the element that needs to be serialized would call the right `Attribute` method already.

I think we should go with a combination of 1) and 2). We shouldn't require things on the interface that are not called if making a composition. However, there are times when a composition is not good enough - see the example above. Using inheritance we could improve this part.

This will be breaking - and as the interface was not designed for the use above I don't see a bug, but rather an improvement. We would still include it in 0.14!

Do you agree @CaptainStack ?

Thanks for bringing this up :beers:!

**Comment by CaptainStack** [comment]
So as a non-expert on this, I see I kind of misunderstood how it worked. Your comment helped me, I now have a working implementation, I just needed to overload both OpenTag and Attribute, even though Attribute was the only one I really wanted to change.

I think 2 makes a lot of sense to me, when first getting into this I didn't see why I needed to include the interfaces I wasn't changing - I was assuming a more traditional inheritance model.

My only hesitation is making this a breaking change as I am now working on an implementation that assumes the current system! Cheers 🍻

**Comment by FlorianRappl** [comment]
> My only hesitation is making this a breaking change as I am now working on an implementation that assumes the current system!

Yeah I know ... it will be frustrating, but I think its the right move to go with 1/2. Existing implementations will not need any major rewrite, even though they need to be touched. But its much clearer and also supports the traditional inheritance model, so I think a good change.

Landed in `devel` and the preview.

Thanks for raising this!

**Comment by bmode** [comment]
First of all, thank you for this awesome library.  It seems that this change has broken the example code listed 
 here: [Let's roll our own markup formatter](https://anglesharp.github.io/docs/Questions.html#how-to-produce-self-closing-tags)

Specifically this section which is output the attributes to the self-closing tag:
```C#
    foreach (var attribute in element.Attributes)
    {
        temp.Append(" ").Append(Instance.Attribute(attribute));   // Compiler error Instance.Attribute not defined
    }
```
Is the recommended approach for small output tweaks now to derive from HtmlMarkupFormatter rather than implement IMarkupFormatter?  Thanks!

**Comment by FlorianRappl** [comment]
> Is the recommended approach for small output tweaks now to derive from HtmlMarkupFormatter rather than implement IMarkupFormatter?

I'd say so. In general the protection was removed since just inheriting seems more natural to most C# developers. In the end I'd say its exactly as you assume; if its smaller just inherit and override, otherwise compose.

> Specifically this section which is output the attributes to the self-closing tag:

Yeah my guess is this code is broken in any case (independent of the change). It should work with `this.Attribute(attribute)` if my eyes work correctly.

Let me know if this is works for you - then I'd make a PR / update on the docs!

cc @bmode

**Comment by bmode** [comment]
Thank you, yes, I agree that inheriting from HtmlMarkupFormatter seems more natural, especially for small changes that only affect one method like in this case OpenTag.  I was able to get this working for my situation (which is slightly different than the example) and did use `this.Attribute(attribute)` to format the tag attributes as you suggest.

**Comment by FlorianRappl** [comment]
thanks for the confirmation @bmode . Fixed https://github.com/AngleSharp/anglesharp.github.io/blob/master/_docs/Questions.md
