### ISSUE TITLE
Default Accepts header

### ISSUE THREAD

**Issue by davidcie** [AngleSharp/AngleSharp#859]
# New Feature Proposal

## Description

Add a default `Accept: text/html` header to the `HttpRequester` created by `Configuration.Default.WithDefaultLoader`.

## Background

I'm very new to AngleSharp so be kind if this is common sense and understood by everyone else in the community. Came across it this morning when I came to a conclusion that regex used until now was too brittle. Tried to use examples found online, such as:

```
var context = BrowsingContext.New(Configuration.Default.WithDefaultLoader();
var document = context.OpenAsync(url).Result;
var divs = document.QuerySelectorAll("div");
foreach (var div in divs)
{
    // do something
}
```

To my surprise, this code would find no divs at all. Turned out that all HTML content was wrapped in another HTML document and a `pre` tag, which I traced to a [commit](https://github.com/FlorianRappl/AngleSharp/commit/c1d56d918da5b8b543e2bc34cb2ed209d8dff025) related to #331. (And sure enough execution was breakpointing in `HtmlDocument.LoadTextAsync`.) 

Fiddler showed that indeed response was being sent with `Content-Type: text/plain;charset=UTF-8` instead of the expected `Content-Type: text/html;charset=UTF-8`. Adding code adapted from #367:

```
var requester = new HttpRequester();
requester.Headers["Accept"] = "text/html";
var context = BrowsingContext.New(Configuration.Default.WithDefaultLoader(requesters: new[] { requester }));
```

...solved the problem. Not sure what web server is being used on the other side (trying to load [this url](https://ezdrowie.gov.pl/3107?modId=20794) but I suppose loading a web page and doing some manipulation might be a common scenario. 

Because at least some web servers will return a text (rather than HTML) response if given no `Accept` header, I would like to propose either adding a default `Accept` header or metioning this in docs / quick guides to save newcomers an hour of figuring out what is happening and why.

**Comment by davidcie** [comment]
To add to my previous post: life is not made any easier with the fact that the API seems to have changed, and to accomplish the above with the latest NuGet packages one has to use the following code:

```
var htmlRequester = new DefaultHttpRequester();
htmlRequester.Headers["Accept"] = "text/html";
var context = BrowsingContext.New(Configuration.Default.With(htmlRequester ).WithDefaultLoader());
```

**Comment by FlorianRappl** [comment]
There are multiple ways to solve this - you can also intercept the HTTP request in AngleSharp and place the header.

Going a step further I indeed think that the given proposal is super valid. And I want to bring it into 0.14.

This is what Chrome sends (among others) when opening a new site:

```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
```

I think the encoding makes sense and part of the accept (esp. the first two entries). I would add these by default to document requests. As such they should be picked up by *any* requester, not only the default requester (i.e., there should be no change required for the requesters of AngleSharp.Io).

**Comment by FlorianRappl** [comment]
Available in `devel` and the latest NuGet preview.

Can you check this @davidcie ? Thanks! :beers:

**Comment by davidcie** [comment]
@FlorianRappl thank you for looking into this and incredibly quick turnaround! Should have a few minutes this evening to test the change, will report back.

**Comment by davidcie** [comment]
Have just checked out the devel branch and can confirm it works as expected. Was a joy to see the new user-agent thrown in the mix too. Thanks for making this happen and fingers crossed for v0.14 going into prod soon!

**EDIT**: Wait a sec, v0.14 is _already_ in prod. That makes my day even more betterer ;)
