### ISSUE TITLE
MinifyMarkupFormatter removes attribute quotes when it should not

### ISSUE THREAD

**Issue by meziantou** [AngleSharp/AngleSharp#860]
# Bug Report

## Description

[MinifyMarkupFormatter](https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Html/MinifyMarkupFormatter.cs#L208) removes attribute quotes when [the spec says not to remove them](http://w3c.github.io/html-reference/syntax.html#attr-value-unquoted). MinifyMarkupFormatter only checks for whitespaces but the spec indicates other characters: 

> In addition to the general requirements for attribute values, an unquoted attribute value has the following restrictions:
> 
> - must not contain any literal space characters
> - must not contain any """, "'", "=", ">", "<", or "`", characters
> - must not be the empty string

In the following example the quotes are mandatory:

````
<div a="b="></div>
````

## Steps to Reproduce

````
// Should preserve quotes or add a space after
var parser = new HtmlParser();
var document = parser.ParseDocument("<div a='/'></div>");
document.ToHtml(Console.Out, new MinifyMarkupFormatter { ShouldKeepAttributeQuotes = false });
// <div a=/></div>

// Should preserve quotes
var parser = new HtmlParser();
var document = parser.ParseDocument("<div a='='></div>");
document.ToHtml(Console.Out, new MinifyMarkupFormatter { ShouldKeepAttributeQuotes = false });
// <div a==></div>
````

**Expected behavior:** It should preserve quotes as indicated in the spec 😊

**Actual behavior:** It removes quotes

**Environment details:** Windows 10, .NET Core 3.1.3

## Possible Solution

https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Html/MinifyMarkupFormatter.cs#L208

````
if (ShouldKeepAttributeQuotes || result.Any(c => CharExtensions.IsWhiteSpaceCharacter(c) || c == '"' || c == '\'' || c == '=' || ...)) // Add all case
// It should also check if the value ends with a '/' and add a space after if needed
````

**Comment by FlorianRappl** [comment]
Thanks for the report! Yes - this should be repaired in a 0.14.1. Mind doing a PR here? Much appreciated! :beers:

**Comment by meziantou** [comment]
I'll do a PR!

**Comment by FlorianRappl** [comment]
Was actually done in 0.14! Sorry - I placed it in the wrong milestone.
