### ISSUE TITLE
.QuerySelector(".row:nth-child(3) div:nth-child(2)") returns the wrong .row content in a special case

### ISSUE THREAD

**Issue by dstj** [AngleSharp/AngleSharp#862]
# Bug Report

I've been banging my head over this for over two hours now, it looks like I found a weird bug with `QuerySelector` when "chaining" selectors.

```
var value = div.QuerySelector($".row:nth-child(3) div:nth-child(2)").TextContent.Trim();
```
returns the wrong value (it returns the 1st row's value, not the 3rd), but separating it into two statements works:
```
var row = div.QuerySelector($".row:nth-child(3)");
var value = row.QuerySelector("div:nth-child(2)").TextContent.Trim();
```
## Prerequisites

- [X] Can you reproduce the problem in a [MWE]
I can reproduce, but not with a minimal example. I tried, but it works as expected with simple cases. I can share a test code though as it's a test, just not publicly. Just tell me how to send it.

- [X] Are you running the latest version of AngleSharp?
Yes, using version 0.14 with .NET Core 3.

- [X] Did you perform a search in the issues?
Looks a bit like [this 2 year-old issue](https://github.com/AngleSharp/AngleSharp/issues/513)

## Description

**Expected behavior:**
Both statement versions should return the same value.

**Actual behavior:**
It doesn't and I'm losing my mind!

**Environment details:**
Windows 10,
.NET Core 3.1.102

**Comment by FlorianRappl** [comment]
Thanks for the report.

We definitely need an HTML to reproduce this - and it must be public as we need it anyway to be included in our tests.

The issue you mentioned is invalid - so maybe this one is also invalid. Please make sure that this runs in a browser with fine (using your HTML - no JS for manipulation etc.). Thanks!

**Comment by dstj** [comment]
@FlorianRappl 
I totally understand you need a reproduction. ;)

**Note**: After a lot of exploration, the problem is **not** with AngleSharp. I'm still utterly confused though, but the browser produces the same results. I'll still post my findings, it may be helpful to others (and if you can explain what I'm not understanding about the CSS selector, that would be really great ;))

I tried to create a dumbed-down version of the issue as much as possible, but it's still doing some manipulations. I couldn't reproduce the issue with a simple project. Here are the project files:
[AngleSharpBug.zip](https://github.com/AngleSharp/AngleSharp/files/4427623/AngleSharpBug.zip)

In the project, you'll see:

```csharp
ExtractSub(sub, 3); // working
ExtractSub(sub, 2); // working
ExtractSub(sub, -1); // working
ExtractSub(sub, 1); // not working... !?!
ExtractSub(sub, 0); // not working?
```

calling this method:

```csharp
private static void ExtractSub(IParentNode refDiv, int offset)
{
	var buggy = refDiv.QuerySelector($".row:nth-child({offset + 2}) div:nth-child(2)").TextContent.Trim();

	var intermediateDiv = refDiv.QuerySelector($".row:nth-child({offset + 2})");
	var expected = intermediateDiv.QuerySelector("div:nth-child(2)").TextContent.Trim();

	if (buggy != expected) throw new Exception($"{buggy} != {expected}. Offset = {offset}");
	Console.WriteLine($"Working as expected. Offset = {offset}. Extract = {expected}");
}
```

Just run it, you'll get an Exception thrown.

Now, the browser yields the same results, hence the problem not being for AngleSharp (sorry!) In the browser, I do

```javascript
var div = $('hr').nextElementSibling.querySelector('div');
div.querySelector("div.row:nth-child(3) div:nth-child(2)");
```

Same problem, I don't get the expected row.

But this works:
```javascript
div.querySelector("div.row:nth-child(3) > div:nth-child(2)");
```

The `refDiv.innerHTML` is kind of like so:

```html
<div class="row">
	<div></div>
	<div>First row</div>
</div>
<div class="row">
	<div>
		<p class="key-value"></p>
	</div>
	<div></div>
</div>
<div class="row">
	<div>
		<p class="key-value">
			<span class="key"> Start Date </span>
		</p>
	</div>
	<div>
		June 05, 2019
	</div>
</div>
<div class="row">
	<div>
		<p class="key-value">
			<span class="key"> End Date </span>
		</p>
	</div>
	<div>
		October 07, 2019
	</div>
</div>
<div class="row">
	<div>
		<p class="key-value">
			<span class="key"> Service Level </span>
		</p>
	</div>
	<div>
		Days <br>
	</div>
</div>
<div class="row">
	<div>
		<p class="key-value">
			<span class="key">Deliverables</span>
		</p>
	</div>
	<div>
		Initial Setup Assistance <br>
	</div>
</div>
```

**Now, the confusing part**
If I extract the `innerHTML` into its own smaller file (see `extracted.html` in the zip), both

```javascript
div.querySelector("div.row:nth-child(3) div:nth-child(2)");
div.querySelector("div.row:nth-child(3) > div:nth-child(2)");
```

give the same result... 😕 🤷‍♂

**Comment by FlorianRappl** [comment]
Thanks for the detailed explanation and for looking into the problem in such depth!

Much appreciated! :beers:

**Comment by dstj** [comment]
You're welcome. it was driving me crazy!
If ever you could help me understand why the Child combinator works but the Descendant doesn't, I'm all ears ;)
(I know it's not related to AngleSharp per say, but you probably know more than me about CSS selectors! 😉)
