### ISSUE TITLE
Add async operation for ToHtml() method

### ISSUE THREAD

**Issue by zhengchun** [AngleSharp/AngleSharp#863]
# New Feature Proposal

## Description

Add `async` operation for `Node.ToHtml(TextWriter writer, IMarkupFormatter formatter)` method.

## Background

In AspNet Core 3.0, Synchronous IO is disallowed in default, [AllowSynchronousIO disabled in all servers](https://github.com/dotnet/aspnetcore/issues/7644), this means if we call `doc.ToHtml()` in AspNet will throw an error: `Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead`.

AspNet code:

```
using (var writer = _writerFactory.CreateWriter(Response.Body, encoding){
    doc.ToHtml(writer);
    await writer.FlushAsync();
}
```

## Specification

Wish to add new `ToHtmlAsync()` method for `asynchronous` IO operation or add new options for `ToHtml()` allows asynchronous write operation.

**Comment by FlorianRappl** [comment]
Hm not sure what that should bring to the table. We are not exchanging data with any external device - we merely write to a `Stream` (which is a memory stream dedicated to this operation).

This is therefore as fast as possible and does not benefit at all from being on a different thread or asynchronous at all.

I would love to hear opinions of the ASP.NET Core team on this one - specifically if its really the way they wanted. Not sure if it should / needs to be solved on library level or in application code.

cc @Tratcher

**Comment by Tratcher** [comment]
@zhengchun what's the stack trace for the exception?

Writing to a MemoryStream should be fine, but flushing it out to the response body needs to be async.

**Comment by zhengchun** [comment]
In my program, I want to load a HTML document and change some data in this document, then transform this changed document write to the client.

Here is my test code in Aspnet core 3.0 

```
        public async Task<IActionResult> Index()
        {
            var context = BrowsingContext.New(Configuration.Default.WithDefaultLoader());
            var document = await context.OpenAsync(new Url("https://github.com/"));
            var writerFactory = HttpContext.RequestServices.GetService<IHttpResponseStreamWriterFactory>();
            await using (var writer = writerFactory.CreateWriter(Response.Body, Encoding.UTF8))
            {
                document.ToHtml(writer);
               // await writer.FlushAsync();
            }
            return new EmptyResult();
        }
```

```
InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(byte[] buffer, int offset, int count)
```

```
InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(byte[] buffer, int offset, int count)
Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternal(bool flushEncoder)
Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.Write(string value)
AngleSharp.Dom.Node.ToHtml(TextWriter writer, IMarkupFormatter formatter)
AngleSharp.FormatExtensions.ToHtml(IMarkupFormattable markup, TextWriter writer)
WebApplication1.Controllers.HomeController.Index() in HomeController.cs
+
                document.ToHtml(writer);
WebApplication1.Controllers.HomeController.Index() in HomeController.cs
+
            }
```

**Comment by FlorianRappl** [comment]
Okay so as far as I can see it you pass the response stream directly to AngleSharp, right?

I guess we could at least add an `Async` overload on the outside. It would, however, only call the synchronous one inside with a `MemoryStream`, which is then copied asynchronously to the given stream.

Would that work?

**Comment by Tratcher** [comment]
Sure, it's that final copy that matters.

**Comment by zhengchun** [comment]
Here is my other test code that wrap a `MemoryStream` and then copy to `Response.Body` with async. It works but I guess it may be cause memory leak, because it create and copy the same data in memory.

```c#
 public async Task<IActionResult> Index5()
        {
            var context = BrowsingContext.New(Configuration.Default.WithDefaultLoader());
            var document = await context.OpenAsync(new Url("https://github.com/"));
            var ms = new MemoryStream();
            using (var writer = new StreamWriter(ms))
            {
                document.ToHtml(writer);
                ms.Position = 0;
                await ms.CopyToAsync(Response.Body);
            }
            return new EmptyResult();
        }
```

I wish a new async method `writer.WriteAsync()` instead of `writer.Write()` in the `ToHtml` method.

```c#
 public static Task ToHtmlAsync(this IDocument doc, TextWriter writer){
     foreach (var node in doc.GetDescendantsAndSelf())
    {
         if (node is IDocumentType docType)
            {
                    writer.WriteAsync(formatter.Doctype(docType));
            }
    }
}
```

**Comment by FlorianRappl** [comment]
Nah why should there be a memory leak? (In your `Index5` you should be `using` the memory stream - so my comment is general, not w. r. t. this specific impl.)

We will not add `Async` to the formatter internally - because this would be the wrong direction. Instead, we will only have an `ToHtmlAsync` extension method that will do pretty much what you did in `Index5`. Having one larger write is much more performing than several smaller ones. The only justification for the latter would be if parts would come in asynchronously. This is not the case.

**Comment by FlorianRappl** [comment]
Landed in `devel` and the preview.

**Comment by Tratcher** [comment]
> Having one larger write is much more performing than several smaller ones. The only justification for the latter would be if parts would come in asynchronously.

Note in MVC and Razor they took this a different direction. Trying to serialize the entire body into memory is not optimal when it starts to get large, it takes up more memory in your app and adds latency to the response. MVC balanced this vs small writes by writing to a fixed size buffer (4-64kb?) and async flushing that buffer when it filled. However, this required the serializer to be fully async because it could need to flush at any point.

**Comment by FlorianRappl** [comment]
Hi @Tratcher that's certainly a good point. The average write here is about 4 to 16 characters dep. on the document. So we do not talk in ~1k (or more) chunks (which would benefit the specific IO). With small I refer to a single write unit in AngleSharp - which is way less than usual IO buffers used these days.
