### ISSUE TITLE
Attribute Match Selector Is Case Sensitive

### ISSUE THREAD

**Issue by logwlogw** [AngleSharp/AngleSharp#864]
Example Html

&lt;input type="TexT"&gt;

&lt;script>&gt;
document.querySelector('input[type="teXt"]').value="Test";
&lt;/script>&gt;

It is work with JavaScript + Chrome

Does not find  - AngleSharp

var context = BrowsingContext.New(Configuration.Default);
var htmlParser = context.GetService<IHtmlParser>();

var document = htmlParser.ParseDocument(html)
document.QuerySelectorAll("input[type =  'text']");

Thank you!

**Comment by FlorianRappl** [comment]
Yes this is indeed a bug - the attribute match selector should be case insensitive!

Do you want to make a PR?

Otherwise I'll try to find time on the weekend.

**Comment by logwlogw** [comment]
The attribute match selector should be case insensitive!
**No, only standart W3C(html5) attribute values**

1. attribute  Name -  should be case insensitive
2. attribute Value - only W3C(html5) case insensitive, such type ...

Example,

&lt;input type="TexT"  MyattribA="z123"  value="testval"&gt;


&lt;script&gt;

alert(document.querySelector('input[type="teXt"]').value);  //Google+JS - OK
alert(document.querySelector('input[myattribA="z123"]').value); //Goole+JS OK
alert(document.querySelector('input[myattribA="Z123"]').value); //Goole+JS Not find


&lt;/script&gt;

**Comment by FlorianRappl** [comment]
Yes, good point. It seems like there is a whitelist of certain attribute names that cause case insensitive value comparison.

Do you have the specification part / whitelist?

**Comment by logwlogw** [comment]
I do'nt have full whitelist list , :(

for example
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#%3Cinput%3E_types

**Comment by FlorianRappl** [comment]
Not sure what input types (these are values not names) should be useful for.

I would then just go for all known attribute names.

**Comment by FlorianRappl** [comment]
The full list:
https://html.spec.whatwg.org/multipage/semantics-other.html#case-sensitivity-of-selectors

**Comment by FlorianRappl** [comment]
Landed in `devel` and the preview.
