### ISSUE TITLE
Article Attributes

### ISSUE THREAD

**Issue by popowich** [AngleSharp/AngleSharp#867]
When trying to parse this page https://makler.md/ru/transnistria/transport/cars?list&kind[]=sell&currency_id=5&list=detail

Parsing does not return the attributes of the article element

http://joxi.ru/p2755BEFK7WxQr

As a result, there are no attributes ((

http://joxi.ru/Vrwqqvec7R8kJ2

```
 var config = Configuration.Default.WithCss().WithDefaultLoader();
 var context = BrowsingContext.New(config);
 var document = await context.OpenAsync("https://makler.md/ru/transnistria/transport/cars?list&kind[]=sell&currency_id=5&list=detail");
var advertList = document.QuerySelectorAll<IHtmlDivElement>(".ls-detail").Last();
 var advertItems = advertList.QuerySelectorAll<IHtmlElement>("article");

```

**Comment by FlorianRappl** [comment]
There are no attributes on *any* `<article>` in the document referenced by the URL.

I guess you confuse a DOM manipulated by JS with a DOM that has not been touched by JS.

(If you want to see this in your browser - deactivate JavaScript and look again; or use `curl`)

```sh
curl -o sample.html  https://makler.md/ru/transnistria/transport/cars?list&kind%5B%5D=sell&currency_id=5&list=detail
```

**Comment by popowich** [comment]
Oh, thank you very much, nothing can be done about it?) To get these attributes? Sorry for the stupid questions)

**Comment by FlorianRappl** [comment]
Well, they are obviously "injected" by some JavaScript.

You can try to use [AngleSharp.Js](https://github.com/AngleSharp/AngleSharp.Js) but its still experimental and will fail for large / complicated / real-world JS apps. Maybe it works in the given scenario; it's at least worth a try.

**Comment by popowich** [comment]
Thanks a lot! You have a cool product!)
