### ISSUE TITLE
NullReferenceException in AngleSharp.Dom.ElementExtensions.GetInnerText()

### ISSUE THREAD

**Issue by duncansmart** [AngleSharp/AngleSharp#868]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Code:

    using System;
    using AngleSharp.Dom;
    using AngleSharp.Html.Parser;

    public class AngleSharpBug
    {
        static void Main()
        {
            var doc = new HtmlParser().ParseDocument("<html><head></head><body><p>hello world</p></body></html>");
            Console.WriteLine(doc.Body.TextContent);    // Works
            Console.WriteLine(doc.Body.GetInnerText()); // NullReferenceException in  AngleSharp.Css.Dom.CssStyleDeclaration.ChangeDeclarations
        }
    }

Results in following error:

    System.NullReferenceException: Object reference not set to an instance of an object.
	    at AngleSharp.Css.Dom.CssStyleDeclaration.ChangeDeclarations(IEnumerable`1 decls, Predicate`1 defaultSkip, Func`3 removeExisting)
        at AngleSharp.Css.Dom.CssStyleDeclaration.SetDeclarations(IEnumerable`1 decls)
        at AngleSharp.Css.StyleCollectionExtensions.ComputeCascadedStyle(StyleCollection styleCollection, IElement element, ICssStyleDeclaration parent)
        at AngleSharp.Css.StyleCollectionExtensions.ComputeDeclarations(StyleCollection rules, IElement element, String pseudoSelector)
        at AngleSharp.Dom.CssApiExtensions.ComputeCurrentStyle(IElement element)
        at AngleSharp.Dom.ElementExtensions.GetInnerText(IElement element)
        Test\AngleSharpBug.cs(11,0): at AngleSharpBug.Main()

**Comment by FlorianRappl** [comment]
Hi @duncansmart ,

thanks for the report. However, this is a configuration problem for you.

1. The given extension method belongs to `AngleSharp.Css`, so this is the wrong repo.
2. You use AngleSharp.Css, but you don't add it to the configuration.

Since you don't specify a configuration you get a default config. Just use the code as given from the various tutorials and you are good (`BrowsingContext` is your friend - use it!).

**Comment by FlorianRappl** [comment]
Code that should have been written:

```cs
var config = Configuration.Default.WithCss(); // important
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(res => res.Content("<html><head></head><body><p>hello world</p></body></html>"));
 Console.WriteLine(document.Body.TextContent);
 Console.WriteLine(document.Body.GetInnerText());
```
