### ISSUE TITLE
Is there a way to wait untill all resources are loaded before executing code?

### ISSUE THREAD

**Issue by ossaltu** [AngleSharp/AngleSharp#87]
```
var document = await BrowsingContext.New(config).OpenAsync(m => m.Content(html).Address(htmlUri));
// some code
```

OpenAsync returns document before all resources in html are loaded. Is there a way to wait untill all resources are loaded?

**Comment by FlorianRappl** [comment]
Right now there is no direct way, however, there are several possible options. You could either listen for request start / stop events or you could wrap the resource loader and aggregate the requests there.

Maybe I'll add some extension method in the next release!
