### ISSUE TITLE
AngleSharp.Js in PowerShell Core

### ISSUE THREAD

**Issue by lupusnocta** [AngleSharp/AngleSharp#870]
Hello. I'm trying to load AngleSharp.Js in PowerShell Core, but I'm lost; I can't load AngleSharp core and AngleSharp.Js in the same time. Below is the code I'm using to load and parse HTML (functioning):

```
$config = [AngleSharp.ConfigurationExtensions]::WithDefaultLoader([AngleSharp.Configuration]::Default)::
$context = [AngleSharp.BrowsingContext]::New($config)
$HTML = [AngleSharp.BrowsingContextExtensions]::OpenAsync($context,$URI).GetAwaiter().GetResult()
```

Could you help me?

**Comment by FlorianRappl** [comment]
Good question - not sure why it is not possible. Can you post what you tried to run them?

Essentially all you'd need to do is to use the C# sharp and translate it. Keep in mind that the `WithJs` extension method comes from the AngleSharp.Js assembly; so maybe this is where you'd need to be explicit about the origin in PowerShell.

**Comment by lupusnocta** [comment]
Yeah. I could write in C#, but I want to "boost" my experience in PowerShell (and VS Code).
What I'm trying to do is automate the collectiong of prices of old cards that are gathering dust in here, so I made the script to do it. Unfortunaly, some cards have diferent edition and the prices updates when you click (or mouseover) on edition symbol. Thanks to Angle, all the information are bringing to me OK, but I can't run the scrip to update de values; I guess that Angle JS could do that, but cant declare both Core an JS.

Like I said, I'm stuck on declaration of both modules... I'll attach my script below.

PS: The code is in "draft" for now, so apologize for some garbage in there.

[Magic_v2.txt](https://github.com/AngleSharp/AngleSharp/files/4541573/Magic_v2.txt)

**Comment by CarloToso** [comment]
@lupusnocta I think i found a solution to this problem.

```ps1
$config = [AngleSharp.JsConfigurationExtensions]::WithJs([AngleSharp.ConfigurationExtensions]::WithDefaultLoader([AngleSharp.Configuration]::Default))
```

**Comment by lupusnocta** [comment]
Great. I'll try your solition @CarloToso and post feedbacks here. 
Thanks for the attention. ^^
