### ISSUE TITLE
How to use cookies?

### ISSUE THREAD

**Issue by SonOfDiablo** [AngleSharp/AngleSharp#871]
Hello,

I have a website where I need to collect cookies from one URL and HTML from another, how would I go about doing this with AngleSharp?

The cookies are authentication cookies that gets set when visiting a special URL, those cookies are needed to access the other URL.

**Comment by FlorianRappl** [comment]
My recommendation is to use AngleSharp.Io:

https://github.com/AngleSharp/AngleSharp.Io#cookies

Hope that helps!
