### ISSUE TITLE
How read site like Inspect element

### ISSUE THREAD

**Issue by MHKarami97** [AngleSharp/AngleSharp#872]
## Description

How can I read page source after it's complete and like it's in inspect element of browser?
For example this page (view source) and (Inspect) are different and I want read it as Inspect:
[link](http://www.tsetmc.com/Loader.aspx?ParTree=151311&i=778253364357513)

**Comment by FlorianRappl** [comment]
Hm not sure what you mean exactly.

If you want to read the page's source you use, e.g., `document.Source.Text`, otherwise if you want to see the "current" serialization you use `document.toHtml()`. The DOM is "live" so using something like `document.Body` will give you the same thing as inspect would get you in the browser.

Hope that helps!

**Comment by MHKarami97** [comment]
@FlorianRappl 
Thank you, for example this pages:

code when I click view source in chrome: 
[link](https://gist.github.com/MHKarami97/7124b8db82668a2371b2104ba030ba47)

code when I right click on page and click Inspect in chrome:
[link](https://gist.github.com/MHKarami97/7cf0e2af0c1f29461e598e1a3315f693)

with main link:
[link](http://www.tsetmc.com/Loader.aspx?ParTree=151311&i=778253364357513)

these codes are very different and if I use this code I get first link code
`dataSource = await _browsingContext.OpenAsync(Source + address).WaitUntilAvailable();`

how can I get code like link two?

**Comment by maxkatz6** [comment]
@MHKarami97 

1. Code in Chrome DevTools (Inspect) is formatted by Chrome. You can prettify HTML code with AngleSharp, I just found one example - https://github.com/AngleSharp/AngleSharp/issues/814 (note on PrettyMarkupFormatter).

2. "View source" shows original HTML code received with HTTP request. While DevTools shows current HTML layout after JS scripts executing and/or user input. With AngleSharp you can try to emulate browser to get dynamic HTML - https://github.com/AngleSharp/AngleSharp.Js. But I am not really familiar with that usage of AngleSharp, so I can't provide you more information.
