### ISSUE TITLE
Working with an account on a webpage

### ISSUE THREAD

**Issue by SerhanCeetin** [AngleSharp/AngleSharp#873]
Let me explain my request with an example.
The user will log into their Facebook account via WebView in my application. 
The application will get images from the user's profile page. The app cant get any images without login. How is this possible? Cookie transfer or something like that?

**Comment by FlorianRappl** [comment]
Yes you can transfer the cookie - only question is if this is somewhat blocked by Facebook (e.g., by fingerprinting the used browser).

I'd recommend looking at the cookie container from [AngleSharp.Io](https://github.com/AngleSharp/AngleSharp.Io). It allows reading cookies from disk (or even writing them). So if you can transfer the cookie file then AngleSharp.Io could deal with it.

Hope that helps!

**Comment by SerhanCeetin** [comment]
Do you know a site with sample codes or tutorials for AngleSharp? except the official docs
