### ISSUE TITLE
IBrowsingContext.OpenAsync doesn't pass CancellationToken on

### ISSUE THREAD

**Issue by singingknight** [AngleSharp/AngleSharp#874]
This line in `public static Task<IDocument> OpenAsync(this IBrowsingContext context, DocumentRequest request, CancellationToken cancel = default)` throws the CancellationToken away

https://github.com/AngleSharp/AngleSharp/blob/3968eb050e142b1d94550fba407afe772232b126/src/AngleSharp/BrowsingContextExtensions.cs#L66

**Comment by FlorianRappl** [comment]
That's a great catch. Thanks for noticing. Want to make a PR?

Would be much appreciated :rocket:!

**Comment by FlorianRappl** [comment]
Landed in `devel` and the preview!

Thanks for your awesome contribution @singingknight
