### ISSUE TITLE
Support System.IO.TextReader sources

### ISSUE THREAD

**Issue by elgonzo** [AngleSharp/AngleSharp#876]
How about supporting System.IO.TextReader sources?

If one can believe the documentation, even Xamarin.IOS and Xamarin.Android should TextReader since at least three years, if i am not mistaken.

Would there be reasons against System.IO.TextReader support?

**Comment by FlorianRappl** [comment]
We (directly) support `string` and `Stream`. A `TextReader` would thus be read first and used as a `string`. We can have an overload for this, but it would not be special support and it would not have any performance improvement. It could send the wrong message to the user, though.

A `TextReader` is already an abstraction that uses a `Stream` and a fixed encoding. AngleSharp, however, needs to switch the coding and do certain things in the stream (e.g., encoding detection) to be aligned with the spec. Low level we thus require a `Stream`.

Can you outline your use case? Support in which way?

Thanks!

**Comment by elgonzo** [comment]
I want to write a (command line) tool which processes some HTML data. The tool should allow the HTML data to be piped into the input channel of the tool. The input channel of console applications is a TextReader, not a stream.

Loading the TextReader into a string is a workaround (i agree with you that this should be done by the user of the AngleSharp library, the library itself should not do this "behind the curtain" while making the impression it properly supports TextReaders). But in my opinion it is an omission for a package that predominantly processes text data to support strings and Stream but not TextReader. Considering that a string can be wrapped in a TextReader via StringReader with little performance and memory penalities (but a TextReader cannot be wrapped in a string), it really feels weird that strings are treated as first-class citizens whereas TextReaders are not.


> would not have any performance improvement

Do i understand your comment correctly that when using streams, AngleSharp preloads the entire stream content (being equivalent performance-wise to preloading an entire TextReader into a string) before creating the HTML DOM from it?

**Comment by FlorianRappl** [comment]
> preloads the entire stream content

No - we do it while constructing the DOM. This is, unfortunately, a misunderstanding. The performance improvement for a `TextReader` would only be there if it could be handled like a `Stream`.

> it really feels weird that strings are treated as first-class citizens whereas TextReaders are not.

I am not sure how that can feel weird. `Stream`s are first-class citizens; the resulting buffer of interpreted characters is a string (please complain at the .NET Team if you disagree here), hence a string is first-class citizen. We can just treat a string as-if a `Stream` has been fully processed.

Coming back to the topic:

The other thing you can do is to wrap the `TextReader` in a `Stream`. It would just get back the bytes from the original stream, so it would be performance wise first-class minus the small overhead. It's unfortunate that you get a `TextReader` from PS, but their design decision is understandable.

We could provide an overload for this, but I still feel that it could send the wrong message to potential users. Nevertheless, I think it could be a good improvement for scenarios like this.

**Comment by FlorianRappl** [comment]
On a general note I find your tone rather strange esp. for someone who has not contributed to this project in any way (not even given a star).

Open-source is not about making demands, but about collaboration and fruitful discussion. There is no obligation to use any of this.

**Comment by elgonzo** [comment]
>On a general note I find your tone rather strange esp. for someone who has not contributed to this project in any way (not even given a star).

>Open-source is not about making demands, but about collaboration and fruitful discussion. There is no obligation to use any of this.

Really? I don't know if you are with the project or not, but you don't seem to be aware that AngleSharp's Github project pages specifically invites people to make feature requests:

![FeatureRequestButton](https://user-images.githubusercontent.com/6129198/80867249-8f458300-8c93-11ea-8981-72964168b395.png)

Yet you seem trying to chastize me for doing so. Why? It doesn't make any sense.

Also, a small but important distinction: I made a feature request, not a demand. You might find my tone rather strange. Okay, so what. Different people are different, some stranger than others. Frankly, i don't know what your problem is...

**Comment by FlorianRappl** [comment]
> Really? I don't know if you are with the project or not, but you don't seem to be aware that AngleSharp's Github project pages specifically invites people to make feature requests

This was not about the OP, but the tone that happened after the initial explanation.

> Loading the TextReader into a string is a workaround (i agree with you that this should be done by the user of the AngleSharp library, the library itself should not do this "behind the curtain" while making the impression it properly supports TextReaders). But in my opinion it is an omission for a package that predominantly processes text data to support strings and Stream but not TextReader. Considering that a string can be wrapped in a TextReader via StringReader with little performance and memory penalities (but a TextReader cannot be wrapped in a string), it really feels weird that strings are treated as first-class citizens whereas TextReaders are not.

Read this paragraph again.

> Frankly, i don't know what your problem is...

And yet again, instead of focusing on the proposition you turn this into an accusation?! This time accusing me of not following the principles of the project? All I did was reminding you to keep the tone friendly and up to the discussion point - plus to put back any demands as they have no room here.

Last attempt to come back to the topic:

> The other thing you can do is to wrap the TextReader in a Stream. It would just get back the bytes from the original stream, so it would be performance wise first-class minus the small overhead.

**Comment by elgonzo** [comment]
> And yet again, instead of focusing on the proposition you turn this into an accusation?! This time accusing me of not following the principles of the project? All I did was reminding you to keep the tone friendly and up to the discussion point - plus to put back any demands as they have no room here.

Seriously, you started berating me, and now you double down? Are you serious?
Your behavior is laughable. I have no interest in further engagement with you. You might want to close this issue if you desire.
