### ISSUE TITLE
Question: For high performance needs how many instances of HtmlParser should be used?

### ISSUE THREAD

**Issue by PonchoPowers** [AngleSharp/AngleSharp#880]
The question is basically whether HtmlParser should be stored in a single variable and used in many methods, or whether each method should create it's own instance. Is there any reason to instantiate more than one HtmlParser, and will it hurt performance to do so?

**Comment by FlorianRappl** [comment]
The `HtmlParser` itself is very lightweight, but you should not use this directly. Instead, use a `BrowsingContext` and store this in a variable.

The `HtmlParser` also requires a `BrowsingContext`, so there is no benefit of going directly to use it. Think of an `BrowsingContext` like a tab in your browser, i.e., only one page at a time. If you have multiple (parallel) page loads then use multiple `BrowsingContext`.

Easiest way would be a `[ThreadStatic]` with 1 context per thread.

Hope that helps!
