### ISSUE TITLE
SubmitAsync taking too long (45 seconds)

### ISSUE THREAD

**Issue by Imadlekal** [AngleSharp/AngleSharp#882]
So, I downloaded this Demo from [AngleSharp ](https://github.com/AngleSharp/AngleSharp.Demos.DeveloperWeek)repository and all did was adding a break inside the `foreach` loop because there were some other elements that I didn't want to fill and I also changed the form to `Last `instead of `FirstOfDefault` (because the first one is the search bar).

```
 public async Task SubmitForm(IDictionary<String, String> fields)
        {

            var document = _context.Active;
            var form = document.Forms.Last();
            var elements = form?.Elements ?? Enumerable.Empty<IHtmlElement>();
            int random = 0;

            foreach (var element in elements.OfType<IHtmlInputElement>())
            {
                if (random == 2)
                    break;
                
                if (fields.TryGetValue(element.Name ?? String.Empty, out string value))
                {
                    element.Value = value;
                }
                random++;
            }


            await form.SubmitAsync();

        }
```
`
```
 async void ExecuteSubmit()
        {

            IsLoading = true;
            await _accessor.SubmitForm(new Dictionary<String, String>(StringComparer.Ordinal)
            {
                ["user"] = "Aklim",
                ["passwrd"] = "azeqsd789456"
            });
            Update();
            var GetWelcomeMessage = _accessor.GetTextOf("div.tborder table:nth-child(2) tbody tr td.titlebg2 span");
            MessageBox.Show($"{GetWelcomeMessage}.");
        }
```
This is working fine, it's just that SubmitAsync is taking too long to execute (45 seconds) and I'm not sure why exactly because if I connect manually, it goes smoothly. I've also tried the same code using the WebApp given in the demo, that was almost instant as well.

![devenv_WUTb83J40Z](https://user-images.githubusercontent.com/14929605/82688017-0f865500-9c50-11ea-8405-c2b22edf2ef8.png)

This is the login link (captcha): https://bitcointalk.org/index.php?action=login;ccode=540745379ff2169d1c1a

If that doesn't work, you can login using the captcha manually, then visit https://bitcointalk.org/captcha_code.php to get the login link without captcha.

Thanks!

**Comment by FlorianRappl** [comment]
I'm not sure this is a bug in AngleSharp.

At least I cannot reproduce it. If you think this is a bug then please create a MWE w/o going to a specific site, but using `localhost` to exclude any network effects.

AngleSharp just uses .NET's HTTP/s mechanism under the hood.

**Comment by TonyDev314** [comment]
I have the same issue - my code tries to spin up 3 browsingcontexts and in each, log into a different account.
The calls to openAsync occur quickly in parallel as do the calls to SubmitAsync, but then the 2nd submit completes quickly - there is then a 45 second delay before the 1st submit is cancelled with the following error

```
The request was aborted: The request was canceled.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

The 3rd submit then completes successfully.

Note - the code works if I only pass in one account taking 5 secs to execute. If I pass in 2 it completes successfully, the second submit completing first and taking 3 seconds, the first call completes after 46 seconds. More than 2 and it fails on some submits.

**Comment by TonyDev314** [comment]
```
 public async Task<IDocument> Initialise(Account account)
        {
            
              
                _config = Configuration.Default.WithDefaultLoader().WithDefaultCookies();

                var browsingContext = AngleSharp.BrowsingContext.New(_config);

                
                await browsingContext.OpenAsync(_myUrl);


                return await browsingContext.Active.QuerySelector<IHtmlFormElement>("form").SubmitAsync(new

                {
                    username = account.User,
                    pass = account.Password
                }).ConfigureAwait(continueOnCapturedContext: false);





           
        }
```

**Comment by FlorianRappl** [comment]
Could you try with the improved HTTP requester from `AngleSharp.Io` @TonyDev314 ?

**Comment by TonyDev314** [comment]
Perfect - fixes the issue.

Many thanks for the swift response - great library by the way!
