### ISSUE TITLE
How can I parse an SVG?

### ISSUE THREAD

**Issue by StefanoBalzarottiEnnova** [AngleSharp/AngleSharp#886]
I tried with  HtmlParser parser = new HtmlParser();
var parsedSvg = parser.ParseDocument(file);

but parsedSvg.All contains  an Html tag witch contains Head and Body and that is not true.

If I use parsedSvg.GetElementsByTagName("svg").FirstOrDefault(); doesn't find any element.

I tried with XmlParser, but parsing fails with AngleSharp.Xml.Parser.XmlParseException: 'Error while parsing the provided XML document.'

I see in the library there is no an SvgParser, do you support SVG dom parsing?

**Comment by FlorianRappl** [comment]
A valid SVG document has to be able to be parsed by `XmlParser` from `AngleSharp.Xml`.

Since you labelled this a bug I assume you have an SVG that fails parsing? Mind posting an MWE? Otherwise, we cannot follow up on the issue. Thanks!

**Comment by StefanoBalzarottiEnnova** [comment]
I labeled as bug because I was only able to choose between bug and feature request, and this library says to support svg.

This is a sample of SVG that fails:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 22.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Lager_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#AFAA96;stroke:#AFAA96;stroke-miterlimit:10;}
</style>
<rect class="st0" width="100" height="100"/>
</svg>
```

**Comment by FlorianRappl** [comment]
Works fine for me.

Ran below in LINQPad with AngleSharp 0.14 and AngleSharp.Xml 0.14:

```cs
async Task Main()
{
	var config = Configuration.Default.WithXml();
	var xml = @"<?xml version=""1.0"" encoding=""utf-8""?>
<!-- Generator: Adobe Illustrator 22.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version=""1.1"" id=""Lager_1"" xmlns=""http://www.w3.org/2000/svg"" xmlns:xlink=""http://www.w3.org/1999/xlink"" x=""0px"" y=""0px""
	 viewBox=""0 0 100 100"" style=""enable-background:new 0 0 100 100;"" xml:space=""preserve"">
<style type=""text/css"">
	.st0{fill:#AFAA96;stroke:#AFAA96;stroke-miterlimit:10;}
</style>
<rect class=""st0"" width=""100"" height=""100""/>
</svg>";
	var document = await BrowsingContext.New(config).OpenAsync(res => res.Content(xml).Header("Content-Type", "text/xml"));
	document.QuerySelector("rect").Dump();
}
```

So the document is fine and the library works fine, too.

Hope that helps!
