### ISSUE TITLE
rename from INode.Owner to INode.OwnerDocument

### ISSUE THREAD

**Issue by xp44mm** [AngleSharp/AngleSharp#887]
the INode.Owner in anglesharp is the INode.ownerDocument in DOM, if possible, should keep same.
the source come from 
https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument

another one:

the `INode.Clone()` in anglesharp is the `INode.cloneNode()` in DOM

**Comment by FlorianRappl** [comment]
It's called `ownerDocument` for the IDL:

https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Dom/INode.cs#L85

In C# we obviously have partially shorter names.

As your propositions are unnecessary breaking and thus cannot be considered. Thanks for noting though.
