### ISSUE TITLE
Please support self close script

### ISSUE THREAD

**Issue by yinyue200** [AngleSharp/AngleSharp#888]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Please support some self close tag such as script and title. I know that is nonstandard writing. But there are quite a lot of things like that in the Internet and most of modern browsers (Firefox, Chrome, MSIE) can parse that.

## Steps to Reproduce

<del>

1. run code
```
    //Create a new context for evaluating webpages with the default config
    var context = BrowsingContext.New(Configuration.Default);

    //Create a document from a virtual request / response pattern
    var document = await context.OpenAsync(req => req.Content("<script/><ul><li>First item<li>Second item<li class='blue'>Third item!<li class='blue red'>Last item!</ul>"));

    //Do something with LINQ
    var blueListItemsLinq = document.All.Where(m => m.LocalName == "li" && m.ClassList.Contains("blue"));
```

</del>

**Expected behavior:** 
get the blueListItemsLinq 
**Actual behavior:** 
blueListItemsLinq's count is 0

**Comment by FlorianRappl** [comment]
The script element is not self-closing. Changing this would violate the HTML5 spec.

Please follow our guideline and first assert with a browser of your choice! Many thanks!

**Comment by FlorianRappl** [comment]
> Please support some self close tag such as script and title. I know that is nonstandard writing. But there are quite a lot of things like that in the Internet and most of modern browsers (Firefox, Chrome, MSIE) can parse that.

I doubt that. See:

![image](https://user-images.githubusercontent.com/1766191/84906453-3cdcec00-b0b2-11ea-8061-c7ff4f57b43f.png)

I used the following code:

```html
<!DOCTYPE html>
<html>
<script>
setTimeout(() => alert(document.body.innerHTML), 1000);
</script>
<body>
<div>
<script/>
</div>
</body>
</html>
```

The same on MSIE:

![image](https://user-images.githubusercontent.com/1766191/84906654-86c5d200-b0b2-11ea-83e7-7b242dba3057.png)

**Comment by yinyue200** [comment]
@FlorianRappl I'm sorry. But modern browsers actually support some cases. Here is a case.
```html
<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" >
<head>
<meta charset="UTF-8"/>
<title>test</title>
<script>
setTimeout(() => alert(document.head.innerHTML), 1000);
</script>
<script xmlns="http://www.w3.org/1999/xhtml" type="text/javascript" src="test.js"/>

</head>
<body>
TEXT
</body>
</html>
```

**Comment by FlorianRappl** [comment]
@yinyue200 This is a different element (your OP used the standard `script` element).

That is not the `script` element from HTML, but an XHTML element. AngleSharp does not support the XHTML DTO.

**Comment by yinyue200** [comment]
@FlorianRappl Thanks

**Comment by FlorianRappl** [comment]
One last remark @yinyue200 - just that I closed this issue (bug) does not mean I am opposed to having XHTML support (as a feature) in there. Maybe `AngleSharp.Xml` can have / provide support for this?

I would love to see support for scenarios such as the outlined one. I am right now not sure if it already works out of the box (e.g., when incl. `AngleSharp.Xml` with `WithXml()` in the config) [I guess it does not], but it *should* (i.e., would be ideal to) just work.
