### ISSUE TITLE
How to resolve encoding conflicts? remove the meta encoding handler.

### ISSUE THREAD

**Issue by xp44mm** [AngleSharp/AngleSharp#889]
i have a file with **utf8** encoding, and have content:
```html
<html>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
...
balabala
...
```
i use it:
```F#
fun file ->
                task {
                    let! text = File.ReadAllTextAsync(file) // this time text is correct.

                    let context = BrowsingContext.New(Configuration.Default)

                    // i guess open method go wrong
                    let! document = context.OpenAsync(fun req -> req.Content(text) |> ignore)

                    let html = document.Body.OuterHtml
                    do! File.WriteAllTextAsync("targetFileName",html, Encoding.UTF8) // assign encoding useless.
                }
```

may i ignore the charset of html file content, force use the file encoding?

**Comment by FlorianRappl** [comment]
Yes that is possible.

In the default configuration the `EncodingMetaHandler` (see https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Browser/EncodingMetaHandler.cs#L12) is used.

I guess if you remove this from the configuration you should be fine.

```cs
var config = Configuration.Default.Without<EncodingMetaHandler>();
// as usual
```

Hope that helps!

**Comment by xp44mm** [comment]
yes! it works and Laborious you!  another question is the config variable put global, and it can singleton or instances?

```c#
var config = Configuration.Default.Without<EncodingMetaHandler>();

/// for many context using same config
...
```

**Comment by FlorianRappl** [comment]
Yes you can do that - every context creates a snapshot ("instance") of the supplied configuration.
