### ISSUE TITLE
IHtmlParser Should have a ParseFragment method taking Stream

### ISSUE THREAD

**Issue by The-Nutty** [AngleSharp/AngleSharp#896]
# New Feature Proposal

## Description
There is a version of every method in the IHtmlParser interface that can take a Stream apart from ParseFragment.
I suggest adding a method like `INodeList ParseFragment(Stream source, IElement contextElement)`

**Comment by FlorianRappl** [comment]
I think this should be no problem and would be really helpful. Mind contributing with a PR?

Thanks a lot already!

**Comment by FlorianRappl** [comment]
Landed in `develop` / preview version.
