### ISSUE TITLE
Good way of using AngleSharp.Css in an other Project

### ISSUE THREAD

**Issue by jogibear9988** [AngleSharp/AngleSharp#898]
I've work sometimes on a svg / wpf lib.
For this I needed to support styles.

So I thought as an addition, it would be nice to support complexer stylesheets.

It is easy to Parse them with anglesahrp.css.
But are there also helper methods to check if a style matches a particular elment?

So maybe I have my object tree, and hand over Functions to anglesharp.css from wich it could get the id, name,... from my objects. and it returns the matching styles?

**Comment by FlorianRappl** [comment]
> But are there also helper methods to check if a style matches a particular elment?

You mean the selector of a style? Yes, that is possible.

So if understand your use case correctly, you'd like to construct the CSSOM of a stylesheet, loop over its styles and get the corresponding / matching nodes in the DOM, right?

**Comment by jogibear9988** [comment]
I‘ve a Dom of my SVG (with my own classes) and I‘ve parsed my stylesheet with your lib.
Now I want for each part of my svg dom the matching style elements.

**Comment by FlorianRappl** [comment]
Yes you can use `Match` from a selector to check if an element matches it.

https://github.com/AngleSharp/AngleSharp/blob/master/src/AngleSharp/Css/Dom/ISelector.cs#L20

**Comment by jogibear9988** [comment]
So I create a wrapper around my Elements wich implement "IElement". I'll try this.

**Comment by FlorianRappl** [comment]
Ah ok @jogibear9988 - I think I now understand (sorry): The SVG is not an SVG `IDocument` instance (i.e., not parsed with AngleSharp).

Well, I'd love to think about how to construct this / match it abstractly in AngleSharp, but the other thing you can do is parse the SVG with AngleSharp.Xml. It should just work fine and gives you `IElement` instances out of the box.
