### ISSUE TITLE
document.QuerySelectorAll does not return any results

### ISSUE THREAD

**Issue by irfan-yusanif** [AngleSharp/AngleSharp#900]
## Description
I'm trying to scrape a website's data, but `QuerySelectorAll` does not return any results. 

![image](https://user-images.githubusercontent.com/5346797/92455473-250d9380-f1db-11ea-829a-d5391ccda8ed.png)

## Steps to Reproduce

           `var pageLink = "https://www.dealkar.pk/";
            var config = Configuration.Default.WithDefaultLoader();
            var document = await BrowsingContext.New(config).OpenAsync(pageLink);

            var titleSelector = ".text-navy";
            var titlecells = document.QuerySelectorAll(titleSelector);
            var titles = titlecells.Select(m => m.GetAttribute("href"));`

**Expected behavior:** document.ToHtml() should return whole HTML

**Actual behavior:** document.ToHtml() returns empty head and body tags

**Environment details:** Windows 10, .Net framework 4.7

**Comment by FlorianRappl** [comment]
Sure its not a certificate error? Looks to me like it.

Keep in mind that .NET's certificate store is not the same as your browser. You may need to allow additional CAs there.

**Comment by irfan-yusanif** [comment]
Its the certificate error, thanks. I fixed using [this](https://stackoverflow.com/a/41484581/3952692). Following issue can be linked with this one
#810
