### ISSUE TITLE
What's the name of the JS Library?

### ISSUE THREAD

**Issue by irfan-yusanif** [AngleSharp/AngleSharp#901]
Hello,
 I'm using the latest version `0.14.0.0`, but `WithJS()` option is not in `Configuration.Default`, when I add `Configuration.Default.WithJs();` I got error `IConfiguration does not contain definition for WithJs`

![image](https://user-images.githubusercontent.com/5346797/92943163-dc203e00-f46b-11ea-9ff1-1522a26a6700.png)

I have included the namespace `AngleSharp.Scripting`, also tried downloading the package `AngleSharp.Scripting.JavaScript -Version 0.5.1`, but then got the version issue.

How can I enable Javascript in version `0.14.0.0`?

**Comment by FlorianRappl** [comment]
The package you are missing is called `AngleSharp.Js`.

This is the repo: https://github.com/AngleSharp/AngleSharp.Js

This is the NuGet: https://www.nuget.org/packages/AngleSharp.Js/

This is the migration doc that explicitly mentions the deprecation of the library you mentioned: https://github.com/AngleSharp/AngleSharp/blob/master/doc/Migration.md#scripting

Hope that helps.
