### ISSUE TITLE
System.NullReferenceException thrown from AngleSharp.Html.HtmlMarkupFormatter.Attribute.

### ISSUE THREAD

**Issue by The-Nutty** [AngleSharp/AngleSharp#903]
# Bug Report
## Description

Unfortunately i dont have a MWE for this just a stack trace and some code:
```
System.NullReferenceException: Object reference not set to an instance of an object.
  at AngleSharp.Html.HtmlMarkupFormatter.Attribute(IAttr attr)
  at AngleSharp.Html.HtmlMarkupFormatter.OpenTag(IElement element, Boolean selfClosing)
  at AngleSharp.Dom.Node.ToHtml(TextWriter writer, IMarkupFormatter formatter)
  at AngleSharp.FormatExtensions.ToHtml(IMarkupFormattable markup, IMarkupFormatter formatter)
```
This happens when calling `document.ToHtml();`

Unfortunately i dont have the raw html, i have had a poke through the code and cant find where this might be happening, i can only guess that `attr` or `attr.Value` is null. Both of which would seem like parsing errors so im not sure where to look beyond that.

I have replaced  `document.ToHtml();` with `document.ToHtml(new AngleSharpHtmlMarkupFormatter());` where AngleSharpHtmlMarkupFormatter is a copy of the AngleSharp.Html.HtmlMarkupFormatter such that if this happens again i will get a good stack trace.

**Comment by FlorianRappl** [comment]
Alright thanks for the heads up. Let's leave it open - as you wrote its more likely a problem with the DOM (construction) than with the markdown formatter; which assumes that the DOM is "clean".

**Comment by The-Nutty** [comment]
So it happened again, and the line that threw the error was `for (var i = 0; i < value.Length; i++)` suggesting `attr.Value` is null.

Some other info i logged out: attr.NamespaceUri is null or blank. attr.LocalName and attr.Name are href.

From i quick glance i dont know how the html parsing works in angle sharp (I dont know if there is some docs somewhere?) but i hope this helps. Im quite keen to get this fixed as its causing a few issues for us currently so im happy to help where i can.

**Comment by FlorianRappl** [comment]
The HTML parsing just follows the W3C HTML 5.1 spec. The routine names etc. are also mapped to mimic the spec quite closely, which helps in keeping it up to date.

The `NamespaceUri` being `null` is fine. This is all as expected. `value` being `null` is strange, however. I need to see about that, but I guess its a case where we have `<a href>` or similar.

I'll have a look tonight!

Thanks for the report @The-Nutty !

**Comment by FlorianRappl** [comment]
Fix pushed to `develop` and deployed in the preview.
