### ISSUE TITLE
.WithJavaScript() config failing

### ISSUE THREAD

**Issue by Gavin-Williams** [AngleSharp/AngleSharp#905]
## Description

Trying to configure with javascript throws exception...

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'AngleSharp.Services.IScriptingProvider' from assembly 'AngleSharp, Version=0.14.0.0, Culture=neutral...

  Source=AngleSharp.Scripting.JavaScript
  StackTrace:
   at AngleSharp.JsConfigurationExtensions.WithJavaScript(IConfiguration configuration)

## Steps to Reproduce

1. Create a blank app (universal Windows)
2. Set target version = 2004, minimum version = 1809
3. Manage nuget packages; add AngleSharp, AngleSharp.Css, AngleSharp.Scripting.Javascript & AngleSharp.Js
4. Create a MainPage_Loaded event handler with the following code...

```
            // use default configuration
            IConfiguration config = Configuration.Default
                .WithDefaultLoader()
                .WithCss()
                .WithJavaScript();
```

**Expected behavior:** Ahm, this should work?!

**Actual behavior:** It doesn't work.

**Environment details:** Windows 10 Pro v2004 Build=19041.508

**Comment by FlorianRappl** [comment]
Hi @Gavin-Williams the `AngleSharp.Scripting.Js` is only for older versions of AngleSharp and deprecated. You should use `AngleSharp.Js` which brings a `WithJs` extension.

Hope that helps!

For details see the migration guide: https://github.com/AngleSharp/AngleSharp/blob/master/doc/Migration.md#scripting

This was mentioned in #841, too.
