### ISSUE TITLE
GetSelector - elements with number ids

### ISSUE THREAD

**Issue by RobertBaldini** [AngleSharp/AngleSharp#909]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?  (_non-alpha_, 0.14.0)
- [ ] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [ ] Did you perform a search in the issues? 

For more information, see the `CONTRIBUTING` guide.

## Description

`GetSelector` provides an "#id" selector starting with a number, which is invalid if you try to use it later.

(Reference: ) https://css-tricks.com/ids-cannot-start-with-a-number/

## Steps to Reproduce

See tests in branch.

**Expected behavior:** `<div id="1st">` --> `[id='1st']`

**Actual behavior:** `<div id="1st">` --> `#1st`

**Environment details:** .NET Core, Windows/Linux

## Possible Solution

Hi, I've used the `GetSelector` utility many times on a few different websites.

I recently tried a new website with some funky web standards.

This page has many elements that begin with a number, or are all numbers. (Like id = '0ab12cd3', possibly generated by some tool.)

I have a fork with a branch for a possible fix:
https://github.com/AngleSharp/AngleSharp/compare/master...robert-baldini:getselector-id-with-numbers

CSS id selectors that start with a number need to be escaped. (And sure enough, if you try `QuerySelector("#1st")`, you'll get an error. It fails for other tools also.)

The easiest way to escape it would be like: `[id='0ab12cd3']` or `[id='1st']`

I tried to keep it consistent with the existing behavior, so id will normally be passed back as "#id", unless it's neccesary to escape. The alternative would be to pass back the id with always using the square brackets.

**Comment by FlorianRappl** [comment]
Good finding! Can you make a PR with the proposed fix? Much welcome!

:beers:

**Comment by robert-baldini** [comment]
Sorry for the delay. The pull request should be ready in a couple minutes.

I was doing some research and I found a [better reference](https://mathiasbynens.be/notes/css-escapes) for CSS escape requirements.

A leading digit, like `#1`, does need to be escaped. So should the id `-1`, or `+1`. And a [few other](https://github.com/AngleSharp/AngleSharp/compare/master...robert-baldini:getselector-id-with-numbers#diff-889f5f0df89f7c938a090085ccfa94d2ee6d983976316af9f99556497aa39ec3R1036) characters too.

The easiest solution, to preserve the id with minimal escape, is to just select with the id attribute: `[id='-1']` or `[id='+1']`

Would there be any problems if the default behavior changes from `#identifier` to `[id='identifier']`?

**Comment by FlorianRappl** [comment]
Personally, I think the get selector should be as minimal and nice as possible.

IIRC there is a function in AngleSharp to check if its a valid CSS selector ID. Maybe if we use this we can distinguish the two cases (valid ->`#...`, invalid -> `[id="..."]`).
