### ISSUE TITLE
HTML parsing on Windows Phone 8.1 taking ages

### ISSUE THREAD

**Issue by matteocontrini** [AngleSharp/AngleSharp#91]
How to reproduce:
- Create a blank Windows Phone 8.1 .NET 4.5 application
- Put the following code inside OnNavigatedTo

``` c#
HttpClient client = new HttpClient();
string response = await (await client.GetAsync("https://google.com")).Content.ReadAsStringAsync();

DateTime before = DateTime.Now;
await new HtmlParser(response).ParseAsync();
DateTime after = DateTime.Now;

double seconds = (after - before).TotalSeconds;
await new MessageDialog(seconds.ToString()).ShowAsync();
```
- Run in debug. Seconds = about 12 seconds in my tests
- Run without debug. Seconds = 1.6 in my tests

Tell me if you can reproduce the problem.
This is not exactly a "milliseconds" parsing...

**Comment by FlorianRappl** [comment]
Hm, can't really reproduce (I get values between 0.1 and 0.2). Can you give me more details on your settings? 

I also didn't see a (significant) difference between debug and release.

**Comment by matteocontrini** [comment]
That's the result I get on a Lumia 820. More or less the same on a Lumia 1020.
And I wasn't talking about debug/release configurations, but Visual Studio debugger attached or not (launch from VS or in the apps list).
The app is an empty project with the code above.

Are you perhaps testing on the emulator?

**Comment by FlorianRappl** [comment]
Yes I am testing on the emulator. But honestly I am quite surprised that devices such as Lumia 820 or 1020 give such bad performance. I have some apps using AngleSharp on my Samsung Ativ S, which has similar specs, and parsing there is a smooth and pleasant experience.

That you are running on a real device wasn't obvious from your post. And "run in debug" / "run without debug" sounded like debug / release configurations.

**Comment by FlorianRappl** [comment]
I also tried with my phone (no emulator) and debugging I am roughly getting your number. Just running a release build without VS attached is much faster. However, the best performance I get when I don't do redundant string operations:

```
protected async override void OnNavigatedTo(NavigationEventArgs e)
{
    var client = new HttpClient();
    var response = await client.GetAsync("https://google.com");
    var content = await response.Content.ReadAsStreamAsync();
    var sw = Stopwatch.StartNew();
    await new HtmlParser(content).ParseAsync();
    sw.Stop();
    await new MessageDialog(sw.Elapsed.ToString()).ShowAsync();
}
```

Here I get around 100ms (no VS attached, release build and the code above).

**Comment by matteocontrini** [comment]
You're right, but how can I test my app if it's that slow with debug configuration + debugger? It takes more than 10 seconds whereas HtmlAgilityPack-PCL takes 140ms with debugger attached.

**Comment by FlorianRappl** [comment]
I can only recommend writing unit tests and using the emulator for logic tests. Attaching VS debugger to a connected device is only performed if unexplained problems occur.

I wouldn't care too much about speed in debugging - speed in production is much more important. That does not mean I won't fix your problem. In fact I would love to help you; but I really can't see what is causing the delay.

**Comment by corliss** [comment]
VS debugging can be very slow if exceptions are thrown and caught. Does AngleSharp rely on exception throw/catch internally during normal execution?

**Comment by FlorianRappl** [comment]
No it does not. There are just a few edge cases (e.g., obtaining an encoding from `Encoding`), where try-catch blocks are used, but these cases are not in hot paths.
