### ISSUE TITLE
GetSelector - pages with duplicate element ids

### ISSUE THREAD

**Issue by RobertBaldini** [AngleSharp/AngleSharp#910]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?  (_non-alpha_, 0.14.0)
- [ ] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [ ] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

`GetSelector` can produce a non-unique id, which is invalid if you try to use it later.

## Steps to Reproduce

See tests in branch.

**Expected behavior:** 

```csharp
<div id="something">First</div>
<span id="something">Second</span>

var span = parent.QuerySelector("span");
var spanSelector = span.GetSelector(); // spanSelector should be something like "body>span"
var queryResult = parent.QuerySelector(spanSelector); // gets the span
```

**Actual behavior:** 

```csharp
<div id="something">First</div>
<span id="something">Second</span>

var span = parent.QuerySelector("span");
var spanSelector = span.GetSelector(); // spanSelector is "#something"
var queryResult = parent.QuerySelector(spanSelector); // gets the div!
```

**Environment details:** .NET Core, Windows/Linux

## Possible Solution

Hi, I've used the `GetSelector` utility many times on a few different websites.

I recently tried a new website with some funky web standards.

This page has many elements with the same ID. (Like id = "RULE_SET", same id, all over the place. Possibly generated by some tool.)

I have a fork with a branch for a possible fix:
https://github.com/robert-baldini/AngleSharp/commit/28782f9200179a1b7ec5c2e447aec592571956e7

This fix will only stop at the id selector if the id selector is, in fact, unique.

Possible side effect: if 'Owner' is null, `isUnique` would be false, and it would probably go back to the root in that case. But it looks like 'Owner' is usually not null.

**Comment by FlorianRappl** [comment]
If `Owner` is `null` we should not generate a selector anyway, because in this case the element is disconnected from the document (i.e., no longer in the hierarchy).

A PR on this would be welcome! Much appreciated :beers:
