### ISSUE TITLE
System.NullReferenceException when try removing url attribute

### ISSUE THREAD

**Issue by ikesnowy** [AngleSharp/AngleSharp#914]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

removing url attribute (`src` in this case) with local path would cause an NRE.

```csharp
using AngleSharp.Html.Parser;

namespace AngleSharpNre
{
    class Program
    {
        static void Main(string[] args)
        {
            const string html = "<video src=\"D:\\videos\\learning\\tail.wmv\"></video>";
            var parser = new HtmlParser();
            var dom = parser.ParseDocument(html);
            dom.GetElementsByTagName("video")[0].RemoveAttribute("src");  // NRE
        }
    }
}
```

## Steps to Reproduce

1. Create a Console Application
2. Paste the code above
3. Run

**Expected behavior:** The attribute been removed successfully

**Actual behavior:** An NRE

**Environment details:** Windows 10, .Net 5.0 rc2, AngleSharp 1.0.0-alpha-827

**Comment by FlorianRappl** [comment]
Thanks for reporting this - will be fixed asap.

**Comment by ikesnowy** [comment]
@FlorianRappl 

Thanks for the quick fix, removing src attribute in video tag is working now!

Unfortunately after a little digging in my log file, I find out that embed tag has exactly the same issue😞 and can be reproduced with version alpha-842.

![image](https://user-images.githubusercontent.com/17109152/96813499-14de0a80-144f-11eb-9110-4b956e60c966.png)

**Comment by FlorianRappl** [comment]
Fixed and available in `devel` / the preview.
