### ISSUE TITLE
Use actual types in documentation and not 'var' keyword

### ISSUE THREAD

**Issue by LukeTOBrien** [AngleSharp/AngleSharp#915]
Hello chaps,

I am new to AngleSharp and wish to port and existing project from HAP to AngleSharp, so I am trying to figure out what classes to use.  
I have a number of existing methods that accept `HtmlDocument` or `HtmlNode` as parameters, so I am trying to figure out the equivalent class names.  

In your documentation you have a [getting started](https://anglesharp.github.io/docs/Basics.html), but you are using the `var` keyword, which is good for development and code maintainability but not so good for documentation.  

What do you think of changing the `var` keyword to the actual type in your documentation?

**Comment by FlorianRappl** [comment]
Sounds fair to me - actually, personally, I never care so much about types in the code examples. I rater care about the flow. But different people enjoy different styles - and the types should not be in the way.

You'd like to contribute here and make some PRs? Would be super helpful!

Thanks a lot :beers:

**Comment by LukeTOBrien** [comment]
I could contribute if I find the time, I have also just created some
extension methods that could be helpful too

**Comment by FlorianRappl** [comment]
Landed in `devel`
