### ISSUE TITLE
Improve ElementExtensions.IsEnabled and ElementExtensions.IsDisabled handling when implementation type is unknown

### ISSUE THREAD

**Issue by AStoney** [AngleSharp/AngleSharp#916]
https://github.com/AngleSharp/AngleSharp/blob/3968eb050e142b1d94550fba407afe772232b126/src/AngleSharp/Dom/ElementExtensions.cs#L308
https://github.com/AngleSharp/AngleSharp/blob/3968eb050e142b1d94550fba407afe772232b126/src/AngleSharp/Dom/ElementExtensions.cs#L349

Can we improve how this works when the implementation type is not known? Anyone implementing IElement for a WrapperElement or a custom element is left out in the cold and has no way to get anything other than false to return. Even just defaulting to the GetAttribute method on line 337 and 373 respectively would be better than nothing.

**Comment by FlorianRappl** [comment]
> Can we improve how this works when the implementation type is not known?

I don't know - can we? Any proposal?

What needs to be done is:

1. It needs to satisfy the spec
2. It should be quite fast
3. If extended / broken it must be done explicitly so (i.e., it should be quite robust)

**Comment by AStoney** [comment]
```
public static Boolean IsEnabled(this IElement element)
{
...
else
{
   string isDisabled = element.GetAttribute(null, AttributeNames.Disabled);
   return isDisabled == null;
}
...
```
```
public static Boolean IsDisabled(this IElement element)
{
...
else
{
   string isDisabled = element.GetAttribute(null, AttributeNames.Disabled);
   return isDisabled != null;
}
...
```


Seems to be working in my case. (using bUnit against a Blazor project to verify a button gets disabled. bUnit uses a WrapperElement that implements IElement and passes through most method/property calls)

I think html specs say a disabled attribute being present means the parent element should be unusable, so I am not sure it makes sense to reuse code on 337 and 373 like I had suggested earlier because `element.GetAttribute(null, AttributeNames.Disabled);` is returning empty string when the attribute is present, but does not have a value and null when the attribute does not exist.
