### ISSUE TITLE
When trying to load a file it always returns null

### ISSUE THREAD

**Issue by Sicos1977** [AngleSharp/AngleSharp#917]
When trying to load a local file like this then document is always null

`var  document = context.OpenAsync(new Url(@"file://d:\test.html")).GetAwaiter().GetResult();`

Why is this? file:// is also a valid url schema

**Comment by FlorianRappl** [comment]
It may be a valid URL in your browser, but to handle this in AngleSharp you need a proper provider. A `file:` schema handler can be provided, e.g., by using the requesters from AngleSharp.Io.

Hope that helps!

**Comment by FlorianRappl** [comment]
(Just to complete `foo:bar` is also a valid URL (its the `foo` schema with quantifier `bar`, but at least my browser does not understand what I refer to here. So there are two things needed: A spec compliant URL (true) and a proper handler for the schema (`file` is not handled by the core as our .NET subset does not yield any FS access). The latter is missing.)
