### ISSUE TITLE
`InvalidOperationException` due to failing `VerifyIntegrity`

### ISSUE THREAD

**Issue by matthewDDennis** [AngleSharp/AngleSharp#918]
Our Web Server code uses AngleSharp to do various HTML cleanup and Colourization.
Today we start to get InvalidOperationExceptions on only 1 of our 6 servers
From the stack trace, it looks like something might be missing some error handling.
___
Exception of type 'System.InvalidOperationException' was thrown.
```
at System.Runtime.CompilerServices.ConditionalWeakTable`2.VerifyIntegrity()
at System.Runtime.CompilerServices.ConditionalWeakTable`2.TryGetValue(TKey key, TValue& value)
at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
at AngleSharp.Css.StyleAttributeObserver.AngleSharp.Dom.IAttributeObserver.NotifyChange(IElement host, String name, String value)
at AngleSharp.Dom.Element.SetupElement()
at AngleSharp.Html.Dom.HtmlImageElement.SetupElement()
at AngleSharp.Html.Parser.HtmlDomBuilder.CloseCurrentNode()
at AngleSharp.Html.Parser.HtmlDomBuilder.InBodyStartTagBreakrow(HtmlTagToken tag)
at AngleSharp.Html.Parser.HtmlDomBuilder.InBodyStartTag(HtmlTagToken tag)
at AngleSharp.Html.Parser.HtmlDomBuilder.Parse(HtmlParserOptions options)
at AngleSharp.Html.Parser.HtmlParser.Parse(HtmlDocument document)
at CodeProject.Modules.Articles.Article.get_FormattedContent()
```

**Comment by FlorianRappl** [comment]
> Today we start to get InvalidOperationExceptions on only 1 of our 6 servers

Hm we must be sure that this is indeed an AngleSharp error and not something in the server (e.g., memory corruption). Multiple hints are there for the latter, specifically that `VerifyIntegrity` usually only fails if the collection was corrupted.

Check the implementation here: https://referencesource.microsoft.com/#mscorlib/system/runtime/compilerservices/ConditionalWeakTable.cs

If you can provide a reproducible (e.g., the source code of the HTML file where this fails) then we can do something here.

**Comment by matthewDDennis** [comment]
I think I found the problem.
ConditionalWeakTable ends up with the _invalid flag set if the lock is aborted, such a on a web page timeout or out of memory error.  Once this condition occurs, it is permanent.

This is not a problem with transient instance of the class, but in the case of a static instance, this results in a permanently broken ConditionalWeakTable.

Unfortunately, ImportLinkRelation has a static instance of a ConditionalWeakTable, and I'm not sure why it is static.

I'm going to dig in and see what the impact of removing the static qualifier.

**Comment by matthewDDennis** [comment]
I made changes to my fork to remove the static quailifier.
The only test that failed was SettingCookieIsPreservedViaRedirect.

**Comment by FlorianRappl** [comment]
> Unfortunately, ImportLinkRelation has a static instance of a ConditionalWeakTable, and I'm not sure why it is static.

For memory efficiency this should be 1 shared instance (the instance itself could also live somewhere else, but since its only used here its the logical place). Otherwise, every instance will also have an instance of the CWT - increasing the size by a fair margin.

The `SettingCookieIsPreservedViaRedirect` is broken due to a change in how cookies are transported in httpbin IIRC - it has nothing to do with this change.

If your investigation is right then just solving this algorithmically would work, too - I mean we could just add the item if we succeeded with the call.

**Comment by matthewDDennis** [comment]
No, it wouldn't.  Once the static ConditionalWeakTable gets corrupted, it is permanently broken.  You can't even Add as the Verify fails.

**Comment by FlorianRappl** [comment]
>  Once the static ConditionalWeakTable gets corrupted, it is permanently broken.

But why does it get corrupted? Why don't we just prevent it from being corrupted in the first place?

**Comment by matthewDDennis** [comment]
How do you propose the stop a ThreadAbort or OutOfMemory exception from occurring at just the wrong time?
We are seeing it once or twice every couple of weeks at CodeProject, probably because of the amount of traffic we have.

I'm not even sure how I would go about trapping the cause of this.

**Comment by matthewDDennis** [comment]
Also, you have had reports of similar issue for a few years now.

**Comment by FlorianRappl** [comment]
Hi @matthewDDennis I think there is a misunderstanding here. Before we go into the wrong direction I'd like to sort that out.

- The fix should not be just on this spot (as it seems rather generic from your description).
- We use the CWT on a couple of spots, so the described behavior may occur at multiple occasions.

> How do you propose the stop a ThreadAbort or OutOfMemory exception from occurring at just the wrong time?

So my questions would be:

Why is there a `ThreadAbort`? Wouldn't that destroy the whole thread? Likewise, an `OutOfMemory` would destroy the whole application - so are these two real scenarios?

In general shouldn't any use of a CWT therefore be a problem as they all would get corrupted (not just this particular one)?

**Comment by matthewDDennis** [comment]
Yes, other parts of AngleSharp is the CWT, but only as instance variables. So if the thread is aborted, only the instance that is on that thread gets corrupted, but it's going away anyways. 
With a static CWT any TheadAbort could corrupt the CWT used by everyone. 
I'm not sure why you need a global instance here. Why not just have a collect, possibly lazy loaded, as a property of the document. The CWT is keyed by the IDocument, so the scope and lifetime would be the same. 
Not saying you are wrong, just trying to understand the design decision.

**Comment by FlorianRappl** [comment]
> just trying to understand the design decision.

Already gave the explanation. Its memory consumption. The other CWTs do not live in parts that are used N times in a document, but are usually tied to a context (directly or indirectly).

**Comment by matthewDDennis** [comment]
I understand this.  My concern that there is a failure mode that leaves AngleSharp in an unusable state.
Granted, this is triggered by a rare condition, but the consequences are critical.
I'm not sure how the CWT can be 'repaired' or if it could be replaced with an new one.
Would replacing it result in the LinkRelations being reloaded for the document.
AngleSharp is amazing, but it is big.  I'm a little concerned about the implications of any changes.

Just to be clear, you use the static CWT allows you to share ImportLists between different IDocument instances if the instances are 'Equal'.  This would reduce the amount of memory and loading.

Unfortunately, I don't think the CWT works the way you think, as it does not use the Equals method to compare the keys.  From the document:

> Keys must be unique; in other words, the ConditionalWeakTable<TKey,TValue> class supports one attached value per managed object. Two keys are equal if passing them to the Object.ReferenceEquals method returns true.

 > Note
You cannot control equality comparisons by overriding Object.GetHashCode to explicitly set the hash code for a key. The ConditionalWeakTable<TKey,TValue> class does not use the Object.GetHashCode method to compute hash codes, and therefore does not invoke Object.GetHashCode overrides.

This means that there is no sharing between different IDocument instances, even if they are 'Equal'.

**Comment by FlorianRappl** [comment]
> This means that there is no sharing between different IDocument instances, even if they are 'Equal'.

This is fine. It works exactly as I think it works. Why do you think I want to use the same value for different `IDocument` instances? That does not make any sense to me.

I'll look into the code - actually, I do think at the given location there may not be any need for a CWT (or a member reference to an owner whatsoever). In general I think it may make sense to replace the CWT instances (even if non-static) if possible. As they are non-static it is not as critical, but maybe worth the effort nevertheless.

Thanks again for your thoughtful investigation and suggestions. Much appreciated!

**Comment by matthewDDennis** [comment]
I though you might be using the same value for multiple IDocuments based on the implementation of Document.Equals.

I've tracked down how the CWT is being corrupted.  
When we load an Article for display, we use AngleSharp to format/sanitize the HTML content of the article if it hasn't been cached recently.
There are a few pages that load a lot of Articles, and under high load, these pages are timing out, usually in the formatting methods.
When a page times out, it throws a ThreadAbortException, and because of where the code is executing there is a better chance than average of the exception being thrown while in the CWT code, causing the CWT corruption.

This may be causing issues in other libraries we are using, and I am investigating,  Probably will need to write a Tip/Article about this.

**Comment by matthewDDennis** [comment]
FYI,
I've eliminated all code that could cause Thread Aborts and the issue has not been observed since.

**Comment by matthewDDennis** [comment]
according to the commit comment, and the code, the CWT in ImportLinkRelations has not been fixed.  This is the code that was causing my issues.  I am still getting the occasional Anglesharp  lockup.

**Comment by FlorianRappl** [comment]
Feel free to make a PR (that's the beauty of open-source).
