### ISSUE TITLE
Windows1252, Big5 etc. initialized with UTF8

### ISSUE THREAD

**Issue by jaladaGmbH** [AngleSharp/AngleSharp#919]
You know, in .Net Standard the function "**Encoding.GetEncoding(string code)**" only returns code pages that are supported on the the specific platform. Any additional encoding is only available after registering an **EncodingProvider** object. 

Therefore you need to make sure that the function "Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)" is called before you initialize your static class **TextEncoding** and especially static elements like "**public static readonly Encoding Big5;**"

A better implementation of your TextEncoding class should therefore have a static constructor in the following form:
`

        #region Constructor
        static TextEncoding()
        {   
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            Utf8 = new UTF8Encoding(false);
            Utf16Be = new UnicodeEncoding(true, false);
            Utf16Le = new UnicodeEncoding(false, false);
            Utf32Le = GetEncoding("UTF-32LE");
            Utf32Be = GetEncoding("UTF-32BE");
            Gb18030 = GetEncoding("GB18030");
            Big5 = GetEncoding("big5");
            Windows874 = GetEncoding("windows-874");
            Windows1250 = GetEncoding("windows-1250");
            Windows1251 = GetEncoding("windows-1251");
            Windows1252 = GetEncoding("windows-1252");
            Windows1253 = GetEncoding("windows-1253");
            Windows1254 = GetEncoding("windows-1254");
            Windows1255 = GetEncoding("windows-1255");
            Windows1256 = GetEncoding("windows-1256");
            Windows1257 = GetEncoding("windows-1257");
            Windows1258 = GetEncoding("windows-1258");
            Latin2 = GetEncoding("iso-8859-2");
            Latin3 = GetEncoding("iso-8859-3");
            Latin4 = GetEncoding("iso-8859-4");
            Latin5 = GetEncoding("iso-8859-5");
            Latin13 = GetEncoding("iso-8859-13");
            UsAscii = GetEncoding("us-ascii");
            Korean = GetEncoding("ks_c_5601-1987");
            encodings = CreateEncodings();
        }
        #endregion
`
I have attached a fixed source:
[TextEncoding.zip](https://github.com/AngleSharp/AngleSharp/files/5579749/TextEncoding.zip)

**Comment by FlorianRappl** [comment]
Maybe I miss the issue, but this is rather for the calling application. Otherwise, the call has to be conditional on the output target.

Just as a reminder: AngleSharp is produced also as non-.NET Standard library. [Here](https://github.com/AngleSharp/AngleSharp/blob/master/build.cake#L6) you can see the targets directly.

**Comment by jaladaGmbH** [comment]
Sorry for my delay,
> Maybe I miss the issue, but this is rather for the calling application. Otherwise, the call has to be conditional on the output target.
> 
> Just as a reminder: AngleSharp is produced also as non-.NET Standard library. [Here](https://github.com/AngleSharp/AngleSharp/blob/master/build.cake#L6) you can see the targets directly.

That's right, but you missed, that you used the encoding inside your framework, when you decode a response. So on .netcore, .netstandard your IDocument is unusable at the moment, when the webserver sends you a response which is not in "utf-8".

Best regards

**Comment by FlorianRappl** [comment]
And what prevents you to have this encodings set up in your application?

If all you give AngleSharp is UTF-8 then it will just work with that. That's why it falls back to it.

**Comment by jaladaGmbH** [comment]
The problem is that you have no initialize routine for AngleSharp. You use for your text encoding a static class and readonly fields. But in dotnet it is not clearly defined when a static class will be initialized. Theoretical when the app will be launched, technically the moment when the .dll is loaded.

If the DLLs are loaded on launch, then the App constructor is called after the initialization of any static class and the needed call to **Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);** comes to late.

If this has happen, a call to AngleSharp.Text.TextEncoding.Big5 will then return UTF8Encoding which is definitely wrong.  Also sending a request to a Chinese or Japanese server via AngleSharp will return only wrong encoding trash, because you are using your TextEncoding class to convert the stream from the response to the internal used html/xml-string. 

But if you thing that is not a bug, that is not my problem. It is open source so I can fix it by my own and use the corrected version.

**Comment by FlorianRappl** [comment]
> But in dotnet it is not clearly defined when a static class will be initialized.

Its quite well defined. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-constructors

Just place the `Encoding.RegisterProvider` as one of your first calls in `Main`. AngleSharp is not responsible for the environment you present to it. If your environment does not have necessary encoding providers then this is your problem.
