### ISSUE TITLE
Most of websites cannot be loaded

### ISSUE THREAD

**Issue by ossaltu** [AngleSharp/AngleSharp#92]
Here is the example:

```
var url = new Uri("http://www.amazon.com");
var config = new Configuration().WithDefaultLoader().WithCss();
var loaded = await BrowsingContext.New(config).OpenAsync(url.ToString());
```

**Comment by FlorianRappl** [comment]
I think this is a bug in the CSS parsing that I've detected a few days ago. A fix is already committed and will be released shortly.

**Comment by FlorianRappl** [comment]
(but feel free to check if it is really CSS to blame; i.e. try without the `WithCss()`)
