### ISSUE TITLE
Cannot set Referer header

### ISSUE THREAD

**Issue by jcotton42** [AngleSharp/AngleSharp#920]
# Bug Report

## Description

Setting the `Referer` header seems to be ignored.

## Steps to Reproduce

```csharp
var requester = new DefaultHttpRequester();
requester.Headers.Add("Referer", "https://example.com/");
// custom header to show the issue is specifically with Referer
requester.Headers.Add("X-Test", "SomeVal");

var config = Configuration.Default.With(requester).WithDefaultLoader();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync("https://httpbin.org/get");
Console.WriteLine(document.Prettify());
```

**Expected behavior:**

Demonstrated with `curl -H 'Referer: https://example.com/' -H 'X-Test: SomeVal' httpbin.org/get`

```json
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "Referer": "https://example.com/", // note, present here, but not below
    "User-Agent": "curl/7.68.0",
    "X-Amzn-Trace-Id": "Root=1-5fc1f68d-480d76f8218f2b4a0d485d03",
    "X-Test": "SomeVal"
  },
  "origin": "REDACTED IP",
  "url": "http://httpbin.org/get"
}
```

**Actual behavior:**

```json
{
    "args": {},
    "headers": {
        "Accept": "text/html,application/xhtml+xml,application/xml",
        "Accept-Encoding": "gzip, deflate",
        "Host": "httpbin.org",
        "User-Agent": "AngleSharp/0.14.0.0",
        "X-Amzn-Trace-Id": "Root=1-5fc1f6ec-78b9bcc5700ac1216ff8dc0c",
        "X-Test": "SomeVal"
    },
    "origin": "[REDACTED IP ADDRESS]",
    "url": "https://httpbin.org/get"
}
```

**Environment details:**

* Windows 10 1909 64-bit
* .NET 5.0
* AngleSharp 1.0.0-alpha-844 (latest prerelease) or 0.14.0 (latest release)

## Possible Solution

UPDATE: I did find a workaround for the meantime, create the `DocumentRequest` yourself

```csharp
var req = DocumentRequest.Get(new Url("https://httpbin.org/get"), referer: "https://www.example.com/");
var document = await context.OpenAsync(req);
```

No ideas from me, but this *is* possible with `HttpClient` directly for what it's worth

```csharp
using System.Net.Http;

var c = new HttpClient();
c.DefaultRequestHeaders.Referrer = new Uri("https://example.com/");

var response = await c.GetStringAsync("https://httpbin.org/get");
Console.WriteLine(response);
```

Gives:

```json
{
  "args": {}, 
  "headers": {
    "Host": "httpbin.org", 
    "Referer": "https://example.com/", 
    "X-Amzn-Trace-Id": "Root=1-5fc1f880-3574415a09b08bfc7c98ab12"
  }, 
  "origin": "REDACTED", 
  "url": "https://httpbin.org/get"
}
```

**Comment by jcotton42** [comment]
Digging into AngleSharp, looks like it uses `WebRequest`, which definitely should also work with this

```csharp
var req = WebRequest.Create("https://httpbin.org/get") as HttpWebRequest;
req.Referer = "https://example.com/";
var response = req.GetResponse() as HttpWebResponse;
var stream = response.GetResponseStream();
var reader = new StreamReader(stream);
Console.WriteLine(reader.ReadToEnd());
```

Gives

```json
{
  "args": {}, 
  "headers": {
    "Host": "httpbin.org", 
    "Referer": "https://example.com/", 
    "X-Amzn-Trace-Id": "Root=1-5fc28645-49b1abb54105950532e3f36f"
  }, 
  "origin": "REDACTED", 
  "url": "https://httpbin.org/get"
}
```

**Comment by FlorianRappl** [comment]
The refererer is set by AngleSharp when navigating. This is the expected behavior. If you want to override headers that are set explicitly by AngleSharp then use a request filter instead. A request filter allows you to do anything with the request (as built by AngleSharp).

Regarding `HttpClient`. Instead of using the `DefaultRequester` you can also use the `HttpClientRequest` from AngleSharp.Io. Actually, this would be my recommendation, too. The only reason for using `WebRequest` is that it is supported in the all the targets that AngleSharp builds to.

**Comment by jcotton42** [comment]
Ah ok. Makes sense, thanks for replying.

**Comment by jcotton42** [comment]
Only just now got back to this, by "filter" are you referring to the `Filter` predicate in `LoaderOptions`?

**Comment by jcotton42** [comment]
Also, you pointing me to AngleSharp.Io made me realize a much better way to do this, using navigation so AngleSharp sets `Referer` for me:

```csharp
var config = Configuration.Default
    .WithRequester(new HttpClientRequester())
    .WithDefaultLoader(new LoaderOptions {
        IsResourceLoadingEnabled = true
    });

var context = BrowsingContext.New(config);
var resourceLoader = context.GetService<IResourceLoader>();

var page1Url = "https://www.example.com/1";
var page2Url = "https://www.example.com/2";

var page1 = await context.OpenAsync(page1Url);
context.NavigateTo(page1);
await Task.Delay(250);

var coverElem = chap1.QuerySelector(".cimage[data-original]");
var coverUri = coverElem.GetAttribute("data-original");
if(coverUri.StartsWith("//")) {
    coverUri = "https:" + coverUri;
}
var coverUrl = new Url(coverUri);

// there's a cancel method on the return value of FetchAsync
// have a CancellationToken call that
var download = await resourceLoader.FetchAsync(new ResourceRequest(coverElem, coverUrl)).Task;
Console.WriteLine("Cover content type: {0}", download.Headers["Content-Type"]);
await download.SaveToAsync("C:/Users/Joshua/Desktop/cover.jpg");

var page2 = await context.OpenAsync(page2Url);
context.NavigateTo(page2);
```

I'm not really sold on doing `var resourceLoader = context.GetService<IResourceLoader>();` though, feels like a hack.

Is there a nicer way of saying "download the resource at this URL for me as if the request came from a given document (e.g. the active one)"?

**Comment by FlorianRappl** [comment]
There is the `DownloadAsync` extension from AngleSharp.Io (see https://github.com/AngleSharp/AngleSharp.Io/blob/master/src/AngleSharp.Io/Dom/ElementExtensions.cs#L89). It pretty much does what you want except using the `referer`. I guess this would be a nice addition there (e.g., having some options like `IncludeReferer`).

**Comment by jcotton42** [comment]
Yeah I looked at `DownloadAsync` but it doesn't quite work for this since the `src` attribute on the `img` tag I'm downloading from isn't set until a JS event happens as a form of lazy loading (the real URL is in `data-original` though).

**Comment by FlorianRappl** [comment]
I see, right. Yeah that sucks. Especially since that means you need to do some logic (which you apply in your sample code,e.g., finding out if the URL is already absolute or relative, which would be auto-handled by AngleSharp / a browser using an `Href` property).

Maybe this is a good pointer that a generic `GetAttributeAsUrl` helper would be great. Then using an `Url` in context of a document could be provided to build a generic request (e.g., using an extension method `CreateRequestFor(this Url url, IDocument document)`).

**Comment by jcotton42** [comment]
Maybe a more generic `ResolveUrlRelativeToDocument` than one specifically for attributes (but also more succulently named), but yeah.

Though in my case it's actually not a relative URL, but rather one without a protocol (with the browser adding on HTTP or HTTPS to match the page (never understood why pages do this instead of just using HTTPS though)).

But yeah I've got a working solution now, I was just wondering if it was the most idiomatic way to do it, b/c asking the browsing context for it's `IResourceLoader` felt weird and wrong.

**Comment by FlorianRappl** [comment]
> Though in my case it's actually not a relative URL, but rather one without a protocol (with the browser adding on HTTP or HTTPS to match the page (never understood why pages do this instead of just using HTTPS though)).

This is also kind of a relative URL (usually called protocol-relative URL). Its path-absolute, but the URL is relative in the sense that it needs information from the parent URL to be fully qualified (e.g., it may be `//foo.com/bar`, but if is `https://foo.com/bar` or `http://foo.com/bar` depends on the parent - if we are at `https://foo.com/qxz` or `http://foo.com/qxz`).

I think adding such a convenience extension method makes sense. Any proposals (like the `ResolveUrlRelativeToDocument ` - what is its signature?) or should we just go ahead with an implementation?

**Comment by jcotton42** [comment]
Sorry for taking so long to get back.

I'm not sure we need a full on method for it, but some way of resolving URLs relative to a document the same way a browser would is important, I can see there's a few props on `IDocument` for this: `Url`, `BaseUri`, `BaseUrl`, and `DocumentUri`. Though I'm not sure which to use.

**Comment by FlorianRappl** [comment]
> some way of resolving URLs relative to a document the same way a browser would is important

We have it. Its on the same properties as in the browser (by spec). For instance, the `Href` on an anchor tag behaves like this. In JS you would solve the problem also using an `href`.

```cs
var coverUri = coverElem.GetAttribute("data-original");
var anchor = document.CreateElement<IHtmlAnchorElement>("a");
anchor.Href = coverUri;
var normalizedUri = anchor.Href;
```

The ones you listed are on the `IDocument` and just give you the document's URL - which is great to start rolling your routine, but nothing more.

**Comment by jcotton42** [comment]
True. A method for this might be best then, not sure where to put it though.
