### ISSUE TITLE
why I can not scrape youtube website ?

### ISSUE THREAD

**Issue by ghost** [AngleSharp/AngleSharp#921]
Hi, I'm new in anglesharp I want to scrap a dynamic website like youtube but I can not. 
in my code I want to get video titles from "youtube.com" url  :
                     
			var config = Configuration.Default.WithDefaultLoader().WithCss().WithJs();
			var context = BrowsingContext.New(config);

			var document = await context.OpenAsync(url, cancellationToken).WaitUntilAvailable(cancellationToken);

			var postTitles = document.QuerySelectorAll("a#video-title-link.yt-simple-endpoint.style-scope.ytd-rich-grid-media");
			var count = postTitles.Length;
			List<string> titleList=new List<string>();

			var title = document.Title;

			foreach (var postTitle in postTitles)
			{
				titleList.Add(postTitle.Text());
			}
		
			var result= string.Join(',', titleList);
			return result;

how can I scrap data from dynamic websites (angular, react, blazor webassembly, ...)

**Comment by FlorianRappl** [comment]
First sentence in the README:

> AngleSharp is a .NET library that gives you the ability to parse angle bracket based hyper-texts like HTML, SVG, and MathML.

What you are after is for instance using [Chromedriver](https://chromedriver.chromium.org/) or an abstraction on top of it such as [Playwright](https://github.com/microsoft/playwright).
