### ISSUE TITLE
AngleSharp never gives a result on using "await context.OpenAsync(url)"

### ISSUE THREAD

**Issue by ghost** [AngleSharp/AngleSharp#922]
I've been trying to get to know AngleSharp to use it in a project I am working on. But I seem to have run into an issue that no one else seems to have (after searching a lot), and I don't know where to begin to get it to work.

I have done the bare minimum project (.net standard 2.0 class library) where I simply have the following code in a class:

```
var config = Configuration.Default.WithDefaultLoader();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync("https://google.com");
```

When I call this class from a testproject (tried both web and windows application) it stops on the last row and never continues. I have tried many different urls but none work. So I downloaded the source and compiled into my solution in order to debug where it goes wrong, and it seems to be here (function NavigateAsync in DefaultNavigationHandler):

```
using (var response = await download.Task.ConfigureAwait(false))
```

This is where it stops to wait and never recovers. I have waited for 20+ minutes and nothing happens. Clearly something is very wrong since I can't even get the simplest example to work but I have no idea why. There are no exceptions or errors, just waiting forever. I have never been able to successfully load a single webpage despite trying different things, uninstalling and reinstalling AngleSharp etc etc. Hope you can bring some clarity to my issue.

**Comment by FlorianRappl** [comment]
Sounds strange to me. What is your HTTP traffic telling you?

I tried the same and for me it works. Are you behind a proxy? Most likely this is related to HTTP handling in .NET rather than AngleSharp, but we'd like to learn and improve.

**Comment by ghost** [comment]
I do not have Fiddler or similar installed on this computer at the moment, guess that will have to be my next step.

I am not behind any proxy, run VS2019 Community on a standard Win10 machine, connected to fibre via an asus router, and have never had connection issues before.

I have recently tried a few different .net libraries for opening and parsing websites, like HtmlAgilityPack and Selenium. They both worked well enough but lacked a few things I hoped AngleSharp would help me with. So they did not show any issues like this.

Do you have any suggestion of anything I could try using standard .net libraries that should display similar issues as when using AngleSharp?

**Comment by FlorianRappl** [comment]
Can you try using the `HttpClient` instead of the `WebRequest`? Its recommended anyway...

Just follow the instructions from `AngleSharp.Io`.
https://github.com/AngleSharp/AngleSharp.Io

**Comment by ghost** [comment]
I did try out .Io as well. Is there anything apart from

```
var config = Configuration.Default.WithRequesters(new HttpClientHandler()).WithDefaultLoader();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync("https://google.com");
```

that I should try? Because it gives the same issue. Also tried using .With() instead of .WithRequesters() and also creating a new HttpClient using the handler and then using .With(httpclient). Still no luck at all.

I also installed Fiddler, tried to load an unsecure http site via AngleSharp, and can verify that it downloaded the full html page (same size as when browsing the site in a browser). Still does not stop waiting.

**Comment by Shogo175R** [comment]
same here any fix?

**Comment by mirkojpn87** [comment]
same here, i was able to load the document using OpenNewAsync instead but looks empty


`            
```
            var option = new AngleSharp.Io.LoaderOptions();
            option.IsNavigationDisabled = false;
            option.IsResourceLoadingEnabled = true;
            var config = Configuration.Default
                .With(new HttpClientRequester()) // only requester
                .WithDefaultLoader();
            var context = BrowsingContext.New(config);


            var document = await context.OpenNewAsync("https://www.google.com/");           

            Debug.WriteLine(document.Title);
            await document.QuerySelector<IHtmlFormElement>("form").SubmitAsync(new
            {
                Search = "test"
            });`

since document.Title is returning and empty string something is going wrong i think.. any help?

**Comment by FlorianRappl** [comment]
@Shogo175R You use the wrong API. `OpenAsync` is the one that opens an address, `OpenNewAsync` gives you a blank document with the address set to what you wrote.

**Comment by mirkojpn87** [comment]
> @Shogo175R You use the wrong API. `OpenAsync` is the one that opens an address, `OpenNewAsync` gives you a blank document with the address set to what you wrote.

thank's you for your reply.
my fault, ( i used OpenAsync before that i switched to OpenNewAsync and wrote here ) since i'm having the same issue as @stonksi i'm trying to find a way to make it works ( when i use OpenAsync the app exit with a code 0 and no exception are throw)

**Comment by FlorianRappl** [comment]
This works. I ran it myself. If it does not work for you then its most likely a network (presumably HTTPS) issue.

Read on StackOverflow how to resolve such issues (see: https://stackoverflow.com/questions/22251689/make-https-call-using-httpclient).

Most likely, it's either going to be

```cs
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
```

or

```cs
ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;
```

I cannot tell you what and how, as this depends on a lot of factors (OS, .NET, ...).

**Comment by markjerz** [comment]
For anyone else who finds this, I too ran in to this issue. In my case it appears to have been a problem with the fact that my project was also referencing HtmlSanitizer which depends on AngleSharp but that had a different version.
