### ISSUE TITLE
HtmlSelectElement change

### ISSUE THREAD

**Issue by Robelind** [AngleSharp/AngleSharp#923]
When calling `ChangeAsync` on a HtmlSelectElement there's an exception saying that 

> The element does not have an event handler for the event 'onchange', nor any other events.

I find that odd, since the `<select>` element has an 'onchange' event.

**Comment by FlorianRappl** [comment]
I don't know what `ChangeAsync` is or should be. AngleSharp does not have this method nor does it give you access to `HtmlSelectElement`. The only thing this lib exposes it `IHtmlSelectElement` and that, too, does not have such a method.
