### ISSUE TITLE
How to parse string to IDocument?

### ISSUE THREAD

**Issue by TuTAH1** [AngleSharp/AngleSharp#930]
I don't like AngleSharp's `await BrowsingContext.New(config).OpenAsync(urlAddress);` (don't like await-async things). I would like to use a standard HTML parser and then use it with AngleSharp functions. Can I?

**Comment by FlorianRappl** [comment]
Sure just use the `HtmlParser` directly or from the `BrowsingContext` using the `IHtmlParser` interface.

Keep in mind that a context is always required - it brings necessary services and sets the boundary conditions.
