### ISSUE TITLE
string to IDocument

### ISSUE THREAD

**Issue by TuTAH1** [AngleSharp/AngleSharp#931]
Is there a way to parse a string with HTML code to IDocument or other interfaces that can do CSS things?

**Comment by FlorianRappl** [comment]
The GitHub issue tracker is for issues only. For questions please use StackOverflow.

If you have a string that needs to be parsed then just use `OpenAsync` from the `IBrowsingContext`. Together with the fake response overload (e.g., `res => res.Content(myHtmlString)`) this is the way to go. Hope that helps.
