### ISSUE TITLE
Custom elements as children of table and tr elements

### ISSUE THREAD

**Issue by geo98003** [AngleSharp/AngleSharp#932]
We have a need to parse a table that has custom elements inside the table definition.  It looks like this

```
<table border="1">
	<tr>
		<cellgroup>
			<td>Data in group</td>
			<td>Data in group</td>
		</cellgroup>
		<td>Data out of cell group</td>
	</tr>
</table>
```

We need to be able to use cellgroup as an element in the DOM as a child of the tr element and parent to the td elements, but it appears when parsing it anything not a td element or th element as a child of a tr element is placed before the table element in the DOM.  Is there a way to keep it inline in the table?

**Comment by FlorianRappl** [comment]
Unfortunately not.

This is the HTML5 specification and its treatment of tables. Custom elements are really just JS constructs, as such they are pretty much always treated as "unknown" elements from a DOM perspective. There is no way to teach the parser that "cellgroup" is actually a legal table element and that the standard algorithms (e.g., moving non-table elements outside of table structures) should not be applied here.

Chrome (or any other HTML5 compliant browser) does the same:

![image](https://user-images.githubusercontent.com/1766191/106191869-b641ce80-61ab-11eb-92f1-db6a5cab4126.png)

**Comment by geo98003** [comment]
In the HTML 5 spec it states that table and tr elements can contain "optionally intermixed with one or more script-supporting elements."  What would these elements be and is there a way for me to leverage those in this case?
