### ISSUE TITLE
XhtmlMarkupFormatter converts empty <title></title> tags into self-closing <title/> tags

### ISSUE THREAD

**Issue by sksk571** [AngleSharp/AngleSharp#933]
When document is rendered using XhtmlMarkupFormatter, empty <title></title> tags are replaced with self-closing <title/> tags.

```csharp
#r "nuget:AngleSharp/1.0.0-alpha-844"
//#r "nuget:AngleSharp/0.14.0" // same result in the stable version

using AngleSharp.Html.Parser;
using AngleSharp.Xhtml;

var html = "<title></title>";
var doc = new HtmlParser().ParseDocument(html);
var sw = new StringWriter();
doc.ToHtml(sw, new XhtmlMarkupFormatter ());

Console.WriteLine(sw.ToString());
```

Resulting markup: `<html><head><title /></head><body /></html>`

This markup is invalid, as end tag is required for title https://www.w3.org/TR/html401/struct/global.html#h-7.4.2

**Comment by FlorianRappl** [comment]
Hm, I am not sure if this is a real issue. The non-self-closed `title` element comes from HTML, but you stringify the document with XHTML. IIRC XHTML has the same rules for serialization as XML. So not sure if the HTML4 (or 5 or any other) specification can be used for this.

![grafik](https://user-images.githubusercontent.com/1766191/107058295-ba39a600-67d4-11eb-97d2-2d1c6cf40d60.png)

Also checking this against XHTML tells me its totally valid (https://validator.w3.org/check).

**Comment by sksk571** [comment]
I appreciate that this markup is valid according to W3C validator, but the browsers treat <title/> as the opening tag and put the rest of the document into title. Try to open this in the latest Chrome:
```html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html><head><title /></head><body /></html>
```

This is what I get:
![image](https://user-images.githubusercontent.com/2163198/107063624-a6e60500-67eb-11eb-9d4d-978dae824dd1.png)

**Comment by FlorianRappl** [comment]
This is not a problem of the serialization, but that Chrome does not support proper XHTML by standard means. You need at least:

- Send the proper mime type (`application/xhtml+xml`)
- Have the right XML namespace (missing in your snippet above, see `html` tag)
- Have the correct doctype
- Have the correct preamble

At the end of the day it also does not matter - the spec is the spec and if Chrome (or any other browser) does not follow it this is not the problem of the spec or other implementations (such as AngleSharp).

**Comment by sksk571** [comment]
Yes, this is understandable, but... We are using Premailer.Net to inline CSS in emails created by our clients. Premailer.Net in turn uses AngleSharp to deal with HTML document. This bit of code does the inline and renders the results: https://github.com/milkshakesoftware/PreMailer.Net/blob/d6bd652cb924a18aeefe7002e5671209488acfcb/PreMailer.Net/PreMailer.Net/PreMailer.cs#L140

All is working fine in Premailer.Net(v1.5.4)/AngleSharp(v0.9.7), but when we migrate to the latest version of Premailer.Net(v2.2.0)/AngleSharp(v0.14.0), empty title tags are converted into self-closing and this breaks in almost all mail clients. There must be regression somewhere between v0.9.7-v0.14.0 of AngleSharp. We really want to upgrade, as the latest version in netstandard-compatible, but this issue is a blocker for us.

**Comment by FlorianRappl** [comment]
There is no regression as there was no `XhtmlMarkupFormatter` in 0.9.

So let's look at the options:

1. Change the specification (no, not possible)
2. Do not follow the specification (really? just because the spec does not fit your use case? what else would we break with this...)
3. Use a custom formatter (e.g., to treat things like `title` differently but rest like XHTML)
4. Prepare the document accordingly (e.g., do not have any empty `title`s)

Don't make your use case our problem. As far as I can see it there is 0 support from you guys (not even a star on GitHub, not to speak of any funding or anything else to foster development). There is also no real community acceptance here (i.e., you want to have some change, which would potentially affect everyone else - just because your use case for whatever reason does not fully fit).

I consider this closed. I hope you guys find a great solution that works out for you!

**Comment by sksk571** [comment]
I'm not saying that it should be changed in the way we need it to work, just trying to point out the possible bug (and producing non-working HTML does look like a bug to me).

There was XhtmlMarkupFormatter in 0.9.7 https://github.com/AngleSharp/AngleSharp/blob/v0.9.7/src/AngleSharp/Xhtml/XhtmlMarkupFormatter.cs

Premailer.Net didn't use it though, so there was no regression in this repo.

**Comment by sksk571** [comment]
Talking about the XHTML specification, while it allows tags to be self-closing:
https://www.w3.org/TR/xhtml1/#h-4.6

There is also a note about compatibility during minimization of empty tags:
https://www.w3.org/TR/xhtml1/#C_3

`
Given an empty instance of an element whose content model is not EMPTY (for example, an empty title or paragraph) do not use the minimized form (e.g. use <p> </p> and not <p />).
`
