### ISSUE TITLE
Parsing inline styles

### ISSUE THREAD

**Issue by tinonetic** [AngleSharp/AngleSharp#934]
Hi,

Thanks for the awesome library! Incredibly powerful.

I am failing to find the right documentation on how to parse in-line styles

I have an `<a>` element with the following structure:

``` html
<a class="my-class" href="https://www.website.com/my-image.jpg" data-title="My Image" style="background-image: url("https://www.website.com/my-image-thumbnail.jpg"); display: block;"><a>
```
I would like to get the `url` value for the `background-image` in the inline `style`

That is, I would like to get `https://www.website.com/my-image-thumbnail.jpg`

Is there support to do so or should I rely on string manipulation after getting the OuterHtml?

Any  help will be appreciated

**Comment by FlorianRappl** [comment]
This is rather a question for `AngleSharp.Css`, but maybe the knowledge that there is something like `AngleSharp.Css` (https://github.com/AngleSharp/AngleSharp.Css) is the actual answer.

Have you tried using AngleSharp.Css? It would parse the inline styles automatically and you can access the CSSOM the "standard way", i.e., using the `Style` property of the element.

**Comment by tinonetic** [comment]
Thank-you. I will try it out
