### ISSUE TITLE
Dataset on IElement is not working

### ISSUE THREAD

**Issue by Mynken** [AngleSharp/AngleSharp#937]
# Bug Report

## Prerequisites

- [Y ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [Y ] Are you running the latest version of AngleSharp?
- [Y ] Did you check the FAQs to see if that helps you?
- [Y ] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [Y ] Did you perform a search in the issues?

## Description

[Description of the bug]

## Code to reproduce:
```
        var str = "https://www.ishopnewworld.co.nz/category/meal-spot?ps=100&pg=1";
        var config = Configuration.Default.WithDefaultLoader();
        var document = await BrowsingContext.New(config).OpenAsync(str);

        var cells = document.QuerySelectorAll(".js-product-card-footer");
        // cells[0].Dataset
 ```

I am trying to parse this div:
![image](https://user-images.githubusercontent.com/11164358/108629709-85c71a80-7461-11eb-91a1-4cdf1b6a5d39.png)

When I am in debug mode - I see property called "Dataset":
![image](https://user-images.githubusercontent.com/11164358/108629736-a8f1ca00-7461-11eb-9d48-1e0e2d5a78e1.png)

But actually I see this property only in debug mode and I can`t evaluate or call this property.
![image](https://user-images.githubusercontent.com/11164358/108629791-dfc7e000-7461-11eb-8c9a-1d33e0893c04.png)

**Expected behavior:** "Dataset" to be callable.

**Actual behavior:** "Dataset" is not avaliable.

**Environment details:** [WIndows10, .Net Framework 4.7.2]

## Possible Solution

Is there any other way to get information from "data-options"?

**Comment by campersau** [comment]
`QuerySelectorAll` returns `IElement`s, try casting it to a `IHtmlElement` then the [`Dataset`](https://github.com/AngleSharp/AngleSharp/blob/3968eb050e142b1d94550fba407afe772232b126/src/AngleSharp/Html/Dom/IHtmlElement.cs#L33-L38) property should be there.

```c#
        var str = "https://www.ishopnewworld.co.nz/category/meal-spot?ps=100&pg=1";
        var config = Configuration.Default.WithDefaultLoader();
        var document = await BrowsingContext.New(config).OpenAsync(str);

        var cells = document.QuerySelectorAll(".js-product-card-footer");
        ((IHtmlElement)cells[0]).Dataset
```
