### ISSUE TITLE
How to use with HttpResponseMessage in UWP?

### ISSUE THREAD

**Issue by moyanming** [AngleSharp/AngleSharp#938]
Hi all,

**Environment details:** [OS, .NET Runtime, ...]
Windows 10 1809, UWP (Universal Windows) project (VS2019), with AngleSharp v0.14.0 NuGet package installed.

Namespace:
https://docs.microsoft.com/en-us/uwp/api/

I want to use Windows.Web.Http.HttpClient class with the AngleSharp.
Does the following is right or not when I want to add the UserAgent header?
`
var EdgeUserAgent = @"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363"
`
![1](https://user-images.githubusercontent.com/13234209/112324444-b7264680-8caa-11eb-8e53-f55b7b37fab8.jpg)

I can't get the right Html source by using the above codes, please see the picture (it seems there need redirection):
![html source](https://user-images.githubusercontent.com/13234209/112322413-cb694400-8ca8-11eb-8fdf-675b5739169c.jpg)

I can get the redirection location from the header of HttpResponseMessage instance just use the HttpClient itself:
![2](https://user-images.githubusercontent.com/13234209/112324493-c2797200-8caa-11eb-8190-6f88d8295660.jpg)

How to use the HttpResponseMessage with AngleSharp?
Any ideas?

Best Regards

**Comment by FlorianRappl** [comment]
Not sure why you give this a label "bug" when its rather a question.

I am not sure I can follow. You start by mentioning that you want to use another requester (Windows.Web.Http.HttpClient) for obtaining the sources, but then your code snippets show  you using the default loader.

If you use a custom requester it must fulfill the `IRequester` interface. If you need guidance to implement that interface have a look at the `HttpClientRequester` from AngleSharp.Io (https://github.com/AngleSharp/AngleSharp.Io/blob/master/src/AngleSharp.Io/Network/HttpClientRequester.cs).
