### ISSUE TITLE
AngleSharp removes first <style> tag from my HTML

### ISSUE THREAD

**Issue by rayrfan** [AngleSharp/AngleSharp#939]
I tried with the latest alpha as well as the stable release when I run the following program to simply let an IDocument take in HTML snippet, then output it through document.Body.InnerHtml. But the result is missing my style tag.

```csharp
using AngleSharp;
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main()
        {
            MainAsync().GetAwaiter().GetResult();
        }

        private static async Task MainAsync()
        {
            string body = @"<style>h1 { font-size: 3 }</style>
<h1>this is a heading</h1>
<style>p { font-size: 1.5rem; line-height: 1.3 }</style>
<p>some text</p>";

            var config = Configuration.Default;
            var context = BrowsingContext.New(config);
            var document = await context.OpenAsync(req => req.Content(body));

            Console.WriteLine(document.Body.InnerHtml);
        }
    }
}
```

The output of the above is, notice the first <style> tag is missing

```html
<h1>this is a heading</h1>
<style>p { font-size: 1.5rem; line-height: 1.3 }</style>
<p>some text</p>
```

The expected is 

```html
<style>h1 { font-size: 3 }</style>
<h1>this is a heading</h1>
<style>p { font-size: 1.5rem; line-height: 1.3 }</style>
<p>some text</p>
```

**Comment by FlorianRappl** [comment]
I am not sure how you reach the conclusion that what you wrote as expected outcome is the right outcome.

I guess you need to read the [HTML spec](https://www.w3.org/TR/html52/).

Long story short; before submitting a bug please check in your browser to have a reference. Its the same behavior as AngleSharp. All good.
