### ISSUE TITLE
Clicking programmatically on elements does not redirect(or doesn't clicks)

### ISSUE THREAD

**Issue by Takoooooo** [AngleSharp/AngleSharp#940]
# Bug Report

## Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description
I am using AngleSharp for some advanced scenarios. I try to click programmatically on the anchor element and I expect to be redirected to another page, but somewhy it doesn't redirect me. I tried executing javascript, calling the DoClick method on IHtmlElement but it doesn't work. If I would execute that js in the console in the browser it would work. Also, I tried running cefsharp and executing such js in CefSharp(i didn't post that bug report in the AngleSharp.Js because it doesn't work with the DoClick method also).In the test cases I haven't found any code what may help me. I tried different ways, different sites but it doesn't redirect me or it doesn't click the elements I need. I think I miss something, help me, please.

## Steps to Reproduce

```
 var config = Configuration.Default
            .WithCss()
            .WithCookies()
            .WithJs()
            .WithDefaultLoader(new LoaderOptions
             {
                 IsNavigationDisabled = false,
                 IsResourceLoadingEnabled = true,
             });
var _context = BrowsingContext.New(config);
var doc = await _context.OpenAsync("https://github.com/AngleSharp/AngleSharp");
doc.ExecuteScript("document.querySelector('a[aria-label=\"Homepage\"]').click()");
(doc.QuerySelector("a[aria-label=\"Homepage\"]") as IHtmlElement).DoClick();//that doesent work also
```

**Environment details:** Win 10

**Comment by FlorianRappl** [comment]
Not sure what your expectation is. The `DoClick` triggers clicking the link. The link is also followed.

```cs
var config = AngleSharp.Configuration.Default
	   .WithDefaultLoader(new LoaderOptions
	   {
		   IsNavigationDisabled = false,
		   IsResourceLoadingEnabled = true,
	   });
var _context = BrowsingContext.New(config);
var doc = await _context.OpenAsync("https://github.com/AngleSharp/AngleSharp");
_context.Active.Title.Dump();
(doc.QuerySelector("a[aria-label=\"Homepage\"]") as IHtmlElement).DoClick();
await Task.Delay(5000);
_context.Active.Title.Dump();
```

Output is:

```txt
GitHub - AngleSharp/AngleSharp: The ultimate angle brackets parser library parsing HTML5, MathML, SVG and CSS to construct a DOM based on the official W3C specifications.
GitHub: Where the world builds software · GitHub
```

**Note**: Clicking the link follows the link. This happens asynchronously. You need to watch the active document changing / loading again. I just added 5s delay to showcase that something *is* happening.
