### ISSUE TITLE
AngleSharp.Dom.IElement.ClassName.get returned null. (System.NullReferenceException: 'Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by sachinbabar83** [AngleSharp/AngleSharp#950]
I am getting System.NullReferenceException: 'Object reference not set to an instance of an object. error with below code

 HtmlParser parser = new HtmlParser();
 IHtmlDocument document = parser.ParseDocument("HTML Data String Here");           
 IEnumerable<IElement> SelectEmement=document.All.Where(x => (x.ClassName.Contains("CssClassname") || x.Id.Contains("ElementID") ));           
  if (SelectEmement.Any())

However if I change like below then it is working
 IEnumerable<IElement> SelectEmement=document.All.Where(x => (x.ClassName =="CssClassname" || x.Id =="ElementID" ));   

Could I get more details why I get null exception when I use contains.  Even i get same exception if I use like below

document.All.Where(x =>x.ParentElement.InnerHtml.Contains(term));

Any help is appreciated.

**Comment by FlorianRappl** [comment]
`Id` is only available if there was an ID. Otherwise its `null`.
