### ISSUE TITLE
Headless device encounter Google SafeSearch-Filter

### ISSUE THREAD

**Issue by moyanming** [AngleSharp/AngleSharp#956]
Hi,

I use the AngleSharp within my headless device which has no UI and has no output display.
When open "www.google.de", there is a SafeSearch-Filter webpage as a result but not the home webpage of the Google search.
Any ideas on how to add a default SafeSearch-Filter, or is there action that can be operated to set on the SafeSearch-Filter webpage?
BTW, it seems that "www.google.co.kr" works fine.

Best Regards

**Comment by moyanming** [comment]
Hi, @FlorianRappl 
Any new information as this issue was closed?

Best Regards

**Comment by FlorianRappl** [comment]
Well it's Question. We close all questions to leave visibility to the issues.

I left it open for so long to increase visibility in case somebody has a good answer for you.
