### ISSUE TITLE
Still have problems while loading websites

### ISSUE THREAD

**Issue by ossaltu** [AngleSharp/AngleSharp#96]
It is related to #92 issue. The related test passes:

```
public async Task ContextLoadAmazonWithCss()
        {
            if (Helper.IsNetworkAvailable())
            {
                var url = "http://www.amazon.com";
                var config = new Configuration().WithDefaultLoader().WithCss();
                var document = await BrowsingContext.New(config).OpenAsync(url);
                Assert.IsNotNull(document);
                Assert.AreNotEqual(0, document.Body.ChildElementCount);
            }
        }
```

but the test itself is not correct, it would pass when exceptions in asyncronious loading of images, css, etc. whould accur.
The correct test would probably be:

```
public async Task ContextLoadAmazonWithCss()
        {
            if (Helper.IsNetworkAvailable())
            {
                var url = "http://www.amazon.com";
                var config = new Configuration().WithDefaultLoader().WithCss();
                var document = await BrowsingContext.New(config).OpenAsync(url);

                await Task.WhenAll(document.Requests);

                Assert.IsNotNull(document);
                Assert.AreNotEqual(0, document.Body.ChildElementCount);
            }
        }
```

Now it fails :)

**Comment by FlorianRappl** [comment]
But that is not the purpose of this test. Otherwise you need to define when exceptions in these requests (e.g. when the resource is not available) are acceptable and when not.

What breaks / what is your specific problem?

**Comment by FlorianRappl** [comment]
I also added the `WhenAll` call - still works for me.

**Comment by ossaltu** [comment]
Today I have some time to dig deeper into this :)
After last code update the test passes, but still getting null ref exceptions when debugging the test:
   at AngleSharp.Dom.Css.CssStyleEngine.Parse(IResponse response, StyleOptions options) in e:\Projects\AngleSharp1\AngleSharp\DOM\Css\CssStyleEngine.cs:line 77
   at AngleSharp.Dom.Html.HtmlLinkElement.<>c__DisplayClassf.<TargetChanged>b__a(Task`1 m) in e:\Projects\AngleSharp1\AngleSharp\DOM\Html\HtmlLinkElement.cs:line 249
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Since there is no resource loading in default loader, request result is always returned as null and than passed to parse:

```
(HtmlLinkElement.cs, 252)
_sheet = engine.Parse(response, options);
```

which results in null ref exception

**Comment by FlorianRappl** [comment]
I see. This will be fixed! Thanks for investigating :+1:
