### ISSUE TITLE
Proposal to drop .NETFramework 4.6 target

### ISSUE THREAD

**Issue by iamcarbon** [AngleSharp/AngleSharp#960]
.NET Framework 4.6 is reaching end of life in April of 2022 and most users should have already updated (or received an automatic update) to at least net462 (covered by the net461 target). 

Is it a good time to drop this target to simplify our build?

**Comment by FlorianRappl** [comment]
Hm, how much would we gain here?

For background: Dropping the .NET Standard 1.3 was "easy" in that regard; apparently not many users (if any) + lots of code that had to be modified just to have it working (which then also impacted the other frameworks...).

In a year the situation will look more clear, right now for me the question is - are there parts in the code that could be done better if we drop 4.6?

**Comment by FlorianRappl** [comment]
Dropped for 0.17.0 / 1.0

Landed in `devel`
