### ISSUE TITLE
Parse only the head from a stream

### ISSUE THREAD

**Issue by MrSmoke** [AngleSharp/AngleSharp#966]
I'll preface this by saying I had a quick look at the docs and couldn't see if something like this existed. If it does, sorry!

# New Feature Proposal

## Description
A new method on `IHtmlParser` which can be used to parse the head of a document and return a `IHtmlHeadElement`.

Maybe something like

```cs
Task<IHtmlHeadElement> ParseHeadAsync(Stream source, CancellationToken cancel);
```

## Background
I have a requirement where I need to pull out some meta tags from the head of a webpage but I don't need to parse the whole document. 

Currently I'm sending the request using a `HttpClient` with `HttpCompletionOption.ResponseHeadersRead` set, then using `ParseDocumentAsync` to get the document. Once I have the document I use `.Head.QuerySelector()` to get my element.

**Comment by FlorianRappl** [comment]
Yeah its a sound proposal. Let me think how it could be achieved in a nice consistent way...

I'll come back with a potential solution!

**Comment by FlorianRappl** [comment]
Landed in `devel` and the preview!
