### ISSUE TITLE
Submitting Javascript built form

### ISSUE THREAD

**Issue by TonyDev314** [AngleSharp/AngleSharp#969]
I've been getting around a javascript created form, by creating the form myself and adding it to the page, and then "finding" the form in the usual way, populating and submitting.

```cs
var queryDocument = await browsingContext.OpenAsync(_url);

var formText = "<form method='POST' id='popup-form'><input type='text' name='user'><input type='password' name='password'><button type='submit' formaction='/login' value='Login'></form>";

var parser = context.GetService<IHtmlParser>();
var formNodes = parser.ParseFragment(formText, queryDocument.Body);
queryDocument.Body.Append(formNodes.ToArray());


var form = queryDocument.QuerySelector<IHtmlFormElement>("#popup-form");
```

etc.
            
While this works well, it's a little messy. It would be preferable to simply submit the form without loading the queryDocument BUT I would want to capture the cookies returned into the browsingContext so that future requests/posts are authorised via the session cookie.

Is there a way to accomplish this?

**Comment by FlorianRappl** [comment]
I'm not sure I can follow.

- Cookies are already preserved, so you don't need to do anything here.
- You can submit a form without constructing an HTML form. The requester allows being used directly.

What do you want to do here? Do you just want to skip re-creating the form in HTML and submit directly? See bullet point 2 - its no problem. Just create a `DocumentRequest` with, e.g., a `POST` method and add the `FormData` directly. It's pretty much the same API as you'd use in JS.

HTH!

**Comment by TonyDev314** [comment]
Thanks for the quick reply. I knew how to submit the form outside of Anglesharp, but I couldn't see how to connect the submission to the browserContext in order to collect the cookies returned. DocumentRequest didn't seem the right object when I first looked at it, because I only browsed the Instance methods - found the static methods which showed it WAS the right object for my purposes!

                var keyValues = new Dictionary<string,string>();
                keyValues.Add("user", account.User);
                keyValues.Add("password", account.Password);

                var request = DocumentRequest.PostAsUrlencoded(new Url(_url), keyValues);

                var queryDocument = await browsingContext.OpenAsync(request);
                
                Thanks for your help!
