### ISSUE TITLE
Trojan found at time to download this code

### ISSUE THREAD

**Issue by bicentennial** [AngleSharp/AngleSharp#972]
# Bug Report
Hello, sorry, i dont know if this is the correct location to report but, just to let you know, this morning at time to try to download zip file of your code my computer reported a trojan was found.. please review your files.
Greetings and thanks for your hard work.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version of AngleSharp?
- [ ] Did you check the FAQs to see if that helps you?
- [ ] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [ ] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the bug]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Environment details:** [OS, .NET Runtime, ...]

## Possible Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Not sure what you mean.

AngleSharp is neither delivered as a ZIP file nor is any trojan included in there.

Please first review your setup before coming up with dubious conclusions.
