### ISSUE TITLE
Unable To Get button from query selector

### ISSUE THREAD

**Issue by mirkojpn87** [AngleSharp/AngleSharp#974]
hi.
i'm trying to click a button on a site, i'm able to do a login but still can't get the button, it return always null.
what i'm missing up?

`            var document = await _context.OpenAsync(URL));
            
            Log("site Opened");
  
            var button =
                document.QuerySelector<IHtmlButtonElement>("#next");

            if( button != null )
            {
                button .DoClick();
            }else
            {
                Log("button not found");
            }`

**Comment by FlorianRappl** [comment]
Are you sure the button is there? Maybe the button will be created via JS. Have a look at the page's HTML code first (e.g., via `document.ToHtml()`.

**Comment by mirkojpn87** [comment]
yes, the button is there.. i'm sure that i'm missing something..

**Comment by mirkojpn87** [comment]
well.. is there and i found a way to get it by doing this 
`            var eelemnts =
                document.GetElementsByTagName("button");

           `
