### ISSUE TITLE
Add an interface for HtmlPictureElement

### ISSUE THREAD

**Issue by Turnerj** [AngleSharp/AngleSharp#977]
# New Feature Proposal

## Description

Many of the other elements have an interface that corresponds with the internal implementation of their element but I noticed that picture doesn't.

## Background

I'm wanting to use it like `myElement is IHtmlPictureElement`.

## Specification

N/A

**Comment by FlorianRappl** [comment]
Yep is fine for me! Thanks for bringing this up.
