### ISSUE TITLE
Replace reflection in `Document.CreateElement<TElement>()`

### ISSUE THREAD

**Issue by Turnerj** [AngleSharp/AngleSharp#979]
# New Feature Proposal

## Description

Currently when calling `document.CreateElement<ISomeElement>()`, it uses reflection to find the element. More than that though, it cycles through every constructor till it finds one that works. If someone is using this on a hot path, this is less than ideal for the allocations and performance it has.

I propose either hard coding it (reasonable but not great for maintenance) or potentially using source generators to create a lookup table for it.

A more radical idea would be to also refactor to be more similar to the other `CreateElement` methods so the logic can be piped through to the appropriate element factory to handle. In these factories, it would still be important to optimize the element creation logic to avoid reflection.

Happy to have a go at fixing this (I've done stuff with source generators in other projects), just need some direction about how far you would want to go with this - whether I build something to keep that extension in-place or refactor to have the element factories to do the logic.

## Background

N/A

## Specification

N/A

**Comment by Turnerj** [comment]
To be clear, this could be as simple as creating a dictionary or switch statement with type-to-tagnames and just pipe it to the existing `document.CreateElement(string)`:

```csharp
public static TElement CreateElement<TElement>(this IDocument document) where TElement : IElement
{
    var tagName = typeof(TElement) switch
    {
        typeof(IHtmlAnchorElement) => TagNames.Anchor,
        ...
        _ => throw new ArgumentException("No element could be created for the provided interface.")
    };

    return document.CreateElement(tagName) as TElement;
}
```

**Comment by Turnerj** [comment]
You could also support namespaces by using a tuple in the switch.

```csharp
        typeof(IHtmlAnchorElement) => (NamespaceNames.HtmlUri, TagNames.Anchor)
```

**Comment by FlorianRappl** [comment]
Well, this is just a convenience method. I'd always recommend using `CreateElement(elementName)` to be used in hot paths. It uses a lookup table.

The explicit solution was not taken due to the maintenance effort. Only a source generator could be helpful here; but then again - would potentially be overkill for a convenience-only solution. Other option is to introduce a lazy loaded dictionary, which just fills when being used. This way only the first call for a specific interface is slow, the second (third fourth ...) ones are fast.

**Comment by Turnerj** [comment]
One of the problems with reflection is that it makes code trimming difficult and potentially buggy. That said, my reasoning for doing this was that I planned to exclusively use interfaces to interact with the DOM. Based on our discussion in #980, I'm going to avoid the interfaces entirely so I won't be using this method.

That the interfaces are meant to correlate to W3C's DOM interfaces, it probably wouldn't be used very heavily as the those interfaces miss a number of common elements so it probably doesn't matter very much.
