### ISSUE TITLE
Potential issue with Source Link configuration

### ISSUE THREAD

**Issue by Turnerj** [AngleSharp/AngleSharp#982]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Was having trouble stepping through some behaviour in my code that went through to AngleSharp. It doesn't seem like Source Link is configured correctly (at least according to the [NuGet Package Explorer app](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer)). This is what I see when opening the AngleSharp NuGet package in it:

![image](https://user-images.githubusercontent.com/904226/122536698-f70b8880-d063-11eb-84bc-efa577ced5be.png)

I don't see anything obviously wrong in the `AngleSharp.Core.csproj` file, at least compared to my own libraries:

![image](https://user-images.githubusercontent.com/904226/122537253-89139100-d064-11eb-9857-a5bcc8ddda48.png)

Not sure if you might have any insights into what is going on? I tried to see if I could get an artifact from the CI to check but it doesn't seem your CI builds store NuGet package artifacts.

**Comment by FlorianRappl** [comment]
Hm not really sure. It might be that - for some reasons - the symbols are not part of the build. I'd need to check.

I'll have a look at this later today / tonight.

**Comment by FlorianRappl** [comment]
Thanks for helping our here @campersau !
