### ISSUE TITLE
BrowsingContext.SetCookie() only sets one cookie while BrowsingContext.GetCookie() might return multiple.

### ISSUE THREAD

**Issue by niobium93** [AngleSharp/AngleSharp#984]
# Bug Report

## Prerequisites

- [yes] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [yes] Are you running the latest version of AngleSharp?
- [yes] Did you check the FAQs to see if that helps you?
- [yes] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [yes] Did you perform a search in the issues?

## Description

BrowsingContext.GetCookie() returns a string containing all cookies for a given url separated by semi-colons. If you store this string and then feed it into a new BrowsingContext using its SetCookie(), only the first cookie actually gets set. I feel like these functions should be symmetrical.

## Steps to Reproduce

1. Get a cookie string using BrowsingContext.GetCookie() and store it somewhere.
2. Start a fresh BrowsingContext
3. Feed the old cookie string into the new SetCookie()

**Expected behavior:** All the cookies in the string get imported.

**Actual behavior:** Only the first cookie in the string got imported.

**Environment details:** Arch Linux, .Net 5.0.7.sdk204

## Possible Solution

I deal with it like this:
`               string allCookies = await File.ReadAllTextAsync(cookiePath);
                foreach (string cookie in allCookies.Split("; "))
                {
                    context.SetCookie(url, cookie);
                }`
I feel the SetCookie() function should do this itself.

**Comment by FlorianRappl** [comment]
Hm have you compared this with the behavior in a browser?

I ask because the design decision for `GetCookie`, `SetCookie` has not been arbitrarily made, but follows the W3C algorithms. The cookie behavior in there is a bit strange (which is why we recommend to use a proper cookie container for doing real work here - going against the container's API, which will be much better and more fine-grained than the string manipulation that you'd need to do otherwise).

**Comment by niobium93** [comment]
Sorry, I didn't know it was meant to match browser behavior. How do I use a cookie container with AngleSharp?

**Comment by FlorianRappl** [comment]
Yes, its written quite explicitly in the "Vision" part of the README. This section gives the direction for any implementation: https://github.com/AngleSharp/AngleSharp#vision

In any case you can just obtain the container via `context.GetService<ICookieProvider>`. If you want to access the .NET Cookie Container (assuming you've used `MemoryCookieProvider`) you can also use `context.GetService<MemoryCookieProvider>().Container`.

Example:

```cs
var url = Url.Create("http://example.com");
var context = BrowsingContext.New(Configuration.Default.WithDefaultCookies());
var cookieContainer = context.GetService<MemoryCookieProvider>();//.Container;
cookieContainer.GetCookie(url).Dump(); // empty
cookieContainer.SetCookie(url, "foo=bar, qxz=fooo, first=second");
cookieContainer.GetCookie(url).Dump(); // foo=bar; qxz=fooo; first=second
```

Hope this helps!

**Comment by niobium93** [comment]
It does! Thank you!
