### ISSUE TITLE
OpenAsync fails to load urls with underscores in the hostname.

### ISSUE THREAD

**Issue by AustrianFields** [AngleSharp/AngleSharp#987]
# Bug Report

```c#
var document = await context.OpenAsync("https://broken_url.bdsmlr.com/");
```
Trying to load an url like that silently fails and returns an empty document. The url loads in a browser though. (Tested in Firefox 89) That is a dummy url, but that site has lots of actual blogs with underscores in their title. Rest of the site is very NSFW! I know underscores in hostnames is technically against spec, but browsers don't mind and urls like that exist in the wild so I think AngleSharp should load them too. 

One thing to note is that even HttpClient fails to load these urls because of some SSL exception. Disabling certificate validation makes it work:
```c#
using (var handler = new HttpClientHandler())
{
    handler.ServerCertificateCustomValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;

    using (var client = new HttpClient(handler))
    {
        HttpResponseMessage response = await client.GetAsync("https://broken_url.bdsmlr.com/");
        Console.WriteLine(response.StatusCode);
    }
}
```

**Comment by FlorianRappl** [comment]
I don't think that this is an issue. Since you did not show the full code I suspect you configured AngleSharp wrong.

![grafik](https://user-images.githubusercontent.com/1766191/123917169-c5a78c80-d982-11eb-9f7b-4452ab03bbe1.png)

URL loads without a problem (`IsInvalid` is `false`).

**Comment by AustrianFields** [comment]
Url.Create works fine for me too. Here's all of my code:
```c#
using System;
using System.Threading.Tasks;
using AngleSharp;
using AngleSharp.Dom;
using AngleSharp.Io;

namespace AngleSharpFiddle
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var config = Configuration.Default.WithDefaultLoader();
            var context = BrowsingContext.New(config);

            Url url = new Url("https://broken_url.bdsmlr.com/");

            var req = new DocumentRequest(url);
            var document = await context.OpenAsync(url);

            Console.WriteLine(document.Body.ChildElementCount);

            var loader = context.GetService<IDocumentLoader>();
            var download = loader.FetchAsync(req);
            var response = await download.Task.ConfigureAwait(false);

            Console.WriteLine(response == null);
        }
    }
}

```
This outputs:
```
0
True
```
If I change the url to "https://good-url.bdsmlr.com/" the output changes to:
```
6
False
```
In a browser both urls load the exact same page.

**Comment by FlorianRappl** [comment]
This may be more a limitation of `WebRequest` than AngleSharp. Try using the requesters from AngleSharp.Io.

**Comment by AustrianFields** [comment]
I'm confused. Is there any other requester besides DefaultHttpRequester? Should I attempt to make my own? Is there any example somewhere?
I tried this but the response is null just like before:
```c#
var request = new Request();
request.Address = url;
var requester = new DefaultHttpRequester();
response = await requester.RequestAsync(request, new System.Threading.CancellationToken());
```

**Comment by FlorianRappl** [comment]
> Is there any other requester besides DefaultHttpRequester

Yes, that's what I wrote...

> Try using the requesters from AngleSharp.Io.

https://github.com/AngleSharp/AngleSharp.Io

**Comment by AustrianFields** [comment]
I figured it out! Here's what I did:
```c#
using System;
using System.Net.Http;
using System.Threading.Tasks;
using AngleSharp;
using AngleSharp.Dom;

namespace AngleSharpFiddle
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true
            };

            var config = Configuration.Default.WithRequesters(handler).WithDefaultLoader().WithDefaultCookies();
            var context = BrowsingContext.New(config);

            Url url = new Url("https://broken_url.bdsmlr.com/");

            var document = await context.OpenAsync(url);

            Console.WriteLine(document.Body.ChildElementCount);
        }
    }
}
```
