### ISSUE TITLE
Tracing/Logging

### ISSUE THREAD

**Issue by qudooschaudhry** [AngleSharp/AngleSharp#989]
Hi

While troubleshooting some performance issues, one of our APM+ tool indicates that AngleSharp is doing some System.Diagnostics logging and sometimes some of those threads are being locked. Perhaps we are using it incorrectly. I just have a question if indeed AngleSharp is doing any sorts of tracing/logging and if we are able to turn it off somehow?

Thanks for the help.

**Comment by FlorianRappl** [comment]
We are indeed writing out some exceptions (alternative would be to silently swallow them), e.g., https://github.com/AngleSharp/AngleSharp/blob/0bee862e8aa61fe3ace84068113d2e97a77beb32/src/AngleSharp/Io/MemoryCookieProvider.cs

IIRC this is it pretty much. There is no way to disable it directly that I'm aware of; its indirectly disabled by .NET as `System.Debug` only writes out in debug mode.

**Comment by qudooschaudhry** [comment]
Thanks.
