### ISSUE TITLE
CSS parser failed to recoganize media query and the rules defined afterwards

### ISSUE THREAD

**Issue by D92130** [AngleSharp/AngleSharp#99]
Using following code for stylesheet parsing testing:

```
        var sheet = ParseStyleSheet(@".mobile,.tablet{display:none;} @media only screen and(max-width:51.875em){.tablet{display:block;}} .disp {display:block;}");
        var sheet2 = ParseStyleSheet(@"@media only screen and(max-width:51.875em){.tablet{display:block;}} .mobile,.tablet{display:none;} .disp {display:block;}");
        var sheet3 = ParseStyleSheet(@".mobile,.tablet{display:none;} .disp {display:block;} @media only screen and(max-width:51.875em){.tablet{display:block;}}");
```

The end result:

sheet.Rules.Length: 1
sheet2.Rules.Lenght: 0
sheet3.Rules.Lenght: 2

**Comment by FlorianRappl** [comment]
Thanks for the report. This will of course be fixed.

**Comment by FlorianRappl** [comment]
Quick question: Does the code you use contain an error on purpose? There is a space missing between the `and` and the `(` in the media query. If you look at how browsers interpret you will see that the media query is detected as invalid and ends up as `not all`.

Either way - this does not make the bug invalid. The behavior still needs to be fixed.

**Comment by D92130** [comment]
Thanks for looking into the issue. No, it is not on purpose.  I just took the snippet from a website stylesheet that I had problem parsing with AngleSharp.
