### ISSUE TITLE
a new series of lex/yacc tools

### ISSUE THREAD

**Issue by xp44mm** [AngleSharp/AngleSharp#990]
A compiler cannot be written without compiler tools, I am very pleased to invite you to try a new series of lex/yacc tools.

`FSharpCompiler` is a generic compiler generator written in F# language. 

Its rules do not contain semantic actions, so it is programming language independent. you can use any language you are familiar with to write your compiler.

You can iteratively apply regular expressions or context-free grammar to syntax sequences using combination approachs. Using it is as easy as `Regex`.

The open source see to:  [xp44mm/FSharpCompiler](https://github.com/xp44mm/FSharpCompiler)

**Comment by FlorianRappl** [comment]
While interesting (and cool) project I'd regard this as an ad ;).

Nevertheless, even though I'll close the (unrelated to AngleSharp) issue I won't delete it.
