### ISSUE TITLE
Node.ToHtml never writes IProcessingInstructions via IMarkupFormatter.Processing

### ISSUE THREAD

**Issue by jgmamxmn** [AngleSharp/AngleSharp#991]
# Bug Report

## Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Node.ToHtml works by testing each Node object against various interfaces (IComment, ICharacterData, etc.) to determine how to write it (i.e. which method to call from the provided Markup Formatter object).

The implementation of IProcessingInstruction is class ProcessingInstruction. ProcessingInstruction is a subclass of CharacterData, therefore implements ICharacterData.
Therefore, if a ProcessingInstruction instance is tested against "is IChararacterData", the result will be true.

In the current Master code, "is ICharacterData" is tested BEFORE "is IProcessingInstruction", therefore ProcessingInstructions are treated as ICharacterData objects and the code specifically for IProcessingInstructions (a subsequent branch in the if-else list) is never reached.

The fix is to test for "is IProcessingInstruction" BEFORE testing "is ICharacterData".

The exact same consideration applies for IComment (class Comment is also a subclass of CharacterData), but that test already preceded the ICharacterData test, so there was no issue there.

(This is my first ever PR, please be kind)

## Steps to Reproduce

1. Parse a document that contains processing instructions.
2. Output the content via ToHtml

(issue occurs irrespective of the markup formatter, if any, passed to ToHtml, since the issue is in Node.ToHtml itself)

**Expected behavior:** 

Processing instructions are rendered as processing instructions
e.g. &lt;?instruction param="value"?&gt;

**Actual behavior:** 

Processing instructions are rendered incompletely, seemingly via Text or LiteralText.
e.g. param="value"
(opening & closing tags, and tag name, missing)
or, if there are no parameters to the processing instruction, there is nothing output at all for the node.

**Environment details:**
N/A

## Possible Solution

Re-order the tests in Node.ToHtml so that "is IProcessingInstruction" is tested before "is ICharacterData".

**Comment by FlorianRappl** [comment]
> The fix is to test for "is IProcessingInstruction" BEFORE testing "is ICharacterData".

Sounds good to me - a PR would indeed be appreciated!

Thanks for detecting and writing it altogether. Superb work :beers:!
