### ISSUE TITLE
After upgrade from 0.15.0 to 0.16.0     System.MissingMethodException : Method not found: 'Boolean AngleSharp.Text.CharExtensions.IsOneOf(Char, Char, Char)'.

### ISSUE THREAD

**Issue by AFAde** [AngleSharp/AngleSharp#993]
# Bug Report

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description
I use AngleSharp in combination with bUnit to test Blazor UI-Components
After upgrading to the version 0.16.0 I get the following error when calling the extension method _Find(this IRenderedFragment renderedFragment, string cssSelector)_ on a rendered fragment

Stack trace
    CssTokenizer.NumberStart(Char current)
    CssTokenizer.Get()
    CssBuilder.CreateDeclarationWith(ICssProperties properties, CssToken& token)
    CssBuilder.FillDeclarations(CssStyleDeclaration style, CssToken token)
    <>c__DisplayClass23_0.<ParseDeclaration>b__0(CssBuilder b, CssToken t)
    CssParser.Parse[T](String source, Func`3 create)
    CssParser.ParseDeclaration(String declarationText)
    CssStyleDeclaration.Update(String value)
    ElementCssInlineStyleExtensions.CreateStyle(IElement element, String source)
    ElementCssInlineStyleExtensions.CreateStyle(IElement element)
    <10 more frames...>
    HtmlDomBuilder.InBody(HtmlToken token)
    HtmlDomBuilder.Home(HtmlToken token)
    HtmlDomBuilder.Consume(HtmlToken token)
    HtmlDomBuilder.Parse(HtmlParserOptions options)
    HtmlParser.ParseFragment(HtmlDocument document, IElement contextElement)
    HtmlParser.ParseFragment(String source, IElement contextElement)
    BunitHtmlParser.Parse(String markup) line 65
    RenderedFragment.get_Nodes() line 76
    RenderedFragmentExtensions.Find(IRenderedFragment renderedFragment, String cssSelector) line 29

## Steps to Reproduce

1. Create an object of type IRenderedFragment
2. Call the extension method Find("mySelector")

**Expected behavior:** [What you expected to happen]
The method returns the expected control

**Actual behavior:** [What actually happened]
Exception 

**Environment details:** [OS, .NET Runtime, ...]
Windows, .NET 5

**Comment by FlorianRappl** [comment]
I think you hit the wrong repository. Also is 0.16 compatible with bUnit at all? Please check first there!

(From the stack trace it seems you want to use AngleSharp 0.16 with AngleSharp.Css pre-0.16 (e.g., 0.15). These are not compatible - the NuGet dependency also reflects that.)

Thanks!

**Comment by AFAde** [comment]
I am sure I hit the right repository. The stack trace clearly shows that the error comes from the AngleSharp library. Could you please at least address me to the where the root cause of the issue could be? I doubt that the root cause is in bUnit

**Comment by campersau** [comment]
bUnit currently uses an older version of anglesharp which looks incompatible to 0.16.0 according to the exception.

[From the changelog](https://github.com/bUnit-dev/bUnit/blob/main/CHANGELOG.md) it looks like the next bUnit version will also [use anglesharp 0.16.0](https://github.com/bUnit-dev/bUnit/pull/427) so you would need to wait for that I guess.

> Updated AngleSharp and related libraries to 0.16.0.

**Comment by AFAde** [comment]
@campersau  Thanks a lot, I did not know exactly where to look at. I will then wait for the next bUnit version before upgrading anglesharp to the 0.16 version
