### ISSUE TITLE
self-closing parse

### ISSUE THREAD

**Issue by wuyu8512** [AngleSharp/AngleSharp#994]
## Description

I am doing some work for the parse epub, he uses the xhtml format

## Steps to Reproduce

1. [HTML]
```
<html>
<head><head/>
<body>

<p>即使到了現在，女學院的錄取率仍跟寶塚<a class="duokan-footnote" epub:type="noteref" href="#note1" id="r_note1"><sup><img alt="note" src="../Images/note.png" /></sup></a>一樣。</p>
<aside epub:type="footnote" id="note1">
	<a href="#r_note1"></a>
	<ol class="duokan-footnote-content" style="list-style:none">
		<li class="duokan-footnote-item" id="note1">註：寶塚音樂學校，錄取率極低，入學平均錄取率約為5％</li>
	</ol>
</aside>

<body/>
<html/>
```
2. [Code]
```
var Config = Configuration.Default.WithCss().WithJs();
var  Context = BrowsingContext.New(Config);
var HtmlParser = Context.GetService<IHtmlParser>();

var html = File.ReadAllText("html.txt");
Console.WriteLine(html);
Console.WriteLine("-------------------------");

var doc = HtmlParser.ParseDocument(html);
html = doc.ToHtml(AngleSharp.Xhtml.XhtmlMarkupFormatter.Instance);
Console.WriteLine(html);

Console.WriteLine("-------------------------");

doc = HtmlParser.ParseDocument(html);
html = doc.ToHtml(AngleSharp.Xhtml.XhtmlMarkupFormatter.Instance);
Console.WriteLine(html);
```

**The final output:**
```
<html><head>
</head><body>

<p>即使到了現在，女學院的錄取率仍跟寶塚<a class="duokan-footnote" epub:type="noteref" href="#note1" id="r_note1"><sup><img alt="note" src="../Images/note.png" /></sup></a>一樣。</p>
<aside epub:type="footnote" id="note1">
        <a href="#r_note1" />
        <ol class="duokan-footnote-content" style="list-style:none">
                <li class="duokan-footnote-item" id="note1">註：寶塚音樂學校，錄取率極低，入學平均錄取率約為5％</li>
        </ol>
</aside>


</body></html>
```
```
<html><head>
</head><body>

<p>即使到了現在，女學院的錄取率仍跟寶塚<a class="duokan-footnote" epub:type="noteref" href="#note1" id="r_note1"><sup><img alt="note" src="../Images/note.png" /></sup></a>一樣。</p>
<aside epub:type="footnote" id="note1">
        <a href="#r_note1">
        <ol class="duokan-footnote-content" style="list-style:none">
                <li class="duokan-footnote-item" id="note1">註：寶塚音樂學校，錄取率極低，入學平均錄取率約為5％</li>
        </ol>
</a></aside><a href="#r_note1">


</a></body></html>
```

You can see that the a tag is misplaced, Is there any way to solve this issue?

**Comment by wuyu8512** [comment]
I read `XhtmlMarkupFormatter` and it seems that it only needs to be changed ` selfClosing || !element.HasChildNodes` to `selfClosing && !element.HasChildNodes`

**Comment by FlorianRappl** [comment]
Sorry, this is no issue. What you do here is:

- Parse HTML (which contains some invalid parts, but let's ignore that)
- Output as XHTML
- Parse XHTML as HTML

The third part is where you go into the wrong direction. You cannot parse XHTML as HTML. It's not the same. Likewise, HTML is not round-trip preserving so even `STRING(PARSE(HTML))` will not be `HTML` again, which may even result that `PARSE(STRING(PARSE(HTML)))` is not the same as `PARSE(HTML)`.

Hope that helps!

**Comment by wuyu8512** [comment]
I now have a requirement that needs to be parsed and formatted repeatedly
And i don't know when is the last
Do you have any good suggestions, or are there any options to parse xhtml?

**Comment by FlorianRappl** [comment]
> Do you have any good suggestions, or are there any options to parse xhtml?

It's based on XML, so using the XML Parser from `AngleSharp.Xml` could be a good starting point. Still, there may be some deviating rules (esp. for scripts), see https://dev.w3.org/html5/spec-LC/the-xhtml-syntax.html so I don't know if everything works out fine. You should definitely enable loose mode, as in the default (strict) mode XML will throw on errors, which is definitely not as desired / given in XHTML.
