### ISSUE TITLE
AngleSharp moving form closing tag to the same line it opens

### ISSUE THREAD

**Issue by jwarlima** [AngleSharp/AngleSharp#998]
Hello, i have the following cenario.

This code came from an ASP file that we're trying to modernize. Once we ParseFragment, the AngleSharp add a tbody tag to the table and close my form tag after the oppening form tag, any idea of how to solv this issue? 

Thanks in advance!

**Code before AngleSharp**
![image](https://user-images.githubusercontent.com/7834703/131889148-635cba85-0acd-42f3-b045-11ecd9ad032d.png)

**Code after AngleSharp**
![image](https://user-images.githubusercontent.com/7834703/131888958-3f0a7e98-38ef-4af5-8c4e-1893a82782e5.png)

![image](https://user-images.githubusercontent.com/7834703/131889032-c97953b0-43a7-4945-936e-541019b199cc.png)

As i don't know much from this library yet, can anyone tell me what i'm missing?

**Comment by campersau** [comment]
I guess `<form>` between `<table>` and `<tbody>` is invalid. Just wrap the `<form>` around the whole `<table>`:

```html
<form><table><tbody><tr><td></td></tr></tbody></table></form>
```

https://dotnetfiddle.net/WeyUxp

**Comment by FlorianRappl** [comment]
Hi @jwarlima  this is standard behavior. Your browser does the same. Its by the spec.
